### ISSUE TITLE
incorrect bridging angle detected

### ISSUE THREAD

**Issue by Jerrill** [alexrj/Slic3r#1003]
I'm trying to slice the chainmail example on Thingiverse here:

http://www.thingiverse.com/thing:31234

However, when it comes time to bridge the upper edges of the links, slic3r detects the wrong angle for the bridge as shown below. The left is the next lower layer. The right is the bridging layer. The bridge extrudates should be running vertically.

![slic3r-error](https://f.cloud.github.com/assets/1562364/165328/83783934-7939-11e2-93e1-329e261289a3.png)

**Comment by lordofhyphens** [comment]
According to @Mikk36 it's  been fixed by now.
