### ISSUE TITLE
Feature Request: Stop extruding for set length before Travel move

### ISSUE THREAD

**Issue by luke321** [alexrj/Slic3r#1005]
I am currently fighting with ooze from my bowden extruder trying different retraction lengths and z lifts but still making little ooze drops.

I tried really high Z moves without retraction to get a feeling how much additional filament is extruded by the spring tension of the filament and noticed that for me it's always about the same amount so:

Would it be possible to stop extruding for a set length before doing a travel move without retracting, the spring tension in the bowden would press filament out further and retraction could be lowered. 
To compensate for the used spring tension in the next print move we could simply use the extra length on restart option.

**Comment by lordofhyphens** [comment]
This is pressure advance. Closing.

**Comment by o-jasper** [comment]
Was confused a bit, ftr "pressure advance" is a concept, [mentioned in for instance release notes 1.2.2](http://slic3r.org/releases/1.2.2).
