### ISSUE TITLE
Feature Request -- z-riveting/knitting infill

### ISSUE THREAD

**Issue by drf5n** [alexrj/Slic3r#1010]
It might add strength to knit along Z during infill. 

If infill left divots or trenches a couple layers deep and then filled them in during successive layers, you could get some welding along the vertical plane while the molten plastic filled the holes.

I've not tested this, maybe I'll experiment with extruding some rivets into holes.

**Comment by lordofhyphens** [comment]
@drf5n  So, anything interesting from experiments? Going to close this for now; if you want to investigate this more, go ahead and reopen the github issue.
