### ISSUE TITLE
pimples are still here !

### ISSUE THREAD

**Issue by jfpion** [alexrj/Slic3r#1037]
there is less but still.....

![granules](https://f.cloud.github.com/assets/1093595/221941/d9e25b94-85ad-11e2-81b8-e3b17ee6073c.jpg)
it's where the perimeters start and end 

it will be a good thing to add the start and end inside the wall instead of just on the perimeter

thnak you

**Comment by nophead** [comment]
I finally managed to get in touch with Adrian and from the date in the Java host source code I was able to find the blog post. http://blog.reprap.org/2009/07/build-quality.html

**Comment by bubnikv** [comment]
Cool, so now we have a prior art and we may experiment with the idea. Now, will this be useful? How to handle multi-perimeter prints? Will it work for inner perimeters first? Would it require a special way to plan the inner perimeters, so there is a space for the inside/outside kink after the inner perimeter is printed?

**Comment by VanessaE** [comment]
It would "seam" ( :stuck_out_tongue_closed_eyes: ) that we don't need to worry about the patent anymore: http://www.cafc.uscourts.gov/sites/default/files/opinions-orders/15-1769.Opinion.9-28-2016.1.PDF

(Short version:  software patents are unconstitutional in the US, by way of the 1st amendment)

**Comment by lordofhyphens** [comment]
That's going up to SCOTUS.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.
