### ISSUE TITLE
Feature Request: Per-extruder print speeds & other UI refactoring

### ISSUE THREAD

**Issue by dognotdog** [alexrj/Slic3r#1064]
I've started printing with a dual extruder setup, and PVA/PLA in the same print, and as it is, the PVA seems to require lower print speeds than the PLA to adhere to the bed and itself properly. Alas, it'd be nice to be able to set the print speeds separately for each extruder.

Also, in this light, "bed temperature" as a part of the filament filament settings seems misplaced, though I have no idea as to where to actually put it that'd make better sense, for all use cases.

**Comment by lordofhyphens** [comment]
Between this and modifier meshes, you can already make the changes you are looking for (and save them to profiles). Going to close this :)
