### ISSUE TITLE
Feature Request: Custom G-code between sequentially printed objects

### ISSUE THREAD

**Issue by c-born** [alexrj/Slic3r#1065]
When objects from the plater are completed individually, it could be useful to be able to insert custom G-code before each new object is started.
A couple of things I would like to have been able to add this way:
1) Wait for bed temperature to return to first-layer temperature
2) Home Z-Axis

The reason for 2) is a bit of a kludge fix, but on occasion I've left a run of 6 or 9 sequentially printed objects, of over an hour each, to print overnight, only to find that after the first or second the machine hasn't fully returned to Z0, and the remaining objects have been printed on air just above the plate. The proper fix is to find the cause (mechanical slippage, stepper slippage, firmware, something giving it a bit of a knock...) but that could take some time, while re-homing Z would give each object a fresh start.

[Edit: It turned out that there was a slightly tighter region on the Z axis screw which caused the stepper to slip when going up at high speed between objects, although not at normal speed when driving manually. A drop of oil fixed it.
Adding Z-axis home between jobs would also have "fixed' it, but masked the real problem.
I still think the ability to add custom G-code could be useful though!]

**Comment by lordofhyphens** [comment]
https://github.com/alexrj/Slic3r/pull/3275 fixes this. Closing.

**Comment by lordofhyphens** [comment]
@alexrj implemented this in bc96a1a268674b2b88edf9b9987d638ee6d9f800
