### ISSUE TITLE
Feature Request - Config File Based on Layer Height

### ISSUE THREAD

**Issue by jcaywood** [alexrj/Slic3r#1081]
I've been playing with the variable layer height feature in 0.9.9 and it's pretty cool. I think it would be pretty functional to also have a 4th column in that setup screen where you could choose an alternate print setting configuration allowing one to not only change the layer height, but also every other option available for print settings configurations (including layer height).

Thanks for everyone's hard work on Slic3r!

**Comment by lordofhyphens** [comment]
We've got an OpenJSCAD and OpenSCAD script in the utils dir to generate simple modifier meshes. Closing :)
