### ISSUE TITLE
extra perimeters with large nozzle and custom extrusion width

### ISSUE THREAD

**Issue by Jerrill** [alexrj/Slic3r#1097]
I'm slicing for a 0.80 mm nozzle. If I have a custom extrusion width of 1.0 mm a 2.1 mm ring has 2 perimeters. In the upper cylinder portion of the model there's a small gap but it works. If I change to something like 1.2 mm or 1.3 mm then I end up with a third perimeter and the the layer is way over extruded when it prints.

I've posted all the relevant files to reproduce the issue here.

https://github.com/Jerrill/files-for-issues/tree/master/slic3r-0.9.9-release/00

**Comment by lordofhyphens** [comment]
That STL is actually being detected as 2 separate meshes that are interspersed, not as a single piece. 

I'm not seeing a third perimeter with bad.ini though. Closing.

**Comment by lordofhyphens** [comment]
Not seeing the issue with current version of slic3r, and the model has some oddities with it (it's actually two meshes, not one).
