### ISSUE TITLE
Block when exporting gcodes

### ISSUE THREAD

**Issue by avalero** [alexrj/Slic3r#1101]
It gets blocke when exporting gcode for any STL

; generated by Slic3r 0.9.9 on 2013-04-07 at 10:32:41

; layer_height = 0.15
; perimeters = 3
; top_solid_layers = 0
; bottom_solid_layers = 6
; fill_density = 0
; perimeter_speed = 30
; infill_speed = 30
; travel_speed = 80
; nozzle_diameter = 0.25
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.35mm
; infill extrusion width = 0.35mm
; solid infill extrusion width = 0.35mm
; top infill extrusion width = 0.35mm
; first layer extrusion width = 0.40mm

**Comment by lordofhyphens** [comment]
It's really slow, even on 1.3.0-dev. Although I think it's excused a bit by being 867 layers of 30% hexagonal infill. Wow.

**Comment by bubnikv** [comment]
This is an interesting problem. Sometimes the g-code export really stalls indefinitely or for extremely long. I currently don't have a good explanation of this effect. Maybe it is a result of to many tiny string operations over a huge text block over and over, maybe it is a concatenation of text bit by bit?

**Comment by lordofhyphens** [comment]
Yeah, I don't know what is going on, but his test case does export when I reduced the infill; just took a long time (and generated a 34M gcode file). So it's not getting into an infinite loop or something. 

It's probably the numerous additive string operations (all the methods in GCode and GCodeWriter return strings).

**Comment by lordofhyphens** [comment]
Closed as it just takes a while, not freezing the program. We have another issue for slow gcode writing.
