### ISSUE TITLE
Random start points even though random start point has been disabled.

### ISSUE THREAD

**Issue by dreamscape74** [alexrj/Slic3r#1116]
Currently, the gcode created accommodates random start point even though settings have been disabled. Discussed this with Alex J, it is doing what it is suppose to do to balance Z axis. If possible when disabled, start points should be on the same X,Y points. Thus reducing "z blobs" all over the print.

**Comment by lordofhyphens** [comment]
@dreamscape74 is it still doing that for you?

**Comment by alexrj** [comment]
No feedback, but this is correct now.
