### ISSUE TITLE
Feature request: dynamically reduce thread count on huge models

### ISSUE THREAD

**Issue by PxT** [alexrj/Slic3r#1117]
As mentioned in #1080, the pre-compiled Slic3r just crashes on Mac OS when slicing very large STLs because it runs out of memory (even on my 16GB machine!).  It would be great if there was logic that automatically reduced the thread count for very large STLs.

Con: slower slicing
Pro: program doesn't crash, user is happy

**Comment by lordofhyphens** [comment]
Is this still a problem? Since there's no test case here going to close. Please reopen with appropriate information to permit reproduction if you are still seeing issues.

**Comment by PxT** [comment]
Not able to reproduce with v1.2.9
