### ISSUE TITLE
Slic3r 0.9.9 perl error

### ISSUE THREAD

**Issue by GeorgeWag** [alexrj/Slic3r#1126]
07:05:44.975 : <Slic3r> Attempt to free unreferenced scalar: SV 0x11fdfee8, Perl interpreter: 0x9e496b8 at C:/PROGRA~1/Repetier-Host-Solidoodle/Slic3r/lib/std/Slic3r.pm line 83

I have installed the latest version of Slic3r and I get this Attempt to free unreferenced scalar error during the slicing operation. The memory addresses and line numbers are not always the same as the above example. I don't know if it affects results, but I never got this error line with the older version I was using.

Thanks,
George

**Comment by kengdahl** [comment]
Same issue on ubuntu 15.04

**Comment by lordofhyphens** [comment]
kengdahl, 0.9.9 is pretty old, as shown by the fact that the previous post was 2 years ago. Are you running into this issue on 1.1.7 or 1.2.7?

**Comment by kengdahl** [comment]
2015-05-27 15:38 GMT+02:00 Joseph Lenox <notifications@github.com>:

> 1.2.7


1.2.7

Kristoffer Engdahl
3D Printer Technician
Arduino Verkstad <http://verkstad.cc/>
+46 (0) 708 97 42 58

**Comment by lordofhyphens** [comment]
Also, are you compiling yourself or using one of the precompiled packages?

I have 1.2.7 debian package source at my fork (http://github.com/lordofhyphens/Slic3r), see if you still have problems.

**Comment by kengdahl** [comment]
Den 27 maj 2015 17:31 skrev "Joseph Lenox" <notifications@github.com>:

> Also, are you compiling yourself or using one of the precompiled packages?
>
> I have 1.2.7 debian package source at my fork (
> http://github.com/lordofhyphens/Slic3r
> <https://github.com/lordofhyphens/Slic3r>), see if you still have
> problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexrj/Slic3r/issues/1126#issuecomment-105960631>.
>
Compiling myself

**Comment by lordofhyphens** [comment]
Cpan can introduce weird problems with debian based distros, usually with
dependencies. This is experience talking.

I would use the source from my fork and build a package for it or use the
prebuilt 1.2.7. I don't know where it is for Ubuntu though.

On May 29, 2015 6:37 AM, "Kristoffer Engdahl" <notifications@github.com>
wrote:
>
> Den 27 maj 2015 17:31 skrev "Joseph Lenox" <notifications@github.com>:
>
> > Also, are you compiling yourself or using one of the precompiled
packages?

**Comment by kengdahl** [comment]
I will try it, this weekend. thank you

**Comment by lordofhyphens** [comment]
@kengdahl 1.3.0-dev (and 1.2.10-dev) has quite a few new fixes and should just build from source without wrecking things in your distro so long as you install the local::lib package first (package name is liblocal-lib-perl) 

Going to close this. If @GeorgeWag can reproduce his issue on 1.3.0-dev (see newest of https://bintray.com/lordofhyphens/Slic3r/slic3r_dev), I will reopen.
