### ISSUE TITLE
Feature request: tie "Solid infill every N layers" to fill density.

### ISSUE THREAD

**Issue by rsilvers129** [alexrj/Slic3r#1129]
If I do a 0.4 fill density with honeycomb, that 0.4 will determine the width of the honeycombs. It would be nice if the solid infill option would then be as many layers high as to match that honeycomb width, or else I need to think too much about the layer thickness and how many layers I want to print before doing a solid infill.

So maybe have an "automatic" checkbox which matches it to what the honeycomb width would be (even if honeycomb is not selected).

**Comment by lordofhyphens** [comment]
If you set up a STL you can get this with modifier meshes; just intersect it with the model. 
I've added a PR with a utility OpenSCAD design to do just that. Just change your infill to rectangular/100% for the modifier mesh and you are good to go.
