### ISSUE TITLE
Option for improving perimeter + infill sticking together

### ISSUE THREAD

**Issue by MLWORKX** [alexrj/Slic3r#1144]
When printing everything's fine BUT on some circumstances the perimeter do not stick perfectly together and the perimeters sometimes do not stick on the infill.

My suggestion therefore:
- add an option how wide (mm and %) the perimeters should overlap
- add an option how wide the infill should overlap on the perimeters

Would be very usefull and make Slic3r so much more professional!
(I really print a lot and create professional parts for industrial purposes - therefore I really need a high sophisticated machine and software with some little more possibility to change the algorithm of slicing)

**Comment by alexrj** [comment]
Done, we now have an option for this. Thank you!
