### ISSUE TITLE
0.9.9 on OSX gives Perl error when adding STL then crashes on export gcode

### ISSUE THREAD

**Issue by jharlap** [alexrj/Slic3r#1169]
Using 0.9.9 on OSX, when adding the STL from http://www.thingiverse.com/thing:6703 (direct download link: http://www.thingiverse.com/download:20602), the following error occurs twice:

![screen shot 2013-05-13 at 10 25 26 am](https://f.cloud.github.com/assets/108388/501125/6cea49e4-bc8e-11e2-87f2-970f32aad276.png)

Dismissing the error message and hitting Export G-Code leads to a full crash. The last message I see in the progress bar is "Generating perimeters".

Config: https://gist.github.com/jharlap/5a1256d39936ff640aa2
Crash log: https://gist.github.com/jharlap/fa4f23dbb871bef32bc6

The same behaviour was observed with several other STLs, all of which work fine with 0.9.8.

**Comment by alexrj** [comment]
This can be closed as of Slic3r 1.2.9.
