### ISSUE TITLE
Invisible STL models in Slic3r viewer, still get sliced successfully.

### ISSUE THREAD

**Issue by woodsmoke** [alexrj/Slic3r#1187]
Slic3r 0.9.9, Win 7, M11x Alienware.

The X carriage from this Prusa set: http://www.thingiverse.com/thing:40064
Specifically: http://www.thingiverse.com/download:113545

..is invisible when loaded into the Slic3r viewer 0.9.9 (config file here: https://dl.dropboxusercontent.com/u/4978192/sl099_config_ws.ini)

The selected file should be coloured in Red: https://dl.dropboxusercontent.com/u/4978192/Slic3r.jpg

The STL certainly exists, and is watertight, checked in Rhinoceros here: https://dl.dropboxusercontent.com/u/4978192/Rhino.jpg

And slicing the model produces gcode here: 
https://dl.dropboxusercontent.com/u/4978192/Pronterface.jpg

But naturally an invisible model makes bed location difficult to predict. Autoarrange has no effect. Has this issue been reported before? I couldn't find it.

woodsmoke

**Comment by lordofhyphens** [comment]
Closing :)
