### ISSUE TITLE
Advanced: Prefix and Suffix gcode

### ISSUE THREAD

**Issue by Lodran** [alexrj/Slic3r#12]
I currently use start.gcode to insure that my printer is homed properly before starting a print.  Because I use sjfw, which doesn't support home commands, this is somewhat complicated.

My start.gcode also makes sure that my hotend is up to temperature before allowing the print to begin.

My end.gcode retracts the filament, turns off the hotend, and homes X and Y.

**Comment by lordofhyphens** [comment]
This has largely been done. Using the appropriate variables for layer temp or first layer temp in start gcode overrides the automatic temperature setting.

Closing
