### ISSUE TITLE
Anticipate feed rate change to avoid pimples/dimples

### ISSUE THREAD

**Issue by whosawhatsis** [alexrj/Slic3r#1203]
I've recently been experimenting with a bowden extruder, and have realized in the process that one cause of pimples (extra plastic at the start points of perimeter extrusion) and dimples (missing plastic at the start point of perimeter extrusion) is the delay in equalization of pressure in the nozzle when changing feed rates (and thus flow rate) when going from internal to external perimeters. My usual profiles all run the outer perimeter significantly (up to 3x) slower than the inner perimeters to get better detail, but when I tried one of these profiles with a bowden extruder, I started seeing huge pimples at the starts of my external perimeters, which went away when I set the internal and external perimeters to the same speed.

What's happening is that the pressure in the nozzle has to drop significantly when switching from high speed to lower speed, and a bowden extruder or a long hot zone will make this pressure change occur slowly. The fix is to always transition (preferably gradually, over the course of several segments) to the outer perimeter feed rate before finishing the inner perimeter (assuming inner->outer->fill order, different orders make it trickier) to allow the pressure to equalize at the new flow rate while the nozzle is still on the interior of the model.

**Comment by alexrj** [comment]
Okay, we can close this one as it was implemented (pressure management).
