### ISSUE TITLE
Wizzard (not a bug)

### ISSUE THREAD

**Issue by Kalf** [alexrj/Slic3r#1204]
Hello!

This is not a bug, but rather a idea!

I don't know how you guys configure slic3r. But I change the settings before every print. But wouldent it be helpfull to add a cofiguration wizzard that creates a temporary configuration file for just the current print?

**Comment by lordofhyphens** [comment]
There's an initial config wizard for slic3r. Having a wizard pop up for every single print is unnecessary and clutters the interface, especially with the Simple interface being a thing.
