### ISSUE TITLE
Weird speed calculations with cooling enabled

### ISSUE THREAD

**Issue by darrenfreeman** [alexrj/Slic3r#1209]
Using Slic3r 0.9.9.

I ran a test print on the calibration object: http://www.thingiverse.com/thing:24238

I had infill set to 95% so as to show gaps between the lines for the infill, and no gaps on the solid top infill.

What I saw was beautiful slow printing for the bottom layers up through the first few mm of infill. Then it sped up and spat out the solid/top infill very quickly. (I'm not sure which kind is being used for the top of the first row of steps.)

I saw that it was slowed to 10 mm/s for the good infill, and the only place where this is defined is in the cooling parameters as the min speed to slow down to for layers shorter than 30 s. Then it speeds up for the top infill probably because the commanded speed is a little slower, so it takes longer than 30s, so it doesn't need to go slowly, so it actually runs much FASTER!!

I suggest that the speed calculation must always keep the slower speeds actually slower. It's not okay for one layer, target speed of 30, to actually run much slower than another layer that has the same shape, target speed of 25 and narrower extrusion width so as to take more than 30s. Even if both of these layers were forced to 30s, the difference would not be as drastic as it actually is.

I also think there could be a bug in the amount that is extruded. I don't know this for sure, but on the layer where it ran much faster, it looked like there could be 50% or more extra plastic than there is room for. It was just going everywhere! But I haven't checked this in the gcode file, only the speeds. So keep that in mind, but I was performing a calibration for a reason :)

Here are the settings as included in the top of the gcode file:

; generated by Slic3r 0.9.9 on 2013-06-02 at 21:26:04

; layer_height = 0.2
; perimeters = 1
; top_solid_layers = 4
; bottom_solid_layers = 4
; fill_density = 0.95
; perimeter_speed = 15
; infill_speed = 30
; travel_speed = 50
; nozzle_diameter = 0.5
; filament_diameter = 2.83
; extrusion_multiplier = 0.95
; perimeters extrusion width = 0.60mm
; infill extrusion width = 1.00mm
; solid infill extrusion width = 0.85mm
; top infill extrusion width = 0.60mm
; first layer extrusion width = 0.60mm

And here are the settings in the cooling dialogue:
Slow down if layer time is less than 30s. Min print speed 10 mm/s.

**Comment by lordofhyphens** [comment]
This might have been fixed by hyperair's PR (which has been merged into master). Could you check and see? I'm going to close this, please reopen if you are still seeing this problem with 1.3.0-dev.
