### ISSUE TITLE
Feature request: per-print-settings temperature deltas

### ISSUE THREAD

**Issue by darrenfreeman** [alexrj/Slic3r#1226]
I have found that one of my filaments requires roughly 5 degrees higher temperature to get the same results as another, so it makes sense to have the temperatures set per filament.

But also, the ideal temperature depends on the speed of extrusion. To get a high quality part with slow printing requires about 5 degrees lower temperature than normal printing. And for extremely rapid printing, it's about 5 degrees higher.

So as a feature request, I hope you will include a small delta-T that I can store in the advanced section of my print settings. When I select the high speed print settings, it will add 5 degrees to whichever base temperature is assigned to the filament in use, and likewise it will subtract 5 degrees for the very slow print settings. I would guess that +-10 C would be a reasonable range if you wish to use a spin box.

Not changing the temperature based on the print speed has a noticeable effect on the quality of the print, so it's important for me to do this. Right now, it's all done manually by having to remember to change the filament settings (without saving them) whenever I change the print settings.

**Comment by lordofhyphens** [comment]
Closing, although I think something like this is implemented under "ooze prevention"
