### ISSUE TITLE
Ascii problems

### ISSUE THREAD

**Issue by pando85** [alexrj/Slic3r#1228]
When i tried to print from a file in a directory named with ñ,é or something like that i get this error:
Bad value for variable 'last_file_path', expecting type 'str' (ascii)
Slicing /home/alex/ñ/Ejer-N01-Sket-Cerradura.stl
Slicing: /usr/share/slic3r/bin/slic3r $s --load /home/alex/.slic3r/config.ini --output $o
Failed to open /home/alex//Ejer-N01-Sket-Cerradura.stl

Attempted to write invalid text to console, which could be due to an invalid baudrate
Attempted to write invalid text to console, which could be due to an invalid baudrate

I'm using pronterface, the fix is easy, just not name directories with that letters but i want to post it here.

Thanks!

**Comment by alexrj** [comment]
Fixed as of today.
