### ISSUE TITLE
Extra Fan Commands in GCode Output

### ISSUE THREAD

**Issue by tenaciousRas** [alexrj/Slic3r#1230]
I've found redundant cooling fan output in the GCode generated in Slic3r 0.99.  The redundant commands don't happen on every layer change, so they must not be there to indicate layer change.  I'm not sure if there are other commands being duplicated in 0.99.

For example, the actual output from Slic3r 0.99 looks like this:
[motion and other commands]...
M106 S224
[motion and other commands]...
M106 S224
[motion and other commands]...
M106 S224
[motion and other commands]...
M106 S223
...

I would expect the output to look likt this:
[motion and other commands]...
M106 S224
[motion and other commands]...
[motion and other commands]...
[motion and other commands]...
M106 S223
...

**Comment by lordofhyphens** [comment]
Closing, but is this still a problem? Please reopen if it's still a problem in 1.3.0-dev.
