### ISSUE TITLE
Settings and Simple mode

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#1233]
When I start a clean slic3r (no existing settings) it starts in Simple mode. When I change to Expert mode and click OK, I'm told I have to restart slic3r, which is fine. But the Preferences window remains there, so I have to click "Cancel" first or just close the window, which is unintuitive ("have I just cancelled the change?").

When restarting, the configuration assistant settings I previously set up while in Simple Mode are all gone, even though they appear to have been autosaved in simple.ini. It'd be nice if they were auto-imported when I have no preexisting expert settings, or perhaps made available as a read-only "Simple" setting (or perhaps even as -default-, arguably makes more sense to use user's own Simple settings than slic3r defaults).

**Comment by lordofhyphens** [comment]
Can't reproduce on 1.3.0-dev, Linux x64 (Debian 8).

**Comment by SydneyMakers** [comment]
Testing on 1.2.9 Bug is gone. OSX 10.11.2 (15C50)
