### ISSUE TITLE
Attach single walls to loops

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#1237]
When printing some slim pieces, I've noticed that slic3r draws a perimeter, and then later draws a tiny blob off the sharp end:

![slic3r-detached-blob-detail](https://f.cloud.github.com/assets/684832/642143/c22dbc84-d34e-11e2-86b9-8314d739aa3b.jpg)

In a case such as mine, where there is only one such tip, the part would have been better if the print started or ended at this tip, and then completed loops as necessary from there.

When there are several such protruding details, this gets more difficult. It may be possible for two protrusions, but for many it gets impossible to print them all in a single uninterrupted pass. But rather than printing such blobs alone, it might be better if slic3r started at a suitable spot along the perimeter, printed some perimeter distance, and then ended in the protrusion. From there, travel back to a new suitable spot along the perimeter, and print a suitable perimeter distance, and finish on the protrusion. Here's a sketch, pardon my bad free hand drawing :) What I think happens today to the left, and a hopefully understandable sketch of what I'm suggesting to the right.

![protrusions-path](https://f.cloud.github.com/assets/684832/641746/7a5a37ca-d33f-11e2-96ed-7e6a36ff2288.jpg)

**Comment by lordofhyphens** [comment]
Is this still a noticable issue on 1.3.0-dev or 1.2.9?

If so, could someone reopen and provide an exported config.ini and screenshots from current 3d preview?

My config: 
[config.zip](https://github.com/alexrj/Slic3r/files/351431/config.zip)

Thin wall detection disabled:
![base-nothin](https://cloud.githubusercontent.com/assets/31754/16642829/44ecbbfe-43d4-11e6-8904-454a99e650a9.png)

Thin wall detection enabled:
![base](https://cloud.githubusercontent.com/assets/31754/16642830/44f0093a-43d4-11e6-905e-7720f8036a35.png)
