### ISSUE TITLE
Setting up nozzles when using multiple extruders

### ISSUE THREAD

**Issue by ajayre** [alexrj/Slic3r#1256]
When using multiple extruders the output gcode sets all nozzles to their operating temperatures. This causes my nozzles to ooze. Then the printing starts and the blobs of ooze are deposited on the print when they fall off.

I suggest Slic3r has an option to chose between the following two scenarios:

1. All temperature management is handled by the firmware. E.g. T0 sets nozzle 0 to operating temperature and all other nozzles to the standby temperature. This is how the RRP version of Marlin works. Don't initialize any temperature settings explicitly in the gcode.

2. Slic3r assumes nothing. It handles all temperature management for the nozzles. At the start of the gcode it sets all nozzles to the *standby* temperature (so no oozing).

Andy

**Comment by lordofhyphens** [comment]
There's ooze prevention now with standby temps. Closing.

**Comment by ajayre** [comment]
In which version?

**Comment by lordofhyphens** [comment]
1.2.9. Probably in earlier versions of 1.2.x as well.
https://github.com/alexrj/Slic3r/files/336282/slic3r-most_prs.zip has it moved to the Printer page.
