### ISSUE TITLE
Variable fill density threshold

### ISSUE THREAD

**Issue by SanjaySuri87** [alexrj/Slic3r#1268]
Would it be possible to adjust fill density to a specific threshold? When I need to print a plate, some parts (large objects) require high infill while other parts (small gears ect) require little to none. Currently I can either print under filled large parts with perfect small parts or prefect large parts with overfilled small parts.

It would be great to have 2 density settings, one below a certain threshold and one above. I am not sure if there is a way to do this already so feel free to correct me if i am wrong.

Thanks!

**Comment by lordofhyphens** [comment]
Per-object settings in the plater should be able to solve this.
