### ISSUE TITLE
Autotune settings for optimal detail width

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#1274]
In some cases horizontal accuracy is important to get a usable print, for example on slim details/thin walls. I'm not sure if work has already been done to test or implement strategies like these, but to be better able to match a specific wall thickness, it would be nice if slic3r tried to automatically accommodate the necessary wall thickness on these details by auto-adjusting the amount of deposited plastic with strategies such as:

1. alter feed rate when printing the specific detail to deposit less or more plastic
2. change the layer height of the specific detail to get wider or slimmer tracks deposited

Is something like this already being worked on in a thinwall branch? Is the printer currently limited to using perimeter width (or infill extrusion width?) for all such details?

**Comment by lordofhyphens** [comment]
1.3.0-dev has variable width perimeters now (also gapfill). Your minimum wall thickness is still dictated by your nozzle diameter.

Closing.
