### ISSUE TITLE
Nylon printing - Skirt and Raft issues

### ISSUE THREAD

**Issue by 3ntrlab** [alexrj/Slic3r#1275]
Maybe I am missing something, but with any gcode I've seen so far, every first layer to be printed follow this logic:

1) Print the skirt
2) Print the brim, outer perimeter first

I believe it would be far more productive the inverse: printing the brim BEFORE the skirt, to reach the object "foot" area with extruder well primed and no discontinuity between skirt and object.

Again, to fight warping, I deeply miss a wider raft (or a way to control its behaviour, letting user to decide how much it may protude outside of object perimeter).

Best Regards
Davide Ardizzoia

**Comment by lordofhyphens** [comment]
@3ntrlab yeah, brim is for adhesion (and secondarily could be used for priming), skirt is mostly used for priming and to keep heat in (if you're printing it tall). Going to close this. Please reopen with a test case and pictures of issues on 1.2.9 or 1.3.0-dev.

FWIW, I print with nylons myself.
