### ISSUE TITLE
Feature Request: Print layer (and other info) during print

### ISSUE THREAD

**Issue by zdar** [alexrj/Slic3r#1285]
Hi,
it would be nice if slic3r could include in G code printing of current layer and other info (such as consumed filament) using M117 command. That way the progress of print could be easilly monitored on printers display.

M117 allows to display any message on printers display

**Comment by bobemoe** [comment]
Yeah, also looking to do this with a placeholder.

There is a method here using a post processing script:
http://www.soliforum.com/topic/173/slic3r-post-processing-scripts/
