### ISSUE TITLE
No infill generated - bug or feauture?

### ISSUE THREAD

**Issue by zdar** [alexrj/Slic3r#1287]
Setting Advanced -> When Solid infill treshold area to 0 causes infill not to be generated,

Only bottom solid fill was generated
. Infill at other layers disappeared.

Slicr 0.9.10b at win8 x64
fill density 0.4
honecomb infill

settings
![setings](https://f.cloud.github.com/assets/1691703/735256/d3b47042-e2ee-11e2-89ef-eb5ebb4281ba.png)

Honeycomb structure missing
![no infill](https://f.cloud.github.com/assets/1691703/735257/d79c51a2-e2ee-11e2-9017-76711faeb3b4.png)

**Comment by lordofhyphens** [comment]
Can't replicate this with 1.2.9, and your test files are not available. Closing.
