### ISSUE TITLE
Infill way to sparse when using "Infill every n layers"

### ISSUE THREAD

**Issue by hungerpirat** [alexrj/Slic3r#1288]
First: Gorgeous software! Thank you very much for your effort.

I used the first time the "Infill every n layers" setting n to 3, while reducing layer height from 0.3 to 0.1 mm. 
Fill density is unchanged 0.4, Fill pattern honeycomb.
The honeycomb infill is way to sparse. It looks like not only the infill layer height has been scaled, the pattern has been scaled as well. 

As I understood the parameter documentation, there should be three layers of perimeters with height .1 and then one infill with height .3 , right?

If you need the stl and the gcode see https://dl.dropboxusercontent.com/u/5519927/Schaufel.gcode.tar.gz

![sparse_infill](https://f.cloud.github.com/assets/3082129/742183/99bca434-e3c2-11e2-817e-d15b1545e1ac.png)
The part where the infill is visible is round about 30mm wide.

Thank you in advance, 
Teja

**Comment by lordofhyphens** [comment]
Could someone please test the Pull request referenced so I can merge it in?

**Comment by lordofhyphens** [comment]
I am going to close this now as #1783 has more conversation on it and is pretty much the same thing.
