### ISSUE TITLE
Retract incorrect for LinuxCNC

### ISSUE THREAD

**Issue by cdsteinkuehler** [alexrj/Slic3r#1289]
I have been having problems getting rid of blobs when using LinuxCNC to drive my MendelMax.  I have finally traced this back to the use of G0 moves combining retract with travel when I select the "Mach3/EMC" gcode flavor.  Apparently, Mach does uncoordinated G0 moves?  LinuxCNC matches Mariln and does coordinated G0 moves, so retract works well for short distance moves, but fails (retracts too slowly to stop blobs) on longer moves.

I looked in the code and did not see an obvious way to disable G0 moves without switching to a different gcode flavor, which then produces a bunch of "illegal" codes (as per RS274D/ISO 6983).

Is there a way to force retract before move and still output RS274D compliant gcode?

**Comment by lordofhyphens** [comment]
@strahlex Does this work in the current 1.2.9 or 1.3.0-dev?

**Comment by mrvn** [comment]
@nophead Rounded off corners are, as mentioned, to maintain speed while changing direction and happens for G1 too. But there is a G-code to switch to exact following (and coming to a full stop in corners): G61. Does that affect G0 too?

For more about rounded corners read http://wiki.linuxcnc.org/cgi-bin/wiki.pl?TrajectoryControl

**Comment by nophead** [comment]
Yes I am aware why it rounds corners and of G61. My guess would be G61 doesn't affect G0

**Comment by lordofhyphens** [comment]
@machinekoder The default filename is an option in the Print Settings->Advanced.

I'll take a look at the LinuxCNC flavor behavior for the axis.

**Comment by lordofhyphens** [comment]
@machinekoder @strahlex

According to https://github.com/alexrj/Slic3r/blob/master/xs/src/libslic3r/PrintConfig.hpp#L354 and https://github.com/alexrj/Slic3r/blob/master/xs/src/libslic3r/GCodeWriter.cpp#L379 and https://github.com/alexrj/Slic3r/blob/master/xs/src/libslic3r/GCodeWriter.cpp#L448, the extrusion axis should be correctly defined for Mach3 firmware flavor. If you weren't in Mach3/LinuxCNC (or Machinekit) flavor and you still wanted the axis to be A you can override the extrusion axis on the command line with --extrusion-axis (those and no-extrusion override this presently).

If you can still reproduce the problem in current master (https://bintray.com/lordofhyphens/Slic3r/slic3r_dev/1.3.0-dev-25bcff3#files) I will reopen.
