### ISSUE TITLE
Feature Request: layer change during infill only

### ISSUE THREAD

**Issue by koolatron** [alexrj/Slic3r#1299]
There's no reason ever to do layer change on a perimeter if it can be helped.

If layer change can be restricted to infill areas, perimeter blobs from extruders with sub-optimal retract settings can be minimized -- the blobs are still there, but they're hidden in the infill.

Ideally: outer perimeter -> infill -> layer change -> inner perimeter -> outer perimeter

**Comment by lordofhyphens** [comment]
IIRC this is the same as #3299 and #1037, and it's patented. Closing.
