### ISSUE TITLE
Cosmetic issue: all text not visible in Object -> Layers window

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#1300]
I'm characterising this as a cosmetic issue. On Ubuntu 13.04, I get an issue when I double-click an object and view the Layers tab - not all text at the top of the window is visible. Here's what it looks like:

![cosmetic-issue-layer-heights](https://f.cloud.github.com/assets/684832/757359/c1490072-e68f-11e2-94cc-92c1c47ed23e.jpg)

Edit: resizing the window doesn't help except if I make the window wide enough to fit all text on one line.

**Comment by lordofhyphens** [comment]
Still a problem? I don't use Ubuntu. Also would help to know which window manager you are using.

**Comment by alexrj** [comment]
Thanks to a pull request by @pn2200 this is now fixed.
