### ISSUE TITLE
Can't locate Slic3r/XS.pm in @INC

### ISSUE THREAD

**Issue by sjkelly** [alexrj/Slic3r#1305]
I am using commit 98726fdef45263a8423e6b7ebe49c15dd26621d7. 

When running under Ubuntu 13.10 I get the following error...

```
Can't locate Slic3r/XS.pm in @INC (@INC contains: /home/steve/Software/Slic3r/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /home/steve/Software/Slic3r/lib/Slic3r.pm line 68.
BEGIN failed--compilation aborted at /home/steve/Software/Slic3r/lib/Slic3r.pm line 68.
Compilation failed in require at ./slic3r.pl line 13.
BEGIN failed--compilation aborted at ./slic3r.pl line 13.
```

I tried installing XS from cpanm, but I believe that is an unrelated package because it does not do anything. I also could not locate `@INC`

**Comment by michaeldbr** [comment]
Hi Guys, can you give me the code you used to run build.pl??
i can't get it to work

**Comment by lordofhyphens** [comment]
@michaeldbr please open a new issue with your question and what you are doing and what you are getting for output.
