### ISSUE TITLE
Only consider the used extruders in skirt

### ISSUE THREAD

**Issue by repetier** [alexrj/Slic3r#1306]
For some reason I wanted to use only extruder 2 for a print. I set perimeter and infill and support to extruder 2. Everything fine except that Slic3r used extruder 1 for the skirt. That makes no sense.

Temporary solution is to change the T0 in T1. But since we print the skirt to fill the extruder at startup and we start with perimeter, I think we should print the skirt with the perimater extruder regardless off the id it has.

**Comment by lordofhyphens** [comment]
@alexrj did you fix this?

**Comment by VanessaE** [comment]
Yes, what @repetier describes is already the case, and it works pretty much as expected.

For the first layer, if both extruders are used in the print, both are used for the skirt as well (if you have asked for enough loops), and only extruder #1 is used for the skirt on successive layers thereafter.  If only one extruder is used in the print (regardless of which one it is), that extruder is used for the skirt as well.

**Comment by lordofhyphens** [comment]
Good. I can close the issue then.
