### ISSUE TITLE
slic3r 0.99 plater layout resets with additional STL

### ISSUE THREAD

**Issue by tenaciousRas** [alexrj/Slic3r#1318]
slic3r 0.9.9

The use-case is this:  I layout 3 STLs in the Slic3r plater, then realize I have enough room for a 4th STL, so I click-and-drag a 4th onto the plater.  Once I do this, the position of the fist 3 STLs is reset, and my prior work is lost.  There really is no good workaround for this.

Expected:  Isn't the old behavior to leave any pre-existing STL layout unaffected and place the additional STL "on top, in center" and give it focus?

**Comment by lordofhyphens** [comment]
You can turn it off now in the plater preferences.

**Comment by lordofhyphens** [comment]
File->Preferences, uncheck the checkbox. :)
