### ISSUE TITLE
feature request: skirt safety anchor

### ISSUE THREAD

**Issue by starno** [alexrj/Slic3r#1333]
More specifically printing with ABS: When the extruder heats up before a print, the ooze that sags out of the nozzle often cools enough that the initial extrusion doesnt stick, and combined with the first second+ of extruding spent building up pressure, the outline ultimately isnt able to connect with itself.  Depending on the geometry of what I'm printing the poorly adhered section can sometimes get dragged around a bit, potentially interfering with the brim and/or object.  

![img_20130718_101926](https://f.cloud.github.com/assets/352025/817734/427f608c-ef7d-11e2-9ea2-a48e044ad0f7.jpg)

I can increase the skirt distance from the object and probably avoid the problem, but a more ideal anchoring routine worked very well to solve this when I was using skeinforge.  I think some form of purging outside the outline or increasing the relative flow rate for a short distance on the outline are two potential options that should improve overall reliability.  

example: http://softsolder.files.wordpress.com/2011/03/cimg5730-manual-splodge-with-companion-cube.jpg

The problem with implementing custom start gcode like this person did, is it must start from the outer edge of the build area.

**Comment by lordofhyphens** [comment]
@starno This isn't actually something I've seen on my printer. Are you using a skirt to keep heat in, or as a prime? Most people nowadays use it to prime.

**Comment by lordofhyphens** [comment]
If you're using it to prime, a post-processing gcode script could increase the extrusion amount by some % for just skirt layers for the first layer.

**Comment by starno** [comment]
Wow, and all this time I thought the request had been ignored!  No offense, but in my opinion that approach is not only over-complicating a simple solution, but it would also cause more issues in a multiple outline or layer skirt configuration like asmacdo was using above.  

My goal all along was to be able to create the most robust first layer application possible so I could have a "set and forget it" setup.  I ended up hacking my own solution within the software itself by increasing the gap between the skirt and object and though it's not the most space efficient solution, it does work.

Regardless, I appreciate your feedback.

**Comment by lordofhyphens** [comment]
Are you talking about a skirt (outer edge used to prime or hold heat in) or
a brim (also usable to prime but mostly used for adhesion purposes) ?

Skirts can already be set up variable distance from the print. This
includes any rafts or brims (if my memory serves, a raft and brim together
puts the brim on the raft layer). There is also a option for minimum skirt
length (handy when priming).

I always lay down at least one layer of skirt for priming purposes 5mm or
so from the print. If I have a brim as well, the skirt is printed first and
then the brim goes down.

In terms of this feature request I am mostly trying to a) understand the
problem and b) work out how much effort is required to solve it if it
hasn't been solved already.

**Comment by lordofhyphens** [comment]
When there is only one person largely responsible for doing everything,
stuff falls through the cracks, and there has been a lot of time for things
to get overlooked.

Just dispositioning all of the issues is going to take months.

**Comment by lordofhyphens** [comment]
Usually post process scripts are the least effort solution to a problem. They also tend to be the most portable and the ones with the most interesting side effects. :)

That being said, I think it would still serve here, to increase extrusion amount on the first loop of a skirt ( I do not actually remember if you can make skirts multiple perimeters).

Please check the current build (these options are in 1.2.9) let me know of the tools there solve your issue.

**Comment by starno** [comment]
I understand there are a lot of issues to sort through and the number of contributors are low.  My intentions were solely for priming.  I think we all agree it is a necessary procedure with FDM, and I understand skirt has multiple functions (prime + trap heat), however the current implementation of skirt assumes that the first segment of extrusion begins instantaneously.  

As the photos above show, the initial extrusion that hasn't reached steady state can sometimes not adhere to the bed right away, opening opportunity for dragging/sticking to something and ultimately interfering with the model.  My solution to this was to increase the distance between the object and skirt.  However this is just a hack, whereas a spiral like start as @asmacdo mentioned is a more robust solution.  Another potential solution being the "anchor" like blob that also starts outside of the skirt and begins the skirt once extrusion has unquestionably reached steady state.

**Comment by mrvn** [comment]
My startup gcode includes a 5mm extrude and wipe (lowering Z while moving across) along the front of the print bed. Only after that the skirt is printed. Pretty much solved the problem of the skirt starting by getting dragged around and taking way to long for me.

Here is what's missing: skirt layer height. Printing a skirt at 0.1mm or even 0.05mm and 10mm minimum extrusion means many many loops around the object. For priming purposes it would be much faster to print the skirt at 0.2mm height and 1mm width for example.

**Comment by lordofhyphens** [comment]
Skirt gets printed at as a perimeter for its layer, etc. I will take a look
at making this configurable.

**Comment by lordofhyphens** [comment]
Well, I *think* this is easy enough to make configurable.

**Comment by lordofhyphens** [comment]
Well, it's less easy than I originally thought. Mostly because Flow objects are apparently immutable; means that there isn't a good way to get a new one and trying to generate a new one in the make_skirt() subroutine crashes slic3r with some interesting segfault or something.

**Comment by lordofhyphens** [comment]
Done. See PR #3349 for details.

**Comment by alexrj** [comment]
Hey @starno, nice to see you around.

I don't think making skirt extrusion width/height configurable addresses the original problem reported by @starno. When pressure is established, I don't see why skirt should behave differently from the other first layer things (brim and object). If settings are okay for brim and object, they are okay for skirt as well.

@starno, why don't you just include a priming extrusion in your start G-code? I do this myself. Go to a corner at z = 0.3, extrude a little blob, than start the print with a fast travel move. In some printers I do this outside the bed or behind a wiper so that when nozzle comes back into the bed area, the ooze is removed.

**Comment by starno** [comment]
Hi @alexrj, 

To be honest, I am not really having trouble with this situation anymore, and I think your suggestion works well.  However, when I think about hypothetical extreme cases-such as a giant bed and a small printed object, there is still a stopping of extrusion and large travel distance before starting back up again, because the priming sequence is hard-coded at a fixed location.  In the cases of printing a large plate of objects one at a time, it could also be less than ideal.   

I think a cool feature would be to do exactly as you explained with the blob, except that action is done at a relative distance and angle to the first segment of the skirt or brim and transitions smoothly into it.  Easier said than done I'm sure, but it seems to satisfy all use cases I can think of.

**Comment by Lord2Vader** [comment]
I use this to prime the nozzle. You just scrape it away after the print is done:

<---Startcode--->

M104 S[first_layer_temperature]
G28 X0 Y0
G28 Z0
G1 F100 Z3
G1 F2400 X0 Y3 Z3
G1 Z0
G92 E0
M109 S[first_layer_temperature]
G1 Z0.3
G1 F500 X50 Y3 E7
G1 Z[first_layer_height]

<---End startcode--->

I dont ever need a skirt.
