### ISSUE TITLE
Estimated time for print in Gcode

### ISSUE THREAD

**Issue by prggmr** [alexrj/Slic3r#1334]
Hello,

Sorry if this is the wrong place for this but I'm not sure where else to post this and couldn't find anything when searching the interwebs.

Is there a way to get an estimated print time when generating GCode files through the command line?

I've used the `--gcode-comments` which generated more information but did not provide the time.

Thanks for the help!

**Comment by ehybrid** [comment]
@alexrj 
would you accept a patch where the estimate was made clear it was an estimate by providing an input for the user, which is "per-printer-fudge-factor" or something else similarly vague without which there is no estimate, and with it, the user gets to adjust it up/down based on if the estimate was close for them in reality on their printer (which, granted, will still be imperfect per print depending on the amount of time each print spends in acceleration compared to another)...  Many people (especially new users) find it very handy to be able to adjust slicing settings if the print time was way beyond their expectations (ie, slicing at 0.1mm, getting everything looking good, then exporting to SD, going to printer, selecting print, and that right there being the first time estimate for the print time means a long feedback loop to cancel it and re-slice it at 0.2mm)...

**Comment by lordofhyphens** [comment]
I would take a look at it. Perhaps as a final output to the status bar?
