### ISSUE TITLE
Layer Height Affects Fill?

### ISSUE THREAD

**Issue by JoshMcCullough** [alexrj/Slic3r#1336]
Slic3r 0.9.10b, Windows x64

I have a simple model which I would really like to come out completely solid. I've set perimeters to 3; top/bottom layers to 3; infill to 100% rectilinear.

However, the infill is not coming out solid nor is the top/bottom layer.

Specifically, when i slice the model with .2mm layer height, the top layer is sparsely filled, if at all. Using .3mm layer height, the top is filled much better.

Why would layer height cause the fill of the top layer(s) to change?

Model: https://docs.google.com/file/d/0B4o6vqgNLpvbNjJVRWp0T29sOWc
Config: https://docs.google.com/file/d/0B4o6vqgNLpvbXzM0VU9TNzFZY2s
GCode @ .2mm:https://docs.google.com/file/d/0B4o6vqgNLpvbVkphb0FuTmJuRG8
GCode @ .3mm: https://docs.google.com/file/d/0B4o6vqgNLpvbQXJzMGhheHk2eVE

Have a look at the difference between the .2mm and .3mm GCode - the only setting I changed was layer height.

Top layer @ .2mm:
![Top layer @ .2mm.](https://f.cloud.github.com/assets/4859660/822569/c7b111e0-eff2-11e2-8219-e493afb3abb0.png)

Top layer @ .3mm:
![Top layer @ .3mm.](https://f.cloud.github.com/assets/4859660/822575/db911034-eff2-11e2-94a2-3a30d5a16c6d.png)

**Comment by lordofhyphens** [comment]
Gapfill has probably fixed this.
