### ISSUE TITLE
Gcode visualization

### ISSUE THREAD

**Issue by nicolinux** [alexrj/Slic3r#1339]
It would be very useful to have a visual representation for the generated gcode. This would save filament and time if problems with slicing would be detected before printing. More often than not the generated object doesn't look good after printing. Some parts might not be properly covered or are too thin or any other random error that might arise from bad settings or combinations.
Right now the workflow (I guess for most people) is to load the gcode file into Repetier Host (or some other tool) and check the model for problems. It would be extremely helpful to have that built into Slic3r. Since you create the gcode, by now you must be a gcode wizzard, so you would know best how to visualize it. I know that it is not possible to have an exact representation because every printer is different. But since Slic3r knows so much about the printer, it would be "easier" for it to approximate the visualization of the model.
Take for example the attached image. The marked area would look bad when printed because I can't tell Slic3r that it should add some extra solid layers at that specific position/height. The models takes roughly one hour to print. A proper visualization would save a ton of time.

![bad_covering](https://f.cloud.github.com/assets/1069286/829370/23825e46-f0d6-11e2-8919-3a1803659d10.png)

**Comment by alexrj** [comment]
As of today we have live 2D and 3D toolpath preview. :)
