### ISSUE TITLE
Gaps in prints

### ISSUE THREAD

**Issue by KGardevoir** [alexrj/Slic3r#1340]
On thin objects such as the 5mm calibration steps (http://www.thingiverse.com/thing:24238) there are small gaps if the perimeters are 1 less than what would be required to fill the gap. This occurs the latest version of slic3r. To fill this gap one would expect either infill or an extra perimeter, in this case adding one more perimeter solves the problem.
![screenshot from 2013-07-20 00 20 51](https://f.cloud.github.com/assets/1061429/829874/08ebcff4-f10d-11e2-9708-98859e1fd6db.png)

**Comment by lordofhyphens** [comment]
Should be fixed with gapfill.
