### ISSUE TITLE
Changing number of extruders has strange behavior/crashes.

### ISSUE THREAD

**Issue by buildrob101** [alexrj/Slic3r#1350]
Windows 7 64bit 0.9.10b

3 issues observed:
- With default initial program config, in Printer Settings increasing number of extruders from 1 to 2 to 3 (without pressing ok) corrupts screeen output (adds addition Extruder fields to screen) [see screenshot]
- With default initial program config, in Printer Settings increasing/decreasing number of extruders from 1 to 2 to 1 to 2 to 1 (without pressing ok) adds multiple Extruder categories. [see screenshot]
- Fresh install of Repetier-Host 0.90c (with Slic3r 0.9.10b). Set number of extruders to 2 in R-H Printer Settings. THen ran Slicer->Slic3r->Configure (from Repetier-Host). In Slic3r Printer Settings increment number of extruders from 1 to 2. Slic3r crashes immediately. Error is as follows: 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	slic3r.exe
  Application Version:	0.9.10.12
  Application Timestamp:	503fe867
  Fault Module Name:	COMCTL32.dll
  Fault Module Version:	6.10.7601.17514
  Fault Module Timestamp:	4ce7c45b
  Exception Code:	c0000005
  Exception Offset:	00000000000941ce
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	3081
  Additional Information 1:	ddf2
  Additional Information 2:	ddf28398ae617409663b42ffea4bc565
  Additional Information 3:	3bf7
  Additional Information 4:	3bf7b5bc6eaf60f214d0e9320d81fb05

![image](https://f.cloud.github.com/assets/3714793/840406/7a98ff94-f371-11e2-9299-2dcc631a28cb.png)
![image](https://f.cloud.github.com/assets/3714793/840411/a68cef20-f371-11e2-98b6-1175594dccde.png)

**Comment by lordofhyphens** [comment]
Can't reproduce on current master, probably fixed. Please reopen if you find issues with current -dev.
