### ISSUE TITLE
Error while slicing

### ISSUE THREAD

**Issue by PaulCornelissen** [alexrj/Slic3r#1379]
I get this error:
http://puu.sh/3Wht1.png

While slicing:
https://www.dropbox.com/s/lsj38m339mmo7ti/Vase_3_Tier_Circular_Base_Solid%20gedraait%20en%20geschaald.stl

Using this config:
https://www.dropbox.com/s/2cgmhlt6wdmdc91/config.ini

And Slic3r 9.10b x86 on Windows 7:
https://www.dropbox.com/s/lulvj3cafb0ixg1/Slic3r%209.10b%20x86.rar

Reproduced the error on my laptop running Windows 8
Reproduced the error with 64bit version of Slic3r 9.10b

I just found out it's related to the layer-height setting. When I change to 0.25 for the layer and 0.35 for the first layer it slices just fine.

**Comment by lordofhyphens** [comment]
Can't recreate now, can't get files. Please reopen with new info if you still have this problem.
