### ISSUE TITLE
No gapfill on top and bottom layer

### ISSUE THREAD

**Issue by thecrazy** [alexrj/Slic3r#1391]
Is it me or setting infill to 0% also disables gapfill on the top and bottom layers???

I want my object to be hollow but I need the gapfill to work (even tough its not perfect) so my top and bottom shells are complete and the item wont fall appart.

With 0.1 infill
![image](https://f.cloud.github.com/assets/2411956/952082/18ae469c-03be-11e3-8758-df653eeeaf83.png)

With 0 infill
![image](https://f.cloud.github.com/assets/2411956/952073/ecb2f592-03bd-11e3-86e3-5bf780bacc0b.png)

FYI this is using 0.9.10b

Here is the stl: https://dl.dropboxusercontent.com/u/69468886/BUGS/Head%20band%20top%20and%20bottom%20gapfill%20missing/Part1%20w%20spikes%202.stl

**Comment by lordofhyphens** [comment]
@thecrazy you could use a modifier mesh in the current version to set parts of the model to 0% infill and others to 100%, which should solve your problem.

There's a simple generator at 
https://github.com/alexrj/Slic3r/blob/master/utils/modifier_helpers/layer_generator.jscad
copy-paste to the text box at openjscad.org and press shift+enter.

Slice the model once to figure out the Z heights of the top and bottom layer, set "layer height" in the openjscad window to the difference and the Z value to the initial layer height. Export as an STL and right-click on your model in the plater->settings. Add the new modifier mesh you just downloaded to the part and set its infill % to 0. For the rest of the model, set it to 100%. 

Alternatively, you can generate two thin layers. and set their infill % as modifier meshes to 100% and leave the other infill to be whatever you want.

**Comment by lordofhyphens** [comment]
0

**Comment by lordofhyphens** [comment]
Modifier mesh tutorial: 
http://slic3r.org/blog/modifier-meshes
