### ISSUE TITLE
crash while generating gcode

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#1398]
Hi all,

I'm using Slic3r 0.9.10b on windows XP (32bit) for as long as this version was published, without any problem

Today, it start crashing (no message, no error, it just disapeared while "Generating perimeters...")

I've noticed that when using the console version, it works fine 

slic3r-console.exe --load config.ini protege-occulaire.STL

The config is the one I use since some month now, without any problem until now

I tried another STL witch was sliced without problem some month ago, and it crashed while "processing triangulated mesh"

here is the config.ini : https://dl.dropboxusercontent.com/u/34934879/config.ini

here is the stl : https://dl.dropboxusercontent.com/u/34934879/protege-occulaire.STL

Here is the known-working-STL-witch-doesnt-works-anymore : https://dl.dropboxusercontent.com/u/34934879/tardis-small2.stl (doctor who rules ! x)

This is my first bug report, so please tell me if i'm doing something wrong :)

cheers
gege

**Comment by alexrj** [comment]
Tested on 1.2.6-dev, it's fixed.
