### ISSUE TITLE
Overhang Threshold Setting Problems

### ISSUE THREAD

**Issue by pirvan** [alexrj/Slic3r#1406]
I've looked around, and so a couple of similar posts, but without any traction (no responses), so I decided to "rekindle the fire" so to speak.

My problem has to do with the <b>Overhang Threshold</b> angle setting.  It appears that no matter what value I input, other than zero, it's either ignored or it makes very little difference in the generated support.

I'm using the latest release version 0.9.10b, and whether I select an angle like 85° or 5°, the results are the same:  the model is literally surrounded with support material.  Setting the angle to 0° does seem to enable an automatic detection and usually produces a more "reasonable" mount of support, but even that is most of the time overkill (see example below).  

To my understanding, the Threshold angle value is from the vertical, so a 0° angle is a vertical, while 90° is horizontal.  Therefore setting the value to 65° would generate support for objects overhanging by more than 65° off the vertical, but not anything less, while setting the value at 85° would only generate support for (mostly) horizontal surfaces or surfaces/objects starting in mid-air.

I've played with a variety of settings for this, and I get support on parts that are at angles of as little as 15-20° off the vertical.  Basically if it overhangs, it gets support regardless of what I do.

Below is an example of the Slic3r output of an object that shouldn't require any support, as the sides are only 18° off the vertical.  I sliced this with 4 settings, Auto, 5°, 45° & 85°.  The auto and 45­° settings, should have (in my mind) produced no support, the 5° and 85° settings would depend on whether my logic (which angle is horizontal and which is vertical) is right or reversed.  In either case, one should have produced support, the other should not.

![slic3r support sample](https://f.cloud.github.com/assets/5299691/1020331/5e6f5e54-0c8e-11e3-8ff4-c91b5c28f6a7.jpg)

BTW, I have a Solidoodle 3 printer, and I'm using Slic3r from within Repetier, however I've also used Slic3r as a standalone and the results are identical.  There are many users on the SoliForum that would like to get to the bottom of this problem, as most of us have now pretty much resigned ourselves to the fact that this setting doesn't work, and you either get everything or nothing.   A Solidoodle Support employee suggested we post this on the Github, so here I am.

**Comment by pikeymick** [comment]
I'm seeing this in v 1.1.7, is this a closed issue, or still open?
