### ISSUE TITLE
Should create perimeters before the first solid layer

### ISSUE THREAD

**Issue by Huwyler** [alexrj/Slic3r#1410]
Ok, this is a bit complicated to explain, but I'll try.

Imagine a cylinder with radius 20mm, and on top of it a cylinder with radius 40mm. At the point where the radius reduces, there will be a bunch of solid layers, which will have a "hole" of a bit less than 20mm radius. That's where the top cylinder will be placed on, so no need for a solid layer here. 

The problem I have noticed sometimes is that trying to place the solid layers, slic3r "bridges" over the honeycomb infill, but stops the strings just in the middle of such a honeycomb pattern, say, in free air, which then of course "curles" back, resulting in a hole in the solid layers.

I think, one relatively simple way to get rid of this issue would be, to "dublicate" the first perimeter of the upper cylinder down the (three or whatever number of) solid layers (or even one more). Then, the solid layers "strings" can be bridged to these perimeters.

**Comment by lordofhyphens** [comment]
You're going to need to come up with a test case (using 1.2.9 or 1.3.0-dev or newer) and images for us to have a hope of figuring out what you mean :).

Anyway, I suspect this may have been fixed at this point. Reopen if you still are seeing issues with a current version of Slic3r.
