### ISSUE TITLE
Slic3r ignores filament setting for second extruder.

### ISSUE THREAD

**Issue by EiNSTeiN-** [alexrj/Slic3r#1414]
I am trying to slice a simple two color cube. Number of extruders is set to 2. I have a filament configured with temperature set to 180. This filament is selected for both extruders in the Platter tab.

After slicing, I open the gcode file and I can see the "set temperature" line for T0 and T1 are different. For T0, it is correctly set to 180, for T1 it is set to 200, which is clearly wrong. Expected behavior is to set the temp for both extruders to the value that I configured. I made several tests: whichever configuration I set for the second filament is always ignored.

Note: settings were originally imported (File>Load Config) from a ini file, then saved and modified. It seems to make no difference that I import or start a new config from scratch, this bug is always present.

This is reproducible on several computers running Windows, and all versions of slic3r that I could test (0.9.9 and 0.9.10b). I have had reports of older versions being affected too.

**Comment by lordofhyphens** [comment]
Probably related to the filament settings parser. I'm going to close this. Reopen if you are having issues with 1.2.9 or 1.3.0-dev.

**Comment by EiNSTeiN-** [comment]
Almost 3 years later, I have not tested but I bet it's been fixed already 👍

**Comment by lordofhyphens** [comment]
Yeah, trying to sort through all of the outstanding issues and at least get them sorted, if not closed.

**Comment by rickyrockrat** [comment]
I can confirm this bug. I have never loaded from a config or hand edited. 2 extruders, Gcode is always T0, not T1, though I am not using T0 at all. Seems to happen with support structures.
