### ISSUE TITLE
Oval holes instead of round.

### ISSUE THREAD

**Issue by exuvo** [alexrj/Slic3r#1415]
I am trying to make a few round holes but slic3r insists on making the bottom and top of the hole flat in the output gcode. I have looked over my slic3r settings and found nothing obviously wrong there.

![repetier-host v0 90c - track_link gcode_2013-08-29_13-28-48](https://f.cloud.github.com/assets/2049338/1049221/689c75ec-109e-11e3-82b7-63be6fa35ebd.png)
![repetier-host v0 90c - listviewitem track_link stl _2013-08-29_13-29-06](https://f.cloud.github.com/assets/2049338/1049224/6aad54f0-109e-11e3-9532-25c414ee9614.png)
STL file http://exuvo.se/file/Files/track_link.stl
Output gcode http://exuvo.se/file/Files/track_link.gcode

I am using Slic3r 0.9.10b from Repetier-Host.

**Comment by alexrj** [comment]
That was just wrong rendering from Repetier-Host which doesn't know the extrusion width. This is a correct rendering of your file:

![schermata 2015-01-30 alle 21 37 41](https://cloud.githubusercontent.com/assets/594957/5982880/4ac2753a-a8c8-11e4-9264-ed069aae4ddf.png)
