### ISSUE TITLE
perl version warning

### ISSUE THREAD

**Issue by JohK** [alexrj/Slic3r#1441]
slic3r warns about perl versions > 5.16.
In all newer debian versions (testing/unstable...) perl has been upgraded to version 5.18. Ubuntu 13.4 still uses 5.14, but I'd guess they will be upgrading with their next release as well.

Also it seems to run fine for now with 5.18 (well except for the bugs that I reported, but afaik those aren't perl version specific).

**Comment by alexrj** [comment]
Okay, this was done.
