### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by mandylieu** [alexrj/Slic3r#1464]
hello,i have downloaded the source code,and i want to install it  in ubuntu.But,when i excute "sudo perl Build.PL" or "sudo perl Build.PL --gui",the system displays that "t/geometry.t...................1/25 failed test 'grow line' at line 189, got:'190', expected:'200'" and 't/polyclip.t...............1/24, failed test 'reverse line is clipped to square with hole', structures begin differing at: $got->[1]p1][0]='99',$expected->=[1][1][0]='100',at line 93".
please help ,thank you.

**Comment by DamienMiras** [comment]
please could you  advise to use "cpan -fi Test::Harness" command in case of the build fails because of wx dep not solved right to the install manuel on  the front page ? it just ahppen to me for stable and master version

**Comment by lordofhyphens** [comment]
@DamienMiras edit the wiki or make a PR against https://github.com/slic3r/Slic3r-Manual.

Instead of posting in 8 year old closed issues, open a new report. FWIW you can 99% of the time download the .tar.bz2 and copy local-lib from it and you won't need to reinstall anything from CPAN.
