### ISSUE TITLE
GUI Feature?  Reload STL file(s)

### ISSUE THREAD

**Issue by tbcarlson** [alexrj/Slic3r#1466]
I'd like to suggest a new button on the plater screen.  I know changing the GUI is not to be done lightly, but this would eliminate several steps in my typical workflow.

I would like to see a button named something like "Reload" or "Refresh" that would reload all the currently plated STL (or OBJ or AMF) files.

I frequently go through several iterations of a design in OpenSCAD, and print each one to see if the sizing is right.  Currently that means saving the STL in OpenSCAD, switching to Slic3r, deleting the model, clicking add, and finding the right file again before slicing it.  If there were a reload button, I could just hit reload and "Export G-code" and be done.

I know it's a minor time savings, but I'm sure I'm not the only one that would benefit from this feature.  Slic3r is an amazing tool and this feature would make it just a little bit better!  

Thanks for all your hard work!

**Comment by callimero** [comment]
What about that feature? I just dropped Repetier (which automatically reloads the part if changed on disk) because I am so happy with Slic3r 1.2.6 (Preview is finally there! And that Octoprint upload!). But quickly reloading the part is so important while in design phase.

**Comment by gege2b** [comment]
I support this feature ! :)

**Comment by alexrj** [comment]
Hello!
This is now implemented as a command in both the menubar and the contextual menu (right-click).
