### ISSUE TITLE
Retraction Speed setting ignored during wipes.

### ISSUE THREAD

**Issue by drahosj** [alexrj/Slic3r#1468]
When the "Wipe before retract" setting is enabled, the feedrate for the wipe retractions is set to 3900.000, regardless of the retraction speed setting. Without firmware settings to limit this to a sane value, the retraction skips steps. The feedrate is then set to a sane amount (taken from Retraction Speed) and the retraction is reversed. The symptoms of this are globbing whenever restarting from a move requiring retraction, as the filament is extruded to make up for retraction that didn't happen.

A workaround is to set the E axis max feedrate to the desired retraction feedrate in firmware, or else steps will be skipped whenever retracting with wipe enabled.

Firmware: Marlin
Host: Printrun/Pronterface
Slic3r: 0.9.10b

========SETTINGS.INI=======
# generated by Slic3r 0.9.10b on Sat Sep 28 21:13:16 2013

avoid_crossing_perimeters = 1
bed_size = 170,170
bed_temperature = 0
bottom_solid_layers = 2
bridge_acceleration = 0
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 60
brim_width = 0
complete_objects = 0
cooling = 1
default_acceleration = 0
disable_fan_first_layers = 1
duplicate = 1
duplicate_distance = 6
duplicate_grid = 1,1
end_gcode = M104 S0 ; turn off temperature\nM140 S0\nG28 X0  ; home X axis\nG1 Y160\nM84     ; disable motors
external_perimeter_speed = 100%
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 0x0
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
fan_always_on = 0
fan_below_layer_time = 60
filament_diameter = 3
fill_angle = 45
fill_density = 0.2
fill_pattern = honeycomb
first_layer_bed_temperature = 0
first_layer_extrusion_width = 200%
first_layer_height = 150%
first_layer_speed = 30%
first_layer_temperature = 230
g0 = 0
gap_fill_speed = 20
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_speed = 60
layer_gcode = 
layer_height = 0.2
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 10
min_skirt_length = 0
notes = 
nozzle_diameter = 0.35
only_retract_when_crossing_perimeters = 1
output_filename_format = [input_filename_base].gcode
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 30
perimeters = 3
post_process = 
print_center = 80,80
raft_layers = 0
randomize_start = 1
resolution = 0
retract_before_travel = 10
retract_layer_change = 0
retract_length = 1.5
retract_length_toolchange = 10
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 8
rotate = 0
scale = 1
skirt_distance = 6
skirt_height = 1
skirts = 1
slowdown_below_layer_time = 15
small_perimeter_speed = 30
solid_fill_pattern = rectilinear
solid_infill_below_area = 70
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0
solid_infill_speed = 60
spiral_vase = 0
start_gcode = ;T1\nG1 Z0
support_material = 0
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_layers = 0
support_material_interface_spacing = 0
support_material_pattern = rectilinear
support_material_spacing = 2.5
support_material_speed = 60
support_material_threshold = 0
temperature = 220
threads = 2
toolchange_gcode = 
top_infill_extrusion_width = 0
top_solid_infill_speed = 50
top_solid_layers = 5
travel_speed = 65
use_relative_e_distances = 0
vibration_limit = 0
wipe = 1
z_offset = .0

**Comment by josla972** [comment]
Hmm... I did not get this part: "because the E delta is calculated so that the retraction lenght is stretched enough to honor the configured retraction speed."

Suppose one would send the following to the firmware:
G1 F<feed_rate>
G1 X<x_pos> Y<y_pos> E<e_pos>

Would the firmware not interpret this as "move to (x_pos, y_pos) and extrude to e_pos at a speed of feedrate mm/minute, (but apply firmware restrictions on this feedrate, should there be any)"?

I do not see how changing the E delta (e_pos in this case) would change this. Have I missed something?
