### ISSUE TITLE
Command line mode can't handle unicode characters in input filenames

### ISSUE THREAD

**Issue by rodrigopitanga** [alexrj/Slic3r#1470]
How to reproduce:

rename an STL file with a character beyond the ASCII table and slice it.

```
rodrigo@snowball2:~/devel/Slic3r$ ./slic3r.pl ~/work/mm/mm_admin/Prototipacao/agora/totem_é_tarde.stl 

stl_initialize: Couldn't open /home/rodrigo/work/mm/mm_admin/Prototipacao/agora/totem_Ã©_tarde.stl for reading: No such file or directory
```

The same file can be sliced with the GUI.

Operating System: Trisquel GNU/Linux 5.5
Encoding: UTF-8
Slicer version: ac5e7133230e12c5019cba2a8ca21788e6b1852b (same behaviour on 0.9.10b, with slightly different output)

**Comment by alexrj** [comment]
This is fixed as of 1.2.6-dev.
