### ISSUE TITLE
Does not run in Expert mode on Win7 with non-ASCII character in user name

### ISSUE THREAD

**Issue by TomSld** [alexrj/Slic3r#1478]
Tested 9.10b on Windows 7 (both 32 and 64 bit, several computers). Czech Windows version.

After change in mode C:\Users\no-ascii name\AppData\Roaming\Slic3r\slic3r.ini to "simple" Slic3r is starting, but in simple mode only. "no-ascii name"="Tomáš Sládek" (=my name)

No error message, no error in command line.

**Comment by lordofhyphens** [comment]
Looks like this is fixed via whatever @alexrj did at #1712. Closing.
