### ISSUE TITLE
request/suggestion to avoid to have support in small holes

### ISSUE THREAD

**Issue by jfpion** [alexrj/Slic3r#1481]
it is a pain in the neck to have to clean the screw and nuts hole frome support if you enable it for the rest of the part.

as a way to avoid it is it possible to stop building support under a bridge less than 15mm (for example ) if your printer can't do 15 mm bridge without support you have a lot of tuning to do.

this way, no more support in the small hole where there is no need for it

**Comment by gaby64** [comment]
i continue to have support in holes

http://www.filedropper.com/bletmounttop
