### ISSUE TITLE
No movement of filament by using --gcode-arcs

### ISSUE THREAD

**Issue by Expander1** [alexrj/Slic3r#1493]
Hi,

I figured out, that by using the command line with gcode-arcs no movement of the filament in G2 or G3 code will be done. 

Could it be that the problem is here?

            # calculate extrusion length for this line
            my $E = 0;
            if ($e) {
                $E = $e * $line_length;
                $self->extruder->e(0) if $self->config->use_relative_e_distances;
                $self->total_extrusion_length($self->total_extrusion_length + $E);
                $E = $self->extruder->e($self->extruder->e + $E);
            }

This is in file GCode.pm from line 329 to 336.

I'm using my CNC-Milling machine with Mach3. I don't think that the problem will be in Mach3, because Mach3 understand G2 and G3 command's.

Thanks for helping in this

Expander1

**Comment by lordofhyphens** [comment]
Arcs are disabled, closing.
