### ISSUE TITLE
Option to use firmware-controlled retraction (G10/G11)

### ISSUE THREAD

**Issue by whosawhatsis** [alexrj/Slic3r#1494]
Marlin has an option to use G10 to retract and G11 to un-retract filament (using speed and length of retraction stored in the firmware). It would be nice to have an option to use this instead of slic3r-controlled retract length and speed.

**Comment by lordofhyphens** [comment]
I think that if this still needs to be worked on, it should be in a separate, more specific issue. Closing :)
