### ISSUE TITLE
Layer-height in flow calculations

### ISSUE THREAD

**Issue by platsch** [alexrj/Slic3r#1495]
The _build_width and _build_spacing methods in Slic3r::Flow rely on the $Slic3r::Config->layer_height for their computations. If the default layer height is overwritten for some parts of an object (in the object's settings), the changes are not taken into account, resulting in wrong extrusion spacings.
To evaluate the problem, I cloned the Flow object from Print with new parameters, to have one object per layer.

**Comment by alexrj** [comment]
This has been fixed in the mean time, and a lot has changed since then. :)
