### ISSUE TITLE
Add a configureable startup priming move

### ISSUE THREAD

**Issue by seemecnc** [alexrj/Slic3r#1496]
It would be sweet if you could add in the printer settings tab, in the custom G Code section a window to enter custom G Code that would be entered into the program after heating is done, to say move down to a fixed position, and make an "x" long move along the X axis, at the given feed/flowrate for the first layer, then retract/lift and start the print.  It could be as easy as just a box users could enter their own gcode, or you could prob. make it a few options to click that would automagically generate the code, but either way it would be nice.

Example G Code might be (delta machine used in example here)

(after heats have been reached, and G28 issued)
G1 X-25.0 Y-60.0 Z0.35 F12000.0
G92 E0.0
G1 E5.0 F250.0
G1 X25.0 E15. F600.0
(then continue the retract/start of file)

What do you guys think?  Would it be used?  I would

**Comment by lordofhyphens** [comment]
This is solvable through the generic start gcode interface. Just write similar to what @alexrj said.
