### ISSUE TITLE
Initial filament position for multiple extruders

### ISSUE THREAD

**Issue by stabbs** [alexrj/Slic3r#1498]
I am running 3 extruders with the following settings:

Slic3r 9.10b
Regular retraction = 4mm
Retraction when tool is disabled = 13mm

I would like to start the print with the filament retracted 13mm but Slic3r assumes that the filament is completely packed in the nozzle.  This is problematic because I get a ton of oozing on the first layer.

This is the first tool change:

G1 X105.600 Y104.345 F7800.000 E-4.78371
G92 E0
T1
G92 E0
G1 F180.000 E-4.00000
G92 E0

I changed it to this to compensate for the filament start position:

G1 X105.600 Y104.345 F7800.000 E-4.78371
G92 E0
T1
G92 E-13
G1 F180.000 E-4.00000
G92 E0

Sorry for the edit - i totally misdiagnosed my issue :)
Thank you for your time and effort on Slic3r - it is awesome!

**Comment by lordofhyphens** [comment]
This is probably appropriately solved with start Gcode, not modifications to Slic3r. Going to close. Reopen if you have something you can persuade us with :)
