### ISSUE TITLE
Feature Request: Rotation of printhead around the z -axis

### ISSUE THREAD

**Issue by Xabbax** [alexrj/Slic3r#1505]
For printing ceramics, pastes and cement (and possibly other materials) to use a rectangular hole in the nozzle.
Determining proper angular orientation of the nozzle head in relation to nozzle head/bed movement.
I think you will get the idea in the following videoclip where they use it for concrete printing but the principle can be used on plastic or any other material.

http://www.youtube.com/watch?v=-yv-IWdSdns
and 
http://www.youtube.com/watch?v=OfUN2RzgJYk

**Comment by alexrj** [comment]
Since there's no documented G-code command for doing that, and no known firmware supports that, I'm not going to implement that in Slic3r. It can (and should) be implemented inside the firmware which can automatically detect the motion direction.
