### ISSUE TITLE
Cooling disabled only for first layer of first object

### ISSUE THREAD

**Issue by darrenfreeman** [alexrj/Slic3r#1516]
This is what I observed: two identical sub-objects were split from the one STL and manually repositioned. The settings cause one object's perimeter and infill to be printed before the corresponding layer on the other object.

While printing, the first layer of the second object was much slower than the first layer of the first object. It appeared to be the same speed as subsequent layers of both objects.

As these are small objects, I believe the cooling settings have kicked in and slowed down the layers which are not in contact with the bed. I think this happened too early, on the first layer of the second object. I'm guessing this is a bug in which the first "layer" ends at the first object.

I don't have a fan, I only make use of slowing down the feed-rate when layers are too short.

**Comment by lordofhyphens** [comment]
Works in the test cases I have a available. Please consult the contributing guidelines and reopen with information if you still have an issue.
