### ISSUE TITLE
FR: fanning out infill to  support the top

### ISSUE THREAD

**Issue by o-jasper** [alexrj/Slic3r#1519]
Sometimes you want to use really low infill, but you do want to guarantee the top layers are supported, maybe there should be some configuration that allows the internal support structure that exists to fan out a bit near the top.

Of course, you could use a higher infill density and `--infill-only-where-needed`, but that often doesnt get the effect that is desired, it is often still more density than the user wants and if the perimeters are especially thin, it might be a bit translucent and have inner towers visible a bit.

**Comment by lordofhyphens** [comment]
Is this still a problem in 1.3.0-dev? The current design is built around putting bridging layers in upper solid infills, so I suspect what is described here is not longer an issue. 

Going to  close, please reopen with current test case (STL, layer screencap from slicer and config) if it's still a problem for you.
