### ISSUE TITLE
Option to use firmware-controlled toolhead offset (M218)

### ISSUE THREAD

**Issue by whosawhatsis** [alexrj/Slic3r#1521]
Thanks for adding the G10/G11 option. I haven't tried it because my attempts to build for Mac failed, but I'm looking forward to trying it in the next release.

Marlin has an option to set toolhead offsets by gcode, but does not (yet) allow this value to be saved in EEPROM. Like the firmware-controlled retract option, it would be nice if Slic3r had an option to send an M218 code to pass toolhead offsets to the firmware rather than passing modified coordinates (which, among other things, breaks gcode previewing). This would also make it possible to adjust the offsets just by modifying one line (or even adjusting it mid-print, which would be hugely useful for calibration) without re-slicing. Slic3r would just have to take the offsets set under printer settings and add the following line after the start.gcode for each extruder:

M218 - set hotend offset (in mm): T\<extruder_number\> X\<offset_on_X\> Y\<offset_on_Y\>

This could, of course, also be added to the start.gcode, but it would be easier for users to break something while trying to modify the values.

This feature will also aid the transition of these types of features into firmware control, where they should be.

**Comment by lordofhyphens** [comment]
It's been 2+ years with nobody else adding anything. Closing.
