### ISSUE TITLE
Bug: Setting acceleration for bridge affects infill's acceleration

### ISSUE THREAD

**Issue by nothinman** [alexrj/Slic3r#1522]
Hi,

I've verified the gcode, and it looks like slic3r detects what should be a solid infill as a bridge, and destroys the print. I can use high acceleration when printing outside shell or bridge, but not infill, as this causes blobs. Smooth areas are 3000 accel, rough -- 9000.
![dsc_4543](https://f.cloud.github.com/assets/812113/1518276/ab722dbe-4b34-11e3-9d96-6aadf6709f4c.jpg)

It sets acceleration to 9000, instead of 3000, for some parts of the infill thinking it's a bridge.

G-Code that's wrong (+slic3r settings):
![gcode_bad](https://f.cloud.github.com/assets/812113/1518292/f82bcdae-4b34-11e3-95c8-7810e92d566a.jpg)
G-Code file: https://www.dropbox.com/s/r7yp69a5by426ky/head%20%28repaired%29%203%20fat%20fill%20verbose.rar

G-Code that's OK (+slic3r settings):
![gcode_ok](https://f.cloud.github.com/assets/812113/1518294/027b84d4-4b35-11e3-8261-d02fd01bbbc8.jpg)
G-Code file: https://www.dropbox.com/s/meryzgja8ai7mkl/head%20%28repaired%29%203%20fat%20fill%20verbose%202.zip

Layer view (second layer):
![layer_view](https://f.cloud.github.com/assets/812113/1518304/331a4c56-4b35-11e3-9b9d-2c4e05bdc874.jpg)

Object view:
![model_view](https://f.cloud.github.com/assets/812113/1518307/3cc7d17e-4b35-11e3-9316-d1927db0871c.jpg)

Cheers,
Marcin

**Comment by lordofhyphens** [comment]
@nothinman could you check this with 1.3.0-dev or 1.2.9? 
If you are still having problems, please reopen the issue and include a copy of the STL and your exported config.ini.

**Comment by nothinman** [comment]
@lordofhyphens Sorry but this issue is 3 years old. I have stopped printing on FDMs a year ago :-) Have no way of verifying this at present...
