### ISSUE TITLE
Prerequisite failures

### ISSUE THREAD

**Issue by alexrj** [alexrj/Slic3r#1529]
Let's track here all the failures in prerequisites:
- Test::Harness has a failing test.
  Workaround: install with `cpanm --force Test::Harness`
  Upstream bug: https://rt.cpan.org/Public/Bug/Display.html?id=75375
- Wx 0.9922 fails to compile.
  Workaround: install the previous version with `cpanm Wx~0.9921` (no need when using CitrusPerl because it already ships with a precompiled working Wx)
  Upstream bug: https://rt.cpan.org/Public/Bug/Display.html?id=88101
- OpenGL fails to compile on Windows 64-bit when using CitrusPerl because CitrusPerl's MinGW doesn't ship a precompiled FreeGLUT (while Strawberry Perl does) and the precompiled one that ships with the OpenGL module itself is compiled for 32-bit.
  Workaround: use Strawberry Perl or install the OpenGL module manually after replacing FreeGLUT.dll with a precompiled 64-bit one.
  Upstream bug: http://sourceforge.net/p/pogl/bugs/4/

While these issues are not under our direct control we should address all of them with automatic workarounds in Build.PL.

**Comment by lordofhyphens** [comment]
@alexrj can I close this then?

**Comment by lordofhyphens** [comment]
Okay, closing. We've largely superseded these issues ^^;
