### ISSUE TITLE
Out of bound moves for circular build plate

### ISSUE THREAD

**Issue by mrbi11** [alexrj/Slic3r#1544]
Am testing rostoc max to see how big a circle can be printed, it is supposed to do 140mm.
Tests manually show it can only handle 138mm radius moves.
attached file is .stl of circle from 136 to 138mm inner/outer radius.
settings turn off brim and skirt.

The printer size is set to 276 by 276, but as you know this is a round printer.
Still, there should be no moves beyond 138,
Actually sqrt (x^2+y^2) should be less than 138.
Which is why i turned brim and skirt off.

After half a circle, slicr generates these mostly out of bound moves:
G1 Z1.500
G1 X70.470 Y-122.133
G1 X51.550 Y-131.245
G1 X31.340 Y-137.479
G1 X10.500 Y-140.614
G1 X-10.500 Y-140.614
G1 X-31.413 Y-137.462
G1 X-51.480 Y-131.272
G1 X-58.519 Y-127.889
G1 X-70.536 Y-122.095
G1 X-68.719 Y-117.323
G1 Z0.500

The center moves crash the Z axis (Y Cartesian axis) 
carriage into the base of the unit.
This gets the position off, and it starts printing in the air in the wrong x-y coordinates.

It appears these moves backtrack the print moves several mm outside the print.
They could simply move to the next coordinate, so i am assuming this is due to the don't cross perimeters setting.

I also had rafting on, so it appears to be laying down a raft layer first.

Anyway, quite startling when the printer starts banging into itself.

I'd also assume the arduino controller code would limit moves here,
and will be checking settings and code there.

I dont see how to upload the .stl file. I will try to email it, but if i fail

please email me at b k 6 at m e
dot com

also, i am happy to review the code to see if i can determine a fix, if you can point me to the right module or something, assuming you would like me to.

**Comment by thinkyhead** [comment]
Two places the code checks for out-of-bounds conditions:

At https://github.com/mrbi11/Repetier-Firmware/blob/work092/src/ArduinoAVR/Repetier/motion.cpp#L1245 the carriages are prevented from moving above the endstops, while the `transformCartesianStepsToDeltaSteps` function at https://github.com/mrbi11/Repetier-Firmware/blob/work092/src/ArduinoAVR/Repetier/motion.cpp#L885 will return 0 in any case where the printer tries to move out of bounds. So these are the bits of code we would need to glean from.

**Comment by lordofhyphens** [comment]
@mrbi11 going to close this, it's not Slic3r's job to prevent dangerous (to the printer firmware) moves (out of bed or otherwise); that belongs to the printer firmware. The bed representation is there to guide a user to making correct decisions.
