### ISSUE TITLE
Please Simplify Raft Geometry

### ISSUE THREAD

**Issue by cakeller98** [alexrj/Slic3r#1546]
Rafts should be simple and easy to print, especially for super complex objects with multiple small points that touch the bed.

slicer has this really bad habit of making a gigantic mess of the raft which makes a big gigantic mess of the print 9 of 10 times.

I want a raft that is JUST the support pattern with a brim... maybe make slicer super simplify the drop-shadow of the 3d part smooth it out, and get rid of any raft perimeters smaller than the support spacing? or 2x support spacing? or just pick a number LARGER than 6mm diameter, as a 5mm loop of plastic on the bed doesn't stick too well, and is easily dislodged and once dislodged can interfere witht he rest of the raft.... and when there are dozens of 1-2mm diameter loops .... fughetaboutit... somethings going to come up even on the most well prepared base - unless you go ridiculouslowly

**Comment by lordofhyphens** [comment]
@cakeller98 Those zip files won't unzip for me.

Is this still a problem?

**Comment by lordofhyphens** [comment]
@cakeller98 I can't get your test files to unzip (looks like they're corrupted?). Is this still a thing that is a problem?

**Comment by cakeller98** [comment]
The test case geometry is simple.  Small footprints with large overhanging area reqiiring a support.  This request is so old i have no idea where the original files are.  Sorry the zip is corrupt, i cant help with that.  If you think this is important please open a new case, i have moved on.
