### ISSUE TITLE
Feature request: Realeaux trianglular build platform for delta printers

### ISSUE THREAD

**Issue by TTN-** [alexrj/Slic3r#1550]
Could we have an feature under the Plater tab in slic3r where the build platform is the shape of a realeaux triangle? That way us delta users can have our printers stay within its build area while still being able to use all of it easily.
This would be useful especially when trying to print something that is quiet long and tricky to get a good layout for.

Something like this:
![featurerequest](https://f.cloud.github.com/assets/6019316/1607119/89a2c1f0-546f-11e3-944f-2d1b90736198.jpg)

**Comment by alexrj** [comment]
This can be now accomplished by supplying an STL file with the custom bed shape. Slic3r now support any shape.
