### ISSUE TITLE
Avoid crossing perimeters is slow (was: 1.0.0RC1 hangs exporting gcode)

### ISSUE THREAD

**Issue by Jerrill** [alexrj/Slic3r#1555]
When trying to export gcode for this model using these setting, Slic3r hangs "Exporting G-code to..." 

Here are the files required to reproduce the issue:

https://github.com/Jerrill/files-for-issues/tree/master/slic3r-1.0.0RC1/01

I'm running the Max OSX version of Slic3r.

**Comment by lordofhyphens** [comment]
Is this still a problem in 1.3.0-dev or https://github.com/alexrj/Slic3r/files/336282/slic3r-most_prs.zip ? Please reopen if it is.

avoid_crossing_perimeters is a much more complex problem as well, so it is going to be slower in general than not doing so.
