### ISSUE TITLE
Problem when trying to build slic3r.pl

### ISSUE THREAD

**Issue by krizzap** [alexrj/Slic3r#1557]
First off, forgive me because I am new to linux (Ubuntu), I'm using it for slic3r because I couldn't for the life of me get perl to run correctly in windows. I updated to the most recent clone (1.0.0RC1) but didn't bother to rebuild, It opened fine when I ran ./slic3r.pl but any stl I feed it comes out looking strange in the plater screen:
![screenshot from 2013-11-24 20 05 03](https://f.cloud.github.com/assets/5056180/1610593/092a04c0-5587-11e3-86ba-d70aea5683c6.png)
So I went ahead and tried to rebuild it with "perl Build.PL" but it fails MANY of the tests, this is from my terminal:

#   Failed test 'gear simplified to a single polygon'
#   at t/clean_polylines.t line 65.
Can't use an undefined value as an ARRAY reference at t/clean_polylines.t line 67.
# Looks like you planned 6 tests but ran 3.
# Looks like you failed 1 test of 3 run.
# Looks like your test exited with 255 just after 3.
t/clean_polylines.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/6 subtests 
t/clipper.t .......... ok   
t/collinear.t ........ ok     
t/combineinfill.t .... 1/3 
#   Failed test 'spurious fill surfaces found on layers that should have none (walls 0.0000 degrees off vertical)'
#   at t/combineinfill.t line 59.

#   Failed test 'spurious fill surfaces found on layers that should have none (walls 0.0003 degrees off vertical)'
#   at t/combineinfill.t line 59.

#   Failed test 'spurious fill surfaces found on layers that should have none (walls 2.8624 degrees off vertical)'
#   at t/combineinfill.t line 59.
# Looks like you planned 3 tests but ran 6.
# Looks like you failed 3 tests of 6 run.
t/combineinfill.t .... Dubious, test returned 3 (wstat 768, 0x300)
Failed 2/3 subtests 
t/cooling.t .......... ok   
t/custom_gcode.t ..... ok   
t/dynamic.t .......... skipped: variable-width paths are currently disabled
t/fill.t ............. ok     
t/gcode.t ............ ok   
t/geometry.t ......... ok     
t/layers.t ........... ok   
t/loops.t ............ skipped: temporarily disabled
t/multi.t ............ Failed 1/1 subtests 
t/perimeters.t ....... 1/6 
#   Failed test 'move inwards after completing external loop'
#   at t/perimeters.t line 72.

#   Failed test 'avoid starting from convex points'
#   at t/perimeters.t line 94.

#   Failed test 'only overhang layer has more than one speed'
#   at t/perimeters.t line 137.
#          got: '0'
#     expected: '1'
t/perimeters.t ....... 6/6 
#   Failed test 'no superfluous extra perimeters'
#   at t/perimeters.t line 168.
# Looks like you failed 4 tests of 6.
t/perimeters.t ....... Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/6 subtests 
t/polyclip.t ......... ok     
t/print.t ............ ok   
t/retraction.t ....... ok     
t/shells.t ........... 1/12 
#   Failed test 'insufficient number of bottom solid layers'
#   at t/shells.t line 43.

#   Failed test 'excessive number of bottom solid layers'
#   at t/shells.t line 44.

#   Failed test 'insufficient number of top solid layers'
#   at t/shells.t line 47.

#   Failed test 'excessive number of top solid layers'
#   at t/shells.t line 48.
t/shells.t ........... 7/12 
#   Failed test 'correct number of top solid shells is generated in V-shaped object'
#   at t/shells.t line 83.
#          got: '0'
#     expected: '3'

#   Failed test 'shells are not propagated across perimeters of the neighbor layer'
#   at t/shells.t line 114.
#          got: '0'
#     expected: '3'
t/shells.t ........... 10/12 
#   Failed test 'no superfluous shells are generated'
#   at t/shells.t line 137.
#          got: '0'
#     expected: '6'
t/shells.t ........... 13/12 
#   Failed test 'no gaps in spiral vase (hollow model)'
#   at t/shells.t line 167.
#          got: '639'
#     expected: '0'
t/shells.t ........... 15/12 # Looks like you planned 12 tests but ran 16.
# Looks like you failed 8 tests of 16 run.
t/shells.t ........... Dubious, test returned 8 (wstat 2048, 0x800)
Failed 7/12 subtests 
t/skirt_brim.t ....... 1/2 
#   Failed test 'wrong number of layers with skirt'
#   at t/skirt_brim.t line 39.

#   Failed test 'skirt_height is honored when printing multiple objects too'
#   at t/skirt_brim.t line 43.

#   Failed test 'brim is generated'
#   at t/skirt_brim.t line 68.
#          got: '0'
#     expected: '1'
# Looks like you planned 2 tests but ran 3.
# Looks like you failed 3 tests of 3 run.
t/skirt_brim.t ....... Dubious, test returned 3 (wstat 768, 0x300)
Failed 2/2 subtests 
t/slice.t ............ skipped: temporarily disabled
t/support.t .......... ok     
t/svg.t .............. ok   
t/threads.t .......... ok   
t/vibrationlimit.t ... ok   

Test Summary Report
-------------------
t/clean_polylines.t (Wstat: 65280 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 6 tests but ran 3.
t/combineinfill.t  (Wstat: 768 Tests: 6 Failed: 5)
  Failed tests:  1, 3-6
  Non-zero exit status: 3
  Parse errors: Bad plan.  You planned 3 tests but ran 6.
t/multi.t          (Wstat: 139 Tests: 0 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
t/perimeters.t     (Wstat: 1024 Tests: 6 Failed: 4)
  Failed tests:  3-6
  Non-zero exit status: 4
t/shells.t         (Wstat: 2048 Tests: 16 Failed: 11)
  Failed tests:  1-4, 8-10, 13-16
  Non-zero exit status: 8
  Parse errors: Bad plan.  You planned 12 tests but ran 16.
t/skirt_brim.t     (Wstat: 768 Tests: 3 Failed: 3)
  Failed tests:  1-3
  Non-zero exit status: 3
  Parse errors: Bad plan.  You planned 2 tests but ran 3.
Files=26, Tests=209, 44 wallclock secs ( 0.11 usr  0.05 sys + 31.53 cusr  1.13 csys = 32.82 CPU)
Result: FAIL
Some tests failed. Please report the failure to the author!

Honestly.. I don't know what any of this means, again I'm sorry! What can I do to get this working?

**Comment by lordofhyphens** [comment]
99.5% this isn't an issue anymore.
