### ISSUE TITLE
Support not generated under small gaps in 1.0.0RC1

### ISSUE THREAD

**Issue by tmenet** [alexrj/Slic3r#1565]
Support is missing under protruding portion of part. It is only about 0.8mm above the surface but gets no support. Also note that support that was being generated elsewhere on part is missing on the first layer  of the protrusion.

Here is layer #3 at 0.2 mm per layer (layers below #3 also have no support.)

![layer_3](https://f.cloud.github.com/assets/1181498/1616482/b92fff12-560b-11e3-88fd-2e1b038b3576.png)

and here is base of protrusion at layer 4 (note all other support is missing on this layer and every other layer?)

![layer_4](https://f.cloud.github.com/assets/1181498/1616506/39840b4a-560c-11e3-9c8a-250d42ccfac1.png)

stl, gcode and config file are in zip at dropbox 
https://dl.dropboxusercontent.com/u/3734131/support_not_generated.zip

Thanks for an awesome program...

Albert

**Comment by lordofhyphens** [comment]
Could you check to see if this has been fixed in 1.2.9? If it hasn't reopen the issue :)
