### ISSUE TITLE
Odd placement of scaled parts in master

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#1577]
Running the latest git head, I've experienced the following issue:

1. I added a large STL, much larger than the bed size, and scaled it to 20%
2. I added a second large STL, and scaled that to 20% also

When this is done, the two parts are placed on top of each other, so auto-placement has failed for some reason. When I try the same with 0.9.10b, these two parts are not placed on top of each other after being scaled, as expected.

Let me know if you want some sample STLs.

**Comment by alexrj** [comment]
This was fixed sometime in the past, so we can close it.
