### ISSUE TITLE
Core dump in current git head (yep, another one)

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#1581]
I get this core dump while slicing some parts, not all. The part should be fairly plain and simple, but it is huge and I'm scaling it down quite a lot in slic3r.

To reproduce this core dump while slicing, I have to use the GUI:

config: https://raw.github.com/kefir-/M2-config/master/slic3r-config-PLA.ini
part: http://kefirshare.dreamhosters.com/kasper.stl

Method to dump core:
1. Checked out latest git head, sudo perl Build.PL (and then --gui)
2. Run slic3r gui
3. Load config
4. Load kasper.stl
5. Scale to 20%
6. Generate gcode - slicer dumps core

A workaound appears to be to run from the command line, something like this, this does not dump core:

./slic3r.pl --load slic3r-config-PLA.ini --scale 0.2 kasper.stl

I'm trying to slice without scaling, and "Infilling layers..." is taking ages to finish, but I think it got past the point where it usually dumps core, so this appears to avoid the problem as well.

**Comment by alexrj** [comment]
Okay, this doesn't crash in 1.2.6-dev:

![schermata 2015-01-30 alle 21 27 35](https://cloud.githubusercontent.com/assets/594957/5982767/db2fd81c-a8c6-11e4-84a1-7c0082b4313b.png)
