### ISSUE TITLE
From time to time no support is generated on some single layers.

### ISSUE THREAD

**Issue by MaikStohn** [alexrj/Slic3r#1583]
Hello, this is a follow up of the initial support problem I had with old 0.9.11-dev version (which seems to be fixed): #1453 

To reproduce this the same STL/INI from the old issue report can be used.
(Full ZIP archive containing Slic3r.ini, STL, GCode and pictures: http://www.stohn.de/Slic3r-0.9.11-dev-Support-Problem.zip)

Version: Current GIT-HEAD
Problem: 
Support is not generated for every layer. It looks like support is totally skipped on some layers:

Layer 1:
![layer1](https://f.cloud.github.com/assets/1702183/1675635/75bba2a0-5d0d-11e3-9502-b37edd4e2f5d.PNG)
==> Support is correct, but BRIM looks a bit strange on lower left corner?

Layer 2:
![layer2](https://f.cloud.github.com/assets/1702183/1675648/9b1c4c5c-5d0d-11e3-9997-4b283d2663b5.PNG)
==> No support generated!

Layer 3:
![layer3](https://f.cloud.github.com/assets/1702183/1675653/a866042a-5d0d-11e3-8ef0-9a5228185042.PNG)
==> OK: Support is there.

Layer 4:
![layer4](https://f.cloud.github.com/assets/1702183/1675664/c8f2447e-5d0d-11e3-8c0e-a59872241775.PNG)
==> No support generated!

Layer 5:
![layer5](https://f.cloud.github.com/assets/1702183/1675669/dd0cc420-5d0d-11e3-9878-c0cc47a058c3.PNG)
==> No support generated!

Layer 6:
![layer6](https://f.cloud.github.com/assets/1702183/1675679/f45b5b78-5d0d-11e3-810e-da1a8a72f817.PNG)
==> OK: Support is there.
...

**Comment by MaikStohn** [comment]
Looks like it disappeared in one of the latest versions (I tried experimental and all is fine now)

**Comment by alexrj** [comment]
Thank you for checking and updating @MaikStohn, much appreciated
