### ISSUE TITLE
Feature request: avoid spots on print bed.

### ISSUE THREAD

**Issue by CTLS** [alexrj/Slic3r#1584]
I was thinking it would be cool if you could set general shapes on spots you don't want the print head to hit.  For example if your using clips to hold print bed to  heating element you could place a rectangle area over where it should avoid and then the printer will avoid it.  You could also set it to avoid bed corners if your bed corners are above the bed surface.  I believe auto homing would become a problem though.

**Comment by lordofhyphens** [comment]
Fixed via STL bed shape.
