### ISSUE TITLE
minor issues with build instructions

### ISSUE THREAD

**Issue by mrbi11** [alexrj/Slic3r#1587]
These are all doc issues, so it seems inappropriate to add multiple issues.

Issue 1, conflicting info on perl/strawbery/citrus/freeglut
I am trying to decide which perl to install to compile slic3r.

Github slic3r Issue #1297 suggests use Citrus
  because Strawberry+ freeglut has x64 issues.
But on page
https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-Windows
It says using Strawbery 
  because Citrus+Freeglut has x64 issues.

Which if any is correct or up to date?
# 

Issue 2, conflict in instructions for build
https://github.com/alexrj/Slic3r says
$ git clone https://github.com/alexrj/Slic3r.git
$ cd Slic3r
$ sudo perl Build.PL
$ sudo perl Build.PL --gui
$ ./slic3r.pl

> > Following the instructions yields error for command sudo, as its source/installation is unexplained.

https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-Windows
says:
cd Slic3r
perl Build.PL
perl Build.PL --gui

which appears to try and work, but gives many errors, including
$cpanm and $mingw and other modules.
# 

Issue 3 cpan
https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-Windows
says:
The Slic3r depends on few modules. We will be downloading, compiling and installing them. The >cpan< tool will do the magic for us.

But instructions leave above modules unloaded (apparently) with errors like:
Global symbol "$cpanm" requires explicit package name at .\Build.PL line 71.
Global symbol "$module" requires explicit package name at .\Build.PL line 71.
# 

Not really a different issue, but neither sudo or cpan appear to be sourced in instructions.

My guess is sudo is not needed (or no longer needed?) with Citrus perl.

However, cpan is not doing any "magic", and does appear to be needed.

Thanks for reading.

**Comment by lordofhyphens** [comment]
Are you sure you were using windows instructions on windows and linux instructions linux?

**Comment by lordofhyphens** [comment]
No response to questions, we have a working build server output at https://bintray.com/lordofhyphens/Slic3r/slic3r_dev and the perl dependencies are now available for download for strawberry perl 5.18 (x64) and 5.24 (32bit). 

Closing.
