### ISSUE TITLE
Missing XML::SAX in Linux binaries (was: Slic3r 1.0RC1 crashes on Linux when loading AMF.xml file)

### ISSUE THREAD

**Issue by jbernardis** [alexrj/Slic3r#1592]
XML::SAX package is missing from the Linux package.  As a result, when loading an amf.xml file, Slic3r crashes and writes "AMF Parsing requires XML::SAX" to the console

**Comment by Darker** [comment]
Still not fixed in 1.30 on Windows.

Also, it's nice to make it possible to copy version info from the Help - About window.
