### ISSUE TITLE
M218 for extruder offsets

### ISSUE THREAD

**Issue by whosawhatsis** [alexrj/Slic3r#1596]
Like my previous suggestions, I would like to see an option to use firmware-controlled extruder offsets Marlin supports setting offsets with the following code: 

// M218 - set hotend offset (in mm): T<extruder_number> X<offset_on_X> Y<offset_on_Y>

It does not (yet) support storing these values in EEPROM, but Slic3r could send these offsets along with the start code for dual extruder prints. Of course, users could add this to the start gcode themselves, but this would create confusion for users who see the offsets listed under extruder settings as well (and you don't want to offset it twice!), and it would require users to understand the gcode and write it without errors (and there are now many less sophisticated users).

**Comment by lordofhyphens** [comment]
We have a toolchange gcode now; and is this in Marlin now?

Please reopen if you feel this is still necessary.
