### ISSUE TITLE
Brim causes moves off the platform

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#1597]
I'm slicing some parts with slic3r 1.0.0RC1, and have some issues with moves outside my platform. I'm printing with brim enabled, and I have enabled "avoid crossing perimeters", which I assume has something to do with this issue. I'm also guessing that this happens because the platform is quite full.

As the brim is being drawn, the nozzle sometimes moves around in an odd pattern, probably to avoid crossing perimeters. However, I have seen moves crash into X=0, and when the print continues, my X axis is shifted.

Here's the first layer as shown by gcode.ws. My bed size isn't configured in gcode.ws, but I assume everything off the left side of the grid has negative X values. (I have verified negative X values in my gcode file).

![odd-brim-moves](https://f.cloud.github.com/assets/684832/1696328/4e74b4c8-5ec2-11e3-84ff-708da386d23a.jpg)

In any case, I guess the distance of these moves off the actual print could be limited, or is there any reason why the nozzle is moved so far outside the print?

The gcode was made up of 3 STL files, which I added, then scaled to 20% and rotated 90 degrees in the GUI. My bed is 200mm x 250mm, so the longest part just fits in the Y direction.

STL files:
http://kefirshare.dreamhosters.com/johannes.stl
http://kefirshare.dreamhosters.com/herman.stl
http://kefirshare.dreamhosters.com/beatrice.stl

GCODE:
http://kefirshare.dreamhosters.com/johannes_20131206-220820_1.0.0RC1.gcode

CONFIG:
http://kefirshare.dreamhosters.com/config-brim.ini

I tried with 0.9.10b as well, and got a lot more moves into negative Z there.

I appear to have managed to work around the issue for now by shifting the print center in my slic3r configuration.

**Comment by lordofhyphens** [comment]
Your firmware can (and probably should) be configured to disallow bad moves like this (soft endstops).

**Comment by kefir-** [comment]
I'm pretty sure this isn't an issue any more...
