### ISSUE TITLE
Doubly-nested shells don't work as expected.

### ISSUE THREAD

**Issue by pdbogen** [alexrj/Slic3r#1600]
I think my terminology is right. Anyway, here's the situation. Consider the following simple SCAD file:

```
difference() {
    cylinder( r=10, h=10 );
    cylinder( r=5, h=10 );
}
cylinder( r=4.99, h=10 );
```

This should print a cylindrical tube, with a cylinder inside it. It's of course very unlikely that I have a printer that will print these in such a way that they're a separate object. That's OK. What happens is that I'm guaranteed to have a cylindrical perimeter extending through the solid object. This is more important when the "filling" cylinder continues up, and is relatively small compared to the surface; for example, the shaft of a spindle. Consider this slightly modified SCAD:

```
difference() {
    cylinder( r=10, h=10 );
    cylinder( r=2, h=10 );
}
cylinder( r=1.99, h=20 );
```

With the continuous perimeter, the shaft is vastly less likely to snap off. When its perimeter is printed only beginning at the top surface of the larger base cylinder, it very easily breaks off at that interface/transition.

I bisected this down to 3bcf1da7025fabe761704cef7386a12fe79e1bcc. It appears that this may have solved some other problems? Or perhaps it was only determined to not be beneficial. However, it's caused this regression.

I'd appreciate guidance if there's a better way to accomplish what I'm attempting, though.

I'm guessing there's some code that detects the gap is too close together and fills it in? Increasing the gap to 1mm prints the objects nested as expected. Is there a way to turn this off?

**Comment by lordofhyphens** [comment]
Could you add pictures, a config where this is a noticeable problem, and STL (or AMF) files?

Also please check and see if this affects 1.2.9 or 1.3.0-dev.

**Comment by lordofhyphens** [comment]
Try splitting the model; OpenSCAD is generating one model with 2 shells in it that seem to be close enough together as to confuse Slic3r.

![image](https://cloud.githubusercontent.com/assets/31754/25068012/fc8e5dce-221a-11e7-85f2-d6fdb6f188eb.png)

Closing as I never got any response with a test STL (or better, AMF) and settings and screenshots to show what is going on.
