### ISSUE TITLE
[master] Multiple Objects (Different STL or Multiple Copies) Results in Ridiculously High Move Cooredinates

### ISSUE THREAD

**Issue by pdbogen** [alexrj/Slic3r#1603]
This is with a02ce3257ef4b37dd9590d61ad713e05d4201092, which at the time of writing is master/HEAD.

STL: https://gist.github.com/pdbogen/5a5692d853cbd3c93d85
Config: https://gist.github.com/pdbogen/9f9ac5278d1682a6a61d
Result (snippet): https://gist.github.com/pdbogen/43b121d92369bd212891

Just the first 50 lines of the gcode output, but you can see the moves.. don't make sense:
```
G1 X-4999915.780 Y-4999901.430 E5.13398 F1800.000
```

While I wish I had a 5km 3D printer.. I don't. 

I tried to dig around in the history to see if I could find when this bug was introduced. I confirmed it as far back as master~8 (3fca0956bca76ca0cca28ea047d76bbf37bf25af); builds before that as far back as master~30 either (a) couldn't build xs, or (b) segfaulted as soon as I added an object to the plater, so I couldn't test them.

**Comment by lordofhyphens** [comment]
It's working now.
