### ISSUE TITLE
Arc compensation feature request

### ISSUE THREAD

**Issue by justmyopinion** [alexrj/Slic3r#1613]
A persistent problem that seems to be with all slicers (or fw)  is that holes are generally printed too small in the area of 0.5-1  extrusion width. I do not know whether this could be solved in FW but it would be nice if other solutions could be present to solve this  or at least compensate for, other than design compensations.I regard this a general problem and not a bug nor Slic3r specific.
A switch/parameter  for some arc compensation would be nice.
articles about this has been discussed widely in slicer forums:
http://reprap.org/wiki/ArcCompensation
http://fabmetheus.crsndoo.com/wiki/index.php/Skeinforge_Stretch
http://hydraraptor.blogspot.dk/2011/02/polyholes.html

**Comment by ClusterM** [comment]
@alexrj I think that it should be optional feature. And with some settings to tune hole sizes.
