### ISSUE TITLE
Support decimal scaling factors (was: Scale factor arbitrarily rounded to nearest percent)

### ISSUE THREAD

**Issue by darrenfreeman** [alexrj/Slic3r#1617]
Slic3r 0.9.9

I just calculated that, in order to make two parts fit, I needed to scale one of them to 97.5 %. However the box only lets you enter an integer number of percent.

Please fix!

**Comment by Wnt** [comment]
Could you change the scaling dialog to also support user input as permillage in addition to a percentage? This might be a quick fix for most use cases.

To be able to print exact dimension objects I always need to scale my prints to 100.5% - 100.7% on X & Y axis depending on the plastic I use. Nowadays I use Blender to do this, but I would really like to get rid of that part in my workflow.

**Comment by lordofhyphens** [comment]
The problem noted above is that the routine we use to get numbers from the user only supports integers.

**Comment by Patola** [comment]
I second this issue. I also have the need for non-integer numbers when scaling, although for a quite different use case than his.

**Comment by claell** [comment]
+1 for this.

**Comment by alexrj** [comment]
Fixed!
