### ISSUE TITLE
Application crashes with a 437Mb STL, OSX 10.8.5

### ISSUE THREAD

**Issue by sejohnso** [alexrj/Slic3r#1618]
Hi everyone,

I've tried to upload a 437 meg .STL file and Slic3r crashes after about 30 seconds of processing.
The file is a fan duct to redirect the power supply cooling air away from the print bed on a Medelmax 2. lots of complex bends……
System used: Macbook pro 17 early 2011 with 10.8.5

If someone wants the file to try let me know (need an FTP to send it to….)

Thx.
sejohnso

**Comment by lordofhyphens** [comment]
@sejohnso you should be able to zip up something that big and drop it onto Github. I'm going to close this for now, let me know if you are still having large file crash problems.
