### ISSUE TITLE
Feature request: definable infill pattern

### ISSUE THREAD

**Issue by nothinman** [alexrj/Slic3r#1620]
Hi,

I came up with this idea while printing with 0.15mm layers. I've noticed that objects aren't as strong as when printed with 0.30mm layers.
I know you can increase the width for infill, but this isn't as precise as using thin lines for infill.
Let focus on rectilinear pattern and 0.15mm layers.
Instead of extruding at 200% to achieve 0.3mm, we could have 2x 100% lines. This produces better quality prints and parts are stronger.
I would actually like to be able to create a pattern based on 1s and 0:
So we could have standard 1010101010....
Or define something like 110011001100...
Or 111000111000, or 111100111100, or whatever.
I'm guessing this would be rather easy to implement but would allow us to create stronger infill for fine resolution parts, so there's a real gain in here.

What do you think?

Thanks,
Marcin

**Comment by lordofhyphens** [comment]
I had thought I'd seen an issue for custom infills, but apparently not.

**Comment by lordofhyphens** [comment]
#942 Found it ;)
