### ISSUE TITLE
Feature request: Extruder multiplier not only for filament but for each extruder

### ISSUE THREAD

**Issue by drakpappan** [alexrj/Slic3r#1622]
As it is now there is a multiplier in the filament setting. This is good to have when there is a difference in filament diameter and you don't want to change the explicit value of the diameter. But as it is for me when i have one extruder stepper motor that is offset in number of steps/mm it would be better to have yet another multiplier for each extruder. This way I don't need to remember which filament color I used in which extruder when I change colors.

Thanks!

**Comment by alexrj** [comment]
So, this is still needed because firmware implementations like Marlin still don't have separate steps/mm settings for each extruder (https://github.com/MarlinFirmware/Marlin/issues/1342)

**Comment by drakpappan** [comment]
Yes, i would say so.

**Comment by alexrj** [comment]
Marlin now supports distinct steps/mm for each extruder. Smoothie does too. I don't know about others but I think we can assume this is an industry standard for firmware capable of handling multiple extruders, so we don't need to add this workaround in Slic3r.
