### ISSUE TITLE
Fill inn seems to be inaccurate at least with thin walls

### ISSUE THREAD

**Issue by justmyopinion** [alexrj/Slic3r#1624]
If I make a testcylinder of say, 1.5mm walls and extrusion width of 0.5, I would expect 2 outer perimeters generated and fillin of a third line between the two perimeters all with extrusion width of 0.5 mm. Well it never happens. Perimeters are fine but infill is always zigzagging between perimeters making infill very inconsistent and make influence on output  quality and print speed.
It is not possible to select an extrusion width to get infill make a line. Worst case it is omitted but mostly it is zigzagging. it seems that it never find a calculation to fit in between perimeters and have a deadzone for this.

I really cannot figure out how you guys add pictures to this forum :-(

**Comment by lordofhyphens** [comment]
Gapfill.
