### ISSUE TITLE
Drag-and-drop issue

### ISSUE THREAD

**Issue by justmyopinion** [alexrj/Slic3r#1625]
Normal way of starting slic3r is to start the program and drag-and-drop an object to the platter and export gcode file. This normally works and Config files used are the latest used  I assume which is remembered in program.
In windows it is also possible to drag-and-drop the object to the program icon on desktop and that also results in an immediate slicing and exporting gcode file without opening the slicer. Amazing..but problem is that slicing is using default settings for the slicing and not the last one used as mentioned above.
Is this way of fast slicing illegal and non intentional or a feature?

**Comment by lordofhyphens** [comment]
@justmyopinion It's calling it as a CLI program with the defaults. If you wanted to call slic3r with specific settings you'd need to create shortcuts or batch files to append the extra information to the command line.

Google search for "windows batch file arguments" for some examples. 

Closing, as nothing is actually wrong here :)
