### ISSUE TITLE
on Linux/Xwindows does not honor the DISPLAY environment variable

### ISSUE THREAD

**Issue by wolfmanjm** [alexrj/Slic3r#1631]
Log into a server with ssh -X host then run Slic3r, the display should come up on the machine that ssh was run from but it pops up on the remote host instead.

Most X programs use the DISPLAY env variable and open the windows on whatever DISPLAY is set to.

**Comment by lordofhyphens** [comment]
I think that it's actually working now, but an unrelated issue for me prevents me from testing it properly. 

 https://devtalk.nvidia.com/default/topic/891349/quadro-k600-x_glxcreatecontext-issue/?offset=6

**Comment by djdelorie** [comment]
I tested today's git slic3r on a headless VM in my basement, setting DISPLAY explicitly to my machine, and it worked fine (except the GL images didn't render, but there's no graphics on that machine anyway)

**Comment by lordofhyphens** [comment]
What @djdelorie said. Going to close this for now.
