### ISSUE TITLE
Slicing fails with more than one thread on Linux

### ISSUE THREAD

**Issue by neildarlow** [alexrj/Slic3r#1636]
Environment: fedora 20 with slic3r 1.0.0RC1

For the default Number of threads setting of 2 or more the following error is output when attempting to slice a .stl file.

Can't locate package GLUquadricObjPtr for @OpenGL::Quad::ISA at /usr/share/perl5/vendor_perl/Slic3r.pm line 111.

Reducing the number of threads setting to 1 permits slicing to occur.

Package requirements:
[neil@corona ~]$ rpm -q --requires slic3r
/usr/bin/perl
libc.so.6()(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libperl.so.5.18()(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
perl >= 1:5.10
perl(:MODULE_COMPAT_5.18.1)
perl(Boost::Geometry::Utils)
perl(Boost::Geometry::Utils) >= 0.15
perl(Carp)
perl(Class::Accessor)
perl(Class::XSAccessor)
perl(Config)
perl(Encode)
perl(Encode::Locale)
perl(Exporter)
perl(File::Basename)
perl(File::Spec)
perl(FindBin)
perl(Getopt::Long)
perl(Growl::GNTP)
perl(IO::Scalar)
perl(List::Util)
perl(Math::ConvexHull::MonotoneChain)
perl(Math::Geometry::Voronoi)
perl(Math::PlanePath::ArchimedeanChords)
perl(Math::PlanePath::Flowsnake)
perl(Math::PlanePath::HilbertCurve)
perl(Math::PlanePath::OctagramSpiral)
perl(Math::Trig)
perl(Moo)
perl(Moo) >= 1.003001
perl(Moo) >= 1.003001
perl(OpenGL)
perl(POSIX)
perl(SVG)
perl(Slic3r)
perl(Slic3r::Config)
perl(Slic3r::ExPolygon)
perl(Slic3r::Extruder)
perl(Slic3r::ExtrusionLoop)
perl(Slic3r::ExtrusionPath)
perl(Slic3r::ExtrusionPath::Collection)
perl(Slic3r::Fill)
perl(Slic3r::Fill::ArchimedeanChords)
perl(Slic3r::Fill::Base)
perl(Slic3r::Fill::Concentric)
perl(Slic3r::Fill::Flowsnake)
perl(Slic3r::Fill::HilbertCurve)
perl(Slic3r::Fill::Honeycomb)
perl(Slic3r::Fill::Line)
perl(Slic3r::Fill::OctagramSpiral)
perl(Slic3r::Fill::PlanePath)
perl(Slic3r::Fill::Rectilinear)
perl(Slic3r::Flow)
perl(Slic3r::Format::AMF)
perl(Slic3r::Format::OBJ)
perl(Slic3r::Format::STL)
perl(Slic3r::GCode)
perl(Slic3r::GCode::ArcFitting)
perl(Slic3r::GCode::CoolingBuffer)
perl(Slic3r::GCode::Layer)
perl(Slic3r::GCode::MotionPlanner)
perl(Slic3r::GCode::Reader)
perl(Slic3r::GCode::SpiralVase)
perl(Slic3r::GCode::VibrationLimit)
perl(Slic3r::GUI::AboutDialog)
perl(Slic3r::GUI::ConfigWizard)
perl(Slic3r::GUI::ConfigWizard::Page)
perl(Slic3r::GUI::OptionsGroup)
perl(Slic3r::GUI::Plater)
perl(Slic3r::GUI::Plater::ObjectPreviewDialog)
perl(Slic3r::GUI::Plater::ObjectSettingsDialog)
perl(Slic3r::GUI::Preferences)
perl(Slic3r::GUI::SimpleTab)
perl(Slic3r::GUI::SkeinPanel)
perl(Slic3r::GUI::Tab)
perl(Slic3r::Geometry)
perl(Slic3r::Geometry::BoundingBox)
perl(Slic3r::Geometry::Clipper)
perl(Slic3r::Layer)
perl(Slic3r::Layer::Region)
perl(Slic3r::Line)
perl(Slic3r::Model)
perl(Slic3r::Point)
perl(Slic3r::Polygon)
perl(Slic3r::Polyline)
perl(Slic3r::Print)
perl(Slic3r::Print::Object)
perl(Slic3r::Print::Region)
perl(Slic3r::Print::SupportMaterial)
perl(Slic3r::Surface)
perl(Slic3r::TriangleMesh)
perl(Slic3r::XS)
perl(Storable)
perl(Time::HiRes)
perl(Wx)
perl(Wx) >= 0.9901
perl(Wx::App)
perl(Wx::DND)
perl(Wx::Dialog)
perl(Wx::Event)
perl(Wx::FileDropTarget)
perl(Wx::GLCanvas)
perl(Wx::Grid)
perl(Wx::Html)
perl(Wx::Panel)
perl(Wx::Print)
perl(Wx::ScrolledWindow)
perl(Wx::StatusBar)
perl(Wx::Wizard)
perl(Wx::WizardPage)
perl(XML::SAX)
perl(XML::SAX::Base)
perl(XSLoader)
perl(base)
perl(constant)
perl(lib)
perl(parent)
perl(strict)
perl(threads::shared)
perl(utf8)
perl(warnings)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)
rpmlib(PayloadIsXz) <= 5.2-1

**Comment by hroncok** [comment]
Still happens on 1.2.9

**Comment by alexrj** [comment]
@hroncok, does this still happen with current master?
(Also, I understand you work on Fedora but I think you should test without using the RPM but using the original dependency toolchain: `perl Build.PL`)

**Comment by hroncok** [comment]
Funny thing. I guess something was updated in Fedora in the menatime, but it works even with 1.2.9 on Fedora 25.

Will try with master and Buid.PL as well just to make sure, but I think it will work.

**Comment by hroncok** [comment]
Cannot test with master, when I attempt to Quic Slice, I get "Can't locate object method "extra_variables" via package "Slic3r::GUI::MainFrame" at /home/vagrant/Slic3r/lib/Slic3r/GUI/MainFrame.pm line 420", would you like me to open another issue?

**Comment by lordofhyphens** [comment]
@hroncok yeah that's probably separate to this issue.

**Comment by hroncok** [comment]
https://github.com/alexrj/Slic3r/issues/3773

**Comment by hroncok** [comment]
Cannot reproduce on Fedora 25.
