### ISSUE TITLE
Pressure surface is rough

### ISSUE THREAD

**Issue by mlcomputer** [alexrj/Slic3r#1638]
Hello
I have problem with the surface of my printed object it is very rough because the printer goes to deep in the ABS. Now I hope everyone can help me with this problem.
Thanks in advance.

With best regards

Michael Lindenberger

**Comment by lordofhyphens** [comment]
This is not a general support forum, check out /r/3dprinting on reddit, reprap.org or #reprap on freenode IRC if you still need help with this.
