### ISSUE TITLE
Enter infill as spacing rather than percentage

### ISSUE THREAD

**Issue by inventaholic** [alexrj/Slic3r#1644]
10% infill no a small part is different than 10% infill on a large part, whereas a 10mm spacing on a small part remains a 10mm spacing on a large part. Entering infill as "spacing" rather than "percentage" would be much more predictable and consistent.

**Comment by lordofhyphens** [comment]
Since @inventaholic didn't elaborate at all when asked, going to close this. Especially as "spacing" doesn't make much sense when your infill isn't simple rectilinear.
