### ISSUE TITLE
[rfc] Linux: .desktop and AppData file

### ISSUE THREAD

**Issue by hroncok** [alexrj/Slic3r#1645]
Hi,
when packaging Slic3r for Fedora, I'm adding two files: a .desktop file and AppData file. I would like them to be located upstream, so other distros can benefit as well.

I'm not (yet) creating a pull request, as I don't know where would you like them to be located and I have further questions.

A .desktop file is used for application to be in menu, here is basically what I use in the package now:

````
[Desktop Entry]
Name=Slic3r
Exec=slic3r
Icon=/usr/share/pixmaps/slic3r.ico
Terminal=false
Type=Application
Categories=Graphics;3DGraphics;
````

An AppData file is a new freedesktop.org format for storing brief info about applications. Currently it is used by GNOME Software app introduced in Fedora 20.

More information about the format may be obtained from http://people.freedesktop.org/~hughsient/appdata/

````
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2013 Alessandro Ranellucci <alessandro@unterwelt.it> -->
<application>
 <id type="desktop">slic3r.desktop</id>
 <licence>CC-BY</licence>
 <summary>G-code generator for 3D printers</summary>
 <description>
  <p>Slic3r takes 3D models (STL, OBJ, AMF) and converts them into G-code instructions for 3D printers. It's compatible with any modern printer based on the RepRap toolchain, including all those based on the Marlin, Sprinter and Repetier firmware. It also works with Mach3 and LinuxCNC controllers.</p>
  <p>Key features are:</p>
  <ul>
    <li>additional complete command-line interface to use it with no GUI</li>
    <li>multi-material (multiple extruders) object printing</li>
    <li>multiple G-code flavors supported (RepRap, Makerbot, Mach3 etc.)</li>
    <li>ability to plate multiple objects having distinct print settings</li>
    <li>multithread processing</li>
    <li>STL auto-repair (tolerance for broken models)</li>
  </ul>
 </description>
 <screenshots>
  <screenshot type="default" width="1061" height="595">https://f.cloud.github.com/assets/2401856/1817033/e66d31a0-6f67-11e3-89d5-05c54cc6c8ab.png</screenshot>
 </screenshots>
 <url type="homepage">http://slic3r.org/</url>
 <updatecontact>alessandro@unterwelt.it</updatecontact>
</application>
````

The AppData file should be licensed with some free content license. I've chosen CC-BY, as the icons in Slic3r are licensed the same way (so the final license of the whole package isn't too complicated). But feel free to choose for example CC-BY-SA instead.

The AppData file also contain an URL of a screenshot, that should preserve it's location. I find it rather stupid, but the optimal ratio of the image should be 16:9, so I've created such screenshot and attached. It would be fine to keep this in the repo as well and update the link to something more nice.

![slic3r-screen](https://f.cloud.github.com/assets/2401856/1817033/e66d31a0-6f67-11e3-89d5-05c54cc6c8ab.png)

So, are you fine keeping this upstream? If so, where should I locate those files (and eventually the screenshot) in the repository? Are you fine with the license and content (taken from the README)?

Even if you are not willing to keep this in the repo, please provide feedback on the license, so I could manage this downstream. Currently the content, as copied form README, is probably AGPL, but that's not a content license and is not supported by AppData.

Thanks.

**Comment by lordofhyphens** [comment]
I don't know if this actually went anywhere, but I think it'd better handled as a patchset than keeping it in-repo. 

If @hroncok or @alexrj want to reopen to continue discussing then by all means :)
