### ISSUE TITLE
Feature Request: 3D Honeycomb infill

### ISSUE THREAD

**Issue by gringer** [alexrj/Slic3r#1646]
The current infill patterns (apart from concentric) seem to be 2D in nature, creating vertical walls. It would be nice to have different patterns where the fill pattern for each layer is dependent on the Z direction / height, allowing for stronger support structures with less infill.

I have an example of one such pattern here, which uses a tesselation of a truncated octahedron:

http://www.thingiverse.com/thing:214169

There are other examples of space-filling tesselations:

http://en.wikipedia.org/wiki/Honeycomb_%28geometry%29#Space-filling_polyhedra.5B2.5D

**Comment by lordofhyphens** [comment]
Yeah, it's done.

**Comment by pmarks-net** [comment]
> Also, Is it possible to complete the octahedrons by filling (bridging) the square when it is at its minimal size? Or perhaps twice in orthogonal directions.

@recmo I tried your filled-in squares idea here: https://github.com/gringer/PrusaSlicer/pull/1, [3d_honeycomb_bridged_squares.patch.txt](https://github.com/user-attachments/files/21818443/3d_honeycomb_bridged_squares.patch.txt)

I'm not really convinced that it's a good idea, for the reasons @alranel stated 10 years ago, but you're welcome to mess with it.
