### ISSUE TITLE
Feature Request - auto X, Y, Z scaling

### ISSUE THREAD

**Issue by hayedid** [alexrj/Slic3r#1656]
Hi. I have a feature request for Slic3r. I know this can be done in somewhat effectively in printer firmware by changing the steps per mm, but it would be really great if it were built into slicer.

 Attached to the 'printer' settings, it would be extremely helpful if automatic and individual X,Y,Z scaling could be included in the settings.

 When I print test objects, the objects are consistently off scale. For example, I printed a 30mm x 30mm x 30mm object. When measuring, the object produced was:

 X: 29.8 mm
 Y: 29.8 mm
 Z: 30.2 mm

 If auto X, Y, Z scaling was included in Slicer, it could take into account the auto-scaling when slicing the object so that it could print correctly.

 Incidentally, I use Slic3r through the Repetier interface. I click 'configure' and setup all my options within Slic3r, but I use the 'Slice' button within Repetier, which I believe slices the model by calling Slic3r via the command line.

Thank you. 

I also posted this on a reprap page I found.  I don't know where the proper place is to post this, but I found this after I found that page.

**Comment by alexrj** [comment]
I'm closing this because:

* we now have XYZ distinct scaling functions
* we now have XYZ mirroring functions
* we now have XY Size Compensation for handling XY size errors
* Z errors can be just fixed with a proper layer height (or with #2978)
