### ISSUE TITLE
1.0RC2 Crashes on Ubuntu Linux

### ISSUE THREAD

**Issue by jbernardis** [alexrj/Slic3r#1657]
GUI repratedly puts up dialog box:

Slic3r::Config::DESTROY() - THIS is not a blessed SV reference at /home/jeff.../lib/std/Slic3r/GUI/Tab.pm line 658

This happens 15 times and then the GUI comes up, but it crashes if I try to slice anything.  When run from the command line, in addition to the above, I see the following:

jeff@jeff-Dell-DM051:~/Downloads/Slic3r/bin$ ./slic3r
Subroutine new redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Config.pm line 1166.
Subroutine apply redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Config.pm line 1227.
Subroutine get redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Config.pm line 1252.
Subroutine set redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Config.pm line 1259.
Subroutine has redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Config.pm line 1319.
Subroutine serialize redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Config.pm line 1325.
Subroutine chained_path redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Geometry.pm line 736.
Subroutine simplify redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/ExPolygon.pm line 94.
Subroutine intersect_expolygons redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/ExtrusionPath.pm line 30.
Subroutine subtract_expolygons redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/ExtrusionPath.pm line 38.
Subroutine simplify redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/ExtrusionPath.pm line 46.
Subroutine clip_end redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/ExtrusionPath.pm line 51.
Subroutine length redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/ExtrusionPath.pm line 58.
Subroutine is_perimeter redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/ExtrusionPath.pm line 68.
Subroutine is_fill redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/ExtrusionPath.pm line 76.
Subroutine is_bridge redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/ExtrusionPath.pm line 83.
Subroutine offset redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Surface.pm line 36.
Subroutine is_solid redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Surface.pm line 51.
Subroutine is_bridge redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Surface.pm line 60.
Subroutine simplify redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Polyline.pm line 30.
Subroutine grow redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Polyline.pm line 38.
Subroutine simplify redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/Polygon.pm line 43.
Subroutine horizontal_projection redefined at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/TriangleMesh.pm line 34.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 198.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 364.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 198.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 364.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 265.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 198.
Slic3r::Config::DESTROY() -- THIS is not a blessed SV reference at /home/jeff/Downloads/Slic3r/lib/std/Slic3r/GUI/Tab.pm line 364.

This happens immediately after un-tarring the file and before I move the files into the target directory.

**Comment by alexrj** [comment]
This was fixed.
