### ISSUE TITLE
Bridging issue with 1.0.0RC1 an below

### ISSUE THREAD

**Issue by cjdavis618** [alexrj/Slic3r#1658]
I am printing a 25mm test cube that contains a small bridge and working on infill settings. 

I have found a problem that appears regardless of the infill shape that needs addressed.

I have attached the Gcode file, and also some images of the issue both printed form and hotend path.

Issues

1. On the very first Bridge junction, there is too much filament extruded even after a wipe/retract on the same layer. I can provide video of the issue if you like. This leaves a large droop of filament on the first side of the bridge.The remaining part of the bridge is good in this case and I am able to get perfectly flat junctions which is awesome. 

2. On a bridge layer, the program deposits material in the wrong order when there is inside geometry to create. It correctly runs outside to inside on this part, but refer to the Layer83, Layer84.jpg toolpath screenshots and then the image of the center of the cube. It is trying to deposit the areas in the small black squares before anything is there to support them leaving a blobbed mess. I have video where it shows it using bridging speed, but extruding over nothing with no anchor points to support it.

![layer83](https://f.cloud.github.com/assets/6147551/1825905/362920ec-71dd-11e3-99bd-322e36ccce24.jpg)
![layer 84](https://f.cloud.github.com/assets/6147551/1825906/3b379136-71dd-11e3-8f99-c83736d6f3dc.jpg)
![602](https://f.cloud.github.com/assets/6147551/1825907/444ff88a-71dd-11e3-9c3e-9fa2b0ea8b3c.jpg)
![604](https://f.cloud.github.com/assets/6147551/1825909/6469f724-71dd-11e3-858a-5fb20d1f8c6c.jpg)
![603](https://f.cloud.github.com/assets/6147551/1825916/9899a80a-71dd-11e3-88fb-fdeceac4997c.jpg)

I've tried various settings but nothing seems to change the outcome of the unsupported bridge in the four small squares on layer 84 image.

**Comment by lordofhyphens** [comment]
@cjdavis618 you never provided what was asked for (so we can reproduce). Closing. 

Please reopen with that information if it's still a problem in 1.2.9 or 1.3.0-dev.
