### ISSUE TITLE
Feature to enable/disable perimiter around support material

### ISSUE THREAD

**Issue by DwayneS** [alexrj/Slic3r#1659]
On some parts, it would be beneficial to not have a perimeter enclosing the support material. This should be an option that can be enabled disabled.

See a post about this issue on the reprap forum here: http://forums.reprap.org/read.php?1,269232,273573#msg-273573

**Comment by lordofhyphens** [comment]
@DwayneS Pillars strategy should solve this problem.  Please  reopen if it doesn't.
