### ISSUE TITLE
Avoid crossing perimeters only works for one of multiple objects

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#1662]
In current stable branch, it seems that "Avoid crossing perimeters" only works for one object when I print two of the same. Here's a screenshot, you can see that moves are crossing the perimeters several times on the lower object, but correctly avoids the perimeters on the top object:

![avoid-x-only-first](https://f.cloud.github.com/assets/684832/1830218/a7fd505c-732d-11e3-803f-8c0adecaae4d.png)

Here's my gcode and STL, config embedded in gcode by verbose option:

http://kefirshare.dreamhosters.com/avoid-crossing-example.gcode
http://kefirshare.dreamhosters.com/avoid-crossing-example.stl

I simply added the STL, and clicked "More" to print two at the same time.

**Comment by lordofhyphens** [comment]
@kefir- can you check this with 1.2.9 or 1.3.0-dev?

**Comment by kefir-** [comment]
Avoid crossing perimeteres works fine on 1.3.0-dev for this case. Thanks, and good job on going through and folllowing up on all of these old issues!
