### ISSUE TITLE
Slicr3r hangs when generating support material for Eiffile tower 

### ISSUE THREAD

**Issue by dean1873** [alexrj/Slic3r#1664]
Hi, 

 I using slic3r to generate gcode for a eiffile tower model 
(http://www.thingiverse.com/thing:53279)
 with support material, but it takes nearly an hour with 100% CPU utilization. Still, nothing comes out. 
It looks like the program hangs somewhere. Below is my configuration file for Slic3r:

 #---- main
bed_size = 150,120
print_center = 75,60
nozzle_diameter = 0.4
filament_diameter = 1.75
layer_height = 0.2
z_offset = -0.2
threads = 8
wipe = 0
rotate = 0
scale = 1

#---- temperature
temperature = 220
first_layer_temperature = 230
bed_temperature = 110
#first_layer_bed_temperature = 115 
standby_temperature_delta = -5

#---- speed
travel_speed = 1500
min_print_speed = 100
first_layer_speed = 30%
perimeter_speed = 1200
external_perimeter_speed = 60%
infill_speed = 1500
solid_infill_speed = 80%
top_solid_infill_speed = 60%
support_material_speed = 1500
bridge_speed = 1500
gap_fill_speed = 1200
vibration_limit = 0

slowdown_below_layer_time = 30
default_acceleration = 0

#---- first & last layers
first_layer_acceleration = 0
first_layer_extrusion_width = 200%
first_layer_height = 0.25
bottom_solid_layers = 5
top_solid_layers = 5

#---- fill
fill_angle = 45
fill_density = 0.4
fill_pattern = honeycomb
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
solid_fill_pattern = rectilinear
solid_infill_below_area = 70
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0
top_infill_extrusion_width = 0
randomize_start = 0

#---- perimeter
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeters = 3
start_perimeters_at_concave_points = 0
start_perimeters_at_non_overhang = 0
external_perimeters_first = 0
extra_perimeters = 1
thin_walls = 1

avoid_crossing_perimeters = 0

#---- support material
support_material = 1
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_extruder = 1
support_material_interface_layers = 3
support_material_interface_spacing = 0
support_material_pattern = rectilinear
support_material_spacing = 4
support_material_threshold = 0
raft_layers = 1

#---- gcode
g0 = 0
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
layer_gcode =
toolchange_gcode =
start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle
end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nG1 Z1500  ; lift Nozzle\nM84     ; disable motors

#--- retract
retract_before_travel = 2
retract_layer_change = 1
retract_length = 1
retract_length_toolchange = 10
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 30
use_firmware_retraction = 0
only_retract_when_crossing_perimeters = 1

#---- bridge & gap
bridge_acceleration = 0
bridge_flow_ratio = 1
gap_fill_speed = 20
overhangs = 1

#---- skirt & brim
skirt_distance = 6
skirt_height = 1
skirts = 0
min_skirt_length = 0
brim_width = 0

#---- fan
fan_always_on = 0
fan_below_layer_time = 60
max_fan_speed = 100
min_fan_speed = 35
disable_fan_first_layers = 1
bridge_fan_speed = 100
cooling = 1

#---- extruders
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 0x0
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
use_relative_e_distances = 0
ooze_prevention = 0

#---- misc
post_process =
resolution = 0
spiral_vase = 0
complete_objects = 0
duplicate = 1
duplicate_distance = 6
duplicate_grid = 1,1
output_filename_format = [input_filename_base].gcode

Does any one have the same issue or have a solution for this?

Sincerely,

Dean

**Comment by lordofhyphens** [comment]
Unfortunately, that model's no longer on Thingiverse. Going to close this for now (and it might have been fixed in the interim). Please reopen if you're still having problems with 1.2.9a or 1.3.0-dev and can zip the model up and drop it here :)
