### ISSUE TITLE
Add option to export all settings as comments in GCode output

### ISSUE THREAD

**Issue by bkpsu** [alexrj/Slic3r#1674]
As I print more and try to determine which settings work best for which objects, I would like to have a repository of "verified" files, complete with a rundown of the exact settings used, without having to use filenames or other files for storing this information. Currently, the output GCode does contain some of this information (comments at the top of the file), but it's missing things like which "preset" was used for Print, Filament and Printer, and most of the checkbox settings. As new options are added to Slic3r, those options should also be allowed to be exported to the GCode file, perhaps as a Preference setting for "Verbose GCode".

**Comment by foreachthing** [comment]
You could write a post-processor (python, c#, c++, vb.net, ....) to keep all lines starting with a `;` and split+dump the rest.
i.e.: keep line `; generated by ...`
`G21 		; metric values` split by `;` and drop the second element. Trim spaces while you're at it.
