### ISSUE TITLE
Handle invalid files gracefully

### ISSUE THREAD

**Issue by JonathanNathan** [alexrj/Slic3r#1675]
I'm getting an fatal error with a simple model made in google sketchup:

ERROR: "Use of uninitialized value at c:/Slic3r_10_RC2/lib/std/Math/ConvexHull/MonotoneChain.pm line 23."

This error prevents slicing completely and it occurs when adding the model to plater.
STL file at: https://dl.dropboxusercontent.com/u/30221595/mirror_corner.stl
Config file at: https://dl.dropboxusercontent.com/u/30221595/mirror_corner_config.ini

WinXP 32bit

**Comment by lordofhyphens** [comment]
With the error code and processing, going to close this. Please reopen if it's still an issue in 1.2.9 or 1.3.0-dev.
