### ISSUE TITLE
Feature Request: Delay after retraction restart for Bowden

### ISSUE THREAD

**Issue by alexborro** [alexrj/Slic3r#1677]
An usual issue on Bowden printers is the delay of extrusion on retracts restart... the filament takes some time to start flowing while the printer already started to trace.

It would be great having a "delay on retract restart", I mean, the printer wait for "n milliseconds" before print moves after the retract restart. That time would be enough for the filament start flowing..

The implementation is quite easy, just a "G4 Pn" after retract restart.

Alex.

**Comment by lordofhyphens** [comment]
I think this can be closed, as there's a commit attached to it.
