### ISSUE TITLE
textbox values double up when saving v1.0.0 (since RC1)

### ISSUE THREAD

**Issue by amanica** [alexrj/Slic3r#1688]
Hi,

Sometimes when saving a tab the values of some of the text fields gets populated with two copies of the actual value.
eg. before save:
![selection_024](https://f.cloud.github.com/assets/849576/1883615/41ced550-7989-11e3-9826-06816bd70445.png)

after save (and selecting name and clicking ok):
![selection_025](https://f.cloud.github.com/assets/849576/1883626/4b99a9f2-7989-11e3-8bec-0cf342f1ec7f.png)

This happens on the Printer Settings tab too eg. Z offset jumps from -2.2 to -2.2-2.2 .

If I close without saving and open it again it appears to have saved the correct values, 
but I think the wrong values have been used to generate gcode and caused the printer to go crazy on occasion (thank goodness for an emergency reset button!)

This did not happen with 0.9.10b and I'm pretty sure I had a good git version I pulled a month or two before 1.0.0 RC1 .
Affected version 1.0.0 and RC3, RC2, RC1.

I'm running on ubuntu 13.10 64bit
$ slic3r --debug
wxWidgets version wxWidgets 2.9.3, Wx version 0.9906

btw. thanks for all the recent improvements in Slic3r, it is awesome.

**Comment by lordofhyphens** [comment]
AFAIK this is not a problem on current -dev, at least for me on linux with 1.2.9 or 1.3.0-dev. Closing.
