### ISSUE TITLE
Support interface adhesion issues

### ISSUE THREAD

**Issue by jonaskuehling** [alexrj/Slic3r#1703]
Hi Alessandro,

I ran a few tests with the latest support implementation and experienced some issues concerning the adhesion between support interface and the model. It seems that the distance between interface and model is a little too large as the first model layer on top of the solid interface doesn't stick well enough to lay down the perimeters precisely.

For testing with ABS I just printed a test object with 5 layers raft (3 solid interface layers), so the base for the model was a nicely flat and solid ABS surface. The bottom model layer perimeters didn't stick well, though, like when printing the first layer on a print bed with too great distance between print surface and model.

As expected, removal of the raft was easy this way and didn't leave any residue on the printed part, but I guess it would still work with a little more adhesion?

I didn't perform too much testing with discrete (soluble) support material (dual extruder) concerning this issue yet, but I believe that it will potentially work even worse, as inter-material-adhesion (HIPS/ABS, PVA/ABS etc.) is mostly weaker than between ABS support and ABS model (break-away support) for example.

Talking about soluble support, I'd suggest some kind of option to choose between break-away and soluble support material, as soluble support would enable printing the model perfectly attached to the support interface without worrying about problematic removal later. In this case variable layer height handling should be turned off, to achieve perfect bottom surfaces on the model as the bottom layer can be printed just like the first layer on the print bed or all the other layers inside the model.

Please let me know if I just missed an advanced option for adjusting the interface-to-model-adhesion :)

**Comment by alexrj** [comment]
Done! I added an option for vertical distance between object and support.
