### ISSUE TITLE
bulid error

### ISSUE THREAD

**Issue by marvinstuart** [alexrj/Slic3r#1705]
please attached of bulid error

odroid@odroid:~/Slic3r$ sudo perl Build.PL
App::cpanminus is up to date. (1.7001)
Class::XSAccessor is up to date. (1.19)
Encode::Locale is up to date. (1.03)
ExtUtils::MakeMaker is up to date. (6.86)
ExtUtils::ParseXS is up to date. (3.22)
skipping R/RJ/RJBS/perl-5.18.2.tar.bz2
File::Spec is up to date. (3.40)
Getopt::Long is up to date. (2.42)
IO::Scalar is up to date. (2.110)
Math::Geometry::Voronoi is up to date. (1.3)
Math::PlanePath is up to date. (113)
Module::Build::WithXSpp is up to date. (0.14)
Moo is up to date. (1.004002)
Scalar::Util is up to date. (1.35)
Test::Harness is up to date. (3.30)
Test::More is up to date. (1.001002)
Time::HiRes is up to date. (1.9726)
XML::SAX::ExpatXS is up to date. (1.33)
Cleaning up build files
Cleaning up configuration files
--> Working on ./xs
Configuring /home/odroid/Slic3r/xs ... OK
Building and testing Slic3r-XS-0.01 ... ^CThe XS/C++ code failed to compile, aborting
odroid@odroid:~/Slic3r$ git clone https://github.com/alexrj/Slic3r.git
Cloning into 'Slic3r'...
remote: Reusing existing pack: 22394, done.
remote: Counting objects: 549, done.
remote: Compressing objects: 100% (488/488), done.
remote: Total 22943 (delta 199), reused 386 (delta 37)
Receiving objects: 100% (22943/22943), 11.87 MiB | 3.65 MiB/s, done.
Resolving deltas: 100% (9785/9785), done.
Checking connectivity... done
odroid@odroid:~/Slic3r$ cd
odroid@odroid:~$ git clone https://github.com/alexrj/Slic3r.git
fatal: destination path 'Slic3r' already exists and is not an empty directory.
odroid@odroid:~$ git clone https://github.com/alexrj/Slic3r.git
Cloning into 'Slic3r'...
remote: Reusing existing pack: 22394, done.
remote: Counting objects: 549, done.
remote: Compressing objects: 100% (488/488), done.
remote: Total 22943 (delta 199), reused 386 (delta 37)
Receiving objects: 100% (22943/22943), 11.87 MiB | 3.64 MiB/s, done.
Resolving deltas: 100% (9785/9785), done.
Checking connectivity... done
odroid@odroid:~$ cd Slic3r
odroid@odroid:~/Slic3r$ sudo perl Build.PL
App::cpanminus is up to date. (1.7001)
Class::XSAccessor is up to date. (1.19)
Encode::Locale is up to date. (1.03)
ExtUtils::MakeMaker is up to date. (6.86)
ExtUtils::ParseXS is up to date. (3.22)
skipping R/RJ/RJBS/perl-5.18.2.tar.bz2
File::Spec is up to date. (3.40)
Getopt::Long is up to date. (2.42)
IO::Scalar is up to date. (2.110)
Math::Geometry::Voronoi is up to date. (1.3)
Math::PlanePath is up to date. (113)
Module::Build::WithXSpp is up to date. (0.14)
Moo is up to date. (1.004002)
Scalar::Util is up to date. (1.35)
Test::Harness is up to date. (3.30)
Test::More is up to date. (1.001002)
Time::HiRes is up to date. (1.9726)
XML::SAX::ExpatXS is up to date. (1.33)
--> Working on ./xs
Configuring /home/odroid/Slic3r/xs ... OK
Building and testing Slic3r-XS-0.01 ... OK
Successfully installed Slic3r-XS-0.01
1 distribution installed
t/angles.t ........... ok     
t/arcs.t ............. skipped: arcs are currently disabled
t/clean_polylines.t .. 1/6 
Failed test 'gear simplified to a single polygon'
at t/clean_polylines.t line 65.
Can't use an undefined value as an ARRAY reference at t/clean_polylines.t line 67.
Looks like you planned 6 tests but ran 3.
Looks like you failed 1 test of 3 run.
Looks like your test exited with 255 just after 3.
t/clean_polylines.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/6 subtests 
t/clipper.t .......... ok   
t/collinear.t ........ ok     
t/combineinfill.t .... 1/2 
Failed test 'infill is only present in correct number of layers'
at t/combineinfill.t line 44.
 got: '-1'
expected: '50'
Looks like you failed 1 test of 2.
t/combineinfill.t .... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
t/cooling.t .......... ok     
t/custom_gcode.t ..... ok   
t/dynamic.t .......... skipped: variable-width paths are currently disabled
t/fill.t ............. ok     
t/gcode.t ............ ok   
t/geometry.t ......... ok     
t/layers.t ........... ok   
t/loops.t ............ skipped: temporarily disabled
t/multi.t ............ terminate called after throwing an instance of 'std::out_of_range'
what():  vector::_M_range_check
t/multi.t ............ Failed 1/1 subtests 
t/perimeters.t ....... 2/6 
Failed test 'move inwards after completing external loop'
at t/perimeters.t line 72.
t/perimeters.t ....... 4/6 
Failed test 'avoid starting from convex points'
at t/perimeters.t line 94.
t/perimeters.t ....... 6/6 
Failed test 'no superfluous extra perimeters'
at t/perimeters.t line 168.
Looks like you failed 3 tests of 6.
t/perimeters.t ....... Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/6 subtests 
t/polyclip.t ......... ok     
t/print.t ............ 1/2 
Failed test 'print is centered around print_center (X)'
at t/print.t line 29.
Failed test 'print is centered around print_center (Y)'
at t/print.t line 30.
Looks like you failed 2 tests of 2.
t/print.t ............ Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 
t/retraction.t ....... ok     
t/shells.t ........... 1/12 
Failed test 'insufficient number of bottom solid layers'
at t/shells.t line 43.
Failed test 'excessive number of bottom solid layers'
at t/shells.t line 44.
Failed test 'insufficient number of top solid layers'
at t/shells.t line 47.
Failed test 'excessive number of top solid layers'
at t/shells.t line 48.
t/shells.t ........... 8/12 
Failed test 'correct number of top solid shells is generated in V-shaped object'
at t/shells.t line 83.
 got: '0'
expected: '3'
t/shells.t ........... 9/12 
Failed test 'shells are not propagated across perimeters of the neighbor layer'
at t/shells.t line 114.
got: '0'
expected: '3'
t/shells.t ........... 10/12 
Failed test 'no superfluous shells are generated'
at t/shells.t line 137.
          got: '0'
   expected: '6'
t/shells.t ........... 13/12 
   Failed test 'no gaps in spiral vase (hollow model)'
   at t/shells.t line 170.
          got: '641'
     expected: '0'
t/shells.t ........... 15/12 # Looks like you planned 12 tests but ran 16.
 Looks like you failed 8 tests of 16 run.
t/shells.t ........... Dubious, test returned 8 (wstat 2048, 0x800)
Failed 7/12 subtests 
t/skirt_brim.t ....... ok   
t/slice.t ............ skipped: temporarily disabled
t/support.t .......... ok     
t/svg.t .............. ok   
t/threads.t .......... ok   
t/vibrationlimit.t ... ok   

Test Summary Report

t/clean_polylines.t (Wstat: 65280 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 6 tests but ran 3.
t/combineinfill.t  (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/multi.t          (Wstat: 134 Tests: 0 Failed: 0)
  Non-zero wait status: 134
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
t/perimeters.t     (Wstat: 768 Tests: 6 Failed: 3)
  Failed tests:  3-4, 6
  Non-zero exit status: 3
t/print.t          (Wstat: 512 Tests: 2 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
t/shells.t         (Wstat: 2048 Tests: 16 Failed: 11)
  Failed tests:  1-4, 8-10, 13-16
  Non-zero exit status: 8
  Parse errors: Bad plan.  You planned 12 tests but ran 16.
Files=26, Tests=220, 126 wallclock secs ( 0.24 usr  0.09 sys + 107.98 cusr  2.01 csys = 110.32 CPU)
Result: FAIL
Some tests failed. Please report the failure to the author!
odroid@odroid:~/Slic3r$

**Comment by alexrj** [comment]
No answer from @marvinstuart :(
