### ISSUE TITLE
breakaway distance and skirt for 2 filaments

### ISSUE THREAD

**Issue by MarioSt** [alexrj/Slic3r#1711]
Hi all!!

I'm quite new to 3d printing and have 2 quick questions and/or requests:

Is there a way to change the distance of the breakaway support to the print?

I'm usually printing a skirt for every layer and was curious if it is possible to have both extruders build a skirt not only one?

I've already set the skirt to 4 lanes and 2 of them are from extruder 2 but only for the 1st layer. After that the skirt is only printed by extruder 1 

Thanks in advance

Mario

**Comment by alexrj** [comment]
Customizable distance between objects and support is being implemented. Some changes in skirt are planned soon as well. Stay tuned :-)
