### ISSUE TITLE
New users try master but should use stable

### ISSUE THREAD

**Issue by bmcage** [alexrj/Slic3r#1713]
I would advise to update

https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux#get-slic3r

so as it to be: 
git clone https://github.com/alexrj/Slic3r.git
cd Slic3r
git checkout origin/stable
git branch -b stable

You now have the stable branch.

Otherwise, people just end up trying and failing with master.

**Comment by lordofhyphens** [comment]
I use master for everything myself, but it's done :)
