### ISSUE TITLE
issues with sequential printing

### ISSUE THREAD

**Issue by bmcage** [alexrj/Slic3r#1714]
My setup: 
1/ current git stable 1.0 RC3-dev
2/ replicator 1 with dual extrusion, Makerbot firmware 7.?
3/ slice with slic3r to gcode
4/ use replicatorg to send gcode to the printer

My aim: sequential printing of 5 small pieces. The replicator 1 has big part close to the table with the two heads, so not very suited for this, but for small pieces it is ok.

Issues:
1/ I need to set print center to (0,0) on bed size (220,140). I suppose that is due to the makerbot firmware? The default puts it in the middle, it takes some fiddling to understand wrong start position can be fixed with this. I set 'Complete individual objects' on and Extruder clearance to R=60 and Height=70.
So I lay out the objects on the platter from -11cm to 11cm x dir, and -7 to 7 y dir.

2/ In replicatorg, the exported STL puts the objects all from 0 to 22cm in x, and from 0 to 14cm in y. At least, that is how replicatorg shows the STL when loaded there. So above setting of print center is not taken into account.
However, the gcode is CORRECT, so the gcode lays it out correctly as seen on the platter from -11 to 11 x, -7 to 7 cm y.

3/ On the replicator 1, I see after the first piece: 'Print complete', and the Red led behind the makerbot logo starts to flash. This should not happen, it moved to the next piece so is still printing

4/ I print with the right extruder. For some setups, the print starts to the right of the bed. For others printing starts to the left. As this is the right extruder, it would be best to start printing always on the rightmost object. This because I should increase the clearance if printing starts left.

**Comment by lordofhyphens** [comment]
@Oryhara did it work? :)

**Comment by Oryhara** [comment]
Pretty sure it did. It was two years ago so i do not really remember. Ive
done sequential printing since then with slic3r.

**Comment by lordofhyphens** [comment]
Thanks :)
