### ISSUE TITLE
first layer printing at wrong height when using brim - not tested without brim

### ISSUE THREAD

**Issue by Jzatopa** [alexrj/Slic3r#1715]
When printing an object with g-code made from slicer 1.0.0RC2 using brim the brim only the brim prints at the proper height and speed.  The rest is printed at full speed after the print head is moved up.  Here is an example of what happens

1. print starts .3mm first layer .2mm for the rest
2. brim starts printing @ .3mmZ
3. brim ends printing @ .3mmZ
4. print head moves to .75mmZ
5. print prints what should be first layer at full speed and @ .75mmZ

New install on windows using stock settings.

**Comment by lordofhyphens** [comment]
Probably fixed.
