### ISSUE TITLE
Support Material not generating or generating erroneously.

### ISSUE THREAD

**Issue by Bobanaut** [alexrj/Slic3r#1719]
Slicer v1.0.0 RC2

Download https://dl.dropboxusercontent.com/u/76507811/Human%20Bone.stl
The Bone is part of the Skeleton model (scheletro.blend) developed by Pepe Cirotti at Univ. of Costa Rica

Use ANY config (my default config is here: https://dl.dropboxusercontent.com/u/76507811/exported%20config%20from%201.0.0%20RC2.ini ).
Alter the following settings:
Disable "Generate support material"
Set "Enforce support for the first:" 300 Layers

The result is no support material or bogus support material in case of raft layers. Only supporting a tiny fraction,

Old versions generate support material. But not as required. They should cover all of the lower part in the shadow of the object (the downwards projected silhouette of the first 300 layers).

v0.9.9/v0.9.10b result:
![slicer 0 9 9 result](https://f.cloud.github.com/assets/6436571/1947269/818cb822-8048-11e3-8dd7-48526272adfe.png)

v1.0.0 RC2 result:
![slicer 1 0 0 rc2 result](https://f.cloud.github.com/assets/6436571/1947285/e4a4d02e-8049-11e3-9d69-0d186d6ec6c7.png)

**Comment by lordofhyphens** [comment]
The syntax for "first N layers" with support is a force-on for those layers, not force-off after those layers.

Here's a picture from 1.3.0-dev. Look better? Looks pretty good to me.
![bonesupport](https://cloud.githubusercontent.com/assets/31754/16168916/9d924fb6-34df-11e6-9185-c475b65ec4e2.png)

Going to close, please reopen if you still have issues with current 1.2.9 or 1.3.0-dev with this.
