### ISSUE TITLE
--gcode-arcs causes segfaults with recent versions

### ISSUE THREAD

**Issue by bgamari** [alexrj/Slic3r#1727]
Crash seen with both HEAD (6afc01c3b) and 1.0.0RC2 when operating on any object I give it,

    => Detecting solid surfaces
    => Preparing infill surfaces
    => Detect bridges
    => Generating horizontal shells
    => Combining infill
    => Infilling layers
    [New Thread 0x7ffff2fd0700 (LWP 18499)]
    [New Thread 0x7ffff37d1700 (LWP 18500)]
    [Thread 0x7ffff2fd0700 (LWP 18499) exited]
    [Thread 0x7ffff37d1700 (LWP 18500) exited]
    => Generating support material
    [New Thread 0x7ffff37d1700 (LWP 18501)]
    [New Thread 0x7ffff2fd0700 (LWP 18502)]
    [Thread 0x7ffff37d1700 (LWP 18501) exited]
    [Thread 0x7ffff2fd0700 (LWP 18502) exited]
    => Generating skirt
    => Exporting G-code to hi.gcode

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff7b06714 in Perl_av_fetch () from /usr/lib/libperl.so.5.14
    (gdb) bt
    #0  0x00007ffff7b06714 in Perl_av_fetch () from /usr/lib/libperl.so.5.14
    #1  0x00007ffff487b6ae in Slic3r::Point::from_SV (this=this@entry=0x225f310, point_sv=<optimized out>) at src/Point.cpp:117
    #2  0x00007ffff487b800 in Slic3r::Point::from_SV_check (this=this@entry=0x225f310, point_sv=<optimized out>) at src/Point.cpp:127
    #3  0x00007ffff4832987 in XS_Slic3r__Line_new (my_perl=<optimized out>, cv=<optimized out>)
        at /usr/bin/perl -MExtUtils::XSpp::Cmd -e xspp -- -t "/home/ben/reprap/code/Slic3r/xs/xsp/typemap.xspt"  "/home/ben/reprap/code/Slic3r/xs/xsp/Line.xsp":131
    #4  0x00007ffff7b10591 in Perl_pp_entersub () from /usr/lib/libperl.so.5.14
    #5  0x00007ffff7b07d36 in Perl_runops_standard () from /usr/lib/libperl.so.5.14
    #6  0x00007ffff7aa75b0 in perl_run () from /usr/lib/libperl.so.5.14
    #7  0x0000000000400e49 in main ()
    (gdb) up
    #1  0x00007ffff487b6ae in Slic3r::Point::from_SV (this=this@entry=0x225f310, point_sv=<optimized out>) at src/Point.cpp:117
    117	    this->x = lrint(SvNV(*av_fetch(point_av, 0, 0)));

`point_av` is `NULL`.

**Comment by lordofhyphens** [comment]
Arc fitting has been removed (incomplete feature) in 1.3.0-dev. Closing.
