### ISSUE TITLE
Request: option to use mm^3 for E values

### ISSUE THREAD

**Issue by whosawhatsis** [alexrj/Slic3r#1746]
I've recently implemented M200 in Marlin, which makes it possible to send the filament diameter to the firmware and then send E values in units of volume (cubic millimeters) instead of sending an extrusion length (with filament diameter data already baked-in). This makes it possible to adjust the filament diameter after slicing, and is needed for the UFID project or printers with a built-in filament measuring device. Slic3r just needs to be able to send the M200 code and output E values in these units, bypassing the step where extrusion length is calculated from filament diameter and just sending the volume measurement.

**Comment by alexrj** [comment]
@whosawhatsis, how are multiple extruders supported with M200?

**Comment by whosawhatsis** [comment]
Same as with M104/109, diameter value goes to the active extruder unless you include a tool number on the same line, so for a dual extruder you would see something like this:

M200 D1.75 T0
M200 D1.8 T1

**Comment by alexrj** [comment]
Great!

**Comment by whosawhatsis** [comment]
BTW, as with M104/109, you should scan the start gcode for an M200 and not insert another one if it's there. It can be advantageous to insert it in a specific place in the start code, such as after a priming procedure.

**Comment by alexrj** [comment]
Good idea.  Done!  :-)

**Comment by alexrj** [comment]
Discussion followup at:
https://github.com/alexrj/Slic3r/commit/47e4e8bb66740af791e56b36f0ecb67143a94b3b#comments

**Comment by braddo99** [comment]
Is this compatible with triffid's trick where you put 1.12838 as the filament diameter then set the diameter in the firmware? I would have thought that if volumetric is set in the slicer then perhaps filament diameter would be greyed out, as it's to be set in firmware. Or is it that if M200 isn't set, the gcode will just continue in non-volumetric mode?

**Comment by whosawhatsis** [comment]
@braddo99 Yes. What this does is ignore the filament diameter setting for gcode calculation and just export units of cubic millimeters. The filament diameter setting isn't greyed-out for (at least) two reasons:

1. Filament settings are separate from machine settings, and you can use the same filament settings with a different printer profile and vice versa.
2. Keeping the value in there allows you to use a replacement variable to fill in the value in an M200 line in your start code.

**Comment by braddo99** [comment]
thanks!
