### ISSUE TITLE
Multimaterial - first layer fault

### ISSUE THREAD

**Issue by tomaswallentinus** [alexrj/Slic3r#1754]
Hi.

When combining three stl-files to an amf file and then generate gcode the file gets rely big. If you load the file to Pronterface you can see that it has filled the entire first layer with extrusion lines.

The example file I'm using is this one from RepRapPro wiki: https://github.com/reprappro/Mendel/tree/master/Multi-material/Sample%20Parts/Simple-test

The settings I use is the default ones from the RepRapPro-wiki but setting it to 3 extruders.

I have used the following Slic3r versions: 0.9.5, 0.9.7, 0.9.8, 0.9.9, 0.9.10b, 1.0 RC1, 1.0 RC2.

The systems I have tried are: Windows XP 32-bit, Windows 8.1 64-bit.

The Printrun I'm using is 2013-10-19 from the Kliment builds.

**Comment by lordofhyphens** [comment]
@tomaswallentinus could you try to reproduce this on 1.2.9 or 1.3.0-dev and provide a copy of your exported config.ini and provide a layer screenshot from Slic3r itself? A lot has changed over the years.

Please reopen this if you are still seeing a problem.
