### ISSUE TITLE
Can not install Slic3r win XP 32bit  It says Application Startup failure

### ISSUE THREAD

**Issue by 3-phase** [alexrj/Slic3r#1755]
As soon as I click it to install I get this pop up box that says, Application Start up failure.   "Invalid or missing map loader.  Try re-installing the application to a clean directory". 
It will install slic3r-console.exe   But it will not install slic3r.exe  Need help please

**Comment by lordofhyphens** [comment]
@3-phase is this still a problem with 1.2.9a? We still need more information. Going to close this; please reopen if you still need help.

Also, WinXP is an ancient OS, can't guarantee it'll stay compatible with it.
