### ISSUE TITLE
Accounting for uneven build surfaces

### ISSUE THREAD

**Issue by RenaeMacLeod** [alexrj/Slic3r#1765]
Most beds I've seen are warped, if minimally, and I hope I have a suggestion that is a reasonable solution. I've seen warped surfaces on printers I've worked on for people and I've also had to deal with it myself, especially on large (in the X/Y) prints. Levelling minimises the issue but cannot eliminate it. Recently, at a particular client, I've measured as much as a 0.2mm gap in both opposing corners for a bed that is 140x140mm (for a few of their printers). When measuring the height in 5 spots (centre and the 4 corners) I use a 0.1mm thick piece of paper. This is an example of a measurement...

____________
+1________+2
______0_____    (with the head *just* touching)
+2________+1
____________

I measure it +1 or +2 depending on how many layers of paper fit between the head and the bed and scrape without forcing it. As you might expect, this issue also changes with different build plates on the same printer. Continuous heating of the build plate coupled with swapping it out and cooling it immediately after a print is warping the build surface. I've also seen fresh build plates slightly warped. The way I recommend dealing with this is to set the print head height according to the layer height plus the extra needed to make sure the outermost edges of the print will get to the bed and adhere. The previously mentioned client has a 0.25mm head and typically prints at a 0.1mm layer height. As you might guess from what I listed above, the center of the print has excessive amounts of filament (when the extruder is able build enough pressure to lift the head off of the bed) and the edges barely touch and sometimes have trouble sticking.

Now, I'll be the first to admit I don't have any idea of the complexities that goes into making this fabulous software and I hope I'm not overlooking some obvious setting. And again, I hope this request is easy (or worth the effort) to implement.

What I would like to propose is in two parts.
- First - A setting in the printer or print section where you enter the head/bed clearance Z offset for a minimum of 5 points (or perhaps 9 for more accuracy).
- Second - The first layer extrusion height/multiplier is automatically adjusted across the bed (according to the values specified in the first part) so that prints won't have excessive filament extruded at the points closest to the head.

Please excuse me if this a duplicate issue or if I have not made myself clear. I searched all issues for 'level' and 'uneven' and checked all the items and found no matching issue. Thanks for this awesome software and reading to the end my issue. :)

**Comment by lordofhyphens** [comment]
Not something that should be handled in the slicer, I think.

@RenaeMacLeod if you're still interested in grid levelling, there's a version in Marlin and also one in Smoothieware. Tighter grid consumes more memory and takes longer to probe but is closer to actually what is on the bed (probe with the bed hot as well to make sure you have everything as expected).
