### ISSUE TITLE
Resize build area when resizing the main window

### ISSUE THREAD

**Issue by RenaeMacLeod** [alexrj/Slic3r#1768]
When I resize the Slic3r window the main tab with the build area/layout doesn't change. Instead the list of items does. I believe it would be more beneficial for the build area grid to expand.

I was surprised I didn't find this item listed in the issues. Apologies if it's a duplicate.

**Comment by lordofhyphens** [comment]
Doesn't do that in Windows or Linux as of 1.2.9.
