### ISSUE TITLE
Slic3r slow when generating SVG

### ISSUE THREAD

**Issue by taskman** [alexrj/Slic3r#1769]
Hi

I am trying to use Slic3r to generate SVG's for printing with a DLP printer.
I use the following STL https://www.dropbox.com/s/a6ztyfdbyk9yp3j/Cells_Bowl_-_Math_Art_by_Dizingof.stl

These are the steps I follow
Download Slic3r 1.0.0RC2 (slic3r-mswin-x64-1-0-0-RC2.zip)
Unzip
Execute the following line
slic3r-console.exe --export-svg --layer-height=0.06 --bed-size=1450x1253 Cells_Bowl_-_Math_Art_by_Dizingof.stl

I am comparing the SVG generation with how long it takes http://reprap.org/wiki/Creation_Workshop.  Creation Workshop does it in about 1 second and it is taking me about 5 minutes+

Are there some settings I can change to get to 1 second?

**Comment by lordofhyphens** [comment]
@taskman Slic3r 1.0 was all Perl, and perl can be slow. Not much that can be done until that section is rewritten.
Try 1.2.9 and see if that's any better (or 1.3.0-dev).

Please reopen if it's still a problem.
