### ISSUE TITLE
Information request: Generating the windows package slicer.exe)

### ISSUE THREAD

**Issue by llluis** [alexrj/Slic3r#1777]
Hi @alexrj,

  Can you point me to the right direction on how to compile Slic3r for windows from git source?
  I have implemented a few new features (as discussed in #1677) and would like to facilitate the tests for others generating the executable file (so people would not have to have the complete perl dev environment).

  Is this information documented anywhere? What procedure or tool do you use?
  I can put together a documentation on the wiki after learning it.

  Thanks in advance.

**Comment by lordofhyphens** [comment]
http://stackoverflow.com/questions/2948405/how-to-compile-a-perl-script-to-a-windows-executable-with-strawberry-perl 
Correlate with the wiki instructions for building from source. prusa3d.com also has a build system for win32 @bubnikv has some knowledge regarding it.

Probably. I'm not a windows person. Going to close now, please reopen if you're still having problems.

**Comment by llluis** [comment]
Just linking the two issues to facilitate search: #2316

**Comment by lordofhyphens** [comment]
Thanks. The PAR method doesn't work for distribution, trying to figure out
what else to do.

**Comment by lordofhyphens** [comment]
For Windows we have compile_wrapper.ps1 and package_win32.ps1

Read the scripts for usage information. 

Or download a build from dl.slic3r.org/dev
