### ISSUE TITLE
Problem with layouts on RC3

### ISSUE THREAD

**Issue by RaD** [alexrj/Slic3r#1786]
I run Slic3r on Ubuntu LTS netbook with 1024x600 screen. It looks not good:

![window](https://f.cloud.github.com/assets/119226/2182567/c09cf3ac-978f-11e3-85e5-278d698b321e.png)

Layouts remain the same if I connect 1440x900 external screen.

Also, I can maximize this window on a whole screen on my netbook.

Thanks.

**Comment by lordofhyphens** [comment]
@RaD It's probably fixed now :)
Reopen if 1.2.9 or 1.3.0-dev are showing the same issue.
