### ISSUE TITLE
When running Export GCode against SD card - no warning when out of space - says GCode exported Successfully

### ISSUE THREAD

**Issue by peter6960** [alexrj/Slic3r#1809]
I have a habbit of putting the SD card into PC, exporting Gcode -> Select SD card in file browser.
Previous night I sliced a big 12 hour print to SD.  Slic3r reported it as Exported successfully.  Kicked off the print, only to come in this morning with a 200deg hotend stuck in the print.

Upon investigating, firmware did not hang, etc.    Figured it to be typical reprap gods issue, i restarted print.  A few hours later, stuck in same place, still at 200 etc.

Since it stops at same spot, I checked GCode and indeed it did not have the entire model.  Card was also at 100% at this point.

The issue here is that if the write to file fails, it should not report Successful.

It should say - Export failed - Out of space

Peter

**Comment by lordofhyphens** [comment]
This still a problem? Please respond/reopen if it is (use 1.2.9 or 1.3.0-dev)
