### ISSUE TITLE
instillation issues in ubuntu linux

### ISSUE THREAD

**Issue by r01walker** [alexrj/Slic3r#1813]
i am running a acer aspire on with Ubuntu 12.04.03 fresh install. I am using the documentation on 
https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux

the first issue i had was the package libwxgtk-media2.8-dev is not in the synaptic package manager or the ubuntu software center. i used google and found a web site that would install that package. for informational purposes. 

interestingly enough cpanminus installed

 when i use sudo perl Build.PL in terminal i get this output

cnc-machine@cncmachine:~$ apt-get install libwxbase3.0-0-unofficial libwxbase3.0-dev libwxgtk3.0-0-unofficial libwxgtk3.0-dev wx3.0-headers wx-common libwxbase3.0-dbg libwxgtk3.0-dbg wx3.0-i18n wx3.0-examples wx3.0-doc
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
cnc-machine@cncmachine:~$ sudo apt-get install libwxbase3.0-0-unofficial libwxbase3.0-dev libwxgtk3.0-0-unofficial libwxgtk3.0-dev wx3.0-headers wx-common libwxbase3.0-dbg libwxgtk3.0-dbg wx3.0-i18n wx3.0-examples wx3.0-doc
[sudo] password for cnc-machine: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  thunderbird-globalmenu graphicsmagick language-pack-kde-en
  gir1.2-ubuntuoneui-3.0 language-pack-kde-en-base kde-l10n-engb
  libubuntuoneui-3.0-1 libgraphicsmagick3
Use 'apt-get autoremove' to remove them.
Suggested packages:
  libgnomeprintui2.2-0
The following NEW packages will be installed:
  libwxbase3.0-0-unofficial libwxbase3.0-dbg libwxbase3.0-dev
  libwxgtk3.0-0-unofficial libwxgtk3.0-dbg libwxgtk3.0-dev wx3.0-doc
  wx3.0-examples wx3.0-headers wx3.0-i18n
The following packages will be upgraded:
  wx-common
1 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 79.6 MB of archives.
After this operation, 193 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libwxbase3.0-0-unofficial libwxgtk3.0-0-unofficial libwxbase3.0-dbg
  libwxgtk3.0-dbg wx3.0-headers libwxbase3.0-dev wx-common libwxgtk3.0-dev
  wx3.0-doc wx3.0-examples wx3.0-i18n
Install these packages without verification [y/N]? y
Get:1 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe libwxbase3.0-0-unofficial i386 3.0.0-2.precise [1,400 kB]
Get:2 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe libwxgtk3.0-0-unofficial i386 3.0.0-2.precise [5,892 kB]
Get:3 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe libwxbase3.0-dbg i386 3.0.0-2.precise [10.7 MB]
Get:4 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe libwxgtk3.0-dbg i386 3.0.0-2.precise [54.2 MB]
Get:5 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe wx3.0-headers i386 3.0.0-2.precise [1,499 kB]
Get:6 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe libwxbase3.0-dev i386 3.0.0-2.precise [126 kB]
Get:7 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe wx-common i386 3.0.0-2.precise [336 kB]
Get:8 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe libwxgtk3.0-dev i386 3.0.0-2.precise [126 kB]
Get:9 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe wx3.0-doc all 3.0.0-2.precise [102 kB]
Get:10 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe wx3.0-examples all 3.0.0-2.precise [4,226 kB]
Get:11 http://repos.codelite.org/wx3.0/ubuntu/ precise/universe wx3.0-i18n all 3.0.0-2.precise [1,046 kB]
Fetched 79.6 MB in 1min 19s (1,000 kB/s)                                       
Selecting previously unselected package libwxbase3.0-0-unofficial.
(Reading database ... 234079 files and directories currently installed.)
Unpacking libwxbase3.0-0-unofficial (from .../libwxbase3.0-0-unofficial_3.0.0-2.precise_i386.deb) ...
Selecting previously unselected package libwxgtk3.0-0-unofficial.
Unpacking libwxgtk3.0-0-unofficial (from .../libwxgtk3.0-0-unofficial_3.0.0-2.precise_i386.deb) ...
Selecting previously unselected package libwxbase3.0-dbg.
Unpacking libwxbase3.0-dbg (from .../libwxbase3.0-dbg_3.0.0-2.precise_i386.deb) ...
Selecting previously unselected package libwxgtk3.0-dbg.
Unpacking libwxgtk3.0-dbg (from .../libwxgtk3.0-dbg_3.0.0-2.precise_i386.deb) ...
Selecting previously unselected package wx3.0-headers.
Unpacking wx3.0-headers (from .../wx3.0-headers_3.0.0-2.precise_i386.deb) ...
Selecting previously unselected package libwxbase3.0-dev.
Unpacking libwxbase3.0-dev (from .../libwxbase3.0-dev_3.0.0-2.precise_i386.deb) ...
Preparing to replace wx-common 2.8.12.1-6ubuntu2 (using .../wx-common_3.0.0-2.precise_i386.deb) ...
Unpacking replacement wx-common ...
Selecting previously unselected package libwxgtk3.0-dev.
Unpacking libwxgtk3.0-dev (from .../libwxgtk3.0-dev_3.0.0-2.precise_i386.deb) ...
Selecting previously unselected package wx3.0-doc.
Unpacking wx3.0-doc (from .../wx3.0-doc_3.0.0-2.precise_all.deb) ...
Selecting previously unselected package wx3.0-examples.
Unpacking wx3.0-examples (from .../wx3.0-examples_3.0.0-2.precise_all.deb) ...
Selecting previously unselected package wx3.0-i18n.
Unpacking wx3.0-i18n (from .../wx3.0-i18n_3.0.0-2.precise_all.deb) ...
Processing triggers for man-db ...
Setting up libwxbase3.0-0-unofficial (3.0.0-2.precise) ...
Setting up libwxgtk3.0-0-unofficial (3.0.0-2.precise) ...
Setting up libwxbase3.0-dbg (3.0.0-2.precise) ...
Setting up libwxgtk3.0-dbg (3.0.0-2.precise) ...
Setting up wx3.0-headers (3.0.0-2.precise) ...
Setting up libwxbase3.0-dev (3.0.0-2.precise) ...
update-alternatives: using /usr/lib/wx/config/base-unicode-3.0-unofficial to provide /usr/bin/wx-config (wx-config) in auto mode.
Setting up wx-common (3.0.0-2.precise) ...
Setting up libwxgtk3.0-dev (3.0.0-2.precise) ...
update-alternatives: using /usr/lib/wx/config/gtk2-unicode-3.0-unofficial to provide /usr/bin/wx-config (wx-config) in auto mode.
Setting up wx3.0-doc (3.0.0-2.precise) ...
Setting up wx3.0-examples (3.0.0-2.precise) ...
Setting up wx3.0-i18n (3.0.0-2.precise) ...
cnc-machine@cncmachine:~$ git clone https://github.com/alexrj/Slic3r.git
Cloning into 'Slic3r'...
remote: Reusing existing pack: 23308, done.
remote: Total 23308 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (23308/23308), 11.71 MiB | 1.48 MiB/s, done.
Resolving deltas: 100% (10266/10266), done.
cnc-machine@cncmachine:~$ cd Slic3r
cnc-machine@cncmachine:~/Slic3r$ sudo perl Build.PL
--> Working on App::cpanminus
Fetching http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7001.tar.gz ... OK
Configuring App-cpanminus-1.7001 ... OK
Building and testing App-cpanminus-1.7001 ... OK
Successfully installed App-cpanminus-1.7001 (upgraded from 1.5007)
1 distribution installed
--> Working on Class::XSAccessor
Fetching http://search.cpan.org/CPAN/authors/id/S/SM/SMUELLER/Class-XSAccessor-1.19.tar.gz ... OK
Configuring Class-XSAccessor-1.19 ... OK
Building and testing Class-XSAccessor-1.19 ... OK
Successfully installed Class-XSAccessor-1.19
1 distribution installed
You have Encode::Locale (1.02)
--> Working on ExtUtils::MakeMaker
Fetching http://search.cpan.org/CPAN/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-6.90.tar.gz ... OK
Configuring ExtUtils-MakeMaker-6.90 ... OK
Building and testing ExtUtils-MakeMaker-6.90 ... OK
Successfully installed ExtUtils-MakeMaker-6.90 (upgraded from 6.57_05)
1 distribution installed
--> Working on ExtUtils::ParseXS
Fetching http://search.cpan.org/CPAN/authors/id/S/SM/SMUELLER/ExtUtils-ParseXS-3.22.tar.gz ... OK
Configuring ExtUtils-ParseXS-3.22 ... OK
Building and testing ExtUtils-ParseXS-3.22 ... OK
Successfully installed ExtUtils-ParseXS-3.22 (upgraded from 2.2210)
1 distribution installed
You have File::Basename (2.82)
You have File::Spec (3.33)
You have Getopt::Long (2.38)
--> Working on IO::Scalar
Fetching http://search.cpan.org/CPAN/authors/id/D/DS/DSKOLL/IO-stringy-2.110.tar.gz ... OK
Configuring IO-stringy-2.110 ... OK
Building and testing IO-stringy-2.110 ... OK
Successfully installed IO-stringy-2.110
1 distribution installed
--> Working on Math::Geometry::Voronoi
Fetching http://search.cpan.org/CPAN/authors/id/S/SA/SAMTREGAR/Math-Geometry-Voronoi-1.3.tar.gz ... OK
Configuring Math-Geometry-Voronoi-1.3 ... OK
==> Found dependencies: Params::Validate, Class::Accessor
--> Working on Params::Validate
Fetching http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Params-Validate-1.08.tar.gz ... OK
Configuring Params-Validate-1.08 ... OK
==> Found dependencies: Test::Fatal, Module::Implementation
--> Working on Test::Fatal
Fetching http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/Test-Fatal-0.013.tar.gz ... OK
Configuring Test-Fatal-0.013 ... OK
Building and testing Test-Fatal-0.013 ... OK
Successfully installed Test-Fatal-0.013
--> Working on Module::Implementation
Fetching http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Module-Implementation-0.07.tar.gz ... OK
Configuring Module-Implementation-0.07 ... OK
==> Found dependencies: Test::Requires, Module::Runtime
--> Working on Test::Requires
Fetching http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/Test-Requires-0.07.tar.gz ... OK
Configuring Test-Requires-0.07 ... OK
Building and testing Test-Requires-0.07 ... OK
Successfully installed Test-Requires-0.07
--> Working on Module::Runtime
Fetching http://search.cpan.org/CPAN/authors/id/Z/ZE/ZEFRAM/Module-Runtime-0.014.tar.gz ... OK
Configuring Module-Runtime-0.014 ... OK
Building and testing Module-Runtime-0.014 ... OK
Successfully installed Module-Runtime-0.014
Building and testing Module-Implementation-0.07 ... OK
Successfully installed Module-Implementation-0.07
Building and testing Params-Validate-1.08 ... OK
Successfully installed Params-Validate-1.08
--> Working on Class::Accessor
Fetching http://search.cpan.org/CPAN/authors/id/K/KA/KASEI/Class-Accessor-0.34.tar.gz ... OK
Configuring Class-Accessor-0.34 ... OK
Building and testing Class-Accessor-0.34 ... OK
Successfully installed Class-Accessor-0.34
Building and testing Math-Geometry-Voronoi-1.3 ... OK
Successfully installed Math-Geometry-Voronoi-1.3
7 distributions installed
--> Working on Math::PlanePath
Fetching http://search.cpan.org/CPAN/authors/id/K/KR/KRYDE/Math-PlanePath-114.tar.gz ... OK
Configuring Math-PlanePath-114 ... OK
==> Found dependencies: constant::defer, Math::Libm
--> Working on constant::defer
Fetching http://search.cpan.org/CPAN/authors/id/K/KR/KRYDE/constant-defer-5.tar.gz ... OK
Configuring constant-defer-5 ... OK
Building and testing constant-defer-5 ... OK
Successfully installed constant-defer-5
--> Working on Math::Libm
Fetching http://search.cpan.org/CPAN/authors/id/D/DS/DSLEWART/Math-Libm-1.00.tar.gz ... OK
Configuring Math-Libm-1.00 ... OK
Building and testing Math-Libm-1.00 ... OK
Successfully installed Math-Libm-1.00
Building and testing Math-PlanePath-114 ... OK
Successfully installed Math-PlanePath-114
3 distributions installed
--> Working on Module::Build::WithXSpp
Fetching http://search.cpan.org/CPAN/authors/id/S/SM/SMUELLER/Module-Build-WithXSpp-0.14.tar.gz ... OK
Configuring Module-Build-WithXSpp-0.14 ... OK
==> Found dependencies: ExtUtils::XSpp, ExtUtils::CppGuess
--> Working on ExtUtils::XSpp
Fetching http://search.cpan.org/CPAN/authors/id/S/SM/SMUELLER/ExtUtils-XSpp-0.18.tar.gz ... OK
==> Found dependencies: Module::Build
--> Working on Module::Build
Fetching http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/Module-Build-0.4205.tar.gz ... OK
Configuring Module-Build-0.4205 ... OK
Building and testing Module-Build-0.4205 ... OK
Successfully installed Module-Build-0.4205 (upgraded from 0.3800)
Configuring ExtUtils-XSpp-0.18 ... OK
==> Found dependencies: Test::Base, Test::Differences
--> Working on Test::Base
Fetching http://search.cpan.org/CPAN/authors/id/I/IN/INGY/Test-Base-0.62.tar.gz ... OK
Configuring Test-Base-0.62 ... OK
==> Found dependencies: Spiffy
--> Working on Spiffy
Fetching http://search.cpan.org/CPAN/authors/id/I/IN/INGY/Spiffy-0.31.tar.gz ... OK
Configuring Spiffy-0.31 ... OK
Building and testing Spiffy-0.31 ... OK
Successfully installed Spiffy-0.31
Building and testing Test-Base-0.62 ... OK
Successfully installed Test-Base-0.62
--> Working on Test::Differences
Fetching http://search.cpan.org/CPAN/authors/id/O/OV/OVID/Test-Differences-0.61.tar.gz ... OK
Configuring Test-Differences-0.61 ... OK
==> Found dependencies: Text::Diff
--> Working on Text::Diff
Fetching http://search.cpan.org/CPAN/authors/id/O/OV/OVID/Text-Diff-1.41.tar.gz ... OK
Configuring Text-Diff-1.41 ... OK
Building and testing Text-Diff-1.41 ... OK
Successfully installed Text-Diff-1.41
Building and testing Test-Differences-0.61 ... OK
Successfully installed Test-Differences-0.61
Building and testing ExtUtils-XSpp-0.18 ... OK
Successfully installed ExtUtils-XSpp-0.18
--> Working on ExtUtils::CppGuess
Fetching http://search.cpan.org/CPAN/authors/id/S/SM/SMUELLER/ExtUtils-CppGuess-0.07.tar.gz ... OK
Configuring ExtUtils-CppGuess-0.07 ... OK
==> Found dependencies: Capture::Tiny
--> Working on Capture::Tiny
Fetching http://search.cpan.org/CPAN/authors/id/D/DA/DAGOLDEN/Capture-Tiny-0.24.tar.gz ... OK
Configuring Capture-Tiny-0.24 ... OK
Building and testing Capture-Tiny-0.24 ... OK
Successfully installed Capture-Tiny-0.24
Building and testing ExtUtils-CppGuess-0.07 ... OK
Successfully installed ExtUtils-CppGuess-0.07
Building and testing Module-Build-WithXSpp-0.14 ... OK
Successfully installed Module-Build-WithXSpp-0.14
9 distributions installed
--> Working on Moo
Fetching http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/Moo-1.004002.tar.gz ... OK
==> Found dependencies: Dist::CheckConflicts
--> Working on Dist::CheckConflicts
Fetching http://search.cpan.org/CPAN/authors/id/D/DO/DOY/Dist-CheckConflicts-0.10.tar.gz ... OK
Configuring Dist-CheckConflicts-0.10 ... OK
==> Found dependencies: List::MoreUtils
--> Working on List::MoreUtils
Fetching http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/List-MoreUtils-0.33.tar.gz ... OK
Configuring List-MoreUtils-0.33 ... OK
Building and testing List-MoreUtils-0.33 ... OK
Successfully installed List-MoreUtils-0.33
Building and testing Dist-CheckConflicts-0.10 ... OK
Successfully installed Dist-CheckConflicts-0.10
Configuring Moo-1.004002 ... OK
==> Found dependencies: strictures, Role::Tiny, Class::Method::Modifiers, Devel::GlobalDestruction, Import::Into
--> Working on strictures
Fetching http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/strictures-1.005003.tar.gz ... OK
Configuring strictures-1.005003 ... OK
==> Found dependencies: multidimensional, indirect, bareword::filehandles
--> Working on multidimensional
Fetching http://search.cpan.org/CPAN/authors/id/I/IL/ILMARI/multidimensional-0.011.tar.gz ... OK
==> Found dependencies: B::Hooks::OP::Check, ExtUtils::Depends
--> Working on B::Hooks::OP::Check
Fetching http://search.cpan.org/CPAN/authors/id/Z/ZE/ZEFRAM/B-Hooks-OP-Check-0.19.tar.gz ... OK
==> Found dependencies: ExtUtils::Depends
--> Working on ExtUtils::Depends
Fetching http://search.cpan.org/CPAN/authors/id/X/XA/XAOC/ExtUtils-Depends-0.306.tar.gz ... OK
Configuring ExtUtils-Depends-0.306 ... OK
Building and testing ExtUtils-Depends-0.306 ... OK
Successfully installed ExtUtils-Depends-0.306
Configuring B-Hooks-OP-Check-0.19 ... OK
Building and testing B-Hooks-OP-Check-0.19 ... OK
Successfully installed B-Hooks-OP-Check-0.19
Configuring multidimensional-0.011 ... OK
==> Found dependencies: Lexical::SealRequireHints
--> Working on Lexical::SealRequireHints
Fetching http://search.cpan.org/CPAN/authors/id/Z/ZE/ZEFRAM/Lexical-SealRequireHints-0.007.tar.gz ... OK
Configuring Lexical-SealRequireHints-0.007 ... OK
Building and testing Lexical-SealRequireHints-0.007 ... OK
Successfully installed Lexical-SealRequireHints-0.007
Building and testing multidimensional-0.011 ... OK
Successfully installed multidimensional-0.011
--> Working on indirect
Fetching http://search.cpan.org/CPAN/authors/id/V/VP/VPIT/indirect-0.31.tar.gz ... OK
Configuring indirect-0.31 ... OK
Building and testing indirect-0.31 ... OK
Successfully installed indirect-0.31
--> Working on bareword::filehandles
Fetching http://search.cpan.org/CPAN/authors/id/I/IL/ILMARI/bareword-filehandles-0.003.tar.gz ... OK
Configuring bareword-filehandles-0.003 ... OK
Building and testing bareword-filehandles-0.003 ... OK
Successfully installed bareword-filehandles-0.003
Building and testing strictures-1.005003 ... OK
Successfully installed strictures-1.005003
--> Working on Role::Tiny
Fetching http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/Role-Tiny-1.003002.tar.gz ... OK
Configuring Role-Tiny-1.003002 ... OK
Building and testing Role-Tiny-1.003002 ... OK
Successfully installed Role-Tiny-1.003002
--> Working on Class::Method::Modifiers
Fetching http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/Class-Method-Modifiers-2.09.tar.gz ... OK
==> Found dependencies: Module::Build::Tiny
--> Working on Module::Build::Tiny
Fetching http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/Module-Build-Tiny-0.035.tar.gz ... OK
==> Found dependencies: TAP::Harness::Env, ExtUtils::Helpers, ExtUtils::InstallPaths, ExtUtils::Config
--> Working on TAP::Harness::Env
Fetching http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/Test-Harness-3.30.tar.gz ... OK
Configuring Test-Harness-3.30 ... OK
Building and testing Test-Harness-3.30 ... OK
Successfully installed Test-Harness-3.30
--> Working on ExtUtils::Helpers
Fetching http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/ExtUtils-Helpers-0.021.tar.gz ... OK
Configuring ExtUtils-Helpers-0.021 ... OK
Building and testing ExtUtils-Helpers-0.021 ... OK
Successfully installed ExtUtils-Helpers-0.021
--> Working on ExtUtils::InstallPaths
Fetching http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/ExtUtils-InstallPaths-0.010.tar.gz ... OK
Configuring ExtUtils-InstallPaths-0.010 ... OK
==> Found dependencies: ExtUtils::Config
--> Working on ExtUtils::Config
Fetching http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/ExtUtils-Config-0.007.tar.gz ... OK
Configuring ExtUtils-Config-0.007 ... OK
Building and testing ExtUtils-Config-0.007 ... OK
Successfully installed ExtUtils-Config-0.007
Building and testing ExtUtils-InstallPaths-0.010 ... OK
Successfully installed ExtUtils-InstallPaths-0.010
Configuring Module-Build-Tiny-0.035 ... OK
Building and testing Module-Build-Tiny-0.035 ... OK
Successfully installed Module-Build-Tiny-0.035
Configuring Class-Method-Modifiers-2.09 ... OK
Building and testing Class-Method-Modifiers-2.09 ... OK
Successfully installed Class-Method-Modifiers-2.09
--> Working on Devel::GlobalDestruction
Fetching http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/Devel-GlobalDestruction-0.12.tar.gz ... OK
Configuring Devel-GlobalDestruction-0.12 ... OK
==> Found dependencies: Sub::Exporter::Progressive
--> Working on Sub::Exporter::Progressive
Fetching http://search.cpan.org/CPAN/authors/id/F/FR/FREW/Sub-Exporter-Progressive-0.001011.tar.gz ... OK
Configuring Sub-Exporter-Progressive-0.001011 ... OK
Building and testing Sub-Exporter-Progressive-0.001011 ... OK
Successfully installed Sub-Exporter-Progressive-0.001011
Building and testing Devel-GlobalDestruction-0.12 ... OK
Successfully installed Devel-GlobalDestruction-0.12
--> Working on Import::Into
Fetching http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/Import-Into-1.002000.tar.gz ... OK
Configuring Import-Into-1.002000 ... OK
Building and testing Import-Into-1.002000 ... OK
Successfully installed Import-Into-1.002000
Building and testing Moo-1.004002 ... OK
Successfully installed Moo-1.004002
20 distributions installed
You have Scalar::Util (1.23)
You have Test::Harness (3.30)
You have Test::More (0.98)
You have Time::HiRes (1.9721_01)
--> Working on XML::SAX::ExpatXS
Fetching http://search.cpan.org/CPAN/authors/id/P/PC/PCIMPRICH/XML-SAX-ExpatXS-1.33.tar.gz ... OK
Configuring XML-SAX-ExpatXS-1.33 ... OK
==> Found dependencies: XML::SAX
--> Working on XML::SAX
Fetching http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-SAX-0.99.tar.gz ... OK
Configuring XML-SAX-0.99 ... OK
==> Found dependencies: XML::NamespaceSupport, XML::SAX::Base
--> Working on XML::NamespaceSupport
Fetching http://search.cpan.org/CPAN/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.11.tar.gz ... OK
Configuring XML-NamespaceSupport-1.11 ... OK
Building and testing XML-NamespaceSupport-1.11 ... OK
Successfully installed XML-NamespaceSupport-1.11
--> Working on XML::SAX::Base
Fetching http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-SAX-Base-1.08.tar.gz ... OK
Configuring XML-SAX-Base-1.08 ... OK
Building and testing XML-SAX-Base-1.08 ... OK
Successfully installed XML-SAX-Base-1.08
Building and testing XML-SAX-0.99 ... OK
Successfully installed XML-SAX-0.99
Building and testing XML-SAX-ExpatXS-1.33 ... OK
Successfully installed XML-SAX-ExpatXS-1.33
4 distributions installed
--> Working on ./xs
Configuring /home/cnc-machine/Slic3r/xs ... OK
==> Found dependencies: ExtUtils::Typemaps::Default, ExtUtils::Typemap
--> Working on ExtUtils::Typemaps::Default
Fetching http://search.cpan.org/CPAN/authors/id/S/SM/SMUELLER/ExtUtils-Typemaps-Default-1.05.tar.gz ... OK
Configuring ExtUtils-Typemaps-Default-1.05 ... OK
Building and testing ExtUtils-Typemaps-Default-1.05 ... OK
Successfully installed ExtUtils-Typemaps-Default-1.05
--> Working on ExtUtils::Typemap
Fetching http://search.cpan.org/CPAN/authors/id/S/SM/SMUELLER/ExtUtils-Typemap-1.00.tar.gz ... OK
Configuring ExtUtils-Typemap-1.00 ... OK
Building and testing ExtUtils-Typemap-1.00 ... OK
Successfully installed ExtUtils-Typemap-1.00
Building and testing Slic3r-XS-0.01 ... OK
Successfully installed Slic3r-XS-0.01
3 distributions installed
t/angles.t ........... ok     
t/arcs.t ............. skipped: arcs are currently disabled
t/clean_polylines.t .. ok   
t/clipper.t .......... ok   
t/collinear.t ........ ok     
t/combineinfill.t .... ok   
t/config.t ........... ok   
t/cooling.t .......... ok     
t/custom_gcode.t ..... ok   
t/dynamic.t .......... skipped: variable-width paths are currently disabled
t/fill.t ............. ok     
t/gcode.t ............ ok   
t/geometry.t ......... ok     
t/layers.t ........... ok   
t/loops.t ............ skipped: temporarily disabled
t/multi.t ............ ok   
t/perimeters.t ....... 6/6 
#   Failed test 'no superfluous extra perimeters'
#   at t/perimeters.t line 168.
# Looks like you failed 1 test of 6.
t/perimeters.t ....... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests 
t/polyclip.t ......... ok     
t/print.t ............ ok   
t/retraction.t ....... ok     
t/shells.t ........... ok     
t/skirt_brim.t ....... ok   
t/slice.t ............ skipped: temporarily disabled
t/support.t .......... ok     
t/svg.t .............. ok   
t/threads.t .......... ok   
t/vibrationlimit.t ... ok   

Test Summary Report
-------------------
t/perimeters.t     (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  6
  Non-zero exit status: 1
Files=27, Tests=223, 464 wallclock secs ( 0.52 usr  0.09 sys + 501.84 cusr  6.12 csys = 508.57 CPU)
Result: FAIL
Some tests failed. Please report the failure to the author!

in the last attempt to install i was using 13.10 ubuntu and it failed at this point. i continued to install and when it absolutely failed i ask for help and the issue was closed before i got to it. the terminal is open and the system is running.i might not respond directly do not close this issue as i ill get to you and comply with corrective directions as i can.

**Comment by lordofhyphens** [comment]
Test failures does not mean the program won't run at all, but it might be weird.
On ubuntu there's a package for slic3r, and you can build packages from my fork if you want a modern version (or use the version built by the people at prusa3d.com).
