### ISSUE TITLE
Octoprint Integration

### ISSUE THREAD

**Issue by lisa-lionheart** [alexrj/Slic3r#1826]
The latest versions of Octoprint have an API that allows you to upload gcode and print it. It would save quite a few steps for those of us who use Octoprint in our work flow if we had a little button that automatically slices and sends it to our printer.

https://github.com/foosel/OctoPrint/wiki/REST-API

Doesn't seem like it would be hard to do, I would look into doing this my self but my perl is pretty rusty

**Comment by Jerware** [comment]
Curious if connecting to OctoPrint using a port other than 80 works. I am trying to access my OctoPi server remotely using Slic3r 1.2.4, and it's reporting a timeout. In the host field I'm typing `my.domain:8100` and I have the universal API key pasted below it.

**Comment by alexrj** [comment]
The timeout has been extended in 1.2.5-dev.

**Comment by timelapse2000** [comment]
I would like to try the new upload feature, but I am not sure what to put in the Host or IP: box. I don't know very much about this sort of stuff, so help would be appreciated. Right now I'm putting in 192.168.1.105 (My pi's IP) and 4C50782D1D824590AE53EF0B446D9FD2 (This is the key in the octoprint settings) but it gives me a "I wasn't able to connect to Octoprint" error.
Thank you!

**Comment by jgangemi** [comment]
i'm seeing the same behavior. i can access the server just fine from a browser using `http://octopl.local` but using just `octopi.local` or the ip address in slic3r results in an error.

**Comment by CptanPanic** [comment]
I am having same problem.  When I try the Test button I get (405 METHOD NOT ALLOWED)

**Comment by sbliven** [comment]
I'm also getting the 405 Error from the test button but successful print uploads.

**Comment by vashdansky** [comment]
Am I just stupid..? i cant find any buttons or settings that allow me to connect to my octoprint from slic3r?? what am i doing wrong... i am using the latest experimental...

**Comment by timelapse21** [comment]
Try going into printer settings, there should be a box for your octoprint address and API key.
