### ISSUE TITLE
Export STL does not respect "print center" setting

### ISSUE THREAD

**Issue by Lenbok** [alexrj/Slic3r#1829]
I have my printer set so that the coordinate origin is in the center of the print bed (i.e. "print center" = 0,0).

When I export a plate as GCODE, all is good.

When I export a plate as an STL, the resulting STL coordinates assume the origin is at the lower left, and do not correspond with the coordinates used when exporting GCODE.

The export STL function should respect the printer setting in this regard, so in my case the resulting STL should be centered on 0,0

(I am currently using 1.0RC2)

**Comment by alexrj** [comment]
It does as of recent versions. Thank you
