### ISSUE TITLE
Slic3r keeps crashing on mac, after every 3 slices or so.

### ISSUE THREAD

**Issue by 3daybreaker** [alexrj/Slic3r#1833]
My Clic3r keeps crashing every 2nd or 3rd slice attempt.
When I restart, it will slice 2 or 3 times again.
So now, I will restart before every slice.... bit cumbersome.

=========
Process: slic3r [42731]
Path: /Users/USER/Desktop/Slic3r 2.app/Contents/MacOS/slic3r
Identifier: slic3r
Version: Slic3r 1.0.0.70 (1.0.0.70)
Code Type: X86 (Native)
Parent Process: launchd [141]
Responsible: slic3r [42731]
User ID: 501

Date/Time: 2014-03-14 17:20:36.039 +0100
OS Version: Mac OS X 10.9.2 (13C64)
Report Version: 11
Anonymous UUID: D6E0CFA7-3711-198B-C1D7-613276898C41

Sleep/Wake UUID: 9D445B45-4A96-4CF0-9947-90E1B9931B47

Crashed Thread: 5

Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000060c9652c

And than a lot of code....
is this a known bug?

**Comment by alexrj** [comment]
This should be fixed as of today.
