### ISSUE TITLE
Feature Request - Support material STL.

### ISSUE THREAD

**Issue by Lodran** [alexrj/Slic3r#1838]
Generally, I design models that utilize bridges and such so that they don't require support.  However, in some cases, you want to add support regardless - perhaps the bridge is too long, or it's simply impossible to design an area so that it won't need support.

I'd like to be able to provide an STL which defines either those areas which are candidates for support, or those areas which are not to be supported under any circumstances.

**Comment by alexrj** [comment]
This continues in #2570. Will come soon. :)
