### ISSUE TITLE
Separate layer height setting for raft and nicer rafts!

### ISSUE THREAD

**Issue by nothinman** [alexrj/Slic3r#1840]
Rafts help prints to stick to bed, also prevent warping somewhat. But also... compensate for uneven bed.
Mine is 300x350mm; I have a thick plate, but it's still tiny bit uneven (I'd say +/- .15mm).
Having two layers of thick (.3mm?) raft would definitely help my 0.1mm prints.
I'm trying to make small steps towards a really nice rafts, something like Zortrax printer produces.
Good video can be seen here: https://www.youtube.com/watch?v=0Zgu0BhJiA0

Marcin

**Comment by alexrj** [comment]
As of recent changes, Slic3r now makes thick rafts ignoring the configured object layer height. So I think we can close this one. Thank you for the idea.
