### ISSUE TITLE
Feature Request: Temporary Filenames while saving

### ISSUE THREAD

**Issue by criede** [alexrj/Slic3r#1844]
Hello,

It happened some times to me that I opened a gcode file in pronterface before slic3r finished generating it. That results in a partial print, according to murphys law after 2/3 of the whole object. Very annoying.

There is an easy fix for that that could be implemented easily in slic3r:  When saving gcode, execute the following steps:
- if file to be written already exisis, rename it to a temporary filename 1
- write new file with a  new temporary filename 2
- if write successfully finished, mv tmpfile2 to outfile
- if write not successful, mv tmpfile1 to outfile 

I would be very please if you could implement this small change.

Regards, Christian Riede

**Comment by alexrj** [comment]
Done!
