### ISSUE TITLE
Thinner Skirt Extrusion

### ISSUE THREAD

**Issue by Patbeck** [alexrj/Slic3r#1846]
I have problems with sticking to bed skirt layer, when I used slic3r 0.9.10b I had more extrusion in the skirt, cleaning mi hotend and sticks very well. When I use Slic3r 1.0.0RC3 I have a thinner skirt layer and doesn´t stick to bed. Make the slicing process with the 2 versions of Slic3r and I found that automatic calculations on various width parameters are affected by 0.13mm, 0.9.10b had more width, having better stick and cleaning better first layer. Obviously I used the same Config File and the same .STL object.

; generated by Slic3r 0.9.10b on 2014-03-20 at 11:36:50

; layer_height = 0.25
; perimeters = 2
; top_solid_layers = 2
; bottom_solid_layers = 1
; fill_density = 0.20
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 100
; nozzle_diameter = 0.4
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.53mm  <-------------------
; infill extrusion width = 0.53mm
; solid infill extrusion width = 0.53mm
; top infill extrusion width = 0.53mm
; support material extrusion width = 0.53mm <------------------
; first layer extrusion width = 0.80mm

; generated by Slic3r 1.0.0RC3 on 2014-03-20 at 11:22:06

; layer_height = 0.25
; perimeters = 2
; top_solid_layers = 2
; bottom_solid_layers = 1
; fill_density = 0.20
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 100
; nozzle_diameter = 0.4
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.40mm <------------------
; infill extrusion width = 0.53mm
; solid infill extrusion width = 0.53mm
; top infill extrusion width = 0.53mm
; support material extrusion width = 0.40mm <--------------------
; first layer extrusion width = 0.80mm

OS: Windows 7 64 bits

It´s normall by new version automatic calculations? Do i need to especify manually this parameters to obtain my older best results?

**Comment by lordofhyphens** [comment]
You can override the first layer extrusion width, which is what the brim (which is what you should use to fight warp) in modern versions of slic3r. Closing.
