### ISSUE TITLE
Generating support Issue with free standing threaded objects. Slic3r 1.0.0RC3

### ISSUE THREAD

**Issue by Opticalworm** [alexrj/Slic3r#1851]
Hello guys, 
recently I've been trying to print a part for a friend which has a feature that is threaded and protrudes from one of the sides. the feature comes out at 90 degree angle(see image). I was using Slic3r's default settings but with support enable. It will correctly add the support for the same part as long as its not threaded.

In the end I manage to print the part for my friend by setting slic3r support threshold to 60 degree. That, unfortunately, forced everything in the model to be supported when I didn't need it to.

I've attached a couple of images and two test models that are virtually identical apart from one that doesn't have the thread.

![slic3r_gcode](https://f.cloud.github.com/assets/2886937/2493945/a6424f14-b2ad-11e3-8edd-35c195029b68.png)
![slic3r_model](https://f.cloud.github.com/assets/2886937/2493946/a658c7d0-b2ad-11e3-80c6-8a87045bf2d0.png)

you can file the test model here:
https://www.dropbox.com/sh/lbeb4iqn289ld2p/HQkQdYnP8Y

**Comment by lordofhyphens** [comment]
please check on https://github.com/alexrj/Slic3r/files/336282/slic3r-most_prs.zip or release 1.2.9.

**Comment by stth1998** [comment]
Looks partially good in 1.2.9. The support for free hanging first layers is startet at a certain overhang angle threshold, not always

![supp_25deg](https://cloud.githubusercontent.com/assets/5288317/16456482/47b302c4-3e18-11e6-9057-c9cb058489b6.png)
![supp_35deg](https://cloud.githubusercontent.com/assets/5288317/16456484/47b5e1ce-3e18-11e6-8813-eeaebeb872ce.png)
![supp_45deg](https://cloud.githubusercontent.com/assets/5288317/16456483/47b40a7a-3e18-11e6-9745-96635eb64c14.png)
![supp_55deg](https://cloud.githubusercontent.com/assets/5288317/16456485/47b867aa-3e18-11e6-9dc5-1b36c4474352.png)

**Comment by whosawhatsis** [comment]
Sounds like you're seeing the same problem as https://github.com/alexrj/Slic3r/issues/3062 and https://github.com/alexrj/Slic3r/issues/2222
