### ISSUE TITLE
Slic3r 1.0.0RC3 - Infills on bridge attempts falling short a perimiter

### ISSUE THREAD

**Issue by kyrreaa** [alexrj/Slic3r#1852]
Trying to slice the flatfoot ultra high rez standford bunny with 3 perimiters allowing extras and no infill results in some odd paths.
Firstly the inner perimiters at one point have no support at all due to them being laid down in free air. Maby it should have used outer->inner ordering in such cases?  Or it could add chords to the curvatures to generate additional support internally to the object before attempting such a placement.
Further more though when it comes to adding solid layers as part of capping off the surface it will tack on the innfill to one side and leave it hanging in free air on the other for no apparant reason. Pics show a sequence of 3 layers where this happens on the middle image.
![missing_perim_1](https://f.cloud.github.com/assets/3826624/2494026/78cded4a-b2b2-11e3-814e-a88ddc96e546.png)
![missing_perim_2](https://f.cloud.github.com/assets/3826624/2494029/a17d08ac-b2b2-11e3-95c6-968faf80f794.png)
![missing_perim_3](https://f.cloud.github.com/assets/3826624/2494034/f96eb894-b2b2-11e3-9da4-5ab78669ef64.png)

Result is gaps and holes.
Bridging internally in model a few layers before problem areas like this should be possible as moving nozzle next to the previous extrude width (using nozzle dia to know ehere and adding a tiny overlap) will tack the new filament onto the edge of the current layer assuming perimiters are done before infill. It requires not falling short of the edge though, which is happening in my slice.  The end not falling short is being tacked on nicely and makes a internal "beard" hanging down from the one side.

**Comment by lordofhyphens** [comment]
Could someone check this on 1.2.9 or 1.3.0-dev and see if it's still a problem?

**Comment by lordofhyphens** [comment]
Looks good now, since the extra perimeters fix that went in a few months ago.

![image](https://cloud.githubusercontent.com/assets/31754/24417636/d120afae-13ae-11e7-9989-112df67a8550.png)

Please reopen (or make a separate issue with a full reproduction using new version of Slic3r) if you are still having issues.
