### ISSUE TITLE
Automatic config backup

### ISSUE THREAD

**Issue by luismanson** [alexrj/Slic3r#1857]
It would be nice to have slic3r save a backup (kinda like versioning) on every setting save, until MAX_HISTORY. Because at lest for a newbie like me its very easy to start changing parameters one by one until you mess the print and/or do not remember what setting caused a probem

**Comment by lordofhyphens** [comment]
The files live in a specific folder (~/.Slic3r on Linux or OSX, the profile folder on Windows), put that folder under version control using a program like Git or Subversion. Heck, even Dropbox if you're paying for the soft version control stuff.
Slic3r is already a bit of a "kitchen sink" application, agree we don't want to stick unrelated functionality that is already done better with other programs.
