### ISSUE TITLE
Printing a part in more than one step

### ISSUE THREAD

**Issue by autorobotics** [alexrj/Slic3r#1863]
Hey,
I am actually printing a part which will need about 8 hours to print. So I printed 2.30 hours and stopped printing at a building height xxx. By using kapton- tape the part keeps fixed to the heating-bed when turned off. I saw, that slic3r has the possibility to set a negative offset in z, but generating g-code, the skirt loops will be <0 (as set in negative offset) => is it possible to restart printing with offset and doing the skirt loops before?
(Cura has the possibility to set something like "cut off object bottom")

**Comment by lordofhyphens** [comment]
There's a Cut option in the current stable version of slic3r, lets you divide the model across an axis. Export the components as STL.

Going to close.
