### ISSUE TITLE
Slic3r on Mac quits after 2 exports of gcode of same object V1.x.x

### ISSUE THREAD

**Issue by tmorris9** [alexrj/Slic3r#1883]
Slic3r 1.0.0 R1,R2 and release version 1.0.0

Load valid STL (any) and export twice (same name or different) and slic3r unexpectedly quits upon completion of second save. Second Gcode is valid and works.

If you delete the object and load another object between saves it's fine.

This is repeatable over and over using many different objects. No error is shown so no error codes given.

Mac 10.6.8 (Snow Leopard), 32Gb Ram, Quad Core I7 processor

**Comment by alexrj** [comment]
Fixed as of 1.2.6-dev
