### ISSUE TITLE
Feature Request - Handle top and bottom solid infill as perimeter (multiple Extruders)

### ISSUE THREAD

**Issue by elkooo** [alexrj/Slic3r#1890]
Hey there, 

Since I work more and more with my dual extrusion printer, I get over stuff I didn't mind about before.

At the moment I have a Project where I need expensive printing material due to its chemical stability. I would like to combine it with cheaper PLA for the infill which works great for all outlines in x and y direction. For the top and bottom solid layers, the infill extruder is used since this is counted to infill (solid infill).
Instead of that I would prefer, if top and bottom layers would be printed by the outline extruder (perhaps as an option? Probably it would be the best, if you have the choice…). 

My idea behind this is, that you can use one material for all visible parts of an object while the inside of it is printed by for example less expensive or different quality/coloured material. 

For example if you like to have many different colours in stock, you will need much less material of each colour and you could use the cheapest (colourless) material for infill while all covering is done by the desired colour or material quality…

Would be great, if you could include this in future versions! Keep up the great work!

Cheers, 
elkooo

**Comment by lordofhyphens** [comment]
The multiple extruder setup lets you define different extruders for different motions.
Solid infill is separate from regular infill and perimeters too.
Modifier meshes let you assign different extruders to different areas of the model. I think this is already covered by those two, please reopen if you don't agree :)
