### ISSUE TITLE
Incorrect number of top infill layers in certain situations

### ISSUE THREAD

**Issue by mkurc1234** [alexrj/Slic3r#1895]
During my latest print i noticed that in a certain area of the model, there is only a single top infill layer and it is very sparse. I have reviewed the gcode in Repetier host and the top infill layers in that area were missing indeed, while in other places the infill was correct. It looks like the Slic3r have omitted the top infill completely as the infill looks like an intermediate one. The issue has manifested itself on a particular model only, others with similar geometrical configuration were sliced correctly.

I have tested this issue in Slic3r version 1.0.0-RC3, 1.0.0-Stable and 1.1.0, the results were identical. The settings were: 6  top infill layers and solid infill every 8 layers. I have attached the slic3r.ini and command line to this post. I have also attached pictures of the gcode visualization.

Unfortunately i was unable to attach the source model file and the generated gcode. I can provide the data via e-mail for request.

![layer16_small](https://cloud.githubusercontent.com/assets/7130520/2583498/ff2dd578-b9d1-11e3-8ea8-f2fd0c241605.jpg)
![layer17_small](https://cloud.githubusercontent.com/assets/7130520/2583508/1812fb54-b9d2-11e3-9936-b4ed788cd25a.jpg)
![layer18_small](https://cloud.githubusercontent.com/assets/7130520/2583516/2aae538a-b9d2-11e3-911a-0f97a361bc0e.jpg)

Command line:
slic3r.exe --load "D:\Repetier\slic3r.ini" --print-center 100,95 --layer-height 0.30 --cooling --fill-pattern honeycomb --solid-fill-pattern rectilinear --fill-angle 45 --fill-density 0.50 -o "D:\Repetier\composition.gcode" "D:\Repetier\composition.obj"

Slic3r INI file:
avoid_crossing_perimeters = 1
bottom_solid_layers = 4
bridge_acceleration = 0
bridge_flow_ratio = 1
bridge_speed = 70
brim_width = 0
complete_objects = 0
default_acceleration = 0
external_perimeter_speed = 95%
external_perimeters_first = 
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 100%
fill_angle = 45
fill_density = 0.35
fill_pattern = honeycomb
first_layer_acceleration = 0
first_layer_extrusion_width = 110%
first_layer_height = 0.25
first_layer_speed = 50%
gap_fill_speed = 20
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 170%
infill_first = 
infill_only_where_needed = 0
infill_speed = 60
layer_height = 0.25
min_skirt_length = 1
notes = 
only_retract_when_crossing_perimeters = 1
ooze_prevention = 0
output_filename_format = [input_filename_base].gcode
overhangs = 
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 170%
perimeter_speed = 30
perimeters = 2
post_process = 
raft_layers = 0
randomize_start = 1
resolution = 0
skirt_distance = 6
skirt_height = 1
skirts = 2
small_perimeter_speed = 80%
solid_fill_pattern = rectilinear
solid_infill_below_area = 25
solid_infill_every_layers = 8
solid_infill_extrusion_width = 100%
solid_infill_speed = 50
spiral_vase = 0
standby_temperature_delta = -5
start_perimeters_at_concave_points = 1
start_perimeters_at_non_overhang = 1
support_material = 
support_material_angle = 45
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_extruder = 1
support_material_interface_layers = 0
support_material_interface_spacing = 0
support_material_pattern = rectilinear-grid
support_material_spacing = 2.5
support_material_speed = 50
support_material_threshold = 75
thin_walls = 1
threads = 2
top_infill_extrusion_width = 100%
top_solid_infill_speed = 30%
top_solid_layers = 6
travel_speed = 200
bed_size = 200,190
end_gcode = M104 S100                   ; Extruder\nM140 S25                    ; Bed\nG91; Relative\nG1 E-1 F300; Retract\nG1 Z+5 E-5 X-10 Y-10 F6000; Wipe & lift Z\nG28 X0 Y0; Home\nG90; Absolute\nG1 Y180 F12000; Bring the table to front\nM84; Disable motors
extruder_offset = 0x0
gcode_flavor = reprap
layer_gcode = 
nozzle_diameter = 0.5
print_center = 100,95
retract_before_travel = 1
retract_layer_change = 1
retract_length = 3
retract_length_toolchange = 10
retract_lift = 0
retract_restart_extra = 0.1
retract_restart_extra_toolchange = 0
retract_speed = 70
start_gcode = G28 ; home all axes\nG90 ; use absolute coordinates\nG21 ; set units to millimeters\nG92 E0\nM82 ; use absolute distances for extrusion\nM201 X800 Y800 ; Przyspieszenia maksymalne\nM205 X15 ; Jerk\nG1 E8 F400 ; prime the nozzle
toolchange_gcode = 
use_firmware_retraction = 0
use_relative_e_distances = 1
vibration_limit = 0
wipe = 1
z_offset = 0
bed_temperature = 40
bridge_fan_speed = 100
cooling = 1
disable_fan_first_layers = 3
extrusion_multiplier = 1.025
fan_always_on = 1
fan_below_layer_time = 30
filament_diameter = 3
first_layer_bed_temperature = 40
first_layer_temperature = 185
max_fan_speed = 100
min_fan_speed = 45
min_print_speed = 10
slowdown_below_layer_time = 15
temperature = 185

**Comment by lordofhyphens** [comment]
This still a problem in 1.2.9 or 1.3.0-dev? 
Please provide a slic3r screenshot, and you should be able to zip up the config and model and drag/drop it onto the github window.

**Comment by alexrj** [comment]
Closing this one. Unfortunately the files were not sent to me. It's probably fixed as of now.
