### ISSUE TITLE
--gcode-arc not working in 1.0

### ISSUE THREAD

**Issue by strahlex** [alexrj/Slic3r#1898]
The --gcode-arc command gives a segmentation fault in slic3r version 1.0.

**Comment by lordofhyphens** [comment]
It's disabled as of 1.2.9. There's a separate issue for tracking gcode-arc. 
Closing.

**Comment by bubnikv** [comment]
By the way, there is not much advantage of generating the arc G-codes with the current Marlin firmware.  The Marlin firmware internally generates a sequence of short linear movements, so the only real advantage of using the arc g-code is a shorter g-code file. It would be a different story, if the 3D printer firmware applied a separate logic to the acceleration control of the arcs.

**Comment by lordofhyphens** [comment]
I think smoothieware does a better job handling arcs.

**Comment by strahlex** [comment]
Machinekit also

**Comment by lordofhyphens** [comment]
#3381 tracks this issue now.
