### ISSUE TITLE
stable giving segfault error

### ISSUE THREAD

**Issue by iplayfast** [alexrj/Slic3r#1905]
on mint 16, 64, running stable 64.

Unknown option interface_shells
The program 'slic3r' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadFormat (invalid PictFormat parameter)'.
  (Details: serial 50139 error_code 142 request_code 139 minor_code 2)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
The program 'slic3r' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadRequest (invalid request code or no such operation)'.
  (Details: serial 50158 error_code 1 request_code 255 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Segmentation fault

This happened when exporting to g-code, although no gcode or gcode file was generated.

config.ini is
# generated by Slic3r 1.1.0 on Thu Apr  3 22:30:38 2014
avoid_crossing_perimeters = 1
bed_size = 284.2,301.88
bed_temperature = 75
bottom_solid_layers = 2
bridge_acceleration = 0
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 40
brim_width = 0
complete_objects = 0
cooling = 1
default_acceleration = 0
disable_fan_first_layers = 1
duplicate_distance = 6
end_gcode = G92 E0; reset extruder\nG1 E-1 F1000; retract extruder to prevent final string\nG1 E-2 F1000; retract extruder to prevent final string\nG1 E-3 F1000; retract extruder to prevent final string\nG1 E-4 F1000; retract extruder to prevent final string\nG1 E-5 F1000; retract extruder to prevent final string\nT0;\nM104 S0 ; turn off temperature\nT1;\nM104 S0 ; turn off temperature\nT2;\nM104 S0 ; turn off temperature\nT3;\nM104 S0 ; turn off temperature\nT4;\nM104 S0 ; turn off temperature\nM140 S0 ; Turn off heated print bed\nG28 X0  ; home X axis\nM84     ; disable motors
external_perimeter_speed = 40
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 10x10,72.95x12.05,9.35x37.7,73.18x38.65,41.6x38.25
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
fan_always_on = 0
fan_below_layer_time = 60
filament_diameter = 1.8
fill_angle = 45
fill_density = 30%
fill_pattern = rectilinear
first_layer_acceleration = 0
first_layer_bed_temperature = 75
first_layer_extrusion_width = 175%
first_layer_height = 0.3
first_layer_speed = 20
first_layer_temperature = 215
g0 = 0
gap_fill_speed = 40
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 1
infill_only_where_needed = 0
infill_speed = 40
interface_shells = 0
layer_gcode = 
layer_height = 0.3
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 5
min_skirt_length = 0
notes = 
nozzle_diameter = 0.5,0.5,0.5,0.5,0.5
only_retract_when_crossing_perimeters = 1
ooze_prevention = 1
output_filename_format = [input_filename_base].gcode
overhangs = 1
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 40
perimeters = 3
post_process = 
print_center = 142.1,150.94
raft_layers = 0
randomize_start = 0
resolution = 0
retract_before_travel = 20,20,20,20,20
retract_layer_change = 0,0,0,0,0
retract_length = 26,26,26,26,21
retract_length_toolchange = 26,26,26,26,21
retract_lift = 0,0,0,0,0
retract_restart_extra = 0,0,0,0,0
retract_restart_extra_toolchange = 0.5,1,0,0,0
retract_speed = 5,5,3,5,3
skirt_distance = 10
skirt_height = 1
skirts = 2
slowdown_below_layer_time = 30
small_perimeter_speed = 40
solid_fill_pattern = rectilinear
solid_infill_below_area = 1
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0
solid_infill_speed = 40
spiral_vase = 0
standby_temperature_delta = -1
start_gcode = M106 S255; turn fans on\nG28 ; home all axes\nT0; //set the 1st extruder to be active
start_perimeters_at_concave_points = 0
start_perimeters_at_non_overhang = 0
support_material = 0
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_extruder = 1
support_material_interface_layers = 1
support_material_interface_spacing = 2.5
support_material_pattern = rectilinear
support_material_spacing = 4
support_material_speed = 40
support_material_threshold = 0
temperature = 215
thin_walls = 1
threads = 4
toolchange_gcode = 
top_infill_extrusion_width = 0
top_solid_infill_speed = 40
top_solid_layers = 3
travel_speed = 12
use_firmware_retraction = 0
use_relative_e_distances = 0
vibration_limit = 0
wipe = 1,1,1,1,1
z_offset = 0

Making this test object
http://www.thingiverse.com/thing:38096

**Comment by lordofhyphens** [comment]
Is this still a problem?
