### ISSUE TITLE
1.11 - no way to keep fan from coming on when printing ABS

### ISSUE THREAD

**Issue by rsilvers129** [alexrj/Slic3r#1910]
I never want the cooling fan to come on when printing ABS, but I do want "autocooling" to slow down the print speed for faster layers. 

I would like a check box to keep the layer-speed auto-cooling on without having the fan come on ("never use cooling fan (ABS mode)")

**Comment by lordofhyphens** [comment]
Set max fan to 0%. Active cooling on ABS is something of an art form though, you can get away with a lot more of it in a heated enclosure.

Closing.
