### ISSUE TITLE
Starting Slic3r 1.1.0 experimental

### ISSUE THREAD

**Issue by tomaswallentinus** [alexrj/Slic3r#1914]
Hi.

When I start 1.1.0 experimental i recive error messages and then it closes down.

"Runtime Error!

Program: C:\3d\Slic3r 1.1.0 ecperimental\slic3r.exe

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

Then it closes down after you have pressed "Ok"

Windows 8.1 Pro (64-bit)
Microsoft Visual C++ 2010 (x64) and (x86) 10.0.40219
Microsoft Visual C++ 2008 (x64) and (x86) 9.0.30726.6161

From the Windows logbook:

&lt;Event xmlns=&quot;http://schemas.microsoft.com/win/2004/08/events/event&quot;&gt;
- &lt;System&gt;
  &lt;Provider Name=&quot;Application Error&quot; /&gt; 
  &lt;EventID Qualifiers=&quot;0&quot;&gt;1000&lt;/EventID&gt; 
  &lt;Level&gt;2&lt;/Level&gt; 
  &lt;Task&gt;100&lt;/Task&gt; 
  &lt;Keywords&gt;0x80000000000000&lt;/Keywords&gt; 
  &lt;TimeCreated SystemTime=&quot;2014-04-07T06:05:25.000000000Z&quot; /&gt; 
  &lt;EventRecordID&gt;21225&lt;/EventRecordID&gt; 
  &lt;Channel&gt;Application&lt;/Channel&gt; 
  &lt;Computer&gt;TomasWin8&lt;/Computer&gt; 
  &lt;Security /&gt; 
  &lt;/System&gt;
- &lt;EventData&gt;
  &lt;Data&gt;slic3r.exe&lt;/Data&gt; 
  &lt;Data&gt;1.1.0.13&lt;/Data&gt; 
  &lt;Data&gt;503fe867&lt;/Data&gt; 
  &lt;Data&gt;libstdc++-6.dll&lt;/Data&gt; 
  &lt;Data&gt;0.0.0.0&lt;/Data&gt; 
  &lt;Data&gt;4f85cd60&lt;/Data&gt; 
  &lt;Data&gt;40000015&lt;/Data&gt; 
  &lt;Data&gt;0000000000018d18&lt;/Data&gt; 
  &lt;Data&gt;9fc&lt;/Data&gt; 
  &lt;Data&gt;01cf5226e4e74bf0&lt;/Data&gt; 
  &lt;Data&gt;C:3dSlic3r 1.1.0 experimentalslic3r.exe&lt;/Data&gt; 
  &lt;Data&gt;C:3dSlic3r 1.1.0 experimentalcpfworkrtlibstdc++-6.dll&lt;/Data&gt; 
  &lt;Data&gt;9b99ecd0-be1a-11e3-be8e-c860008a753f&lt;/Data&gt; 
  &lt;Data /&gt; 
  &lt;Data /&gt; 
  &lt;/EventData&gt;
  &lt;/Event&gt;

Regards Tomas Wallentinus

**Comment by alexrj** [comment]
Maybe fixed in the mean time or in a bug fix that is contained in 1.2.6-dev.
