### ISSUE TITLE
Feature - merge small internal infill areas into solid infill

### ISSUE THREAD

**Issue by ledvinap** [alexrj/Slic3r#1921]
When slicing hollow box shaped object, surface classification could end up with thin S_TYPE_INTERNAL surface next to S_TYPE_INTERNALSOLID
This is caused by top surface propagating down, turning part of internal surface solid.
This behavior is technically correct, but small internal infills are confusing and maybe hard to print.
It should be quite easy to merge these areas into adjacent internal solid.

Here is illustration of the problem:
![layer3](https://cloud.githubusercontent.com/assets/2318015/2643688/2cdeed0c-bf1f-11e3-8e67-f59d3a9c268d.png)
green - perimeters 
cyan - S_TYPE_INTERNALSOLID
red - S_TYPE_INTERNAL

resulting in confusing g-code (with slightly different settings):
![cover](https://cloud.githubusercontent.com/assets/2318015/2643777/6d28b004-bf20-11e3-8bfb-8641e1422986.png)

I attached this to #1803, the cause is probably different.

**Comment by lordofhyphens** [comment]
Is this still a problem with the gapfill gcode in 1.3.0-dev? The associated issue was closed and marked as fixed. 

Please reopen with a test case and some screenshots from slic3r's 3d preview itself.
