### ISSUE TITLE
Bug(?): Vibration Limit doesn't affect Support (1.0.0 stable)

### ISSUE THREAD

**Issue by jonaskuehling** [alexrj/Slic3r#1929]
Hey,

as shown in #1920 support can end up beeing really hacky on the outlines. To avoid destructive vibrations I tried vibration limit set to something rather small like 1-3Hz for example, but it seems that Slic3r doesn't watch out for possible vibrations caused by support?

I'd have expected, that vibration limit should limit any kind of fast direction changing sequence on any axis, no matter if its caused by infill, perimeters or support. Am I missing something? Or is there maybe any other parameter that prevents Slic3r from limiting feedrates so much that, say, 3Hz won't be exceeded?

Let me know if you need the sample gcode/config!

**Comment by alexrj** [comment]
As of the current implementation, I can confirm that vibration limit is applied to support material as well. I don't remember how it was before. Support material still needs to be smoothed...
