### ISSUE TITLE
Windows 7 Unhandled Exception

### ISSUE THREAD

**Issue by donhuevo** [alexrj/Slic3r#1941]
I got this in both 32bit pro and 64bit pro moving the cursor in the plater tab...
'Unhandled exception at 0x70735f6c in slic3r.exe: 0xC0000005: Access violation reading location 0x70735f6c.'  If I mouse around to the top and quickly get to the 'Add' button, I can choose an stl file and then I get this...
'Unhandled exception at 0x03acfe90 in slic3r.exe: 0xC0000096: Privileged instruction.'
Is it just me?  Did I do it wrong?  I really want the new algorithm for the linear gap fill.  I need to stop the shaking.  It's causing my hobs to strip the filament.

**Comment by alexrj** [comment]
This was fixed.
