### ISSUE TITLE
Failed test 'no gap between perimeters and infill'

### ISSUE THREAD

**Issue by sapir** [alexrj/Slic3r#1971]
Apologies if this is a duplicate. I seem to remember seeing this mentioned in an issue or commit somewhere, but  can't find it.

The above test fails on master on 32-bit linux, with Perl 5.18.

```
t/perimeters.t .. Running Slic3r under Perl >= 5.16 is not supported nor recommended
t/perimeters.t .. 6/7 
#   Failed test 'no gap between perimeters and infill'
#   at t/perimeters.t line 236.
# Looks like you failed 1 test of 7.
t/perimeters.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/7 subtests 
```

By the way, is the warning still relevant? I found issue #1216, which is closed.

**Comment by alexrj** [comment]
Okay, this was fixed as of today.
