### ISSUE TITLE
Restore lost ability to keep head within object where possible

### ISSUE THREAD

**Issue by c-born** [alexrj/Slic3r#1975]
In version 0.9.10b and before, setting "Avoid Crossing Perimeters" would result in the print head staying within the object as much as possible. In all versions since it appears this has taken a more literal meaning, and the head may choose to remain outside the object rather than inside.
This can result in some pretty awful print jobs. Objects that I can slice with 0.9.10b and drop straight in require so much cleanup when sliced with anything more recent that it isn't worth it. However I would really like to be able to make use of some of the cool new features in the latest release.

Can we please have another setting that says to stay inside the object where at all possible? Take a look at this object, sliced with 0.9.10b and then with 1.1.1, with the same configuration settings:
![image](https://cloud.githubusercontent.com/assets/2059837/2810482/439d9d42-cdc3-11e3-80a9-e6e48e3a3e3c.png)

![image](https://cloud.githubusercontent.com/assets/2059837/2810485/59e7d73e-cdc3-11e3-92ef-e8d0769b57ee.png)

The difference is quite dramatic, and is reflected in the printed objects. Note that in printing this object there are no islands, so the head should be able to remain within the objects boundaries for the complete job.

Here are the two gcode files, the original STL, and the config settings used:
https://github.com/alexrj/Slic3r/files/852992/Ob2.zip

I have reported this issue before in #1919 and #1531 , but it wasn't until last night that Alex confirmed on IRC that my interpretation of the "Avoid Crossing Perimeters" setting was a bit off, so we may need a new one.

**Comment by clefranc** [comment]
Any news on this?
Perhaps separate options: 

Avoid crossing outside perimeters
Avoid crossing inside perimeters

**Comment by lordofhyphens** [comment]
Can someone please check in 1.3.0-dev? http://dl.slic3r.org/dev

**Comment by lordofhyphens** [comment]
Original testcase link is dead. Please upload using instructions from https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by c-born** [comment]
@lordofhyphens 
The original was in a Dropbox public folder, Dropbox dropped support for these recently. I've repackaged as .zip (Github doesn't support .7z for some reason) at a 50% size increase here:  [Ob2.zip](https://github.com/alexrj/Slic3r/files/852992/Ob2.zip)

I just tested it against 1.3.0-dev (built 1SEP2016) and the result is MUCH better, only a few open air traverses at the top of the arch, although not quite as good a 0.9.10b.

I'll try to build from current head now and see how it compares.

**Comment by lordofhyphens** [comment]
You have a broken Perl (64-bit perl > 5.18 has problems with exception handling in certain cases).

We have automatic builds now if you want master branch. 
http://dl.slic3r.org/dev/

**Comment by lordofhyphens** [comment]
BTW: If you have supports enabled, check your config settings and set the threshold to 60% (from 0). That's the new default (the semantics for that changed; regular numbers are treated as degrees, % is the old auto but considers 60% of the width of a perimeter to be unsupported). If you want the old old behavior of auto, set it to 200%.

**Comment by lordofhyphens** [comment]
FYI: I suspect it will never be "as good" as 0.9 for that specific test case but it probably either got a lot faster or had better results for another situation. This problem is fairly computationally expensive. Definitely though the second picture from the original post is clearly broken ;)

**Comment by c-born** [comment]
Image is from the latest 1.3.0-dev automatic build, looks the same as from my much older self-built 1.3.0-dev. I don't have supports enabled.

![image](https://cloud.githubusercontent.com/assets/2059837/24078787/47066f96-0ccb-11e7-83f9-11abff444523.png)

I would still like to be able to do my own builds, currently using Strawberry Perl:
> This is perl 5, version 22, subversion 0 (v5.22.0) built for MSWin32-x64-multi-thread

What do I need to do to get builds working again?

**Comment by lordofhyphens** [comment]
Currently: install Strawberry perl 5.18.1.4 (replace c:\Strawberry, no need
to use installer so just get the normal zip).

You will need to rebuild Boost.

That or use 32bit version of perl.

@bubnikv has a separate perl distribution that was built with MSVC that
apparently avoids the problem, but I don't know offhand if you have to
build Slic3r with MSVC then (he does).

**Comment by c-born** [comment]
Ok, I see the problem. Although adding a test that hangs the build process, really?
The documentation does say that croak() doesn't handle exceptions (perldoc Carp), so it really shouldn't be called from within a catch(). It tries to find the calling function, which has been lost by then. Although it should revert to calling die(), looks like this doesn't always work.

**Comment by lordofhyphens** [comment]
It should time out and fail, apparently it dies in such a way that isn't
possible -.-;

**Comment by lordofhyphens** [comment]
Yeah, my current plan is to have it set a flag or something in the handler
and then croak out of the exception.

**Comment by lordofhyphens** [comment]
@c-born Things have changed now, see wiki and #3815. 

It comes down to needing our version of perl until Strawberry sorts itself out. 

I'm closing as the original issue appears to have been resolved.
