### ISSUE TITLE
Some objects are too close; your extruder will collide with them.

### ISSUE THREAD

**Issue by plskyline** [alexrj/Slic3r#1988]
Using both versions 1.01 and 1.00RC3

When adding multiple versions of any object with the Complete Individual Objects checked under Sequential printing I get the error "Some objects are too close; your extruder will collide with them." when trying to generate G-Code. 

Adjusting the extruder clearance radius larger and removing/adding the objects does not help. The extruder clearance height is double the height of the object. Moving the objects by hand further apart fixes this issue and allows me to generate gcode but prevents repeatability between prints, the objects should be loaded automatically the minimum distance apart from each other to satisfy the extruder clearance check.

**Comment by AndKe** [comment]
please reopen this issue.
Slic3r 1.2.9
I tried to split and arrange the attached stl  - and print with "Complete Individual Objects"
I even tried to lower the clearance radius to 1mm and Height to 1mm.  no success.
bed is 255x216mm

![screenshot from 2016-01-13 20-15-16](https://cloud.githubusercontent.com/assets/1468842/12304953/89f10272-ba32-11e5-973f-9901b61a7ca1.png)


![screenshot from 2016-01-13 20-15-53](https://cloud.githubusercontent.com/assets/1468842/12304958/8e9d52a8-ba32-11e5-81d6-c5ec1ed8e908.png)


[Sony100RX2 suspension.stl.zip](https://github.com/alexrj/Slic3r/files/89372/Sony100RX2.suspension.stl.zip)


I wish there were a way to disable this (defective) check.

**Comment by lordofhyphens** [comment]
Well, a workaround is to generate GCODE for each item separately, with the
first one having the Start GCODE specified and the last having the End
Gcode specified, then just concatenate the files.


"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by mrvn** [comment]
Look at the 2D view to see where your objects are overlapping. Problem is that slicer generates a hull around the object (think putting a rubber band around it) and needs a minimum distance from that hull. This is bad for U shaped objects because they are handled like O shaped or solid objects. For that reason you can't interleave 2 U shaped objects like you are trying even if physically that could print.
