### ISSUE TITLE
Hilbertcurve doesn't fill layer

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#2006]
slic3r 1.1.3-dev (latest git master), ubuntu 14.04 (perl 5.18.2, gcc 4.8.2)

I printed the part from http://www.thingiverse.com/thing:258201 following the instructions, using hilbertcurve for top and bottom infill for a fancy finish. That didn't quite work as expected.
1. The top and bottom layers weren't completely filled in. Here's a couple of screenshots:
![screenshot from 2014-05-04 22 07 26](https://cloud.githubusercontent.com/assets/684832/2873981/62a69812-d3ca-11e3-89c8-6dec2fa748eb.png)
![screenshot from 2014-05-04 22 07 49](https://cloud.githubusercontent.com/assets/684832/2873982/655ceb4c-d3ca-11e3-9e19-be084d7cccee.png)
2. My config has 3 solid bottom layers and 4 solid top layers. However, hilbertcurve was only used for one exterior layer, the rest of the solid layers are rectilinear. If that's by design, it was unexpected for me when I saw it. :)

config: http://kefirshare.dreamhosters.com/slic3r-config-PLA-careful-hilbertcurve.ini
gcode: http://kefirshare.dreamhosters.com/seahorse_gear_gear_V2_20140504-215439_1.1.3-dev.gcode

**Comment by lordofhyphens** [comment]
A lot has changed in the intervening years; is this still a problem?

**Comment by robertwallace** [comment]
I can't say -- I don't use Slic3r anymore.   Because of this problem (and others), I switched to a different tool.

**Comment by lordofhyphens** [comment]
It's fixed.
