### ISSUE TITLE
feature - use local XS

### ISSUE THREAD

**Issue by ledvinap** [alexrj/Slic3r#2008]
Maybe it would be useful to prepend local ./xs/blib to @INC, so that local version of XS is used preferentially. It would simplify development and could possibly improve user experience if running master/stable side-by-side.

including blib/lib works, but is far from ideal.

```
+use lib "$FindBin::Bin/xs/blib/lib";
+use lib "$FindBin::Bin/xs/blib/arch/auto/Slic3r/XS";
+
 use Slic3r::XS;   # import all symbols (constants etc.) before they get parsed
```

Maybe Slicer::XS does not need to by system-installed at all (is there any advantage)? Just installing to local tree and using @INC to find it should work in most cases..

**Comment by lordofhyphens** [comment]
local::lib works pretty well actually for slic3r so far as I can tell.

**Comment by alexrj** [comment]
We use local::lib now and it works nicely.
