### ISSUE TITLE
AutoSave Enhancement

### ISSUE THREAD

**Issue by Leary** [alexrj/Slic3r#2010]
I prefer to save the slic3r cfg for each job in the dir with the gcode. It would be useful if there was an option to use the --output-filename-format with the autosave function, either changing the file extension to ini or appending ini. This capability would be used with a GUI option to "Save CFG with gcode". This way each gcode file could be tied directly to the specific configuration that created the gcode.

**Comment by mrvn** [comment]
Could config be stored as comments in the original stl file? Then when the stl file is imported again slic3r could ask wether to use the stored global settings or the stl ones.

Note: When importing multiple stl files the settings could be set per object.

**Comment by lordofhyphens** [comment]
I don't see any provision for comments in the ASCII version of the file
format and there is definitely no comments in the binary format.

So, no.

Could be done for AMF, assuming that other parsers don't choke on
nonstandard syntax or you feel like encoding everything in comments.

**Comment by alexrj** [comment]
Per-object and per-part settings are stored in AMF files when exported (and then reimported back)

**Comment by alexrj** [comment]
Loading configs from G-code files is tracked in #3849

**Comment by lordofhyphens** [comment]
Also overrides are saved in AMF export.

There is some room to save config in AMF export though. Prusa3d was going
this way (as a true project file for plates and such).

I think it is viable.
