### ISSUE TITLE
Repeat last quick slice uses incorrect output file name

### ISSUE THREAD

**Issue by Lenbok** [alexrj/Slic3r#2016]
I just tested this with 1.1.2 and this bug is present. To reproduce:

1) Quick Slice a file, say, **object-a.stl** outputting to **file-a.gcode**.
2) Use the plater to slice (via Export to GCode button) a different set of STLs, outputting to **file-b.gcode**
3) Repeat last Quick Slice (it *should* re-slice **object-a.stl** into **file-a.gcode**)

What actually happens is that step 3 slices **object-a.stl** into the **file-b.gcode**.

**Comment by alexrj** [comment]
Thank you for reporting this. I fixed it.
