### ISSUE TITLE
Slicer precompiled package slic3r-linux-x86_64-1-0-1-stable.tar.gz

### ISSUE THREAD

**Issue by tsantor** [alexrj/Slic3r#2020]
We need to run slic3r automatically at times via command line.  However, when we run the below command we get this:

```
/opt/test/Slic3r/bin/slic3r --version
Failed to initialize virtual file system at <Packaged Modules>/Application::Loader line   1183.
BEGIN failed--compilation aborted at /opt/test/Slic3r/lib/std/File/Glob.pm line 7.
Compilation failed in require at <Packaged Modules>/Application::Loader line 1433.
```

However running with `sudo` give us this:

```
sudo /opt/test/Slic3r/bin/slic3r --version
1.0.1
```

We need to be able to run this via python script using command...however running with sudo would require a password.  Help?

**Comment by querry43** [comment]
I also ran into this just today so the new tarballs have not been fixed.  I recommend re-opening this ticket.  The better fix would be to have default permissions in the tarball as a+r.  I fixed it by doing a bunch of sudo chmod which many people might know how to do.  Certainly most will not know to use strace to find the permission issue.

**Comment by RTimothyEdwards** [comment]
I'm still getting this issue in December 2015. . .  and it's a really simple problem with a simple solution. The file permissions under lib/vrt are sort of random. . . and the directory called "528ccea98cad02a5f453a7135f9ca183" has world read permission but not world execue permission, so no user other than root can see what's down in that directory.  Just doing (as root, of course) "chmod go+x 528ccea98cad02a5f453a7135f9ca183" solves the problem.

That appears to be the only directory missing group execute permissions.  Some are weirdly assigned group write permission, which is usually not a default state you want, but at least I don't see any marked as world writeable, which would be a security issue.

**Comment by alexrj** [comment]
I'm closing this. We're going to use AppImage for 1.3.0 packages.
