### ISSUE TITLE
Feature request: Add a checkbox and a value for retract before and after print (to prevent oozin before print)

### ISSUE THREAD

**Issue by cuthulino** [alexrj/Slic3r#2051]
Hello,
In an other slicer software i loved this feature, because my Hotend is very leaky...

It would be great if you add a checkbox "Retract at beginning and end of print" or sth. like that. And a box for the mm Value of this retract.

As example, the print ends and the extruder pulls 5mm out of the extruder.
Next time you start a print, after the extruder is heated to the wanted temperature, 
the extruder pushes 5mm into the extruder and starts printing.

Like this the oozing before the print starts will be gone.

**Comment by lordofhyphens** [comment]
As a solution (start gcode) has been provided, closing :)

For people with multiple extruders, there's ooze prevention and toolchange gcode as well.
