### ISSUE TITLE
Retract is not triggered when retract-length equals negative retract-restart-extra

### ISSUE THREAD

**Issue by Humphreybas** [alexrj/Slic3r#2059]
1.1.3 experimental
When the retract-length has the same value as the negative retract-restart-extra the retract is not triggered.
For example:
--retract-length 0.1 --retract-restart-extra -0.1 --retract-lift 3
The retract is never triggered (the filament is not retracted and there is no z lift)
Expected behaviour: it will retract the filament (and lift z) and at restart it will not undo the retraction of the filament.

This works as expected:
--retract-length 0.1 --retract-restart-extra -0.11 --retract-lift 3

**Comment by alexrj** [comment]
This was fixed some time ago, and covered by a regression test. Thank you for reporting it.
