### ISSUE TITLE
[feature request] variable zoning infill 

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#2062]
to form 'shell' inside object, infill density could be distributed in a gradient fashion (less dense inside, more dense close to the perimeter) 

this can allow saving plastic while providing very strong parts. 

example algo to implement this could be mere 'minesweep' style zoning - dividing sliced perimeter layer into rectangle (or other shape) zones, and determining if edge of zone crosses perimeter. if yes, increase infill density 'ratio' in the zone. 

if layer above the processed layer is also included in the algo, then it also solves problem of supporting bridges and other structures by sparse infill.

**Comment by lordofhyphens** [comment]
Better thread is at #3333 currently. Closing, please use that for discussion.
