### ISSUE TITLE
First infil layer incorrect when combining infill layers

### ISSUE THREAD

**Issue by alvinavr** [alexrj/Slic3r#2063]
When combining 2 infill layers the very first infill layer is incorrect. This was seen with honeycomb infill. As can be seen the first infill patter is at a too large pitch.
This is with slic3r 1.1.4 dev downloaded on May 27.

The first generated infill layer, layer 2, below.
![gcodeviewer-2](https://cloud.githubusercontent.com/assets/7116792/3108140/3effd042-e68d-11e3-8744-64ce2c69dd98.png)
The next infill layer, layer 4, below.
![gcodeviewer-3](https://cloud.githubusercontent.com/assets/7116792/3108149/57b7b2b2-e68d-11e3-8041-acca0ffa6262.png)
The config file.
# generated by Slic3r 1.1.4-dev on Wed May 28 19:21:56 2014
avoid_crossing_perimeters = 1
bed_size = 140,140
bed_temperature = 70
bottom_solid_layers = 4
bridge_acceleration = 0
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 30
brim_width = 0
complete_objects = 0
cooling = 1
default_acceleration = 0
disable_fan_first_layers = 2
dont_support_bridges = 1
duplicate_distance = 6
end_gcode = M104 S0 ; turn off extruder temperature\nM140 S0 ; turn off bed\nG1 X10  ; park X axis\nG1 Y120 ; move to front\nM84     ; disable motors
external_perimeter_speed = 15
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 0x0
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
fan_always_on = 0
fan_below_layer_time = 30
filament_diameter = 1.75
fill_angle = 45
fill_density = 25%
fill_pattern = honeycomb
first_layer_acceleration = 0
first_layer_bed_temperature = 70
first_layer_extrusion_width = 0
first_layer_height = 0.3
first_layer_speed = 30%
first_layer_temperature = 170
g0 = 0
gap_fill_speed = 10
gcode_arcs = 0
gcode_comments = 1
gcode_flavor = reprap
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_speed = 20
interface_shells = 0
layer_gcode = 
layer_height = 0.3
max_fan_speed = 75
min_fan_speed = 25
min_print_speed = 10
min_skirt_length = 10
notes = 
nozzle_diameter = 0.63
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = [input_filename_base].gcode
overhangs = 1
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 20
perimeters = 3
post_process = 
print_center = 70,70
raft_layers = 0
resolution = 0
retract_before_travel = 1.8
retract_layer_change = 1
retract_length = 5
retract_length_toolchange = 10
retract_lift = 0.25
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 20
seam_position = random
skirt_distance = 6
skirt_height = 1
skirts = 3
slowdown_below_layer_time = 25
small_perimeter_speed = 10
solid_fill_pattern = rectilinear
solid_infill_below_area = 40
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0
solid_infill_speed = 20
spiral_vase = 0
standby_temperature_delta = -5
start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\nG1 Z[layer_height] F200
support_material = 0
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 75%
support_material_interface_extruder = 1
support_material_interface_layers = 3
support_material_interface_spacing = 0
support_material_interface_speed = 100%
support_material_pattern = honeycomb
support_material_spacing = 2.5
support_material_speed = 20
support_material_threshold = 0
temperature = 165
thin_walls = 1
threads = 3
toolchange_gcode = 
top_infill_extrusion_width = 0
top_solid_infill_speed = 15
top_solid_layers = 4
travel_speed = 130
use_firmware_retraction = 0
use_relative_e_distances = 0
vibration_limit = 0
wipe = 1
z_offset = 0

**Comment by lordofhyphens** [comment]
@alvinavr Could you reopen/update this with a screenshot from Slic3r's own 3d preview?

It should be possible to drag/drop ZIP files.
