### ISSUE TITLE
[feature request] Setting for layers between object and support material

### ISSUE THREAD

**Issue by mbjoker** [alexrj/Slic3r#2069]
Since version 1.0.0 some extra layers are added between the interface layers and the object. Using layer height = 0.2, after the 3 interface layers I can see a layer with a very sparse infill in the support area and then a layer with no support material at all, before the layer with the overhang is printed.
This makes for a support that can be very easily peeled off, but unfortunately such Z gap causes sagging and other problems. The same issue was reported here: http://forums.reprap.org/read.php?263,359302
It would be important to add settings also for these separator layers, like their infill pattern and number of layers.

**Comment by alexrj** [comment]
I added an option for vertical distance between object and support. It will be available in the upcoming 1.2.6.
