### ISSUE TITLE
Tiny holes on the sliced model

### ISSUE THREAD

**Issue by snavarrod** [alexrj/Slic3r#2081]
Hi
 I´ve been doing a small cap for a project and I every time that I send the model to slice I get this imperfections. Is just details but I dont know what could I do for solving it. I´m working on slic3r for macos version 1.1.2.  I will be sending you the original file plus the config file.

# generated by Slic3r 1.1.2 on Mon Jun  9 09:46:45 2014
avoid_crossing_perimeters = 0
bed_size = 152.4,152.4
bed_temperature = 0
bottom_solid_layers = 3
bridge_acceleration = 0
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 40
brim_width = 0
complete_objects = 0
cooling = 1
default_acceleration = 0
disable_fan_first_layers = 1
dont_support_bridges = 1
duplicate_distance = 6
end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\ng28 y0  ; home y axis\nM84     ; disable motors
external_perimeter_speed = 40%
external_perimeters_first = 0
extra_perimeters = 0
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 0x0
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
fan_always_on = 0
fan_below_layer_time = 60
filament_diameter = 1.75
fill_angle = 45
fill_density = 20%
fill_pattern = honeycomb
first_layer_acceleration = 0
first_layer_bed_temperature = 0
first_layer_extrusion_width = 200%
first_layer_height = 0.3
first_layer_speed = 75%
first_layer_temperature = 200
g0 = 0
gap_fill_speed = 30
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_speed = 60
interface_shells = 0
layer_gcode = 
layer_height = 0.35
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 10
min_skirt_length = 0
notes = 
nozzle_diameter = 0.4
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = [input_filename_base].gcode
overhangs = 1
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 40
perimeters = 3
post_process = 
print_center = 76.2,76.2
raft_layers = 0
randomize_start = 0
resolution = 0
retract_before_travel = 2
retract_layer_change = 1
retract_length = 1
retract_length_toolchange = 0
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 30
skirt_distance = 10
skirt_height = 1
skirts = 4
slowdown_below_layer_time = 20
small_perimeter_speed = 60
solid_fill_pattern = rectilinear
solid_infill_below_area = 70
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0
solid_infill_speed = 60
spiral_vase = 0
standby_temperature_delta = -5
start_gcode = G28 X0 Y0  \nG29\nG1 Z15.0 F
start_perimeters_at_concave_points = 0
start_perimeters_at_non_overhang = 0
support_material = 1
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_extruder = 1
support_material_interface_layers = 3
support_material_interface_spacing = 0
support_material_pattern = honeycomb
support_material_spacing = 2.5
support_material_speed = 40
support_material_threshold = 0
temperature = 200
thin_walls = 1
threads = 2
toolchange_gcode = 
top_infill_extrusion_width = 0
top_solid_infill_speed = 50
top_solid_layers = 3
travel_speed = 70
use_firmware_retraction = 0
use_relative_e_distances = 0
vibration_limit = 0
wipe = 0
z_offset = 0

![captura de pantalla 2014-06-09 a la s 9 52 42](https://cloud.githubusercontent.com/assets/7838679/3217224/7b4c4e1e-efdd-11e3-8664-5e051bc1b6da.png)

greetings

sebastian

**Comment by alexrj** [comment]
@alvinavr, this is what it looks like on 1.2.8-dev with the gap fill logic at corners:

![schermata 2015-06-02 alle 23 04 32](https://cloud.githubusercontent.com/assets/594957/7947183/ce368eba-097b-11e5-8479-c97d555589fa.png)

I think we can close this as it now looks beautiful ;)
