### ISSUE TITLE
Slic3r takes a long time to generate support material

### ISSUE THREAD

**Issue by TTN-** [alexrj/Slic3r#2083]
Slic3r took 2minutes and 18 seconds to export this model at 100% scale as gcode: http://www.thingiverse.com/thing:350694/#files

When scaled to 160% it took 8 minutes and 1 second to export as gcode.

Next supports were enabled and the model was scaled to 160% and exported as gcode. Slic3r was busy for 5 hours, until I killed the process. The computer was not used for any other tasks during this time period

All settings were identical in all tests except where stated.

Not too sure whether this should be considered a bug/issue, but 5 hours to slice a model is rather long. What is your take on this Alex? 

Details:
Slic3r version: 1.2.0 dev (pulled and compiled a 7 hours ago)
OS: ubuntu 14.04, 64bit
Perl: from ubuntu repository, version 5.18.2-2ubuntu1

Slicer config.ini:

# generated by Slic3r 1.2.0-dev on Tue Jun 10 14:43:05 2014
avoid_crossing_perimeters = 1
bed_size = 185,190
bed_temperature = 0
bottom_solid_layers = 3
bridge_acceleration = 100
bridge_fan_speed = 100
bridge_flow_ratio = 0.85
bridge_speed = 28
brim_width = 0
complete_objects = 0
cooling = 1
default_acceleration = 400
disable_fan_first_layers = 1
dont_support_bridges = 1
duplicate_distance = 6
end_gcode = M104 S0 ; turn off extruder\nG28 X0  ; home X axis\nG1 Y100 ; move bed forward, easy object removal\nM84  ; disable motors
external_perimeter_extrusion_width = 0
external_perimeter_speed = 50
external_perimeters_first = 1
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 0x0
extrusion_axis = E
extrusion_multiplier = 0.98
extrusion_width = 0
fan_always_on = 0
fan_below_layer_time = 60
filament_diameter = 2.86
fill_angle = 45
fill_density = 25%
fill_pattern = honeycomb
first_layer_acceleration = 2000
first_layer_bed_temperature = 0
first_layer_extrusion_width = 200%
first_layer_height = 0.35
first_layer_speed = 50%
first_layer_temperature = 198
g0 = 0
gap_fill_speed = 20
gcode_arcs = 0
gcode_comments = 1
gcode_flavor = reprap
infill_acceleration = 2000
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_speed = 80
interface_shells = 0
layer_gcode = 
layer_height = 0.1
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 15
min_skirt_length = 4
notes = Someone said bridging flow ratio of .6 helped so we'll have to test that.\nsomeone else said 0.85 is good. Auzze on irc recomended 28mm/sec bridging speed. Genius, works really well. 30mm/sec does not (using .85 flow ratio for all bridging).
nozzle_diameter = 0.5
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = [input_filename_base].gcode
overhangs = 1
perimeter_acceleration = 400
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 60
perimeters = 2
post_process = 
print_center = 100,90
raft_layers = 0
resolution = 0
retract_before_travel = 2
retract_layer_change = 1
retract_length = 6
retract_length_toolchange = 10
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 40
seam_position = aligned
skirt_distance = 4
skirt_height = 1
skirts = 4
slowdown_below_layer_time = 30
small_perimeter_speed = 20
solid_fill_pattern = rectilinear
solid_infill_below_area = 70
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0
solid_infill_speed = 60
spiral_vase = 0
standby_temperature_delta = -5
start_gcode = G28 Y; do y first so that when x homes next it doesnt ram the cube for the probe\nG28 X Z; home x and z next\nG29; level bed\nG1 Z35 F5000\nG1 X195 Y20 F5000\nG1 Z14.5 F5000\nG1 Z35 F5000\nG1 X150 F5000\nG1 Z0.5  F5000; almost touch nozzle to bed to stop oozing\nM109 S[first_layer_temperature]   ;set temperature and don't move till temperature is reached
support_material = 0
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_extruder = 1
support_material_interface_layers = 3
support_material_interface_spacing = 0
support_material_interface_speed = 100%
support_material_pattern = honeycomb
support_material_spacing = 2.5
support_material_speed = 60
support_material_threshold = 80
temperature = 194
thin_walls = 1
threads = 4
toolchange_gcode = 
top_infill_extrusion_width = 0
top_solid_infill_speed = 60%
top_solid_layers = 3
travel_speed = 120
use_firmware_retraction = 0
use_relative_e_distances = 0
vibration_limit = 0
wipe = 1
z_offset = 1.8

**Comment by lordofhyphens** [comment]
It is probably avoid crossing perimeters, although could you check with 1.3.0-dev? There is a more efficient gcode export. See the main page for a windows dev build if you use windows and can't do a build of slic3r yourself.

**Comment by migero** [comment]
replay to 1y old topic

**Comment by lordofhyphens** [comment]
@TTN- "Avoid Crossing Perimeters" is a known gcode generation bottleneck (and it represents a computationally hard problem to solve), but the new efficient gcode generation routine may help. I'm going to close this for now, let me know if there's still problems. Otherwise, leave the feature off and use z lift for retraction instead. 

@migero it's not necromancy if the thread isn't dead (closed) :)

**Comment by TTN-** [comment]
Yup :)

Ok cool, thanks LoH.
