### ISSUE TITLE
One line is drawn wrongly in Slic3r 1.1.4 in the first top infill layer of a 20x20x10 cube

### ISSUE THREAD

**Issue by hyperair** [alexrj/Slic3r#2087]
![screenshot1](https://cloud.githubusercontent.com/assets/88355/3248622/723d95da-f190-11e3-9d5d-ecb2645aec06.png)

Full G-code is here: https://gist.github.com/hyperair/177b5d84eabf0f39e352

**Comment by alexrj** [comment]
Can't reproduce this one on 1.2.6-dev, luckily

**Comment by hyperair** [comment]
Yeah I haven't seen this bug recently. Thanks.
