### ISSUE TITLE
Heated bed not enabled when extruder 1 is disabled

### ISSUE THREAD

**Issue by ghost** [alexrj/Slic3r#2089]
On multiple extruder machines if extruder 1 is disabled and extruder 2 is used to print the heated bed is not enabled. I have created a workaround where I have the bed temp set in a profile that is used for extruder 1 but extruder temps set to 0. It would be nice to not have to create these "cheater" profiles.

**Comment by alexrj** [comment]
@jrn-aa, I'm not sure I can reproduce this. Could you please give me more details about the steps for reproducing it? Also, does it still happen on 1.2.6? Thank you

**Comment by alexrj** [comment]
User deleted their profile from GitHub + bug is unreproducible + report is incomplete = closing this one
