### ISSUE TITLE
Strange extra perimeter generated at top interface layer

### ISSUE THREAD

**Issue by vitalif** [alexrj/Slic3r#2093]
I'm using Slic3r from master branch (@97231327e0da0de81186763e03b6eab02594f662), and it generates something strange under the upper edge of my wheel rim model if interface layers are enabled (z position 11.9):
![rim_small_bug](https://cloud.githubusercontent.com/assets/945339/3273460/80105a54-f324-11e3-9625-8ba51f713669.png)
What is the extra perimeter intersecting with the rim perimeter? When I disable interface layers, it's not there.
It's caused by "elsif (@$contact && $contact_loops > 0) { ... }" in Slic3r::Print::SupportMaterial::generate_toolpaths (line 551). What's the idea of that piece of code, why not just generate it like other layers?
I patched it in my repository for myself, but is it really a bug or not?
The whole model looks like: 
![rim_small_bug1](https://cloud.githubusercontent.com/assets/945339/3273513/62af66fc-f325-11e3-9550-c69d6ac877d2.png)
Model file, resulting gcode and config: http://vmx.yourcmc.ru/var/tmp/rim_small_bug.tar.gz

**Comment by lordofhyphens** [comment]
![image](https://cloud.githubusercontent.com/assets/31754/16662205/f023f462-443b-11e6-8ea4-d404b8812dfc.png)
This is with 1.3.0-dev; I can't see the perimeter you're talking about.

The red lines are infill, that's slic3r unable to work out what the infill width actually should be on a layer.
Setting the infill width manually leads to:
![image](https://cloud.githubusercontent.com/assets/31754/16662272/45945360-443c-11e6-8f8b-34c0c9d8b352.png)

Please retest with 1.2.9 or 1.3.0-dev and reopen if there's still a problem.
