### ISSUE TITLE
SIMPLE feature request :-) -- disable fan for perimeters ONLY

### ISSUE THREAD

**Issue by nothinman** [alexrj/Slic3r#2095]
Hi,

When printing in PLA enabling fan add more details to the print, also the plastic no longer looks glossy, which I personally like.
But if I leave it on for both perimeters and infill, the object is substantially weaker.
I cannot break objects by hand if I print them without fan, but they will always delaminate if the fan is on.

An option would be to use the fan only on the outside, but keep it on for infill.
I've tried it by manually editing gcode in sublime text, and it seems to be working as expected.

Any chance you could add this option @alexrj?

Thanks for all your hard work so far!
Marcin

**Comment by lordofhyphens** [comment]
Seeing as @nothinman didn't have anything more to add to his request and @alexrj disagrees (and I don't think it's a good idea either), going to close this for now. Please reopen if @nothinman has new information (and a reproducible test case).
