### ISSUE TITLE
Slic3r crashes when opening Object Settings dialog 2nd time

### ISSUE THREAD

**Issue by vitalif** [alexrj/Slic3r#2099]
Hi, I'm still talking about master branch of Slic3r... the bug reproduces at least since 1.1.2-dev.
The bug is very simple - when I'm trying to open Object Settings dialog 2nd time, Slic3r crashes with BadDrawable X11 error.
I've fixed it like this: vitalif/Slic3r@e73d76e7711e136b7e4e8a345cb66867fe94ddfc (so canvas is not repainted while creating window)
Don't know if it's the best way to fix issue, but it definitely needs a fix :)

**Comment by alexrj** [comment]
Can be closed now.
