### ISSUE TITLE
Small typo in 1.1.4 release docs and problem with those changes

### ISSUE THREAD

**Issue by Jnesselr** [alexrj/Slic3r#2110]
Hey, just reading the released docs for 1.1.4 here: http://slic3r.org/releases/1.1.4

Under Changes: "The command line --save option will not only save the options that were explicitely specified on command line, without the implicit defaults"

I'm almost certain that "not" should be "now".

Also, I use --save with no arguments to get the default configuration shipped with the slic3r, which frankly is just awful behavior. What was the reasons for doing this. I really need to be able to export the default config, not the config that I've set up for my profile, and this was the easiest way to do it.

**Comment by alexrj** [comment]
Probably a bit late :-) but I pushed a commit that saves the full default settings when `--save` is not combined with any other config settings.
