### ISSUE TITLE
Command line vs interactive

### ISSUE THREAD

**Issue by sicht** [alexrj/Slic3r#2113]
There are differences in the generated gcode files between the windows 1.14 interactive and the linux command line generated files using version 1.2 compiled from GitHub. I am using the config.ini file exported from slic3r in the command line. There are also small holes in the Windows 1.14 generated code and much larger ones generated from the linux command line both at 100% infill. I can supply all the files.

**Comment by alexrj** [comment]
This is fixed as of recent versions. @sicht, thank you for reporting.
