### ISSUE TITLE
Overlap of objects' programmed rafts will extrude twice in overlap area

### ISSUE THREAD

**Issue by 3daybreaker** [alexrj/Slic3r#2116]
I am not sure whether this is intended, but when I ad 2 objects to the build plate that each have a one layer programmed raft and those rafts overlap, Slic3r will extrude twice on the overlap area. I use this to prevent multiple small and high objects to fall over and have them to stick to the raft all together and therefore keep their position as the combined raft is so big, it will not displace.

Is Slic3r not aware of the overlap ? Should it not just see the one layer overlap as one layer ?
Can that become a feature ?
Thomas

**Comment by lordofhyphens** [comment]
Why do you need to intentionally overextrude on brims?
