### ISSUE TITLE
Multiextruder printing should use "extra length on restart" also on first use of second extruder, if previously heated in custom priming gcode

### ISSUE THREAD

**Issue by simonkuehling** [alexrj/Slic3r#2118]
Hi,

for all prints, we generally do a priming sequence for the extruders in a custom start gcode and use the slic3r's ooze prevention feature to handle toolchanges.
This works like a charm throughout the print, using something like 1.3mm "extra length on restart" after changing extruders to compensate ooze during cooldown after last use.

Upon first use of the second extruder, the "extra length on restart" is not added, though - most likely because slic3r did not recognize that it was in fact already used in the start gcode sequence. This way the first few centimeters of extrusion on the second extruder will reliably fail until nozzle pressure is back.

My suggestion is to check for each extruder if it was previously already heated by M104 or M109 and to also add the extra extrusion length to the first toolchange with this extruder, if that's the case.

Simon

**Comment by lordofhyphens** [comment]
Is the generic toolchange gcode sufficient to handle this?

**Comment by simonkuehling** [comment]
Oh, this is like a message from the past :-)

Yes, from our side the generic toolchange gcode did fix this problem, since we do a dedicated "prime and wipe nozzle" operation upon each toolchange and do not use slic3r's ooze prevention anymore.

I'll close this issue then, please reopen if anyone disagrees.
Thanks for tidying up these old issues!

**Comment by lordofhyphens** [comment]
My pleasure; I dream of a day where we have < 20 unsorted open issues.
