### ISSUE TITLE
Not able to enforce support for initial layers

### ISSUE THREAD

**Issue by Humangutan** [alexrj/Slic3r#2121]
I am trying to use the "Enforce support for the first:" command in Slic3r and I do not get any support generated. If I enable support for the print, I get support throughout the print, including in the first 30 layers. If I do not enable support, but try to use the "Enforce support" command, I get no support all all, not even in the first 30 layers as I set it.

Here is a picture of my model. It is a multi-material print, with two sets of spheres and a wireframe that connects them. It is a unit cell of the crystal lattice of halite (NaCl, also known as table salt). 

![halite_3dmodel](https://cloud.githubusercontent.com/assets/7991509/3394235/84811d52-fcda-11e3-9d0e-3d7e12510272.JPG)

As you can see in the image, the smaller white spheres do not touch the base. I just need enough support to put something under the first layer of the white spheres. I would love to provide the .amf file to you, but I see no way to attach that to this issue report. Only image files are allowed. Could I email the .amf file to you?

I get this same issue with the latest stable version of Slic3r (1.0.1) as well as the latest experimental version (1.1.4), which I have separately installed on identical computers running Windows XP. 

I have read your instructions for providing a good issue report here:

https://github.com/alexrj/Slic3r/blob/master/CONTRIBUTING.md

But I don't know how to provide you with my config.ini file because this issue reporting format will only let me attach image files.

When I use the Cura software to generate gcode, I enable support and it only provides support for the initial layers beneath the first layer of smaller spheres, but I want to generate it from Slic3r because the toolpaths I get from Slic3r are generally better.

Can you advise how I could send you the .amf and config.ini files, and how I might resolve this problem?

**Comment by lordofhyphens** [comment]
Nobody ever replied :( You can attach zip files now as far as I know now, so please zip it up and attach.

@Humangutan if you're still having problems with 1.3.0-dev (https://bintray.com/lordofhyphens/Slic3r/slic3r_dev/view) or 1.2.9 please reopen.
