### ISSUE TITLE
Wrong Support material

### ISSUE THREAD

**Issue by Balles-** [alexrj/Slic3r#2134]
Starting from Slic3r Version 1.0.0.RC1 I found wrong Support material.

The model is a cube with a tapered bore at the side.
To print the walls of this bore support material Is needed to print the top wall of it.

In version 0.9.10b support Is generated in the bore from the bottom wall to the top wall.

In version 1.0.0.RC1 until version 1.1.5 support material is also generated outside the bore and outside the cube.
For this material Is no need and there Is nothing to support outside of the cube.

The test model looks like this.
![wp_20140628_001](https://cloud.githubusercontent.com/assets/8025402/3428532/e2bd37ec-0041-11e4-99b3-bc4a4f0e5ccf.jpg)

The result of Slic3r as follows

![extra_support](https://cloud.githubusercontent.com/assets/8025402/3428535/edb3d174-0041-11e4-9457-f65614f3da7b.jpg)

What setting is causing the generation of this support material.

**Comment by lordofhyphens** [comment]
@Balles- Browse to https://github.com/alexrj/Slic3r/issues/2134 (remember to log in)
Zip up the STL file along with a screenshot of the 3d preview from slic3r and an exported config.ini file and drag/drop it there (or upload it somewhere else and provide a link here).

Github doesn't take kindly to email attachments.

**Comment by lordofhyphens** [comment]
And click "reopen and comment" when you do so.
