### ISSUE TITLE
Feature Request: If faces in a solid are reversed, invert them to be correct

### ISSUE THREAD

**Issue by efbrazil** [alexrj/Slic3r#2140]
This feature request springs from bug report 2129.

The issue is that many programs can produce stl files that have faces partly or completely inverted. For instance, sketchup has a bug where it inverts faces on models when exporting negatively scaled solids. It's also hard in sketchup to audit a file for inverted faces, since sketchup reports a group or component as being a solid even if faces are inverted.

When slic3r encounters a model with inverted faces, it always fails. Makerware is somewhat better, as it handles the scenario where all faces on a solid are backwards, but it also fails to handle the scenario where some faces on a model are backward.

I am creating this as a feature request as Alexj suggested. In particular, he said "sketchup is not the only program that can produce STLs that are broken in this way, and it seems like a relatively easy error to detect and repair (compared to things like open meshes and self-intersections)."

Is what I would recommend is first doing the work to be as good as makerware by fixing the scenario where all faces in a solid are wrong. For extra credit, it would be good to fix the scenario where only some faces in a solid are wrong.

For reference STL content and background, see bug report 2129

**Comment by alexrj** [comment]
I'm closing this one since Slic3r has been able to repair models with inverted faces for a while. :)
