### ISSUE TITLE
Missing support materials under big bridges in 1.1.5 causes bad borders

### ISSUE THREAD

**Issue by NinjaCross** [alexrj/Slic3r#2147]
I'm experiencing a problem with missing support materials.
Here you can see the model

![model](https://cloud.githubusercontent.com/assets/5829421/3456613/a862500e-01f0-11e4-9462-8a9451d4c6d7.PNG)

Here there is the sliced model

![sliced](https://cloud.githubusercontent.com/assets/5829421/3456678/53fe8d6a-01f1-11e4-97a3-09af707525ff.PNG)

Here you can see the bridge (34mm) that Slic3r is trying to generate without any support material.

![bridge](https://cloud.githubusercontent.com/assets/5829421/3456728/a321414e-01f1-11e4-9409-1e172f474698.PNG)

As you can see, there's nothing supporting the highlighted part.
The print does not fail since the bridge is generated, but the border of that bridge is very rough and fragile, and compromises the functionality of the final object.
I obviously tried to use different speed and temperature settings, but no one seems to reach the needed precision.

It would be very usefull a setting to constraint the max length of the bridges, or better, a setting that allows to force the generation of support materials under the bridges.

Here are the files to reproduce/analyze the issue:
http://www.ninjacross.com/public/Temp/Guscio_laterale_SX.stl
http://www.ninjacross.com/public/Temp/Guscio_laterale_SX.gcode
http://www.ninjacross.com/public/Temp/Slic3r_config_bundle_DUPLICATOR4.ini

**Comment by ioquatix** [comment]
Any progress on configurable max bridge length?
