### ISSUE TITLE
1.1.5 and 1.1.6 fail to start in Mac OSX 10.9.4

### ISSUE THREAD

**Issue by MotoBarsteward** [alexrj/Slic3r#2151]
First thing to point out is that I've not tried this in a while. I'm not sure what version I had before but that one doesn't run any more, either. I have a full crash log but can't attach it so I've pasted an excerpt here. Any idea why it's failing? I think its more to do with a newer version of OSX rather than a problem with Slic3r as I can't get my old version to work.
kernel messages:
-0 sec           	CODE SIGNING: cs_invalid_page(0x10eb3e000): p=1171[CoreServicesUIAg] final status 0x1000a00, denying page sending SIGKILL
-0 sec           	CODE SIGNING: process 1171[CoreServicesUIAg]: rejecting invalid page at address 0x10eb3e000 from offset 0x4d000 in file "/Applications/Slic3r.app/Contents/MacOS/slic3r" (cs_mtime:1403714854.0 == mtime:1403714854.0) (signed:1 validated:1 tainted:1 wpmapped:0 slid:0)

The Slic3r icon bounces for a minute and Slic3r appears in the running task list but no window appears.

**Comment by lordofhyphens** [comment]
Closing, please reopen if 1.2.9 doesn't work.
