### ISSUE TITLE
Unnecessary tool change on new layers

### ISSUE THREAD

**Issue by PatONeil** [alexrj/Slic3r#2174]
The brim,skirt, and loops are all done on a single extruder.   I want to be able to do these things with the current extruder to avoid changing tools unnecessarily.

Is there a way to have slic3r not change extruders on layers without writing a post processing script?

**Comment by lordofhyphens** [comment]
Please see contributing guidelines and reopen and update your post.

Slic3r should use the skirt to prime if you have it set for enough layers. Otherwise, there's an option in the Advanced print settings to set the extruder for different things.
