### ISSUE TITLE
Support top layer too far away - no way to configure it via gui (& cmd line?)

### ISSUE THREAD

**Issue by antfurn** [alexrj/Slic3r#2181]
Slic3r v1.1.6 on Windows (GUI)

Hi, I've just upgraded my lulzbot AO-101 to dual hotends with the primary focus being able to print with dissolvable support material.

However, I'm having issues with the first layers, which are part of the object, above where the support material should be supporting.
There seems to be just too big a gap between the top of the support and what it should be supporting. See the object I'm testing with below, there is 0.75mm gap when I'm using 0.25 layers.
I can't find anyway to adjust this air gap setting between the top of the support material and the supported layers, well via the Windows GUI at least. 

![shelf_slot_hook_test_failed_support](https://cloud.githubusercontent.com/assets/4171512/3714157/ff718ba2-1597-11e4-97b7-d53b45887acf.png)
![shelf_slot_hook_test_failed_support2](https://cloud.githubusercontent.com/assets/4171512/3714158/ff738c4a-1597-11e4-9fb7-8be533ad0bdb.png)

Thanks for the great Slic3r program, hope you can help.
Antony

**Comment by ihbar** [comment]
Hello I have similar issue with 1.1.7 : 
- With solvable support material (PVA) and PLA as material, the PLA does not stick to the PVA and warp or move away during printing.
- With ABS object and ABS support, if base surface is small, the adhesion between raft and object is not sufficient and object it going away before end of printing. 
Would it be possible to have an option to deactivate or adjust this gap ?
Thanks.

**Comment by markwal** [comment]
@ihbar It looks to me like there is a new feature coming in the next release where you can specify the support contact distance in the Z dimension.  If you're up for it, you could try it out by running from source.

**Comment by lordofhyphens** [comment]
It should be in 1.2.6, which has builds.

**Comment by ihbar** [comment]
Great !
I tried the 1.2.6 and it seems to work fine. My first test : PVA + PLA.  The PLA is sticking on the PVA, I am able to build PLA over the support, While before, it was not sticking due to the gap.  :-)

The option seems good.  I will do more tests, but it seems to be exactly what I was looking for.
Thanks a lot.

**Comment by lordofhyphens** [comment]
Closing.
