### ISSUE TITLE
feature request: bedlevel dimensions

### ISSUE THREAD

**Issue by bonm014** [alexrj/Slic3r#2182]
I have a large (heat)bed which I do not want to probe everytime all the way. (Slow movement)
I would like the parameters of the dimensions of the objects to be printed. I can add that to my g29 code to probe only that region.
XY start and XY end.

Sounds not that hard ;-)

Thanks

**Comment by lordofhyphens** [comment]
definitely a task for a post-processing script... or switch your electronics to Smoothieware, which can save the probe results.

**Comment by mrvn** [comment]
As a side note: You probably only need to probe the area where the first layer extrudes something.
