### ISSUE TITLE
Compiling Slic3r on Windows

### ISSUE THREAD

**Issue by samverstocken** [alexrj/Slic3r#2186]
Dear all,

We at Ghent University (Belgium) are working on developing polymers (in the form of a gel) that we seek to print with a 3D printer. The printed gellish forms are then bathed in human cells in order to be able to create human organs, cartilage and ligaments. We have chosen Slic3r for generating the GCode and MatterControl for operating the 3D printer. I have been assigned the task of creating a modified version of both programs that is specifically adapted to our application with gels. However, I have not much experience with programming in Perl and 3D printing software. We are using Windows for operating the printer and thus also for programming, compiling and running the modified Slic3r versions.

I have followed the steps on the Slic3r github and I have succesfully built the software from source. I am able to run Slic3r by using the "perl Slic3r.PL" command. However, I actually need the Slic3r source code to compile into an executable file, such as you would get when you download the Windows version of Slic3r. This is important since then I can copy these executables into the MatterControl folder. I don't find anything about compiling Slic3r into executables. Am I missing something? 

Any suggestion regarding this would be of immense help.

Looking forward to a response,

Sam Verstocken
Faculty of Sciences
Ghent University

**Comment by gege2b** [comment]
Hi,

You can follow instructions here on how to setup CitrusPerl to run slic3r from source https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-Windows

And then follow this http://www.citrusperl.com/helpweb/createexecutable.htm
to make an exe out of source.

I have not tested yet
