### ISSUE TITLE
build from git impossible if --gui enabled

### ISSUE THREAD

**Issue by Chr0nos** [alexrj/Slic3r#2189]
hi,
i get Slic3r sources from git on my gentoo,  but i cant compile it if --gui argument is set, if i dont: that compile fine but i need tue gui

that what i got:
StarK Slic3r # perl Build.PL --gui
App::cpanminus is up to date. (1.7004)
Growl::GNTP is up to date. (0.20)
OpenGL is up to date. (0.6703)
Wx is up to date. (0.9923)
Wx::GLCanvas is up to date. (0.09)

then the script exit with no error
arch is: amd64

**Comment by lordofhyphens** [comment]
No update since more info was asked for. See wiki and reopen issue if you are still having problems with 1.2.9 or 1.3.0-dev.
