### ISSUE TITLE
[Bug Report] Floating Pillars Support

### ISSUE THREAD

**Issue by zezons** [alexrj/Slic3r#2199]
The slic3r is generating floating pillars supports.
In practice, when this was printed, some filaments drops and the support fail.

Slic3r: 1.2.0 (but the same problem occurs in the previous and stable versions).
[CupSupport.stl | uploaded via ZenHub](https://www.zenhub.io/files/53e1222583e101843a000b49)
[CupSupport.gcode | uploaded via ZenHub](https://www.zenhub.io/files/53e1228483e101843a000b4b)
[Slic3r-config.ini | uploaded via ZenHub](https://www.zenhub.io/files/53e1229683e101843a000b4c)

This is happening In curved and draft faces like the following images.

![image_01](https://cloud.githubusercontent.com/assets/8364310/3816424/66dae3c8-1cce-11e4-9a92-5b2331ee271a.jpg)
![image_02](https://cloud.githubusercontent.com/assets/8364310/3816425/66dba2ea-1cce-11e4-9a0c-1f3cfe4a69e4.jpg)
![image_03](https://cloud.githubusercontent.com/assets/8364310/3816426/66deafc6-1cce-11e4-8e80-e627ca8e94ac.jpg)

**Comment by lordofhyphens** [comment]
Is this in the model? Is slic3r's generated support on? Is the area too small to produce correct perimeters?
Unfortunately the host you used for the model and config is defunct.

Please reopen and upload new versions of everything if you still have a problem with 1.2.9 or 1.3.0-dev, and include screenshots from Slic3r's 3d preview. You *should* be able to attach zip files in Github directly.
