### ISSUE TITLE
[Feature Request] Contact support on edges corners

### ISSUE THREAD

**Issue by zezons** [alexrj/Slic3r#2200]
I suggest add an option to add or not a contact point between support and object.
When generating any kind of support, I suggest that Slic3r create an small contact point with the object to avoid warping on corners.

The images bellow, show the support contact pillar (blue lines) between support interface layer and the object (black lines).

![image_01](https://cloud.githubusercontent.com/assets/8364310/3817023/d8da125a-1cd3-11e4-82f0-62a4f2ebc972.jpg)
![image_02](https://cloud.githubusercontent.com/assets/8364310/3817022/d8d9f248-1cd3-11e4-868a-f377737fdbef.jpg)

**Comment by lordofhyphens** [comment]
Closing, as the requested information was never provided and even I can't figure out what is meant here. @zezons reopen if you can help with this.

**Comment by bubnikv** [comment]
Long overhangs will lift up. With ABS this lifting of overhangs is deadly to the print quality. It makes sense to fuse the overhangs to a support as having to cut the anchors is better than to have a warped and distorted bottom surface. This again goes to the examples in https://github.com/prusa3d/Slic3r/issues/102
