### ISSUE TITLE
firmware retract issues G92 E0 between G10/11

### ISSUE THREAD

**Issue by wolfmanjm** [alexrj/Slic3r#2201]
When firmware retract is set the gcode generated is...

G10 ; retract
G92 E0
G11 ; unretract

This seems to be incorrect as it resets the E position before the unretract. I believe the G92 E0 should go after the G11.

It currently has no effect in Smoothie for various obscure reasons, and WW added  a hack to Marlin to work around it. So it currently works, but would be nice if it were corrected for future happiness :)

**Comment by wolfmanjm** [comment]
this seems to have regressed in 1.2.5-dev

G10 ; retract
G92 E0
G1 X-14.210 Y14.193 F18000.000
G11 ; unretract
G92 E0

**Comment by alexrj** [comment]
@wolfmanjm, what's wrong with that snippet? I see `G92 E0` after both `G10` and `G11` and that looks correct

**Comment by wolfmanjm** [comment]
I thought you said "...Removing it after G10 was not necessary, but I did it anyway to save bytes"

**Comment by alexrj** [comment]
It's good if it's after both… after all. ;)  Since E is undefined status for most firmwares after G10/11.
