### ISSUE TITLE
vibration limit ignored for short travel moves

### ISSUE THREAD

**Issue by makertum** [alexrj/Slic3r#2206]
Rapidly successing, short travel moves are carried out at travel speed, which is usually the fastest speed of motion in a printer. Those short pieces of rapid motion can cause strong resonance in a printer and therefore step loss even at moderate speeds where without resonance a step loss would not occur.

This could be resolved by
- reducing travel speed (slower printing)
- lowering the travel move accelleration (which currently can only be set indirectly via default acceleration)
- or by making the "vibration limit" option work when switching between print moves and travel moves, it currently seems to only detect vibrations within print moves and ignore them when rapidly switching between print and travel.

I suggest this, because rapidly successing, short travel moves, such as in the picture (generated with vibration limit = 1 Hz), which are mostly generated at the borders of interface layers, are causing massive trouble to me since they have been introduced to slic3r.

![bildschirmfoto 2014-08-08 um 13 25 34](https://cloud.githubusercontent.com/assets/5277180/3856071/88b92aae-1eef-11e4-8fcd-bd91c6220c5f.png)

Hope that helps making Slic3r even better!

**Comment by lordofhyphens** [comment]
Closing, as @makertum never responded and @alexrj doesn't indicate there is a problem to fix.

**Comment by makertum** [comment]
Hey there, sorry for that, that's been more than 2 years ago and I can't recall what it was.

**Comment by lordofhyphens** [comment]
No problem, just trying to clean up old issues that can be closed. If you
come across new information then the issue can be reopened.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.
