### ISSUE TITLE
Drop down menu auto-width

### ISSUE THREAD

**Issue by CupricReki** [alexrj/Slic3r#2208]
I have long descriptions for print profiles. The width of the drop down menu for selecting is to narrow to see all the details needed

![image](https://cloud.githubusercontent.com/assets/6509200/3862083/ddb6f90e-1f36-11e4-9705-aeb39793ec71.png)

**Comment by alexrj** [comment]
Yes, unfortunately that's what wxWidgets provides on Windows. On Windows I enlarged the entire popup menu so the contents are more visible.
