### ISSUE TITLE
Configure failed for OpenGL-0.6703

### ISSUE THREAD

**Issue by w821881341** [alexrj/Slic3r#2211]
I'm using ubuntu 14.04 64bit was a frash install.
followed the instructions on https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux.

installing by sudo perl Build.pl is Success,But when sudo perl Build.pl --gui,I got that:

App::cpanminus is up to date. (1.7004)
Growl::GNTP is up to date. (0.20)
--> Working on OpenGL
Fetching http://www.cpan.org/authors/id/C/CH/CHM/OpenGL-0.6703.tar.gz ... OK
Configuring OpenGL-0.6703 ... N/A
! Configure failed for OpenGL-0.6703. See /home/wei/.cpanm/work/1407688942.20108/build.log for details.
Don't worry, this module is optional.
--> Working on Wx
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Wx-0.9923.tar.gz ... OK
==> Found dependencies: Alien::wxWidgets
--> Working on Alien::wxWidgets
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Alien-wxWidgets-0.65.tar.gz ... OK
Configuring Alien-wxWidgets-0.65 ... OK
Building and testing Alien-wxWidgets-0.65 ... OK
Successfully installed Alien-wxWidgets-0.65
Configuring Wx-0.9923 ... OK
Building and testing Wx-0.9923 ... OK
Successfully installed Wx-0.9923
2 distributions installed
--> Working on Wx::GLCanvas
Fetching http://www.cpan.org/authors/id/M/MB/MBARBON/Wx-GLCanvas-0.09.tar.gz ... OK
Configuring Wx-GLCanvas-0.09 ... OK
Building and testing Wx-GLCanvas-0.09 ... OK
Successfully installed Wx-GLCanvas-0.09
1 distribution installed

the opengl module is installed failed although I tried many times by different means.

**Comment by lahure-c** [comment]
I had a similar error on Debian 8 RC1

>Fetching http://www.cpan.org/authors/id/C/CH/CHM/OpenGL-0.6704.tar.gz ... OK
>Configuring OpenGL-0.6704 ... N/A
>! Configure failed for OpenGL-0.6704. See /root/.cpanm/work/1426682544.4806/build.log for details.

It's because this installer is probing the display and it does not have access to it because it's root.
Root should have access to the display. See here:
https://wiki.archlinux.org/index.php/Running_X_apps_as_root

In my case I had to type, as a user: 
kdesudo "perl Build.PL --gui"

instead of:
su perl Build.PL --gui

**Comment by gege2b** [comment]
I'm using "xhost +" before and "xhost -" after the su perl Build.PL --gui and it works fine too

**Comment by lordofhyphens** [comment]
Gege if you are using Debian you can build packages from my repo (debian
branch). I am using Jessie as well.

**Comment by lordofhyphens** [comment]
Sorry I mean lahure

**Comment by lahure-c** [comment]
Thank you  lordofhyphens 
I understand your version of Slic3r does not follow the same compilation procedure ...right ?

gege2b: your solution "xhost +" is probably better because more universal

**Comment by lordofhyphens** [comment]
No, but it is the same procedure used for the official debian packages.

**Comment by bj0** [comment]
On Ubuntu 14.10, I also had to install libghc-glut-dev and it's associated packages to get OpenGL.pm to compile correctly.

**Comment by lordofhyphens** [comment]
Just install the packages you need to make packages and use my fork, which
is upstream master, ready to package. Much cleaner than breaking your
system with cpanm.

https://github.com/lordofhyphens/Slic3r

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.
