### ISSUE TITLE
[bug] Slic3r cuts model in half during slicing resulting in a horizontal gap

### ISSUE THREAD

**Issue by beberle** [alexrj/Slic3r#2212]
Slic3r version: 1.1.7 x64 on Ubuntu 14.04 (also tested with 1.2.0)
Config file: [config.ini](https://benjamineberle.de/slic3rbug/config.ini)
STL file: [tuerschluessel.stl](https://benjamineberle.de/slic3rbug/tuerschluessel.stl)

When slicing the above stl, slic3r cuts the (solid) model right under the key bit, treating it as two separate objects, so the resulting gcode consists of a bottom cylinder (including top solid infill), a gap, and the remaining top part of the model (including bottom solid infill).

![Side view](https://benjamineberle.de/slic3rbug/bug_3d.png)

When enabling support slic3r generates support inside the model where it got cut (and also additional support around the cylinder) which should not be there.

![2d view](https://benjamineberle.de/slic3rbug/bug_support_2d.png)

Slicing the file with cura delivers the expected results:

![cura](https://benjamineberle.de/slic3rbug/cura_3d.png)

**Comment by alexrj** [comment]
This is fixed as of today. Thank you for reporting it.

![schermata 2015-06-02 alle 22 41 51](https://cloud.githubusercontent.com/assets/594957/7946730/9f5377a0-0978-11e5-8ee4-a6e18fa0903b.png)
