### ISSUE TITLE
Ver 1.1.7 Missing support structures

### ISSUE THREAD

**Issue by NinjaCross** [alexrj/Slic3r#2222]
I'm usingslic3r-mswin-x64-1-1-7-stable on Windows 7 x64 Pro
As you can see in the attached screenshots, support structures are completely missing on some overangings:
![screenshot 2014-08-15 08 28 08](https://cloud.githubusercontent.com/assets/5829421/3930516/b67f7c1c-2445-11e4-8b99-e7ed2d52aabf.png)
![screenshot 2014-08-15 08 27 52](https://cloud.githubusercontent.com/assets/5829421/3930517/b733262c-2445-11e4-9352-7afe21a2862f.png)
![screenshot 2014-08-15 08 28 01](https://cloud.githubusercontent.com/assets/5829421/3930519/b8a1298c-2445-11e4-9a4d-8fa4441bc333.png)
![screenshot 2014-08-15 08 18 43](https://cloud.githubusercontent.com/assets/5829421/3930521/bb1d4074-2445-11e4-853c-b85bde46d4ff.png)
![screenshot 2014-08-15 08 18 54](https://cloud.githubusercontent.com/assets/5829421/3930522/bcfaa1ac-2445-11e4-852f-0c008af8f403.png)
![screenshot 2014-08-15 08 19 17](https://cloud.githubusercontent.com/assets/5829421/3930523/bf9fcf68-2445-11e4-97d5-0b15ea42aaae.png)

Please see the STL files and configurations used:
http://www.dogmasolutions.com/public/Temp/Slic3r_Issue_2222.zip

I'm using these settings:
[printer:Duplicator 4 (singolo)]
[print:Duplicator 4 (0.1mm - infill 0.40)]
[filament:1.75 - BIANCO 210°]

**Comment by lordofhyphens** [comment]
Is this still a problem on 1.2.9?

**Comment by NinjaCross** [comment]
Unfortunately, due to this (and other problems) I had to abandon the usage of Slic3r in favour of a different software, so I hadn't had the chance to check it.

**Comment by xoan** [comment]
@lordofhyphens:
> Is this still a problem on 1.2.9?

Seems to be solved.

![captura de pantalla - 290616 - 11 04 43](https://cloud.githubusercontent.com/assets/288246/16446778/8a8052d4-3de9-11e6-95e6-cb7362c62f30.png)

**Comment by lordofhyphens** [comment]
Thanks
