### ISSUE TITLE
Ver 1.2.0 doesn't recognize multiple extruders in .ini file

### ISSUE THREAD

**Issue by dc42** [alexrj/Slic3r#2223]
When slic3r 1.2.0 loads a file that was saved when 2 extruders were configured in the Printer settings, it only shows 1 extruder. I have to re-add the second extruder every time I load slic3r 1.2.0. This happens whether the file was saved by version 1.1.7 or 1.2.0. Slic3r 1.1.7 loads the same .ini file correctly. Running x64 build under Windows 7. Here are the contents of the .ini file:

# generated by Slic3r 1.2.0 on Thu Aug 14 22:11:20 2014
bed_shape = 0x0,200x0,200x210,0x210
end_gcode = G1 E-5 F4000\nG1 X2 Y200; park the machine\nM0; stop
extruder_offset = -11x0,11x0.5
gcode_flavor = reprap
layer_gcode = 
nozzle_diameter = 0.5,0.5
retract_before_travel = 2,2
retract_layer_change = 1,1
retract_length = 4,4
retract_length_toolchange = 10,10
retract_lift = 0,0
retract_restart_extra = 0,0
retract_restart_extra_toolchange = 0,0
retract_speed = 45,45
start_gcode = ; layer_height = [layer_height]\nG21 ; set units to millimeters\nG90 ; use absolute coordinates\nM83 ; use relative distances for extrusion\nG1 Z5 F200 ; lift nozzle\nG1 X2 Y50 F4000; Go to wait for warm position\nG10 P1 R150\nG10 P2 R150\nM563 S1; add 1 to tool numbers from now on\nM116; Wait for all temperatures
toolchange_gcode = T[next_extruder]
use_firmware_retraction = 0
use_relative_e_distances = 1
vibration_limit = 0
wipe = 0,0
z_offset = 0

**Comment by alexrj** [comment]
@dc42, did have you have a chance to check whether this was fixed in the recent versions?

**Comment by alexrj** [comment]
This looks fixed.
