### ISSUE TITLE
slic3r 1.2.0 crashes when slicing auto-repaired file

### ISSUE THREAD

**Issue by dc42** [alexrj/Slic3r#2226]
slic3r 1.2.0 (x64 build running under Windows 7) crashes when slicing a file that it has auto-repaired, with Windows message "This program had requested the runtime to terminate it in an unusual way". Steps to reproduce:

1. Load the ini files at https://dl.dropboxusercontent.com/u/19369680/slic3rSettings2.zip into slic3r 1.2.0.
2. Reinstate the 2nd extruder that sli3er has forgotten about (reported as a separate issue).
3. Load file 2color_treefrog_big_solid.stl from http://www.thingiverse.com/thing:329436/#files.
4. Go to object settings and load additional file 2color_treefrog_big_hollow.stl from the same site.
5. Assign the first file to extruder 1 and the second file to extruder 2.
6. Export gcode.

If I slice the same files using slic3r 1.1.7 (using the "Combine multi-material STL files" option first), then slic3r does not crash when exporting gcode (although the generated gcode is no good because large parts of the first layer are missing).

**Comment by alexrj** [comment]
Unfortunately that file is severely broken, and even though Slic3r tries to repair it it doesn't succeed:

![schermata 2015-06-02 alle 22 36 10](https://cloud.githubusercontent.com/assets/594957/7946601/d609287c-0977-11e5-88b0-55bc26719e05.png)
