### ISSUE TITLE
Crash on export g-code (core dumped)

### ISSUE THREAD

**Issue by xix-xeaon** [alexrj/Slic3r#2228]
When I try to export g-code with this model it starts working but then crashes with this error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
Aborted (core dumped)
```
I used 1.2.0 from website on Linux x64.
Config: https://dl.dropboxusercontent.com/u/53934565/slic3r_config.ini
STL: https://dl.dropboxusercontent.com/u/53934565/frame.stl

Latest git version crashes whenever I **load** *any* model with:
```
Can't locate object method "raw_mesh" via package "Slic3r::Model::Object::Ref" at /home/xixxeaon/Downloads/Slic3r-dev/lib/Slic3r/Model.pm line 433.
```
I don't know if it's related but I've used earlier git versions successfully before.

**Comment by alexrj** [comment]
@xix-xeaon, did have you have a chance to check whether this was fixed in the recent versions?

**Comment by xix-xeaon** [comment]
Yes, both issues have been resolved in recent git.

**Comment by alexrj** [comment]
Thank you very much!
