### ISSUE TITLE
Brim distance

### ISSUE THREAD

**Issue by machinekoder** [alexrj/Slic3r#2230]
There is no option for setting the brim distance. Printing the brim lets say 0.1mm away from the object (and maybe use some rigid filling) would make it easier to remove the brim from the finished object. Cura has a similar option.

**Comment by alexrj** [comment]
Yes but wouldn't such a weak connection between brim and object defeat the anti-warping purpose of brim? Warping forces are quite high, and object may detach from brim...

**Comment by whosawhatsis** [comment]
It's a balancing act. The important thing is that the lines of the brim need to be connected to each other more strongly than they are connected to the part to tear away cleanly. The other option would be to slightly overlap the brim lines among themselves. That might actually be a better solution...

**Comment by strahlex** [comment]
Basically the connection between the object and the brim needs to be weaker than the brim itself. The idea of the brim is to prevent curling of the object. For this purpose the strenght of the brim is not important. It is important the brim is wide enought to provide enought adhesion to hold the object down.

**Comment by whosawhatsis** [comment]
For that purpose, the strength of the brim is not important, but for the purpose of trying to remove the brim in once piece, the strength of the brim (and the relative strength of it's connection to the print) is important.

**Comment by alexrj** [comment]
Okay, @whosawhatsis. Will do it :)

**Comment by lordofhyphens** [comment]
Looking at this, the way to go would be to subtract a little more distance (like half a perimeter width) from the space where the brim should be in _make_brim?

**Comment by alexrj** [comment]
I reduced the overlap between brim and object. Can someone try printing this? (Even if you don't run via git, we have automated builds now)

**Comment by lordofhyphens** [comment]
@machinekoder or @whosawhatsis could you check this please?

**Comment by machinekoder** [comment]
@lordofhyphens  I have switched to Cura in the meantime as it worked better for my application.

**Comment by lordofhyphens** [comment]
@machinekoder You were the one who had asked for it. It was implemented. Please check that it works so this issue can be closed (or reworked depending on the output).

**Comment by machinekoder** [comment]
Okay then I will close this issue.

**Comment by thiagopeixoto16** [comment]
@lordofhyphens I've noted the difference in the printed part itself then I came here to get more details. It is much better than before. Thanks

**Comment by haleypearse** [comment]
Any chance this could be implement as an adjustable parameter in the brim settings? The optimal value depends on other parameters like first layer extrusion multiplier and filament type. I have it set in s3d to 0.35mm with PETg. The brim comes off like a perforated tear line in paper. This is a great solution for adhesion and warping.

**Comment by Tinchus2009** [comment]
Hi... doesnt look like a good idea, seems like this would go against the purpuse of a brim. It is suposed to have a strong adhesion to the object, that s the way you gain adhesion to the bed

**Comment by haleypearse** [comment]
Setting a small (.1-.4mm) brim distance simply makes the brim removable by tearing off, by making it thinner where it meets the print. A brim with no distance usually needs cutting or filing around the perimeter of the print, which is never pretty. With a larger distance the brim barely joins the print, but with a heated bed and PETg this is still sufficient to hold the print in place.

**Comment by Tinchus2009** [comment]
As Lord pointed, im reporting issues with brim. lease reconsider this setting, right now the brim is almos useless while printing ABS. The hole purpose of a brin is to give a strong adhesion to the bed, creating a weak conection is not good.
