### ISSUE TITLE
[feature request] perimeter offset to make perimeters overlap over eachother

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#2235]
In case of 'stairway' extrusion , perimeters from layer down do not 'match' perimeters from layer above.  'generate extra perimeters if needed' should fix this, but next perimeters are often also offset.

Solution for this would be that extra perimeters would get small factor allowing them to be a little thinner to match perimeters extruded above them to provide good bonding. 
ofcourse some kind of range would need to be defined for that. 
this would allow to form strong shell inside object, with good inter-layer bond.

**Comment by alexrj** [comment]
I don't understand this - can you provide a test case?

**Comment by lordofhyphens** [comment]
@curiouspl2 I suspect this was a bug that has since been fixed. Closing as you never provided a test case ^^; 

If you provide a test case showing 1.3.0-dev has the issue, I'll reopen.

**Comment by haleypearse** [comment]
I have been doing this by using smaller perimeter extrusion widths and bumping up the extrusion multiplier to 120-130. Overhangs are coming out better. This fooling of the software is not ideal though.
