### ISSUE TITLE
Slic3r crashes when trying to load empty STL

### ISSUE THREAD

**Issue by microGen** [alexrj/Slic3r#2237]
This is only a minor issue, but as the title says, upon trying to load an STL file that contains no topological data, Slic3r quits without warning.
Now I understand that the scenario of an empty STL is very rare, but it would be nice to have Slic3r output a warning that the file is invalid/broken instead of crashing.

Tested with 1.1.5 and 1.2.0

**Comment by alexrj** [comment]
Okay, now it outputs an error message without crashing.
