### ISSUE TITLE
1.2.0 Exp - Slice Error modifier

### ISSUE THREAD

**Issue by bstott** [alexrj/Slic3r#2240]
I am using the 1.2.0 experimental and it crashes on slicing a box stl. The error given is:

Can't call method "modifier" on an undefined value at C:/Users/Dad/Documents/3D_Printing/Software/slic3r-1-2-0-experimental/lib/std/Slic3r/Print/Object.pm line 382.

P.S. Is there a way to attach the stl for your testing?

**Comment by alexrj** [comment]
@bstott, did have you have a chance to check whether this was fixed in the recent versions?

**Comment by alexrj** [comment]
Well, this looks fixed.
