### ISSUE TITLE
Feature Request: Infill starts inside of the part

### ISSUE THREAD

**Issue by koniarik** [alexrj/Slic3r#2243]
Hi folks

I've recent problems with start of the perimeter being too large (you can spot where perimeter started on the part really easily) and while I know I can improve it with another settings, I thought about one thing, would be possible to start perimeters inside of the part? -> the big dot at the start that somebody got problems with wouldn't be visible and it would make it look better

![p](https://cloud.githubusercontent.com/assets/5853442/4020594/3c9c9adc-2ac2-11e4-8665-a4807a8eb9e5.JPG)

black -> outer perimeter
red -> perimeter
green -> infill

(I know that the illustration picture is horrible, sorry)

**Comment by oysteinkrog** [comment]
@alexrj If this is covered by a patent we may be able to find a workaround that does not infringe the patent. Could you please post some details about the patent so that we can do some research?

**Comment by a4jp-com** [comment]
You just need seamline pressure settings to fine tune the start and end. A movement like that would probably cause other problems. Even a micro X/Y adjustment setting for the start and end of the seam would allow the nozzle to print cleanly without having to move from inside the model.

What is the patent? It's usually easy to tweak an idea so there is no conflict or find information that proves a patent is not an original idea.

**Comment by lordofhyphens** [comment]
https://www.google.com/patents/US20130095303
Looks like there referenced patent.
