### ISSUE TITLE
support bug

### ISSUE THREAD

**Issue by pciavald** [alexrj/Slic3r#2252]
Hi, 
Thank you for your contribution in the world of 3d printing :)
I've just found a bug in slicer's support generation
I'm trying to slice this stl ( https://drive.google.com/file/d/0B2BRn5mfsnVid00tbVpSTXBMZ3c click download at the top) with support settings of threshold 1 degree and [don't support bridges : off], no support is generated. If I select [don't support bridges : on], it does create the support for all appropriated slopes. Tested on 1.1.7 and 1.2.0.
Good luck !

![capture d ecran 5](https://cloud.githubusercontent.com/assets/3384097/4126137/86b3def4-32e8-11e4-8240-34478a754f97.png)

**Comment by lordofhyphens** [comment]
Is it still a problem in 1.3.0-dev? https://bintray.com/lordofhyphens/Slic3r/slic3r_dev/view
