### ISSUE TITLE
1.2.0 exp freezes *all* the time

### ISSUE THREAD

**Issue by darrenfreeman** [alexrj/Slic3r#2256]
As above. Sometimes I get nothing to stdout, but here are some things I've seen (only one line per freeze):

Argument "\x{2d}" isn't numeric in subtraction (-) at /home/opt/Slic3r/lib/std/Slic3r/GUI/BedShapeDialog.pm line 200.

Argument "\x{2d}" isn't numeric in subtraction (-) at /home/opt/Slic3r/lib/std/Slic3r/GUI/BedShapeDialog.pm line 202.

Scalars leaked: 1

Attempt to free unreferenced scalar: SV 0x60557e8, Perl interpreter: 0x6dd7a50 at /home/opt/Slic3r/lib/std/Slic3r.pm line 107.

**Comment by alexrj** [comment]
This is likely fixed as of today.
