### ISSUE TITLE
1.2.0 exp uses wrong slicing settings

### ISSUE THREAD

**Issue by darrenfreeman** [alexrj/Slic3r#2257]
I have had a few random things go wrong in the g-code output. I've had it output with no infill at all, or possibly with the spacing set to a huge number, and I've just had it output a brim even though I've never used one in my entire life.

It makes it really hit and miss.. you have to check g-code carefully every single time, and hope to not miss anything.

**Comment by alexrj** [comment]
No answer from @darrenfreeman :(
