### ISSUE TITLE
[feature request] minimum gap fill width

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#2270]
I've noticed gap fill does not fill below certain threshold. 
I have no idea what sets this theshold. 

It is apparent when i.e. doing 1mm wall thick print, 
and external perimeters is set to 0.35, then there is 0.3 gap inbetween perimeters left out.
my printer can do down to 0.2 extrusion - though it's not really usefull for perimeters, it can work fine
to make gap fill like this.

**Comment by lordofhyphens** [comment]
Should be fixed via new gap fill logic.
