### ISSUE TITLE
Accepting stdin as input file

### ISSUE THREAD

**Issue by tehpwny** [alexrj/Slic3r#2279]
Dear Slic3r maintainers,

I'm working on a project using Slic3r to slice a lot of STL data which isn't supposed to be real files on the system at this point, I would like to take input directly from stdin and read input from stdout but slic3r don't seems to support pipes (we tried multiples ways and workaround like named pipes but it doesn't work). 
Do you plan to fix that in the future ? 
Or am I doing it wrong ?

Dataloves, happy hacking,

**Comment by adius** [comment]
STL and gcode are really suited for a streaming interface.
So I think io with stdin and stdout should be planned!
