### ISSUE TITLE
slic3r-console broken

### ISSUE THREAD

**Issue by jgrjgr** [alexrj/Slic3r#2303]
i'm going from slic3r 9.8 to slic3r1.17  and i'm using the slic3r-console.exe part of slic3r in my slicing server, 
these are on files that slice perfectly fine on 9.8

the main error i get is "can't call "modifier" on  and undefined value at lib/std/slic3r/print/object.pm line 336"

**Comment by alexrj** [comment]
Should be fixed in 1.2.5.

**Comment by eduardgonzalez** [comment]
It works for me in win10 (previous versions did crash).
