### ISSUE TITLE
GUI Bug: Dropdown menu not displaying long profile titles (Slic3r 1.1.7, Windows 8.1 Pro 64bit)

### ISSUE THREAD

**Issue by jonaskuehling** [alexrj/Slic3r#2305]
Hi Alessandro,

we received a bug report from one of our customers, that the preset-dropdown menus don't show long profile titles, like you can see in the screenshot here:

![anzeigefehler profilauswahl](https://cloud.githubusercontent.com/assets/1555760/4663003/865672ca-5537-11e4-9809-016a9a2a67a3.jpg)

The used OS ist Windows 8.1 Pro 64bit.

Under Ubuntu 14.04 Linux (64bit) I cannot complain, since even rather long profile titles are shown in its full lengh when dropping down the list. So this seems to be limited to Windows.

**Comment by lordofhyphens** [comment]
Near as I can tell this is fixed by 1.2.9.
