### ISSUE TITLE
"Point not found" error when exporting G-code from command line

### ISSUE THREAD

**Issue by harriv** [alexrj/Slic3r#2306]
I'm running latest version from Git, and when slicing model I get this:

$ ./slic3r.pl T4MiniBody.stl 
Running Slic3r under Perl >= 5.16 is not supported nor recommended
=> Processing triangulated mesh
=> Generating perimeters
=> Preparing infill
=> Infilling layers
=> Generating skirt
=> Exporting G-code to ./T4MiniBody.gcode
Error in function split_at_vertex at src/libslic3r/ExtrusionEntity.cpp:263: Point not found
     at /home/harriv/slic3r/Slic3r/lib/Slic3r/GCode.pm line 183.
    Slic3r::GCode::extrude_loop('Slic3r::GCode=HASH(0x94534f4)', 'Slic3r::ExtrusionLoop::Ref=SCALAR(0x96669e0)', 'perimeter') called at /home/harriv/slic3r/Slic3r/lib/Slic3r/GCode.pm line 134
    Slic3r::GCode::extrude('Slic3r::GCode=HASH(0x94534f4)', 'Slic3r::ExtrusionLoop::Ref=SCALAR(0x96669e0)', 'perimeter') called at /home/harriv/slic3r/Slic3r/lib/Slic3r/GCode/Layer.pm line 215
    Slic3r::GCode::Layer::_extrude_perimeters('Slic3r::GCode::Layer=HASH(0x8bd83d4)', 'ARRAY(0x9726fd0)', 'Slic3r::Print::Region::Ref=SCALAR(0x966683c)') called at /home/harriv/slic3r/Slic3r/lib/Slic3r/GCode/Layer.pm line 183
    Slic3r::GCode::Layer::process_layer('Slic3r::GCode::Layer=HASH(0x8bd83d4)', 'Slic3r::Layer::Ref=SCALAR(0x971b8e4)', 'ARRAY(0x96f59c0)') called at /home/harriv/slic3r/Slic3r/lib/Slic3r/Print.pm line 925
    Slic3r::Print::write_gcode('Slic3r::Print=SCALAR(0x9459654)', './T4MiniBody.gcode') called at /home/harriv/slic3r/Slic3r/lib/Slic3r/Print.pm line 395
    Slic3r::Print::export_gcode('Slic3r::Print=SCALAR(0x9459654)', 'output_file', undef) called at /home/harriv/slic3r/Slic3r/lib/Slic3r/Print/Simple.pm line 96
    Slic3r::Print::Simple::export_gcode('Slic3r::Print::Simple=HASH(0x93742e0)') called at ./slic3r.pl line 204

$ git rev-parse HEAD
6b8f03ff1c8a83be88adf61486a6b47e4f3958b3

Model is this one: http://www.thingiverse.com/download:718624

Running Ubuntu 14.04, x86.

Exporting GCode from GUI seems to work ok.

**Comment by kyrreaa** [comment]
Just a note:
I encountered this in 1.2.5 Experimental, but not in 1.2.6 Experimental.
G-code data ends in middle of "sentence" and a partial model is printed on some complex models.
(I cannot share the file that fails unfortunately, trying to reproduce with a open file.)
Platform was 32 bit x86 which seems to fit the original issue.
