### ISSUE TITLE
Wrong detection of support necessity with both manually set threshold and auto detection (1.1.7)

### ISSUE THREAD

**Issue by jonaskuehling** [alexrj/Slic3r#2312]
Did another quick support test for further dual-extrusion tuning. Unfortunately the 50mm diameter sphere I tried printing with support received far too less support - in both auto detection mode (overhang threshold = 0) als well as manually set (overhang threshold = 45). Further the auto detection produces even less support than manual configuration (3 layers?) and doesn't even generate the perimeter-supporting zig-zag on top of support material interface. This seems to be alright with 45° threshold, though.

support_material_threshold = 0
![auto](https://cloud.githubusercontent.com/assets/1555760/4715910/2b540aac-5903-11e4-9b48-86e6833abee0.png)

![auto-01](https://cloud.githubusercontent.com/assets/1555760/4716033/8a149fc4-5904-11e4-8166-317b788c52de.png)

![auto-02](https://cloud.githubusercontent.com/assets/1555760/4716043/8df46fe8-5904-11e4-8a57-0e3df164ac04.png)

![auto-03](https://cloud.githubusercontent.com/assets/1555760/4716042/8dcf9e52-5904-11e4-9dda-e74948b1c03a.png)

support_material_threshold = 45
![45deg](https://cloud.githubusercontent.com/assets/1555760/4715924/54b3cbe4-5903-11e4-9633-7a1e18a6f5a1.png)

![45deg-01](https://cloud.githubusercontent.com/assets/1555760/4716053/9ab701fa-5904-11e4-80b4-d18c8a362b8a.png)

![45deg-02](https://cloud.githubusercontent.com/assets/1555760/4716051/9aabdf28-5904-11e4-83f0-2a31b9e3b07c.png)

![45deg-03](https://cloud.githubusercontent.com/assets/1555760/4716052/9ab0b912-5904-11e4-9f4e-9440160aada6.png)

STL: https://www.dropbox.com/s/utcjc7r2csqx0ge/sphere_r25.stl?dl=0
GCODE auto detection: https://www.dropbox.com/s/xk9itelwubu8aov/sphere_r25.gcode?dl=0
GCODE manual 45° threshold: https://www.dropbox.com/s/39quyfk1mew84ei/sphere_r25_45deg.gcode?dl=0

So, general support itselt seems so be much more correct with manually set 45° overhang threshold - compared to the auto detection - but still it is far away from supporting up to 45° surface angle of the sphere actually..

**Comment by lordofhyphens** [comment]
Still a problem in 1.3.0-dev or 1.2.9? Please reopen if it is.
