### ISSUE TITLE
How to compile Slic3r.pl which I have modified to exe programs?

### ISSUE THREAD

**Issue by a312514554** [alexrj/Slic3r#2316]
I have modified the Slic3r.pl, then I want to copy the source file to another computer, but I don't want to install Strawberry build-environment, I want to run the modified Slic3r through the method of exe programs. It is convenient for me to run the modified Slic3r in a computer which don't have the Strawberry build-environment. Could you tell me how to convert the Slic3r.pl to Slic3r.exe programs?Thanks for your help very much!!!!!!!

**Comment by lordofhyphens** [comment]
I'm currently working on it myself, but I don't honestly know offhand how @alexrj does it himself. 4

@bubnikv could you give me a primer or hint on how the build process you use for prusa3d.com?

For myself, I've done the following: 
1. Install PAR::Packer
2. Install Wx::Perl::Packer
3. Build Slic3r normally. 
4.Copy/paste the below into a batch file and put it in the slic3r build dir. 
5.Run the batch file.

`wxpar -c -B -M Class::Accessor -M Encode -M Encode::Locale -M File::Basename -M File::Spec -M FindBin -M IO::Scalar -M List::Util -M Math::PlanePath::ArchimedeanChords -M Math::PlanePath::Flowsnake -M Math::PlanePath::HilbertCurve -M Math::PlanePath::OctagramSpiral -M Math::Trig -M Moo -M Moo::Role -M OpenGL -M POSIX -M Scalar::Util -M Thread::Semaphore -M Time::HiRes -M Unicode::Normalize -M Wx -M Wx::DND -M Wx::Event -M Wx::GLCanvas -M Wx::Grid -M Wx::Html -M Wx::Print -M threads::shared -o slic3r.exe slic3r.pl`

**Comment by lordofhyphens** [comment]
@a312514554 Hopefully that works for you, it worked for me with a base Strawberry Perl 5.22 install (32-bit) on Windows 10.

**Comment by bubnikv** [comment]
This certainly works. It has a drawback though. The "exe" you get will decompress a content of the packed ZIP into a temporary directory, so you have a penalty of the decompression on startup and a penalty of having two copies of Slic3r on your hard drive, if you don't disable caching.

I believe this method works on MacOS as well.

Vojtech

**Comment by lordofhyphens** [comment]
For Windows we have compile_wrapper.ps1 and package_win32.ps1

Read the scripts for usage information.

Or download a build from dl.slic3r.org/dev
