### ISSUE TITLE
how to build slic3r-console.exe and slic3r.exe on Win7 x64 from the source code?

### ISSUE THREAD

**Issue by a312514554** [alexrj/Slic3r#2334]
how to build slic3r-console.exe and slic3r.exe on Win7 x64 from the source code?
like this?![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313237343532382f313631313337382f31653461336237322d353561612d313165332d386430332d6537303966316337386533652e706e67](https://cloud.githubusercontent.com/assets/8042696/4881564/92b19e7a-634a-11e4-95f9-1f104aee0a9b.png)

**Comment by likeant** [comment]
@a312514554 ：Do you success ???

**Comment by lordofhyphens** [comment]
As far as I know, Sound builds using the "from source" git instructions for Windows and then uses Cava packager to build the "exe" you run. http://www.cavapackager.com/
