### ISSUE TITLE
Feature Request: all contours clockwise or counterclockwise option to prevent backlash

### ISSUE THREAD

**Issue by georgmartius** [alexrj/Slic3r#2352]
Dear all,

I propose to add an option to go always the same direction on all contours (clockwise or counterclockwise). At the moment the direction is sometimes changed from layer to layer (depending on the shape or so) and this results in inhomogeneous surfaces due to slight printer backlash. 

What do you think?

**Comment by lordofhyphens** [comment]
This isn't something that we can reliably do in the slicer for the reasons @simonkuehling indicates.
