### ISSUE TITLE
Top collapses reproducible bug

### ISSUE THREAD

**Issue by imarin2** [alexrj/Slic3r#2357]
This is a bug of slic3r that the top layer collapses because slic3r does not infill in the layers just under it, even if the user forces it by setting a high number of solid infil layers on top (35 in this case).
All is discused in this thread (with fotos and screenshots that show the problem):
http://forums.reprap.org/read.php?263,429852,431787#msg-431787
All files (STL) and configuration used are in the thread and/or Thingiverse.

Do not feel compeled to fix the bug. I just wanted to provide you with all the information so that you can reproduce the bug if you want to fix it (Ï have seen in the internet that people complain about this bug, but they do not provide the means to reproduce it). I can not program in Perl, so in this I can not help much...

Nice piece of software. Thanks!!

![image](https://cloud.githubusercontent.com/assets/31754/16771278/7d051c3a-4815-11e6-9a1c-b957304b26ce.png)

[config_and_stl.zip](https://github.com/alexrj/Slic3r/files/359621/config_and_stl.zip)

(Added STL and configuration from thread for safekeeping and added a screenshot - @lordofhyphens).

**Comment by lordofhyphens** [comment]
* He's been bitten by the bug where combined infill doesn't actually make the infill layers thicker. This is how he probably noticed it in a print where it was weak structurally. This part has a PR available to fix it.
* Setting combined infill to 1 makes the symptoms go away, so I suspect that the problem lies in the surface aggregation function (combining areas to make prepare them for infill).
* Interestingly, if you set the combined infill setting to 1, slice and then go back to 4 the symptoms are gone but there's a few artifacts in the solid infill layers.

**Comment by lordofhyphens** [comment]
infill_every_layers = 1
![image](https://cloud.githubusercontent.com/assets/31754/16771349/cb4b65c0-4815-11e6-8de2-8ea9f1bb3f5f.png)

**Comment by alexrj** [comment]
Hm, I can't download this file anymore. I think this is fixed now. @lordofhyphens maybe you have the file still around?

**Comment by lordofhyphens** [comment]
If I uploaded it, I should still have it on my home work station. Will
check when I can.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
Darn, I can't find it. It is still available at the top of the linked
reprap.org thread.

**Comment by imarin2** [comment]
Sorry for the delay:
http://www.thingiverse.com/thing:515539/#files

**Comment by lordofhyphens** [comment]
@imarin2 I think this may have been fixed recently, can you retest using one of the new builds on bintray?

**Comment by lordofhyphens** [comment]
Looks fixed to me as of current master:
![image](https://cloud.githubusercontent.com/assets/31754/23827956/202d7f8a-0687-11e7-9eb5-2a712d85fb15.png)
[testcase.zip](https://github.com/alexrj/Slic3r/files/836210/testcase.zip)

**Comment by imarin2** [comment]
Thanks (without reopening) ;)
