### ISSUE TITLE
Feature Request: Threshold for extrusion length to minimize useless moves

### ISSUE THREAD

**Issue by luke321** [alexrj/Slic3r#2369]
Hello,

I upgraded my printer to a 0.25 mm nozzle and getting fabulous results with slicer, there is only one thing where I could see a possibility to improve prints.

It would be nice if you could set a minmal extrusion length and all extrusion moves shorter than that get removed from the gcode.

When printing parts sometimes gap fill / or infill is so small that the nozzle only hops to the point retracts and goes to the next, I often get this behaviour when printing gears. So if we could set a threshold that an extrusion must be at least x mm long  we could get rid of these extrusions which sometimes cause blobs or lots of unecessary moves and in case of infill are useless and regarding perimeters often don't stick very well or are not important.

Thanks for the great work!

**Comment by lordofhyphens** [comment]
There's an option to not retract if you didn't move (laterally) below a threshold. Closing.
