### ISSUE TITLE
adding modifier changing extrusion width breaks perimeter

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#2381]
adding modifier changing extrusion width breaks perimeter and 'inserts' modifier just as it was another object file into base object. 
This results in seam, start/stop of extruder, and other obvious effects.
slic3r 1.2.1 
you can use this as example : 
http://www.thingiverse.com/thing:569275

here are pics of example output and problem and modifier settings page. 
Problem occurs on all modifiers of the example object , and can be easily reproduced. 
![break perimeter](https://cloud.githubusercontent.com/assets/6697487/5233846/ee63b39c-776e-11e4-8421-475752e02e58.jpg)
![break perimeter settings](https://cloud.githubusercontent.com/assets/6697487/5233845/ee5ff5e0-776e-11e4-8b02-6279f33833d7.jpg)

**Comment by lordofhyphens** [comment]
In the far future of 2017, we do have variable-width perimeters available to us.
