### ISSUE TITLE
Should I compile Slic3r with a version of Perl that is under 5.16?

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2392]
When I compile Build.PL with Perl v5.20.1 I get a message for a lot of t files that says:

"Running Slic3r under Perl >= 5.16 is not supported"

This means, running Slic3r in Perl 5.16 or higher is not supported, doesn't it?

Is there a way to fix this so the newest version of Perl can be used without any problems?

**Comment by zsolta** [comment]
@a4jp-com :   Had you figured out which perl distribution/version works? I tried pretty much all versions of both strawberry and citrus and all failed at one point or another (eg. failed tests, missing perl518.dll or something similar when I tried to build it with citrus perl 5.16, etc). 

I am trying to build slic3r under windows7, but I am not a perl guy and all inputs will be highly appreciated.

**Comment by c-born** [comment]
Citrus v5.14.2 built for MSWin32-x64-multi-thread currently works for me.

**Comment by a4jp-com** [comment]
I have Perl 5.20.1 built for MSWin32-x86-multi-thread-64int.

Type in perl -v to check the version you have installed in the command prompt.

When you open the Windows Command Processor you might have to type in cd.. then cd.. to get back to the main directory. After that cd/directory-name-you-chose-for-slicer.

Next type in perl Build.PL -v

After that perl Build.PL --gui

**Comment by a4jp-com** [comment]
How do we get  MinGW working? I always get an error and have tried installing it in every way I know... Alessandro or anyone else, are there any setup pages for this?

**Comment by alexrj** [comment]
Strawberry Perl works fine, see instructions at http://slic3r.org/download

**Comment by a4jp-com** [comment]
Thanks for the quick reply Alessandro and all your hard work. I checked that site again but it doesn't explain how to install MinGW. It just says there is an installer available in Strawberry that can be installed. Does anyone have MinGW working in Windows 7 (64-bit) or have a link that shows how to get it working?

**Comment by markwal** [comment]
@a4jp-com, I think that comment was meant if you'd like to use the MingW that is included with Strawberry perl for your own development, you can with a bit of configuration.  Without any fussing though, just installing Strawberry Perl via the link above it installed enough of MingW to use to compile the modules that Slic3r needs via cpanm.  Though on the machine where I had ActivePerl and cygwin installed I had to remove them from my PATH (not just have them later) so that the build process didn't get confused and pick up prereq's from the other places.  Also on that machine I ended up using cpan to install the modules that cpanm was having trouble with.  I didn't stop to figure out why though since cpan worked.

**Comment by zsolta** [comment]
Thanks for all responses! I made a fresh/clean Win7 virtual machine, I installed strawberry-perl-5.20.2.1-32bit , then I downloaded the Slic3r tagged as 1.1.7 and run the build which failed due to test failures. The log looks like this: 
```
...
t\01_trianglemesh.t ............. ok
t\03_point.t .................... ok
t\04_expolygon.t ................ ok
t\05_surface.t .................. ok
t\06_polygon.t .................. ok
t\07_extrusionpath.t ............ ok
t\08_extrusionloop.t ............ ok
t\09_polyline.t ................. ok
t\10_line.t ..................... ok
t\11_clipper.t .................. ok
t\12_extrusionpathcollection.t .. ok
t\13_polylinecollection.t ....... ok
t\14_geometry.t ................. ok
t\15_config.t ................... ok
t\16_flow.t ..................... ok
t\17_boundingbox.t .............. ok
t\19_model.t .................... ok
All tests successful.
Files=17, Tests=399,  3 wallclock secs ( 0.20 usr +  0.12 sys =  0.33 CPU)
Result: PASS
Building Slic3r-XS
Files found in blib\arch: installing files in blib\lib into architecture dependent library tree
Installing C:\STRAWB~1\perl\site\lib\auto\Slic3r\XS\XS.bs
Installing C:\STRAWB~1\perl\site\lib\auto\Slic3r\XS\XS.xs.dll
Installing C:\STRAWB~1\perl\site\lib\Slic3r\XS.pm
OK
Successfully installed Slic3r-XS-0.01
3 distributions installed
t\angles.t ........... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\angles.t ........... 1/34
#   Failed test 'W direction'
#   at t\angles.t line 47.
#          got: '3.14159265358979'
#     expected: '0'
# Looks like you failed 1 test of 34.
t\angles.t ........... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/34 subtests
t\arcs.t ............. Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\arcs.t ............. ok
t\bridges.t .......... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\bridges.t .......... ok
t\clean_polylines.t .. Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\clean_polylines.t .. ok
t\clipper.t .......... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\clipper.t .......... ok
t\collinear.t ........ Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\collinear.t ........ ok
t\combineinfill.t .... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\combineinfill.t .... ok
t\config.t ........... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\config.t ........... ok
t\cooling.t .......... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\cooling.t .......... ok
t\custom_gcode.t ..... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\custom_gcode.t ..... ok
t\dynamic.t .......... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\dynamic.t .......... skipped: variable-width paths are currently disabled
t\fill.t ............. Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\fill.t ............. ok
t\flow.t ............. Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\flow.t ............. ok
t\gaps.t ............. Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\gaps.t ............. ok
t\gcode.t ............ Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\gcode.t ............ ok
t\geometry.t ......... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\geometry.t ......... ok
t\layers.t ........... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\layers.t ........... ok
t\loops.t ............ Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\loops.t ............ skipped: temporarily disabled
t\multi.t ............ Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\multi.t ............ ok
t\perimeters.t ....... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\perimeters.t ....... ok
t\polyclip.t ......... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\polyclip.t ......... ok
t\print.t ............ Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\print.t ............ ok
t\retraction.t ....... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\retraction.t ....... ok
t\shells.t ........... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\shells.t ........... ok
t\skirt_brim.t ....... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\skirt_brim.t ....... ok
t\slice.t ............ Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\slice.t ............ skipped: temporarily disabled
t\support.t .......... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\support.t .......... ok
t\svg.t .............. Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\svg.t .............. ok
t\thin.t ............. Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\thin.t ............. ok
t\threads.t .......... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\threads.t .......... ok
t\vibrationlimit.t ... Running Slic3r under Perl >= 5.16 is not supported nor recommended
t\vibrationlimit.t ... ok

Test Summary Report
-------------------
t\angles.t         (Wstat: 256 Tests: 34 Failed: 1)
  Failed test:  18
  Non-zero exit status: 1
Files=31, Tests=356, 212 wallclock secs ( 0.16 usr +  0.06 sys =  0.22 CPU)
Result: FAIL
Some tests failed. Please report the failure to the author!
```
I'm wondering what did I miss. Again, all inputs will be highly appreciated.

**Comment by zsolta** [comment]
Same configuration as in my previous post, this time I run the build for 1.2.6 and it succeeded. Does that means that 1.1.7 is not maintained ? Is there a way to disable the testing part during the build (even if it doesn't sound like a great idea).

Thank you,

**Comment by lordofhyphens** [comment]
The build still finishes even if the tests fail.

Also 1.1.7 isn't maintained.

**Comment by zsolta** [comment]
@lordofhyphens : right, the build finishes even the tests fail, just I got confused by the error message.

GUI builds nicely for both 1.1.7 and 1.2.6. Thank you for all inputs.

**Comment by lordofhyphens** [comment]
Iirc it is just 5.16.

**Comment by alexrj** [comment]
I recommend just running the `master` branch instead of tags...

**Comment by hroncok** [comment]
Actually, we are experiencing the same test failure on Fedora with Perl 5.22

https://bugzilla.redhat.com/show_bug.cgi?id=1231263

````
/builddir/build/BUILD/Slic3r-1.1.7
+ cd -
+ SLIC3R_NO_AUTO=1
+ perl Build.PL installdirs=vendor
#   Failed test 'W direction'
#   at t/angles.t line 47.
#          got: '3.14159265358979'
#     expected: '0'
# Looks like you failed 1 test of 34.
t/angles.t ........... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/34 subtests
````

The test is on second line here:

    is line_direction([ [0, 0],  [10, 0] ]), (0),      'E direction';
    is line_direction([ [10, 0], [0, 0]  ]), (0),      'W direction';
    is line_direction([ [0, 0],  [0, 10] ]), (PI/2),   'N direction';
    is line_direction([ [0, 10], [0, 0]  ]), (PI/2),   'S direction';

If I understand correctly, `line_direction` should give an angle between X axis and the line defined by it's two points. I believe that both PI and 0 are correct answers. Is the fact that PI is returned instead of 0 in any way dangerous, or could I just patch the test without worrying?

**Comment by amit79** [comment]
Hi All,
Sorry if I have posted on wrong thread and need help regarding citrusperl+slic3r.

I am trying to compile slic3r on citrusperl5.16, but i get errors for GUI compilation(related to OpenGL)
Tried installing packages manually for this citrus version but still the GUI part doesn't compile.
Then thought of using 5.14 version so searched on internet but cant find older version.So please is it possible for someone to upload citrulperl 5.14 version?

**Comment by lordofhyphens** [comment]
@amit79, Slic3r is known to fail on 5.16. Newer releases (5.18, 5.20) are
known to work. Strawberry Perl has a 5.20 release and is known to work.

As for getting ahold of an old version of citrus perl (if that is what you
really want), I suggest contacting their support structures instead of here.
http://www.citrusperl.com/support.html

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.
