### ISSUE TITLE
Extra bits stick out on single perimeter wall and sharp corners

### ISSUE THREAD

**Issue by napter** [alexrj/Slic3r#2404]
I'm consistently having a really wierd slic3r issue on sharp corners. Slic3r will add little bits extruding from the corner only on some layers - see here: 
![image](https://cloud.githubusercontent.com/assets/6260841/5334504/5d53337a-7e60-11e4-9cb7-efa711a149e6.png)

GCode: https://drive.google.com/file/d/0B57Du2WjL1iqYVNpOWxjdkY3TEk/view?usp=sharing
STL: https://drive.google.com/file/d/0B57Du2WjL1iqWU5SNTFVVFhrYzQ/view?usp=sharing

**Comment by alexrj** [comment]
Okay, this is how it looks like after several fixes:

![schermata 2015-06-02 alle 22 45 47](https://cloud.githubusercontent.com/assets/594957/7946807/3993441c-0979-11e5-9a1f-5285a5977063.png)

Those two tiny loops are probably not what user expects, but the original shape is actually thicker there and Slic3r is behaving correctly.  Also now all layers are consistent:

![schermata 2015-06-02 alle 22 46 18](https://cloud.githubusercontent.com/assets/594957/7946819/584ca1be-0979-11e5-87c1-af3ba2b16b02.png)

Thank you for reporting this test case.

**Comment by napter** [comment]
You fixed it! It's amazing now, thank you!

**Comment by napter** [comment]
I found a similar issue where all the layers are not consistent. I'm not sure if it's the same issue, this is a weird one. Slice the model and it prints with the issues in the top right picture - missing parts of layers and extra blobs in the GCode. Then rotate the model, as you can see the orientation in the bottom set is rotated 180 degrees, and the issues go away and it slices and prints perfectly. [config file](https://drive.google.com/file/d/0B57Du2WjL1iqX0Q0MHJBYlA5RDQ/view?usp=sharing) and [STL file](https://drive.google.com/file/d/0B57Du2WjL1iqejVwSzNaMmFSdVk/view?usp=sharing)
![slic3r issue](https://cloud.githubusercontent.com/assets/6260841/8299297/9892994c-1944-11e5-8463-46aab56a59dc.png)

**Comment by alexrj** [comment]
@napter, I moved that to a new issue (@2948)
