### ISSUE TITLE
Inside circle is not round in the toolpath preview.

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2416]
![screen shot 12-14-14 at 05 36 pm](https://cloud.githubusercontent.com/assets/9621044/5426858/f5eb6e02-83b7-11e4-8ee8-6d0d22adcf5e.JPG)

Windows 7 64-bit
Slic3r 1.2.2-dev

http://a4jp.com/3d-files/bugs/2014-12-14th-5-42-pm-for-github-config.ini
http://a4jp.com/3d-files/bugs/walking-machine.stl

**Comment by harriv** [comment]
Clipper library can be found here: http://angusj.com/delphi/clipper.php

**Comment by alexrj** [comment]
Okay, these artifacts are now filtered out by Slic3r.
