### ISSUE TITLE
Allow g-code on per filament basis

### ISSUE THREAD

**Issue by linor** [alexrj/Slic3r#2419]
Currently there's an option to add g-code to the start and end of the file based on printer settings. It would be usefull if you could have a similar g-code start/end block for filament too, for instance to set extruder steps (rather then using the multiplier).

**Comment by lordofhyphens** [comment]
@simonkuehling the only thing I can think of offhand is @linor apparently wants to affect retract/restore and using firmware retraction.

Otherwise the two are equivalent.

Closing, please reopen if there's another use case (and one that doesn't break things if you have more than one extruder).
