### ISSUE TITLE
【Feature request】Zoom and pan for the preview (toolpath) tab: I can't see small details. Can I get zoom and pan for the path tab?

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2434]
I can't see small details. Can I get zoom and pan for the path tab?

Sometimes models are difficult to see because they are small. Could you add zoom and pan to the toolpath window?

![screen shot 12-20-14 at 12 42 am](https://cloud.githubusercontent.com/assets/9621044/5506860/7bd1baf8-87e1-11e4-8abb-07f4a1fb13c9.JPG)

**Comment by a4jp-com** [comment]
Any chance of getting zoom and pan added to the 2D toolpath view?

**Comment by alexrj** [comment]
This is now implemented as of 1.2.7-dev.
