### ISSUE TITLE
Sponsoring Proposal: A Soluble Support Material Option 

### ISSUE THREAD

**Issue by simonkuehling** [alexrj/Slic3r#2435]
Hi @alexrj,

a while back i tried to contact you via email offering to fund the introduction of a soluble support material option into Slic3r - but as i have not heard back from you, i'd like to quickly check if my messaged reached you inbox at all. Never mind if you are just busy or something - just wanted to make sure the mail addresses i tried were correct.

We are making really (like REALLY!) awesome progress on prints with soluble supports (ABS/HIPS as one example) by generating support-structure-volumes with external scripts and printing them in a two-material setup with different extruders.
I'd be very happy to talk to you about this - if you feel it is worth considering, you are welcome to contact me directly via office@kuehlingkuehling.de

(Pardon me for using the issue system for my request - i just could find you on irc as well recently... )

**Comment by alexrj** [comment]
Done! I added an option for vertical distance between object and support, with special handling for the case where distance is set to 0, that disables bridge flow and speed. for the first layer. :)
