### ISSUE TITLE
Changing extruder on an object, with multple objects on the plater, segfaults

### ISSUE THREAD

**Issue by dakkar** [alexrj/Slic3r#2446]
To reproduce:
* take any STL (I tested with a simple cube)
* add it to the plater twice (it does not make any difference if the two STL are the same or not)
* select one
* press "settings"
* change the extruder to any value different than the default (1)
** you can set it on the object, or on the part, but if you set the object's extruder to 2, and the part's extruder to 1, it won't segfault
* press "ok"
* watch the segfault

Tested on Slic3r commit 632e3, perl 5.14.4 and 5.18.2

Attached my settings directory as a tarball.

`gdb` says the segfault is inside `Slic3r::Print::apply_config(Slic3r::DynamicPrintConfig)`

Possibly related:
* adding one object, setting its extruder to 2, then adding another object segfaults in the same way
* the extruder drop-down has 5 values ('default', 1, 2, 3, 4) but I only have 3 extruders
* changing the extruder setting while the program is slicing in the background seems to deadlock something

**Comment by alexrj** [comment]
@dakkar, did have you have a chance to check whether this was fixed? Thank you :)

**Comment by dakkar** [comment]
I finally tested it. It works now.

**Comment by alexrj** [comment]
Grazie for checking!
