### ISSUE TITLE
The infill cuts through the bottom left hole in the model

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2448]
The infill is cutting through the bottom left hole in the model below.

Windows 7 64-bit
Slic3r 1.2.2-dev (2014-12-24th 10:23 a.m.)

http://a4jp.com/3d-files/bugs/2014-12-24th-10-21-am-for-github-config.ini
http://a4jp.com/3d-files/bugs/block-with-holes.stl

![screen shot 12-24-14 at 10 20 am](https://cloud.githubusercontent.com/assets/9621044/5544945/34ec9698-8b57-11e4-875c-60bb4341d968.JPG)

-----------------
Slic3r 1.2.2-dev (2014-12-26th 1:38 a.m.)
![screen shot 12-26-14 at 01 36 am](https://cloud.githubusercontent.com/assets/9621044/5554497/cacebb98-8c9f-11e4-9aa6-81b3fc667494.JPG)

**Comment by a4jp-com** [comment]
Thank you. 

If I change the infill percent I can sometimes get rid of the problem but a fix would be great ^^

**Comment by a4jp-com** [comment]
Angus posted some code. Maybe it is the fix ^^

**Comment by alexrj** [comment]
Okay, this is now fixed.

**Comment by a4jp-com** [comment]
Thank you ^^
