### ISSUE TITLE
Layers with missing infill

### ISSUE THREAD

**Issue by darrenfreeman** [alexrj/Slic3r#2452]
Slic3r experimental 1.2.1

I can't see what this depends on.. it seems intermittent and not triggered by anything in particular.

Scrolling up through the layers (as you do before printing).. I see that some layers are just a perimeter and no infill. They occur seemingly at random, and usually I can live with it because there's just one. But today I have a model that has a few close together in Z, so I wish it hadn't gone from solid infill to effectively hollow at that spot.

I am running 100% infill and this part of the model is not varying in Z. So the layers have identical perimeters and alternating +45 and -45 degree infills as I go up through the layers. And then for no reason, no infill at all.

**Comment by darrenfreeman** [comment]
Unless you have fixed this, I don't think you should close it. It's a real bug. I'm not asking you to fix it in ten days, so please don't expect me to produce a test case in ten days.

**Comment by darrenfreeman** [comment]
I still don't have a way to attach files to bug reports, so I'll have to email it.

**Comment by alexrj** [comment]
No hurry, just open an issue when you have collected everything that's needed for submitting an issue.

(You can host things on some file hosting provider, like Dropbox, and put a link here.)
