### ISSUE TITLE
[1.2.7 experimental binary] 64bit slic3r fails to start in gui mode

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#2456]
bug concerns latest x86_64 binaries published . 
no error, it just runs as commandline app, no way to start up gui. 

system is linux 64bit, based on knoppix 7.4 .

**Comment by curiouspl2** [comment]
it applies to 1.2.4 aswell. knoppix is free to download from knoppix.org, and can be run in i.e. qemu. 

i wouldn't bother if it does not happen on other linux distros though

**Comment by alexrj** [comment]
@curiouspl2, try to launch it with the `--gui` option. It should output a more detailed error. Could you paste it here?

**Comment by alexrj** [comment]
Okay, I think it was libglut.so missing in the package. This should be fixed in 1.2.5. Let me know.

**Comment by alexrj** [comment]
@curiouspl2, is this fixed as of 1.2.5?

**Comment by curiouspl2** [comment]
sorry for delay. yes, it is fixed in 1.2.5 :) 
thank You!

**Comment by alexrj** [comment]
Thank you for confirming!

**Comment by curiouspl2** [comment]
again in 1.2.6
 
knoppix@Microknoppix:~/Desktop/slic3r/Slic3r.1.2.6/bin$ ./slic3r --gui
Can't load '/home/knoppix/Desktop/slic3r/Slic3r.1.2.6/lib/vrt/8b57d08e0d55cfe6498642b59ecf5ad1/Wx.so' for module Wx: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory at <content>/DynaLoader.pm line 157.
 at /home/knoppix/Desktop/slic3r/Slic3r.1.2.6/lib/std/Slic3r/GUI/AboutDialog.pm line 6
Compilation failed in require at /home/knoppix/Desktop/slic3r/Slic3r.1.2.6/lib/std/Slic3r/GUI/AboutDialog.pm line 6.
BEGIN failed--compilation aborted at /home/knoppix/Desktop/slic3r/Slic3r.1.2.6/lib/std/Slic3r/GUI/AboutDialog.pm line 6.
Compilation failed in require at /home/knoppix/Desktop/slic3r/Slic3r.1.2.6/lib/std/Slic3r/GUI.pm line 8.
BEGIN failed--compilation aborted at /home/knoppix/Desktop/slic3r/Slic3r.1.2.6/lib/std/Slic3r/GUI.pm line 8.
Compilation failed in require at (eval 107) line 1.

**Comment by bogger33** [comment]
Your new issue is the same as this:

https://github.com/alexrj/Slic3r/issues/2631

**Comment by curiouspl2** [comment]
hello. it is still broken in 1.2.7
knoppix@Microknoppix:~/Desktop/slic3r/Slic3r.1.2.7/bin$ ./slic3r --gui
Can't load '/home/knoppix/Desktop/slic3r/Slic3r.1.2.7/lib/vrt/8b57d08e0d55cfe6498642b59ecf5ad1/Wx.so' for module Wx: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory at <content>/DynaLoader.pm line 157.
 at /home/knoppix/Desktop/slic3r/Slic3r.1.2.7/lib/std/Slic3r/GUI/AboutDialog.pm line 6
Compilation failed in require at /home/knoppix/Desktop/slic3r/Slic3r.1.2.7/lib/std/Slic3r/GUI/AboutDialog.pm line 6.
BEGIN failed--compilation aborted at /home/knoppix/Desktop/slic3r/Slic3r.1.2.7/lib/std/Slic3r/GUI/AboutDialog.pm line 6.
Compilation failed in require at /home/knoppix/Desktop/slic3r/Slic3r.1.2.7/lib/std/Slic3r/GUI.pm line 8.
BEGIN failed--compilation aborted at /home/knoppix/Desktop/slic3r/Slic3r.1.2.7/lib/std/Slic3r/GUI.pm line 8.
Compilation failed in require at (eval 70) line 1.

**Comment by alexrj** [comment]
Since we recently learned that shipping those libs with Slic3r leads to crashes on several platforms (as they are dependent on the graphic card drivers), future releases starting with 1.2.8 will not carry the GL/GLU/glut libs. So they are a prerequisite to install using your distro's package manager.
