### ISSUE TITLE
Infill overlap option

### ISSUE THREAD

**Issue by lonelymyp** [alexrj/Slic3r#2459]
My printer is made of plastic and has unrecoverable backlash in axes. 
So I have problems at the connection infill with perimeter. 
Cura have a great option "Infil overlap", it makes infill come on the perimeter, Infil overlap = 40% perfectly solves the problem.
But I like a lot more Slic3r, it would be great to see such an option in the Slic3r.

Here is an example:
![example](https://cloud.githubusercontent.com/assets/2085051/5562728/8ce1c290-8e47-11e4-8971-ab23c99ab556.jpg)
everything is fine except that the perimeter is not in contact with the infill.

**Comment by DwayneS** [comment]
Looks similar to issues delta printers have with excess arm friction. Can also be caused by improper belt tension or loose carriages on an axis from worn or improperly adjusted bearings, those issues affect both cartesian and delta.

**Comment by alexrj** [comment]
Okay, I added an option for this.  It's getting requested a lot...
