### ISSUE TITLE
V1.2.2 crashing without error message when specific STL file is loaded

### ISSUE THREAD

**Issue by justmyopinion** [alexrj/Slic3r#2461]
Win7/X64
When I drag this file to plater, Slic3r crashes  without error message
https://www.dropbox.com/s/uki4a9ddmog77cp/3DR_Top_Boss_V2_001_RTP%20%281%29.stl?dl=0
ini file is default settings.

**Comment by alexrj** [comment]
Okay, I'm able to reproduce this on Windows only.

**Comment by alexrj** [comment]
Fixed!  It was a bug in the admesh code.
