### ISSUE TITLE
1.2.3 Pressure Management and Retraction bug

### ISSUE THREAD

**Issue by ccavanaugh** [alexrj/Slic3r#2470]
I tried the new Pressure management with a K factor of 8.  When used in combination with retraction enabled (10 mm) , the filament was retracted significantly multiple times until it was half way up the bowden tube before I stopped the print.  This occurred while laying the perimeter of the first layer.

Resliced without pressure management enabled and everything was okay.

**Comment by alexrj** [comment]
@ccavanaugh, I failed to reproduce the issue. I also wrote a unit test that succeeds.

Could you provide more details for reproducing that? STL file and configuration (File -> Export config…). Thank you!

**Comment by alexrj** [comment]
Okay, I fixed this and added a regression test. Thank you!

**Comment by ccavanaugh** [comment]
Thank you!... Will try again after the next release.  I'm tying to run nylon with heavy retract and looking forward to seeing if it improves print quality.

**Comment by braddo99** [comment]
Terrific, had this problem too, massive retraction (and I couldn't see it in the gcode for some reason?)
