### ISSUE TITLE
Infill missing, preview doesn't reflect this

### ISSUE THREAD

**Issue by fpiesik** [alexrj/Slic3r#2474]
Slic3r version: 1.2.4
OS: Ubuntu 12.04 64Bit

Expected result: Infill should be everywhere, gcode-preview should reflect the actual gcode.
Actual result: A part of the infill is missing in the actual gcode, but not in the Slic3r-preview.

Slic3r preview:
![image](https://cloud.githubusercontent.com/assets/1476763/5592785/2ac4e5de-91e3-11e4-9ce5-c82a32aec386.png)

actual gcode (displayed in octoprint):
![image](https://cloud.githubusercontent.com/assets/1476763/5592787/45208136-91e3-11e4-9ee5-e538409dc563.png)

files (didn't found a way to attach to this issue):
https://www.dropbox.com/sh/qc9rtwu8h7oxyep/AACV_R1dOt3Qy7JVWS1N_mmsa?dl=0

**Comment by a4jp-com** [comment]
How are you trying to print this? Do you have supports turned on?

![screen shot 01-02-15 at 01 19 pm](https://cloud.githubusercontent.com/assets/9621044/5594162/343056e0-9282-11e4-84fb-ebd2cb180b54.JPG)

**Comment by Piesi** [comment]
it's rotated 90 degrees along the x-axis
Am 02.01.2015 05:21 schrieb "a4jp-com" <notifications@github.com>:

**Comment by a4jp-com** [comment]
I rotated it as you said.

![2015-01-02nd](https://cloud.githubusercontent.com/assets/9621044/5595941/afbe3fc0-92c3-11e4-9847-f4b9426837dc.gif)

**Comment by fpiesik** [comment]
The thing is, that the slic3r preview doesn't show the missing infill. look at my screenshots, in the slic3r preview the infill is there, but in the actual gcode, there is some infill missing. Yes, I actually use a 0.8mm nozzle as it prints much faster and the resolution is still good enough for most of my print jobs.

**Comment by a4jp-com** [comment]
Maybe Octoprint has the problem. Have you tried printing using another program? I would also have at least 2 perimeters if possible. Go into the advance settings for the time being and get some more. See if that makes a difference. It might not fix Slic3r but it might fix the G-code for printing.

**Comment by fpiesik** [comment]
nope, it's not a problem with octoprint. here is a screenshot of the second layer made with pronterface:
![image](https://cloud.githubusercontent.com/assets/1476763/5600917/7cfb16a8-92e6-11e4-8652-2a65e14ee20c.png)

With a 0.8mm nozzle there is no need for two perimeters, that speeds up the printing process significantly. I have made many good and fast prints this way. 

actually, the infill is only incorrect in a few layers which is not a very big problem in this case.

I think the main issue here is the indifference between the slic3rs gcode preview and the actual gcode.

**Comment by a4jp-com** [comment]
That's okay but please change the settings to see if there is a bug.

**Comment by fpiesik** [comment]
sorry, but I don't get the point of changing the paras to something i don't want. I have used many different parameters and never noticed this beahviour before. I provided everything needed to prove that under this circumstances there IS a bug. the gcode differs from what the preview shows and from what it should be...

**Comment by a4jp-com** [comment]
Okay. If you can't try then I can't help you. Sorry.

**Comment by alexrj** [comment]
@fpiesik, good catch there. I'm able to reproduce this issue, and the problem is not in the viewer since the missing segments are actually missing from G-code.

**Comment by alexrj** [comment]
Ouch, I'm suddenly unable to reproduce this anymore... :(

**Comment by fpiesik** [comment]
ah, good to hear that and how it can (not) be reproduced:)

**Comment by alexrj** [comment]
Very tricky issue, combining two distinct minor bugs that I managed to isolate into regression tests. One of them is already fixed.

**Comment by alexrj** [comment]
Fixed!

**Comment by fpiesik** [comment]
Great!
Am 22.05.2015 14:26 schrieb "Alessandro Ranellucci" <
notifications@github.com>:
