### ISSUE TITLE
Scroll wheel zoom direction in the 3d view is clearly wrong!

### ISSUE THREAD

**Issue by Lenbok** [alexrj/Slic3r#2478]
Actually, I realise it's fairly arbitrary, but when using the scroll wheel to zoom in the 3d preview, the direction is inverted when compared to most other apps in the 3d printing toolchain, like: openscad, netfab, tatlin, blender, thingiverse 3d view, and the octoprint gcode viewer. With all of these, pushing the scroll wheel forward makes the 3d object bigger.  Please invert the scroll wheel direction for consistency with these apps.

**Comment by Lenbok** [comment]
(BTW, I am using 1.2.4, which is awesome!!)

**Comment by gege2b** [comment]
I agree, it's very disturbing ^_^

**Comment by a4jp-com** [comment]
Or add an option to reverse it please ^^

**Comment by alexrj** [comment]
@a4jp-com, it was you that asked to reverse it (#2420)... <facepalm>

**Comment by alexrj** [comment]
Anyway, I reversed it again.
