### ISSUE TITLE
Cannot create g-code for pre-arranged sequential printing objects of different STLs

### ISSUE THREAD

**Issue by blue-ice** [alexrj/Slic3r#2480]
Slic3r 1.1.7
Lubuntu Trusty 14.04 LTS
No command line parameters
[Config file](https://docs.google.com/uc?export=download&id=0B9BayVcJhr5NUWhGYXF2bDRWTmM)

[endstop+motor_clip.stl](https://docs.google.com/uc?export=download&id=0B9BayVcJhr5NTlRGOTdrVWxJa1U)
[motor_clip.stl](https://docs.google.com/uc?export=download&id=0B9BayVcJhr5NbjdwelRuQUlIYnM)

The print here is set up to be sequential, so each object should complete individually. The radius of the extruder is 17mm, and the height is 15mm. The parts are only about 6mm tall.

![2015-01-01-160252_627x389_scrot](https://cloud.githubusercontent.com/assets/7453952/5593665/75757514-91dc-11e4-9850-6602e04f2d84.png)

When setting up a print with 4x endstop+motor_clip.stl and 8x motor_clip.stl (above), and pressing "Arrange" on the top button, the print will not export to g-code and it instead fails with "Some objects are too close; your extruder will collide with them."

![2015-01-01-160242_311x183_scrot](https://cloud.githubusercontent.com/assets/7453952/5593664/71cf162c-91dc-11e4-815a-cb10dd6fa1f8.png)

Even moving the prints slightly apart from each other didn't help at all.

However, after arranging the print into 2 separate areas, one with one STL, and the other with the other STL, the g-code was exported:

![2015-01-01-160223_923x432_scrot](https://cloud.githubusercontent.com/assets/7453952/5593663/6e31c53c-91dc-11e4-8925-fe0d368d5638.png)

What I'm hoping is that it would export with the original setup instead of having to move it around. Thanks.

**Comment by alexrj** [comment]
Thank you, I have fixed this in 1.2.5-dev.

**Comment by blue-ice** [comment]
Thanks!
