### ISSUE TITLE
Octoprint integration: 500 error

### ISSUE THREAD

**Issue by PxT** [alexrj/Slic3r#2481]
Slic3r 1.2.4
Mac OS 10.10.1

If I upload a very large gcode file (20MB) I get an error back:  
```Error while uploading to the OctoPrint server: 500 read timeout```

I can upload the same file manually with no error.

**Comment by PxT** [comment]
![screen shot 2015-01-01 at 10 46 57 am](https://cloud.githubusercontent.com/assets/1613394/5593766/2f73118a-91db-11e4-9934-9c083c8d6342.png)

**Comment by alexrj** [comment]
What OctoPrint version?

**Comment by PxT** [comment]
Octoprint Version: 1.1.1 (master branch)

**Comment by alexrj** [comment]
I increased the timeout now. Works also with large files.

**Comment by twproject** [comment]
I have the same problem in the devel branch
Version: 1.2.0-dev-687-g45bf398 (devel branch)

**Comment by lordofhyphens** [comment]
That got fixed months ago, and the version number you give makes no sense.
Use the master branch.
