### ISSUE TITLE
Dragging the 3D View stops when hovering an object

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#2482]
Hi all
Commit 69da8b09997c58c3f47d1e676fe578f68cbb96e9
Debian Wheezy x64

When I import an object and drag the  3D view to turn around it, if the mouse pass over the object (when it highlights), sometimes the dragging stops

edit: it seems that the mouse should be very close to the object when starting to drag the view for this issue to happens. If the cursor is far enough (2 or 3 grid unit - arbitrary measure), it works fine even when hovering

Well, its not a big issue, but its an annoying one (like the wheelzoom inverted ^_^)

**Comment by a4jp-com** [comment]
This is kind of the same problem I have:

https://github.com/alexrj/Slic3r/issues/2454

**Comment by gege2b** [comment]
Exact, I didn't found your issue before posting mine
I was speaking about rotating the view, but pan is also chaotic

I observed that the pan/rotation of the view is dropped as soon as the object is highlighted, and sometimes the object is highlighted even if the mouse isn't hover him.

**Comment by alexrj** [comment]
Okay, I fixed this.
