### ISSUE TITLE
X/Y differences when "Detect thin walls" is disabled

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#2485]
OpenSCAD model: http://hastebin.com/xiwakacupu.erl (walls are 0.5mm; it is only a testcase --print it with "Detect thin walls" disabled has no sense)
STL file: http://hastebin.com/nametufuci.vbs
Slic3r config: http://hastebin.com/edegatotis.hs

1. Load the same model twice
2. Rotate one of them 90º

When "Detect thin walls" option is enabled, G-code generated file is as expected:
![screenshot-gcode ws 2015-01-02 15-44-49](https://cloud.githubusercontent.com/assets/288246/5596848/fea76dd6-9297-11e4-8e07-d34f47995c57.png)

But with this option disabled, there are significant differences when the geometry is in X axis and when it is in Y axis:
![screenshot-gcode ws 2015-01-02 15-42-46](https://cloud.githubusercontent.com/assets/288246/5596850/fef9098e-9297-11e4-8ffa-d13bf3ffcee1.png)

Also some other strange things happen when this walls are 45º:
![screenshot-gcode ws 2015-01-02 15-55-52](https://cloud.githubusercontent.com/assets/288246/5596849/fecfa9ea-9297-11e4-9d29-10246b1b0a65.png)

**Comment by a4jp-com** [comment]
When I was printing a ring I had to turn off "detect thin walls" to get perimeters to show properly so it was an important setting for me. I haven't had the problem above yet though.

**Comment by xoan** [comment]
Related: #2829

**Comment by xoan** [comment]
Seems to be fixed in 31e0fc7 like the referenced issue.

Thanks.
