### ISSUE TITLE
GUI update that can fix the icon padding problem

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2486]
Can you make the Windows version of Slicer look more like this? 

![53933b5e-9293-11e4-90ec-03421cae73dd](https://cloud.githubusercontent.com/assets/9621044/5597030/becc2d68-92de-11e4-93ee-738674e59767.png)

Maybe it would be nice to take away the dots after a few words as well.

Add...
Scale...
Settings...
Export STL...
Export G-code... 

This will also fix the padding problem ^^

**Comment by xoan** [comment]
Dots after a word in a button or menu entry means the click opens a dialog or another kind of input to allow user interaction.

**Comment by koghe** [comment]
you can customize your Gtk/Wx theme on window too http://gtk-win.sourceforge.net/home/ search for gtk theme on google
dots as to do with some standard good gui design

**Comment by a4jp-com** [comment]
Thanks for explaining that Xoan but the save button doesn't have 3 dots so I don't think we need 3 dots to tell us a screen will popup when we hit a button.
If you check out the "save current print settings" icon as an example. It doesn't have the 3 dots.
I can guess when I hit the add icon that a dialogue will pop-up.
Also if I push scale, I just expect a dialogue box of the cursor to change.
Do you think the 3 dots are important? 
I think removing them will make the program cleaner and easier to use.
If they are important I suggest changing the icons instead.
The 3 dots are more confusing and just look like a mistake to me.

**Comment by a4jp-com** [comment]
![screen shot 01-03-15 at 04 28 pm](https://cloud.githubusercontent.com/assets/9621044/5601874/b2ccff74-9365-11e4-98a5-483e6815e574.JPG)

![screen shot 01-03-15 at 04 23 pm](https://cloud.githubusercontent.com/assets/9621044/5601875/b2d1501a-9365-11e4-9fed-5c1560e7914d.JPG)

**Comment by alexrj** [comment]
Short answer to your original question is: no, I can't make the Windows version look like the Linux/GTK one. That depends entirely on the GUI toolkit.

Regarding dots, as @xoan explained they have a standard meaning and their presence is correct. The "Save current print settings" button is just an icon with no text, so putting three dots alone would look pretty dumb.

**Comment by a4jp-com** [comment]
Okay. I understand now. 

If this is a standard rule in programming does Google Chrome only use 3 dots for options with popups?

![screen shot 01-03-15 at 07 48 pm](https://cloud.githubusercontent.com/assets/9621044/5602218/158f1aee-9383-11e4-9758-6a7900ef71bf.JPG)
