### ISSUE TITLE
Add option for adjustable gap between support material

### ISSUE THREAD

**Issue by DwayneS** [alexrj/Slic3r#2491]
KISSlicer and Skeinforge provide an option for the gap between support material and the object being printed. In KISSlicer I get excellent results using a gap that is 90% of my layer height (so 0.18 on 0.2mm layers). This gives enough separation that the support peels away cleanly without tools, but the bottom surface has no loose threads and the extrusions aren't fat and rounded like a bridged gap without support. The lack of support options is the only reason I still ever resort to using other programs. This would be a very simple change to make, just change the contact_distance method in SupportMaterial.pm to read a constant entered in the GUI.

**Comment by alexrj** [comment]
Done! I added an option for vertical distance between object and support.
