### ISSUE TITLE
Binary download on slic3r.org

### ISSUE THREAD

**Issue by HcDevel** [alexrj/Slic3r#2493]
I currently try to download the Linux binaries from slic3r.org. Clicking on any operating system button there is a quite long attempt to connect and the connection fails. Are there any known problems?

**Comment by MorganSandercock** [comment]
I get the same problem clicking on the Windows stable version. (I did not try the others.)

**Comment by alexrj** [comment]
Sorry! The server was down overnight. Now it's running again.
