### ISSUE TITLE
Slic3r 1.2.4 missing perimeter segment

### ISSUE THREAD

**Issue by mkurc1234** [alexrj/Slic3r#2495]
I have noticed a missing perimeter segment on first layer. The rest of layers looks ok. All files (STL, GCODE and config) are on my dropbox:
https://www.dropbox.com/sh/jxre2iyuffzpre6/AAAfaAGMqWQLSLmSmnr24XvJa?dl=0

![screenshot](https://cloud.githubusercontent.com/assets/7130520/5606809/45d0417e-9441-11e4-927e-15055a611479.png)

**Comment by curiouspl2** [comment]
i confirm this occurs, and is especially annoying on bridges.

**Comment by alexrj** [comment]
I can reproduce this. It's horrible.

**Comment by alexrj** [comment]
Fixed, and added regression test. Thank you for reporting.
