### ISSUE TITLE
[feature request] Make Overlap factor, Bridge spacing, etc. tunable

### ISSUE THREAD

**Issue by Vicious-one** [alexrj/Slic3r#2500]
This should enable to get closer to perfection (proper single wall width and smooth infill at the same time) with various materials, like plywood, trimmer line nylon, no-name ABS with abnormal viscosity.

Maybe this can also help to reduce overextrusion problems and nozzle drag near perimeters when solid rectilinear infill is used in fast accelerated prints.

This phenomenon causes some people to over-tune K and K2 advance parameters as described in Sailfish firmware manual, but they are not aware that Slic3r's overlap math gives quite different results from skeinforge that was originally used to slice those infamous calibration boxes.

Advance overtuning can cause critical underextrusion on sharp turns and small perimeters while maintaining seemingly proper infill, which is a little freaking frustrating.

**Comment by alexrj** [comment]
I don't like starting from solutions. I always start from problems. I analyze them, I discuss them, I find potential causes and then finally make hypothesis about possible solutions.
Can we discuss on a concrete test case? With pictures, files, configuration files, tests.

**Comment by Vicious-one** [comment]
Working on that...

**Comment by curiouspl2** [comment]
i +1 on that one. 
i think 'advanced' settings are all about this, and it allows fine-tuning prints, experimenting, testing... 

perhaps warnings could be put on settings which are likely to disappear with rebuild of flow logic code, but this still helps a lot people who just want to experiment and try to nail problems like badly anchored infills, overfilled solid infill (while rest of print is fine) etc. 

groupthink and brainstorming is all about finding solutions together :)

**Comment by lordofhyphens** [comment]
@Vicious-one Did you every get that written up? I see this wasn't updated since.

**Comment by Vicious-one** [comment]
@lordofhyphens Overlap factor is tunable now, and the bridge flow formula has been changed, so the described issue is mostly fixed. I think this ticket can be closed for now.

**Comment by Vicious-one** [comment]
@lordofhyphens Overlap factor is tunable now, and the bridge flow formula has been changed, so the described issue is mostly fixed. I think this ticket can be closed for now.
