### ISSUE TITLE
Pressure advance option retracts the filament

### ISSUE THREAD

**Issue by NilsUUID** [alexrj/Slic3r#2501]
I quickly tested pressure advance option by just activating it on my reprappro tricolour mendel (all other settings unchanged, this included retraction during moves, and retraction during toolchange).
On a small part (tricolour calibration piece by reprappro) with many retract (retraction during honeycomb printing) it ended up retracting more filament that it extruded. At some point no plastic was extruded at all.
I will provide more information when I have more time.
Thanks for this useful option by the way.

**Comment by alexrj** [comment]
Okay, I fixed this.

**Comment by pentaglut** [comment]
Thank you!
