### ISSUE TITLE
Python Script on Mac not executing properly

### ISSUE THREAD

**Issue by rsolorzano44** [alexrj/Slic3r#2504]
Hi Alex,

So I am trying to run a python script off of the post processing in Slic3r. I add executable permission in with with chmod +x and script works. The script even runs properly outside of Slic3r. When I run it in Slic3r I get no error, but the code doesn't not execute. If anyone has had this problem and could get it fixed that would be great.

Thank you,
Ricardo

**Comment by alexrj** [comment]
There's nothing to fix in Slic3r - postprocessing scripts work correctly. I think you haven't read the guidelines before posting, otherwise you would have posted much more information. Otherwise it's just guesswork...
