### ISSUE TITLE
Add Machinekit to G-code flavors

### ISSUE THREAD

**Issue by strahlex** [alexrj/Slic3r#2505]
Currently Slic3r has the option "Mach3/LinuxCNC" for GCode flavor. As Machinekit is fork of LinuxCNC for embedded platform and mainly used for 3D printing it makes sense to add it to the G-Code flavors. 

The output should be the same as for "Mach3/LinuxCNC", particularly the E axis needs to be renamed to A.

**Comment by strahlex** [comment]
Link to the project website: http://www.machinekit.io/

**Comment by strahlex** [comment]
The Mach3/LinuxCNC flavor option uses the P parameter for M1xx codes, however. Machinekit supports the RepRap style S parameter.

Can someone please point me to where the GCode flavors are generated?

**Comment by alexrj** [comment]
@strahlex, it looks like some more codes need to be changed for Machinekit:
https://github.com/strahlex/Machinekit-Slic3r-postprocess/blob/master/postprocess.py

If so, can you update your pull request with the missing bits? Thank you! :)

**Comment by strahlex** [comment]
Ok, I added the retract and unretract commands.

Is there a way to automatically add a M2 command at the end of the GCode file? The M2 is necessary for all Machinekit flavour GCode files.

**Comment by strahlex** [comment]
Ok I found it. I added a flavour specific funtion to the GCodeWriter that automatically adds the M2 code at the end of the program.

**Comment by alexrj** [comment]
Merged. Thank you!
