### ISSUE TITLE
The z-axis line is behind any model in 1.2.4-dev or 1.2.5-dev if the number is wrong (Windows 7 64-bit)

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2510]
![image](https://cloud.githubusercontent.com/assets/9621044/5658324/4d85e34c-9743-11e4-97ab-5e87ed9ce2de.png)

I saw 1.2.5 was written in a thread before (https://github.com/alexrj/Slic3r/issues/2480) but the latest version says 1.2.4. at the bottom of the window. Is this a mistake?

![screen shot 01-08-15 at 03 06 pm](https://cloud.githubusercontent.com/assets/9621044/5658771/191e40d8-974b-11e4-998c-305541aeb376.JPG)

**Comment by alexrj** [comment]
Thank you, I fixed the rendering of the Z axis.
