### ISSUE TITLE
1.2.4-dev: Plater is saving STLs in the air again

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#2512]
Original files: 
http://www.thingiverse.com/download:241326
http://www.thingiverse.com/thing:262121

Added two copies of the second item and one of the first, rotated the first to make it flat on the bed (-90degree rotate in Y dir), and then saved as an STL. Added the exported stl and the two ducts were hanging in the air.

Export the STL, clear the plate and add the exported STL. The two tall parts should be in the air. 

Current workaround is to split the STL, which puts everything on the plate properly again.

Resulting STL:
STL: http://www.2shared.com/file/SHlNrmUd/fan.html

**Comment by lordofhyphens** [comment]
Remember the second download button is the correct one, first (larger) one is an ad.

**Comment by alexrj** [comment]
:(

**Comment by lordofhyphens** [comment]
Not trying to make life harder for you :)
I'm in #slic3r if you need to chat directly about it.

**Comment by alexrj** [comment]
Heh, I really appreciate your reports. Sad face was because I was hoping this issues about floating models were fixed.

**Comment by lordofhyphens** [comment]
If it helps, the models aren't floating in the gcode export.

**Comment by alexrj** [comment]
Fixed!

**Comment by lordofhyphens** [comment]
Time to look for more bugs then :D

**Comment by alexrj** [comment]
Heh :P
