### ISSUE TITLE
Overlapping gap fill

### ISSUE THREAD

**Issue by Vicious-one** [alexrj/Slic3r#2513]
Sometimes Slic3r generates a self-overlapping gap fill. 
The problem may disappear when object orientation is changed or slicing resolution is manually limited.

![gap-overlap](https://cloud.githubusercontent.com/assets/10331220/5673727/4b0c4390-97b1-11e4-9f21-e2c239466059.png)

Example model with bugged top slice, config, STL and G-code are here:
http://vserv.sinp.msu.ru/temp/gap-overlap.tar.gz

**Comment by alexrj** [comment]
@Vicious-one, I'm actually checking your G-code file but I can't find any overlap in the uppermost layer… can you help me find where it is?

**Comment by Vicious-one** [comment]
Line 9900:

G1 E3510.09983 F1200.00000
G1 X-8.593 Y30.121 E3510.77640 F1800.000
G1 X23.045 Y30.102 E3511.44790

**Comment by alexrj** [comment]
This should be fixed by #2836

**Comment by Vicious-one** [comment]
Seems fixed, but I'll test this on some more hardcore manifestations, of which I already have plenty.

**Comment by alexrj** [comment]
Okay, thank you. Feel free to report them!
