### ISSUE TITLE
1.2.4-dev: Plater auto-arrange is placing models on top of each other

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#2514]
STLs:
http://www.thingiverse.com/download:241326
http://www.thingiverse.com/thing:262121

Add both, rearrange fan_mount by -90 around Y. 

I think it has something to do with the fact that the rotate-point of the bracket model is above the plate, because if you rotate it 180degrees, the autoarrange puts them very far apart. 

Click "arrange".

The bracket will be on top of the duct.

**Comment by alexrj** [comment]
Hmm, I can't reproduce this one with your instructions... are you sure you did `git pull` after my previous fix?

**Comment by lordofhyphens** [comment]
Yes. It was the first thing I did after I noticed the fix for floating
objects was in. I'll try again later.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
Well, did a new pull and I couldn't repro on 28d7b0dba69de87e685c66e9dab135916e19ce88.

**Comment by alexrj** [comment]
That's good news - thank you
