### ISSUE TITLE
[feature request] move only above previously printed stuff

### ISSUE THREAD

**Issue by St0rmingBr4in** [alexrj/Slic3r#2529]
When printing ninjaflex or other flexible filament, the retraction setting can't be used. Unfortunately, those type of filaments are known for there oozing problems. Therefore, one is forced to clean up all the residue left in mid air. (particularly difficult considering ninjaflex's strength) It would be great if there was a feature which would restrict the extruder moves only above something already printed. That would prevent spider webs from appearing all over the place, at the cost of the print speed. (not really an issue when printing flexible filaments)

**Comment by alexrj** [comment]
Yes, that feature exists and it's called *Avoid crossing perimeters*.
