### ISSUE TITLE
Unexpected boundary detection/bridging

### ISSUE THREAD

**Issue by sirkha** [alexrj/Slic3r#2533]
I am experiencing some issues where on a couple of layers, Slic3r doesn't properly detect the edge of a part, and generates solid infill where there should be empty space.

Currently using Slic3r 1.2.5
Slic3r settings: https://github.com/sirkha/MotoX1ChargeCase/blob/master/Slic3rPrintSettings.ini
Part (Its an AMF with a modifier and some specific part settings): https://github.com/sirkha/MotoX1ChargeCase/blob/master/X1ChargeCase-inverted.amf

![partwin](https://cloud.githubusercontent.com/assets/2826011/5708587/104bd8fc-9a58-11e4-82c4-c0310ee8d0b4.png)

![1050](https://cloud.githubusercontent.com/assets/2826011/5708589/104cda36-9a58-11e4-942a-ff72af674846.png)
On this layer (at 10.50 mm), it fills the hole in the center of the image, when its not supposed to.
![1065](https://cloud.githubusercontent.com/assets/2826011/5708586/104b8672-9a58-11e4-8df7-fa06c918b525.png)
On the next layer, its fine.
![1080](https://cloud.githubusercontent.com/assets/2826011/5708588/104c1344-9a58-11e4-8e17-01618efeac3f.png)
The layer after that has the issue again, but all other layers are fine.

**Comment by sirkha** [comment]
A couple of notes on the model and desired results:
Case_Body_inverted.stl is the main part that I am trying to get. I am using Partial Support to support a specific part of the end result. I have a dual-extruder setup, and will be printing Case_Body_inverted.stl using Ninjaflex, and everything else with HIPS, which I am going to dissolve away later. The modifier, Hex_Window.stl is setup so that its enclosed volume will not have a top or bottom infill, giving a see-thru hexagonal grid in that area.

I think the issue is how the modifier changes some of the perimeters. With just Case_Body_inverted.stl, i have no issues. As soon as I add the modifier to that (even without the support) i begin to see the issues I am having.

**Comment by lordofhyphens** [comment]
Looks fixed to me by loading your amf in 1.3.0-dev 90395f93940410093244e9cfcaf3dce407ddc811
![image](https://cloud.githubusercontent.com/assets/31754/24077319/52067e2c-0c17-11e7-8bf7-ebd9d7739cf8.png)
