### ISSUE TITLE
Correct value of retract-length-toolchange?

### ISSUE THREAD

**Issue by adius** [alexrj/Slic3r#2541]
In [PrintConfig.hpp#L359](https://github.com/alexrj/Slic3r/blob/47e4e8bb66740af791e56b36f0ecb67143a94b3b/xs/src/libslic3r/PrintConfig.hpp#L359) it gets set to 10 but the documentation states that its default value is 1.

Which one is correct?

**Comment by alexrj** [comment]
Thank you, the output of `--help` contained wrong values. 10mm is the default value.
