### ISSUE TITLE
Support material Skirt issues

### ISSUE THREAD

**Issue by sirkha** [alexrj/Slic3r#2544]
Problem 1: When generating automatic support material, some times a layer just for support material is generated in between the normal layers of the print. I am not sure if this is by design, but either way, the skirt is not on that layer in the tool path preview, but in the G-code it is. The problems with this are two-fold: the skirt basically tries to print twice in the same place which for me has resulted in skirts getting torn off the bed, and also has caused the extruder to jam, as too much back pressure is created and the hobbed bolt wears a hole in the fillament.

Especially of note is that the skirt isn't shown in the toolpath preview on these layers, but it does exist in the G-Code.

Example stl: http://www.thingiverse.com/download:67468

Example config and g-code below.

**Comment by sirkha** [comment]
I am having both these problems with slic3r version 1.2.0 through 1.2.5:

**Comment by alexrj** [comment]
In the guidelines it's clearly written that multiple distinct things should not be mixed in a single report.
It's also written that you need to provide some required things in order to reproduce the issues. Can you please read the guidelines and adapt this one? Otherwise it's very unlikely that your problems get fixed.

**Comment by sirkha** [comment]
Config file used
=========
    # generated by Slic3r 1.2.5 on Thu Jan 15 18:42:20 2015
    avoid_crossing_perimeters = 0
    bed_shape = 0x0,300x0,300x300,0x300
    bed_temperature = 90
    bottom_solid_layers = 3
    bridge_acceleration = 0
    bridge_fan_speed = 0
    bridge_flow_ratio = 1.5
    bridge_speed = 18
    brim_width = 0
    complete_objects = 0
    cooling = 1
    default_acceleration = 0
    disable_fan_first_layers = 1
    dont_support_bridges = 1
    duplicate_distance = 6
    end_gcode = T0 ; Select 1st extruder\nM104 S0 ; turn off E0 nozzle temperature\nT1 ; Select 2nd extruder\nM104 S0 ; Turn off E1 nozzle temperature\nM140 S0 ; Turn off bed temp\nG91 ; Relative Move\nG1 Z5 F5000 ;\nG90 ; Absolute Move\nG28 X0  ; home X axis\nG1 Y305 F10800.000; move tray out\nM84     ; disable motors\nT0    ; return to default
    external_fill_pattern = rectilinear
    external_perimeter_extrusion_width = 160%
    external_perimeter_speed = 50%
    external_perimeters_first = 0
    extra_perimeters = 1
    extruder_clearance_height = 20
    extruder_clearance_radius = 50
    extruder_offset = 0x0,0x-53.6
    extrusion_axis = E
    extrusion_multiplier = 1,1
    extrusion_width = 0.4
    fan_always_on = 0
    fan_below_layer_time = 60
    filament_diameter = 2.9,2.95
    fill_angle = 30
    fill_density = 40%
    fill_pattern = honeycomb
    first_layer_acceleration = 0
    first_layer_bed_temperature = 84
    first_layer_extrusion_width = 0.5
    first_layer_height = 0.3
    first_layer_speed = 50%
    first_layer_temperature = 230,230
    gap_fill_speed = 40
    gcode_arcs = 0
    gcode_comments = 0
    gcode_flavor = reprap
    infill_acceleration = 0
    infill_every_layers = 1
    infill_extruder = 2
    infill_extrusion_width = 0.6
    infill_first = 0
    infill_only_where_needed = 0
    infill_speed = 90
    interface_shells = 0
    layer_gcode = 
    layer_height = 0.15
    max_fan_speed = 0
    min_fan_speed = 0
    min_print_speed = 5
    min_skirt_length = 0
    notes = 
    nozzle_diameter = 0.35,0.35
    octoprint_apikey = 
    octoprint_host = 
    only_retract_when_crossing_perimeters = 1
    ooze_prevention = 1
    output_filename_format = [input_filename_base].gcode
    overhangs = 1
    perimeter_acceleration = 0
    perimeter_extruder = 2
    perimeter_extrusion_width = 0.38
    perimeter_speed = 80
    perimeters = 3
    post_process = 
    pressure_advance = 0
    raft_layers = 0
    resolution = 0.01
    retract_before_travel = 0,2
    retract_layer_change = 1,1
    retract_length = 1,2.5
    retract_length_toolchange = 5,30
    retract_lift = 0,0.5
    retract_restart_extra = 0,0.5
    retract_restart_extra_toolchange = 5,10
    retract_speed = 20,20
    seam_position = random
    skirt_distance = 6
    skirt_height = 130
    skirts = 3
    slowdown_below_layer_time = 23
    small_perimeter_speed = 50%
    solid_infill_below_area = 70
    solid_infill_every_layers = 0
    solid_infill_extruder = 2
    solid_infill_extrusion_width = 0.38
    solid_infill_speed = 50%
    spiral_vase = 0
    standby_temperature_delta = -35
    start_gcode = G28 ; home all axes\nG1 Z30 F5000 ; lift nozzle\nG1 X100 F10800 ; \nT0\nM104 S[first_layer_temperature_0]\nM117 Move extruder until material emits from nozzle, then resume.\nM25\nM104 S195\nT1\nM104 S[first_layer_temperature_0]\nM117 Move extruder until material emits from nozzle, then resume.\nM25\nM104 S195\nG28 ; home again\nG1 Z5.0 F5000
    support_material = 1
    support_material_angle = 0
    support_material_enforce_layers = 2
    support_material_extruder = 1
    support_material_extrusion_width = 0.6
    support_material_interface_extruder = 1
    support_material_interface_layers = 2
    support_material_interface_spacing = 0
    support_material_interface_speed = 25%
    support_material_pattern = honeycomb
    support_material_spacing = 2
    support_material_speed = 80
    support_material_threshold = 0
    temperature = 230,230
    thin_walls = 1
    threads = 3
    toolchange_gcode = 
    top_infill_extrusion_width = 0.3
    top_solid_infill_speed = 25%
    top_solid_layers = 3
    travel_speed = 180
    use_firmware_retraction = 0
    use_relative_e_distances = 0
    use_volumetric_e = 0
    vibration_limit = 0
    wipe = 0,0
    xy_size_compensation = 0
    z_offset = 0

**Comment by sirkha** [comment]
First two layers of G-Code 
===============
This illustrates that the skirt is appearing where it doesn't on the toolpath preview.
    ; generated by Slic3r 1.2.5 on 2015-01-15 at 18:44:52

    ; external perimeters extrusion width = 0.24mm
    ; perimeters extrusion width = 0.38mm
    ; infill extrusion width = 0.60mm
    ; solid infill extrusion width = 0.38mm
    ; top infill extrusion width = 0.30mm
    ; support material extrusion width = 0.60mm

    M107
    M190 S84 ; set bed temperature
    G28 ; home all axes
    G1 Z30 F5000 ; lift nozzle
    G1 X100 F10800 ; 
    T0
    M104 S230
    M117 Move extruder until material emits from nozzle, then resume.
    M25
    M104 S195
    T1
    M104 S230
    M117 Move extruder until material emits from nozzle, then resume.
    M25
    M104 S195
    G28 ; home again
    G1 Z5.0 F5000
    G21 ; set units to millimeters
    G90 ; use absolute coordinates
    M82 ; use absolute distances for extrusion
    G92 E0
    T0
    G92 E0
    M109 S230 ; wait for temperature to be reached
    G1 E-1.00000 F1200.00000
    G92 E0
    G1 Z0.300 F10800.000
    G1 X124.239 Y115.505 F10800.000
    G1 E1.00000 F1200.00000
    G1 X126.014 Y113.876 E1.04767 F2400.000
    G1 X129.111 Y112.747 E1.11288
    G1 X132.541 Y112.327 E1.18125
    G1 X133.430 Y112.273 E1.19888
    G1 X166.356 Y112.273 E1.85034
    G1 X167.194 Y112.321 E1.86695
    G1 X170.838 Y112.741 E1.93952 F2400.000
    G1 X173.153 Y113.409 E1.98719
    G1 X175.126 Y114.792 E2.03486
    G1 X176.541 Y116.743 E2.08253
    G1 X177.307 Y120.000 E2.14874
    G1 X177.307 Y180.000 E3.33586
    G1 X176.910 Y182.376 E3.38353
    G1 X175.761 Y184.495 E3.43120
    G1 X173.986 Y186.124 E3.47887
    G1 X170.889 Y187.253 E3.54408
    G1 X167.459 Y187.673 E3.61245
    G1 X166.570 Y187.727 E3.63008
    G1 X133.593 Y187.727 E4.28255
    G1 X132.743 Y187.678 E4.29939
    G1 X129.150 Y187.257 E4.37096
    G1 X126.836 Y186.586 E4.41863
    G1 X124.866 Y185.199 E4.46630
    G1 X123.454 Y183.247 E4.51397
    G1 X122.693 Y180.000 E4.57995
    G1 X122.693 Y120.000 E5.76707
    G1 X123.090 Y117.624 E5.81474
    G1 X124.214 Y115.552 E5.86138
    G1 E4.86138 F1200.00000
    G92 E0
    G1 X124.608 Y115.774 F10800.000
    G1 E1.00000 F1200.00000
    G1 X124.671 Y115.662 E1.00253 F2400.000
    G1 X126.432 Y114.127 E1.04875
    G1 X129.164 Y113.180 E1.10595
    G1 X132.594 Y112.759 E1.17432
    G1 X133.430 Y112.708 E1.19090
    G1 X166.356 Y112.708 E1.84236
    G1 X167.144 Y112.753 E1.85797
    G1 X170.788 Y113.174 E1.93054 F2400.000
    G1 X173.029 Y113.833 E1.97676
    G1 X174.920 Y115.204 E2.02298
    G1 X176.243 Y117.129 E2.06920
    G1 X176.871 Y120.000 E2.12734
    G1 X176.871 Y180.000 E3.31445
    G1 X176.474 Y182.302 E3.36067
    G1 X175.329 Y184.338 E3.40689
    G1 X173.568 Y185.873 E3.45311
    G1 X170.836 Y186.820 E3.51031
    G1 X167.406 Y187.241 E3.57868
    G1 X166.570 Y187.292 E3.59526
    G1 X133.593 Y187.292 E4.24772
    G1 X132.794 Y187.245 E4.26356
    G1 X129.201 Y186.825 E4.33513
    G1 X126.961 Y186.163 E4.38134
    G1 X125.072 Y184.788 E4.42756
    G1 X123.752 Y182.860 E4.47378
    G1 X123.129 Y180.000 E4.53171
    G1 X123.129 Y120.000 E5.71883
    G1 X123.526 Y117.698 E5.76504
    G1 X124.583 Y115.819 E5.80769
    G1 E0.80769 F1200.00000
    G92 E0
    G1 X125.698 Y110.798 F10800.000
    M104 S195 ; set temperature
    T1
    G92 E0
    M109 S230 ; wait for temperature to be reached
    G1 X124.972 Y169.647 F10800.000
    G1 X125.103 Y169.424 E0.00494 F2400.000
    G1 X126.849 Y167.989 E0.04816
    G1 X129.217 Y167.212 E0.09581
    G1 X132.647 Y166.792 E0.16188
    G1 X133.430 Y166.744 E0.17688
    G1 X166.356 Y166.744 E0.80645
    G1 X167.094 Y166.786 E0.82058
    G1 X170.738 Y167.207 E0.89071 F2400.000
    G1 X172.903 Y167.856 E0.93393
    G1 X174.710 Y169.214 E0.97714
    G1 X175.936 Y171.113 E1.02036
    G1 X176.436 Y173.600 E1.06886
    G1 X176.436 Y233.600 E2.21608
    G1 X176.039 Y235.825 E2.25930
    G1 X174.897 Y237.776 E2.30251
    G1 X173.151 Y239.211 E2.34573
    G1 X170.783 Y239.988 E2.39338
    G1 X167.353 Y240.408 E2.45945
    G1 X166.570 Y240.456 E2.47445
    G1 X133.593 Y240.456 E3.10499
    G1 X132.844 Y240.413 E3.11932
    G1 X129.252 Y239.992 E3.18848
    G1 X127.088 Y239.339 E3.23170
    G1 X125.283 Y237.978 E3.27492
    G1 X124.060 Y236.077 E3.31813
    G1 X123.564 Y233.600 E3.36644
    G1 X123.564 Y173.600 E4.51366
    G1 X123.961 Y171.375 E4.55687
    G1 X124.946 Y169.693 E4.59414
    G1 E2.09414 F1200.00000
    G92 E0
    G1 X168.121 Y232.267 F10800.000
    G1 E3.00000 F1200.00000
    G1 X168.121 Y231.721 E3.01043 F1200.000
    G1 X168.879 Y231.721 E3.02492
    G1 X168.879 Y232.479 E3.03940
    G1 X168.121 Y232.479 E3.05388 F1200.000
    G1 X168.121 Y232.319 E3.05693
    G1 X167.686 Y232.319 F10800.000
    G1 X167.686 Y231.286 E3.07670 F1200.000
    G1 X169.314 Y231.286 E3.10784 F1200.000
    G1 X169.314 Y232.914 E3.13898
    G1 X167.686 Y232.914 E3.17012
    G1 X167.686 Y232.372 E3.18050
    G1 X167.250 Y232.372 F10800.000
    G1 X167.250 Y230.850 E3.20960 F1200.000
    G1 X169.750 Y230.850 E3.25740
    G1 X169.750 Y233.350 E3.30520
    G1 X167.250 Y233.350 E3.35300 F1200.000
    G1 X167.250 Y232.424 E3.37070
    G1 X167.553 Y232.197 F10800.000
    G1 X168.528 Y232.017 F10800.000
    G1 X168.583 Y232.049 E3.37190 F1350.000
    G1 E0.87190 F1200.00000
    G92 E0
    G1 X131.450 Y231.721 F10800.000
    G1 E3.00000 F1200.00000
    G1 X131.879 Y231.721 E3.00819 F1200.000
    G1 X131.879 Y232.479 E3.02267
    G1 X131.121 Y232.479 E3.03716 F1200.000
    G1 X131.121 Y231.721 E3.05164
    G1 X131.398 Y231.721 E3.05693
    G1 X131.398 Y231.286 F10800.000
    G1 X132.314 Y231.286 E3.07445 F1200.000
    G1 X132.314 Y232.914 E3.10560
    G1 X130.686 Y232.914 E3.13674
    G1 X130.686 Y231.286 E3.16788
    G1 X131.345 Y231.286 E3.18050 F1200.000
    G1 X131.345 Y230.850 F10800.000
    G1 X132.750 Y230.850 E3.20735 F1200.000
    G1 X132.750 Y233.350 E3.25515
    G1 X130.250 Y233.350 E3.30295 F1200.000
    G1 X130.250 Y230.850 E3.35076
    G1 X131.293 Y230.850 E3.37070
    G1 X131.520 Y231.153 F10800.000
    G1 X131.528 Y232.017 F10800.000
    G1 X131.583 Y232.049 E3.37190 F1350.000
    G1 E0.87190 F1200.00000
    G92 E0
    G1 X131.560 Y174.721 F10800.000
    G1 E3.00000 F1200.00000
    G1 X131.879 Y174.721 E3.00610 F1200.000
    G1 X131.879 Y175.479 E3.02058
    G1 X131.121 Y175.479 E3.03506 F1200.000
    G1 X131.121 Y174.721 E3.04955
    G1 X131.507 Y174.721 E3.05693
    G1 X131.507 Y174.286 F10800.000
    G1 X132.314 Y174.286 E3.07236 F1200.000
    G1 X132.314 Y175.914 E3.10350
    G1 X130.686 Y175.914 E3.13465
    G1 X130.686 Y174.286 E3.16579
    G1 X131.455 Y174.286 E3.18050 F1200.000
    G1 X131.455 Y173.850 F10800.000
    G1 X132.750 Y173.850 E3.20526 F1200.000
    G1 X132.750 Y176.350 E3.25306
    G1 X130.250 Y176.350 E3.30086 F1200.000
    G1 X130.250 Y173.850 E3.34866
    G1 X131.402 Y173.850 E3.37070
    G1 X131.630 Y174.153 F10800.000
    G1 X131.528 Y175.017 F10800.000
    G1 X131.583 Y175.049 E3.37190 F1350.000
    G1 E0.87190 F1200.00000
    G92 E0
    G1 X168.121 Y175.083 F10800.000
    G1 E3.00000 F1200.00000
    G1 X168.121 Y174.721 E3.00692 F1200.000
    G1 X168.879 Y174.721 E3.02140
    G1 X168.879 Y175.479 E3.03588
    G1 X168.121 Y175.479 E3.05037 F1200.000
    G1 X168.121 Y175.135 E3.05693
    G1 X167.686 Y175.135 F10800.000
    G1 X167.686 Y174.286 E3.07318 F1200.000
    G1 X169.314 Y174.286 E3.10432 F1200.000
    G1 X169.314 Y175.914 E3.13547
    G1 X167.686 Y175.914 E3.16661
    G1 X167.686 Y175.188 E3.18050
    G1 X167.250 Y175.188 F10800.000
    G1 X167.250 Y173.850 E3.20608 F1200.000
    G1 X169.750 Y173.850 E3.25388
    G1 X169.750 Y176.350 E3.30168
    G1 X167.250 Y176.350 E3.34948 F1200.000
    G1 X167.250 Y175.240 E3.37070
    G1 X167.553 Y175.013 F10800.000
    G1 X168.528 Y175.017 F10800.000
    G1 X168.583 Y175.049 E3.37190 F1350.000
    G1 E0.87190 F1200.00000
    G92 E0
    G1 Z0.300 F10800.000
    G1 E-27.50000 F1200.00000
    G92 E0
    G1 X180.307 Y174.865 F10800.000
    M104 S195 ; set temperature
    T0
    G92 E0
    M109 S230 ; wait for temperature to be reached
    G1 X165.956 Y123.760 F10800.000
    G1 E10.00000 F1200.00000
    G1 X166.120 Y123.432 E10.00892 F2400.000
    G1 X164.757 Y123.760 E10.04301
    G1 X166.120 Y121.041 E10.11699
    G1 X165.654 Y119.580 E10.15431
    G1 X163.559 Y123.760 E10.26805
    G1 X162.361 Y123.760 E10.29720
    G1 X164.456 Y119.580 E10.41095
    G1 X163.258 Y119.580 E10.44010
    G1 X161.163 Y123.760 E10.55384
    G1 X159.964 Y123.760 E10.58299
    G1 X162.059 Y119.580 E10.69674
    G1 X160.861 Y119.580 E10.72589
    G1 X158.766 Y123.760 E10.83963
    G1 X157.568 Y123.760 E10.86878
    G1 X159.663 Y119.580 E10.98253
    G1 X158.465 Y119.580 E11.01168
    G1 X156.370 Y123.760 E11.12542
    G1 X155.171 Y123.760 E11.15457
    G1 X157.266 Y119.580 E11.26832
    G1 X156.068 Y119.580 E11.29747
    G1 X153.973 Y123.760 E11.41121
    G1 X152.775 Y123.760 E11.44037
    G1 X154.870 Y119.580 E11.55411
    G1 X153.672 Y119.580 E11.58326
    G1 X151.577 Y123.760 E11.69701
    G1 X150.378 Y123.760 E11.72616
    G1 X152.473 Y119.580 E11.83990
    G1 X151.275 Y119.580 E11.86905
    G1 X149.180 Y123.760 E11.98280
    G1 X147.982 Y123.760 E12.01195
    G1 X150.077 Y119.580 E12.12569
    G1 X148.879 Y119.580 E12.15484
    G1 X146.784 Y123.760 E12.26859
    G1 X145.585 Y123.760 E12.29774
    G1 X147.680 Y119.580 E12.41148
    G1 X146.482 Y119.580 E12.44063
    G1 X144.387 Y123.760 E12.55438
    G1 X143.189 Y123.760 E12.58353
    G1 X145.284 Y119.580 E12.69727
    G1 X144.086 Y119.580 E12.72642
    G1 X141.991 Y123.760 E12.84017
    G1 X140.792 Y123.760 E12.86932
    G1 X142.887 Y119.580 E12.98307
    G1 X141.689 Y119.580 E13.01222
    G1 X139.594 Y123.760 E13.12596
    G1 X138.396 Y123.760 E13.15511
    G1 X140.491 Y119.580 E13.26886
    G1 X139.293 Y119.580 E13.29801
    G1 X137.197 Y123.760 E13.41175
    G1 X135.999 Y123.760 E13.44090
    G1 X138.094 Y119.580 E13.55465
    G1 X136.896 Y119.580 E13.58380
    G1 X134.801 Y123.760 E13.69754
    G1 X133.880 Y123.206 E13.72368
    G1 X135.698 Y119.580 E13.82237
    G1 X134.499 Y119.580 E13.85152
    G1 X133.880 Y120.816 E13.88515
    G1 E12.88515 F1200.00000
    G92 E0
    G1 X133.880 Y178.194 F10800.000
    G1 E1.00000 F1200.00000
    G1 X134.859 Y176.240 E1.05315 F2400.000
    G1 X136.057 Y176.240 E1.08230
    G1 X133.962 Y180.420 E1.19605
    G1 X135.161 Y180.420 E1.22520
    G1 X137.256 Y176.240 E1.33895
    G1 X138.454 Y176.240 E1.36810
    G1 X136.359 Y180.420 E1.48184
    G1 X137.557 Y180.420 E1.51099
    G1 X139.652 Y176.240 E1.62474
    G1 X140.850 Y176.240 E1.65389
    G1 X138.755 Y180.420 E1.76763
    G1 X139.954 Y180.420 E1.79678
    G1 X142.049 Y176.240 E1.91053
    G1 X143.247 Y176.240 E1.93968
    G1 X141.152 Y180.420 E2.05342
    G1 X142.350 Y180.420 E2.08257
    G1 X144.445 Y176.240 E2.19632
    G1 X145.643 Y176.240 E2.22547
    G1 X143.548 Y180.420 E2.33921
    G1 X144.747 Y180.420 E2.36836
    G1 X146.842 Y176.240 E2.48211
    G1 X148.040 Y176.240 E2.51126
    G1 X145.945 Y180.420 E2.62500
    G1 X147.143 Y180.420 E2.65415
    G1 X149.238 Y176.240 E2.76790
    G1 X150.436 Y176.240 E2.79705
    G1 X148.341 Y180.420 E2.91080
    G1 X149.540 Y180.420 E2.93995
    G1 X151.635 Y176.240 E3.05369
    G1 X152.833 Y176.240 E3.08284
    G1 X150.738 Y180.420 E3.19659
    G1 X151.936 Y180.420 E3.22574
    G1 X154.031 Y176.240 E3.33948
    G1 X155.229 Y176.240 E3.36863
    G1 X153.134 Y180.420 E3.48238
    G1 X154.333 Y180.420 E3.51153
    G1 X156.428 Y176.240 E3.62527
    G1 X157.626 Y176.240 E3.65442
    G1 X155.531 Y180.420 E3.76817
    G1 X156.729 Y180.420 E3.79732
    G1 X158.824 Y176.240 E3.91106
    G1 X160.022 Y176.240 E3.94021
    G1 X157.927 Y180.420 E4.05396
    G1 X159.126 Y180.420 E4.08311
    G1 X161.221 Y176.240 E4.19685
    G1 X162.419 Y176.240 E4.22600
    G1 X160.324 Y180.420 E4.33975
    G1 X161.522 Y180.420 E4.36890
    G1 X163.617 Y176.240 E4.48265
    G1 X164.815 Y176.240 E4.51180
    G1 X162.720 Y180.420 E4.62554
    G1 X163.919 Y180.420 E4.65469
    G1 X166.014 Y176.240 E4.76844
    G1 X166.120 Y178.419 E4.82150
    G1 X165.117 Y180.420 E4.87596
    M140 S90 ; wait for bed temperature to be reached
    G1 E3.87596 F1200.00000
    G92 E0
    G1 Z0.375 F10800.000
    G1 X165.117 Y187.727 F10800.000
    G1 E1.00000 F1200.00000
    G1 X133.593 Y187.727 E1.17321 F4800.000
    G1 X132.743 Y187.678 E1.17789
    G1 X129.150 Y187.257 E1.19776
    G1 X126.836 Y186.586 E1.21100
    G1 X124.866 Y185.199 E1.22424
    G1 X123.454 Y183.247 E1.23748
    G1 X122.693 Y180.000 E1.25581
    G1 X122.693 Y120.000 E1.58548
    G1 X123.090 Y117.624 E1.59872
    G1 X124.239 Y115.505 E1.61196
    G1 X126.014 Y113.876 E1.62520
    G1 X129.111 Y112.747 E1.64331
    G1 X132.541 Y112.327 E1.66229
    G1 X133.430 Y112.273 E1.66719
    G1 X166.356 Y112.273 E1.84811
    G1 X167.194 Y112.321 E1.85272
    G1 X170.838 Y112.741 E1.87287 F4800.000
    G1 X173.153 Y113.409 E1.88611
    G1 X175.126 Y114.792 E1.89935
    G1 X176.541 Y116.743 E1.91259
    G1 X177.307 Y120.000 E1.93098
    G1 X177.307 Y180.000 E2.26065
    G1 X176.910 Y182.376 E2.27389
    G1 X175.761 Y184.495 E2.28713
    G1 X173.986 Y186.124 E2.30037
    G1 X170.889 Y187.253 E2.31848
    G1 X167.459 Y187.673 E2.33747
    G1 X166.570 Y187.727 E2.34236
    G1 X165.169 Y187.727 E2.35006
    G1 E1.35006 F1200.00000
    G92 E0
    G1 X165.169 Y187.292 F10800.000
    G1 E1.00000 F1200.00000
    G1 X133.593 Y187.292 E1.17350 F4800.000
    G1 X132.794 Y187.245 E1.17790
    G1 X129.201 Y186.825 E1.19777
    G1 X126.961 Y186.163 E1.21061
    G1 X125.072 Y184.788 E1.22344
    G1 X123.752 Y182.860 E1.23628
    G1 X123.129 Y180.000 E1.25237
    G1 X123.129 Y120.000 E1.58204
    G1 X123.526 Y117.698 E1.59488
    G1 X124.671 Y115.662 E1.60771
    G1 X126.432 Y114.127 E1.62055
    G1 X129.164 Y113.180 E1.63643
    G1 X132.594 Y112.759 E1.65542
    G1 X133.430 Y112.708 E1.66002
    G1 X166.356 Y112.708 E1.84094
    G1 X167.144 Y112.753 E1.84528
    G1 X170.788 Y113.174 E1.86543 F4800.000
    G1 X173.029 Y113.833 E1.87827
    G1 X174.920 Y115.204 E1.89110
    G1 X176.243 Y117.129 E1.90394
    G1 X176.871 Y120.000 E1.92008
    G1 X176.871 Y180.000 E2.24976
    G1 X176.474 Y182.302 E2.26259
    G1 X175.329 Y184.338 E2.27543
    G1 X173.568 Y185.873 E2.28827
    G1 X170.836 Y186.820 E2.30415
    G1 X167.406 Y187.241 E2.32314
    G1 X166.570 Y187.292 E2.32774
    G1 X165.222 Y187.292 E2.33515
    G1 E1.33515 F1200.00000
    G92 E0
    G1 X165.222 Y186.856 F10800.000
    G1 E1.00000 F1200.00000
    G1 X133.593 Y186.856 E1.17379 F4800.000
    G1 X132.844 Y186.813 E1.17791
    G1 X129.252 Y186.392 E1.19778
    G1 X127.088 Y185.739 E1.21020
    G1 X125.283 Y184.378 E1.22262
    G1 X124.060 Y182.477 E1.23504
    G1 X123.564 Y180.000 E1.24892
    G1 X123.564 Y120.000 E1.57860
    G1 X123.961 Y117.775 E1.59102
    G1 X125.103 Y115.824 E1.60344
    G1 X126.849 Y114.389 E1.61586
    G1 X129.217 Y113.612 E1.62955
    G1 X132.647 Y113.192 E1.64853
    G1 X133.430 Y113.144 E1.65285
    G1 X166.356 Y113.144 E1.83376
    G1 X167.094 Y113.186 E1.83783
    G1 X170.738 Y113.607 E1.85798 F4800.000
    G1 X172.903 Y114.256 E1.87040
    G1 X174.710 Y115.614 E1.88282
    G1 X175.936 Y117.513 E1.89524
    G1 X176.436 Y120.000 E1.90917
    G1 X176.436 Y180.000 E2.23885
    G1 X176.039 Y182.225 E2.25127
    G1 X174.897 Y184.176 E2.26369
    G1 X173.151 Y185.611 E2.27611
    G1 X170.783 Y186.388 E2.28980
    G1 X167.353 Y186.808 E2.30879
    G1 X166.570 Y186.856 E2.31310
    G1 X165.274 Y186.856 E2.32022
    G1 E1.32022 F1200.00000
    G92 E0
    G1 X166.100 Y180.400 F10800.000
    G1 E1.00000 F1200.00000
    G1 X166.100 Y176.260 E1.02745 F4800.000
    G1 X133.900 Y176.260 E1.24094
    G1 X133.900 Y180.400 E1.26838
    G1 X166.100 Y180.400 E1.48187
    G1 X162.366 Y179.817 F10800.000
    G1 X161.776 Y178.794 E1.48970 F4800.000
    G1 X158.389 Y178.794 E1.51216
    G1 X157.799 Y179.817 E1.51999
    G1 X162.366 Y179.817 E1.55027
    G1 X161.776 Y178.210 F10800.000
    G1 X162.564 Y176.844 E1.56072 F4800.000
    G1 X157.601 Y176.844 E1.59363
    G1 X158.389 Y178.210 E1.60408
    G1 X161.776 Y178.210 E1.62653
    G1 X153.219 Y179.817 F10800.000
    G1 X152.628 Y178.794 E1.63436 F4800.000
    G1 X149.242 Y178.794 E1.65681
    G1 X148.651 Y179.817 E1.66464
    G1 X153.219 Y179.817 E1.69493
    G1 X152.628 Y178.210 F10800.000
    G1 X153.417 Y176.844 E1.70538 F4800.000
    G1 X148.454 Y176.844 E1.73828
    G1 X149.242 Y178.210 E1.74873
    G1 X152.628 Y178.210 E1.77118
    G1 X144.072 Y179.817 F10800.000
    G1 X143.481 Y178.794 E1.77902 F4800.000
    G1 X140.095 Y178.794 E1.80147
    G1 X139.504 Y179.817 E1.80930
    G1 X144.072 Y179.817 E1.83958
    G1 X143.481 Y178.210 F10800.000
    G1 X144.269 Y176.844 E1.85003 F4800.000
    G1 X139.307 Y176.844 E1.88294
    G1 X140.095 Y178.210 E1.89339
    G1 X143.481 Y178.210 E1.91584
    G1 X134.924 Y179.817 F10800.000
    G1 X134.484 Y179.054 E1.92168 F4800.000
    G1 X134.484 Y179.817 E1.92674
    G1 X134.924 Y179.817 E1.92966
    G1 X134.484 Y177.950 F10800.000
    G1 X135.122 Y176.844 E1.93812 F4800.000
    G1 X134.484 Y176.844 E1.94235
    G1 X134.484 Y177.950 E1.94968
    G1 E0.94968 F1200.00000
    G92 E0
    G1 X144.668 Y122.757 F10800.000
    G1 E1.00000 F1200.00000
    G1 X143.481 Y120.700 E1.01575 F4800.000
    G1 X140.095 Y120.700 E1.03820
    G1 X138.907 Y122.757 E1.05394
    G1 X135.521 Y122.757 E1.07639
    G1 X134.484 Y120.961 E1.09015
    G1 X134.484 Y123.156 E1.10470
    G1 X165.516 Y123.156 E1.31044
    G1 X165.516 Y122.757 E1.31309
    G1 X162.963 Y122.757 E1.33001
    G1 X161.776 Y120.700 E1.34576
    G1 X158.389 Y120.700 E1.36821
    G1 X157.202 Y122.757 E1.38396
    G1 X153.816 Y122.757 E1.40641
    G1 X152.628 Y120.700 E1.42215
    G1 X149.242 Y120.700 E1.44460
    G1 X148.055 Y122.757 E1.46035
    G1 X144.668 Y122.757 E1.48280
    G1 X166.100 Y123.740 F10800.000
    G1 X166.100 Y119.600 E1.51025 F4800.000
    G1 X133.900 Y119.600 E1.72374
    G1 X133.900 Y123.740 E1.75118
    G1 X166.100 Y123.740 E1.96467
    G1 E0.96467 F1200.00000
    G92 E0
    G1 Z0.450 F10800.000

**Comment by lordofhyphens** [comment]
Looks alright to me. 
![image](https://cloud.githubusercontent.com/assets/31754/24077499/18c5e3fe-0c1d-11e7-9e25-81df03dfcdce.png)

I'm not seeing weird gcode output either from 1.3.0-dev.

Closing; please provide updated test case if you can't replicate this (http://dl.slic3r.org/dev), attaching files as per https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/
