### ISSUE TITLE
combine multimaterial

### ISSUE THREAD

**Issue by alke** [alexrj/Slic3r#2547]
Hello
I wonder why combine multimaterial is not in the file menu on version 1.2.x 
Ubuntu 14.04

Idont now if this is the right place to ask but try
Sinserly Kent

**Comment by alexrj** [comment]
Because it was decided to remove it.

The same thing can be done with these steps:
* add the first part to the plater
* double click on it
* click "Load part…" to add the other part(s)
* close the dialog
* Export as AMF file (if you want)

**Comment by peterjsp** [comment]
I can export to AMF using the above steps however when I try to reload the file in Slic3r I get the following error...
![2015-06-25_045517](https://cloud.githubusercontent.com/assets/13043352/8346568/9db42b1c-1af6-11e5-8dea-b13706aedf6d.png)
