### ISSUE TITLE
Crash when reading empty STL file

### ISSUE THREAD

**Issue by rbuckland** [alexrj/Slic3r#2557]
Hi, 

Slic3r keeps crashing on import of the below STL.

https://www.dropbox.com/s/b2xwyqmmrgzh0ix/wheel-brace-for-samsonsite-case.stl?dl=0

(it actually may be corrupt :-/ but a good test none the less.. I think sketchup is playing up)
I have tried v1.2.1 and v1.2.5 on Mac OSX 10.10.1

Regards
Ramon

**Comment by alexrj** [comment]
That file is empty:

```
solid wheel-brace-for-samsonsite-case
endsolid wheel-brace-for-samsonsite-case
```

I agree that Slic3r shouldn't crash. I think it's time to handle the parsing errors gracefully :)

**Comment by alexrj** [comment]
Done.
