### ISSUE TITLE
odd perimter fragments on some layers

### ISSUE THREAD

**Issue by fpiesik** [alexrj/Slic3r#2559]
Slic3r Version: 1.2.5
OS: Ubuntu 14.04 64Bit

I think the screenshot explains it sufficiently:
![screenshot](https://cloud.githubusercontent.com/assets/1476763/5792957/0d4010e6-9f31-11e4-82ec-61134adf6c4f.png)

files:
https://www.dropbox.com/sh/qc9rtwu8h7oxyep/AACV_R1dOt3Qy7JVWS1N_mmsa?dl=0

**Comment by alexrj** [comment]
@fpiesik, does 1.2.6 fix this issue?

**Comment by fpiesik** [comment]
Yes it does -Thanks!
