### ISSUE TITLE
v1.2.5 Strange artifacts

### ISSUE THREAD

**Issue by justmyopinion** [alexrj/Slic3r#2561]
Some strange artifacts at the limits of this model
![artifacts](https://cloud.githubusercontent.com/assets/5621573/5793457/5fcb88fa-9f44-11e4-94e8-5e61bd578d4d.JPG)

And specific strange layout of layer at 1mm:
![1mmlayer](https://cloud.githubusercontent.com/assets/5621573/5793458/64aabbfc-9f44-11e4-8c86-7f27e52bac33.JPG)

STL file:
https://www.dropbox.com/s/jz34hlps8fsaqre/Idler_GT2_2mm_lip.STL?dl=0
Config
https://www.dropbox.com/s/ptowwqw8tw3e0n1/artif_config.ini?dl=0

W7/X64

**Comment by alexrj** [comment]
The artifacts in the first screenshot are just rendering errors, don't trust them. They are acute angles not being mitered.

The artifact in the second one is an issue of the Clipper library. I'll investigate it.  Same thing as #2416

**Comment by alexrj** [comment]
Well, the reason for the artifact is that the original STL file has a little spike and that's being propagated in the offsets:

![schermata 2015-01-30 alle 16 30 00](https://cloud.githubusercontent.com/assets/594957/5978078/67b5d3a6-a89d-11e4-91a2-59128ee6d8fc.png)

So it's theoretically correct. But the result is not visually nice and gives the user a feeling that Slic3r is misbehaving, so I'll check whether this is fixable without slowing things down.

**Comment by alexrj** [comment]
Okay, I added a call to the Douglas-Peucker simplification algorithm before generating perimeters. Small performance penalty, sadly.

**Comment by a4jp-com** [comment]
It would be very nice if this could get fixed. Even with a speed penalty it is nicer to see a clean image. At the moment it just looks like the program is playing up.
