### ISSUE TITLE
Configuration UI default change -- Default view for plater?

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#2562]
I see that 3d is the default for the plater. While it's nice, could a Slic3r preference be added to choose the default? The 2D plater shows how far the skirt goes and the 3d doesn't.

**Comment by alexrj** [comment]
Well, the proper solution would be to show the skirt in 3D as well, wouldn't it? :)

**Comment by a4jp-com** [comment]
Yes please ^^

**Comment by lordofhyphens** [comment]
I also find it easier to plater in x/y with the 2D plater. 3d is good to
check for floating parts.

**Comment by gege2b** [comment]
Instead of adding another option, I think that slic3r should remember the last  used view on opening
