### ISSUE TITLE
Solid infill on too many layers

### ISSUE THREAD

**Issue by fpiesik** [alexrj/Slic3r#2565]
Slic3r Version: 1.2.5
OS: Ubuntu 14.04 64Bit

expected result: the solid infill should be only at the top layers
actual result: solid infill is generated on too many layers on the left and righ side of the model.

This is problably because the sides are rounded and there are effectively no top layers:
![image](https://cloud.githubusercontent.com/assets/1476763/5803323/c0893fb6-9ffd-11e4-93e6-b18f900e6823.png)

here is a pictiure of the g-code at less than half heigt, note the solid infil left and right:
![image](https://cloud.githubusercontent.com/assets/1476763/5803236/eb17ba4c-9ffc-11e4-9473-088eb7d4dbcb.png)
Files:
https://www.dropbox.com/sh/sp2nr2o58ojco7b/AAC0JzIdaJLckyfvlqpEIsJxa?dl=0

(I actually don't want to print it in this orientation, but I recognised this incidantially...)

**Comment by justmyopinion** [comment]
Try to adjust your Solid Infill Treshold:  at Printing/Infill/Solid......

**Comment by fpiesik** [comment]
that helped - thanks!
