### ISSUE TITLE
Rectilinear support material not correctly lined up

### ISSUE THREAD

**Issue by Gatulibu** [alexrj/Slic3r#2566]
In recent versions the support material isn't generated correctly:

Version 1.2.5:
![125](https://cloud.githubusercontent.com/assets/1441713/5805735/f9449652-a011-11e4-92f6-0a448d9fe36b.png)

Version 1.1.7 generates correct support:
![117](https://cloud.githubusercontent.com/assets/1441713/5805741/098215bc-a012-11e4-8556-0ce785d8a7ea.png)

example STL, config files, gcode:
https://drive.google.com/folderview?id=0B2EPQumqM4OhN2dobkNnYUFHd00&usp=sharing

**Comment by alexrj** [comment]
Interesting, thank you for that report.

**Comment by simonkuehling** [comment]
I was just writing a new issue on this - but seems like this one covers my findings already.
I'd like to add that the misalignement affects rectilinear as well as rectilinear grid support structures
![layer screenshot](https://www.dropbox.com/s/rrqig6p6kvsi91c/layer-preview-screenshot.png?dl=1)

**Comment by alexrj** [comment]
Fixed, thank you!

![schermata 2015-01-28 alle 19 49 48](https://cloud.githubusercontent.com/assets/594957/5944401/f3267238-a726-11e4-9c1b-5c14fd775d94.png)
