### ISSUE TITLE
Request: Have selected printer setting remain when switching between saved printer settings 

### ISSUE THREAD

**Issue by griffdb** [alexrj/Slic3r#2568]
In Slic3r 1.1.7, when in expert mode, if you select Print or Filament settings, and then select one of the sub menus, such as "Skirt and Brim" or "Cooling", if you switch between the saved settings for that category, the selected sub menu remains, allowing for easy comparision between saved settings.   

By contrast, if you select printer settings, and you select the sub menu "Custom G-code", if you load another saved setting, then the selected menu goes back to "General", making comparisons difficult between the two saved settings of "Custom G-code" or "Extruder 1".  Please implement the loading of saved settings in Printer settings to have the behavior as that of Print and Filament settings.
![1 filament before](https://cloud.githubusercontent.com/assets/10609066/5812678/77ac99c4-a024-11e4-8bf8-a026bb13b4ec.jpg)
![2 filament after](https://cloud.githubusercontent.com/assets/10609066/5812680/77cb0d28-a024-11e4-83f0-497960b2f1bd.jpg)
![3 printer before](https://cloud.githubusercontent.com/assets/10609066/5812681/77cc04a8-a024-11e4-864b-0931f6568c26.jpg)
![4 printer after](https://cloud.githubusercontent.com/assets/10609066/5812679/77c879fa-a024-11e4-81ac-e386baf7c8fb.jpg)

**Comment by griffdb** [comment]
Also, when saving printer settings, please allow the current submenu to remain active.  Currently, when you save the printer settings, the sub menu gets reset to "General".  Please have the behavior be similar to when the Print and Filament settings are saved.  The active submenu remains active.

**Comment by alexrj** [comment]
Good catch, I fixed that.
