### ISSUE TITLE
Ooze prevention tall skirt, always printed with same extruder

### ISSUE THREAD

**Issue by bethebeer** [alexrj/Slic3r#2576]
I have not found a case where this does not happen, 1.2.1 through 1.2.5. I don't believe it is related to my STL files or specific settings. I have ooze prevention enabled but changing any of the default extruder settings in the same tab have no effect on which extruder is used. I am using a Creator Pro. For the tool change code I have "T[next_extruder]". Not sure it that is somehow related. Also, it is the first extruder that always prints the skirt.
Here are my exported settings:

# generated by Slic3r 1.2.5 on Thu Jan 22 12:21:49 2015

[filament:Filaflex Blue]
bed_temperature = 30
bridge_fan_speed = 100
cooling = 1
disable_fan_first_layers = 3
extrusion_multiplier = 1
fan_always_on = 0
fan_below_layer_time = 60
filament_diameter = 1.5
first_layer_bed_temperature = 30
first_layer_temperature = 233
max_fan_speed = 100
min_fan_speed = 100
min_print_speed = 10
slowdown_below_layer_time = 15
temperature = 233

[filament:UM PVA]
bed_temperature = 30
bridge_fan_speed = 100
cooling = 1
disable_fan_first_layers = 3
extrusion_multiplier = 1
fan_always_on = 1
fan_below_layer_time = 60
filament_diameter = 1.73
first_layer_bed_temperature = 30
first_layer_temperature = 201
max_fan_speed = 100
min_fan_speed = 100
min_print_speed = 10
slowdown_below_layer_time = 15
temperature = 201

[presets]
filament = Filaflex Blue.ini
filament_1 = UM PVA
print = creator dual.ini
printer = Creator Pro (DUAL).ini

[print:creator dual]
avoid_crossing_perimeters = 0
bottom_solid_layers = 5
bridge_acceleration = 0
bridge_flow_ratio = 1
bridge_speed = 14
brim_width = 0
complete_objects = 0
default_acceleration = 0
dont_support_bridges = 0
external_fill_pattern = rectilinear
external_perimeter_extrusion_width = 0
external_perimeter_speed = 100%
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 0
fill_angle = 45
fill_density = 28%
fill_pattern = rectilinear
first_layer_acceleration = 0
first_layer_extrusion_width = 0
first_layer_height = 0.1
first_layer_speed = 70%
gap_fill_speed = 14
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 2
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_speed = 14
interface_shells = 1
layer_height = 0.2
min_skirt_length = 0
notes = 
only_retract_when_crossing_perimeters = 1
ooze_prevention = 1
output_filename_format = [input_filename_base].gcode
overhangs = 1
perimeter_acceleration = 0
perimeter_extruder = 2
perimeter_extrusion_width = 0
perimeter_speed = 14
perimeters = 3
post_process = 
raft_layers = 0
resolution = 0
seam_position = random
skirt_distance = 2
skirt_height = 1
skirts = 1
small_perimeter_speed = 100%
solid_infill_below_area = 40
solid_infill_every_layers = 0
solid_infill_extruder = 2
solid_infill_extrusion_width = 0
solid_infill_speed = 100%
spiral_vase = 0
standby_temperature_delta = 1
support_material = 0
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 2
support_material_extrusion_width = 0
support_material_interface_extruder = 2
support_material_interface_layers = 3
support_material_interface_spacing = 0
support_material_interface_speed = 100%
support_material_pattern = pillars
support_material_spacing = 0
support_material_speed = 14
support_material_threshold = 89
thin_walls = 1
threads = 2
top_infill_extrusion_width = 0
top_solid_infill_speed = 100%
top_solid_layers = 5
travel_speed = 130
xy_size_compensation = 0

[printer:Creator Pro (DUAL)]
bed_shape = -114x-75,114x-75,114x75,-114x75
end_gcode = M73 P100 ; end build progress\nG162 X Y F2500; home X and Y axes\nM109 S0 T0; set bed temperature to 0\nM104 S0 T0; set 1st extruder temperature to 0\nM104 S0 T1; set 2nd extruder temperature to 0\nM18; disable all stepper motors\nM70 P5; Display "We <3 Making Things!" message\nM72 P1; Play Ta-Da song\n
extruder_offset = 0x0,0x0
gcode_flavor = sailfish
layer_gcode = 
nozzle_diameter = 0.4,0.4
octoprint_apikey = 
octoprint_host = 
pressure_advance = 0
retract_before_travel = 2,3
retract_layer_change = 1,1
retract_length = 4,2
retract_length_toolchange = 10,10
retract_lift = 0,0
retract_restart_extra = 0,0
retract_restart_extra_toolchange = 4,3
retract_speed = 8,22
start_gcode = ;\n;\n;--SUMMARY--\n;\n;first layer temperature (right) = [first_layer_temperature_0]C\n;first layer temperature (left) = [first_layer_temperature_1]C\n;temperature (right) = [temperature_0]C\n;temperature (left) = [temperature_1]C\n;first layer bed temperature = [first_layer_bed_temperature]C\n;bed temperature = [bed_temperature]C\n;\n;first layer height = [first_layer_height]mm\n;layer height = [layer_height]mm\n;z_offset = [z_offset]mm\n;perimeters = [perimeters]\n;fill density = [fill_density]\n;infill every n layers = [infill_every_layers]\n;skirts = [skirts]\n;brim width = [brim_width]mm\n;raft layers = [raft_layers]\n;support material = [support_material]\n;support material threshold = [support_material_threshold] degrees\n;support material enforced for first n layers = [support_material_enforce_layers]\n;support material extruder = [support_material_extruder]\n;\n;first layer speed = [first_layer_speed]\n;perimeter speed = [perimeter_speed]mm/s\n;small perimeter speed = [small_perimeter_speed]\n;external perimeter speed = [external_perimeter_speed]\n;infill speed = [infill_speed]mm/s\n;solid infill speed = [solid_infill_speed]\n;top solid infill speed = [top_solid_infill_speed]\n;support material speed = [support_material_speed]mm/s\n;gap fill speed = [gap_fill_speed]mm/s\n;travel speed = [travel_speed]mm/s\n;bridge speed = [bridge_speed]mm/s\n;bridge flow ratio = [bridge_flow_ratio]\n;slowdown if layer time is less than = [slowdown_below_layer_time]secs\n;minimum print speed = [min_print_speed]mm/s\n;\n;bottom solid layers = [bottom_solid_layers]\n;top solid layers = [top_solid_layers]\n;\n;\n;-EXTRUSION-\n;\n;filament diameter (right) = [filament_diameter_0]mm\n;nozzle diameter (right) = [nozzle_diameter_0]mm\n;extrusion multiplier (right) = [extrusion_multiplier_0]\n;filament diameter (left) = [filament_diameter_1]mm\n;nozzle diameter (left) = [nozzle_diameter_1]mm\n;extrusion multiplier (left) = [extrusion_multiplier_1]\n;bridge flow ratio = [bridge_flow_ratio]\n;extrusion axis = [extrusion_axis]\n;extrusion width = [extrusion_width]mm\n;first layer extrusion width = [first_layer_extrusion_width]mm\n;perimeter extrusion width = [perimeter_extrusion_width]mm\n;infill extrusion width = [infill_extrusion_width]mm\n;solid infill extrusion width = [solid_infill_extrusion_width]mm\n;top infill extrusion width = [top_infill_extrusion_width]mm\n;support material extrusion width = [support_material_extrusion_width]mm\n;\n;\n;--SUPPORT--\n;\n;raft layers = [raft_layers]\n;brim width = [brim_width]mm\n;support material = [support_material]\n;support material threshold = [support_material_threshold] degrees\n;support material enforced for first n layers = [support_material_enforce_layers]\n;support material extruder = [support_material_extruder]\n;support material extrusion width = [support_material_extrusion_width]mm\n;support material interface layers = [support_material_interface_layers]\n;support material interface spacing = [support_material_interface_spacing]mm\n;support material pattern = [support_material_pattern]\n;support material angle = [support_material_angle] degrees\n;support material spacing = [support_material_spacing]mm\n;support material speed = [support_material_speed]mm/s\n;\n;\n;--EVERYTHING--\n;\n;complete objects = [complete_objects]\n;cooling enabled = [cooling]\n;default acceleration = [default_acceleration]mm/s/s\n;disable fan for first layers = [disable_fan_first_layers]\n;duplicate = [duplicate]\n;duplicate distance = [duplicate_distance]mm\n;duplicate grid = [duplicate_grid]\n;external perimeters first = [external_perimeters_first]\n;extra perimeters = [extra_perimeters]\n;extruder clearance height = [extruder_clearance_height]mm\n;extruder clearance radius = [extruder_clearance_radius]mm\n;extruder offset = [extruder_offset]mm\n;fan always on = [fan_always_on]\n;fan below layer time = [fan_below_layer_time]secs\n;fill angle = [fill_angle] degrees\n;fill pattern = [fill_pattern]\n;gcode arcs = [gcode_arcs]\n;gcode comments = [gcode_comments]\n;gcode flavor = [gcode_flavor]\n;infill acceleration = [infill_acceleration]mm/s/s\n;infill extruder = [infill_extruder]\n;infill first = [infill_first]\n;infill only where needed = [infill_only_where_needed]\n;minimum skirt length = [min_skirt_length]mm\n;only retract when crossing perimeters = [only_retract_when_crossing_perimeters]\n;perimeter acceleration = [perimeter_acceleration]mm/s/s\n;perimeter extruder = [perimeter_extruder]\n;randomize start = [randomize_start]\n;resolution = [resolution]mm\n;retract before travel (right) = [retract_before_travel_0]\n;retract on layer change (right) = [retract_layer_change_0]\n;retract length (right) = [retract_length_0]mm\n;retract length on tool change (right) = [retract_length_toolchange_0]mm\n;retract lift (right) = [retract_lift_0]\n;retract extra distance on restart (right) = [retract_restart_extra_0]mm\n;retract extra on tool change (right) = [retract_restart_extra_toolchange_0]mm\n;retract speed (right) = [retract_speed_0]mm/s\n;retract before travel (left) = [retract_before_travel_1]\n;retract on layer change (left) = [retract_layer_change_1]\n;retract length (left) = [retract_length_1]mm\n;retract length on tool change (left) = [retract_length_toolchange_1]mm\n;retract lift (left) = [retract_lift_1]\n;retract extra distance on restart (left) = [retract_restart_extra_1]mm\n;retract extra on tool change (left) = [retract_restart_extra_toolchange_1]mm\n;retract speed (left) = [retract_speed_1]mm/s\n;rotate = [rotate] degrees\n;scale = [scale]\n;skirt distance = [skirt_distance]mm\n;skirt height = [skirt_height]mm\n;solid fill pattern = [solid_fill_pattern]\n;solid infill below area = [solid_infill_below_area]mm (sq)\n;solid infill every n layers = [solid_infill_every_layers]\n;\n;\n;--------------------\n;\n;\nT0; set primary extruder\nM73 P0; enable show build progress\nM109 S[first_layer_bed_temperature] T0 ; heat bed up to first layer temperature\nM104 S[first_layer_temperature_0] T0 ; set 1st nozzle heater to first layer temperature\nM104 S[first_layer_temperature_1] T1 ; set 2nd nozzle heater to first layer temperature\nM103; disable RPM\nG21; set units to mm\nG162 X Y F9000; home XY axes maximum\nG161 Z F6000; home Z axis minimum\nG92 Z0; set Z to 0\nM132 X Y Z A B; Recall stored home offsets\nG90; set positioning to absolute\nG1 Z10; move Z to waiting height\nG1 X84 Y-73 F6000.000; move to front right corner of bed\nG1 Z0.05 F3000.000; plug up nozzle\nM6 T0; wait for bed and extruder 1 to heat up\nM6 T1; wait for extruder 2 to heat up\nT0; change to primary extruder\nM108 T0 R3; set extruder speed\nG92 E0; set E to 0\nM320; acceleration enabled for all commands that follow\nG1 Z[first_layer_height] F6000.000; move to first layer height\nG1 X84 Y-73 F14000.000; move to front right corner of bed\nG1 X-90 Y-73 E24 F2000.000; extrude a line of filament across the front edge of the bed using the 1st extuder\nG92 E[retract_length]; set E to retraction length defined in printer settings\nG1 E0 F1800; excute reverse extrusion to retract by length defined in printer settings\nG1 Z0 F6000.000; lower nozzle height to 0\nG1 X-95; wipe purged noodle on edge of bed\nG92 E0; set E to 0 for 1st extruder\nT1; switch to 2nd extruder\nG1 Z[first_layer_height] F6000.000; set nozzle to first layer height\nG1 X100 Y-71 F14000.000; move to front right corner of print bed\nG1 X-90 Y-71 E24 F2000.000; extrude a line of filament across the front edge of the bed using the 2nd extuder\nG4 P2000; wait for ooze to slow\nG1 Z0 F6000.000; lower nozzle height to 0\nG1 X-95; wipe purged noodle on edge of bed\nG1 Z[first_layer_height] F6000.000; set nozzle to first layer height\nG1 F14000; ensure fast travel to first print move\nG92 E0; set E to 0 for 2nd extruder\nT0; switch to 1st extruder\nM73 P0; reset build progress to 0\n
toolchange_gcode = T[next_extruder]\n
use_firmware_retraction = 0
use_relative_e_distances = 0
use_volumetric_e = 0
vibration_limit = 0
wipe = 1,1
z_offset = 0

[settings]
autocenter = 1
mode = expert

**Comment by alexrj** [comment]
Well, if you increase the number of skirt loops then other extruders will be used as well. However this is going to be redesigned in a better way and there are many open reports about this here, so stay tuned...
