### ISSUE TITLE
max feed rate axis Z

### ISSUE THREAD

**Issue by c128** [alexrj/Slic3r#2577]
is possible to add in slic3r/speed option max feed option?

when generate code first movement  is G1 Z0.250 F4200  for my printer 500 is the max!

in the marlin firmware max_feed rate is configured but ignored when print

grazie.

**Comment by alexrj** [comment]
You need to configure your firmware correctly, by setting the maximum speed that your machine can use for each axis. The Marlin option to set is DEFAULT_MAX_FEEDRATE.

**Comment by c128** [comment]
ok after set DEFAULT_MAX_FEEDRATE = 3 problem resolved!
