### ISSUE TITLE
Slic3r 1.2.5 : Overhang threshold ne respecte pas les valeurs indiquées.

### ISSUE THREAD

**Issue by bharralure49** [alexrj/Slic3r#2582]
J’ai déjà abordé ce sujet, mais en vain...
Mais je ne désespère pas d’obtenir un jour des éclaircissements sur le comportement surprenant de ce paramètre…

Je rappelle succinctement le disfonctionnement évident de ce paramètre, et comme pour le sujet #2581, je vais pas faire de grand discourt, mais seulement joindre des captures d’écran qui, à mon sens, sont suffisamment explicites…
- Pour obtenir un soutien sous les surplombs dont la pente forme un angle supérieur à 45° (donc à partir de 46° inclus), il faut renseigner 62°.
- Pour obtenir un soutien sous les surplombs dont la pente forme un angle supérieur à 43° (donc à partir de 44° inclus), il faut renseigner 64° (l’angle diminue, mais il faut augmenter la valeur ?).
- Pour obtenir un soutien sous les surplombs dont la pente forme un angle supérieur à 46° (donc à partir de 47° inclus), il faut renseigner 61° (l’angle augmente, mais il faut diminuer la valeur ?).

De plus, les couches 3 ; 4 et 5 sont bien superposées entre elles, mais pas avec la première. Les couches suivantes se superposent entre elles, mais pas avec les couches 3 ; 4 et 5.

Ces disfonctionnements sont visibles sur n’importe quel modèle.

![image](https://cloud.githubusercontent.com/assets/8447219/5880185/80177f4c-a336-11e4-8311-900e69efa902.png)
Modèle utilisé pour le test

![image](https://cloud.githubusercontent.com/assets/8447219/5880193/926a5142-a336-11e4-8cf2-7402c9a74273.png)

![image](https://cloud.githubusercontent.com/assets/8447219/5880198/9ccc6d64-a336-11e4-91a7-e2990c99d60b.png)

![image](https://cloud.githubusercontent.com/assets/8447219/5880201/a7782e06-a336-11e4-9122-742b5f4de666.png)

![image](https://cloud.githubusercontent.com/assets/8447219/5880205/b02c8222-a336-11e4-97ff-0df0b015c875.png)

**Comment by lordofhyphens** [comment]
This has been changed to check unsupported perimeter width in Auto mode. Closing.
