### ISSUE TITLE
slic3r last update error slicing stl with untouch default config

### ISSUE THREAD

**Issue by c128** [alexrj/Slic3r#2584]
./slic3r.pl 
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `GtkRange::activate-slider' of type `gboolean' from rc file value "((GString*) 0x5315f80)" of type `GString'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

slicing file
http://www.thingiverse.com/thing:771

after error need to reboot PC because very slow!

**Comment by alexrj** [comment]
That file is very broken. Not even Netfabb is able to fix it. Slic3r can't do miracles...

**Comment by alexrj** [comment]
(The error itself might be linked to #2569, but the output is garbage because the input is not valid)
