### ISSUE TITLE
Layers skipped in a manifold STL of a Prusa i3

### ISSUE THREAD

**Issue by DiThi** [alexrj/Slic3r#2585]
![http://i.imgur.com/HIxTA2b.png](http://i.imgur.com/HIxTA2b.png)
![http://i.imgur.com/cSI3HI2.png](http://i.imgur.com/cSI3HI2.png)
![http://i.imgur.com/prc0cKb.png](http://i.imgur.com/prc0cKb.png)

STL is "EJE X/Eje X izquierda.stl" in the Prusa i3 Hephestos kit https://static-bqreaders.s3.amazonaws.com/file/Prusa/piecess_Hephestos.zip

I prined it 3 times already thinking it was a hardware problem before I saw it skip actually skip the layers and then checked the generated gcode...

edit: tested with 1.2.2 and 1.2.5

**Comment by DiThi** [comment]
Oddly enough, I don't have that problem when calling Slic3r from Repetier-Host (that screenshot above is made loading the .gcode directly).

**Comment by alexrj** [comment]
I confirm I can reproduce this with 1.2.6-dev and default settings.

**Comment by alexrj** [comment]
I think this is related to the upstream bug in the Clipper library:
http://sourceforge.net/p/polyclipping/bugs/123/

**Comment by alexrj** [comment]
Okay, I fixed this in b1f1893481c744801249d143971b6cf2d27308ef.
It was probably not very related to the mentioned Clipper bug.

![schermata 2015-01-28 alle 13 14 25](https://cloud.githubusercontent.com/assets/594957/5937440/d5e81e74-a6ef-11e4-8402-2d8e67bbf0d2.png)

Thank you for reporting!
