### ISSUE TITLE
1.2.5 Slic3r exports incomplete GCode File

### ISSUE THREAD

**Issue by Taurus1-1** [alexrj/Slic3r#2587]
Hello,

I just gave the new experimental version 1.2.5 a try. 
During printing the first part with v1.2.5's GCode suddenly the printer stopped.
I investigated it and saw that the GCode file is incomplete. The End of the file (approx. the last 10%) is missing. But In the preview window all layers are visible.
When I slice it with 1.1.7 the GCode file is complete.

.stl, config and Gcode can be found here:
https://www.dropbox.com/sh/2wumcreq2qmdqfh/AAAM4g3yD-Bbfsdpl0FBe9wra

I am using Linux Mint 17 x86.

Peter

**Comment by alexrj** [comment]
Thank you, this is fixed as of 1.2.6-dev.
