### ISSUE TITLE
cant set 'no' if an option default 'yes' using slic3r CLI

### ISSUE THREAD

**Issue by KidFeng** [alexrj/Slic3r#2589]
Hi, I found the boolean option could set to 'yes'  like this:

 ```
slic3r --fan-always-on
```

but i cant switch it off by

```
slic3r --fan-always-on no /*not work*/
```
it does not matter for '--fan-always-on' because 'no' by default. 

but it would be a problem with '--extra-perimeters'.

it seem all the boolean options has this problem.

**Comment by alexrj** [comment]
Use `--no-fan-always-on` and `--no-extra-perimeters`

**Comment by KidFeng** [comment]
Great!
