### ISSUE TITLE
Slic3r Crashs with SegFault When Printing Tentacles

### ISSUE THREAD

**Issue by gabosgab** [alexrj/Slic3r#2591]
When printing this object (http://www.thingiverse.com/download:998022), slicer 1.2.5 crashes with a segfault.  Using the default config or a printer specific config, all cases result in a crash.

Process:               slic3r [1876]
Path:                  /Applications/Slic3r.app/Contents/MacOS/slic3r
Identifier:            slic3r
Version:               Slic3r 1.2.5.92 (1.2.5.92)
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           slic3r [1876]
User ID:               501

Date/Time:             2015-01-27 22:06:35.210 -0800
OS Version:            Mac OS X 10.10.1 (14B25)
Report Version:        11
Anonymous UUID:        474DBE37-F2DF-531E-483B-3605B49990BB

Sleep/Wake UUID:       2B11E6B7-C69C-4F16-BB0C-2C1AEB75A4B8

Time Awake Since Boot: 4000 seconds

Crashed Thread:        15

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 0000000000001000-0000000000038000 [  220K] r-x/rwx SM=COW  /Applications/Slic3r.app/Contents/MacOS/slic3r

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x98ba7a2e mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x98ba6ad0 mach_msg + 68
2   com.apple.CoreFoundation      	0x950a6ae6 __CFRunLoopServiceMachPort + 214
3   com.apple.CoreFoundation      	0x950a5ef9 __CFRunLoopRun + 1529
4   com.apple.CoreFoundation      	0x950a5696 CFRunLoopRunSpecific + 390
5   com.apple.CoreFoundation      	0x950a54fb CFRunLoopRunInMode + 123
6   com.apple.HIToolbox           	0x9152f178 RunCurrentEventLoopInMode + 262
7   com.apple.HIToolbox           	0x9152eeb1 ReceiveNextEventCommon + 494
8   com.apple.HIToolbox           	0x9152ecac _BlockUntilNextEventMatchingListInModeWithFilter + 99
9   com.apple.AppKit              	0x9b202d99 _DPSNextEvent + 734
10  com.apple.AppKit              	0x9b2025e1 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 186
11  com.apple.AppKit              	0x9b1f4dac -[NSApplication run] + 907
12  libwx_osx_cocoau_core-3.0.0.0.0.dylib	0x064bb685 wxGUIEventLoop::OSXDoRun() + 277
13  libwx_baseu-3.0.0.0.0.dylib   	0x06b387c6 wxCFEventLoop::DoRun() + 38
14  libwx_baseu-3.0.0.0.0.dylib   	0x06a679ba wxEventLoopBase::Run() + 74
15  libwx_baseu-3.0.0.0.0.dylib   	0x06a27a3f wxAppConsoleBase::MainLoop() + 95
16  Wx.bundle                     	0x05e75e22 wxPliApp::MainLoop() + 50
17  Wx.bundle                     	0x05e1a911 XS_Wx__App_MainLoop(interpreter*, cv*) + 129
18  libperl.dylib                 	0x000e74a6 Perl_pp_entersub + 2294
19  libperl.dylib                 	0x000e5af6 Perl_runops_standard + 22
20  libperl.dylib                 	0x0007542e perl_run + 366
21  slic3r                        	0x00006d2b 0x1000 + 23851
22  slic3r                        	0x000045a5 0x1000 + 13733

**Comment by alexrj** [comment]
Thank you, this was fixed in 1.2.6-dev
