### ISSUE TITLE
Not a source code issue - can't download from slic3r.org page

### ISSUE THREAD

**Issue by WKnak** [alexrj/Slic3r#2592]
Hi, sorry for opening an issue here, can't find other contact form. I can't download slic3r from site, I've tried using chrome and firefox, but url http://dl.slic3r.org/win/ simple don't work, it runs "loading" until timeout. Thanks!

**Comment by lerouxb** [comment]
Same thing with /mac/, btw.

**Comment by gege2b** [comment]
the dl.slic3r.org host seems to be gone

**Comment by WKnak** [comment]
it is working right now.

**Comment by alexrj** [comment]
Yeah sorry, there were server issues...

**Comment by MarkNahabedian** [comment]
It looks like there are server issues again.
