### ISSUE TITLE
1.2.5 Ex: Feature request: Ability to adjust distance between support material and object

### ISSUE THREAD

**Issue by kyrreaa** [alexrj/Slic3r#2594]
When printing with soluble support material it is very usefull to set the distance between object and support to 0 so that the object completely rests on the surface of the support.  This allows for smooth surfaces. It seems to leave about 2 layers regardless... (0.2mm layers, 0.4mm nozzle)

I cannot find this option even with dual setup configured.  If it exists please explain where.

**Comment by alexrj** [comment]
It exists in the 1.2.6 version that will be released soon.
