### ISSUE TITLE
1.1.7 & 1.2.5 weird support generation

### ISSUE THREAD

**Issue by karrack** [alexrj/Slic3r#2596]
the slicer versions i'm using seem to be never able to generate supports correctly. When slicing, slic3r switches to different layer heights which i can't even see a pattern. For instance whe i just take the 5_mm_calibration_steps and slice them with 40% honeycomb infill (infill percentage and pattern doesnt matter): http://www.thingiverse.com/thing:24238
(note: i unchecked "don't support bridges", but the issue will occur with every other support as well)

The first layer is correct (.3mm) but then it will generate a layer at .53mm where only support is printed. it goes on with a layer at 0.6mm (normal model layer height) witout support and then another layer at 0.9 consisting of support and the normal model. next layer is at 1.2mm (model only) followed by 1.27 (support only)
![bild1](https://cloud.githubusercontent.com/assets/10194595/5945140/b0642db8-a72c-11e4-811e-538ec4a6fa5b.png)
![bild2](https://cloud.githubusercontent.com/assets/10194595/5945139/b060c678-a72c-11e4-9ae7-9f2e91e19654.png)
![bild3](https://cloud.githubusercontent.com/assets/10194595/5945138/b05b006c-a72c-11e4-83a3-e7ab727053d0.png)

slic3r 1.1.7 has the same problems except i cant get such nice images

**Comment by oschonrock** [comment]
I can confirm this behaviour of "skipping layers", but I assumed it was a "feature not a bug". ie the skipped layers were designed to make the support "more flimsy". 

It does result in very flimsy "stringy" support. The downside is that they are somewhat "compressable" and "heavy overhangs" will doop slightly.

**Comment by Lenbok** [comment]
It is a feature not a bug. Inspired by: 
http://hydraraptor.blogspot.co.nz/2012/08/peel-able-support.html

**Comment by alexrj** [comment]
Skipping layers… you're misinterpreting. No layers are skipped. You actually have TWO distinct piles of layers: the object ones, and the support ones. Incidentally, they have different heights. But each one of those two piles is *continuous* and each layer is firmly attached to a layer below.

Look at a 3D preview of the object you mentioned above:
![schermata 2015-02-01 alle 10 34 55](https://cloud.githubusercontent.com/assets/594957/5991656/415d1a04-a9fe-11e4-9c02-d5d3b45a3f46.png)

As you see, there's no skipped layer.

Have you actually tried printing?
