### ISSUE TITLE
Slic3r window out of screen

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#2600]
Hi all
Win7 x64
Slic3r 1.2.4-exp (1.2.5-exp is unusable on win7, waiting for the next exp release)

I sometime use Slic3r on a dual screen setup in "extended" mode, so the total resolution is mainScreenX + secondScreenX
And sometimes, I forget to move the Slic3r window back to the main screen before closing it

If I switch back to one screen and then run Slic3r, it opens out of screen

Slic3r saves its windows position in the slicer.ini file, but it doesn't check if the usable aera of the screen is coherent with the saved position

Well, Its not a big deal, and my workaround when this happens is to manually edit the slic3r.ini

**Comment by alexrj** [comment]
Okay, I have fixed this. I hope I didn't break how it works with multiple screens. Let me know.
