### ISSUE TITLE
1.2.5 experimental can't generate svg files correctly

### ISSUE THREAD

**Issue by AndySze** [alexrj/Slic3r#2601]
Trying to slice to svg file. But with the experimental version , I can't get it, seems like blank image.
With the stable version (1.1.7), it's working good.

**Comment by alexrj** [comment]
Okay, I fixed it. Slices were there, but placed outside the SVG viewport.
SVG export needs some serious redesign, though.  What do you use it for?

**Comment by AndySze** [comment]
@alexrj I used for DLP printer. I agree with you SVG export need redesign. Hope you will do that soon.
