### ISSUE TITLE
1.2.5 Seam Alignment Incorrect

### ISSUE THREAD

**Issue by mwiebold** [alexrj/Slic3r#2604]
Version: 1.2.5, 1.1.7
OS: Mac OS 10.10.2

In 1.2.5, with seam alignment set to Aligned it doesn't seem to honor this setting. Slicing FirstCube.stl from the Printrbot setup page ([Firstcube.stl](http://3k8g8c3p564l1zjnb621d3aoii6.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/FirstCube.stl_.zip)), I get the following in 1.2.5:

![1 2 5](https://cloud.githubusercontent.com/assets/2126987/5988377/049d22f2-a923-11e4-9a90-b427668436df.png)

Notice the corners have seams at different places, which do appear on the prints as well. In 1.1.7, I get:

![1 1 7](https://cloud.githubusercontent.com/assets/2126987/5988381/1cf1729a-a923-11e4-8bf1-788fa1ed1e8d.png)

with the seams aligned appropriately. I have tried this on several other STLs and can duplicate it on these as well (all on Mac, 10.10.2).

Configs (should be same on both, nothing changed except opened STL in 1.2.5):

1.1.7:

\# generated by Slic3r 1.1.7 on Sat Jan 31 08:29:49 2015
avoid_crossing_perimeters = 0
bed_size = 150,150
bed_temperature = 60
bottom_solid_layers = 4
bridge_acceleration = 800
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 25
brim_width = 0
complete_objects = 0
cooling = 1
default_acceleration = 800
disable_fan_first_layers = 0
dont_support_bridges = 1
duplicate_distance = 6
end_gcode = M104 S0 ; turn off extruder temperature\nG28 X0  Y0; home X axis\nM84     ; disable motors\n
external_perimeter_speed = 30
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 0x0
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
fan_always_on = 1
fan_below_layer_time = 60
filament_diameter = 1.75
fill_angle = 45
fill_density = 20%
fill_pattern = rectilinear
first_layer_acceleration = 800
first_layer_bed_temperature = 60
first_layer_extrusion_width = 200%
first_layer_height = 0.2461
first_layer_speed = 75%
first_layer_temperature = 200
g0 = 0
gap_fill_speed = 20
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
infill_acceleration = 1000
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_speed = 40
interface_shells = 0
layer_gcode = 
layer_height = 0.1746
max_fan_speed = 100
min_fan_speed = 100
min_print_speed = 10
min_skirt_length = 0
notes = 
nozzle_diameter = 0.4
only_retract_when_crossing_perimeters = 1
ooze_prevention = 0
output_filename_format = [input_filename_base].gcode
overhangs = 1
perimeter_acceleration = 800
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 30
perimeters = 3
post_process = 
print_center = 75,75
raft_layers = 0
resolution = 0
retract_before_travel = 2
retract_layer_change = 1
retract_length = 3
retract_length_toolchange = 10
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 30
seam_position = aligned
skirt_distance = 6
skirt_height = 1
skirts = 3
slowdown_below_layer_time = 30
small_perimeter_speed = 30
solid_fill_pattern = rectilinear
solid_infill_below_area = 70
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0
solid_infill_speed = 40
spiral_vase = 0
standby_temperature_delta = -5
start_gcode = G28 X0 Y0;\nG28 Z0;\nG29;\nG1 Z5 F5000;  \n
support_material = 0
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_extruder = 1
support_material_interface_layers = 3
support_material_interface_spacing = 0
support_material_interface_speed = 100%
support_material_pattern = pillars
support_material_spacing = 2.5
support_material_speed = 30
support_material_threshold = 0
temperature = 200
thin_walls = 1
threads = 8
toolchange_gcode = 
top_infill_extrusion_width = 0.32
top_solid_infill_speed = 30
top_solid_layers = 4
travel_speed = 100
use_firmware_retraction = 0
use_relative_e_distances = 0
vibration_limit = 0
wipe = 0
z_offset = 0

1.2.5:

\# generated by Slic3r 1.2.5 on Sat Jan 31 08:30:30 2015
avoid_crossing_perimeters = 0
bed_shape = 0x0,150x0,150x150,0x150
bed_temperature = 60
bottom_solid_layers = 4
bridge_acceleration = 800
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 25
brim_width = 0
complete_objects = 0
cooling = 1
default_acceleration = 800
disable_fan_first_layers = 0
dont_support_bridges = 1
duplicate_distance = 6
end_gcode = M104 S0 ; turn off extruder temperature\nG28 X0  Y0; home X axis\nM84     ; disable motors\n
external_fill_pattern = rectilinear
external_perimeter_extrusion_width = 0
external_perimeter_speed = 30
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 0x0
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
fan_always_on = 1
fan_below_layer_time = 60
filament_diameter = 1.75
fill_angle = 45
fill_density = 20%
fill_pattern = rectilinear
first_layer_acceleration = 800
first_layer_bed_temperature = 60
first_layer_extrusion_width = 200%
first_layer_height = 0.2461
first_layer_speed = 75%
first_layer_temperature = 200
gap_fill_speed = 20
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
infill_acceleration = 1000
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_speed = 40
interface_shells = 0
layer_gcode = 
layer_height = 0.1746
max_fan_speed = 100
min_fan_speed = 100
min_print_speed = 10
min_skirt_length = 0
notes = 
nozzle_diameter = 0.4
octoprint_apikey = 
octoprint_host = 
only_retract_when_crossing_perimeters = 1
ooze_prevention = 0
output_filename_format = [input_filename_base].gcode
overhangs = 1
perimeter_acceleration = 800
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 30
perimeters = 3
post_process = 
pressure_advance = 0
raft_layers = 0
resolution = 0
retract_before_travel = 2
retract_layer_change = 1
retract_length = 3
retract_length_toolchange = 10
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 30
seam_position = aligned
skirt_distance = 6
skirt_height = 1
skirts = 3
slowdown_below_layer_time = 30
small_perimeter_speed = 30
solid_infill_below_area = 70
solid_infill_every_layers = 0
solid_infill_extruder = 1
solid_infill_extrusion_width = 0
solid_infill_speed = 40
spiral_vase = 0
standby_temperature_delta = -5
start_gcode = G28 X0 Y0;\nG28 Z0;\nG29;\nG1 Z5 F5000;  \n
support_material = 0
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_extruder = 1
support_material_interface_layers = 3
support_material_interface_spacing = 0
support_material_interface_speed = 100%
support_material_pattern = pillars
support_material_spacing = 2.5
support_material_speed = 30
support_material_threshold = 0
temperature = 200
thin_walls = 1
threads = 8
toolchange_gcode = 
top_infill_extrusion_width = 0.32
top_solid_infill_speed = 30
top_solid_layers = 4
travel_speed = 100
use_firmware_retraction = 0
use_relative_e_distances = 0
use_volumetric_e = 0
vibration_limit = 0
wipe = 0
xy_size_compensation = 0
z_offset = 0

**Comment by alexrj** [comment]
Ouch, fixed. Thank you.   That kind of errors will disappear as soon as I finish porting those things to C++.
