### ISSUE TITLE
1.2.6-dev latest commit, crash if First layerheight is 0 during editing of param

### ISSUE THREAD

**Issue by justmyopinion** [alexrj/Slic3r#2605]
W7/x64
If Printing/First Layerheight is changed by clearing edit field an error shows in status (error in new_from_config_width) but if a 0 is added to empty field (ex 0.1) Slic3R crash and exits.

Any STL and  default settings.

**Comment by alexrj** [comment]
I can't reproduce this. I loaded an STL file, then deleted the value in Print Settings -> Layer height
Are you sure you did Build.PL after git pull?

**Comment by justmyopinion** [comment]
I did yes.
but I changed "First layer Height" obviously, sorry
Here is what happened:
![crash](https://cloud.githubusercontent.com/assets/5621573/5989965/60e8f6f8-a99b-11e4-9482-03ef8f823936.JPG)

I start "Perl Slic3R.pl" with default settings.
Drag STL file into plater
Enter Print settings/First Layerheighr. show 0.35
Backspace to clear numerical field.
Try to change FLH to 0.1 and crashes.

**Comment by alexrj** [comment]
Ah okay, now I can reproduce it, thanks :-)

**Comment by alexrj** [comment]
Fixed!  There was no validation for that field.

**Comment by justmyopinion** [comment]
Verified to be solved with latest commit
