### ISSUE TITLE
missing dependencies when building from git in a "clean" environment

### ISSUE THREAD

**Issue by swsch** [alexrj/Slic3r#2607]
I've cleaned out /usr/local/lib/perl5 and let cpanm use ~/perl5.

Slic3r built, but the tests would only run successfully after I manually installed

  * strictures
  * Module::Runtime
  * Devel::GlobalDestruction
  * Import::Into
  * Role::Tiny

I'm not sure if they should be classified as "required" or "recommended", though.

**Comment by alexrj** [comment]
Hm.  Actually those are not Slic3r direct dependencies but they are dependencies of Moo, and are normally installed by cpanm when Moo is installed...

**Comment by swsch** [comment]
dang, another upstream thingie ... but wait for my next one :-)

**Comment by alexrj** [comment]
Heh :-)
But I think that only depends on something specific to your perl environment. Those dependencies *are* installed automatically most of the time...

**Comment by gege2b** [comment]
Try::Tiny (a Moo dependency) was not automatically installed on my linux box

I've mentionned this here : https://github.com/alexrj/Slic3r/issues/2579#issuecomment-71374254
Anyway I've got no other dependency failure
