### ISSUE TITLE
Infill artifacts under vertical extrusions

### ISSUE THREAD

**Issue by Vicious-one** [alexrj/Slic3r#2610]
Somehow, even with solid infill area threshold high enough, solid infill layers have gaps under vertical extrusions (near the edges):
![infill-gaps](https://cloud.githubusercontent.com/assets/10331220/5993297/a6fa76be-aa5c-11e4-9853-bf8a6f7fbb5f.png)

Extruded parts:
![infill-gaps-2](https://cloud.githubusercontent.com/assets/10331220/5993298/aad9ce4c-aa5c-11e4-8fa6-71baf5294b57.png)

STL and config:
http://vserv.sinp.msu.ru/temp/infill-gaps.tar.gz

**Comment by Vicious-one** [comment]
The gaps are not generated on this model when "extra perimeters" are disabled.

**Comment by Vicious-one** [comment]
The problem became much more aggravated with a recent commit:
![extgap-1](https://cloud.githubusercontent.com/assets/10331220/6212445/6c4985e6-b5f6-11e4-9c76-de05217c992a.png)

**Comment by alexrj** [comment]
Fixed as well.
