### ISSUE TITLE
1.2.6 - Filament Settings Revert

### ISSUE THREAD

**Issue by quillford** [alexrj/Slic3r#2612]
The temperature settings under the Filament Settings tab will revert to their previous value if one manually enters a value. Using the increase/decrease arrows will save changes, however.

OS: OS X 10.10.2
slic3r 
![slic3r_and_new_issue_ _alexrj_slic3r](https://cloud.githubusercontent.com/assets/8762862/5993642/5789f7b2-aa0c-11e4-85e8-420078912159.png)
version 1.2.6

**Comment by gege2b** [comment]
works fine on win7 x64

**Comment by alexrj** [comment]
Ouch, that's true.  It's caused by some behavior change in wxCocoa. I usually develop on a machine that has wxCarbon installed so this didn't happen...

**Comment by alexrj** [comment]
Fixed. Thank you for the report...
