### ISSUE TITLE
1.2.6 post-processing scripts error

### ISSUE THREAD

**Issue by Aerospacesmith** [alexrj/Slic3r#2616]
Running post-processing scripts in 1.2.6 gives an error "the configured post-processing script is not executable: check permissions". 
In 1.2.4, the script runs with no issues.

Trying to run the filament-weight.pl script with perl 5.20
Windows 7 x64 (I have full write access given to all folders and files)

**Comment by alexrj** [comment]
Uhm, what operating system?

**Comment by Lenbok** [comment]
I got the same thing on linux, but when I put in the full path to the postprocessing script and saved the settings it is working again.

**Comment by Aerospacesmith** [comment]
i have the full path specified. Here is my output settings: ![capture](https://cloud.githubusercontent.com/assets/5132118/6016131/b9e90eb6-ab42-11e4-8487-dc4b6e434164.PNG)

**Comment by DanNsk** [comment]
I have the issue when i keep script path in quotes, if i remove quotes - that fixes the issue (same config worked in 1.2.4 i think)

**Comment by alexrj** [comment]
Okay, I fixed this, thank you.

(@DanNsk, that's another thing - you need to remove quotes)
