### ISSUE TITLE
1.2.6 Wrong support generated

### ISSUE THREAD

**Issue by Zuborg** [alexrj/Slic3r#2618]
This problem happened if I tilt this complex part (for produce lower quantity of a support plastic).

The first picture present a corner item in a "free space" without any link to the part and without support. This failure is same for any type of support (pillars, honeycomb, etc)
+45 degrees about X axis:
![wrong_pillars1](https://cloud.githubusercontent.com/assets/10492362/5996945/0a5507ac-aade-11e4-87d9-d5665d9ee473.png)

Here problem of a "pillars support": At left side of picture there are top items of pillars without bottom columns. We can see a raft for these pillars at the first layer but no more. At right there is very thin pillar which will be broken with its weight during printing.
-45 degrees about X axis:
![wrong_pillars](https://cloud.githubusercontent.com/assets/10492362/5996907/31cf345c-aadd-11e4-8280-e95f700f2c7e.png)

source stl: https://drive.google.com/file/d/0BwiHfZggx8jHQzNvWENScW1YZ0E/view?usp=sharing

config.ini: https://drive.google.com/file/d/0BwiHfZggx8jHTTl2NUozYW9VUnM/view?usp=sharing

**Comment by alexrj** [comment]
Yeah, definitely ugly support there.  I think pillars is not the best choice at the moment for that kind of model...

**Comment by Zuborg** [comment]
I think really should be used cautiously "pillars" for complex models, especially where the result of the generation of support is difficult to see. However, the problem at the first picture is more serious, as it is not dependent of the type of support.

**Comment by markfinn** [comment]
The first picture issue may be what I'm reporting in #2635

**Comment by MikeFitz73** [comment]
I also have this same problem in the latest 1.26 release.  if I turn my object 45 degrees on x axis for example, support is missing in many areas.
I would like to know if we could add a feature.... would it be possible to be able to setup support Manually, let the user put support in where the user sees necessary?  Like in simplify3d? thank you.
Mike

**Comment by lordofhyphens** [comment]
Looks fixed.
Rectilinear
![image](https://cloud.githubusercontent.com/assets/31754/24077567/9b548d0a-0c1f-11e7-9787-fd0fa2eb23d2.png)

pillars:
![image](https://cloud.githubusercontent.com/assets/31754/24077572/d3d8d546-0c1f-11e7-941a-6cd6eb7c3b26.png)

The narrow pillars are still an issue, but that's an issue of coverage with pillars (those thin areas are the attempt to cover areas that the pillars didn't get).
