### ISSUE TITLE
[1.2.6] Infill/perimeter overlap is not applied with modifier meshes

### ISSUE THREAD

**Issue by Vicious-one** [alexrj/Slic3r#2620]
I've noticed that infill pattern, etc. can be changed with a modifier mesh, but overriding the infill overlap has no effect whatsoever.

**Comment by alexrj** [comment]
Well, modifier meshes work by isolating a portion of the object and generating its own perimeters+infill. In this case, overlap is applied to the combo.

However if the modifier mesh and the main object have the same perimeter settings, a single set of perimeters is generated around both and modifier mesh only defines a portion of the infill. In this case, only the overlap of the main object is used.  I'll look into the possibility of using both overlaps in this case, but I'm afraid that's a good amount of work.

Does this answer your report?

**Comment by Vicious-one** [comment]
Yes, it does (kind of). 
Anyway, this hint allows to accomplish what was intended (enhancing perimeter stitching with sparse infill). 
Closing.

**Comment by Vicious-one** [comment]
Wow, a modifier with [a little] different perimeter parameters also allows to create solid thick walls inside a sparse infill and segment circular perimeters to enhance stitching. And that is a goldmine of neat strength-enhancing tricks. Thanks again!

**Comment by alexrj** [comment]
If you happen to have a test case with pictures, we could make a little tutorial-blog post on that :)

**Comment by Vicious-one** [comment]
Well, I do.

Here's a spoolholder with a bearing that I wanted to be light and a little flexy for bearing insertion, but quite rigid nonetheless.
![spoolholder-3d](https://cloud.githubusercontent.com/assets/10331220/6156405/09313750-b24b-11e4-865c-3231d0a39ab0.png)

Infill settings:
![spoolholder-settings](https://cloud.githubusercontent.com/assets/10331220/6156422/33994de8-b24b-11e4-9fef-92ae62e9c09e.png)


So I've created a cross-shaped modifier mesh whish is a little narrower than the model's walls and changed its infill and perimeter settings:
![spoolholder-modifier](https://cloud.githubusercontent.com/assets/10331220/6156424/3a09efca-b24b-11e4-922b-d2ef25aed7cc.png)

This results in proper sparse infill where needed: 
![spoolholder-bottom](https://cloud.githubusercontent.com/assets/10331220/6156434/4dfa7040-b24b-11e4-8e31-d86bef0282f1.png)

And sparse infill with rigid rips where appropriate:
![spoolholder-ribs](https://cloud.githubusercontent.com/assets/10331220/6156444/5df3cc76-b24b-11e4-8a69-3bcd39e549db.png)
