### ISSUE TITLE
Bridges with holes/saggings

### ISSUE THREAD

**Issue by Lord2Vader** [alexrj/Slic3r#2621]
Hi,

most of the time i print mechanical stuff, which has many overhangs or holes with saggings/sink (sorry iam german i dont know the word for it).

Well. The picture tells it. There is a hole in the middle of a sink and slic3r does only form the bridges in one direction/dimension, so only the part which travels beside the hole gets bridged correctly.
Maybe you would say print it upside down but in many cases this is not possible due to overhang/shrinkingproblems

![sink](https://cloud.githubusercontent.com/assets/10619572/6007714/93229a20-ab1c-11e4-9e3d-43e5640f685f.png)

Also when perimeters first is activated (or NOT infill first) then the inner perimeter of the hole gets printed in mid air.

Here another pic:
![sink2](https://cloud.githubusercontent.com/assets/10619572/6007756/f70b4bc2-ab1c-11e4-8155-7f0459bd06be.png)

**Comment by alexrj** [comment]
Well… you need support material.  No other solutions :-)

(or you can put a membrane in your model, that you can easily drill out after printing)

**Comment by nophead** [comment]
Or you might be able to use the technique described here:
http://hydraraptor.blogspot.co.uk/2014/03/buried-nuts-and-hanging-holes.html.
Not sure if it works with Slic3r.

On 2 February 2015 at 20:15, Alessandro Ranellucci <notifications@github.com

**Comment by alexrj** [comment]
Also, a related idea was discussed in #254

**Comment by Lord2Vader** [comment]
Well how about bridging besides the hole and the overlapp-bridging on the same layer in the other direction? How could that not be possible?

**Comment by lordofhyphens** [comment]
You still need to place that perimeter and attach it to something that isn't in free space (aka support).
