### ISSUE TITLE
[Feature Request] Center view on the build plateform on 3D & 3D Preview tabs

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#2622]
Hi there

I'm testing the 1.2.6-exp64 on Win7 x64 right now
so far, it's way better and _stable_ than the 1.2.5, but I keep testing

When playing with the 3D Preview, I don't know exactly why, I've completely lost the build surface... Zooming, dragging, panning in any way doesn't helped me to restore the view

So, an interesting feature would be to add a way (maybe a double-click or a right-click menu) to center the view back on the build plateform in 3D and 3D preview tabs

**Comment by alexrj** [comment]
We now have menu commands for this. Thank you!
