### ISSUE TITLE
MAX Threads global setting

### ISSUE THREAD

**Issue by qharley** [alexrj/Slic3r#2629]
Sent a profile to a friend, and it kept crashing his system.  Came down to my printing profile specifying too many threads.

We need a global maximum number of threads allowed even if the printing profile specifies more.  This could be in the <File><Preferences> menu.  If set to zero, it should take the specified number of threads as before.

**Comment by whosawhatsis** [comment]
Is there any reason the number of threads shouldn't be a preferences setting rather than a profile setting?

**Comment by lordofhyphens** [comment]
On 02/05/2015 12:54 AM, whosawhatsis wrote:
>
> Is there any reason the number of threads shouldn't be a preferences 
> setting rather than a profile setting?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alexrj/Slic3r/issues/2629#issuecomment-73002627>.
>
Unless there are side effects to the threadcount, I don't think so.

-- 
--Joseph Lenox, BS, MS
I'm an engineer. I solve problems.

**Comment by alexrj** [comment]
Yes @whosawhatsis, it should be there.  It's in the print settings because it's way older than the Preferences window itself :-)

**Comment by qharley** [comment]
Sounds good!

**Comment by harriv** [comment]
I think the real question here is why it crashed? There may be some problems in the code if specific thread count crashes the program.

**Comment by qharley** [comment]
My guess is that it did not crash in slic3r... Used up all the ram, and
computer froze

**Comment by alexrj** [comment]
Thread number was moved to application preferences. We can close this one. :)
