### ISSUE TITLE
Infill/Perimeter Overlap Overlapping Too Much (v. 1.2.6)

### ISSUE THREAD

**Issue by rf1k-mjh11** [alexrj/Slic3r#2632]
The new "Infill/perimeters overlap" function seems to equate a value of 0% as a 50% overlap.

In other words, an overlap setting of 50% will position the infill bead at the exact same spot as the bead from the perimeter.  I would consider this a 100% overlap.

Playing around with the new function, I set the overlap to 65% and the preview functions of both Slic3r and Repetier Host showed an overlap of more than 100%, i.e. the infill was starting to show up outboard of the perimeter.
Conversely, an overlap value of -55% shows both the infill and perimeters still kissing each other.  Some may be the result of display, calculation or rounding errors.  But the two beads are barely touching, so I would consider that an overlap of 0%

I hope I explained this understandably. 

mjh11

**Comment by Lord2Vader** [comment]
Yep can confirm that.
Just printing with 25% overlap and the perimeter is allmost completally printing over the infill!

**Comment by alexrj** [comment]
Okay, I changed that.

**Comment by epoxi** [comment]
Confirmed on *1.2.7-dev* also, but now differs from what @rf1k-mjh11 says:

**0% Overlap** - No overlap at all
![screenshot from 2015-04-02 00 45 07](https://cloud.githubusercontent.com/assets/1245806/6957455/95d185c8-d8d1-11e4-9c27-922ba66a59e9.png)

**50% Overlap** - Almost there...
![screenshot from 2015-04-02 00 47 02](https://cloud.githubusercontent.com/assets/1245806/6957474/cf95e7ea-d8d1-11e4-8464-cc8676d766d3.png)

**100% Overlap** - Touching.
![screenshot from 2015-04-02 00 48 32](https://cloud.githubusercontent.com/assets/1245806/6957507/39b60010-d8d2-11e4-826e-78cf146bc97b.png)
![screenshot from 2015-04-02 00 50 34](https://cloud.githubusercontent.com/assets/1245806/6957513/4b48feae-d8d2-11e4-8c3b-8591607050d4.png)

***115% Overlap*** - I think its the *15%* meant to be *default*
![screenshot from 2015-04-02 00 52 03](https://cloud.githubusercontent.com/assets/1245806/6957525/8aeafe4a-d8d2-11e4-9540-7e2840d8079e.png)
![screenshot from 2015-04-02 00 52 45](https://cloud.githubusercontent.com/assets/1245806/6957530/979789b0-d8d2-11e4-9286-62eccdb390ca.png)
