### ISSUE TITLE
1.2.6 x64 - Sequential printing not working

### ISSUE THREAD

**Issue by thiagopeixoto16** [alexrj/Slic3r#2633]
It is always telling that the extruder will colide.
Ini and STL files on:
https://www.dropbox.com/sh/pqsmt90pyutrkib/AACOamcNYLzAAFOtbWWeA6zna?dl=0

This is the image:
![image](https://cloud.githubusercontent.com/assets/4227271/6067287/9abe7976-ad5a-11e4-9ff7-689e29634eec.png)

**Comment by zsolta** [comment]
I succeeded slicing them. No error message. Try moving the parts around a bit, that might help.

Slic3r 1.2.6 on Win7/64

**Comment by thiagopeixoto16** [comment]
The Celtic piece is 60% scaled. Did you scaled too?

**Comment by zsolta** [comment]
Nope, just put the parts on the plate, imported the config file and generated the g-code. I'll try the scaled version tomorrow.

**Comment by zsolta** [comment]
It's already tomorrow and I just tried the scaled version. It works, no issues. I positioned the parts manually. Drag them a bit around, that helped me a few times in the past.

**Comment by thiagopeixoto16** [comment]
The funny thing is that the problem is random...  
I tried again and no problems where found... I'm not sure how to reproduce now...
I'll share the configurations if I noticed this again.

**Comment by alexrj** [comment]
I found the issue: the background processing were not restarted when a previous run failed because of object collision.
