### ISSUE TITLE
Possible bridging or bridge detection regression

### ISSUE THREAD

**Issue by Vicious-one** [alexrj/Slic3r#2636]
Strange bridge region detection was encountered when trying to bridge the fins:
![bridge-detection-fail-fins-120](https://cloud.githubusercontent.com/assets/10331220/6078415/64af2ace-ae09-11e4-83f4-ad709159bdd5.png)

1.2.0 binary (bridges detected, but regions are too grown):
![bridge-detection-fail-120](https://cloud.githubusercontent.com/assets/10331220/6078433/9b5b3306-ae09-11e4-9189-642e76527ef2.png)

Current(right bridging region not detected at all, but accidentally the infill is more appropriate):
![bridge-detection-fail-127](https://cloud.githubusercontent.com/assets/10331220/6078449/b97a2edc-ae09-11e4-92ed-d762c137c2ba.png)

STL and config:
http://vserv.sinp.msu.ru/temp/bridge-detection-fail.tar.gz

There is also no way to force bridge detection completely off to work around the issue using this particular model, and "detect bridging perimeters" option also has no noticable effect.

Please note that both 1.2.0 and 1.2.7-dev versions are clearly faulty, but in different ways.

May be related to #2618, #2635 and #2646

**Comment by Vicious-one** [comment]
When trying to avoid the problem by shifting bridges to different layers, I've also noticed than bridge infill pattern angle is not applied to the bridges besides the leftmost one:
![bridge-detection-fail-127-3](https://cloud.githubusercontent.com/assets/10331220/6216629/f471976c-b61c-11e4-885c-542626c44e78.png)
![bridge-detection-fail-127-2](https://cloud.githubusercontent.com/assets/10331220/6216632/f78d31b8-b61c-11e4-9f0c-5f3c86390e6f.png)

**Comment by Vicious-one** [comment]
![yunofix](https://cloud.githubusercontent.com/assets/10331220/6268686/c5979032-b85f-11e4-8f94-c52902ad5dbe.jpg)

**Comment by Vicious-one** [comment]
Seems that bridging infill angle is applied only to one of the bridges:
![bridge-detection-fail-127-4](https://cloud.githubusercontent.com/assets/10331220/6391376/d028d36e-bdc6-11e4-8cea-3ef83a73bf29.png)
![bridge-detection-fail-127-5](https://cloud.githubusercontent.com/assets/10331220/6391377/d02cc906-bdc6-11e4-985d-ee9b2f7f2427.png)
![bridge-detection-fail-127-6](https://cloud.githubusercontent.com/assets/10331220/6391379/d02e96c8-bdc6-11e4-9829-4c4982e1d7e4.png)
![bridge-detection-fail-127-7](https://cloud.githubusercontent.com/assets/10331220/6391378/d02db23a-bdc6-11e4-80d5-c53ef28f0bb2.png)

**Comment by Vicious-one** [comment]
Processing bridge at layer 46:
Angle -1.000000:
Processing bridge at layer 46:
Angle 1.570795:
Processing bridge at layer 106:
Angle 1.396263:
Processing bridge at layer 106:
Angle -1.000000:


BridgeDetector::detect_angle() sets angle to -1 which results in applying default infill angle for current layer.

**Comment by Vicious-one** [comment]
@alexrj -- please revert 379cde30e296482e784825e9df586fe654023c4 so everyone can have proper multiple bridges again!

**Comment by alexrj** [comment]
I fixed that regression. Thank you for reporting it :-)

**Comment by Vicious-one** [comment]
Thanks, now it seems to be working as before.
One question remains, though: the calculated angle seems strange, doesn't it?
![bridge-detection-fail-127-8](https://cloud.githubusercontent.com/assets/10331220/6422385/fe10b9e0-bee8-11e4-934d-a058c83ca1d0.png)
![bridge-detection-fail-127-9](https://cloud.githubusercontent.com/assets/10331220/6422387/0238a6ea-bee9-11e4-8264-c2459e9428b8.png)

**Comment by Vicious-one** [comment]
Okay, having seen the best angle calculation algorithm, the does not seem strange anymore, but the fact that they are not symmetric still does.

Never mind though, I'll just play a little with detection method.

**Comment by Vicious-one** [comment]
I've changed line interval to 1/4 extrusion width and consistently getting more sane results.

(double line_increment = this->extrusion_width/4.0; BridgeDetector.cpp:116)
![div4-1](https://cloud.githubusercontent.com/assets/10331220/6424162/4e042e8a-bf04-11e4-8a04-26610f1e2618.png)
![div4-2](https://cloud.githubusercontent.com/assets/10331220/6424163/4e08e0d8-bf04-11e4-8e07-5ab893083c9a.png)
![div4-3](https://cloud.githubusercontent.com/assets/10331220/6424164/4e0933d0-bf04-11e4-8d91-17cea4973ac4.png)
![div4-4](https://cloud.githubusercontent.com/assets/10331220/6424165/4e0aaa44-bf04-11e4-9c9d-7716bdb32e8d.png)
![div4-5](https://cloud.githubusercontent.com/assets/10331220/6424166/4e0c9c64-bf04-11e4-9254-5007e3bfa981.png)
