### ISSUE TITLE
[input_filename] & [input_filename_base] custom g-code

### ISSUE THREAD

**Issue by jneilliii** [alexrj/Slic3r#2638]
When exporting gcode these custom parameters are not being recognized, as described in [this](https://github.com/alexrj/Slic3r/issues/1507) bug that is reportedly closed.  I've tried with current stable version 1.1.7 and experimental 1.2.6 and they both export the literal variables instead of the replaced strings.  Running on Windows 8.1 64 Bit with 64 Bit versions of both Slic3rs.

**Comment by alexrj** [comment]
Oops, that was lost in the mean time. I fixed it now and also added a regression test so that this is not broken anymore in the future. Thank you for the report.
