### ISSUE TITLE
Slic3r 1.2.6 gives shortcutting perimeters

### ISSUE THREAD

**Issue by hyperair** [alexrj/Slic3r#2639]
I'm not sure what causes this, but I just discovered some odd perimeters generated from a drill bit sharpening jig I was making.

![screenshot23](https://cloud.githubusercontent.com/assets/88355/6092475/ae670c00-af1b-11e4-9b9e-5b93f2111e77.png)
Gcode: https://gist.github.com/554bdfb70695d89c66fc
Config: https://gist.github.com/6f97fcb7641a43fdf79b
STL: https://dl.dropboxusercontent.com/u/169656/sharpening-jig.stl

**Comment by hyperair** [comment]
I verified the generated G-code in gcode.ws, so it's not an issue with the preview.

**Comment by justmyopinion** [comment]
I do not know what is causing the trouble, but if you rotate item  (45deg), problem seems to disappear.

**Comment by Lenbok** [comment]
I see it too. I tried slicing with 1.2.5 and the perimeters are fine, so something between 1.2.5 and 1.2.6.

**Comment by hyperair** [comment]
Hmm, interesting workaround. Thanks!

**Comment by lordofhyphens** [comment]
Any idea if this problem is in 1.2 5 or 1.2.4?

**Comment by hyperair** [comment]
Don't see it in 1.2.5.

**Comment by alexrj** [comment]
Thank you. That looks like an issue in the Clipper library. I isolated the test case and escalated the report to the kind Clipper author:
https://sourceforge.net/p/polyclipping/bugs/126/

**Comment by AngusJohnson** [comment]
Yes, there was a bug in the Clipper code that has now been fixed in [the latest revision on SF](https://sourceforge.net/p/polyclipping/code/HEAD/tree/trunk/).

**Comment by alexrj** [comment]
Thank you @AngusJohnson for coming here :) I'm glad to contribute to achieve more robustness in the already wonderful Clipper library.
