### ISSUE TITLE
1.2.6 crashes on "Check for updates..."

### ISSUE THREAD

**Issue by Lenbok** [alexrj/Slic3r#2641]
I am on 64 bit Ubuntu 14.04. After starting slic3r and selecting Check for updates... slic3r immediately crashes, with the following on the terminal:

$ ./Slic3r/bin/slic3r 
slic3r: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

**Comment by Lenbok** [comment]
BTW, same thing happens with 1.1.7 - I'd just never tried that menu entry before, so wanted to see what it does. Now I know, it just crashes slic3r :-)

**Comment by alexrj** [comment]
Oh, I can reproduce that...

**Comment by alexrj** [comment]
Fixed! Thank you for reporting.
