### ISSUE TITLE
1.2.6 Icons for save / delete presets borken on linux

### ISSUE THREAD

**Issue by Lenbok** [alexrj/Slic3r#2642]
This was fine in 1.2.4, but now the icons have gone all tiny:

![slic3r_tiny_icons](https://cloud.githubusercontent.com/assets/282098/6095149/8150fdc4-afb2-11e4-895a-0d0328211649.png)

This is most likely due to commit 69da8b0999 (ostensibly to make things look better on OS X).

**Comment by alexrj** [comment]
Thank you, I fixed this - it's a weirdness of wxGTK.
