### ISSUE TITLE
Load stl into gui from command line

### ISSUE THREAD

**Issue by chickenchuck040** [alexrj/Slic3r#2644]
Hello, I have been working on integrating slic3r into Openscad. I would like to be able to call slic3r with the stl path in the command line arguments, and have slic3r open the gui, not just slice from the command line. The main reason for the gui would be for the octoprint support, to streamline the printing process.
Unfortunatly, I cannot find a way to do this.

**Comment by chickenchuck040** [comment]
In case you were wondering, Cura works like this.

**Comment by alexrj** [comment]
Hello, done.  You need to supply the `--gui` switch along with file path(s).  No `--gui` switch performs command line slicing as usual instead of launching the GUI.

**Comment by chickenchuck040** [comment]
Thanks
