### ISSUE TITLE
Umlauts in Path Names causes an Error loadin STLs

### ISSUE THREAD

**Issue by callimero** [alexrj/Slic3r#2645]
Umlauts in Path Names (dirs or files) causes an Error loadin STLs. Same file imports fine from a path without Umlauts (öäüßÖÄÜ).

Windows 8.1 64bit. Slic3r 1.2.6 precompiled

**Comment by alexrj** [comment]
Thanks, this should be fixed as of 6185f458157ebca874de0cf1f902ceedec93d2a7

**Comment by alexrj** [comment]
@callimero, can you confirm whether the newly released 1.2.7 fixes the issue you reported? Thank you!

**Comment by callimero** [comment]
Works! Thank you!

Carsten

**Comment by alexrj** [comment]
Thank you @callimero!
