### ISSUE TITLE
【Slic3r 1.2.7-dev】Blend and antializing for the preview window

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2653]
Can you turn on the blend and antializing for the 3D preview window, or can I do it in Windows through my Nvidia card's settings area?

![screen shot 02-11-15 at 08 18 pm](https://cloud.githubusercontent.com/assets/9621044/6146000/3875e012-b22b-11e4-91ae-1de223620fa7.JPG)

**Comment by alexrj** [comment]
I did everything I could. If you have a patch I'll review it.

**Comment by a4jp-com** [comment]
Here is a page with a sample of multi sampling:

http://stackoverflow.com/questions/27953949/make-opengl-polygon-edges-smooth

And another page with more details and better images:

http://www.learnopengl.com/#!Advanced-OpenGL/Anti-Aliasing
