### ISSUE TITLE
1.2.6 experimental: Wrong printing speed applied for first layer infill on top of (suoluble) raft

### ISSUE THREAD

**Issue by jonaskuehling** [alexrj/Slic3r#2656]
Hi Alessandro,

just noticed some slightly off infill speed handling for the first model layer on top of (soluble) support interface. According to my speed settings I guess Slic3r uses bridge speed for the infill as it would be correct in non-soluble-support-mode, although bridge logic is deactivated when configured for the brand new soluble support option.

Perimeters are printed in default speed though as expected. Only for first model layer infill speed there seems to be a tiny issue.

GCODE/CONFIG: https://www.dropbox.com/s/2g8zonybp53cy0p/pulley-clamp-tool.gcode?dl=0

**Comment by alexrj** [comment]
Good catch!  That only happened for first layer above raft.  I fixed it and added a test suite for bridge speed and contact distance.
