### ISSUE TITLE
1.2.6: Unable to set temperature manually (for extruder and bed... minor issue...)

### ISSUE THREAD

**Issue by elkooo** [alexrj/Slic3r#2669]
Hey there, 

I use 1.2.6. since a few days (and I find the print quality with it is reeeeeally nice!!! good job).
Now I just got over a minor issue with the temperatures in the «Filament Settings». Whenever I try to set a new temperature manually by typing in the new value, it switches back to the old temperature as soon as I hit «tab» or click into the next field. I can only adjust the temperature by using the «up» and «down» buttons right to the temperature fields. 
Since I was able to choose different temperatures this way, it's no mayor issue...
I use Slic3r 1.2.6. for Mac on Mac OS 10.8.5 (don't know if this matters...)

Thank you for the great work, keep it up!
Best Regards!

**Comment by alexrj** [comment]
Yeah, very annoying. Closing this as we already have #2612
