### ISSUE TITLE
Feature Req:  Add option for labelling (sub)profiles, so that chosen profiles' labels can be added to output-filename-format

### ISSUE THREAD

**Issue by axs-gentoo** [alexrj/Slic3r#2673]
I find myself needing to play with the output-filename-format a lot now due to the way the output filename format template is used solely for the "Send to printer" option.  I'm fine with this (ie I don't have a need specifically to manually name files each time), but it would be very helpful to me if I could have the selected filament profile as part of the filename.

**Comment by alexrj** [comment]
https://github.com/alexrj/Slic3r/wiki/FAQ#how-can-i-specify-a-custom-filename-format-for-output-g-code-files

Does this work for you?

**Comment by alexrj** [comment]
i.e. `[filament_preset]`

**Comment by axs-gentoo** [comment]
Yes it does, thank you!!  I've been looking through the codebase for quite a while to try and find such an option.  I assume [print_preset] and [printer_preset] are also available?

**Comment by alexrj** [comment]
See the linked FAQ
