### ISSUE TITLE
1.2.6-dev: Expected hole in simple cylinder has bridging strands in center

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#2679]
Title says it all, seeing lines in the output gcode (screencap is from slic3r) on 1.2.6-dev. The print does look like the gcode preview. Also,  there's a 1-line gap on the bottom layer which I don't understand, which is visible in the gcode preview and was in the print.

![screenshot - 02212015 - 10 57 45 am](https://cloud.githubusercontent.com/assets/31754/6315013/1bc29182-b9b9-11e4-840a-b1e98747bed8.png)

STL, configuration, and resultant gcode:
http://www.2shared.com/file/QAW9P3I5/weird-infill.html
Remember to use the second link (first is an advertisement).

OS is Debian/Linux 8 (Jessie)

**Comment by alexrj** [comment]
At least we know that G-code preview is realistic ;-)

**Comment by lordofhyphens** [comment]
Yes, but that is coming from an incorrectly generated tool path :p

**Comment by alexrj** [comment]
Okay, 2655f3f816b07abcb6f3df9b633dcbaec259cac7 fixes this.
