### ISSUE TITLE
Copied parts are supported differently

### ISSUE THREAD

**Issue by dieck** [alexrj/Slic3r#2680]
I just sliced two same parts, copied in RepetierHost, and got very different slicing results for support material.

I would have expected exactly same results, as the same structures would need supporting.

Here a short video showing the differences: http://youtu.be/RssU_5lBVBg?hd=1
The part in question is y slider A2 from http://www.thingiverse.com/download:954921

![support](https://cloud.githubusercontent.com/assets/670562/6326641/0e929c0e-bb54-11e4-888b-4e8454e3aa7a.jpg)

Slic3r 1.2.6 / Repetier Host 1.0.6

**Comment by alexrj** [comment]
Unfortunately AFAIK Repetier-Host merges all copies into a single object and then processes it with Slic3r. So Slic3r doesn't know those are copies of the same object. The current implementation of the pillars support material is coordinate-dependent.

If you copy the object in Slic3r's plater, you'll get the same support structure.
