### ISSUE TITLE
1.2.7-dev: XY Compensation value is inverted? 

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#2685]
Contrary to the tooltip, negative numbers in Advanced->XY Compensation seem to make holes bigger and positive make them smaller.

**Comment by alexrj** [comment]
Actually it's correct :-)
The tooltip says that a negative value shrinks the object. That will make outer dimensions smaller, and holes larger...

**Comment by lordofhyphens** [comment]
Thanks for the confirmation.
