### ISSUE TITLE
No anchor for edges of interior angle (missing internal perimeter?)

### ISSUE THREAD

**Issue by markwal** [alexrj/Slic3r#2686]
I'm running 1.2.7-dev

The layer immediately below:
![image](https://cloud.githubusercontent.com/assets/10781013/6324529/f4eb5958-baef-11e4-88ad-b8719fae49ad.png)

The very next layer:
![image](https://cloud.githubusercontent.com/assets/10781013/6324636/7cf1f5f4-baf1-11e4-9467-bdfb7e59c212.png)

Note that the solid infill layer for the inset over every other honeycomb is unsupported/unanchored.

Should there be a perimeter around that square or perhaps it should decide to do a solid infill layer here?

stl is here: http://www.thingiverse.com/download:1087135  It is the ILoveYouBoxLid.stl part of http://www.thingiverse.com/thing:676630/#files

**Comment by alexrj** [comment]
I don't understand. It looks very okay. The square solid infill is laid over sparse infill. What's the problem? Do you have a picture of the printed object showing the problem?

**Comment by markwal** [comment]
The loops over the infill droop or peel up.  But I see what you mean, as it is laid down it should anchor to the adjacent.  Probably this is fine, I need to recalibrate.
