### ISSUE TITLE
Feature Request: Additional Information in Filament Settings

### ISSUE THREAD

**Issue by LeChuck71** [alexrj/Slic3r#2689]
Hi,

it would be great if some information in the filament settings could be stored e.g.:

Brand Name
WWW Shop / Distributor
Cost per kg

Maybe with this its possible to write a post processing script that puts the costs of the printed gcode in the top most lines of the code so that you can quickly check it

**Comment by quillford** [comment]
That kind of info that doesn't matter when slicing would clutter the UI.

**Comment by alexrj** [comment]
We have "Filament Notes" and "Cost per kg" now.
