### ISSUE TITLE
Modifier is generating undesired internal perimeters

### ISSUE THREAD

**Issue by thiagopeixoto16** [alexrj/Slic3r#2690]
The image shows what I mean by undesired internal perimeters:
![image](https://cloud.githubusercontent.com/assets/4227271/6360494/2c42329a-bc59-11e4-8220-3866fde1eea7.png)
It is there only for few layers, not all.

Here find below the STLs, config and generated G-code:
https://www.dropbox.com/sh/cpec6t0ktotff4q/AADTZXPxuxx6YTx5kzdbCj09a?dl=0

**Comment by Vicious-one** [comment]
That's actually a feature, very useful in some situations. 

If you don't override perimeter-related parameters with a modifier (width, number of perimeters, etc), it should not generate additional perimeters.

If you want to do it anyway, make your modifier mesh fit inside the outer shell.

**Comment by alexrj** [comment]
Yes, as @Vicious-one says the separate perimeters are generated only if the two regions have different perimeter settings. If they have the same settings, a common set of loops is generated.

**Comment by thiagopeixoto16** [comment]
I got it and noted! Thanks!
