### ISSUE TITLE
Skirt printing on half layers

### ISSUE THREAD

**Issue by strikeferret** [alexrj/Slic3r#2695]
Due to drafts, skirt is enabled at 100 layers.

Sliced model with Slic3r 1.1.6, model printed normally but skirt printed on half and full steps, apparent both in Pronterface and the print itself. (Example: layer 3.1mm and 3.3mm correctly print skirt, then later 3.4mm erroneously prints, followed by 3.5mm printing.) This leads to obvious issues regarding nozzle crashing from excess plastic.

Upgraded to Slic3r 1.2.6. Sliced model. Problem persists above 3mm. Slic3r 2d and 3d previews do not display this toolpath, but Pronterface does, and the machine deposits filament in that move. As all gcode is generated by Slic3r, I believe that to be the source of the error.

I hope this can be replicated elsewhere, and post the following settings in the hope that they assist in replicating this. Most other options are default or typical:

Layer Height: 0.2mm
First Layer Height: 0.3mm
Skirt Position: 3mm
Skirt Height: 100 layers
Brim Width: 3mm
Support: Pillars
Support Spacing: 7.5mm

Slicing is done in Slic3r directly, exported as gcode, then imported into Pronterface where the error becomes apparent. I suspect the error occurs between initial pathing for internal rendering and the final export. As such, I doubt it matters, but for completeness sake, I'm using Printrun 2014.3.10 and Marlin firmware on RAMPS 1.4.

**Comment by alexrj** [comment]
Good catch, I fixed this.
