### ISSUE TITLE
printer "has heated bed" option.

### ISSUE THREAD

**Issue by whosawhatsis** [alexrj/Slic3r#2700]
It would be nice to have an option in the printer profile to specify whether the machine has a heated bed. With this option unchecked, all M140/M190 codes would be left out of the gcode, but the same  filament profiles could still be used for a different machine that does have a heated bed to produce those codes.

**Comment by alexrj** [comment]
Will do.  :)

**Comment by jonaskuehling** [comment]
Apologize my dumb question :) but does it hurt at all, if M140/M190 commands are sent to a non-heatbed-printer? Does it try to heat up infinitely then?

Never tried actually :)

**Comment by alexrj** [comment]
Unfortunately yes!  (Or so it was last time it happened to me)

**Comment by whosawhatsis** [comment]
M140 doesn't hurt, but M190 makes it wait for something that will never happen before proceeding, effectively locking up the printer.

**Comment by kefir-** [comment]
Shouldn't the firmware handle (ignore) M190 if there's no heatbed?

**Comment by jonaskuehling** [comment]
That's at least what I would have expected...

**Comment by lordofhyphens** [comment]
There you go.

**Comment by alexrj** [comment]
Merged, we have a "Has heatbed option".
