### ISSUE TITLE
1.2.6 Crash when parameters changed fast while preview updated

### ISSUE THREAD

**Issue by DanNsk** [alexrj/Slic3r#2708]
Hi,

Trying to change several parameters affecting gcode one following another - if i'm not waiting for preview to be updated after each parameter, that crashes application (even not crashes - it just disappears).

Doesn't matter how complex the object - even for just cube 2x2x2 cm.

Win 7 x64

**Comment by justmyopinion** [comment]
Probably same as #2676

**Comment by MikeFitz73** [comment]
maybe we could add a feature that allows us to start the preview update after we are finished making edits to profile.... LIke and update now button.

**Comment by justmyopinion** [comment]
@MikeFitz73 
You may already have that feature in preferences: "background processing" which can be unselected :-)

**Comment by lordofhyphens** [comment]
@DanNsk Please check to see if this is still a problem in 1.2.9a (with or without background processing turned on). Closing for now.
