### ISSUE TITLE
1.2.6 Support half - generated 

### ISSUE THREAD

**Issue by DanNsk** [alexrj/Slic3r#2709]
For some stl files - no matter of support settings no support generated for some sections 

example https://dl.dropboxusercontent.com/u/20891836/Light_Switch_Key_Hanger.stl

![untitled2](https://cloud.githubusercontent.com/assets/1418937/6496395/e1ace158-c298-11e4-91c9-08f198d8327e.png)

**Comment by lordofhyphens** [comment]
Need a configuration and the dropbox link is dead.

Suggest testing again with 1.3.0-dev (note that the automatic support generation has changed, set the threshold to 60%). 

Current -dev builds: http://dl.slic3r.org/dev (pick newest version)
Attaching files:
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

Closing, please comment if you are able to reproduce on 1.3.0 and I will reopen.
