### ISSUE TITLE
slic3r does not start.

### ISSUE THREAD

**Issue by lonelymyp** [alexrj/Slic3r#2710]
slicer 1.2.6, win7 64. 
Some problems with my username?

![err](https://cloud.githubusercontent.com/assets/2085051/6501301/7743149c-c327-11e4-9d48-53ea4f0c7bce.jpg)

**Comment by hippich** [comment]
just a side note - but just because you can use cyrillic in path names (and account names,) doesn't mean you absolutely have to :)

**Comment by alexrj** [comment]
I confirm there are issues with non-ASCII paths on Windows. It's a bit of a pain, but it's my current highest priority.

**Comment by alexrj** [comment]
Okay, I think this commit fixes it.

**Comment by Naesstrom** [comment]
Great, I noticed I had the same problem when trying the 1.2.6 version today. Any idea when 1.2.7 will be out for testing?

**Comment by alexrj** [comment]
@Naesstrom, I released 1.2.7 today. Can you confirm it fixes the issue? Thank you!

**Comment by bubnikv** [comment]
See the resolution to https://github.com/prusa3d/Slic3r/issues/133
