### ISSUE TITLE
retract goes with acceleration that was set the last time. not with the maximum

### ISSUE THREAD

**Issue by lonelymyp** [alexrj/Slic3r#2715]
slic3r 1.2.6
When I set acceleration, it as well affects retract.
I'm set for the perimeter low acceleration and retract done slowly than might be.
according to the g-code acceleration for perimeter placed before going retract. 

example:
![1](https://cloud.githubusercontent.com/assets/2085051/6537064/3d73965e-c464-11e4-9b99-fb46d44e4cf6.jpg)

**Comment by alexrj** [comment]
AFAIK, the `M204 Sx` command does *not* affect retractions (at least in Marlin). According to Marlin documentation, acceleration for retract moves is set using `M204 Tx`.

**Comment by alexrj** [comment]
Also, there's an error in your screenshot. The line you marked as "unretract" is not an unretraction. It's a normal extrusion move. The unretract move is two lines above (`G1 E5.00000 F4800.00000`).

**Comment by lonelymyp** [comment]
Yes, you're right. 
looks like I'm not there looking for the problem.

When enabled the "wipe" retract slower due to the fact that it is synchronized with the movement of the head. Occurs several retracts and one unretract. looks like a different acceleration.
