### ISSUE TITLE
[Feature Request] Provide a way to disable bridge detection

### ISSUE THREAD

**Issue by Vicious-one** [alexrj/Slic3r#2717]
Considering the growing number of reports and evidence on improper bridging in tricky situations, it would be good to have a way to disable bridge region detection for the entire model or within a modifier mesh.

**Comment by lordofhyphens** [comment]
![image](https://cloud.githubusercontent.com/assets/31754/24344083/6f7e2756-128f-11e7-8fa8-6619a757f436.png)

**Comment by lordofhyphens** [comment]
![image](https://cloud.githubusercontent.com/assets/31754/24344191/f8d51276-128f-11e7-9318-153b9a78b31a.png)

**Comment by Vicious-one** [comment]
This option does not affect infill segmentation.

**Comment by lordofhyphens** [comment]
How would disabling it help anything for infill?

**Comment by Vicious-one** [comment]
It's fairly obvious.

![screenshot_2017-03-27_11-43-46](https://cloud.githubusercontent.com/assets/10331220/24348111/9a814bca-12eb-11e7-8b6d-b16656be13f3.png)

![screenshot_2017-03-27_11-43-58](https://cloud.githubusercontent.com/assets/10331220/24348121/a08cc698-12eb-11e7-8237-3635a5d6bc4a.png)

Disabling bridge detection altogether can prevent the obvious anchoring failure.

**Comment by alexrj** [comment]
@Vicious-one, it bridge detection fails the solution is to fix bridge detection. If you have a failing test case, please share it. We will be glad to work on it!

**Comment by Vicious-one** [comment]
@alexrj, here it is.
Bridge detector grows infill regions in order to provide better anchoring, but this strategy is faulty in presence of thin walls. Solid unsegmented infill is clearly better in this case.

![screenshot_2017-03-27_13-40-09](https://cloud.githubusercontent.com/assets/10331220/24352782/f25d90dc-12fb-11e7-8701-60231b608764.png)
![screenshot_2017-03-27_13-40-17](https://cloud.githubusercontent.com/assets/10331220/24352783/f25fa8f4-12fb-11e7-9302-0b64396784a7.png)

STL and config
[bridge-d1.zip](https://github.com/alexrj/Slic3r/files/872202/bridge-d1.zip)
