### ISSUE TITLE
wrong slicing calculation from stl file

### ISSUE THREAD

**Issue by vadimosk** [alexrj/Slic3r#2719]
I adjust one gear from 5mm(5.6) to 4mm(4.6) inner diameter in FreeCad. I only add one 4mm tube into the center in the gear and then with another cylinder drill hole for 3mm bolt for tighten in to the shaft. In all programs (MeshLab, FreeCad, Wings, Cura, Slic3r/3D_preview) this part look OK. 
But when slicing in Slic3r (and also when is part printed) the gear hole looks  from bottom to top:
  0-~2mm -- 5mm diameter
~2-~7mm -- 4mm diameter
~7-   top  --- 5mm diameter.
The 4mm hole is only in the place where is the second hole for shaft bolt, the right is from bottom to top. I try more slicing options but not luck. Then i try Cuda and here is all OK. The hole is 4mm for whole height. 
I try Slicer 1.2.0, 1.2.6 and 1.1.7. The same. I try Cuda and here is slicing OK. But Slic3r is my favorite ;-)

The stl file here:
https://www.dropbox.com/s/vg89cpvwc8ctxr9/4mm_gear_maly_ISSUE.stl?dl=0

![0_bottom](https://cloud.githubusercontent.com/assets/3455534/6545328/34bc7084-c582-11e4-9cff-3242ad887118.jpg)
![1_wings](https://cloud.githubusercontent.com/assets/3455534/6545331/34c37b22-c582-11e4-9777-7e9388718bc5.jpg)
![2_bottom_slic3r](https://cloud.githubusercontent.com/assets/3455534/6545329/34beb5ce-c582-11e4-95a5-fec42a7bd5e7.jpg)
![3_preview1](https://cloud.githubusercontent.com/assets/3455534/6545330/34c038c2-c582-11e4-80d5-52636c203f53.jpg)
![4_preview2](https://cloud.githubusercontent.com/assets/3455534/6545332/34c51a9a-c582-11e4-98cf-6c21f06e338c.jpg)

**Comment by whosawhatsis** [comment]
I can see from the Wings view that it's not manifold. It looks like you started with the shape that Slic3r is creating when it slices and tried to add a tube to decrease the inner diameter, but you didn't perform a boolean union, so there are two separate solid volumes that are overlapping. This is impossible in physical space, so the second volume is being dropped.

Of course, I can't tell from the image if the added geometry even is a closed volume. If it's not manifold, you won't be able to do a boolean union, and there's no possible way for slic3r to figure out what you intended the part to look like.

**Comment by vadimosk** [comment]
I must say i big amateur in 3D modeling. But when i see the straight hole 4mm in model i want print straight hole.  
Maybe help a FreeCad file?
https://www.dropbox.com/s/lldjoimu3p25uh0/4mm_Gear_3%20-maly_ISSUE.fcstd?dl=0

**Comment by xoan** [comment]
As @whosawhatsis says, it's a model problem: in FreeCAD you need to convert meshes to shapes, perform a boolean operation (and optionally, refine the final shape) before to try to export it again.

**Comment by vadimosk** [comment]
OK. Thanks. I try. As i said i amateur in 3D modeling.
