### ISSUE TITLE
[Bug] "Send to printer" fails with filenames containing special characters (e.g. umlauts)

### ISSUE THREAD

**Issue by GHPS** [alexrj/Slic3r#2721]
The problem: The "send to printer" button in Slic3r 1.2.7 is a great and very useful feature. It works like charm except in cases where the filename contains special characters, e.g. German umlauts. While slicing (and saving) the G-Code is possible without any problem, the transfer fails with the error message

"Error while uploading to the OctoPrint server: 500 Server closed connection without sending any data back".

Workaround: Renaming the file fixes the problem.

Test case: Try to send "Test with Umlaut öäü.stl" to printer

Platform:
- Slic3r 1.2.7
- OctoPrint 1.1.1

**Comment by lordofhyphens** [comment]
On 03/08/2015 05:10 PM, GHPS wrote:
>
> The problem: The "send to printer" button in Slic3r 1.2.7 is a great 
> and very useful feature. It works like charm except in cases where the 
> filename contains special characters, e.g. German umlauts. While 
> slicing (and saving) the G-Code is possible without any problem, the 
> transfer fails with the error message
>
> "Error while uploading to the OctoPrint server: 500 Server closed 
> connection without sending any data back".
>
> Workaround: Renaming the file fixes the problem.
>
> Test case: Try to send "Test with Umlaut öäü.stl" to printer
>
> Platform:
>
>   * Slic3r 1.2.7
>   * OctoPrint 1.1.1
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alexrj/Slic3r/issues/2721>.
>
Can you upload the files with umlauts to octoprint already?

-- 
--Joseph Lenox, BS, MS
I'm an engineer. I solve problems.

**Comment by GHPS** [comment]
> Can you upload the files with umlauts to octoprint already?

Yes - uploads work fine, both 'drag-and-drop' and via the upload button. 
Although the file is renamed: 
1) Spaces are substituted by underscore.
2) Umlauts (öäü) are substituted by similar non-umlaut characters (oau).
3) The German s character ('ß') is stripped.

**Comment by alexrj** [comment]
Fixed in 854be6a1861f109763d93974e8eef39db823ea8e
