### ISSUE TITLE
"Cut -> Rotate lower part" places the part under the grid

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#2724]
Hi here
As mentionned in #2475 I got a strange behaviour while cutting an object

1.2.6-exp64 on Win7 x64 

Cutting an object and keeping "rotate lower part" checked will make the lower part of the object to be rotated (thats good) but under the grid.

No matter what  the model or the values are, as long as "rotate lower part upwards" is checked

![meshlab_64bit 09032015 162629](https://cloud.githubusercontent.com/assets/2814966/6557999/9daef6b4-c679-11e4-8be3-6f07c02aa6b7.jpg)

![meshlab_64bit 09032015 163224](https://cloud.githubusercontent.com/assets/2814966/6558077/07db20d0-c67a-11e4-9a0d-507e54f6b71c.jpg)

**Comment by alexrj** [comment]
Oh no, again!

**Comment by alexrj** [comment]
One line was missing. Fixed.

**Comment by gege2b** [comment]
liked your "oh no again" :D
