### ISSUE TITLE
Bug 1.2.7-dev: Solid infill extrusion width not used for solid infill

### ISSUE THREAD

**Issue by jonaskuehling** [alexrj/Slic3r#2730]
Maybe I'm misinterpreting something here, but doesn't "solid infill" mean all internal infill when fill density is set to 100%?

In that case Slic3r doesn't respect the "solid infill extrusion width" for its solid infill - be it left to default (0) or set manually. In the first few lines of the GCODE it says:
```
; generated by Slic3r 1.2.7-dev on 2015-03-10 at 13:48:29

; external perimeters extrusion width = 0.35mm
; perimeters extrusion width = 0.59mm
; infill extrusion width = 0.98mm
; solid infill extrusion width = 0.59mm           <---------------
; top infill extrusion width = 0.59mm
; support material extrusion width = 0.50mm
```

But the result is this, where solid infill obviously uses 0.98mm extrusion width from general "infill extrusion width" parameter, rather than "solid infill extrusion width"

![screenshot02](https://cloud.githubusercontent.com/assets/1555760/6575272/a95a9d06-c72d-11e4-9d29-adf124068944.png)

For comparison, this is the first object layer with "top infill extrusion width" used, which is 0.59mm:

![screenshot01](https://cloud.githubusercontent.com/assets/1555760/6575274/aff1fbf0-c72d-11e4-9ba6-214a14f9446f.png)

GCODE: https://www.dropbox.com/s/pb756so8dukd0z6/cylinder20.gcode?dl=0

**Comment by lordofhyphens** [comment]
Internal infill width is set for all internal infill, "solid infill" refers only to the top/bottom solid infill. These options are greyed out if you set top/bottom solid layers to 0, so this seems to be just a different interpretation of things. 

I'm going to close this for now, as I don't think it's a bug myself. Please post/reopen if you want to make a case for treating all 100% infill the same as "solid" infill, @jonaskuehling .
