### ISSUE TITLE
Crossing perimeters although it shouldn't

### ISSUE THREAD

**Issue by lahure-c** [alexrj/Slic3r#2741]
Hi
I would like to avoid crossing perimeters in order to avoid oozing deposit on visible surfaces
But I cannot succeed.
Here is the gcode file
https://github.com/lahure-c/public/blob/master/CylAR-4.gcode
; generated by Slic3r 1.2.6 on 2015-03-16 at 11:42:42
;...
; avoid_crossing_perimeters = 1

When completing the infill, the head moves across the internal perimeter instead of choosing the  longer path of flying above the deposited infill.
That's what I see with this gcode viewer http://gcode.ws

Thank you

**Comment by lahure-c** [comment]
Here's a snapshot of the crossing:
https://github.com/lahure-c/public/blob/master/CylAR-4.jpg

**Comment by lahure-c** [comment]
I have found a fix to this problem
Although I have set the retract_length to zero, it seems that Slic3r still uses the retract-before_travel variable.
There retract-before_travel was set to 20.
Now that I set it to 2, there's no crossing anymore.

**Comment by lahure-c** [comment]
I still have issues on a more complex model. 
It works fine with extrusion widths equal to 0.5mm for perimeters and infills.
But with other values it does not work, for example 0.4mm
May I post this ?

**Comment by alexrj** [comment]
Have you read the guidelines? You probably haven't (why?). This report is incomplete.

**Comment by lahure-c** [comment]
https://github.com/alexrj/Slic3r/blob/master/CONTRIBUTING.md

You can close this thread.
I'll open a new one that will include new things and follow the guidelines
