### ISSUE TITLE
Only retrack when crossing perimeters...

### ISSUE THREAD

**Issue by KarelVorel** [alexrj/Slic3r#2747]
I think it would greatly improved the quality of the first layer, add a switch: Only retrack When crossing perimeters but always retrack on first layer. Thank you.
Karel
I can also print quality, but this is to show what I mean. :)
![retracting](https://cloud.githubusercontent.com/assets/3129080/6716737/a8dc9fde-cda7-11e4-8765-2c8f3e4b8f13.jpg)
![retract](https://cloud.githubusercontent.com/assets/3129080/6716814/4c538510-cda8-11e4-918c-b1e57566d615.jpg)

**Comment by alexrj** [comment]
Yes, that should actually happen automatically without the need for one more switch.
