### ISSUE TITLE
Gcode Export remains disabled after canceling export

### ISSUE THREAD

**Issue by OhmEye** [alexrj/Slic3r#2754]
Current git master with default settings running on Linux 64bit:

On the Plater tab, add an STL.
Click the Export G-code button.
Click the Cancel button at the bottom of the window.
The Export G-code button remains disabled.
Choosing the Export G-code menu item from the Plater menu give the error: "Another export job is currently running."
Exporting to G-code is not possible without restarting slic3r.

**Comment by lordofhyphens** [comment]
It is probably because the threads haven't joined yet.

I can confirm the general behavior though.

**Comment by OhmEye** [comment]
It also happens when single threaded. I didn't realize default was 2 threads, my own profiles are all single threaded but I did a check with defaults to make simpler reporting.

**Comment by alexrj** [comment]
Fixed, thank you.
