### ISSUE TITLE
 Feature request: optional printing of the "outside" support material only

### ISSUE THREAD

**Issue by Zuborg** [alexrj/Slic3r#2757]
When I print complex mechanical parts often need a support material under them. It prevent a bend and vibration of tall and inclined models. (I prefer a tilt angle near 45 degrees) But when I adjust appropriate "overhang threshold" for generation the support from printbed up to the model it also generated unnecessary support in internal hollow volumes of the model. It will be a good selectable option to generate support when it can reach printbed directly and disable support for other cases (internal and shielded by the model body).

**Comment by lonelymyp** [comment]
It would be just super function.

I recently printed a salt shaker in the form of a pig, and got the problem of removing the support from the inside. 
Pillar of support was larger than the diameter of the hole.

Support within the model is not needed, no one will see if several perimeters fail inside. 
But without the support, the snout is not printed

**Comment by lordofhyphens** [comment]
#3310
