### ISSUE TITLE
Slic3r crashes with a doc folder with accent

### ISSUE THREAD

**Issue by huguesdb** [alexrj/Slic3r#2759]
My main document folder is named "Görald" - Slic3r crashed on startup as it cannot create a document with this name in the path.

I cant change my document folder name under windows 8.1 ( widh I could).

Any solutions ? 
:)

**Comment by huguesdb** [comment]
btw, am using V 1.2.6.36

**Comment by harriv** [comment]
Commit 6185f458157ebca874de0cf1f902ceedec93d2a7 may have fixed this.

**Comment by huguesdb** [comment]
yes, I did see that but I'm not setup to code... thanks!

**Comment by huguesdb** [comment]
no solution in view in the production release ? not sure why u closed this alexrj.

**Comment by alexrj** [comment]
As @harriv, this was fixed. Next release will contain the fix. No need to keep this open.
