### ISSUE TITLE
[1.2.7-dev] Part/Object settings window incorrect initialization

### ISSUE THREAD

**Issue by Lenbok** [alexrj/Slic3r#2762]
When I open the part settings it initially looks like this:
![image](https://cloud.githubusercontent.com/assets/282098/6883976/60c33c18-d62f-11e4-8d51-7a44590ab949.png)
I would expect that straight after opening this window I should be able to start adding settings. After all, the '+' icon is present. However, this does not work.

In the tree view it looks like it should currently be in "Object Settings" mode, but the settings area below is labelled "Part Settings". Note that this settings area no section for the Extruder. Clicking on the '+' icon does not bring up a list of settings that can be applied.

If you click on the part name (in this case vacuum-pipe-lock), the "Extruders" section appears and per-part settings can now be chosen via '+'. 
![image](https://cloud.githubusercontent.com/assets/282098/6883989/2f288284-d630-11e4-82b3-baa0d88aa5e6.png)

Clicking on "Object" to switch to "Object Settings" now contains the missing Extruders section and object settings can now be chosen via '+'.
![image](https://cloud.githubusercontent.com/assets/282098/6883990/3de820f4-d630-11e4-8a23-f19fe8d6e0d5.png)

It seems like this window is being initialized incorrectly so it isn't completely in either Object Settings or Part Settings.

**Comment by alexrj** [comment]
Good catch...

**Comment by alexrj** [comment]
Fixed. Thank you!
