### ISSUE TITLE
feature request: modifier meshes when running headless

### ISSUE THREAD

**Issue by mattratto** [alexrj/Slic3r#2763]
I'd like to be able to call the modifier meshes functionality when running slic3r headless. In the design process I will predetermine areas requiring different settings, generate meshes encompassing those areas using a solid modeler and using generic names, and then call them out from ini file.

**Comment by alexrj** [comment]
Slic3r supports that; you need to use the AMF file format.
In order to see how it works, try to define a multi-part print with the GUI and then export the AMF file. Open it and see how it's made.

**Comment by mattratto** [comment]
great! Thanks so much Alessandro. Slic3r is an essential tool!

**Comment by lordofhyphens** [comment]
As the man said, it's already implemented, just have to do it with AMF.
