### ISSUE TITLE
Feature Request: Adjustable minimum segment length

### ISSUE THREAD

**Issue by NitroXpress** [alexrj/Slic3r#2764]
Is it possible to make the minimum segment length for arcs respectively circles adjustable ?
Shorter segments contribute to better trajectory generation and smoother surfaces.

Greetings

Frank

**Comment by lordofhyphens** [comment]
So polyholes? Can't you fix this in the model?

**Comment by alexrj** [comment]
Slic3r does not generate segments from arcs, since the input models (STL files) don't contain arcs. Slic3r generates G-code having exactly the same number of vertices as the original STL file contains - no loss of detail. If you want smoother curves, you need to export your STL files with more facets from the CAD itself.

**Comment by NitroXpress** [comment]
Hi,

I know, in .stl models are no arcs.
But don't know how to explain it exactly...

Slic3r doesn't follow the original number of vertices.

I've created a 50mm diameter cylinder with a angle resolution of 1° (360 segments).
But Slic3r only outputs 128 segments.

Did I something wrong ?

**Comment by alexrj** [comment]
Have you read the guidelines before posting this issue? Please do.

**Comment by NitroXpress** [comment]
Yes, but don't know how to attach a .stl file...

**Comment by alexrj** [comment]
Host it somewhere and put the link here.

**Comment by NitroXpress** [comment]
Much effort...
Can I email it direct to you ?

**Comment by alexrj** [comment]
No, please.

**Comment by NitroXpress** [comment]
OK.

Too much bureaucracy for me here (like in Germany)

Bye...

**Comment by alexrj** [comment]
I do this on voluntary basis. This is not a company help desk. Your help is appreciated. Otherwise, goodbye.

**Comment by alexrj** [comment]
(And writing Slic3r for you was "much effort" as well, by the way. lol)

**Comment by NitroXpress** [comment]
Yes, i know that all...

And i have great respect about your great work !
No  reason for gallows humor...

I want to help making Slic3r more perfect.
But how to, if not so ?

**Comment by a4jp-com** [comment]
You can upload your files onto any upload site. I did a quick search and found this: http://www.filedropper.com/

**Comment by lordofhyphens** [comment]
NitroXpress,

Uploading the test case allows people other than Alessandro to test as
well. It's just better practice overall. You can help by reporting issues
in the proper way, or modifying Slic3r so that it does what you want and
submitting a pull request that explains the reason for the change and why
it's important.

Adding your own changes should not break any existing tests either and
should be readable by other people.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by NitroXpress** [comment]
Damned...
I am forgetful :-(
You can download the file in the RepRap forum.
The file is attached there.
Scroll a little bit down...
http://forums.reprap.org/read.php?263,490722

**Comment by NitroXpress** [comment]
Ok.
Shame on me !
I am very sorry.
That was only a picture.

I will find a nother way...

**Comment by lordofhyphens** [comment]
2shared, filedropper, etc.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
But seriously, read Contributing.md before you post any more.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by a4jp-com** [comment]
NitroXpress, thank you for reporting the bug ^^

**Comment by NitroXpress** [comment]
...
I don't know if this a bug...

@lordofhyphens 
But thanks for the hint... 
Contributing should not be the problem.

**Comment by NitroXpress** [comment]
Sorry again...
It was the wrong thread in the slic3r forum.
Now the right link:
http://forums.reprap.org/read.php?263,490228

The file is attached at the third post.

**Comment by a4jp-com** [comment]
All of our config files are different, so you need to upload your individual config file to get help. Your settings just might be wrong.

**Comment by NitroXpress** [comment]
I have the highest resolution setting in slic3r with a extrusion wide of 0,25mm.
What can i do more ?
Have you downloaded the files from RepRap forum ?

I found out, that decreasing the resolution of my CAD output to 2° (180 segments) slic3r forces to create 188 segments.
Don't know why...

Both files can be downloaded in the thread here:
http://forums.reprap.org/read.php?263,490228

**Comment by a4jp-com** [comment]
I only see an STL file...

**Comment by a4jp-com** [comment]
http://www.filedropper.com/

**Comment by NitroXpress** [comment]
What file format would you have ?
.stl is standard for 3D printing, or not ?
I tried with many CAD programs, same problem every time.

Sorry, I don't want to share my settings with the whole world.

I asked Alessandro to direct email the files.
I don't understand what the problem is thereby.

Nevertheless, thanks for your effort.

Now back to CURA...

**Comment by xoan** [comment]
If you want to other people help you, other people need to be able to
reproduce your exact environment, so you need to share all the information
you have.

If you don't want to cooperate, you can't demand anything.

And if you are comfortable using Cura, please, keep using it.

Thanks.

**Comment by NitroXpress** [comment]
Hi,
i am not married with Cura...
Currently i am using 3 Slicers. (Skeinforge, Slic3r, Cura)
Each has advantages and disadvantages.
My goal is, to have 1 slicer for all cases.
I think slic3r is the most promising...
There is only 1 problem: resolution.

My hope was, to modify the source code for higher segment resolution.
But no success, although i dug in the source code for many hours.

Sorry for the trouble !

Frank

**Comment by lordofhyphens** [comment]
Well yeah, segment resolution is a *model* problem. If you want more
segments in an approximation of an arc,  then fix your model. Slic3r would
have to able to read your mind otherwise.

**Comment by NitroXpress** [comment]
No, it is not a model problem !

I have made the cylinder (50x10) with up to 300000 facetes.
But slic3r output is only 128 segments on circumference.

**Comment by lordofhyphens** [comment]
Please post a link to your test cylinder  and your settings then.

**Comment by NitroXpress** [comment]
config

http://www.filedropper.com/config_10

**Comment by NitroXpress** [comment]
Thanks for you considerations.
But no difference...
