### ISSUE TITLE
Slider is not updated or reset to original full position.

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2766]
Hi @alexrj 

If I load a model then move the slider everything is okay. But when I press delete all and load another model the slider is in the same position showing everything. When I click on the slider's handle it redraws the model at the correct layer. 

![screen shot 04-02-15 at 01 44 pm](https://cloud.githubusercontent.com/assets/9621044/6957985/f593318c-d93f-11e4-9090-b0863562cc55.JPG)

![screen shot 04-02-15 at 02 01 pm](https://cloud.githubusercontent.com/assets/9621044/6958047/d7fb70ca-d940-11e4-92e8-ca33a8c5466e.JPG)

http://a4jp.com/3d-files/bugs/2015-04-02nd-01-42-pm-for-github-config.ini

http://a4jp.com/3d-files/bugs/2015-04-02nd-github-1-apartment.stl

**Comment by lordofhyphens** [comment]
This looks fixed as of 90395f93940410093244e9cfcaf3dce407ddc811

**Comment by a4jp-com** [comment]
Just checked. It works properly now ^^
