### ISSUE TITLE
Infill speed is sometimes used instead of *solid* infill speed

### ISSUE THREAD

**Issue by jmeosbn** [alexrj/Slic3r#2769]
*Slic3r version: both the current beta (1.2.7) and stable (1.1.7) versions
Operating system: OS X 10.10*

For a minimal test, I added the simple cube included in [this test example](https://www.dropbox.com/s/lpafeq01tbsg2oc/Infill%20Speed%20Issue.zip?dl=0). When printing with the given profile (and any other settings I try), the regular **infill** speed is used for the first **solid infill** after any regular infill.

i.e. With the three top solid layers of the cube, the first is (incorrectly) at infill speed, the second is at solid infill speed, and the last is at top solid infill speed.

The test files have resulting gcode for the two current versions listed above. I've set the two speeds of interest to 40 and 10, so as to see the difference easily. Though I usually use a percentage for solid infill and it happens with that too.

I've noticed a similar issue with automatic extrusion width and this layer, that I can write up if not part of this same issue.

Cheers!

**Comment by lordofhyphens** [comment]
Could you run a test with 1.2.9 and 1.3.0-dev and see if the problem has gone away?

My tests with 1.3.0-dev indicates that it's fixed now (it's putting in F600 feedrates which is 10mm/s) ; going to close.
