### ISSUE TITLE
Splitting rotated STLs badly changes object positioning

### ISSUE THREAD

**Issue by OhmEye** [alexrj/Slic3r#2772]
Versions I have reproduced with: current git master, 1.2.6 release, 1.1.7 release

Steps to reproduce:

1. Plate multiple objects to a single STL outside slic3r. Here is an example of a plated STL:
http://ohmeye.com/download/debug/slic3r/x25_X%20Carriage%20Spacer_fab.stl

2. Add STL in Slic3r.
3. Rotate STL (I click one of the 45 deg buttons twice)
4. Note that the STL rotated and looks correct on the plater 2D view (and 3D view in recent versions)
5. Click the Split button
6. Note that instead of remaining in place, the positions of the individual objects change and the coordinates appear to snap back to pre-rotation positions.

Desired results: Retain the relative object positions when splitting a rotated STL.

**Comment by alexrj** [comment]
I fixed this. Thank you.
