### ISSUE TITLE
Bottom solid layers not available [1.2.6]

### ISSUE THREAD

**Issue by cocoknight** [alexrj/Slic3r#2773]
Happy Easter everybody,
I've been playing around with custom support directly generated in my CAD software. For these structures I want to apply special printing/slicing parameters. Works fine so far, but when I want to set the number of top and bottom infill layers Slic3r only gives me the option for the top layers.
![modifier](https://cloud.githubusercontent.com/assets/11601966/6996403/b20a4358-db86-11e4-9cd0-9f784aba4d0a.png)
Don't know if the option is hidden somewhere in the background or if there isn't a possibility so far to set that value. Would be happy if you could fix that issue.
Windows 7 x64
Regards
Stefan

**Comment by alexrj** [comment]
Are you sure? I see both:

![schermata 2015-05-02 alle 22 45 25](https://cloud.githubusercontent.com/assets/594957/7442728/15a6b58a-f11d-11e4-9012-daa47be4efa7.png)

**Comment by cocoknight** [comment]
You are right with this. My bad! I've totally overseen that.
