### ISSUE TITLE
MORE Octoprint Integration!

### ISSUE THREAD

**Issue by flyswatter** [alexrj/Slic3r#2780]
Closing issue #1826 is the coolest thing ever, Slic3r is very close to becoming the only application I need to 3d print!

If you just add a "Print" button, I won't even need to open the OctoPrint web interface!  I think this would be a small feature with a big enhancement.

Long term, it'd be cool to provide even more of a front-end, but it's realistically probably beyond the scope of what Slic3r is about..

**Comment by lordofhyphens** [comment]
Disagree here. Slic3r should be about slicing models and generating gcode.

If you want a more integrated solution someone was working on a octoprint
plug in for slic3r.

**Comment by flyswatter** [comment]
I didn't realize slic3r could take plug-ins!  That would be a cool project!  Looks like it's kept [over here](https://github.com/OctoPrint/OctoPrint-Slic3r/tree/master).

**Comment by lordofhyphens** [comment]
On 04/12/2015 05:47 PM, Dan Finlay wrote:
>
> I didn't realize slic3r could take plug-ins! That would be a cool 
> project! Looks like it's kept over here 
> <https://github.com/OctoPrint/OctoPrint-Slic3r/tree/master>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alexrj/Slic3r/issues/2780#issuecomment-92146314>.
>
Octoprint can, and you can do any sort of "postprocessing" script in slic3r.

-- 
--Joseph Lenox, BS, MS
I'm an engineer. I solve problems.

**Comment by alexrj** [comment]
I added a prompt to start printing at upload time.

**Comment by flyswatter** [comment]
Cool, thanks!
