### ISSUE TITLE
Thin walls printed without infills making them weak

### ISSUE THREAD

**Issue by led42** [alexrj/Slic3r#2781]
I've been using slic3r version 1.2.6 and noticed some models print with thin walls without any infill making them really flimsy.
Looked in previous issues and looks similar to what was happening in issue #281 I even used the rake stl file presented in that issue http://nypano.com/clients/UM/rake.stl (not my file) and looking at the preview on 1.2.6 3 of the walls are empty.

Models that also exhibit this problem: http://www.thingiverse.com/thing:604915 http://www.thingiverse.com/thing:423216

I'm using a 0.5mm nozzle, 0.1mm layer height.

**Comment by led42** [comment]
The 3 walls on the left are empty, this is from the rake.stl file.
![screen shot 2015-04-13 at 21 37 32](https://cloud.githubusercontent.com/assets/3342360/7125006/5f6038f6-e225-11e4-8b55-289d0c0833ec.png)

**Comment by lordofhyphens** [comment]
Led42 please post entire configuration file.

**Comment by led42** [comment]
Here it goes

# generated by Slic3r 1.2.6 on Mon Apr 13 21:39:52 2015

[filament:ABS]
bed_temperature = 105
bridge_fan_speed = 100
cooling = 1
disable_fan_first_layers = 1
extrusion_multiplier = 0.9
fan_always_on = 0
fan_below_layer_time = 999
filament_diameter = 1.8
first_layer_bed_temperature = 105
first_layer_temperature = 240
max_fan_speed = 100
min_fan_speed = 100
min_print_speed = 10
slowdown_below_layer_time = 5
temperature = 240

[filament:M-PLA-05-03-1mc]
bed_temperature = 57
bridge_fan_speed = 100
cooling = 1
disable_fan_first_layers = 1
extrusion_multiplier = 0.9
fan_always_on = 0
fan_below_layer_time = 999
filament_diameter = 1.75
first_layer_bed_temperature = 57
first_layer_temperature = 0
max_fan_speed = 100
min_fan_speed = 100
min_print_speed = 10
slowdown_below_layer_time = 5
temperature = 0

[filament:PLA 0.5]
bed_temperature = 57
bridge_fan_speed = 100
cooling = 1
disable_fan_first_layers = 1
extrusion_multiplier = 0.8
fan_always_on = 0
fan_below_layer_time = 60
filament_diameter = 1,74
first_layer_bed_temperature = 57
first_layer_temperature = 195
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 10
slowdown_below_layer_time = 30
temperature = 195

[filament:PLA-03]
bed_temperature = 57
bridge_fan_speed = 100
cooling = 1
disable_fan_first_layers = 4
extrusion_multiplier = 1
fan_always_on = 0
fan_below_layer_time = 30
filament_diameter = 1.75
first_layer_bed_temperature = 57
first_layer_temperature = 200
max_fan_speed = 100
min_fan_speed = 100
min_print_speed = 10
slowdown_below_layer_time = 25
temperature = 200

[filament:PLA-05]
bed_temperature = 57
bridge_fan_speed = 100
cooling = 1
disable_fan_first_layers = 2
extrusion_multiplier = 0.83
fan_always_on = 1
fan_below_layer_time = 60
filament_diameter = 1.72
first_layer_bed_temperature = 57
first_layer_temperature = 195
max_fan_speed = 100
min_fan_speed = 80
min_print_speed = 5
slowdown_below_layer_time = 30
temperature = 195

[presets]
filament = PLA-05.ini
print = Mendel PLA 05 nozzle OPT.ini
printer = Mendel PLA 05 nozzle.ini

[print:Huxley PLA 03 nozzle]
avoid_crossing_perimeters = 0
bottom_solid_layers = 3
bridge_flow_ratio = 1
bridge_speed = 25
brim_width = 0
complete_objects = 0
default_acceleration = 0
external_fill_pattern = concentric
external_perimeter_speed = 20
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 0
fill_angle = 45
fill_density = 20%
fill_pattern = rectilinear
first_layer_extrusion_width = 0.5
first_layer_height = 0.3
first_layer_speed = 50%
gap_fill_speed = 20
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_speed = 32
layer_height = 0.25
min_skirt_length = 0
notes = H-PLA-03-025-1
only_retract_when_crossing_perimeters = 0
output_filename_format = [input_filename_base].g
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 20
perimeters = 3
post_process = 
skirt_distance = 6
skirt_height = 1
skirts = 1
small_perimeter_speed = 20
solid_infill_below_area = 5
solid_infill_every_layers = 0
solid_infill_speed = 32
support_material = 0
support_material_angle = 0
support_material_extruder = 1
support_material_extrusion_width = 65%
support_material_pattern = rectilinear
support_material_spacing = 2.5
support_material_speed = 40
support_material_threshold = 45
threads = 4
top_solid_infill_speed = 32
top_solid_layers = 4
travel_speed = 250

[print:Huxley PLA 05 nozzle]
avoid_crossing_perimeters = 0
bottom_solid_layers = 2
bridge_flow_ratio = 1
bridge_speed = 30
brim_width = 0
complete_objects = 0
default_acceleration = 0
external_fill_pattern = rectilinear
external_perimeter_speed = 24
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 0.5
fill_angle = 45
fill_density = 20%
fill_pattern = rectilinear
first_layer_extrusion_width = 0.5
first_layer_height = 0.3
first_layer_speed = 40%
gap_fill_speed = 20
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.5
infill_speed = 48
layer_height = 0.3
min_skirt_length = 0
notes = 
only_retract_when_crossing_perimeters = 0
output_filename_format = [input_filename_base]_PLA.gcode
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0.5
perimeter_speed = 30
perimeters = 2
post_process = 
seam_position = random
skirt_distance = 6
skirt_height = 1
skirts = 1
small_perimeter_speed = 26
solid_infill_below_area = 5
solid_infill_every_layers = 0
solid_infill_speed = 48
support_material = 0
support_material_angle = 0
support_material_extruder = 1
support_material_extrusion_width = 75%
support_material_pattern = honeycomb
support_material_spacing = 4
support_material_speed = 40
support_material_threshold = 45
threads = 2
top_solid_infill_speed = 26
top_solid_layers = 3
travel_speed = 250

[print:M-PLA-05-03-1mc]
avoid_crossing_perimeters = 0
bottom_solid_layers = 2
bridge_acceleration = 0
bridge_flow_ratio = 1
bridge_speed = 30
brim_width = 0
complete_objects = 0
default_acceleration = 0
external_fill_pattern = rectilinear
external_perimeter_speed = 26
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 0.5
fill_angle = 45
fill_density = 20%
fill_pattern = rectilinear
first_layer_extrusion_width = 0.5
first_layer_height = 0.3
first_layer_speed = 50%
gap_fill_speed = 20
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.5
infill_first = 0
infill_only_where_needed = 0
infill_speed = 50
layer_height = 0.3
min_skirt_length = 0
notes = M-PLA-05-03-1
only_retract_when_crossing_perimeters = 0
output_filename_format = [input_filename_base]_PLA.gcode
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0.5
perimeter_speed = 32
perimeters = 2
post_process = 
raft_layers = 0
resolution = 0
skirt_distance = 3
skirt_height = 999
skirts = 2
small_perimeter_speed = 26
solid_infill_below_area = 5
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0.5
solid_infill_speed = 40
support_material = 0
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 85%
support_material_interface_layers = 0
support_material_interface_spacing = 0
support_material_pattern = rectilinear
support_material_spacing = 6
support_material_speed = 20
support_material_threshold = 45
threads = 4
top_infill_extrusion_width = 0.5
top_solid_infill_speed = 32
top_solid_layers = 3
travel_speed = 250

[print:Mendel ABS 05 nozzle]
avoid_crossing_perimeters = 1
bottom_solid_layers = 2
bridge_acceleration = 0
bridge_flow_ratio = 1
bridge_speed = 30
brim_width = 0
complete_objects = 0
default_acceleration = 0
external_fill_pattern = rectilinear
external_perimeter_speed = 26
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 0.5
fill_angle = 45
fill_density = 15%
fill_pattern = rectilinear
first_layer_acceleration = 0
first_layer_extrusion_width = 0.5
first_layer_height = 0.3
first_layer_speed = 50%
gap_fill_speed = 20
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.5
infill_first = 0
infill_only_where_needed = 0
infill_speed = 50
layer_height = 0.3
min_skirt_length = 0
notes = 
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = [input_filename_base]_ABS.gcode
overhangs = 1
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0.5
perimeter_speed = 32
perimeters = 2
post_process = 
raft_layers = 0
resolution = 0
skirt_distance = 8
skirt_height = 1
skirts = 1
small_perimeter_speed = 26
solid_infill_below_area = 5
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0
solid_infill_speed = 40
spiral_vase = 0
standby_temperature_delta = -5
support_material = 1
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 85%
support_material_interface_extruder = 1
support_material_interface_layers = 3
support_material_interface_spacing = 0
support_material_pattern = rectilinear
support_material_spacing = 6
support_material_speed = 20
support_material_threshold = 65
thin_walls = 1
threads = 4
top_infill_extrusion_width = 0
top_solid_infill_speed = 32
top_solid_layers = 3
travel_speed = 300

[print:Mendel PLA 03 nozzle]
avoid_crossing_perimeters = 0
bottom_solid_layers = 3
bridge_flow_ratio = 1
bridge_speed = 20
brim_width = 0
complete_objects = 0
default_acceleration = 0
external_fill_pattern = rectilinear
external_perimeter_speed = 20
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 0.3
fill_angle = 45
fill_density = 20%
fill_pattern = rectilinear
first_layer_extrusion_width = 0.3
first_layer_height = 0.25
first_layer_speed = 50%
gap_fill_speed = 20
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.3
infill_speed = 32
layer_height = 0.25
min_skirt_length = 0
notes = 
only_retract_when_crossing_perimeters = 0
output_filename_format = [input_filename_base]_PLA.gcode
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0.3
perimeter_speed = 20
perimeters = 3
post_process = 
seam_position = random
skirt_distance = 6
skirt_height = 1
skirts = 1
small_perimeter_speed = 20
solid_infill_below_area = 10
solid_infill_every_layers = 0
solid_infill_speed = 32
support_material = 0
support_material_angle = 0
support_material_extruder = 1
support_material_extrusion_width = 65%
support_material_pattern = rectilinear
support_material_spacing = 2.5
support_material_speed = 40
support_material_threshold = 45
threads = 4
top_solid_infill_speed = 32
top_solid_layers = 4
travel_speed = 250

[print:Mendel PLA 05 nozzle]
avoid_crossing_perimeters = 0
bottom_solid_layers = 2
bridge_flow_ratio = 1
bridge_speed = 30
brim_width = 0
complete_objects = 0
default_acceleration = 0
external_fill_pattern = rectilinear
external_perimeter_speed = 26
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 0.5
fill_angle = 45
fill_density = 20%
fill_pattern = rectilinear
first_layer_extrusion_width = 0.5
first_layer_height = 0.3
first_layer_speed = 50%
gap_fill_speed = 20
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.5
infill_speed = 50
layer_height = 0.3
min_skirt_length = 0
notes = M-PLA-05-03-1
only_retract_when_crossing_perimeters = 0
output_filename_format = [input_filename_base]_PLA.gcode
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0.5
perimeter_speed = 32
perimeters = 2
post_process = 
skirt_distance = 3
skirt_height = 1
skirts = 1
small_perimeter_speed = 26
solid_infill_below_area = 5
solid_infill_every_layers = 0
solid_infill_speed = 40
support_material = 0
support_material_angle = 0
support_material_extruder = 1
support_material_extrusion_width = 85%
support_material_pattern = rectilinear
support_material_spacing = 6
support_material_speed = 20
support_material_threshold = 45
threads = 4
top_solid_infill_speed = 32
top_solid_layers = 3
travel_speed = 250

[print:Mendel PLA 05 nozzle OPT]
avoid_crossing_perimeters = 1
bottom_solid_layers = 5
bridge_acceleration = 0
bridge_flow_ratio = 1
bridge_speed = 26
brim_width = 0
complete_objects = 0
default_acceleration = 0
dont_support_bridges = 0
external_fill_pattern = rectilinear
external_perimeter_extrusion_width = 0
external_perimeter_speed = 26
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 0
fill_angle = 45
fill_density = 25%
fill_pattern = rectilinear
first_layer_acceleration = 0
first_layer_extrusion_width = 150%
first_layer_height = 0.3
first_layer_speed = 50%
gap_fill_speed = 20
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 3
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_overlap = 20%
infill_speed = 50
interface_shells = 0
layer_height = 0.1
min_skirt_length = 0
notes = M-PLA-05-03-1
only_retract_when_crossing_perimeters = 1
ooze_prevention = 0
output_filename_format = [input_filename_base]_PLA.gcode
overhangs = 1
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 32
perimeters = 2
post_process = 
raft_layers = 0
resolution = 0.01
seam_position = aligned
skirt_distance = 1
skirt_height = 1
skirts = 3
small_perimeter_speed = 26
solid_infill_below_area = 5
solid_infill_every_layers = 0
solid_infill_extruder = 1
solid_infill_extrusion_width = 0
solid_infill_speed = 40
spiral_vase = 0
standby_temperature_delta = -5
support_material = 0
support_material_angle = 45
support_material_contact_distance = 0.2
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 85%
support_material_interface_extruder = 1
support_material_interface_layers = 3
support_material_interface_spacing = 0.1
support_material_interface_speed = 100%
support_material_pattern = rectilinear-grid
support_material_spacing = 5.5
support_material_speed = 20
support_material_threshold = 45
thin_walls = 1
threads = 4
top_infill_extrusion_width = 0
top_solid_infill_speed = 32
top_solid_layers = 6
travel_speed = 250
xy_size_compensation = 0

[print:Simple Mode]
bottom_solid_layers = 3
brim_width = 0
complete_objects = 0
extruder_clearance_height = 20
extruder_clearance_radius = 20
fill_density = 40%
fill_pattern = honeycomb
infill_speed = 60
layer_height = 0.4
perimeter_speed = 30
perimeters = 3
raft_layers = 0
support_material = 0
support_material_spacing = 2.5
top_solid_layers = 3
travel_speed = 130

[printer:Huxley PLA 03 nozzle]
bed_shape = 0x0,140x0,140x140,0x140
end_gcode = M104 S120\nM140 S40\nG1 X0 Y130 F9000
extruder_offset = 0x0
gcode_flavor = reprap
layer_gcode = 
nozzle_diameter = 0.3
retract_before_travel = 1.8
retract_layer_change = 1
retract_length = 1.75
retract_length_toolchange = 3
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 37
start_gcode = G28\nG1 Z[layer_height] F200\nG1 X15 Y20 F12000
toolchange_gcode = 
use_relative_e_distances = 0
vibration_limit = 0
z_offset = 0

[printer:Huxley PLA 05 nozzle]
bed_shape = 0x0,140x0,140x140,0x140
end_gcode = M104 S120\nM140 S40\nG1 X0 Y130 F9000
extruder_offset = 0x0
gcode_flavor = reprap
layer_gcode = 
nozzle_diameter = 0.5
retract_before_travel = 1.8
retract_length = 1.6
retract_length_toolchange = 3
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 37
start_gcode = G28\nG1 Z[layer_height] F200\nG1 X15 Y20 F12000
toolchange_gcode = 
use_relative_e_distances = 0
vibration_limit = 0
z_offset = 0

[printer:M-PLA-05-03-1mc]
bed_shape = 0x0,218x0,218x218,0x218
end_gcode = M104 S120\nM140 S40\nG1 X0 Y0 F12000
extruder_offset = 0x0,0x0,0x0
gcode_flavor = reprap
layer_gcode = 
nozzle_diameter = 0.5,0.5,0.5
retract_before_travel = 1.8,1.8,1.8
retract_layer_change = 1,1,1
retract_length = 3.2,3.2,3.2
retract_length_toolchange = 5,5,5
retract_lift = 0,0,0
retract_restart_extra = 0,0,0
retract_restart_extra_toolchange = 0,0,0
retract_speed = 46,46,46
start_gcode = G28\nG1 Z0.3 F200\nG1 X15 Y20 F12000
toolchange_gcode = G1 X5 Y100 F9000
use_relative_e_distances = 1
vibration_limit = 0
z_offset = 0

[printer:Mendel ABS 05 nozzle]
bed_shape = 0x0,218x0,218x180,0x180
end_gcode = M104 S120\nM140 S40\nG1 X0 Y0 F12000
extruder_offset = 0x0
gcode_flavor = reprap
layer_gcode = 
nozzle_diameter = 0.5
retract_before_travel = 1.8
retract_layer_change = 
retract_length = 2
retract_length_toolchange = 3
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 80
start_gcode = G28 X0 Y0\nG28 Z0\nG1 Z0.3 F200\nG1 X15 Y20 F12000
toolchange_gcode = 
use_firmware_retraction = 0
use_relative_e_distances = 0
vibration_limit = 0
wipe = 1
z_offset = 0

[printer:Mendel PLA 03 nozzle]
bed_shape = 0x0,218x0,218x218,0x218
end_gcode = M104 S120\nM140 S40\nG1 X0 Y180 F9000
extruder_offset = 0x0
gcode_flavor = reprap
layer_gcode = 
nozzle_diameter = 0.3
retract_before_travel = 1.8
retract_layer_change = 1
retract_length = 2.4
retract_length_toolchange = 3
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 50
start_gcode = G28 X0 Y0\nG28 Z0\nG1 Z[layer_height] F200\nG1 X15 Y20 F12000
toolchange_gcode = 
use_relative_e_distances = 0
vibration_limit = 0
z_offset = 0

[printer:Mendel PLA 05 nozzle]
bed_shape = 0x0,215x0,215x185,0x185
before_layer_gcode = 
end_gcode = M104 S0\nM140 S57\nG1 X0 Y180 F9000
extruder_offset = 0x0
gcode_flavor = reprap
layer_gcode = 
nozzle_diameter = 0.5
octoprint_apikey = F8D5117F7314473FB2765223F085EEB4
octoprint_host = 192.168.0.29
pressure_advance = 0
retract_before_travel = 2
retract_layer_change = 1
retract_length = 3.2
retract_length_toolchange = 3
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 46
start_gcode = G28 X0 Y0\nG28 Z0\nG1 Z[layer_height] F200\nG1 X15 Y20 F12000
toolchange_gcode = 
use_firmware_retraction = 0
use_relative_e_distances = 0
use_volumetric_e = 0
vibration_limit = 0
wipe = 0
z_offset = 0

[settings]
autocenter = 1
mode = expert

[simple]
avoid_crossing_perimeters = 1
bed_shape = 0x0,200x0,200x200,0x200
bed_temperature = 57
bottom_solid_layers = 3
bridge_acceleration = 0
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 60
brim_width = 0
complete_objects = 0
cooling = 1
default_acceleration = 0
disable_fan_first_layers = 1
duplicate_distance = 6
end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors
external_fill_pattern = rectilinear
external_perimeter_speed = 70%
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 0x0
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
fan_always_on = 0
fan_below_layer_time = 60
filament_diameter = 1.75
fill_angle = 45
fill_density = 40%
fill_pattern = honeycomb
first_layer_acceleration = 0
first_layer_bed_temperature = 62
first_layer_extrusion_width = 200%
first_layer_height = 0.5
first_layer_speed = 30%
first_layer_temperature = 205
gap_fill_speed = 20
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
infill_acceleration = 0
infill_every_layers = 10
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_speed = 60
interface_shells = 0
layer_gcode = 
layer_height = 0.4
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 10
min_skirt_length = 0
notes = 
nozzle_diameter = 0.5
only_retract_when_crossing_perimeters = 1
ooze_prevention = 0
output_filename_format = [input_filename_base].gcode
overhangs = 1
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 30
perimeters = 3
post_process = 
raft_layers = 0
resolution = 0
retract_before_travel = 2
retract_layer_change = 1
retract_length = 1
retract_length_toolchange = 10
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 30
skirt_distance = 6
skirt_height = 1
skirts = 1
slowdown_below_layer_time = 30
small_perimeter_speed = 30
solid_infill_below_area = 70
solid_infill_every_layers = 0
solid_infill_extrusion_width = 0
solid_infill_speed = 60
spiral_vase = 0
standby_temperature_delta = -5
start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle
support_material = 0
support_material_angle = 0
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_extruder = 1
support_material_interface_layers = 3
support_material_interface_spacing = 0
support_material_pattern = pillars
support_material_spacing = 2.5
support_material_speed = 60
support_material_threshold = 0
temperature = 200
thin_walls = 1
threads = 2
toolchange_gcode = 
top_infill_extrusion_width = 0
top_solid_infill_speed = 50
top_solid_layers = 3
travel_speed = 130
use_firmware_retraction = 0
use_relative_e_distances = 0
vibration_limit = 0
wipe = 0
z_offset = 0

**Comment by VanessaE** [comment]
Here's another situation where gap fill is not working:

Grab this Thing, http://www.thingiverse.com/thing:1271651 

For the sake of saving time, you might want to split it up and consider only the five gears on the right.

Notice the gears' teeth, and arguably around the center of the largest of the five.  No combination of settings causes Slic3r to fill them in.

Config bundle:  
[Prusa i3 - Slic3r 1.3.0 config bundle.ini.zip](https://github.com/alexrj/Slic3r/files/180996/Prusa.i3.-.Slic3r.1.3.0.config.bundle.ini.zip)

**Comment by alexrj** [comment]
@led42, this is how rake.stl appears with your config as of 1.2.10-dev (but this was probably already fixed in the previous versions:

![schermata 2016-03-19 alle 22 34 02](https://cloud.githubusercontent.com/assets/594957/13901400/d7b8d880-ee22-11e5-9cf3-6332a57102e6.png)

**Comment by alexrj** [comment]
@VanessaE, I fixed that in both stable and master. However, those are very very thin gaps and I'm not sure how effective/useful that gap fill is physically speaking.

**Comment by VanessaE** [comment]
It's angle-sensitive but yep, seems much better now for most of the gears in that test.
