### ISSUE TITLE
Not an issue, just a question about extrusion multiplier

### ISSUE THREAD

**Issue by clefranc** [alexrj/Slic3r#2784]
Is the `Extrusion multiplier` used when I set `Use volumetric E`, or the diameter is fixed to 1.12837916709551mm (2*sqrt(1/pi) ?

Christian

**Comment by alexrj** [comment]
Extrusion multiplier is used when volumetric extrusion is enabled.

(No diameter is involved at all in the math in that case - setting that value was a workaround needed before this was implemented natively)
