### ISSUE TITLE
Slic3r hangs on recalc when entering values

### ISSUE THREAD

**Issue by foulowl** [alexrj/Slic3r#2788]
Hello,

When attempting to enter in a value for "extrusion width", slic3r appears to do some recalculation for the gcode after each keystroke entered by user. Thus, if I start typing "1" in the field, slic3r tries to recalc, "1" is obviously a degenerate value, and slic3r then hangs for a very long period of time. I never had it finish, I had to end the process. 

Expected: slic3r does no recalc until I click the "Export" button, or at the very least until I am done typing in a number into the field in question.

Version was checked out from git yesterday. 

Thank you.

**Comment by lordofhyphens** [comment]
AFAIK this is fixed now, but you should still turn off background processing.
