### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by koclukasz** [alexrj/Slic3r#2789]
I have a problem: Every time i start slic3r it looks like i do it for the first time, configuration wizard shows and any configuration i set before is lost. Moreover when i checked expert mode in setup and restarted slic3r it started in simple mode. Any ideas how to fix this?

**Comment by gege2b** [comment]
looks like  some write permissions troubles on the folder where slic3r saves his config

more info on the OS ?

**Comment by koclukasz** [comment]
it is normal that repetier folder is "read only" ?
windows 8.1 dell inspiron5537

**Comment by gege2b** [comment]
I don't know, I don't use repetier at all
If it's installed on the "program files" directory, then maybe its normal

maybe you can specify a path in repetier for the slic3r config ?

**Comment by alexrj** [comment]
I don't really know how Repetier handles Slic3r. Try to contact Repetier's author or issue tracker. Try to give write permissions to the Repetier and Slic3r directories.
