### ISSUE TITLE
Bug 1.2.7-dev: Change in "Resolution" feature doesn't force re-slicing with background processing enabled

### ISSUE THREAD

**Issue by jonaskuehling** [alexrj/Slic3r#2795]
Hi Alex,

found this one already a while back, I think since the implementation of background processing. Changes in the "Resolution" feature (Print Settings > Advanced > Other > Resolution) seems not to be watched to trigger re-slicing when background processing is enabled.

Minor bug with low priority I guess, will just show when one tries to actually change the resolution values and observe the effects to the printing paths... But anyway, just for the records, it's there, this bug ;)

**Comment by alexrj** [comment]
Good catch! Fixed.
