### ISSUE TITLE
Thin wall generation inconsistent across Z-levels - wedge example

### ISSUE THREAD

**Issue by BurninSun** [alexrj/Slic3r#2800]
I've been having issues with thin wall generation and I've boiled it down to a relatively simple example - a wedge. The model should generate consistent gcode across all Z-levels but the thin walls at the tip of the wedge are seemingly random. With thin walls disabled, the model slices exactly how I expect - down to a minimum of 2 perimeter lines then ignoring the thin part of the tip.

Picture with 1000 words (Slic3r 1.1.7):
![wedge gcode preview 1.1.7](https://cloud.githubusercontent.com/assets/12116957/7335328/a0c829c2-eb6a-11e4-865c-63b2ff0561da.png)

Slic3r settings: http://pastebin.com/v3ubs9Fy
STL file: http://pastebin.com/Q7DqVUx0
Generated gcode: http://pastebin.com/672rUpGp

Version 1.2.6 produces notably different but still "random" results:
![wedge gcode preview 1 2 6](https://cloud.githubusercontent.com/assets/12116957/7335352/011f5934-eb6c-11e4-9482-506d9d47647f.png)

**Comment by alexrj** [comment]
Thank you for the report! This is now fixed, and I think this commit also fixes some other issues that were reported here in GitHub.

![schermata 2015-05-13 alle 20 49 34](https://cloud.githubusercontent.com/assets/594957/7618319/aa2d1324-f9b1-11e4-9054-c7af6c737954.png)

**Comment by BurninSun** [comment]
Thank you very much. While this did fix one of the major issues I had, it also created a few more (or at least somewhere between 1.2.6 and now created a few more issues). More reports to follow :)
