### ISSUE TITLE
Feature request: Option to disable retract on supports

### ISSUE THREAD

**Issue by sorki** [alexrj/Slic3r#2803]
Would greatly improve print times especially with pillars pattern.

**Comment by alexrj** [comment]
AFAIK, unless there's a bug, retraction is skipped while moving inside a single support material island.

**Comment by alexrj** [comment]
Do you have a test case showing that Slic3r is not skipping retraction when moving inside support material?

**Comment by sorki** [comment]
Sorry, forgot about this and can no longer remember what caused this.
