### ISSUE TITLE
Missing raft on thick layers

### ISSUE THREAD

**Issue by Cylindric** [alexrj/Slic3r#2814]
I'm just experimenting with a new 1.2mm nozzle, and have noticed that no raft is being created when layer height is 0.9mm or more.

I am using Slic3r 1.2.6, with a simple 20mm cube and all the (default) profiles. All I changed for the test is:

* Nozzle set to 1.2mm
* Layer height set to 0.9mm
* First layer height set to 0.9mm
* Raft set to 1

Preview - you can see the gap under the object:
![slic3rbug_preview](https://cloud.githubusercontent.com/assets/215695/7463326/80943cc0-f2b0-11e4-8412-3f51fb904fa7.PNG)

Layer 1: 0.9mm - can only see the skirt:
![slic3rbug_layer1](https://cloud.githubusercontent.com/assets/215695/7463322/7aa59368-f2b0-11e4-9df1-d3714b250583.PNG)

Layer 2: 2.3mm - straight to the object over 2mm above the bed:
![slic3rbug_layer2](https://cloud.githubusercontent.com/assets/215695/7463323/7aa5a20e-f2b0-11e4-99d5-26df5aed7b35.PNG)

**Comment by Cylindric** [comment]
Forgot to add, here's a copy of the entire config: https://gist.github.com/Cylindric/1b36d2955806b07ffc2d

**Comment by alexrj** [comment]
Fixed, thank you.
