### ISSUE TITLE
[request] skirt&brim in preview

### ISSUE THREAD

**Issue by koghe** [alexrj/Slic3r#2817]
Hi
i really like to have skirt and brim preview, is possible?
slic3r last git, ubuntu 14.04
thanks
![screenshot from 2015-05-06 00 31 34](https://cloud.githubusercontent.com/assets/745801/7484328/82602d98-f387-11e4-8031-d39f7b4970de.png)

**Comment by a4jp-com** [comment]
+1

**Comment by peter1960** [comment]
+1

**Comment by pOmelchenko** [comment]
+1

**Comment by alexrj** [comment]
Done.

**Comment by a4jp-com** [comment]
Thank you soooo much. This is so useful ^^

**Comment by koghe** [comment]
I missed the 1rst notification! 
Thanks!! really useful
