### ISSUE TITLE
When you send a file to the printer application crashes

### ISSUE THREAD

**Issue by pOmelchenko** [alexrj/Slic3r#2827]
I noticed today that when sending G-code printer (Octoprint) application crashes. If it is discovered fail with STL if was originally a Cyrillic name. When attempts through the web interface octoprint pour gcode he gave an error in the title of the Cyrillic (or rather that he does not understand the file format), but slic3r just took off without telling anything.

Ubuntu 14.04.2
slik3r 1.2.7 dev

**Comment by pOmelchenko** [comment]
As an option, it makes sense to convert the file name, when you send to the printer. For example Cyrillic transliteration in Latin script

**Comment by alexrj** [comment]
Thank you, I fixed this.
