### ISSUE TITLE
"Only infill where needed" not respecting 0% infill rates

### ISSUE THREAD

**Issue by BurninSun** [alexrj/Slic3r#2830]
Setting fill density to 0% disables the "Only infill where needed" setting, however that setting is still being taken into account for slicing.

To reproduce:
Set fill density to anything > 0%.
Check "Only infill where needed"
Set fill density to 0%

"Only infill where needed" is now disabled but checked, fill density is 0%, however it results in slicing similar to this:
![cone filled](https://cloud.githubusercontent.com/assets/12116957/7627006/872a825c-f9c6-11e4-9bff-c7c55c923587.png)

Now set fill density to > 0% again.
uncheck "Only infill where needed"
Set fill density back to 0%

"Only infill where needed" is disabled again but unchecked this time, fill density is again 0%, and slicing results in no infill as expected:
![cone empty](https://cloud.githubusercontent.com/assets/12116957/7627018/a8cb9eaa-f9c6-11e4-92ef-e5acf459dc0b.png)

This is happening with the current dev build as well as 1.2.6

Slic3r settings: http://pastebin.com/v3ubs9Fy (other than the "only infill where needed" setting)
STL file: http://pastebin.com/9j6kfvBt

**Comment by alexrj** [comment]
Well, that situation is a bit undefined. If you slice that model at ~0.3mm and you ask for top solid shells Slic3r will think that you actually need infill below them, even if you have an internal 0% density:

![schermata 2015-05-18 alle 19 56 35](https://cloud.githubusercontent.com/assets/594957/7686714/2d527a34-fd98-11e4-9991-37a0a7e4f932.png)

I think that slicing a model like that with fill_density = 0 and top_solid_layers = 2 has no valid solutions anyway. No?

**Comment by BurninSun** [comment]
I agree that there is not a valid solution with no infill but after setting the infill to 0%, I cannot turn back on the "infill where needed" option because it is disabled. A fix would be one of two changes:

Option 1:
"Only infill where needed" isn't disabled with infill set to 0%. This would let us turn it on if need be, or if sometime in the future we manage to calibrate printers well enough that they can print what is essentially a curved bridge, we would have the option of turning it off.

Option 2:
Force "Only infill where needed" to be on when infill is at 0% so that the print is still valid.

The main problem right now is that the option affects slicing output even though the option is disabled and cannot be changed.

**Comment by alexrj** [comment]
*Only infill where needed* is now ignored when Fill Density = 0%.
