### ISSUE TITLE
slic3r.pl options like --print-center requiring a float value on Arm7 with Perl 5.20.2

### ISSUE THREAD

**Issue by andrewhodel** [alexrj/Slic3r#2840]
Passing --print-center 0,0 will result in the Y axis being off by 1000mm from the center of 0,0.

In order to get it to work, floats must be passed as 0.0,0.0

--layer-height complains as well when a value like .3 is used, 0.3 works.

Seems to only happen on single digit or single decimal values so it may not be a float issue but a conversion issue from passed arguments.

**Comment by alexrj** [comment]
Very weird, I can't reproduce this on 5.14.

**Comment by alexrj** [comment]
Parsing was rewritten since then. Issue should be gone.
