### ISSUE TITLE
1.2.6 Experimental gets stuck on this STL (Windows 7 64-bit)

### ISSUE THREAD

**Issue by WZ9V** [alexrj/Slic3r#2842]
This STL file consistently crashes in the "triangulating mesh" phase in Windows 7 64-bit.

http://www.thingiverse.com/download:405692

**Comment by gege2b** [comment]
confirmed in 1.2.7-exp too (same OS)

**Comment by alexrj** [comment]
Same thing as #2471: file has multiple "solid" definitions, so it's technically a bad STL file. Slic3r needs to be more tolerant since apparently there is some CAD out there that produces these wrong files.

**Comment by alexrj** [comment]
I fixed this. Thank you for reporting.

**Comment by WZ9V** [comment]
Thanks.  I assume its fixed in 1.2.8 because 1.2.7 is still crashing on this one.

**Comment by alexrj** [comment]
Yes, it's fixed in 1.2.8-dev.
