### ISSUE TITLE
Skirt floating in the air in 3D preview an not exported

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#2843]
Hi all
Spotted a bug right now.
It happens when I set more than 1 raft layer (other config or model independant)

The 3D preview shows the skirt on the upper raft layer only
The Layer view is OK

The exported Gcode doesn't contain skirt at all

Debian Jessie 64b
Current dev

config : https://dl.dropboxusercontent.com/u/34934879/config-skirt.ini
example gcode : https://dl.dropboxusercontent.com/u/34934879/octopus_body.gcode

![slic3r-raft-skirt](https://cloud.githubusercontent.com/assets/2814966/7787365/72e0511a-0208-11e5-8be6-68d9d6353bf6.png)

![slic4r-raft-skirt2](https://cloud.githubusercontent.com/assets/2814966/7787368/75e468e2-0208-11e5-882c-ed1d26c3bc90.png)

and on the next layer :

![slic4r-raft-skirt3](https://cloud.githubusercontent.com/assets/2814966/7787374/b2e90b58-0208-11e5-9e4d-69b0ddeeade9.png)

**Comment by alexrj** [comment]
Hah, nice catch there...

**Comment by alexrj** [comment]
![skirt_floating_in_the_air](https://cloud.githubusercontent.com/assets/594957/7787718/d5c3fa4a-021a-11e5-9c6d-d57038a9aec0.jpg)

**Comment by alexrj** [comment]
Fixed. Thank you for the report.
