### ISSUE TITLE
1.2.7: No way to close "Help -> About"

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#2847]
I updated Slic3r from git (revision 249a48d68d8bab5302fc8adbe4a304c3bffeb02a) and built it on Ubuntu 14.04. I clicked Help -> About, and then my screen looked like this:

![slic3r-1 2 7-help-about](https://cloud.githubusercontent.com/assets/684832/7789696/17e6caa2-026a-11e5-9d7f-ec74afab69e3.png)

I can't find a way to close the About screen, so I ended up having to kill Slic3r to get out of it. There's nothing to click, and I tried to hit ESC, Enter, and various other keys to remove it, but nothing seemed to help. Am I missing something, or is this a bug?

**Comment by alexrj** [comment]
We'll probably need an "OK" button for handling that. See #2688 (I'm closing this one as you don't mind to avoid duplicates)

**Comment by kefir-** [comment]
Sorry I missed that this was a duplicate. Thanks.
