### ISSUE TITLE
1.2.6 missing perimeter segment on gcode export

### ISSUE THREAD

**Issue by hon-po** [alexrj/Slic3r#2849]
On win 7 64 bit system, slice 20x20x5 cube, path on layers view look OK:
![capture](https://cloud.githubusercontent.com/assets/7111240/7796689/6d8495fc-0314-11e5-9796-325b48723d61.PNG)
But exported gcode miss one perimeter segment:
![capture1](https://cloud.githubusercontent.com/assets/7111240/7796722/da87daec-0314-11e5-8662-19c14116d6c8.PNG)
This is repeating for all layers with fill density more than ~52%
Config:
https://drive.google.com/file/d/0B4bLJHgWDzxfdE5seGUxc1pKcDA/view?usp=sharing
stl:
https://drive.google.com/file/d/0B4bLJHgWDzxfN0JfaC1ENVVUdlE/view?usp=sharing
gcode:
https://drive.google.com/file/d/0B4bLJHgWDzxfMEtWVVRnak0wVVU/view?usp=sharing

**Comment by lordofhyphens** [comment]
1.2.7 just came out, could you try that version and see if your problem
still exists?

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by alexrj** [comment]
Yes, there was a bug in an upstream library that causes that problem in 1.2.6.
This should be fixed as of 1.2.7. We'll wait for your confirmation, @hon-po. Thank you!

**Comment by hon-po** [comment]
My bad, this is a repetier-host 1.0.6 not displaying the segment after G92 E gcode. I was trying pressure advance at 0.3. Craftware display the segment correctly.
![capture2](https://cloud.githubusercontent.com/assets/7111240/7798961/fb69419c-0332-11e5-85a4-a9d9cfc7ed74.PNG)
No problem with both 1.2.6 & 1.2.7. Thanks!
