### ISSUE TITLE
1.2.7 About Slic3r window cannot be closed. (Windows OS)

### ISSUE THREAD

**Issue by hon-po** [alexrj/Slic3r#2851]
Win 7 64 bit OS.
Missing button to close window, but focus remain on about window. Need to kill Slic3r to continue.
![capture4](https://cloud.githubusercontent.com/assets/7111240/7799127/f8459c16-0334-11e5-9859-c0c7803038cc.PNG)

**Comment by ignaworn** [comment]
I can confirm that also happens on Win10
Slic3r 1.2.7 experimental.

**Comment by peter1960** [comment]
ALT-F4 will close it if your get stuck

**Comment by hon-po** [comment]
Thanks!
ALT-F4 is good in closing the window.
Wonder should I close this issue?

**Comment by a4jp-com** [comment]
I don't think closing this thread is a good idea yet. 

I think that the about screen should:

Have a close button somewhere,
it should close when you click on it anywhere besides the links,
it should close when you click any area besides the box,
or it should at least say press alt + f4 to close until it gets fixed.

**Comment by alexrj** [comment]
There's #2688

**Comment by hon-po** [comment]
I am closing this as it is already referenced in #2688 
I add (Windows OS) to the title, so it will be obvious in that thread. Thanks everyone.
