### ISSUE TITLE
Crash when loading large volume objects

### ISSUE THREAD

**Issue by cocoknight** [alexrj/Slic3r#2853]
I had some issues with Slic3r when I tried to open poorly scaled and therefore huge models. If a model is too big by its dimensions Slic3r crashes when adding it. I had this issue with for example this model:
http://www.thingiverse.com/thing:220423/#files
A solution would be to check the bounding box of a model before adding it to the build platform and scaling it down by a specific factor (e.g. 1000) if the units are obviously wrong.

Windows 7 x64
Slic3r 1.2.6/1.2.7

**Comment by alexrj** [comment]
That's a great idea. I added a size check that scales the object to fit the print bed and warns user if it is too large.

**Comment by a4jp-com** [comment]
Nice
