### ISSUE TITLE
Request: offset between lines in solid infill to improve layer adhesion

### ISSUE THREAD

**Issue by rsatue** [alexrj/Slic3r#2856]
Hi,

I am working on a part in which it is necessary to have some solid infill because it is mechanically solicited. 

Currently slic3r is printing each layer over the previous one resulting in the following: 
![current](https://cloud.githubusercontent.com/assets/10961065/7807781/a23765b6-038e-11e5-9158-b5da506ae404.jpg)

It would probably improve the mechanical response of the part if we could print the layer with an offset equal to half the extrusion width. The result would look this way:
![offset](https://cloud.githubusercontent.com/assets/10961065/7807815/e25f98c0-038e-11e5-99a4-b730ff0b0ec3.jpg)

It would be necessary to increase a little the amount of material extruded but I think it could result in an improved print. 

What do you think?

Of course this option would only apply to solid infill layers. 

Thanks in advance.

**Comment by alexrj** [comment]
Actually, solid infill layers are cross-hatched (i.e. each layer is rotated by 90°), so they don't reflect your first drawing.

**Comment by whosawhatsis** [comment]
What would be even better would be to print alternating lines at half a layer heigh offset, so that they are packed hexagonally rather than rectangularly. You also wouldn't get the problem with the half-extrusion-width gaps at the edges shown here.
