### ISSUE TITLE
Incorrect concave seam point detection when inside loops

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#2857]
When there is one convex point in an inside closed loop (a hole), it is choosed as the perimeter start point instead one of the other concave ones (outside concave points are detected and used)

![cube-convex-inside](https://cloud.githubusercontent.com/assets/288246/7814722/42384dfc-03c4-11e5-8ec3-1590d91566ab.png)

`config.ini`: https://gist.github.com/xoan/7b3c230fdda1e4fc2a2f (it is also reproducible with de `default`config)

[OpenJSCAD](http://openjscad.org/) compatible code to generate the STL:
```openscad
//!OpenSCAD
difference() {
	cube([20,20,10], center = true);
	translate([10,10]) cube([10,10,20], center = true);
	difference() {
		cube([10,10,20], center = true);
		translate([5,5]) cube([10,10,20], center = true);
	}
}
```

**Comment by alexrj** [comment]
Good catch. I fixed this and added a regression test.
