### ISSUE TITLE
Why is first layer so dense when first_layer_extrusion_width 100%?

### ISSUE THREAD

**Issue by Cylindric** [alexrj/Slic3r#2859]
I have a simple 20mm cube, that I sliced with all the default profile settings in Slic3r 1.2.7.

If I leave the first_layer_extrusion_width at the default 200%, things look pretty normal for the first and second layers:

![slic3rbug_layer1-default](https://cloud.githubusercontent.com/assets/215695/7834568/7bbe1508-0468-11e5-8708-879158c7874a.PNG)
![slic3rbug_layer2-default](https://cloud.githubusercontent.com/assets/215695/7834569/7bc1be88-0468-11e5-9b42-2dee3e23432b.PNG)

But if I set first_layer_extrusion_width to 100%, the first layer looks like this:

![slic3rbug_layer1-100](https://cloud.githubusercontent.com/assets/215695/7834584/8f00cbce-0468-11e5-9f46-0ac29301fb28.PNG)

Is that normal?

I only really noticed because I was getting massive over-extrusion on my first layer, so thought I'd take off the default 200% first layer setting.

The reason it's a problem for me, is because when I use a large nozzle (tried with 0.8mm), I get what looks like a related problem.
Here's what layers 1 and 2 look like with all the default settings, apart from the nozzle changed to 0.8mm:

![slic3rbug_layer1-800](https://cloud.githubusercontent.com/assets/215695/7834630/0d0700d8-0469-11e5-8b96-5e2491a48ad1.PNG)
![slic3rbug_layer2-800](https://cloud.githubusercontent.com/assets/215695/7834631/0d0b40a8-0469-11e5-969a-62fa43c94708.PNG)

This results in massive over-extrusion on layer 1.

**Comment by xoan** [comment]
When extrusion width is configured by a %, it is relative to layer height, so ¿what is your first layer height?

**Comment by alexrj** [comment]
The behavior you're describing is correct and expected. As pointed out by the previous comment, when extrusion width is expressed in % it's relative to later height.
If you get overstuffing on first layer you need to raise your Z end stop a bit.
