### ISSUE TITLE
OSX: Add "cmd+,"-hotkey to open preferences

### ISSUE THREAD

**Issue by luclu** [alexrj/Slic3r#2860]
for standard osx user-experience.

Is this possible with wx? 
Or is it binding ```Ctrl / Cmd``` and so confusing Win-users with ```Ctrl+,```?

**Comment by alexrj** [comment]
Thank you, I did it.

Yes, Ctrl and Cmd are bound by the GUI toolkit we use, but I don't know whether there's a standard shortcut for Windows so let's see if someone complains for this.

**Comment by luclu** [comment]
:heart: cool! :)

**Comment by mikenew12** [comment]
Are you sure this is right? The only preferences hotkey I've ever seen has always been '⌘,' (command comma). I just tested on the half dozen programs I have open right now, and that's they hotkey for each one.

**Comment by luclu** [comment]
@mikenew12 yeah, you are totally right!
the GUI-toolkit in use makes ```Ctrl+,``` to ```Cmd+,```on osx and ```Ctrl+,```on win.

**Comment by alexrj** [comment]
Exactly @mikenew12, that's what Slic3r now has.

**Comment by mikenew12** [comment]
Ha, sorry guys. I completely misread the title here. Sneaky comma.
