### ISSUE TITLE
[1.2.7-exp] wheel zoom inverted in Layer tab

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#2861]
Hi all

Another little anoying thing spotted right now

The wheel zoom is inverted (and so, less intuitive) in layers tab, compared to 3D, and 3D Preview ones

Win7 x64, Slic3r 1.2.7 exp

cheers

**Comment by alexrj** [comment]
Yes... also @simonkuehling noticed that.  The current scrolling direction is the same as other 2D programs like Adobe Illustrator. I guess that opposite conventions are used for 2D programs vs 3D programs. Not sure what are the recommended ones. Maybe it's just better to have them aligned whatever they are. Dunno.

**Comment by simonkuehling** [comment]
i couldn't really find a universal convention in scroll wheel zooming direction either to date - but i agree that aligned behavior is probably the least obtrusive...

For my very own personal taste i would initially expect to zoom in when pulling the wheel into my direction - but that's not even consistent through 3D programs i use (actually 1:1 right now when switching through my currently open windows)..

**Comment by gege2b** [comment]
I find the zoom in 3D / Preview tabs are more intuitive, but it's only my opinion ^_^

maybe add an option in slic3rs preferences ?

**Comment by a4jp-com** [comment]
+1 for an option for people to choose the way the mouse wheel zooms.

**Comment by Lenbok** [comment]
Ewww, the current direction is horrid! :-)

Web browsers zooming (ctrl-wheel) use zoom in on wheel push, same as slic3r 3D panes.

**Comment by a4jp-com** [comment]
I think the only problem is the "3D" and "Preview" tab zoom one way, but the "Layers" tab is reversed. If they are all zooming the same way it would be nice. Then having an option to reverse all or each direction in a settings area would make Slic3r even better, being slightly customizable. 

You can now press ctrl and zoom with the mouse wheel but I definitely don't want to have to push ctrl to zoom every time. Having it the way it is now is nice though to support everyone. The mouse wheel works well the way it is now. Zoom with the mouse wheel then pan by pressing down the middle scroll wheel.

**Comment by ghuser2** [comment]
My 2D tab does not zoom at all. Nobody mentioned it, so that's probably how it is.

**Comment by Lenbok** [comment]
Addressed by PR #3749

**Comment by lordofhyphens** [comment]
@ghuser2 FYI, it's the 2D layer preview tab that has a zoom function.
