### ISSUE TITLE
1.2.7-Printer Setup TAB Change extruders from 1 to 2

### ISSUE THREAD

**Issue by billkaroly** [alexrj/Slic3r#2863]
When I change Extruders from 1 to 2 it almost always crashes. I an using Windows 7 64 bit.

**Comment by peter1960** [comment]
I just tried and see the same crash

**Comment by billkaroly** [comment]
It happened in the previous experimental as well.

*Bill Karoly*
Product Manager
BoxBOT
*Email*: bill@boxbot.net
*Tel*: +1.801.784.8090

**Comment by alexrj** [comment]
I'm not able to make it crash, however I noticed some concurrency issues that I just fixed. Is any of you able to test from git?

**Comment by a4jp-com** [comment]
I have just updated 1.2.8-dev and went to the print settings area and changed the extruders from 1 to 2 and nothing crashed. All looks good here.

Windows 7 64-bit

**Comment by alexrj** [comment]
@billkaroly, @peter1960, can you try with 1.2.8 and confirm this was fixed? Thank you!

**Comment by billkaroly** [comment]
I'll give it a try. I'm using Windows 10 now though if that makes a
difference.  I can try it on another computer with windows 7 64 though

**Comment by billkaroly** [comment]
Looks good in win10 64. So far.
