### ISSUE TITLE
Slic3R 127 at Ubuntu failed to launch due 'GLXBadRenderRequest'

### ISSUE THREAD

**Issue by docMP** [alexrj/Slic3r#2867]
Hi,
I so needed the new (127) version, and now I can't get is running on 64bit Ubuntu 14.04:
Files downloaded (slic3r-linux-x86_64-1-2-7-experimental.tar.gz	2015-05-24 18:20 	16M	 ) and extracted, then I try the same as with v126, to get the error:

~/Documents/3d/Slic3r_1_2_7/bin$ ./slic3r 
The program 'slic3r' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadRenderRequest'.
  (Details: serial 813 error_code 175 request_code 155 minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by alexrj** [comment]
Hello, merging with #2850
