### ISSUE TITLE
Crash when launching on Ubuntu 15.04 64 bits

### ISSUE THREAD

**Issue by avalero** [alexrj/Slic3r#2868]
PC: DELL XPS 13
Ubuntu Version: 15.04 64 bits
Slic3r Version: 1.2.7

Error message:
The program 'slic3r' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 541 error_code 2 request_code 154 minor_code 24)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Stable version of Slic3r works properly

**Comment by avalero** [comment]
When compiling from code it works

**Comment by alexrj** [comment]
Hello, merging with #2850
