### ISSUE TITLE
1.1.7 : AMF files use material id="0"

### ISSUE THREAD

**Issue by bobc** [alexrj/Slic3r#2871]
The AMF file produced contains material spec for id ="0" : 

 &lt;material id=&quot;0&quot;&gt;
    &lt;metadata type=&quot;Name&quot;&gt;&lt;/metadata&gt;
  &lt;/material&gt;
  &lt;material id=&quot;1&quot;&gt;
    &lt;metadata type=&quot;Name&quot;&gt;&lt;/metadata&gt;
  &lt;/material&gt;
  &lt;material id=&quot;2&quot;&gt;
    &lt;metadata type=&quot;Name&quot;&gt;&lt;/metadata&gt;
  &lt;/material&gt;

According to AMF spec http://en.wikipedia.org/wiki/Additive_Manufacturing_File_Format#Material_specification material id = "0" is reserved for void spaces (i.e holes). The wiki article was a bit vague but the ASTM spec makes it clear "0" is reserved (section 7.1 of ISO/ASTM 52915:2013(E))

Therefore, material ids should be numbered from "1".

**Comment by alexrj** [comment]
Thank you for pointing that out.

**Comment by alexrj** [comment]
Starting from 1.2.x Slic3r does not use AMF materials anymore but it puts config options inside <object> and <volume> metadata tags.  Files with materials are still read for backwards compatibility. I added a comment in the source code that will serve as a reminder should we start using materials anytime in the future. Thank you for your report.
