### ISSUE TITLE
1.2.7 64bit locks up on win 8.1 when I select 'help > about Slic3r'

### ISSUE THREAD

**Issue by ML3D** [alexrj/Slic3r#2876]
Just what the title says, that's all. I've been able to repeat this 3 times in a row. Maybe someone else with the same setup can try it...

**Comment by Mikk36** [comment]
Duplicate of https://github.com/alexrj/Slic3r/issues/2688

**Comment by alexrj** [comment]
@ML3D, can you confirm this issue is about the inability to close the About window since there's no close button?

**Comment by ML3D** [comment]
Yes, I'm sure that's it. I was just thinking I could escape it, or click it or click off of it to make it close. Sorry for the duplicate.

**Comment by alexrj** [comment]
No problem @ML3D, I fixed this.
