### ISSUE TITLE
Slic3r 0.7.1 for windows crashes using Wine/Network

### ISSUE THREAD

**Issue by mrseeker** [alexrj/Slic3r#288]
Invalid or missing application map loader. Try re-installing the application to a clean directory. No such file or directory at <Packaged Modules>/Application::Loader line 1286.

Bug can be reproduced by running an executable which is:
1. On another PC and connected by a local network (local share).
2. On Linux using Wine.
3. On Windows using an unzipped map from Linux.

Suggested problem could be caused by using "\" as the root map instead of "c:\".

**Comment by lordofhyphens** [comment]
Going to  close this; just use a native build of Slic3r; the profiles are  compatible with each other.
