### ISSUE TITLE
Strange Bridging Detection Problem version 1.2.6

### ISSUE THREAD

**Issue by Mandlbaur** [alexrj/Slic3r#2889]
I have a strange issue with a design of mine where one arm is correctly detected as a bridge, but the other is not.   http://www.thingiverse.com/thing:865652

![screen shot 2015-06-05 at 1 09 17 pm](https://cloud.githubusercontent.com/assets/9879094/8004902/4d3e9a72-0b84-11e5-9a48-096084afa8ab.png)
![screen shot 2015-06-05 at 1 09 33 pm](https://cloud.githubusercontent.com/assets/9879094/8004903/5197c152-0b84-11e5-9c94-31d64c975268.png)

**Comment by Mikk36** [comment]
I believe this has been fixed already, not sure if it made it into the 1.2.7 or will come with 1.2.8 release.
If you'd like, it's already available in the git version.

**Comment by Mikk36** [comment]
Yup, works as you'd expect in latest git version:
![Bridging](https://dl.dropboxusercontent.com/u/54281287/slic3rBridge.PNG)

**Comment by xoan** [comment]
It is fixed in 1ab8efb (see #2636)

**Comment by Mandlbaur** [comment]
Thanks for the feedback guys
