### ISSUE TITLE
[1.2.8-dev] UI allows travel speed to be set to 0, which produces F0 gcode

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#2893]
From the notes on the autospeed feature, I thought it would also control travel moves, so I set it to 0. 

While autospeed not affecting travel is not necessarily a bug, that the UI allows obviously bad gcode to be generated like this is a bug. Thankfully, it's easy to fix (I think).

I see one of two ways out here:
1) Disallow a value of "0" for travel speed in the UI. 
2) If travel speed is set to "0", just don't put a F command in (so it uses the last speed). 

I'm leaning more towards 1), as it looks like it's the shortest solution with the fewest surprises. 

Reproduction steps:
1) Load any STL you please. 
2) Print Settings -> Speed
3) Set "Travel Speed" to 0.
4) Export to gcode
5) Try to print
6) Watch as your printer tries to move at speed 0 to some coordinates.
7) :(

**Comment by alexrj** [comment]
Heh, right.  I fixed this by fixing the validation that is applied to those values
