### ISSUE TITLE
1.2.7 Changing the infill extrusion width creates gap between perimeters and solid infill

### ISSUE THREAD

**Issue by noname21** [alexrj/Slic3r#2895]
If the infill extrusion width is broader than the solid infill extrusion width, there is a gap between the perimeters and the solid infill, from the second layer to the top of the object.

Taking the default settings and changing the layer hight to 0.1 mm also creates the problem:

![unbenannt](https://cloud.githubusercontent.com/assets/12811818/8055889/56b4085e-0ea3-11e5-8e50-aba023b00cdd.PNG)
![unbenannt2](https://cloud.githubusercontent.com/assets/12811818/8055888/56b314f8-0ea3-11e5-866c-ba44118a18a1.PNG)
![unbenannt3](https://cloud.githubusercontent.com/assets/12811818/8055890/56b665ae-0ea3-11e5-8e2d-1059aba977e6.PNG)

**Comment by alexrj** [comment]
Good catch!  I fixed this now.
