### ISSUE TITLE
Wide Character error(1.2.7/1.2.8)

### ISSUE THREAD

**Issue by truelife2** [alexrj/Slic3r#2898]
hi,

when i open stl file or save gcode file 
if the file path contains wide character 
 will alert wide character error.

like this

![widecharacter](https://cloud.githubusercontent.com/assets/12017748/8072920/1794a086-0f50-11e5-8540-f3986e6239f6.png)

**Comment by alexrj** [comment]
wtf

**Comment by pOmelchenko** [comment]
I had a similar problem if the Cyrillic Fail had the title as soon as me everywhere on the Latin alphabet problem was solved

**Comment by alexrj** [comment]
Should should be definitely fixed as of 552430db679cbceebe5b7db761c5624fd53eead7. Releasing shortly.
