### ISSUE TITLE
Wrong infill in 1.2.8

### ISSUE THREAD

**Issue by rsatue** [alexrj/Slic3r#2899]
Same part, same config.ini are resulting in different infills. Obviously the 1.2.8 infill is wrong.

Here is the part sliced with 1.2.7:
![2](https://cloud.githubusercontent.com/assets/10961065/8078822/a1f3b824-0f60-11e5-8ccf-f6f50f53d272.jpg)

And here, with 1.2.8: 
![1](https://cloud.githubusercontent.com/assets/10961065/8078836/b45fcb88-0f60-11e5-998c-a7f3363f1385.jpg)

When reading the gcode it confirms that in those points there are huge extrusions without any reason. 

The part file: https://www.dropbox.com/s/ptuz0lpd4fb0svj/bug%20part.stl?dl=0
The config file: https://www.dropbox.com/s/o1spfalo2arcqya/nozz06.ini?dl=0

**Comment by alexrj** [comment]
Ouch.  Last minute change resulted in horrible effect.

**Comment by alexrj** [comment]
Actually, this looks more like a rendering issue than a real infill issue as it's not noticeable in 2D toolpaths nor in other 3D preview tools. I'll investigate further.

**Comment by alexrj** [comment]
Fixed. Thank you for reporting this.
