### ISSUE TITLE
Perimeter pieces stick out in different directions.

### ISSUE THREAD

**Issue by lonelymyp** [alexrj/Slic3r#2910]
Slic3r 1.2.7
![default](https://cloud.githubusercontent.com/assets/2085051/8145870/ae4839e6-1222-11e5-978e-6950cd408188.jpg)

Config:
https://drive.google.com/file/d/0B2sGop41unyOZmdQSE5BTHVETEE/view?usp=sharing
STL: 
https://drive.google.com/file/d/0B2sGop41unyOTWN2UXpxNFljVVU/view?usp=sharing

**Comment by alexrj** [comment]
Does Slic3r's 3D preview show those?

**Comment by alexrj** [comment]
Does they show also in any 2D preview like Slic3r's one, Pronterface or http://gcode.ws ?

**Comment by lonelymyp** [comment]
Yes, the same.
![default](https://cloud.githubusercontent.com/assets/2085051/8145979/5266829e-1228-11e5-997a-4229280f4406.jpg)

**Comment by lonelymyp** [comment]
G-code:
https://drive.google.com/file/d/0B2sGop41unyOS1RMQ3ZsbHNtVDA/view?usp=sharing

**Comment by alexrj** [comment]
Okay, this is Slic3r trying to generate the thin walls for some of the teeth:

![schermata 2015-06-14 a 11 34 27](https://cloud.githubusercontent.com/assets/594957/8148052/6f7e9284-1289-11e5-81c7-f39bb11db6e0.png)

**Comment by alexrj** [comment]
I fixed this. However I'd like to do more work on it.

**Comment by lonelymyp** [comment]
Thank you.
