### ISSUE TITLE
1.2.8-dev 1st layer and 2nd layer around the wrong way or miscalculated. Also top layers not touching edge.

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2913]
My first layer is set for 0.3mm so it should be bigger with less lines than the second layer set at 0.21mm. The layers are reversed for some reason. Can you flip these the right way around please?

http://a4jp.com/3d-files/bugs/2015-06-15th-12-12-am-for-github-config.ini
http://a4jp.com/3d-files/bugs/cube20bmm.stl

![screen shot 06-15-15 at 12 24 am](https://cloud.githubusercontent.com/assets/9621044/8149155/fcdfed92-12f4-11e5-9aa6-892faabb3a7a.JPG)

Layer 1: 0.3mm is not 0.3mm but 0.21mm
![screen shot 06-15-15 at 12 19 am](https://cloud.githubusercontent.com/assets/9621044/8149146/bc0a9948-12f4-11e5-9514-785f7749d2bf.JPG)

Layer 2: 0.21mm is not 0.21mm but 0.3mm
![screen shot 06-15-15 at 12 19 am 001](https://cloud.githubusercontent.com/assets/9621044/8149145/bc0750c6-12f4-11e5-9170-24cb0665cfdb.JPG)

Here the bottom layer is thicker which looks right.
![screen shot 06-15-15 at 03 08 am](https://cloud.githubusercontent.com/assets/9621044/8149790/066c68f6-130c-11e5-9eec-ca5d3dcd2607.JPG)

**Comment by kefir-** [comment]
You should file separate issues for separate problems. 

Don't know about the second issue, but what's wrong with the first and second layers of the box? What do you mean by "bigger" and "smaller"? From your pictures it looks like the layer heights are correct. It doesn't look like you've specified any extrusion widths, so a 0.3mm layer height will result in thinner extrusions than a 0.21mm layer. It looks right to me.

**Comment by a4jp-com** [comment]
0.3mm is bigger so the bottom layer should have less lines. 0.3mm is bigger than 0.2mm. I'm sure this is a mistake in the program.

**Comment by a4jp-com** [comment]
Hi kefir, I just fixed this post and made it one layer issue. I thought putting both together would be useful but will make another post for objects not having top or bottom layers.

**Comment by kefir-** [comment]
0.3mm is the layer height. You're extruding a cylinder of plastic from your printer's hotend, and if you squeeze that to thinner layers, the extrusion will be wider. That results in fewer lines in your second layer. Conversely, when you print a thicker layer it'll be squeezed less, and you'll have thinner extrusions, like in your first layer. 

If you want wider (bigger?) extrusions and fewer lines *and* a thicker first layer, you'll need to change your first layer extrusion width under advanced settings.

**Comment by a4jp-com** [comment]
I understand that but my setting is default in the Advanced section. I'm not choosing to make it fatter and flatter as the instruction say. If I want it to do that I know I can set it there but it is at the default of 0.

**Comment by a4jp-com** [comment]
![screen shot 06-15-15 at 03 28 am](https://cloud.githubusercontent.com/assets/9621044/8149869/a8c28b10-130e-11e5-9a0f-6b2bffc26692.JPG)
![screen shot 06-15-15 at 03 27 am](https://cloud.githubusercontent.com/assets/9621044/8149870/a8c67388-130e-11e5-9494-d67f79b25d33.JPG)

I think something is wrong with the calculation.

**Comment by a4jp-com** [comment]
![screen shot 06-15-15 at 03 30 am](https://cloud.githubusercontent.com/assets/9621044/8149874/fb40684e-130e-11e5-8766-4a2b52225fa0.JPG)

I couldn't delete the 0.21 number from the field.

**Comment by a4jp-com** [comment]
There are also 5 layers instead of 3 like I set.

**Comment by a4jp-com** [comment]
I just changed the bottom layer count to 2 but there was a 4th and 5th layer.

**Comment by a4jp-com** [comment]
![test](https://cloud.githubusercontent.com/assets/9621044/8149913/cc2b59d6-1310-11e5-88cf-c56469ef470f.gif)

I made a mistake pointing at the top 3 but the bottom 3 is what I was meant to be pointing at.

**Comment by alexrj** [comment]
I don't see the problem. A thicker layer (in Z) will have thinner extrudates (in XY), so more lines. It's normal.

**Comment by a4jp-com** [comment]
If 3 layers are set the extra layers are part of a bug, aren't they?

**Comment by a4jp-com** [comment]
![gif2](https://cloud.githubusercontent.com/assets/9621044/8165960/9442640a-13cf-11e5-99d5-b7cb81c144ff.gif)

**Comment by a4jp-com** [comment]
Everything looks okay now in 1.2.9-dev ^^

![gif6](https://cloud.githubusercontent.com/assets/9621044/8214779/86343c9c-1566-11e5-8d23-5c0a8e944b4b.gif)
