### ISSUE TITLE
Slic3r 1.2.8 GUI crashes while loading a broken STL (Dremelfuge_V4.stl)

### ISSUE THREAD

**Issue by hyperair** [alexrj/Slic3r#2914]
Problematic thing: http://www.thingiverse.com/thing:1483
Problematic STL: http://www.thingiverse.com/download:5775

Steps to reproduce:
1. Launch Slic3r
2. Click add
3. Select this stl.
4. Crash.

Command line output:
```
% slic3r
threads.pm >= 1.96 is required, please update
Something is syntactically very wrong with this ASCII STL!: Resource temporarily unavailable
Illegal division by zero at /usr/share/perl5/Slic3r/GUI/3DScene.pm line 281.
```

**Comment by alexrj** [comment]
Thank you!  Turned out the STL file is almost valid, and the recent changes I did for making our STL parser stronger made it more strict on this thing. Now fixed.
