### ISSUE TITLE
Slic3r 1.2.8 prints gaps between infill edges and perimeter, then does gapfill

### ISSUE THREAD

**Issue by hyperair** [alexrj/Slic3r#2918]
The shape's a simple cylinder, and it's doing one of the top solid layers (but not the topmost). The topmost solid layer appears to be done correctly (possibly due to a different extrusion width).

![screenshot16](https://cloud.githubusercontent.com/assets/88355/8180750/db00e000-1452-11e5-98ce-41b81c3514f4.png)

Test STL: https://gist.github.com/hyperair/3e658c7079345526f3c3

**Comment by hyperair** [comment]
G-code in question: https://gist.github.com/62c2f0124f3892e380c2

**Comment by a4jp-com** [comment]
https://github.com/alexrj/Slic3r/issues/2913

My point is kind of the same. The infill isn't touching the perimeter.

**Comment by alexrj** [comment]
@hyperair, actually that's not gap fill. That's internal infill.  Look at layer 5.20mm:

![schermata 2015-06-17 alle 00 39 39](https://cloud.githubusercontent.com/assets/594957/8196186/5c824aca-1489-11e5-8b56-daf539170e91.png)

Then let's go down one layer:

![schermata 2015-06-17 alle 00 40 02](https://cloud.githubusercontent.com/assets/594957/8196192/6b018fde-1489-11e5-9fa6-325437c64117.png)

As you see, that's normal internal infill which is built below the upper part.
We could say that it's very narrow and Slic3r should merge it with the adjacent solid infill, but I'd say that this behavior does not create problems as it's not visible from the outside and it's also consistent with what Slic3r normally does for any shape.

**Comment by hyperair** [comment]
Oh yeah you're right. Sorry for the noise.
