### ISSUE TITLE
1.2.9-dev settings missing

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2919]
All the saved settings are missing from the plater view.

![gif3](https://cloud.githubusercontent.com/assets/9621044/8181189/ef2458da-145e-11e5-9c6a-16cc76182401.gif)

**Comment by alexrj** [comment]
What are your Wx and wxWidgets versions?  You can read them by launching Slic3r with the `--debug` option.

**Comment by a4jp-com** [comment]
I'll check. Thank you for the reply.

**Comment by alexrj** [comment]
Can you try to update wxWidgets? You need to issue the following command: `cpanm -v Alien::wxWidgets`.

**Comment by a4jp-com** [comment]
Done.

![screen shot 06-17-15 at 06 32 pm](https://cloud.githubusercontent.com/assets/9621044/8203800/5502bbe0-151f-11e5-80e4-941706b093f0.JPG)

**Comment by alexrj** [comment]
Hm, that screenshot shows that wxWidgets wasn't actually updated to 3.0.2. Can you now do `cpanm -v --reinstall Wx` ?

**Comment by a4jp-com** [comment]
Doing it just now ^^

![screen shot 06-17-15 at 09 52 pm](https://cloud.githubusercontent.com/assets/9621044/8207304/839af7d0-153b-11e5-9245-219a278bcb25.JPG)

**Comment by a4jp-com** [comment]
The options are back now just a few icons are messing but everything is good ^^ Thank you soooo much.

![gif4](https://cloud.githubusercontent.com/assets/9621044/8208269/c2c99c8a-1541-11e5-9f10-8703d20cc505.gif)

**Comment by a4jp-com** [comment]
Just the filament icons are missing. Maybe this is very easy to fix now.

**Comment by xoan** [comment]
Filament dropdown menu options has no iconos but square color you can configure un The proper Filament Settings tab.

**Comment by a4jp-com** [comment]
I see. I changed the color and the icon changed. So I guess that is all good but none of the actual preview colors changed. What are the colors for? Just the menu icons? Or should the model change color as well?

**Comment by xoan** [comment]
Just for easy identification.

**Comment by a4jp-com** [comment]
Okay. So I can close this as everything works now ^^

Just one last thing, if the actual 3D Preview color changed this would be very cool.

Or the top filament default should also have the color square icon and not the actual filament icon as it is a bit confusing.

All my colors are white so it just looks like the icons are missing. 

Even a light #ccc 1px border would be nice.

**Comment by a4jp-com** [comment]
@alexrj thanks for fixing this.

**Comment by alexrj** [comment]
Yes, I'll probably add a 1px border. But I don't know what would be the appropriate color for the default preset, so I think it's better to stick with a generic icon.
Using that color for the 3D preview is definitely in my plans.

**Comment by a4jp-com** [comment]
Okay ^^
