### ISSUE TITLE
[1.2.8] Different extrusion width in some first solid layer portions

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#2920]
First of all, sorry for the weird title (I have no real idea on how to abstract this issue).

STL file: [`3Dponics-Drip-Nozzle-3_4-inch-3-holes.STL`](https://github.com/3dponics/Drip-3Dponics/blob/master/Drip%20Nozzles/Drip%20Nozzle%20(3_4%20inch%2C%203%20holes)/3Dponics-Drip-Nozzle-3_4-inch-3-holes.STL)
Configuration file: [`FoldaRap - 1.2.8.ini`](https://gist.github.com/xoan/314f57d2cd5255d42d44)

![overextrudate-1st_solid_layer-layers_tab](https://cloud.githubusercontent.com/assets/288246/8192076/11668d20-146c-11e5-84bd-eb338017a2f0.png)
![overextrudate-1st_solid_layer-preview_tab](https://cloud.githubusercontent.com/assets/288246/8192122/4e6df00a-146c-11e5-976f-5a54ae1c6b2c.png)

The issue appears also in the 2.25, 2.75 and 3.75mm layers but here in 1.75mm (7th layer) is very noticeable.

If it is needed, I can paste the `.gcode` file too.

**Comment by xoan** [comment]
Same issue here:

STL file: [`3Dponics-Conduit.STL`](https://github.com/3dponics/Drip-3Dponics/blob/master/Conduit/3Dponics-Conduit.STL)
Configuration file: (same as above)

![overextrudate-1st_solid_layer-preview_tab-conduit](https://cloud.githubusercontent.com/assets/288246/8194449/037ba2b2-147c-11e5-8184-08e7d8ee5975.png)

Right side seems ti be correct, while left side seems to be over extrudate (the part of the conduits near the middle one)

**Comment by alexrj** [comment]
@xoan, regarding the first model… it does look ugly, but those are solid shells above overhangs. The inner large hole is not regular since it appears to be threaded, so each layer has a thin overhang, which generates a solid shell with bridging flow:

![schermata 2015-06-16 alle 23 31 38](https://cloud.githubusercontent.com/assets/594957/8195044/df728d3c-147f-11e5-93e6-3adcda3e8a7c.png)

The toolpaths might be made more elegant (I can't figure how they should be), but I think they're not strictly wrong either - i.e. causing a badly printed object.

**Comment by alexrj** [comment]
Also, see #240

**Comment by xoan** [comment]
Yep, it is a threaded hole, so it has some areas with top/bottom solid shells. My first picture shows one of this areas with a top solid shell, and a portion of this with the first solid layer (I have configured 2 top/bottom solid layers). Here is with the strange extrusion hilighted:

![overextrudate-1st_solid_layer-preview_tab-marked](https://cloud.githubusercontent.com/assets/288246/8195560/b8590510-1483-11e5-9bab-265229eaa751.png)

And this is the same layer for the first test case sliced in Slic3r-1.2.7:

![overextrudate-1st_solid_layer-preview_tab-1 2 7](https://cloud.githubusercontent.com/assets/288246/8195527/881a24c4-1483-11e5-81e3-fe77f5c17e31.png)

I know that the first solid layer inherit bridge parameters, but some of this layers are different than others first solid layers in the same part (as shown in the second test case.)

**Comment by xoan** [comment]
I've searching and this is maybe related to #2899 and therefore it is fixed (even it is not a bug) in 38a9e32a287c4a601e256ebd96533f68c0c8dcc0

I can't compile current dev here, son I can't confirm that :\

**Comment by xoan** [comment]
Yep, it is fixed in 1.2.9-experimental.

![overextrudate-1st_solid_layer-preview_tab-fixed](https://cloud.githubusercontent.com/assets/288246/8205028/31ffbda0-14ed-11e5-8552-b3d21e3e1977.png)

Thanks
