### ISSUE TITLE
[1.2.8] single wall object not sliced with X-Y compensation Enabled

### ISSUE THREAD

**Issue by simone97** [alexrj/Slic3r#2921]
I notice this bug since version 1.2.6 as in that version, the slicing process never ends.
With the new version, the slicing process ends but gives me only the skirt lines.
If I set X-Y compensation to 0 the file is correctly sliced.

STL (0.5mm-thin-wall.stl):
http://www.thingiverse.com/download:17273
Screen (I made a screen of RepetierHost but the gocde was generated with Slic3r):
![wall](https://cloud.githubusercontent.com/assets/3505087/8195956/c6b6e912-1486-11e5-95f6-a3b633854afa.png)

**Comment by simone97** [comment]
; generated by Slic3r 1.2.8 on 2015-06-17 at 00:26:15

; external perimeters extrusion width = 0.30mm
; perimeters extrusion width = 0.34mm
; infill extrusion width = 0.34mm
; solid infill extrusion width = 0.34mm
; top infill extrusion width = 0.34mm

M107
M107 ; Turn off fan
M190 S60 ; Activate bed and wait
G28 ; home all axis
G90; Set absolute coordinates
M82 ; Extruder in absolute mode
G1 Z5 F5000 ; lift nozzle
M109 T0 S220 ; Activate hotend and wait
G28 Z0 ; home Z axis
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
G1 Z0.250 F18000.000
G1 E-2.00000 F2400.00000
G92 E0
G1 Z0.350 F18000.000
G1 X85.099 Y85.241 F18000.000
G1 Z0.250 F18000.000
G1 E2.00000 F2400.00000
M204 S1250
G1 X85.241 Y85.099 E2.00357 F5819.352
G1 X86.000 Y84.462 E2.02122
G1 X86.164 Y84.347 E2.02479
G1 X87.022 Y83.852 E2.04243
G1 X87.204 Y83.767 E2.04600
G1 X88.135 Y83.428 E2.06366
G1 X88.329 Y83.376 E2.06723
G1 X89.305 Y83.204 E2.08488
G1 X90.004 Y83.165 E2.09735
G1 X109.996 Y83.165 E2.45339
G1 X110.491 Y83.186 E2.46222
G1 X110.695 Y83.204 E2.46587
G1 X111.671 Y83.376 E2.48352
G1 X111.865 Y83.428 E2.48708
G1 X112.796 Y83.767 E2.50474
G1 X112.978 Y83.852 E2.50831
G1 X113.836 Y84.347 E2.52595
G1 X114.000 Y84.462 E2.52952
G1 X114.759 Y85.099 E2.54717
G1 X114.901 Y85.241 E2.55074
G1 X115.538 Y86.000 E2.56839
G1 X115.653 Y86.164 E2.57196
G1 X116.148 Y87.022 E2.58961
G1 X116.233 Y87.204 E2.59318
G1 X116.572 Y88.135 E2.61083
G1 X116.624 Y88.329 E2.61440
G1 X116.796 Y89.305 E2.63205
G1 X116.835 Y90.004 E2.64453
G1 X116.835 Y109.996 E3.00056
G1 X116.814 Y110.491 E3.00939
G1 X116.796 Y110.695 E3.01304
G1 X116.624 Y111.671 E3.03069
G1 X116.572 Y111.865 E3.03426
G1 X116.233 Y112.796 E3.05191
G1 X116.148 Y112.978 E3.05548
G1 X115.653 Y113.836 E3.07313
G1 X115.538 Y114.000 E3.07670
G1 X114.901 Y114.759 E3.09435
G1 X114.759 Y114.901 E3.09792
G1 X114.000 Y115.538 E3.11557
G1 X113.836 Y115.653 E3.11914
G1 X112.978 Y116.148 E3.13678
G1 X112.796 Y116.233 E3.14035
G1 X111.865 Y116.572 E3.15800
G1 X111.671 Y116.624 E3.16157
G1 X110.695 Y116.796 E3.17922
G1 X109.996 Y116.835 E3.19170
G1 X90.004 Y116.835 E3.54773
G1 X89.509 Y116.814 E3.55657
G1 X89.305 Y116.796 E3.56022
G1 X88.329 Y116.624 E3.57786
G1 X88.135 Y116.572 E3.58143
G1 X87.204 Y116.233 E3.59909
G1 X87.022 Y116.148 E3.60266
G1 X86.164 Y115.653 E3.62030
G1 X86.000 Y115.538 E3.62387
G1 X85.241 Y114.901 E3.64152
G1 X85.099 Y114.759 E3.64509
G1 X84.462 Y114.000 E3.66274
G1 X84.347 Y113.836 E3.66631
G1 X83.852 Y112.978 E3.68396
G1 X83.767 Y112.796 E3.68752
G1 X83.428 Y111.865 E3.70518
G1 X83.376 Y111.671 E3.70875
G1 X83.204 Y110.695 E3.72640
G1 X83.165 Y109.996 E3.73887
G1 X83.165 Y90.004 E4.09491
G1 X83.186 Y89.509 E4.10374
G1 X83.204 Y89.305 E4.10739
G1 X83.376 Y88.329 E4.12504
G1 X83.428 Y88.135 E4.12861
G1 X83.767 Y87.204 E4.14626
G1 X83.852 Y87.022 E4.14983
G1 X84.347 Y86.164 E4.16748
G1 X84.462 Y86.000 E4.17104
G1 X85.070 Y85.275 E4.18789
M204 S1500
G1 X85.220 Y85.362 F18000.000
M204 S1250
G1 X85.362 Y85.220 E4.19146 F5819.352
G1 X86.098 Y84.602 E4.20858
G1 X86.263 Y84.488 E4.21215
G1 X87.095 Y84.007 E4.22926
G1 X87.276 Y83.922 E4.23283
G1 X88.180 Y83.594 E4.24996
G1 X88.373 Y83.542 E4.25352
G1 X89.320 Y83.375 E4.27064
G1 X90.004 Y83.336 E4.28285
G1 X109.996 Y83.336 E4.63889
G1 X110.476 Y83.357 E4.64745
G1 X110.680 Y83.375 E4.65110
G1 X111.627 Y83.542 E4.66822
G1 X111.820 Y83.594 E4.67179
G1 X112.724 Y83.922 E4.68891
G1 X112.905 Y84.007 E4.69248
G1 X113.737 Y84.488 E4.70959
G1 X113.902 Y84.602 E4.71316
G1 X114.638 Y85.220 E4.73028
G1 X114.780 Y85.362 E4.73385
G1 X115.398 Y86.098 E4.75097
G1 X115.512 Y86.263 E4.75454
G1 X115.993 Y87.095 E4.77165
G1 X116.078 Y87.276 E4.77522
G1 X116.406 Y88.180 E4.79234
G1 X116.458 Y88.373 E4.79591
G1 X116.625 Y89.320 E4.81303
G1 X116.664 Y90.004 E4.82524
G1 X116.664 Y109.996 E5.18127
G1 X116.643 Y110.476 E5.18984
G1 X116.625 Y110.680 E5.19349
G1 X116.458 Y111.627 E5.21060
G1 X116.406 Y111.820 E5.21417
G1 X116.078 Y112.724 E5.23129
G1 X115.993 Y112.905 E5.23486
G1 X115.512 Y113.737 E5.25198
G1 X115.398 Y113.902 E5.25555
G1 X114.780 Y114.638 E5.27267
G1 X114.638 Y114.780 E5.27623
G1 X113.902 Y115.398 E5.29335
G1 X113.738 Y115.512 E5.29692
G1 X112.905 Y115.993 E5.31404
G1 X112.724 Y116.078 E5.31760
G1 X111.820 Y116.406 E5.33473
G1 X111.627 Y116.458 E5.33830
G1 X110.680 Y116.625 E5.35541
G1 X109.996 Y116.664 E5.36762
G1 X90.004 Y116.664 E5.72366
G1 X89.524 Y116.643 E5.73223
G1 X89.320 Y116.625 E5.73587
G1 X88.373 Y116.458 E5.75299
G1 X88.180 Y116.406 E5.75656
G1 X87.276 Y116.078 E5.77368
G1 X87.095 Y115.993 E5.77725
G1 X86.263 Y115.512 E5.79436
G1 X86.098 Y115.398 E5.79793
G1 X85.362 Y114.780 E5.81505
G1 X85.220 Y114.638 E5.81862
G1 X84.602 Y113.902 E5.83574
G1 X84.488 Y113.738 E5.83931
G1 X84.007 Y112.905 E5.85642
G1 X83.922 Y112.724 E5.85999
G1 X83.594 Y111.820 E5.87711
G1 X83.542 Y111.627 E5.88068
G1 X83.375 Y110.680 E5.89780
G1 X83.336 Y109.996 E5.91001
G1 X83.336 Y90.004 E6.26604
G1 X83.357 Y89.524 E6.27461
G1 X83.375 Y89.320 E6.27826
G1 X83.542 Y88.373 E6.29537
G1 X83.594 Y88.180 E6.29894
G1 X83.922 Y87.276 E6.31607
G1 X84.007 Y87.095 E6.31964
G1 X84.488 Y86.263 E6.33675
G1 X84.602 Y86.098 E6.34032
G1 X85.191 Y85.396 E6.35664
M204 S1500
G1 X85.341 Y85.483 F18000.000
M204 S1250
G1 X85.483 Y85.341 E6.36020 F5819.352
G1 X86.197 Y84.743 E6.37679
G1 X86.361 Y84.628 E6.38036
G1 X87.167 Y84.162 E6.39694
G1 X87.349 Y84.078 E6.40051
G1 X88.224 Y83.759 E6.41710
G1 X88.418 Y83.707 E6.42067
G1 X89.335 Y83.545 E6.43726
G1 X90.004 Y83.507 E6.44920
G1 X109.996 Y83.507 E6.80524
G1 X110.461 Y83.528 E6.81354
G1 X110.665 Y83.545 E6.81718
G1 X111.582 Y83.707 E6.83377
G1 X111.776 Y83.759 E6.83734
G1 X112.651 Y84.078 E6.85393
G1 X112.833 Y84.162 E6.85750
G1 X113.639 Y84.628 E6.87408
G1 X113.803 Y84.743 E6.87765
G1 X114.517 Y85.341 E6.89423
G1 X114.659 Y85.483 E6.89780
G1 X115.257 Y86.197 E6.91439
G1 X115.372 Y86.361 E6.91796
G1 X115.838 Y87.167 E6.93454
G1 X115.922 Y87.349 E6.93811
G1 X116.241 Y88.224 E6.95470
G1 X116.293 Y88.418 E6.95827
G1 X116.455 Y89.335 E6.97485
G1 X116.493 Y90.004 E6.98680
G1 X116.493 Y109.996 E7.34283
G1 X116.472 Y110.461 E7.35113
G1 X116.455 Y110.665 E7.35478
G1 X116.293 Y111.582 E7.37137
G1 X116.241 Y111.776 E7.37493
G1 X115.922 Y112.651 E7.39152
G1 X115.838 Y112.833 E7.39509
G1 X115.372 Y113.639 E7.41168
G1 X115.257 Y113.803 E7.41524
G1 X114.658 Y114.517 E7.43183
G1 X114.517 Y114.659 E7.43540
G1 X113.803 Y115.257 E7.45199
G1 X113.639 Y115.372 E7.45556
G1 X112.833 Y115.838 E7.47214
G1 X112.651 Y115.922 E7.47571
G1 X111.776 Y116.241 E7.49230
G1 X111.582 Y116.293 E7.49587
G1 X110.665 Y116.455 E7.51245
G1 X109.996 Y116.493 E7.52440
G1 X90.004 Y116.493 E7.88043
G1 X89.539 Y116.472 E7.88873
G1 X89.335 Y116.455 E7.89238
G1 X88.418 Y116.293 E7.90896
G1 X88.224 Y116.241 E7.91253
G1 X87.349 Y115.922 E7.92912
G1 X87.167 Y115.838 E7.93269
G1 X86.361 Y115.372 E7.94927
G1 X86.197 Y115.257 E7.95284
G1 X85.483 Y114.658 E7.96943
G1 X85.341 Y114.517 E7.97300
G1 X84.743 Y113.803 E7.98958
G1 X84.628 Y113.639 E7.99315
G1 X84.162 Y112.833 E8.00974
G1 X84.078 Y112.651 E8.01330
G1 X83.759 Y111.776 E8.02989
G1 X83.707 Y111.582 E8.03346
G1 X83.545 Y110.665 E8.05005
G1 X83.507 Y109.996 E8.06199
G1 X83.507 Y90.004 E8.41803
G1 X83.528 Y89.539 E8.42633
G1 X83.545 Y89.335 E8.42998
G1 X83.707 Y88.418 E8.44656
G1 X83.759 Y88.224 E8.45013
G1 X84.078 Y87.349 E8.46672
G1 X84.162 Y87.167 E8.47029
G1 X84.628 Y86.361 E8.48687
G1 X84.743 Y86.197 E8.49044
G1 X85.313 Y85.518 E8.50623
M204 S1500
G1 X85.463 Y85.604 F18000.000
M204 S1250
G1 X85.604 Y85.463 E8.50979 F5819.352
G1 X86.295 Y84.883 E8.52585
G1 X86.459 Y84.768 E8.52942
G1 X87.240 Y84.318 E8.54547
G1 X87.421 Y84.233 E8.54904
G1 X88.268 Y83.925 E8.56510
G1 X88.462 Y83.873 E8.56867
G1 X89.350 Y83.716 E8.58472
G1 X90.004 Y83.679 E8.59640
G1 X109.996 Y83.679 E8.95243
G1 X110.446 Y83.698 E8.96047
G1 X110.650 Y83.716 E8.96411
G1 X111.538 Y83.873 E8.98017
G1 X111.732 Y83.925 E8.98373
G1 X112.579 Y84.233 E8.99979
G1 X112.760 Y84.318 E9.00336
G1 X113.541 Y84.768 E9.01941
G1 X113.705 Y84.883 E9.02298
G1 X114.396 Y85.463 E9.03904
G1 X114.537 Y85.604 E9.04260
G1 X115.117 Y86.295 E9.05866
G1 X115.232 Y86.459 E9.06223
G1 X115.682 Y87.240 E9.07828
G1 X115.767 Y87.421 E9.08185
G1 X116.075 Y88.268 E9.09791
G1 X116.127 Y88.462 E9.10148
G1 X116.284 Y89.350 E9.11753
G1 X116.321 Y90.004 E9.12921
G1 X116.321 Y109.996 E9.48524
G1 X116.302 Y110.446 E9.49328
G1 X116.284 Y110.650 E9.49692
G1 X116.127 Y111.538 E9.51298
G1 X116.075 Y111.732 E9.51654
G1 X115.767 Y112.579 E9.53260
G1 X115.682 Y112.760 E9.53617
G1 X115.232 Y113.541 E9.55222
G1 X115.117 Y113.705 E9.55579
G1 X114.537 Y114.396 E9.57185
G1 X114.396 Y114.537 E9.57542
G1 X113.705 Y115.117 E9.59147
G1 X113.541 Y115.232 E9.59504
G1 X112.760 Y115.682 E9.61109
G1 X112.579 Y115.767 E9.61466
G1 X111.732 Y116.075 E9.63072
G1 X111.538 Y116.127 E9.63428
G1 X110.650 Y116.284 E9.65034
G1 X109.996 Y116.321 E9.66202
G1 X90.004 Y116.321 E10.01805
G1 X89.554 Y116.302 E10.02609
G1 X89.350 Y116.284 E10.02973
G1 X88.462 Y116.127 E10.04579
G1 X88.268 Y116.075 E10.04935
G1 X87.421 Y115.767 E10.06541
G1 X87.240 Y115.682 E10.06898
G1 X86.459 Y115.232 E10.08503
G1 X86.295 Y115.117 E10.08860
G1 X85.604 Y114.537 E10.10466
G1 X85.463 Y114.396 E10.10823
G1 X84.883 Y113.705 E10.12428
G1 X84.768 Y113.541 E10.12785
G1 X84.318 Y112.760 E10.14390
G1 X84.233 Y112.579 E10.14747
G1 X83.925 Y111.732 E10.16353
G1 X83.873 Y111.538 E10.16709
G1 X83.716 Y110.650 E10.18315
G1 X83.679 Y109.996 E10.19483
G1 X83.679 Y90.004 E10.55086
G1 X83.698 Y89.554 E10.55890
G1 X83.716 Y89.350 E10.56254
G1 X83.873 Y88.462 E10.57859
G1 X83.925 Y88.268 E10.58216
G1 X84.233 Y87.421 E10.59822
G1 X84.318 Y87.240 E10.60179
G1 X84.768 Y86.459 E10.61784
G1 X84.883 Y86.295 E10.62141
G1 X85.434 Y85.639 E10.63666
M204 S1500
M106 S255
M104 S215 ; set temperature
G1 Z0.500 F18000.000
G1 Z0.750 F18000.000
G1 Z1.000 F18000.000
G1 Z1.250 F18000.000
G1 Z1.500 F18000.000
G1 Z1.750 F18000.000
G1 Z2.000 F18000.000
G1 Z2.250 F18000.000
G1 Z2.500 F18000.000
G1 Z2.750 F18000.000
G1 Z3.000 F18000.000
G1 Z3.250 F18000.000
G1 Z3.500 F18000.000
G1 Z3.750 F18000.000
G1 Z4.000 F18000.000
G1 Z4.250 F18000.000
G1 Z4.500 F18000.000
G1 Z4.750 F18000.000
G1 Z5.000 F18000.000
G1 Z5.250 F18000.000
G1 Z5.500 F18000.000
G1 Z5.750 F18000.000
G1 Z6.000 F18000.000
G1 Z6.250 F18000.000
G1 Z6.500 F18000.000
G1 Z6.750 F18000.000
G1 Z7.000 F18000.000
G1 Z7.250 F18000.000
G1 Z7.500 F18000.000
G1 Z7.750 F18000.000
G1 Z8.000 F18000.000
G1 Z8.250 F18000.000
G1 Z8.500 F18000.000
G1 Z8.750 F18000.000
G1 Z9.000 F18000.000
G1 Z9.250 F18000.000
G1 Z9.500 F18000.000
G1 Z9.750 F18000.000
G1 Z10.000 F18000.000
G1 E8.63666 F2400.00000
G92 E0
G1 Z10.100 F18000.000
M107
M104 S0  ; turn off extruder
M140 S0  ; turn off bed
G91; Set relative coordinates
G1 E-1 ; Reduce filament pressure
M104 T0 S0
M140 S0
G1 Z5 F5000; lift nozzle 5mm
G28 X0 ; home X axis
G90; Set absolute coordinates
G1 Y180 F5000; move Y to the max
M84; disable motors
; filament used = 8.6mm (0.0cm3)

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 60
; before_layer_gcode = 
; bridge_acceleration = 1250
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 1
; cooling = 1
; default_acceleration = 1500
; disable_fan_first_layers = 1
; duplicate_distance = 6
; end_gcode = M104 S0  ; turn off extruder\nM140 S0  ; turn off bed\nG91; Set relative coordinates\nG1 E-1 ; Reduce filament pressure\nM104 T0 S0\nM140 S0\nG1 Z5 F5000; lift nozzle 5mm\nG28 X0 ; home X axis\nG90; Set absolute coordinates\nG1 Y180 F5000; move Y to the max\nM84; disable motors
; extruder_clearance_height = 30
; extruder_clearance_radius = 50
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.99999
; fan_always_on = 1
; fan_below_layer_time = 60
; filament_colour = #000000
; filament_diameter = 1.75
; first_layer_acceleration = 1250
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 90%
; first_layer_speed = 75%
; first_layer_temperature = 220
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 1250
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_print_speed = 250
; max_volumetric_speed = 0
; min_fan_speed = 50
; min_print_speed = 5
; min_skirt_length = 5
; notes = 
; nozzle_diameter = 0.3
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 1250
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0.1
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 5
; skirt_height = 1
; skirts = 2
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = M107 ; Turn off fan\nM190 S[first_layer_bed_temperature] ; Activate bed and wait\nG28 ; home all axis\nG90; Set absolute coordinates\nM82 ; Extruder in absolute mode\nG1 Z5 F5000 ; lift nozzle\nM109 T0 S[first_layer_temperature] ; Activate hotend and wait\nG28 Z0 ; home Z axis
; temperature = 215
; threads = 4
; toolchange_gcode = 
; travel_speed = 300
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.25
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.25
; raft_layers = 0
; seam_position = nearest
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 300
; support_material_threshold = 0
; xy_size_compensation = -0.1
; bottom_solid_layers = 3
; bridge_flow_ratio = 0.9
; bridge_speed = 25
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 15
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 30%
; fill_pattern = rectilinear
; gap_fill_speed = 5
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 1%
; infill_speed = 250
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 50
; perimeters = 3
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 100
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 50
; top_solid_layers = 3

**Comment by peter1960** [comment]
I have seen this behavior via Repetier/MatterControl as well where it never completes but works ok with slic3r standalone.

**Comment by simone97** [comment]
I've alse tried to export the gcode directly from slic3r and gives the same result.

**Comment by alexrj** [comment]
It's not a bug.
Despite the name says 0.5mm, your test object has 0.25mm walls. If you apply a size compensation of -0.1mm (for each side) you'll trim it down to 0.05mm walls, which is filtered out by Slic3r because it's quite thin to be extruded with a 0.3mm nozzle.
