### ISSUE TITLE
1.2.9-dev Math-PlanePath fail

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2923]
I think the program is working now but Math-PlanePath gives me an error message.

Building and testing Math-PlanePath-119 ... FAIL
! Installing Math::PlanePath failed. See /home/travis/.cpanm/work/1434530566.4171/build.log for details. Retry with --force to force install it.
2 distributions installed
--> Working on Module::Build::WithXSpp

**Comment by alexrj** [comment]
You can install it with `cpanm -f Math::PlanePath`

**Comment by a4jp-com** [comment]
Done. Thank you ^^

Is this the same error causing the failure in Travis CL?

**Comment by a4jp-com** [comment]
This error is completely gone now. Thank you.
