### ISSUE TITLE
1.2.9 - [Debian Jessie] Distro ships Encode::Locale 1.03, is 1.05 really necessary?

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#2926]
So, yeah, 1.2.9 breaks on Debian Jessie because of a hard dependency on v 1.05 of Encode::Locale.
Is this really a hard dependency?
I've changed the requirement line to 1.03, and all tests do pass. So my debian packages will be built with that change. 

Error:
Encode::Locale version 1.05 required--this is only version 1.03 at /home/lenox/Slic3r/t/../lib/Slic3r.pm line 73.

**Comment by alexrj** [comment]
It is required for Windows. So I think your change will not break anything on Linux.
