### ISSUE TITLE
Feature Request: Different print settings for different layers

### ISSUE THREAD

**Issue by SkyRzn** [alexrj/Slic3r#2929]
Now we can set different layer heights for different z-sectors. I think different print settings would be more useful.
Thank you for your work!

**Comment by alexrj** [comment]
You can do that with modifier meshes. See this tutorial: http://slic3r.org/blog/modifier-meshes

**Comment by SkyRzn** [comment]
Modifier to do longer than specify heights.
It may be better to remove the Layers tab and add a built-in modifier with values minZ and maxZ?

**Comment by alexrj** [comment]
Easier built-in tools for creating modifiers is in the roadmap

**Comment by SkyRzn** [comment]
Thank you!
