### ISSUE TITLE
Weird arrangment when adding more than 4 copies of a parts 

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#2932]
Hi there
It's a bug that I've see since 1.2.7 exp, but maybe was here before
Win7 x64 with the latest 1.2.9a x64

when adding more copies of some STL (using sur "+" button), the first 4th copies autoarranged correctly, but 5th+ are just superposed with a little offset on X & Y (see screen)

![slicc3r-copy](https://cloud.githubusercontent.com/assets/2814966/8271111/1b653ad6-1806-11e5-871a-8f8a3bc950d8.jpg)

Clicking "Autoarrange" does nothing

a STL where the problem occurs : https://dl.dropboxusercontent.com/u/34934879/24h%2B.STL
Here is the config : https://dl.dropboxusercontent.com/u/34934879/copies_config.ini
Gcode is irrelevant

Complementary info :
Right now, I used to slice this : https://www.youmagine.com/designs/toothpaste-squeezer
As you can see, the object isn't correctly oriented, so I rotated him (-90 on X and on Z). And added some (up to 12) copies and the problem didn't occurs at all, they was all arranged correctly, even if out of printing area.
Tried without rotating, and the problem was back again after the 4th copy
Tried with just a -90° rotation on X and the problem occurs too.

Tried with the default config and the first linked STL, problem still occurs but after the 9th copy
Seems to be some math related to bed size etc...

cheers

**Comment by a4jp-com** [comment]
I had no problem adding models 1cm by 1cm blocks or just pushing the plus button.

![screen shot 06-21-15 at 11 55 pm](https://cloud.githubusercontent.com/assets/9621044/8272114/ffc08c60-1871-11e5-9e35-59a407094ee1.JPG)


I had this problem with your model from the 10th model, just using the plus button. I can drag and drop parts into the correct position though.

![screen shot 06-21-15 at 11 59 pm](https://cloud.githubusercontent.com/assets/9621044/8272113/f51f6fd8-1871-11e5-9973-83cd5da541eb.JPG)

**Comment by gege2b** [comment]
yeah, I forgot to say that drag&drop of the superposed objects works anyway

My guess is that it depends of : 
- the size of the object
- the size of the bed
- maybe the rotation
so the 1cm cube you used is maybe just OK, mathematically speaking ^_^

**Comment by alexrj** [comment]
Thank you, this behavior was recently fixed.

**Comment by a4jp-com** [comment]
Nice ^^
