### ISSUE TITLE
Main Frame Filament Icon missing. (1.2.9 Windows)

### ISSUE THREAD

**Issue by fuding** [alexrj/Slic3r#2939]
Main Frame Filament Icon missing. (1.2.9 Windows)
![image](https://cloud.githubusercontent.com/assets/1652252/8276543/47327e64-18ea-11e5-93ee-e735eed50d4b.png)

**Comment by xoan** [comment]
#2919

**Comment by a4jp-com** [comment]
I suggested there should be a border to make it look like something is there. I was confused by the white icons as well until they told me the color changes if you go to the filament settings area and change the color. After you change the color we also have to click save but maybe an auto save for the color data would be nice.

**Comment by fuding** [comment]
I misunderstood
This is not a bug
