### ISSUE TITLE
gcode output on gui and command line not consistant 1.29 and 1.27

### ISSUE THREAD

**Issue by jgrjgr** [alexrj/Slic3r#2946]
I think i have discovered a bug, 

when i slice a cube using the Gui the gcode it produces is perfectly centred on my bed, 
when i slice the same object using the commandline (slic3r-console.exe) if produces gcode that is 100mm to the left of centre of the bed.

https://dl.dropboxusercontent.com/u/76417200/cube-console-error.zip

the link above contains the gcode files and the config i used for both
this was running 1.29a on windows 7 and windows 8  this also happenes on 1.27 as well

**Comment by alexrj** [comment]
This behavior was recently fixed: command line now centers the print around the center of the configured bed.
