### ISSUE TITLE
Feature request: Override brim setting

### ISSUE THREAD

**Issue by hyperair** [alexrj/Slic3r#2964]
I usually print without a brim, but for some prints with extremely tiny bases I do need them, and it would be nice if I could specify this without maintaining a different print profile for it. Brim width isn't listed in the list of settings you can override for a print.

**Comment by whosawhatsis** [comment]
duplicate of https://github.com/alexrj/Slic3r/issues/1316

**Comment by Lenbok** [comment]
Also, duplicate of #2163 and #2164

**Comment by alexrj** [comment]
@hyperair, see #2163

**Comment by hyperair** [comment]
Hmm, I guess I wanted a way to override this per-print, rather than having to mess up my configured print profiles.

**Comment by alexrj** [comment]
Just change it under "Print Settings" and don't save the changed profile.
