### ISSUE TITLE
tests fail on current master

### ISSUE THREAD

**Issue by wolfmanjm** [alexrj/Slic3r#2965]
Test Summary Report
-------------------
t/multi.t                    (Wstat: 139 Tests: 0 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 13 tests but ran 0.

bullding on linux. worked before git pull this morning

**Comment by lordofhyphens** [comment]
Need more information about your setup. The Travis server is reporting that
all tests pass, so the problem is more likely related to your particular
system.

**Comment by wolfmanjm** [comment]
Ubuntu 14.04 32bit system. doing a clean sudo perl BUILD.PL.
Using stock perl.

**Comment by wolfmanjm** [comment]
It got fixed, thanks ;)

**Comment by lordofhyphens** [comment]
You probably should use my fork anyway; make packages and do less damage to
system perl.

**Comment by alexrj** [comment]
Yeah thank you, the master branch was a bit unstable these days because of heavy refactoring...
