### ISSUE TITLE
Feature request: Gap fill at constant volumetric extrusion rate (autospeed)

### ISSUE THREAD

**Issue by Hexman64** [alexrj/Slic3r#2976]
(Moved from issue #2810 as it was off topic there):

**START READING AT THE FOURTH POST (the one by luisonoff). WHAT I THOUGHT IS A BUG TURNED OUT TO BE NORMAL BEHAVIOR, BUT THEN A FEATURE IS MISSING.** You can ignore posts 1-3.

I set all the extrusion widths to 0, and as long as the speed settings are above 0, I get a nice gap fill which I call "the new style":
![gapspeed20](https://cloud.githubusercontent.com/assets/2305334/8507028/d00bdf64-2231-11e5-834e-11c045e9c35b.jpg)

When I then change the speed settings, especially the gap fill speed setting to 0, gap filling is done the legacy way. I guess printers cannot keep up a good (extrusion) speed when filling gaps the zig-zag way:
![gapspeed0](https://cloud.githubusercontent.com/assets/2305334/8507032/f595edba-2231-11e5-922a-45212d33c5a3.jpg)
(by the way, for this model you see a gap fill error in one of the lower layers)

The gap fill looks good for speed settings above 0, so it should be done the same way when using autospeed.
Constant volumetric speed is a good improvement when printing flexible material.
Slic3r is Windows 1.2.9 x64

**Comment by luisonoff** [comment]
Are those two pictures of the same STL?? Because they look quite different, one looks taller or the other one wider...

**Comment by Hexman64** [comment]
Just to make sure, in the below test I only changed the gap speed from 30 to 0.

![gapspeed_sameview](https://cloud.githubusercontent.com/assets/2305334/8763223/01600bb4-2d93-11e5-919a-a6965f960a08.jpg)

**Comment by luisonoff** [comment]
If you set "gap filling speed" to 0, gap filling is disabled, as the GUI says when you stay over that option.
So if I understand correctly you are asking for an improvement that enables gap filling to work with autospeed in order to keep volumetric extrusion rate constant also while gap filling? Yes?

**Comment by Hexman64** [comment]
DAMN! Your suspicion is right. What I thought is the legacy way of gap-filling in fact is a solid infill because the area is smaller than the value in the "solid infill threshold area" setting.
**So it was just my confusion, Slic3r is working as designed**, and yes, then I'd 

**Need an Improvement please: gap filling with constant volumetric extrusion rate.**

I'll change the title fo "Feature request". Thank you for finding the bug in my thoughts.

**Comment by luisonoff** [comment]
+1 on this request. Gap filling is a very nice feature and it "looks like" should not be too hard to make it compatible with autospeed. Since widths of gap filling are very variable, that's an extra argument to make it work with autospeed instead of manually setting a speed.

**Comment by teppix** [comment]
+1
Have also encountered this before. Definitely would expect 0 to be autospeed for gapfill. Also, gapfill is one of the cases where volumetric speed would be most useful, due to the wide extrusions.

**Comment by Hexman64** [comment]
Yes... when printing flexible material, I could set all the widths and speeds to the same value, except for gap filling, which has variable widths. But there autospeed is not implemented. Hopefully the implementation and the fix of #2960 will be done in one step (gap filling is broken since 1.2.8).

**Comment by lordofhyphens** [comment]
Probably could use a negative # as indication for disable gap fill instead
of 0.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by teppix** [comment]
@lordofhyphens 
That would work, but personally I'm against hiding features like that. It would just add yet another thing to explain in the already long tooltip. A UI should be self explanatory as much as possible, and coding things into integers is just counter intuitive.

I have no problem with using the integer behind the scenes, but definitely not in the GUI.

I think it would be better if all speed fields had an "auto" checkbox that would disable the numeric input.

One could also question if gap fill should be enabled/disabled in the speed section. That also is counter intuitive IMHO.  Better to place that option in the infill tab, where you would expect to find it.

**Comment by lordofhyphens** [comment]
Works for me, I am mostly thinking about the ini interface.

**Comment by alexrj** [comment]
I fixed this: gap_fill_speed = 0 now enabled autospeed for gaps instead of disabling gap fill. A new fill_gaps option was added for that purpose.
