### ISSUE TITLE
Changing layer thickness in specific STL settings does not change heights on 2nd change

### ISSUE THREAD

**Issue by the-edge01** [alexrj/Slic3r#2980]
I sliced a part at .1mm layer height and .3mm first layer, and then selected through the layers menu to make 0-2.4mm .3 in height.  I then went back and selected the 2.4 to be 1.8, but the preview of the model was not changed.  When I changed the 1st layer to .2 from .3, it added a .1 layer but still continued the .3 until 2.4 instead of 1.8

Slic3r v1.2.9

**Comment by alexrj** [comment]
Thank you @the-edge01, this was recently fixed as of #2958.
