### ISSUE TITLE
Brim not attached to part when support is enabled

### ISSUE THREAD

**Issue by pyrophreek** [alexrj/Slic3r#2981]
I was trying to print a part with a small width lip, followed by a large thickness wall
![image](https://cloud.githubusercontent.com/assets/5613825/8513485/e86e0014-2321-11e5-9d25-89cc3c8aed3c.png)
and I noticed that if I enabled brim, it didn't attach to the part when support was enabled, so it started to peel up.  Would it be possible to make the brim attach directly to the part rather than to the support material?  Any support material that coincided with the brim would then print on top of the brim rather than in place of it.

**Comment by lordofhyphens** [comment]
@pyrophreek could you dig out a test case for this?

**Comment by alexrj** [comment]
I fixed this. Thank you for reporting it @pyrophreek
