### ISSUE TITLE
3D and 2D view are different than Preview and Layers view

### ISSUE THREAD

**Issue by efa** [alexrj/Slic3r#2982]
I reported this on reprap forum before, but no answer there:
http://forums.reprap.org/read.php?263,528286,529568#msg-529568

The trouble is, using Slic3r 1.2.9 with this STL file:
http://forums.reprap.org/file.php?263,file=57628,filename=revers_3.stl,download=1

the 3D and 2D view are different than Preview and Layers view, the complete knob is missing.
See shots:

![thr737_slic3r1 2 9_2d](https://cloud.githubusercontent.com/assets/1578980/8523065/6a216318-23f3-11e5-93c8-441cde1e3544.png)
![thr737_slic3r1 2 9_3d](https://cloud.githubusercontent.com/assets/1578980/8523056/613f4c1a-23f3-11e5-8b82-70f220572b83.png)
![thr737_slic3r1 2 9_preview](https://cloud.githubusercontent.com/assets/1578980/8523071/6f1fd14c-23f3-11e5-84f6-672b399151ce.png)
![thr737_slic3r1 2 9_layers](https://cloud.githubusercontent.com/assets/1578980/8523076/75c50b3e-23f3-11e5-9459-c1db36e33e0b.png)

**Comment by lordofhyphens** [comment]
For starters it looks like your stl is broken. Second, 2D view shows the
shadow of the part on the z plane.

Could you post your slic3r settings and OS as well?

**Comment by efa** [comment]
which configuration settings ini files do you need:
filament, print or printer?
(seems that the only accepted attachments are images, neither .stl files can be loaded on this issue tracker)

**Comment by alexrj** [comment]
Your STL file has wrong normals. Fix it.

![schermata 2015-07-06 alle 22 29 53](https://cloud.githubusercontent.com/assets/594957/8532464/86089e76-242e-11e5-90dd-f83f6c39468d.png)
![schermata 2015-07-06 alle 22 30 01](https://cloud.githubusercontent.com/assets/594957/8532462/86027a28-242e-11e5-8ec0-511947b1fa02.png)
![schermata 2015-07-06 alle 22 30 05](https://cloud.githubusercontent.com/assets/594957/8532463/860628ee-242e-11e5-9f6f-828b99816ddc.png)

**Comment by efa** [comment]
please tell me which software do you use to see the normals error.
(try loading Slic3r_config_bundle.ini say:
Unfortunately, we don't support that file type. Try again with a PNG, GIF, JPG)

**Comment by efa** [comment]
ok using Blender I fixed the normals and now the part is sliced correctly, see
http://forums.reprap.org/read.php?263,528286,529762#msg-529762

**Comment by lordofhyphens** [comment]
efa in the future upload configs/stls to a hosting site and post a link
here.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by efa** [comment]
reprap forum is OK for you for upload and link?

**Comment by lordofhyphens** [comment]
@alexjr is the final authority on what's acceptable, as it's his project :D

Issue's been closed, though, so nothing else need be posted here.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by efa** [comment]
next time (future issues) I had to upload configs/stls, it is OK to use the reprap forum and link them here?
