### ISSUE TITLE
Argument isn't numeric Layer.pm line 53

### ISSUE THREAD

**Issue by dtmille2** [alexrj/Slic3r#2983]
Change extrusion width settings on objects within a multiple-object .xml file and got the following error:

![image](https://cloud.githubusercontent.com/assets/2092921/8544994/39be64fc-2478-11e5-851a-f643c22f8f73.png)

Was changing extrusion widths of perimeters and external perimeters to 100%.  Also tried 134% and got the same error.  Error occurs after settings dialog box is closed as Slic3r is re-processing the file in the background.

**Comment by alexrj** [comment]
What Slic3r version?

**Comment by dtmille2** [comment]
1.2.9

**Comment by alexrj** [comment]
Fixed, thank you.
