### ISSUE TITLE
Help -> About Slic3r = Crash, "Error while autoloading 'Wx::wxCLOSE' at /usr/lib64/perl5/vendor_perl/5.20.2/Slic3r/GUI/AboutDialog.pm line 69."

### ISSUE THREAD

**Issue by triffid** [alexrj/Slic3r#2984]
Using Slic3r c65c9d876eb29e4660deea0a51dd6a2a2a047ab5 via ["axs" gentoo overlay](http://gpo.zugaina.org/media-gfx/Slic3r)/[Slic3r-9999](http://data.gpo.zugaina.org/axs/media-gfx/Slic3r/Slic3r-9999.ebuild)

**Comment by alexrj** [comment]
What wxWidgets version?  You can see it running `slic3r.pl --debug --gui`

**Comment by triffid** [comment]
wxWidgets version wxWidgets 2.8.12, Wx version 0.9902

**Comment by tomgeor** [comment]
I'm seeing the same thing on Fedora 23.

$ slic3r --debug --gui
wxWidgets version wxWidgets 2.8.12, Wx version 0.9927

Error while autoloading 'Wx::wxCLOSE' at /usr/share/perl5/vendor_perl/Slic3r/GUI/AboutDialog.pm line 69.

**Comment by alexrj** [comment]
Fixed - #2881
