### ISSUE TITLE
Feature Request - Filament Notes

### ISSUE THREAD

**Issue by Enchiridion** [alexrj/Slic3r#2993]
Hi,
Just like how there's a Notes field under Print Settings, I'd love if there was another Notes field under Filament Settings too, so I can record notes per filament.

Thanks!

**Comment by a4jp-com** [comment]
That is a nice idea. I would write the temps that didn't work with certain plastics if that was in the program.

+1

**Comment by alexrj** [comment]
We have Filament Notes now! Thank you.

**Comment by a4jp-com** [comment]
Cool. Thank you too.
