### ISSUE TITLE
Filament profile doesn't select from main tab, uses filament tab selection

### ISSUE THREAD

**Issue by nicksears** [alexrj/Slic3r#2997]
Using Slic3r 1.2.9x64 on Windows 8.1(x64) I have issues getting slic3r to use the right filament profile in a special (common) case. This is on a dual extruder printer, but I'm only using one extruder, I think this is key. When I select the first filament in the main "Plater" window, slic3r does not necessarily use that filament. I usually select the same filament for both extruders even if I'm not using the second one, but this does not seem to affect it. I've configured "Print Settings">"Output options">"Output file">"Output filename format:" to be "[input_filename_base] [[print_preset]] [[filament_preset]] [[printer_preset]].gcode" so I can see what profiles are used.

When I slice where I've selected a certain profile in the "Plater" tab, but for whatever reason the "Filament Settings" tab had another filament selected, the Filament tab overrules the plater tab. To reproduce this you should just be able to change the filament in the filament tab, then select a dual extruder (printer) in the plater tab, select a DIFFERENT filament in the plater tab, and export. 

For me, this yields a file using the filament profile from the filament page (most easily checked int he gcode by the temperatures being wrong) rather than the plater page (also represented in the filename as the incorrect filament profile).

![1](https://cloud.githubusercontent.com/assets/6611900/8754128/dff3034e-2c86-11e5-86cf-051b161e5a0a.jpg)
![2](https://cloud.githubusercontent.com/assets/6611900/8754129/dffa65a8-2c86-11e5-87e9-aebb376c1b58.jpg)

**Comment by lordofhyphens** [comment]
@nicksears please try with new build from http://dl.slic3r.org/dev

**Comment by lordofhyphens** [comment]
This looks like it has been fixed, changing profiles in the profile editor for a filament updates the plater tab (and changing it in the plater tab and clicking the edit profile button brings up that profile).

This should be relevant (although anything after gui3 was merged is fine): https://bintray.com/lordofhyphens/Slic3r/slic3r_dev/1.3.0-dev-9ecc1a2#files
