### ISSUE TITLE
Feature Request: hexagonal and square cell infill pattern

### ISSUE THREAD

**Issue by OhmEye** [alexrj/Slic3r#300]
The current infill pattern options don't include any patterns that form cells up through the layers. Cells provide more bonding area and are relatively stronger for sparse infill. The Grid Rectangular and Grid Hexagonal in Skeinforge are strong and have side benefits of being aesthetically pleasing for translucent objects.

Example of pathing for hexagonal pattern... http://wiki.bitsfrombytes.com/index.php/File:FILL_TESTA_layer4.png and http://wiki.bitsfrombytes.com/index.php/File:FILL_TESTA_layer5.png

The SF rectangular pattern differs from the slic3r rectilinear in that the SF pattern paths in an alternating 90 degree zigzag such that adjacent paths form square cells, and each layer more fully bonds with the layer below to form more solid cell walls, instead of simply alternating straight parallel lines that only bond layers together at line intersections.

**Comment by lordofhyphens** [comment]
As the man said 4 years ago, we have honeycomb! And 3D honeycomb!
