### ISSUE TITLE
More information about autospeed?

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#3018]
Autospeed doesn't have a manual entry. 

What other slicing parameters does slic3r take into account when calculating pressure for autospeed? If acceleration control is used, does it take accel into account?

Would it be possible to add a few tuning settings (such as junction deviation or jerk) so that Slic3r can make slightly better decisions?

**Comment by luisonoff** [comment]
My guess is that it does not account for acceleration, but I really have no idea and would like to know the answer as well. :)

**Comment by alexrj** [comment]
See last paragraph in http://slic3r.org/blog/new-stable-1.2.9
Also, #2810
