### ISSUE TITLE
Latest git pull hangs in tests...

### ISSUE THREAD

**Issue by wolfmanjm** [alexrj/Slic3r#3020]
The latest git pull hangs while doing tests...

t/retraction.t ................. ok     
t/shells.t ..................... 

Linux Ubuntu 14.04 132x also 64x.

**Comment by atupek** [comment]
I am also having this problem, hangs on the same test.  Also using Ubuntu 14.04 64x.  Using Perl 5.14.4

**Comment by mikenew12** [comment]
Same behavior on OS X 10.10.5. 

Removing the ```shells.t``` test causes it to hang on the ```skirt_brim.t``` test, and removing that test will let it finish the build. So whatever the issue is, it's shared between those 2.

**Comment by llluis** [comment]
This was corrected in the last commit: https://github.com/alexrj/Slic3r/commit/5b8ed7367a2a9148c215eafa53c7e13b30cd0c36
