### ISSUE TITLE
please change custom start gcode order

### ISSUE THREAD

**Issue by AndKe** [alexrj/Slic3r#3031]
this is the start code we have today.
```
M107 ;fan off
M190 S60 ; set(, and wait for) bed temperature 
M104 S180 ; set hotend temperature (do not wait)
(custom start gcode here)
M109 S180 ; wait for hotend temperature to be reached
```

the experience is like: 
fan off, set temp, wait for 5 minutes, then set hotend, and wait for additional 3 minutes. 

If you changed the start code to this;
```
M107 ;fan off
(custom start gcode here)
M190 S60 ; set(, and wait for) bed temperature 
M109 S180 ; set and wait for hotend temperature to be reached
```

Then I user could add custom code to achieve this:
fan off, set bed to 35degree and wait, set bed to 60 (no wait) , set hotend to 180 (no wait)..
this would make hotend and bed get warm at about the same time - both within 5 minutes, instead of 5+3minutes

**Comment by whosawhatsis** [comment]
If you put M109/M190 in your start code, they won't be added automatically, outside of it, so you can put them in the order you want.

**Comment by AndKe** [comment]
fantastic, I did not knew the gcode would adapt to what's inside :)
