### ISSUE TITLE
【XS/C++ failed】I couldn't compile the latest Slicer development version on Windows 10 (64-bit)

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#3034]
I couldn't compile the latest Slicer development version on Windows 10 (64-bit)

Any advice is greatly appreciated.

I loaded the latest version of Strawberry Perl (32-bit).

-----------------------------------------------------
c:\slic3r-4>perl -v

This is perl 5, version 22, subversion 0 (v5.22.0) built for MSWin32-x86-multi-thread-64int

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

![screen shot 08-07-15 at 05 19 pm](https://cloud.githubusercontent.com/assets/9621044/9131888/90f3cd3c-3d2a-11e5-8985-664d702ad1f8.JPG)

**Comment by a4jp-com** [comment]
Any ideas anyone?

**Comment by llluis** [comment]
The problem is with the module ExtUtils::CppGuess (which is a prerequisite of other modules).
I had the same problem and is a known bug with this module: https://github.com/tsee/extutils-cppguess/issues/9

You will have to make the change in the source indicated in that issue and install the module manually.

Or you can download the corrected package here: https://www.dropbox.com/s/hpzipgbsm7ngaf1/ExtUtils-CppGuess-0.09.tar.gz?dl=0

And run:

cpanm /path/to/the/file

After that run again the Build.PL

**Comment by a4jp-com** [comment]
Thank you soooooo much @llluis.

Do you mean path to the Build.PL file?

**Comment by a4jp-com** [comment]
![screen shot 08-11-15 at 07 38 am](https://cloud.githubusercontent.com/assets/9621044/9186013/09136628-3ffc-11e5-9990-e675455586b6.JPG)

I guess the path is to the files you posted. I'll try again.

**Comment by a4jp-com** [comment]
![screen shot 08-11-15 at 07 43 am](https://cloud.githubusercontent.com/assets/9621044/9186083/b967a44e-3ffc-11e5-9a04-071f4d98ae43.JPG)

I'm not sure which folder or file to point to.

**Comment by a4jp-com** [comment]
I changed cpanm to cpan and it tried to install but failed.

![screen shot 08-11-15 at 07 55 am](https://cloud.githubusercontent.com/assets/9621044/9186304/63c4bf3e-3ffe-11e5-8daf-272ac47e6d6a.JPG)

**Comment by a4jp-com** [comment]
It is compiling now but gets stuck on Building and testing Wx-0.9927 ... when making the gui file.

![screen shot 08-11-15 at 08 51 am](https://cloud.githubusercontent.com/assets/9621044/9186969/2cd6a980-4006-11e5-8d89-06930465eb4b.JPG)

**Comment by llluis** [comment]
You had to point to the file I sent.
'''cpanm ExtUtils-CppGuess-0.09.tar.gz'''
But as it's working now I believe you figured this out.

For the Wx, do you see a window with the title "X" during compilation? It take a long time to compile this module.

**Comment by a4jp-com** [comment]
I don't have this problem as I'm using version 1.2.10-dev now.
