### ISSUE TITLE
Faulty bridges for thin walls

### ISSUE THREAD

**Issue by lobanov** [alexrj/Slic3r#304]
Apparently Slic3r doesn't generate gcode for bridge layers correctly if walls are thinner than perimeter setting.

The following OpenSCAD scipt models two hollow boxes of the same size without side faces. Top and bottom faces are of the same thickness, which makes bridge layer to be generated on the same level. Red box has 1.5mm-thick front and back faces, the green one has them 2mm-thick.

```
module testbox(walls) {
  difference() {
    cube([10, 20, 20]);
    translate([-1, walls, 2]) cube([12, 20 - walls * 2, 16]);
  }
}

color("red") translate([-20, 0, 0]) testbox(1.5);
color("green") testbox(2);
```

When sliced for 0.5mm nozzle and perimeter=3, red box has invalid bridge layer, whilst the green one is generated correctly. This is illustrated on a screenshot (Pronterface):
http://forums.reprap.org/file.php?263,file=7334,filename=perimeter3.png

If perimeter is set to 2, both boxes have correct bridge layers:
http://forums.reprap.org/file.php?263,file=7333,filename=perimeter2.png

_This report is based on this forum thread, where more photos, screenshots and test models are presented:_
http://forums.reprap.org/read.php?263,127574,127621

**Comment by elXaptation** [comment]
Hello, I'm running 1.3.1-dev. I'm experiencing this issue.. Even though its seems to be identified, reported, confirmed and fixed. Should I open a new issue?

I have my perimeters set to 6, an internal wall on the part is thiner then 6. Slic3r prints 6 perimeters on the thin wall, in thin air, then tries to bridge anchored on the floating perimeter.  Any suggestions?

I'm trying to print:
https://www.thingiverse.com/thing:2254103
Part: Y_Carriage_xDia8_LM10UU_1.0.stl

![Screenshot - 04232019 - 05:08:28 PM](https://user-images.githubusercontent.com/19847622/56624140-728c5f00-65ec-11e9-8688-cbd83b79bf55.png)
![Screenshot - 04232019 - 05:08:17 PM](https://user-images.githubusercontent.com/19847622/56624141-728c5f00-65ec-11e9-950c-6f0e6f1c9f54.png)
![20190423_170540](https://user-images.githubusercontent.com/19847622/56624146-78824000-65ec-11e9-9a46-05227b51f6b1.jpg)
![Screenshot - 04232019 - 05:25:15 PM](https://user-images.githubusercontent.com/19847622/56624231-d747b980-65ec-11e9-98af-3489316086f0.png)

**Comment by supermerill** [comment]
It's not a thin wall, as it's a normal perimeter and not a single extrusion (or your should link your settings).

Solution1: decrease your perimeter count.
Solution2: put a big flat modifier box (0.2 height, 200x200 in xy) at the first "flat" layer and reduce the perimeter count to 1 or 2 for this modifier mesh.
Solution3: add supports
Solution4: create complicated code that change the way slic3r separate different parts to resolve this issue and submit a pr.

**Comment by supermerill** [comment]
I think the way slic3r works has changed a lot since 2013. This function is now lost. Imo, it's difficult to correct it.

Your best bet is to create a modifier mesh and assign a 1-perimeter count to it. (create thin box around the area to correct)

**Comment by VanessaE** [comment]
Dupe of #3916

**Comment by VanessaE** [comment]
See also #3916

**Comment by elXaptation** [comment]
Thanks @supermerill, took me a few re-reads of the modifier mesh docs, but I think I got it.. Wow.. modifier meshes are amazing. Thank you!

Looks good on screen. I'll try to pint tonight.


![Screenshot - 04242019 - 03:58:51 PM](https://user-images.githubusercontent.com/19847622/56699476-72529900-66aa-11e9-8017-b0560f858811.png)
![Screenshot - 04242019 - 03:58:13 PM](https://user-images.githubusercontent.com/19847622/56699480-78e11080-66aa-11e9-8429-1ae7dd9269fe.png)
![Screenshot - 04242019 - 03:57:51 PM](https://user-images.githubusercontent.com/19847622/56699485-7b436a80-66aa-11e9-9e3e-3c23b00c2a78.png)

**Comment by elXaptation** [comment]
@VanessaE Thank for the reference. Looks like the same effect I'm seeing. The ModifierMesh solution apears to work great and easy to implement in my situation.
