### ISSUE TITLE
Spiral vase print of cylinder produces bad gcode

### ISSUE THREAD

**Issue by dc42** [alexrj/Slic3r#3044]
When slicing a cylinder in spiral vase mode, the resulting gcode produced by slic3r 1.2.9 spirals up by about 6mm for each layer instead of by the layer height. When reaching the starting point again, it drops the head to the original height plus the layer height. Here is an extract from the gcode at this point:

G1 Z11.261 X-11.691 Y21.872 E0.03614
G1 Z11.309 X-12.750 Y21.272 E0.03614
G1 Z11.356 X-13.778 Y20.620 E0.03614
G1 Z11.404 X-14.773 Y19.920 E0.03614
G1 Z11.452 X-15.733 Y19.171 E0.03614
G1 Z11.508 X-16.803 Y18.234 E0.04221
G1 Z5.6 F12000.000
G1 Z5.640 X-17.536 Y17.536 E0.03007 F2400.000
G1 Z5.687 X-18.376 Y16.655 E0.03614
G1 Z5.735 X-19.171 Y15.733 E0.03614
G1 Z5.783 X-19.920 Y14.773 E0.03614
G1 Z5.830 X-20.620 Y13.778 E0.03614

The cylinder I sliced was produced by this OpenScad model:

cylinder(r = 25, h = 30, $fn = 128);

Here is the end of the gcode file:

; filament used = 1206.7mm (2.9cm3)

; avoid_crossing_perimeters = 0
; bed_shape = 149.178x15.6793,146.722x31.1868,142.658x46.3525,137.032x61.0105,129.904x75,121.353x88.1678,111.472x100.37,100.37x111.472,88.1678x121.353,75x129.904,61.0105x137.032,46.3525x142.658,31.1868x146.722,15.6793x149.178,0x150,-15.6793x149.178,-31.1868x146.722,-46.3525x142.658,-61.0105x137.032,-75x129.904,-88.1678x121.353,-100.37x111.472,-111.472x100.37,-121.353x88.1678,-129.904x75,-137.032x61.0105,-142.658x46.3525,-146.722x31.1868,-149.178x15.6793,-150x0,-149.178x-15.6793,-146.722x-31.1868,-142.658x-46.3525,-137.032x-61.0105,-129.904x-75,-121.353x-88.1678,-111.472x-100.37,-100.37x-111.472,-88.1678x-121.353,-75x-129.904,-61.0105x-137.032,-46.3525x-142.658,-31.1868x-146.722,-15.6793x-149.178,0x-150,15.6793x-149.178,31.1868x-146.722,46.3525x-142.658,61.0105x-137.032,75x-129.904,88.1678x-121.353,100.37x-111.472,111.472x-100.37,121.353x-88.1678,129.904x-75,137.032x-61.0105,142.658x-46.3525,146.722x-31.1868,149.178x-15.6793,150x0
; bed_temperature = 0
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 0
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_gcode = G1 E-5 F4000\nG28\nM0\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF
; filament_diameter = 1.75
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0
; first_layer_speed = 50%
; first_layer_temperature = 205
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 15
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 8
; retract_length_toolchange = 10
; retract_lift = 0.5
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 100
; skirt_distance = 10
; skirt_height = 1
; skirts = 2
; slowdown_below_layer_time = 15
; spiral_vase = 1
; standby_temperature_delta = -5
; start_gcode = ; layer_height = [layer_height]\nG21 ; set units to millimeters\nG90 ; use absolute coordinates\nM83 ; use relative distances for extrusion\nG1 Z10 F10000 ; Ensure at a safe height\nG1 X0 Y150 F10000 ; Go to wait for warm position\nT0\nM116; Wait for all temperatures\n
; temperature = 195
; threads = 2
; toolchange_gcode = 
; travel_speed = 200
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.2
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.2
; raft_layers = 0
; seam_position = nearest
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 0.5
; support_material_speed = 100
; support_material_threshold = 0
; xy_size_compensation = 0
; bottom_solid_layers = 3
; bridge_flow_ratio = 1
; bridge_speed = 20
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 80%
; external_perimeters_first = 1
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 0%
; fill_pattern = rectilinear
; gap_fill_speed = 10
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15%
; infill_speed = 100
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 50
; perimeters = 1
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 80%
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 70%
; top_solid_layers = 0

**Comment by alexrj** [comment]
Thank you @dc42, I just tested this and I confirm it's fixed. Probably fixed long time ago.
