### ISSUE TITLE
Vase mode won't start if support is enforced but turned off

### ISSUE THREAD

**Issue by VikOlliver** [alexrj/Slic3r#3046]
The confusing message "Spiral vase mode is not compatible with support material" appears if a spiral vase mode Gcode output is attempted and support material is turned off. This happens when support is enforced for the first layer - although it won't actually be generated because support is turned off...

Took me a while to figure out what was going on there!

**Comment by a4jp-com** [comment]
Nice find. Got a sample file and config file for testing?

**Comment by VikOlliver** [comment]
It happens with any STL file. Not sure what a config file is - ~/.Slic3r contains a whole heap of .ini files. It might just be easier to start with any vase config that works for you, go to Print Settings/Support Material and make sure "Generate support material" is unticked. Then set "Enforce Support for the first:" to 1.

I'm fairly sure the problem lies here:
https://github.com/alexrj/Slic3r/blob/master/lib/Slic3r/Config.pm#L300

where there is an unnecessary check of support_material_enforce_layers.

Vik :v)

**Comment by lordofhyphens** [comment]
Export your config from the file menu.

Or make the fix, test it, and submit a pull request :)

**Comment by a4jp-com** [comment]
The files are needed just to check if the problem is just on one PC or every PC.

Also the wall thickness can make a difference depending on the model.

Do you have a link to a model with this problem? I don't have any vases to test and see if I have the same problem. All of my files have been coming out pretty well though.

File > Export config bundle...

**Comment by VikOlliver** [comment]
It is not possible to export the config. As I pointed out earlier, there is suspicious logic in Config.pm#L300. As this is called in any attempt to export the config, attempting to export the config will also reproduce the error!

**Comment by a4jp-com** [comment]
Can you take a screen shot of the settings then?

**Comment by thebobgeezer** [comment]
Thanks for the help. I was lost.  On the repetier host for print-rite, disabling support and setting enforce to 0 was good.  Happy building all.
B0B

**Comment by hyperair** [comment]
The tooltip message for "support_material_enforce_layers" suggests that it overrides the "support_material" option. Therefore the bug is not in the check that is done, but is more of a GUI bug where the option is grayed out when you uncheck "Generate support material".

    def->tooltip = "Generate support material for the specified number of layers counting from bottom, regardless of whether normal support material is enabled or not and regardless of any angle threshold. This is useful for getting more adhesion of objects having a very thin or poor footprint on the build plate.";

**Comment by VikOlliver** [comment]
I thought that, but I'm using v1.2.9 and I don't get support generated unless support is turned on, whatever is in that tick box. Am I just strangely unlucky?

**Comment by hyperair** [comment]
You're right. So `support_material` turns off `support_material_enforce_layers`, but the tooltip for `support_material_enforce_layers` says that shouldn't happen. Additionally, the vase mode does the `support_material || support_material_enforce_layers > 0` check.

So, which behaviour is correct?
