### ISSUE TITLE
Feature request: retract on first layer

### ISSUE THREAD

**Issue by kloppertje** [alexrj/Slic3r#3053]
Using Slic3r 1.2.9: In order to reduce the number of retracts, I enabled the option "Only retract when crossing perimeters". However, I'd like to see an option to disable this function for the first layer, so that no ooze is visible in the bottom of a printed object. Would this be possible? If required, I can try to make a photo of the issue.

**Comment by mrvn** [comment]
See https://github.com/alexrj/Slic3r/issues/3068 for a more general feature request for more retract options. I noticed the same problem.

**Comment by alexrj** [comment]
Since Slic3r now ignores that option for the top external layers, maybe we could do the same for the bottom, without even adding an option...

**Comment by xoan** [comment]
Nice solution :)

**Comment by kloppertje** [comment]
Seems like a perfect solution to me.

**Comment by alexrj** [comment]
Done!
