### ISSUE TITLE
Unusable corners with 3D Honeycomb infill

### ISSUE THREAD

**Issue by brandonheller** [alexrj/Slic3r#3055]
Starting with an OpenSCAD-generated box, then generating a 3d honeycomb infill with no outer perimeters or top/bottom solid layers, I see output that isn't cleanly printable within the Slic3r preview.

<img width="946" alt="screen shot 2015-08-31 at 12 06 26 am" src="https://cloud.githubusercontent.com/assets/82859/9573727/8bb2be94-4f74-11e5-8009-59f539724b84.png">

Focus on the diagonals at the bottom of the image; these would try to print unsupported.

The infill density is set to 5%. 

Also, some related questions:
(1) the angle didn't seem to affect anything.  Is this intended with this fill?  Might be nice to have more vertical patterns that match ones I see from the original feature request discussion:
https://github.com/alexrj/Slic3r/issues/1646
(2) are the lines supposed to alternate, causing lots of effective bridging?  I had assume the walls would print solid.

BTW, Slic3r has really improved in the last year - thanks for all the features and bug fixes!

**Comment by lordofhyphens** [comment]
Please provide what is asked in the contributing guidelines.

Additionally I don't think 3d honeycomb is meant to be printable with 0 perimeters.
