### ISSUE TITLE
Bug: Wipe while retracting / Use FW retraction

### ISSUE THREAD

**Issue by wes1007** [alexrj/Slic3r#3056]
Noticed a bug while setting up Slic3r.

If one sets Wipe while reacting (Printer Settings>Extruder1) and Use FW Retraction (Printer settings>General an error message appears when clicking changing settings on a model:

--use-firmware-retraction is not compatible with --wipe

Steps to reproduce:
1. Set Printer Settings>Extruder1>Wipe while retracting to Enabled
2. Set Printer settings>General>Use FW Retraction to Enabled
3. Load a model and and right click on it and click settings

I would suggest that when enabling firmware retraction a check is done to see if wipe when retracting is enabled and possibly disable it with a dialog stating that both cant be enabled

Edit I'm using V1.2.9

**Comment by alexrj** [comment]
Okay, not really a bug but I added the additional prompt you suggested.
