### ISSUE TITLE
Feature request: lift Z on retraction, except on first N layers

### ISSUE THREAD

**Issue by dc42** [alexrj/Slic3r#3057]
Please can the "Lift Z" option in Printer settings -> Extruder 1 have a "except on first N layers" option. I generally find "Lift Z" works well, however on prints with sharp pointy corners it tends to cause that part of the print to detach from the bed if a lift occurs at that point in the first layer or two.

**Comment by a4jp-com** [comment]
Maybe an option like that would help but also changing the heat settings is another way to fix this. Can you post a picture of one of your printed models with the problem? What type of print bed do you have? Also are you using a skirt and raft?

**Comment by luke321** [comment]
I am currently working on a Gcode Post Processor which eliminates z Lift for a certain number of layers and for short travel distances.
This is definitely a nice feature to reduce print time and increase print quality!

**Comment by a4jp-com** [comment]
Cool. I always went with the heat settings to fix problems like this but anything that makes printing easier is greatly welcomed ^^

**Comment by Lenbok** [comment]
This would also be addressed by #1316  (which discusses e.g. auto adding "mouse ears" on sharp corners)

**Comment by alexrj** [comment]
This is complementary to #763

**Comment by alexrj** [comment]
I'll add two new options:
* `--retract-lift-above`
* `--retract-lift-below`

Both will accept an absolute Z. If `below` is zero, lift will take place on the entire print.

**Comment by alexrj** [comment]
Done.
