### ISSUE TITLE
Missing information in 'Unsaved Changes' warning message

### ISSUE THREAD

**Issue by demestav** [alexrj/Slic3r#3061]
Slic3r notifies the user when the profile is switched and there are unsaved changes. The message informs the user about the unsaved setting by specifying the category and the name of the setting. As shown in the attached image, `Extrusion Width > Perimeters`. For the `Extrusion Width > First layer`, the message is missing the `Extrusion Width > ` part (see attached image).

To reproduce:
1) Select any profile
2) Change `Extrusion Width > First layer` to a different value
3) Select a different profile

![slic3r_bug](https://cloud.githubusercontent.com/assets/1180929/9771182/0baa016e-573d-11e5-8386-fcd52fc64f58.png)

**Comment by alexrj** [comment]
Fixed, thank you.
