### ISSUE TITLE
Changing the custom layer heights doesn't change the slicing

### ISSUE THREAD

**Issue by PaulCornelissen** [alexrj/Slic3r#3066]
Custom layer heights for different sections is a brilliant feature that can save a lot of printing time and resolve problems in general, but (at least) in Slic3r 1.2.9 on OS X the custom layer heights are only used when I first set them. 

So they work the first time I set them, but if I then see something in the slicing preview I'd like to change the only reliable way to get it to work is to delete the .STL, re-import it and re-enter all the custom settings. This is also true if I want to delete the custom setting.

**Comment by alexrj** [comment]
That bug was fixed shortly after releasing 1.2.9.  The fix will be included in 1.2.10. Thank you for reporting.
