### ISSUE TITLE
Slic3r crashing when trying to slice with 0.05mm layer height

### ISSUE THREAD

**Issue by wuflnor** [alexrj/Slic3r#307]
I was testing some very low layer heights but i have a problem
When i try to slice http://www.thingiverse.com/download:34066 with 0.05mm layer then slic3r crashes. Its diffrent everytime, some times its clipper.pm error [same as in https://github.com/alexrj/Slic3r/issues/71], sometimes its hard crash, and other times slic3r just closes.
Memory usage comes up to 1,2Gb and CPU usage to 50%. 
I dont know if this is problem with to big file, or memory leak, or maybe something else.
My config.ini looks like this:
acceleration = 0
bed_temperature = 0
bottom_layer_speed_ratio = 0.3
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 60
cooling = 1
disable_fan_first_layers = 2
duplicate_distance = 6
duplicate_x = 1
duplicate_y = 1
end_gcode = M140 S0 ;Turn heated bed off\nM104 S0 ;Turn nozzle heat off\nG28 X0  ; home X axis\nM84 ;Disable steppers so they dont get hot during idling...\nM84 S0 ;Cancel the timeout set by the start gcode
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width_ratio = 0
fan_always_on = 
fan_below_layer_time = 40
filament_diameter = 3.1
fill_angle = 45
fill_density = 0.8
fill_pattern = rectilinear
first_layer_bed_temperature = 0
first_layer_height_ratio = 1
first_layer_temperature = 230
g0 = 0
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
infill_acceleration = 50
infill_every_layers = 1
infill_speed = 80
layer_height = 0.05
max_fan_speed = 100
min_fan_speed = 55
min_print_speed = 10
notes = 
nozzle_diameter = 0.5
output_filename_format = [input_filename_base].gcode
perimeter_acceleration = 25
perimeter_speed = 50
perimeters = 1
post_process = 
print_center = 80,100
retract_before_travel = 2
retract_length = 1
retract_lift = 0
retract_restart_extra = 0
retract_speed = 10
rotate = 90
scale = 1
skirt_distance = 6
skirt_height = 1
skirts = 1
slowdown_below_layer_time = 0
small_perimeter_speed = 30
solid_fill_pattern = rectilinear
solid_infill_speed = 80
solid_layers = 2
start_gcode = M104 S0 ;Cancel the M104 set by Slic3r\nM140 S100 ;Start heating the bed up\nG28 ; home all axes\nM84 ;Disable all steppers\nM84 S30 ;Set stepper timeout to 30 seconds\nM190 S100 ;Set bed temperature and wait\nM140 S110 ;Set bed temperature but continue with the gcode
support_material = 0
support_material_tool = 0
temperature = 220
travel_speed = 150
use_relative_e_distances = 0
z_offset = 0

**Comment by lordofhyphens** [comment]
@wuflnor could you test this with current stable and let me know if it works now (so I can close this ancient issue)? 

I know I've been able to slice most things with ridiculously low layer heights.

**Comment by lordofhyphens** [comment]
On second thought, I'm going to close it now, if it still doesn't work for you @wuflnor put a comment in with a fresh config.ini.
I was able to slice with no crash with 1.2.9 and your config and that model.
