### ISSUE TITLE
NOTES.... 

### ISSUE THREAD

**Issue by D9ve** [alexrj/Slic3r#3097]
Hi,

Please can you add a notes tab for each main tab(saved profile) ie one for the filament and another for the printer. This would enable users to keep track of their minor modifications to specific profiles. I have spoken to a few people regarding this and we all tend to  use paper (which gets lost) or a separate document, can get confusing, it would be nice to have it tied to the setting that you are working on. For example for certain filaments such as Blue PLA type 2: I could include supplier, e-step settings, temperature settings for different model types (thin walled, viase, 100% infill). Also most importantly how well your type of filament worked for specific tasks.

What do you all think?

Much obliged,

David

**Comment by alexrj** [comment]
Thank you David, we added noted for Print Settings and Filament Settings.
For printer settings that's much less needed but you can still put comments in the G-code section.
