### ISSUE TITLE
1.2.9 CRASHES on MAC OS X 10.11

### ISSUE THREAD

**Issue by adernicolasK8200** [alexrj/Slic3r#3098]
I'm unable to use the 1.2.9 version, unstable, mostly crashes when loading the .STL file. 
I've never been able to use it, crashes since installation. 
Had to step down to the 0.9.9 included in the Repetier.
Mac Book Pro 15" (april 2010)
OS X El Capitan
8 Go RAM
500 Go HDD

Printer K8200

Any help? 

Thank you! 

Bellow extracts of the crash report: 

Process:               slic3r [49069]
Path:                  /Applications/Slic3r.app/Contents/MacOS/slic3r
Identifier:            slic3r
Version:               Slic3r 1.2.9.99 (1.2.9.99)
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           slic3r [49069]
User ID:               501

Date/Time:             2015-10-21 16:01:15.179 +0300
OS Version:            Mac OS X 10.11 (15A284)
Report Version:        11
Anonymous UUID:        DD59DEAC-88DC-1D85-01A4-814BBAE13F89

Sleep/Wake UUID:       6E96A5ED-7863-4AEF-8F0B-B4601E484E70

Time Awake Since Boot: 950000 seconds
Time Since Wake:       9300 seconds

System Integrity Protection: enabled

Crashed Thread:        13

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000006574744c
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x6574744c:
    __LINKEDIT             00000000495cb000-000000004962b000 [  384K] r--/rwx SM=COW  /System/Library/Extensions/GeForceTeslaGLDriver.bundle/Contents/MacOS/GeForceTeslaGLDriver
--> 
    __TEXT                 000000008fef8000-000000008ff2d000 [  212K] r-x/rwx SM=COW  /usr/lib/dyld

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x9796c07a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x9796b464 mach_msg + 68
2   com.apple.framework.IOKit     	0x949432ee io_connect_method + 424
3   com.apple.framework.IOKit     	0x948d8774 IOConnectCallMethod + 403
4   com.apple.GeForceTeslaGLDriver	0x4834bd18 0x48000000 + 3456280
5   libGPUSupport.dylib           	0x9231cc99 gldDestroyContext + 110
6   GLEngine                      	0x98e49bfb gliDestroyContext + 130
7   com.apple.opengl              	0x929973f9 CGLReleaseContext + 206
8   com.apple.opengl              	0x92996511 CGLDestroyContext + 29
9   com.apple.QuartzCore          	0x94faab2c view_destroy_state(_CAViewState*, bool) + 209
10  com.apple.QuartzCore          	0x94f4d08e view_finalize(void const*) + 204
11  com.apple.CoreFoundation      	0x9cceabde CFRelease + 766
12  com.apple.AppKit              	0x90d34b89 -[_NSCGSWindowLocallyRenderedLayerSurface dealloc] + 44
13  libobjc.A.dylib               	0x9005b7df objc_object::sidetable_release(bool) + 239
14  libobjc.A.dylib               	0x90058d1c -[NSObject release] + 25
15  libobjc.A.dylib               	0x900581b0 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 488
16  com.apple.CoreFoundation      	0x9cd2994f _CFAutoreleasePoolPop + 47
17  com.apple.Foundation          	0x9906a478 -[NSAutoreleasePool drain] + 122
18  com.apple.AppKit              	0x905551c6 -[NSApplication run] + 946
19  libwx_osx_cocoau_core-3.0.0.0.0.dylib	0x05bbc685 wxGUIEventLoop::OSXDoRun() + 277
20  libwx_baseu-3.0.0.0.0.dylib   	0x062397c6 wxCFEventLoop::DoRun() + 38
21  libwx_baseu-3.0.0.0.0.dylib   	0x061689ba wxEventLoopBase::Run() + 74
22  libwx_baseu-3.0.0.0.0.dylib   	0x06128a3f wxAppConsoleBase::MainLoop() + 95
23  Wx.bundle                     	0x05575be2 wxPliApp::MainLoop() + 50
24  Wx.bundle                     	0x0551a8b1 XS_Wx__App_MainLoop(interpreter*, cv*) + 129
25  libperl.dylib                 	0x000e74a6 Perl_pp_entersub + 2294
26  libperl.dylib                 	0x000e5af6 Perl_runops_standard + 22
27  libperl.dylib                 	0x0007542e perl_run + 366
28  slic3r                        	0x00006d2b 0x1000 + 23851
29  slic3r                        	0x000045a5 0x1000 + 13733

Thread 1:
0   libsystem_kernel.dylib        	0x97972e16 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9298535f _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x92982f82 start_wqthread + 34

Thread 2:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x979738b2 kevent_qos + 10
1   libdispatch.dylib             	0x9ace0836 _dispatch_mgr_invoke + 234
2   libdispatch.dylib             	0x9ace040a _dispatch_mgr_thread + 52

Thread 3:
0   libsystem_kernel.dylib        	0x97972e16 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9298535f _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x92982f82 start_wqthread + 34

Thread 4:
0   libsystem_kernel.dylib        	0x97972e16 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9298535f _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x92982f82 start_wqthread + 34

Thread 5:
0   libsystem_kernel.dylib        	0x97972e16 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9298535f _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x92982f82 start_wqthread + 34

Thread 6:
0   libsystem_kernel.dylib        	0x97972e16 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9298535f _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x92982f82 start_wqthread + 34

Thread 7:
0   libsystem_kernel.dylib        	0x97972e16 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9298535f _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x92982f82 start_wqthread + 34

Thread 8:
0   libsystem_kernel.dylib        	0x97972e16 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9298535f _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x92982f82 start_wqthread + 34

Thread 9:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x9796c07a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x9796b464 mach_msg + 68
2   com.apple.CoreFoundation      	0x9cd6d096 __CFRunLoopServiceMachPort + 214
3   com.apple.CoreFoundation      	0x9cd6c4a1 __CFRunLoopRun + 1521
4   com.apple.CoreFoundation      	0x9cd6bc46 CFRunLoopRunSpecific + 390
5   com.apple.CoreFoundation      	0x9cd6baab CFRunLoopRunInMode + 123
6   com.apple.AppKit              	0x906ca1c2 _NSEventThread + 291
7   libsystem_pthread.dylib       	0x92985794 _pthread_body + 138
8   libsystem_pthread.dylib       	0x9298570a _pthread_start + 155
9   libsystem_pthread.dylib       	0x92982fa6 thread_start + 34

Thread 10:: com.apple.CoreAnimation.render-server
0   libsystem_kernel.dylib        	0x9796c07a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x9796b464 mach_msg + 68
2   com.apple.QuartzCore          	0x94f1d8e0 CA::Render::Server::server_thread(void*) + 307
3   com.apple.QuartzCore          	0x94f1d7a4 thread_fun + 29
4   libsystem_pthread.dylib       	0x92985794 _pthread_body + 138
5   libsystem_pthread.dylib       	0x9298570a _pthread_start + 155
6   libsystem_pthread.dylib       	0x92982fa6 thread_start + 34

Thread 11:
0   libsystem_kernel.dylib        	0x97972e16 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9298535f _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x92982f82 start_wqthread + 34

Thread 12:: com.apple.appkit-heartbeat
0   libsystem_kernel.dylib        	0x97972886 __semwait_signal + 10
1   libsystem_c.dylib             	0x92cba632 nanosleep$UNIX2003 + 218
2   libsystem_c.dylib             	0x92cba4de usleep$UNIX2003 + 60
3   com.apple.AppKit              	0x90871ab5 -[NSUIHeartBeat _heartBeatThread:] + 2288
4   com.apple.Foundation          	0x99089b37 -[NSThread main] + 45
5   com.apple.Foundation          	0x990898c2 __NSThread__start__ + 1550
6   libsystem_pthread.dylib       	0x92985794 _pthread_body + 138
7   libsystem_pthread.dylib       	0x9298570a _pthread_start + 155
8   libsystem_pthread.dylib       	0x92982fa6 thread_start + 34

Thread 13 Crashed:
0   libperl.dylib                 	0x000e71cc Perl_pp_entersub + 1564
1   libperl.dylib                 	0x00074bcd Perl_call_sv + 509
2   libperl.dylib                 	0x000c9fcc S_invoke_exception_hook + 492
3   libperl.dylib                 	0x000cbe33 Perl_vwarner + 243
4   libperl.dylib                 	0x000cbeac Perl_warner + 44
5   libperl.dylib                 	0x000f0a76 Perl_sv_free + 182
6   libperl.dylib                 	0x000a911d Perl_cv_undef + 701
7   libperl.dylib                 	0x000f0f47 Perl_sv_clear + 1111
8   libperl.dylib                 	0x000f0985 Perl_sv_free2 + 85
9   libperl.dylib                 	0x0011a411 Perl_free_tmps + 97
10  libperl.dylib                 	0x00074df3 Perl_call_sv + 1059
11  threads.bundle                	0x04c32f4a S_ithread_run + 1546
12  libsystem_pthread.dylib       	0x92985794 _pthread_body + 138
13  libsystem_pthread.dylib       	0x9298570a _pthread_start + 155
14  libsystem_pthread.dylib       	0x92982fa6 thread_start + 34

Thread 13 crashed with X86 Thread State (32-bit):
  eax: 0x026b8000  ebx: 0x65747441  ecx: 0x13945530  edx: 0x00000001
  edi: 0x00000000  esi: 0x00000001  ebp: 0xb06aab78  esp: 0xb06aab10
   ss: 0x00000023  efl: 0x00010202  eip: 0x000e71cc   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000023   gs: 0x0000000f
  cr2: 0x6574744c
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate.framework               256K        3 
Activity Tracing                  2048K        2 
CG backing stores                 5632K        7 
CG image                           424K       56 
CG shared images                   336K       10 
CoreAnimation                      900K       59 
CoreUI image data                  584K       39 
CoreUI image file                  384K        5 
Foundation                           4K        2 
IOKit                             15.5M        2 
Kernel Alloc Once                    4K        2 
MALLOC                           133.3M       66 
MALLOC guard page                   48K       10 
Memory Tag 242                      12K        2 
OpenCL                              40K        6 
OpenGL GLSL                        128K        3 
Process Corpse Info               2048K        2 
Stack                             14.1M       15 
Stack Guard                       56.1M       15 
VM_ALLOCATE                        268K       46 
__DATA                            26.0M      320 
__GLSLBUILTINS                    2588K        2 
__IMAGE                            528K        2 
__LINKEDIT                        59.7M       66 
__OBJC                            4700K      103 
__TEXT                           230.1M      319 
__UNICODE                          552K        2 
mapped file                      107.5M      101 
shared memory                     16.4M        9 
===========                     =======  ======= 
TOTAL                            679.6M     1247 

Model: MacBookPro6,2, BootROM MBP61.0057.B10, 2 processors, Intel Core i7, 2,66 GHz, 8 GB, SMC 1.58f17
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 512 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x855D, 0x202020202020202020202020202020202000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x855D, 0x202020202020202020202020202020202000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 4.4.0f4 16320, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: OCZ-VECTOR150, 480,1 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FT232R USB UART
USB Device: Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FT232R USB UART
USB Device: IR Receiver
USB Device: Built-in iSight
Thunderbolt Bus:

**Comment by lordofhyphens** [comment]
Probably your graphics drivers pitching a fit, from what I can see in the logs you provided. Might want to try the prusa3d.com OSX build, update your graphics drivers, build your own version of 1.3.0-dev from source, or try any combination of the above.

If you're still having issues, reopen.
