### ISSUE TITLE
UI hang on Ubuntu 15.04

### ISSUE THREAD

**Issue by Dinsmoor** [alexrj/Slic3r#3102]
Left window open after exporting g-code, came back, UI nonresponsive, with:
```
Use of uninitialized value in concatenation (.) or string at /home/d/dev/src/Slic3r/lib/Slic3r/GUI/Plater.pm line 1209.
```
In the terminal. Had to force quit.
Git Revision 5b8ed7367a2a9148c215eafa53c7e13b30cd0c36
Ubuntu 15.04 GNU/Linux

"Attaching documents requires write permission to this repository." - could not include configuration file.

**Comment by lordofhyphens** [comment]
Is this still a problem?

**Comment by Dinsmoor** [comment]
I haven't had an issue with this for a long time, I presume fixed somewhere along the line.
