### ISSUE TITLE
can't calculate thin wall object with XY size compensation

### ISSUE THREAD

**Issue by lordfwahfnah** [alexrj/Slic3r#3107]
Hi guys, 
just found out that slic3r was stuck on "processing triangulated mesh..." a thin wall object since i added a -0.2mm XY Size compensation. 
It does make sense but i guess it's better to cancel the calculation with an error when such objects are recognised.
Or maybe put an hint into the infos of the XY compensation.

**Comment by alexrj** [comment]
Thank you, fixed.
