### ISSUE TITLE
1.2.10-dev (Windows 10) - Infill patterns not working

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#3110]
I just updated to 1.2.10-dev (Windows 10) and the infill patterns are not changing.

The top/bottom fill pattern is working though.

http://a4jp.com/3d-files/bugs/CUBE.stl

http://a4jp.com/3d-files/bugs/2015-11-02nd-05-52-pm-for-github-config.ini

![screen shot 11-02-15 at 05 54 pm 001](https://cloud.githubusercontent.com/assets/9621044/10877581/daa51b6c-818a-11e5-9626-f3c0e8b4a23b.JPG)
![screen shot 11-02-15 at 05 54 pm](https://cloud.githubusercontent.com/assets/9621044/10877582/dac63752-818a-11e5-803c-7995480155ff.JPG)

**Comment by a4jp-com** [comment]
Did the infill work with 1.2.9? I didn't try changing it so I'm not sure.

**Comment by markwal** [comment]
It did, but perhaps you're below the 70 mm^2 threshold so it is always solid?  10x10 would be 100 minus the area covered by the perimeters.  What happens on a 20x20 cube or if you set the solid infill threshold to 0?

**Comment by a4jp-com** [comment]
I did a 20x20mm cube and it worked. I hope the smaller infill can get fixed soon. I make little houses and the diagonal fill is really bad on these little houses. I need a way to select other fill patterns if possible.

**Comment by markwal** [comment]
You can just set that solid infill threshold to something lower like 30 it's right there in your picture

Sent from my Windows Phone
________________________________

**Comment by a4jp-com** [comment]
I set the threshold to 0 and got the infill settings back but I just want to know why it is set to 70 by default. What problem is this trying to fix? If the program disables the infill pattern could it gray out the box and say "decrease the solid threshold area to allow fill patterns"?

**Comment by markwal** [comment]
It doesn't know it is disabling the infill for the whole part. It only does this per each infill area per layer. And your settings aren't for only one part anyway.

This is to prevent weirdness when the infill pattern, low infill and a very small area combine to make the infill absurd. For a bot that isn't under or over extruding, solid infill helps improve quality without to much expense because the area is small.

Sent from my Windows Phone
________________________________

**Comment by a4jp-com** [comment]
@alexrj what do you think about the default number 70? Is that best?

**Comment by alexrj** [comment]
It has proven to be reasonable for several years.
