### ISSUE TITLE
Request: Increase max temperature for filaments to 500°C at least

### ISSUE THREAD

**Issue by simonkuehling** [alexrj/Slic3r#3114]
Hi,

with our latest revision of the RepRap Industrial we're ready for some really high melting temperatures of up to 500°C - needed for fancy materials like PEEK for example (430-470°C roughly). During testing i ran into a max limit of 400°C extruder temperature in Slic3r.

A temporary work-around is setting the temperature in the start GCODE, but it would be great if the limit could be increased instead. Or the limit could be replaced by a warning alert shown when high temperatures are being entered in a filament preset...

**Comment by alexrj** [comment]
Thank you @simonkuehling, I did this. And congrats for making a printer able to reach those temperatures... :-)
