### ISSUE TITLE
Slic3R 1.29, sliced box has no bottom in output

### ISSUE THREAD

**Issue by justmyopinion** [alexrj/Slic3r#3124]
![box_](https://cloud.githubusercontent.com/assets/5621573/11032890/6441bbba-86df-11e5-9011-c8a50efc2cb3.JPG)

![box](https://cloud.githubusercontent.com/assets/5621573/11032768/4f712776-86de-11e5-9a18-3c2b41d6cac3.JPG)

When I slice this (simple box) bottom disappears and I find no settings to get bottom slice output.
Slic3r 1.29/ W7/64

https://www.dropbox.com/s/s9bhrn0mz3x3583/Box_config.ini?dl=0
https://www.dropbox.com/s/fnw7fv715jo8thy/Box_.stl?dl=0

**Comment by a4jp-com** [comment]
Printer settings > Horizontal shells > Solid layers... may help

**Comment by justmyopinion** [comment]
Ok, found it, there was indeed no dimension created on the bottonplate, but no errors was issued so it was not recognized. Sorry

**Comment by a4jp-com** [comment]
^^
