### ISSUE TITLE
Use of uninitialized value in concatenation (.) or string at /.../Slic3r/lib/Slic3r/GUI/Plater.pm line 1212

### ISSUE THREAD

**Issue by kino3d** [alexrj/Slic3r#3130]
current git , linux 

Use of uninitialized value in concatenation (.) or string at /.../Slic3r/lib/Slic3r/GUI/Plater.pm line 1212
config
https://www.dropbox.com/s/nz7p80dvbb2kz8k/config-error.ini?dl=0

**Comment by alexrj** [comment]
This was fixed.
