### ISSUE TITLE
Feature Request: Multiple configs for a single slice, with select layer ranges using Config INI Section Names

### ISSUE THREAD

**Issue by h3rb** [alexrj/Slic3r#3131]
It would be extremely useful for me to be able to say "use this config for these layers", where I could specify infill (and other options) for specific layers  .. this feature is probably an enhancement of the "every nth layer" feature.

ie:

; For setting special parameters on the first layer that override the 'master settings'

[special_settings_for_layer_1]  ; this is a "config section" name
start_layer=1
end_layer=1
... settings here

; For setting special params on the 2nd-10th layer:
[special_settings_for_layers_1_10]
start_range=2
end_range=10
... settings here

etc

**Comment by ghuser2** [comment]
Isn't this how modifiers work?

**Comment by h3rb** [comment]
Can someone show me the documentation for modifiers?  I'm not yet convinced I have the full control I'm hoping for.  What are the limits of mesh modifiers?  CAn you have multiple mesh modifiers interacting with the same layer?  Can you have any mesh shape or only cubes?  Do they have to be 2d extruded along the Z or can they be a sphere for example?

**Comment by lordofhyphens** [comment]
See #3590 and http://slic3r.org/blog/modifier-meshes
