### ISSUE TITLE
[request] Show approximate print time in info

### ISSUE THREAD

**Issue by Lord2Vader** [alexrj/Slic3r#3137]
Would be nice to get a print time shown in the info.

With repetierhost i get that, but not in slic3r itself.
I upload a gcode to octoprint and then it shows like 24h print. Would be nice to know before uploading ;)

**Comment by mrvn** [comment]
Include the filament length / volume and estimated weight too. When I print at the local fablab (makerspace) I have to pay by weight so it would be nice to know beforehand.

**Comment by pyrophreek** [comment]
I would suggest integrating this into #2979.  This would be best if you could slice the file in Slic3r without exporting it to view filament usage, time, etc.  Then if it is too long, or too much filament, you could adjust settings prior to uploading/saving the gcode.

**Comment by claell** [comment]
Any update on this?

**Comment by lordofhyphens** [comment]
The filament length is already in the gcode; grep for "; filament used = " in the output gcode.

@kliment put an estimator into #1334. If someone wants to cook up a clean planner/estimator and submit it as a PR, I'll at least look at it and review it for a PR. I know I have no interest in working on such a thing myself.
