### ISSUE TITLE
Skirt do not attaching to the object (light brim tentative)

### ISSUE THREAD

**Issue by thiagopeixoto16** [alexrj/Slic3r#3138]
Hello!

I'd like to do something the people do at Cura, that is set skirt to 0 and have a brim for the object border only, however when I set that to 0 I get something like the images below.
I have printed that to make sure this is not just a visualization mistake.
Is it possible to 0 really means attached or allow negatives values for that parameter?

Thanks!

![image](https://cloud.githubusercontent.com/assets/4227271/11375922/0a9edc90-92c5-11e5-9b31-ca4748bde1ee.png)
![image](https://cloud.githubusercontent.com/assets/4227271/11376026/9d97e938-92c5-11e5-9801-61cfab457379.png)

**Comment by a4jp-com** [comment]
I see what you mean. 0mm is not 0.

**Comment by pyrophreek** [comment]
have you tried setting it to 0.01? I think setting it to 0 may  be interpreted as just using the default, rather than actually 0.

**Comment by Sebastianv650** [comment]
I'm maybe missing something, but why you don't use the brim feature for a brim?

**Comment by pyrophreek** [comment]
if you are printing something with very convoluted outer perimeter (such as a gear), it can be difficult to remove the brim from inside the concave areas (ie. between teeth).  In this case, it would be almost as effective to prevent warping to attach only the tips of the teeth to the brim, while making it much easier to remove.  Or at least this is my experience.

**Comment by a4jp-com** [comment]
Even if the distance is set to 0.01mm there is still a gap that is much larger.

![screen shot 11-25-15 at 04 34 pm](https://cloud.githubusercontent.com/assets/9621044/11391015/907feb6a-9392-11e5-9705-c3cfaf2d8f6d.JPG)
![screen shot 11-25-15 at 04 34 pm 001](https://cloud.githubusercontent.com/assets/9621044/11391018/97bcc6a0-9392-11e5-9aa2-10a9552a662f.JPG)

I agree with @pyrophreek. If this setting of 0mm or 0.01mm etc can connect at 0mm, it would be wonderful. I would be able to make bases for people without having to model anything very quickly which is very useful. A brim is only 1 layer thick so this skirt fix would allow so many new things to be created quickly. If it's okay could you please adjust the code here @alexrj .

**Comment by thiagopeixoto16** [comment]
I think we can close this due the new Brim distance on this [commit](https://github.com/alexrj/Slic3r/commit/af46db320f820cc68e692cccf2f83890f4ee1596)
