### ISSUE TITLE
Arrange button not working

### ISSUE THREAD

**Issue by koghe** [alexrj/Slic3r#3149]
Hi
load 2 different objects, press "Arrange" , nothing happen.
current git
linux ubuntu 15.04

ps.while triyng i cannot select 2 objects from the list panel.

**Comment by lordofhyphens** [comment]
One of the reasons that can happen is that the logic can't find a place to
put everything.

**Comment by koghe** [comment]
It work for you? even for simple object? with 2 cubes doesn't work, also with "More" option and duplicated objects

**Comment by kefir-** [comment]
Slic3r arranges as you load, so there's nothing to change when you click arrange if you haven't done anything else. Have you moved the objects first, and then tried clicking arrange? Does something happen then?

**Comment by koghe** [comment]
No, just load 2 object one after other and press the button nothing happen, or try with this object 
load, it then right click and select split, click on arrange and nothing...
https://www.dropbox.com/s/3q298h7d7jujdik/coolingcase.stl?dl=0

i see alex is working on a new gui, will wait for it :)

**Comment by lordofhyphens** [comment]
I actually disable auto arrange myself. It can be a headache.

**Comment by koghe** [comment]
:) yes but sometmes is useful to arrange multiple objects, np will wait

**Comment by koghe** [comment]
with last commits it work better 
open
![selection_072](https://cloud.githubusercontent.com/assets/745801/11653650/d8272b74-9d9f-11e5-8ad4-79ce64615a08.jpg)

split

![selection_073](https://cloud.githubusercontent.com/assets/745801/11653653/dd9c96f2-9d9f-11e5-965c-a9905574131e.jpg)

Arrange first click 

![selection_074](https://cloud.githubusercontent.com/assets/745801/11653661/ee2d676c-9d9f-11e5-8614-86edfff6aa91.jpg)

Click Arrange again.. ok! 

![selection_075](https://cloud.githubusercontent.com/assets/745801/11653677/fbca3148-9d9f-11e5-8aa5-c19a77cad87c.jpg)

**Comment by koghe** [comment]
after this fix arrange work with one click only https://github.com/alexrj/Slic3r/commit/c73378744f0d6e8c4a07952d9228069f35fcb56e

manually arranged
![selection_079](https://cloud.githubusercontent.com/assets/745801/11819846/5f56bf48-a362-11e5-8b13-fa92e5c1d289.jpg)

click to Arrange

![selection_080](https://cloud.githubusercontent.com/assets/745801/11819861/74ed5010-a362-11e5-8eae-c4098e31c0f4.jpg)

it work better now

**Comment by alexrj** [comment]
Ok.
