### ISSUE TITLE
[1.2.10-dev] Slic3r is putting random moves to bottom corner on layer change

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#3156]
Printing http://www.thingiverse.com/thing:1071090
The resultant gcode has a move to the lower-left corner of the part on every layer change.

config:
[config-move-to-corner.txt](https://github.com/alexrj/Slic3r/files/60254/config-move-to-corner.txt)

**Comment by alexrj** [comment]
Was this with the master or the stable branch?
If it's with master, can you retry now? 667a121ddbbe9732c3831166792128a901c01315 might fix it.

**Comment by hoh61** [comment]
I can confirm this effect for revision 1.3.0-dev, downloaded Dec. 8th 2015.

Slicing this part: http://www.thingiverse.com/thing:1133248

![extruder_cover_g](https://cloud.githubusercontent.com/assets/14939467/12536229/a4a717d0-c29f-11e5-9cfd-c8f01b3010e7.jpg)

**Comment by lordofhyphens** [comment]
Looks like it's fixed for my test model.
