### ISSUE TITLE
Slic3r crashes when I click on "Controller" tab

### ISSUE THREAD

**Issue by mmarkle** [alexrj/Slic3r#3159]
When I click on the Controller tab, it crashes and leaves the message "Segmentation fault (core dumped)" in the terminal. Not sure if this is related to issue #3158 which I just submitted.
[config_no_connect.zip](https://github.com/alexrj/Slic3r/files/60749/config_no_connect.zip)
Commit ID: 21364b7cd10fa503bde4b53c53f97c2e76b75203
OS and version: Xfce 4.10 Ubuntu run through crouton on a chromebook.

**Comment by alexrj** [comment]
Fixed, thank you. There was a compatibility issue with wxWidgets 2.8.x. which was not easy for me to find.
