### ISSUE TITLE
The manual control window isn't wide enough

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#3164]
The manual control window isn't wide enough and cuts off the text.

![screen shot 12-19-15 at 04 41 am](https://cloud.githubusercontent.com/assets/9621044/11905662/01f1c84c-a60b-11e5-9141-f80d88b78c37.JPG)

Version 1.3.0-dev

Fantastic loading speed of files though. Thank you for the speed up in coding.

**Comment by alexrj** [comment]
Yeah, that needs some more work, including temperature control and box for sending commands. Background shouldn't be black, though. I'll check.

**Comment by a4jp-com** [comment]
Cool. Thanks for all the checks and updates recently.
