### ISSUE TITLE
White grid is too bright

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#3169]
I made this to make the grid dark gray so the text is readable.

https://github.com/a4jp-com/Slic3r/commit/15cd55cf2f450d004f0a2cd957001999b74f7dde

**Comment by Mikk36** [comment]
Got comparison images to show?

**Comment by xoan** [comment]
What version? In 1.2.9 text is perfectly readable.
![captura de pantalla - 201215 - 15 13 48](https://cloud.githubusercontent.com/assets/288246/11918325/690829b4-a72c-11e5-8590-52ea82127e9a.png)

**Comment by a4jp-com** [comment]
Version 1.3.0-dev

![screen shot 12-21-15 at 12 14 am](https://cloud.githubusercontent.com/assets/9621044/11918516/e9aede6e-a777-11e5-878d-368038a3e7ba.JPG)
![screen shot 12-20-15 at 01 40 pm](https://cloud.githubusercontent.com/assets/9621044/11918515/e9aecbea-a777-11e5-99ed-81b9c0094e40.JPG)

**Comment by alexrj** [comment]
Black background is a bug.

**Comment by a4jp-com** [comment]
Okay. I though it was a design change.

**Comment by alexrj** [comment]
Is this fixed as of current master?

**Comment by lordofhyphens** [comment]
I think so, I don't think I've seen the black background for the regular plater for quite some time.
