### ISSUE TITLE
Slic3r 1.3.0-dev: Option to easily set temperature while printing from the controller. Also before printing.

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#3171]
Slic3r 1.3.0

First I just wanted to say I can now print directly from Slicer and it is amazing. Thank you so much. 

If you add a box under the current temperature values to easily change the temperature values while printing it would be even better.

Temperature:
Nozzle: 212.0 C    Bed: 65 C

Set temperature: 
Nozzle: XXX C    Bed: XXX C     Set    Off

If this could be used anytime including while printing it would be very nice and also useful when changing filament too.

**Comment by a4jp-com** [comment]
Is there a way to send G-code?

**Comment by alexrj** [comment]
@a4jp-com, we now have both temperature controls and a field for sending G-code manually. Thanks for the input!

**Comment by a4jp-com** [comment]
Thank you ^^
