### ISSUE TITLE
Bridging Regression since 1.2.9

### ISSUE THREAD

**Issue by ednisley** [alexrj/Slic3r#3175]
Version 1.2.9 produces a bridge aligned perpendicular to the two bars of the central link:

![slic3r 1 2 9 - good bridging](https://cloud.githubusercontent.com/assets/599600/11956860/6d99dcb0-a88b-11e5-96e2-e1b49256532e.jpg)

The current development head (7c8b71012c1) produces a diagonal bridge that doesn't anchor properly:

![slic3r 7c8b710 - diagonal bridging](https://cloud.githubusercontent.com/assets/599600/11956903/c1f485d0-a88b-11e5-9fe2-229804b934fd.jpg)

The small links also have diagonal bridges:

![slic3r 7c8b710 - diagonal bridging on links](https://cloud.githubusercontent.com/assets/599600/11956969/457be538-a88c-11e5-864b-76ab9148747e.jpg)

The config and (manifold!) STL file:
[Slic3r bridge regression - 7c8b71012c1.zip](https://github.com/alexrj/Slic3r/files/69769/Slic3r.bridge.regression.-.7c8b71012c1.zip)

This looks similar to the problem described in [#2646](https://github.com/alexrj/Slic3r/issues/2646), which was fixed in 1.2.7. In this case, however, *none* of the links have correct bridges.

Running the 64 bit version of Xubuntu 14.04, with the chain mail model generated by the most recent dev version of OpenSCAD.

**Comment by wolfmanjm** [comment]
I have also noticed that bridge detection is failing in the current versions. even on simple bridges that are detected in the 1.2.9 release

**Comment by clough42** [comment]
I am also having trouble with bridges in 1.2.9.  Attached are two STL files and a config file that generate bridges that terminate or have seams in open space.

These are both real production designs where I had to redesign the part to be able to print it correctly with Slic3r.

[ShroudBridges2.zip](https://github.com/alexrj/Slic3r/files/75851/ShroudBridges2.zip)

Some examples below.  Note the seams in the bridging over open space.

![oddbridging2](https://cloud.githubusercontent.com/assets/3324188/12069746/2ce72d62-b006-11e5-9d99-b4547d893525.PNG)

![oddbridging1](https://cloud.githubusercontent.com/assets/3324188/12069748/3c9aa856-b006-11e5-877c-17d391d4cc21.PNG)

![oddbridging3](https://cloud.githubusercontent.com/assets/3324188/12069750/657bbfda-b006-11e5-89c1-bce30c4c99cb.PNG)

**Comment by clough42** [comment]
Okay...the problem I'm seeing is in 1.2.9, so maybe it's something different.

**Comment by ghuser2** [comment]
How do you design around a floating bridge seam like that? Add a support bar there?

**Comment by clough42** [comment]
I changed the print orientation so bridging want required.  I wanted to print it flat on the bed, using the large base of the post for adhesion, but ended up flipping it so it stands up on the narrow front edges and adding a breakaway plate for adhesion.

**Comment by curiouspl2** [comment]
+1 on this one. 
1.2.9 detects bridge direction ok, but there are many 'terminate and start in free space' bridges.

**Comment by thiagopeixoto16** [comment]
+1 on this, I had the same problem as @clough42

**Comment by chuckmitchell** [comment]
+1

**Comment by Vicious-one** [comment]
https://github.com/alexrj/Slic3r/commit/9fcec107373b6846f3775fe353c7ae29653cf9ac is causing this behavior.

**Comment by a4jp-com** [comment]
Thanks for finding that @Vicious-one. I hope it can get fixed soon along with the overfill problem.

**Comment by alexrj** [comment]
Thank you, I have fixed this and included a regression test.

@clough42, that's a different thing which is caused by the shape of that object. Slic3r is not very good (yet) at dealing with bridges spanning more supports, like in your case. Basically Slic3r tries to handle each segment of the bridge like a separate bridge, but that approach fails because the supports are too thin. Things will improve on that side, eventually. It's not something I can do quickly.
