### ISSUE TITLE
Dual extruder feed rate

### ISSUE THREAD

**Issue by pbrgle1** [alexrj/Slic3r#3178]
I've been having problems with extruder feedrates lately so firstly i re-calibrated the E-Steps with the single extruder. I got a value of about 295 steps/mm (direct drive, 1/32 microstepping). For single extrusion it worked perfectly. Then i printed a dual color business card and the 295 were suddenly far too low. I ramped E-steps up to 410 with M92 and it seemed too work but as soon as the extruders switched it was far too low again. I tried volumetric E and it seems to work with both extruders (at 295). At first i thought it was an issue with marlin and the Dual-X-Carriage feature but volumetric E seems to solve the issue. Any idea what caused the low feed rate in the first place?

**Comment by alexrj** [comment]
Maybe your printer's firmware expects volumetric E by default, so this is the only way for operating it...
