### ISSUE TITLE
Refresh/redrawing bug in Slic3r 1.3.0-dev

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#3179]
![screen shot 12-25-15 at 12 53 am](https://cloud.githubusercontent.com/assets/9621044/11996209/03f6cc32-aaa2-11e5-9acb-88f16d16eac3.JPG)

When I start moving things around in Windows 10 everything gets messy.

**Comment by alexrj** [comment]
Hm, is this fixed as of current master?

**Comment by alexrj** [comment]
@a4jp-com, can you confirm this was fixed as of current master?

**Comment by lordofhyphens** [comment]
Looks fixed to me on my Win10 system. @a4jp-com please confirm, I will close this in the meantime (checked on my local Win10 system from a recent build off of bintray).

**Comment by a4jp-com** [comment]
I'll download the new file, compile it and get back to you in the next 30 minutes .

**Comment by a4jp-com** [comment]
Everything compiled perfectly and this problem was gone ^^
