### ISSUE TITLE
Slic3r 1.2.9 stable 64 bit missing nearly everything under lib/std

### ISSUE THREAD

**Issue by thehans** [alexrj/Slic3r#3183]
I tried to load an AMF file and got this error:

`no element found at line 1, column 1, byte 0 at /home/peeps/apps/Slic3r-1.2.9-stable64/lib/std/Slic3r/Format/AMF.pm line 19`

Comparing the zips from here:  http://dl.slic3r.org/linux/
I found that the x86 version has a ton of files and subdirectories (97 of theml) under lib/std.  
While the 64bit  version has no files and only 2 subdirs: "Mozilla" and "XML"

**Comment by maktub8** [comment]
@thehans Hi bro，have you solved it ?

**Comment by lordofhyphens** [comment]
"No element found" is a generic XML error; there was likely something wrong
with your input file (or Slic3r's handling of it)

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by alexrj** [comment]
@thehans, unless you provide a test AMF file to load we can't reproduce this or take any action.

**Comment by maktub8** [comment]
Maybe, the AMF file is wrong. I proved it. Thanks everybody.

**Comment by alexrj** [comment]
We're working on a new packaging method for Linux, which will fix this anyway.
