### ISSUE TITLE
Changing to Expert mode does change some default settings - causes frustration for newbies like me.

### ISSUE THREAD

**Issue by placydo** [alexrj/Slic3r#3188]
Slic3r version: 1.2.9
Operating system type: W7 x64
Steps to reproduce the issue, including: Download fresh Slic3r, use wizzard to configure, generate gcode, change to expert mode, generate gcode again. View both gcode.
Expected result: Setting should be same in both cases.
Actual result: Settings differ.

When running wizzard in simple mode gcode output is:
; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.48mm
; infill extrusion width = 0.48mm
; solid infill extrusion width = 0.48mm
; top infill extrusion width = 0.48mm

But after switch to Expert mode (no other changes) same model gives gcode:
; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.67mm
; infill extrusion width = 0.67mm
; solid infill extrusion width = 0.67mm
; top infill extrusion width = 0.67mm

To debug this it took me almost two weeks (yes I have spent a lot of time on hardware because over extrusion)...

**Comment by lordofhyphens** [comment]
Closing, Expert mode is now only mode with the GUI changes.
