### ISSUE TITLE
USB connection to Printrun Pronterface from El Capitan

### ISSUE THREAD

**Issue by mariyo66** [alexrj/Slic3r#3194]
Just installed OS X El Capitan 10.11.2 and there is a problem: no USB connection  to Printrun. I've changed to 3Feb2015 version and the problem persist.
When I do the connection it appears tty.usbmodem1A21 port but now the process doesn't run and at the end I have to kill it.
Any idea?
Thanks.
Mario

**Comment by alexrj** [comment]
No, this issue tracker is only about Slic3r. While I love Pronterface, I don't use El Capitain so I can't even help.
