### ISSUE TITLE
[1.2.9 stable] Support Material to close

### ISSUE THREAD

**Issue by samu87** [alexrj/Slic3r#3197]
Hi all, i use slic3r after i had try a lot of slicer before. It's amazing but the Support Material generated are to much close to vertical wall in x and y and it's impossible to clean the printed part from the support. There is a way to put the support far to the vertical wall? A parameter o work around?!

Many thanks!

**Comment by lorenzo-franco** [comment]
I have the same problem. Thanks Samu for this issue!

**Comment by anokiernan** [comment]
I have also recently been struggling with this issue, it would be very helpful to be able to adjust the XY plane support clearance with a parameter.

**Comment by lonelymyp** [comment]
https://github.com/alexrj/Slic3r/issues/2916

**Comment by CodeChief** [comment]
Mee too. We have contact Z distance but no "contact X/Y distance". Please add it!

**Comment by lordofhyphens** [comment]
So long as I can figure out how to cleanly get a config option propagated to the logic, line 531 in lib/Slic3r/Print/SupportMaterial.pm seems to govern the XY separation. 

Specifically, it's for the interface/base layers, and then the rest of the support is drawn down from that. Looks like you could add an extra constant there (would be in mm so far as I can tell) to reduce things. 

Default is the extrusion width, by the way. So you could increase the extrusion width to get better XY gaps.

**Comment by lordofhyphens** [comment]
@samu87 can I close this as it's already covered in #2916 (and related to #1539)?

**Comment by samu87** [comment]
Yes many thanks i follow the other 2 post!

**Comment by lordofhyphens** [comment]
Closing because duplicate issue.
