### ISSUE TITLE
Seem like the gcode generator doesn't generate the same model.

### ISSUE THREAD

**Issue by robertgregor** [alexrj/Slic3r#3214]

**Comment by robertgregor** [comment]
[Keeper1_export.gcode.txt](https://github.com/alexrj/Slic3r/files/98103/Keeper1_export.gcode.txt)
[Keeper1.stl.txt](https://github.com/alexrj/Slic3r/files/98105/Keeper1.stl.txt)

Look to the left corner of the gcode model, it is not the same as stl.

**Comment by lordofhyphens** [comment]
Please include the configuration.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.
