### ISSUE TITLE
[feature request] add option for a filename dialog when sending to Octoprint

### ISSUE THREAD

**Issue by Azlinon** [alexrj/Slic3r#3217]
When I send gcode direct to Octoprint, I don't see a way to specify the filename to use.  Instead, one of the models I added to the plater serves as the filename.  This is a problem because sending a PLA model to a printer loaded with ABS is bad (stripping the filament as a best case?), and then I also don't know what options were used or what's actually in the gcode.  Popping up a dialog box and then using that name would be ideal, IMO.

**Comment by lordofhyphens** [comment]
The filename is currently in the print options and uses variables.

**Comment by pyrophreek** [comment]
Is the filament type a variable? haven't been able to get that to work.  Had to create a print profile for each type of filament to be able to add that manually.  

Have to say I think this is a good idea, and for those who maybe don't want it, add an option to the output section or global preferences to enable/disable.

**Comment by lordofhyphens** [comment]
You can use the filament preset name as a variable.

**Comment by bj0** [comment]
Something like this would be very useful because, as is, if I try a print and then change a setting (like creating multiple copies of an object) and resend, octoprint's old copy gets overwritten.

**Comment by alexrj** [comment]
Done! Slic3r now prompts with the filename and asks whether to start printing.

**Comment by Azlinon** [comment]
Awesome!  Thank you.

On December 17, 2016 3:25:05 PM EST, Alessandro Ranellucci <notifications@github.com> wrote:
>Done! Slic3r now prompts with the filename and asks whether to start
>printing.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/alexrj/Slic3r/issues/3217#issuecomment-267784717

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
