### ISSUE TITLE
Slic3r fills area that should be empty space

### ISSUE THREAD

**Issue by justbuchanan** [alexrj/Slic3r#3221]
I'm not entirely sure what the issue is, but for a particular item I tried to slice and print, slic3r seems to have filled areas that should be empty, then left the solid parts unfilled.  Almost looks like it's filling the negative of what it's supposed to.  Here's a screenshot of the item in Repetier Host:
![screen shot 2016-01-26 at 4 12 21 pm](https://cloud.githubusercontent.com/assets/115131/12595449/5ccc5a1e-c449-11e5-80b7-4606e128b6cd.png)

And a screenshot of the "rendered gcode" after running slic3r:
![screen shot 2016-01-26 at 4 12 08 pm](https://cloud.githubusercontent.com/assets/115131/12595467/6b5b26b4-c449-11e5-8610-b1b06b552cc5.png)

The `stl` part file can be found on thingiverse [here](http://www.thingiverse.com/download:1045227).

Please let me know if there is anything I can do to help debug this further.  Thanks for the excellent software!

**Comment by lordofhyphens** [comment]
First note - Rephost has no clue what the width of the filament should be.
Any "screenshots" of the path should use slic3r's own preview (which does
know).

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by justbuchanan** [comment]
Thanks for the quick reply!

Here's a preview of the part in slic3r:
![screen shot 2016-01-26 at 4 55 43 pm](https://cloud.githubusercontent.com/assets/115131/12596421/d3b4a72c-c44d-11e5-88b0-8661d4db9642.png)

And here's a screenshot of the layer's tab showing that slic3r is filling in the area that should be blank.
![screen shot 2016-01-26 at 4 56 16 pm](https://cloud.githubusercontent.com/assets/115131/12596436/eb3e858e-c44d-11e5-942f-da90ae068590.png)

It's possible that this is a problem with the stl file itself.  I'm not sure what it would be though because it looks fine in the viewer.

**Comment by justmyopinion** [comment]
Your model is is not MANIFOLD. 
SLIC3R is reporting Auto repair of 23671 errors!
You cannot expect to get deasant result out of that. Thingiverse is not a good place to find quality models.. Check and repair STL file with Netfabb before slicing

**Comment by justbuchanan** [comment]
Thanks for the info!  I figured it was probably the model file since slic3r has done a great job with many other stl files I've tried.  I didnt' notice the manifold errors before, but that explains a lot.
