### ISSUE TITLE
"3D Tab" Works well, "Preview Tab" and "Layers Tab" doesn't works well

### ISSUE THREAD

**Issue by mpp2user** [alexrj/Slic3r#3224]
Hi,
I try to expose my problem:
1 - to load .stl file (see attached)
2 - select "3D Tab" :  works perfectly (see attached)
3 - select "2D Tab" :  works perfectly (see attached)
4 - select "Preview Tab" : the top part is not displayed (see attached)
5 - select "Layers Tab" and slide it : the top part is not displayed

the stl file should be ok ("Cura" works perfectly)

thanks in advance for your response
[Problem.zip](https://github.com/alexrj/Slic3r/files/108504/Problem.zip)

![2d](https://cloud.githubusercontent.com/assets/31754/24416626/03bd9070-13ab-11e7-9e3b-5ea19a37db48.png)
![3d](https://cloud.githubusercontent.com/assets/31754/24416628/04cb3c7e-13ab-11e7-941b-0450aedc4f15.png)
![preview](https://cloud.githubusercontent.com/assets/31754/24416630/0609341a-13ab-11e7-984e-9b9b3dfb0525.png)

**Comment by SFS87** [comment]
I'm having the same exact problem. I'm running Windows 10 with the latest version 1.2.9 and cannot see the slicing paths.

**Comment by bubnikv** [comment]
Yeah, my Slic3r 1.3.0-dev hangs on the 3D preview.

**Comment by lordofhyphens** [comment]
The provided STL has multiple parts in it. 

The model on the 3d preview does not look right to me: 
![image](https://cloud.githubusercontent.com/assets/31754/24416337/11a0ec42-13aa-11e7-8fcd-cc53f9904663.png)

Here's the model after a split operation:
![image](https://cloud.githubusercontent.com/assets/31754/24416380/3140a588-13aa-11e7-9186-2d53fffe67b1.png)

**Comment by lordofhyphens** [comment]
![image](https://cloud.githubusercontent.com/assets/31754/24416475/8c1dd46c-13aa-11e7-8726-a5324c240a86.png)

This is the 3d model after it got passed through service.netfabb.com

And here's the 3d preview.
![image](https://cloud.githubusercontent.com/assets/31754/24416526/ac96845a-13aa-11e7-8bb7-4ba1e410121c.png)

It looked like there were multiple intersecting shells. So each piece was manifold.

**Comment by lordofhyphens** [comment]
1.3.0-dev doesn't hang anymore though.

**Comment by xoan** [comment]
Even model is manifold, it has normal orientation issues.

![snapshot00](https://cloud.githubusercontent.com/assets/288246/24416801/406110d4-13e6-11e7-9a01-6decd372b2ad.png)

All darkgray faces are inverted.

**Comment by lordofhyphens** [comment]
Fixed model: https://service.netfabb.com/upload/download.php/Object_fixed.stl?job=3bfdab7213d411e7b4115254a20161ba
