### ISSUE TITLE
Feature Request - home between layers

### ISSUE THREAD

**Issue by blacktigersoftware** [alexrj/Slic3r#3226]
Would be nice if the gcode would generate  movement to a known position (home?) between layers.  This would help for external efforts like time-lapse recording.  We can record a still image on layer change (Octoprint), but there is no way to know where the head might be, at that time.  Specifically, 
1) move to a known location after the layer is complete but before the 'z' movement.
2) perform the 'z' movement
3) continue

**Comment by lordofhyphens** [comment]
Use the before or after gcode section.

**Comment by blacktigersoftware** [comment]
:) Good idea......
