### ISSUE TITLE
Re-arranging objects doesn't recalculate

### ISSUE THREAD

**Issue by smurfix** [alexrj/Slic3r#3246]
I have two large irregular objects which I want to move (partly) on top of each other so that I can save on support material. Unfortunately Slicr3r doesn't care and will happily print support material from A and the actual object B in the same place.

**Comment by lordofhyphens** [comment]
Yeah, the support material is considered per model.

**Comment by lordofhyphens** [comment]
I don't really know what we can do about this in terms of software. The auto-arrange is designed to place things far enough apart so this can't happen. If you saved the plate as one big STL and re-loaded it, your support probably would work as intended (as both STLs would be considered together).

**Comment by mrvn** [comment]
This would be solved by issue #3266. Merge the objects and you get support for both of them combined.

**Comment by alexrj** [comment]
Yes, @mrvn wrote the solution and @lordofhyphens the workaround.
