### ISSUE TITLE
Dangerous RAM increase when the default width extrusion is less than 21%

### ISSUE THREAD

**Issue by unconexo** [alexrj/Slic3r#3253]
RAM increase when the default width extrusion is less than 24%. With 23% and 22% slic3r takes some time, but with 21% using up much ram and when it reaches the 90% usage of RAM, the PC freezes.

![20160218060820](https://cloud.githubusercontent.com/assets/17484810/13338647/13e0bbe6-dc23-11e5-8f43-3c189efb1049.jpg)

If you let it continue to grow, windows dies (BSOD).
![photo_2016-02-26_00-51-03](https://cloud.githubusercontent.com/assets/17484810/13338646/0fa8f93a-dc23-11e5-80ab-427a5f57cee6.jpg)

The version is 1.2.9
Windows 10.

I do not know if it is a known bug and my google translator is not very good.
But congratulations on the job! 
Thanks.

**Comment by lordofhyphens** [comment]
Need a copy of the rest of your configuration and a model in which this
happens, as mentioned in the contribution guidelines.

FYI the width is relative to the layer height when expressed in %. You
don't want to have it that low to start with.

**Comment by unconexo** [comment]
True, I do not want such a low value, but I'm beginner and testing configurations that happen.
For someone else may happen and you go crazy looking for the cause.

[21 percentage extrusion with and Cube_stl.zip](https://github.com/alexrj/Slic3r/files/148335/21.percentage.extrusion.with.and.Cube_stl.zip)

If it really is not a bug, I just tried to report something that I thought would be useful. ^^

**Comment by alexrj** [comment]
What is your layer height? Supposing it's 0.3mm, you're telling Slic3r to produce extrusions whose width is 0.06mm. Being so thin, you need a lot of toolpaths and your G-code file will be huge. So you also need a computer with a lot of RAM for processing this hard job, and this is not a bug.

However, a 0.06mm extrusion width is crazily small and not possible. Slic3r should definitely warn the user telling they're doing a very wrong thing.
