### ISSUE TITLE
V 1.2.9 Negative coordinates at bed shape

### ISSUE THREAD

**Issue by UlliBien** [alexrj/Slic3r#3254]
Entering a minus sign in an empty fiels causes a crash. Entering a minus sign in front of an existing number works fine.

Negative coodinates are not diplayed. When opening the bed shape configuration dialog always positve values appear. But negative values seem to be stored correctly.

Size x: -200, y: -150
Origin x: -100, y: -75
=>
printer.ini
bed_shape = 100x75,-100x75,-100x-75,100x-75

=> Reopen the dialog:

Size x: 200, y: 150
Origin x: 100, y: 75

**Comment by lordofhyphens** [comment]
Yeah, pretty sure it is because it tries to use the value immediately and
just a - is not a number.

**Comment by lordofhyphens** [comment]
Also, why are you trying to use - sizes for the bed? That makes no sense whatsoever. - Origins are legal and work on my Linux build of current -dev, so does just putting a - in the field (no crash)

What OS are you using?

**Comment by alexrj** [comment]
Fixed, thank you.
