### ISSUE TITLE
Object settings used in parts/modifiers should also be usable at z heights like layers tab

### ISSUE THREAD

**Issue by KriLL3** [alexrj/Slic3r#3259]
There are a lot of uses for this, would allow you to print one of those temperature tests where you gradually change the temperature of a printed shape, would allow you to override the infill % for specific z heights which is needed frequently in order to get solid tops of non-flat topped figures etc etc, currently only way to do this is to slice your model up into separate sections and then re-assemble in slic3r's settings dialog, a very cumbersome workflow compared to just defining starting and ending z ranges to apply changes.

**Comment by alexrj** [comment]
We now have a handy "Create modifier" button to create modifiers on the fly and achieve the result you described.

**Comment by lordofhyphens** [comment]
Define a "slab" type mesh.
