### ISSUE TITLE
[feature request] autocool priority or exclude from autocool 

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#3273]
autocool is very cool feature, but it causes external perimeter speed to vary.
this causes uneven finish of prints.

it would be nice if external perimeters could be excluded from autocool, and printed at their nominal speed each time. 
perhaps another 'last resort' or 2nd pass could be added to slow down external perimeters when lowest autocool speed was reached on other features, so priority could be set this way.

**Comment by alexrj** [comment]
Duplicate of #2796
