### ISSUE TITLE
stable broken by last commit

### ISSUE THREAD

**Issue by vuokko** [alexrj/Slic3r#3276]
Commit 3d4b9b024a7d511ddfa4df3bdc0bdb30f87bed80 added line:
line 276: use XXX; ZZZ $bw if !$bw;

`
./slic3r.pl --gui
Can't locate XXX.pm in @INC (you may need to install the XXX module) (@INC contains: /tmp/packerbuild-1000/slic3r-git/slic3r-git/src/Slic3r/lib /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /tmp/packerbuild-1000/slic3r-git/slic3r-git/src/Slic3r/lib/Slic3r/GUI/BedShapeDialog.pm line 276.
BEGIN failed--compilation aborted at /tmp/packerbuild-1000/slic3r-git/slic3r-git/src/Slic3r/lib/Slic3r/GUI/BedShapeDialog.pm line 276.
Compilation failed in require at /tmp/packerbuild-1000/slic3r-git/slic3r-git/src/Slic3r/lib/Slic3r/GUI.pm line 9.
BEGIN failed--compilation aborted at /tmp/packerbuild-1000/slic3r-git/slic3r-git/src/Slic3r/lib/Slic3r/GUI.pm line 9.
Compilation failed in require at (eval 65) line 1.
`
Breaks Arch linux AUR slic3r-git package at least.

**Comment by alexrj** [comment]
Fixed, thank you.
