### ISSUE TITLE
Build failed on master branch 

### ISSUE THREAD

**Issue by wolfmanjm** [alexrj/Slic3r#3277]
src/libslic3r/PerimeterGenerator.cpp:481:53: error: ‘assert’ was not declared in this scope
                     assert(pp.size() == segments + 1);
                                                     ^
error building src/libslic3r/PerimeterGenerator.o from 'src/libslic3r/PerimeterGenerator.cpp' at /usr/share/perl/5.18/ExtUtils/CBuilder/Base.pm line 177.

**Comment by alexrj** [comment]
Fixed.
