### ISSUE TITLE
[1.3.0-dev] Perimeters laid in mid-air

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#3279]
[floating_perimeters.zip](https://github.com/alexrj/Slic3r/files/181060/floating_perimeters.zip)
as of commit dfb1ec99ac2699840e0dbe40163fade9df3e966b

If you fix Infill, Perimeters, and External perimeters width to 0.6, you start seeing strange artifacts around the same point in the model, like there's perimeters being generated that are too small to render properly.

![visual_problem](https://cloud.githubusercontent.com/assets/31754/13902133/506e007a-ee0a-11e5-91b8-b0ea01239787.png)

**Comment by lordofhyphens** [comment]
It's commit dfb1ec99ac2699840e0dbe40163fade9df3e966b that is causing the behavior, as reverting it fixes the behavior.

**Comment by alexrj** [comment]
I'm not sure I can see the actual problem in your screenshot, but could you test as of current master? I pushed many fixes.

**Comment by alexrj** [comment]
@lordofhyphens, can you confirm this is fixed?

**Comment by lordofhyphens** [comment]
Unfortunately it's not.
Here's the same area at 3 different heights:

This is the last area touched by infill.
![image](https://cloud.githubusercontent.com/assets/31754/23977529/ba4fa5ec-09bc-11e7-8051-f1c7454eff05.png)


As can be seen, several perimeters (but no infill) get built up here on the intervening layers for a full mm.
![image](https://cloud.githubusercontent.com/assets/31754/23977515/a9ec3daa-09bc-11e7-94a0-3cbe8c3bcf96.png)

The perimeter now appears between the two perimeters that had been laid up is floating in the air.
![image](https://cloud.githubusercontent.com/assets/31754/23977500/9a04beee-09bc-11e7-8b40-290b177deee6.png)

A closer look.
![image](https://cloud.githubusercontent.com/assets/31754/23977648/42c1f2f4-09bd-11e7-9896-6c8085888fd2.png)

**Comment by lordofhyphens** [comment]
I found a second shell in the provided test case, a single ring. It looks like it is the confounding agent here--the gap is being formed because Slic3r is somehow interpreting the second shell (a ring) in a weird way. If you turn on support, Slic3r tries to generate supports in the gap. 

Splitting the model eliminates the symptoms. I'm not sure where to put this on the bug hierarchy, as I don't recall putting that ring in there when I SCAD'ed up the model. 

Up to you how you want to handle it w/r/t tagging not a bug, as the model is showing as manifold.

**Comment by alexrj** [comment]
Actually, the model is manifold, and Slic3r _is_ doing the right thing!

It's not just two nested shells (in which case they would be considered as a single solid): the outer shell has a hole/void, and the inner shell is inside that void. So they are actually two nested and non-overlapping *solids*. The object is modeled as if you wanted a circular tunnel inside the object, and that's what Slic3r is doing.

 I'm attaching some more screenshots showing the situation:

![schermata 2017-03-27 alle 00 39 56](https://cloud.githubusercontent.com/assets/594957/24335919/6ad8f522-1286-11e7-942f-d51fe4136c0c.png)
![schermata 2017-03-27 alle 00 38 55](https://cloud.githubusercontent.com/assets/594957/24335920/6adf7906-1286-11e7-8a76-e2a1650af37c.png)
![schermata 2017-03-27 alle 00 38 47](https://cloud.githubusercontent.com/assets/594957/24335918/6ad61e92-1286-11e7-8627-cb7a748a2827.png)
