### ISSUE TITLE
Volumetric E support question.

### ISSUE THREAD

**Issue by pbrgle1** [alexrj/Slic3r#3319]
Hi. I need some explanation of how volumetric e works and how to set the diameter.
Is it enough setting the diameter in the filament tab or do i also need M200 Dxxx Tx in start gcode?
Which one? Or both?
I use Marlin RC5 and the latest slic3r on windows 10.

**Comment by lordofhyphens** [comment]
Marlin only understands gcode, so M200 D[filament_diameter_0] (use whatever
shows up in the saved filament profile as the variable name) in your start
gcode is required if you want to set that at the start of every print.

I *think* M200 gets saved to EEPROM on Marlin though, so you could also
hand-set it if your filament diameter isn't changing from roll to roll.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
Going to close this.
