### ISSUE TITLE
Solid infill is not quite solid

### ISSUE THREAD

**Issue by VanessaE** [alexrj/Slic3r#3322]
### Version
git commit 510ca9f9e2f0e550ee3733510f7738e6ca0128aa with LoH's debian patch

### Operating system type + version
Debian 8.2

### Behavior
The title actually says it all - solid infill is not being printed as solid anymore.  I'm using regular rectilinear infill for solid layers, and what is' printing is still the usual rectilinear pattern, but there are visible gaps between the lines.  Seems to be only about 60 or 70 percent as dense as it ought to be.

#### STL/Config (.ZIP) where problem occurs
[fan-shroud-squirrel-cage-dual-5015-parts.zip](https://github.com/alexrj/Slic3r/files/256704/fan-shroud-squirrel-cage-dual-5015-parts.zip)
[fan-shroud-squirrel-cage-dual-5015-parts.gcode.zip](https://github.com/alexrj/Slic3r/files/256705/fan-shroud-squirrel-cage-dual-5015-parts.gcode.zip)
[Prusa i3 - Slic3r 1.3.0-dev config bundle.ini.zip](https://github.com/alexrj/Slic3r/files/256708/Prusa.i3.-.Slic3r.1.3.0-dev.config.bundle.ini.zip)

Here's what the effect looks like, a few layers in:
![20160510_044449a](https://cloud.githubusercontent.com/assets/1733537/15140707/639f9efa-166a-11e6-9760-9f686042cb73.jpg)

That same STL, finished (you can see that the lines are thicker here, but there are still gaps):
![20160510_043152a](https://cloud.githubusercontent.com/assets/1733537/15140715/68571e78-166a-11e6-804a-2dafd7441693.jpg)

**Comment by Mikk36** [comment]
This looks like a machine configuration issue.
Try printing a lot slower and see if it helps.
Also set the default extrusion width to the same as nozzle diameter. This will help you diagnose your issues better.

**Comment by VanessaE** [comment]
I might have suspected that, if not for the fact that this machine's quite well-calibrated and has been for a while now.

In any case, I recall reading somewhere that one should set the print width at 25% over the nozzle diameter, or larger, so 0.5mm for my 0.4mm nozzle.  Setting all of the "advanced" size settings to that value does not help.

**Comment by xoan** [comment]
If the preview tab shows the desired result and later, it isn't the same in the printed part, it is a hardware problem.

We all need to understand that Slic3r is not intended as a workaround for all of the machine related problems, so this problems should be fixed first at the hardware level.

**Comment by VanessaE** [comment]
Actually, looks like you guys were right, it was a hardware failure.  *sigh*

**Comment by Mikk36** [comment]
That 25% over the nozzle diameter is a bit of a myth to be honest. Cura (and Ultimaker in that sense) have been doing just fine with all extrusions always being the same width as the nozzle diameter.

**Comment by lordofhyphens** [comment]
@Mikk36 Slic3r defaults external perimeters to the nozzle width in a lot of cases. 

The reasoning is that wider traces give better fusion for the most part (2.2 seems to be the "magic" ratio that was bandied about).

**Comment by Mikk36** [comment]
Only if you print with high enough heat. If you're just about getting good bonding with the outer perimeters, then you might get a lot worse bonding with the fatter traces.
