### ISSUE TITLE
Meeting at Maker Faire Bay Area?

### ISSUE THREAD

**Issue by alexrj** [alexrj/Slic3r#3328]
Sorry for abusing the issue tracker with an off-topic thing. :-)

I'll be at Maker Faire Bay Area. If any of you is around there, let's meet and have a Slic3r beer.

**Comment by lordofhyphens** [comment]
Wrong area of the country for me. The closest convention to me is Midwest Reprap Festival, or MRRF.

**Comment by lordofhyphens** [comment]
Closing, as the event has passed. Hope it was fun.
