### ISSUE TITLE
Per-object slicing settings

### ISSUE THREAD

**Issue by sdaitzman** [alexrj/Slic3r#3335]
Is there any way to slice multiple objects to be printed simultaneously with different settings per object? Thanks!!

CC @Louieadamian

**Comment by lordofhyphens** [comment]
Yes, right click on the object in the plater and select settings
There is not a way to assign profiles to individual objects; interface is
designed for overriding a few things.

**Comment by LouieAdamian** [comment]
Is there a Command line way to do it?

**Comment by lordofhyphens** [comment]
@LouieAdamian I don't know; I don't use the command line myself.

**Comment by h3rb** [comment]
No there is no way.  This feature (as well as related features of being able to slice REGIONS of the same model with different settings, not just LAYERS, and also LAYERS) should be supported on command line.  It was first requested 5 years ago as far as my research has shown.

**Comment by lordofhyphens** [comment]
Help work out an interface for it and it will be closer to being done.

**Comment by lordofhyphens** [comment]
As this was a question and said question was answered, closing. Please open a new issue if you have a feature request; going to lock this topic.

@h3rb modifier meshes combined with simple SCAD or JSCAD setups (which are in the utils directory now) cover most of the "change settings whenever you feel like it, regardless of whether or not it's a good idea" cases. I've been looking into making support respect modifier meshes but that's probably going to be very fiddly.
