### ISSUE TITLE
Ooze prevention crash

### ISSUE THREAD

**Issue by VanessaE** [alexrj/Slic3r#3352]
### Version

Slic3r git commit 9e8022f6f62b6f4c07b5846a765128b3609e53ef
### Operating system type + version

Linux (Debian)
### Behavior

Slic3r crashes when a large enough model is loaded and then exported to G-code, if multiple-extruder ooze prevention is turned on (Print Settings -> Multiple Extruders).

Watching the status at the bottom of the window, it goes through these steps, in order (I have background processing disabled):
- processing triangulated mesh
- generating perimeters
- processing triangulated mesh (again)
- generating perimeters (again)
- preparing infill
- infilling layers
- preparing infill (again)
- infilling laters (again)
- generating support material
- generating skirt

... and then it crashes before it starts writing the g-code file.  Smaller models such as the popular dual extruder calibration squares object on Thingiverse (http://www.thingiverse.com/thing:124450) make it all the way through the process and save out a working g-code file.

Output on the console at the time of the crash:

`Can't call method "print_z" on an undefined value at /home/vanessa/RepRap/Slic3r-git/lib/Slic3r/GUI/3DScene.pm line 1104.`

I don't know enough perl to fix this, but I was able to insert a few print statements and found that the loop surrounding that line dies at layer 218, which is the highest point of the color transition in my model (below), when using 0.2mm layers.  The two parts of the model deliberately overlap slightly (by maybe 0.1mm) to ensure that color change occurs without any gaps.

I tried adding a tall object (scaled-up cube) to the plate, set for extruder 1 to make sure that that extruder is used throughout the entire print, but that didn't help.

Moving the two parts of the model away from one another to eliminate the overlap does not help, but deleting either part and leaving the other behind allows the program to finish slicing.

Manually setting the skirt height to a very large value (99999) didn't help, nor did adding a brim (5mm),  increasing the number of skirt loops (8), setting the minimum skirt extrusion length to 0 (normally I have it at 10), or all of these together.  Enabling interface shells didn't help, either.

I should also point out that in the case of that small test object where Slic3r made it all the way through, only the first extruder was being used to draw the ooze prevention skirt after the first layer, and only as many loops as were needed for just the one extruder, even though Slic3r's preview shows otherwise (Pronterface agrees with the output from the printer, though).  See also, issues #1869 and #2523.
#### STL/Config (.ZIP) where problem occurs

Config bundle:  [Prusa i3 - Slic3r 1.3.0-dev config bundle.ini.zip](https://github.com/alexrj/Slic3r/files/295715/Prusa.i3.-.Slic3r.1.3.0-dev.config.bundle.ini.zip)
Use "Dual Material (two colors)..." for print settings, and "Dual extruder, increased retract" for printer settings.  I suppose any filament will do, I was using my red and orange Inland PLA profiles.
Model (AMF): [aleph-2-color.zip](https://github.com/alexrj/Slic3r/files/295720/aleph-2-color.zip)

**Comment by alexrj** [comment]
Thank you for the report. I think this was fixed.
@VanessaE, do you have a chance to test again?

**Comment by VanessaE** [comment]
I'm afraid I do not, as I've returned my machine back to a single nozzle configuration.

**Comment by alexrj** [comment]
Okay, closing then :)
