### ISSUE TITLE
 "zick-zack" line on perimeter infill!?

### ISSUE THREAD

**Issue by Hecot** [alexrj/Slic3r#3370]
Usually I have a lot off thin walls in my prints. When I choose 3 perimeters on the outside and the wall is thinner to let 3 perimeters fit in the inner perimeter will be replaced by a small "zick-zack" line:

![zick zack](https://cloud.githubusercontent.com/assets/11699283/16209951/d3c1e2de-3739-11e6-86df-23b46e9c2759.JPG)

But when this "zick-zack" line is printed my printer **always** over extrude and leave a big hump in this area!!! Usually the nozzle will jam into this hump of plastics on the next layer and mess the print by smearing the overextruded plastics to the sides.

I found that these perimeter infills can not be controlled by the "infill" tab so I ask myself how to control this "zick-zack" lines!? Perfect would be a separete extrusion multiplyer or "density" adjustment for these ... or at least a way to switch this automatic replacement off!?

**Comment by lordofhyphens** [comment]
Please provide a STL and config.ini where you are seeing this problem, and provide a screenshot from Slic3r's 3d preview, not repetierhost.

**Comment by lordofhyphens** [comment]
Also, try 1.3.0-dev (there's a build available www.prusa3d.com/downloads/dev/slic3r )

**Comment by bubnikv** [comment]
Where does it over extrude? Over the full layer, or just where the infill lines flip their direction?
You may try to set the infill line width explicitely to the same value as the nozzle diameter. Slic3r by default uses a much wider line width for the infill than for the perimeter, which may cause problems with some extruders I suppose, if the nozzle does not iron out the material sufficiently flat.

**Comment by Hecot** [comment]
Here are the information - when you look at the height of 19.80 mm you can see that there is only 2 Perimeters and not three as in the lower part. 

![zick-zack_slic3r](https://cloud.githubusercontent.com/assets/11699283/16241530/61722b3e-37ee-11e6-9bb0-84d7fef054ad.png)

These small "zick-zack" infills causing trouble as there is too much plastics extruded in this area, unfortunatly I have no print but to show you the problem.

[zick-zack.zip](https://github.com/alexrj/Slic3r/files/326313/zick-zack.zip)

**Comment by Hecot** [comment]
I found when I switch on "gap-fill" (was set to zero) the "zick-zack" infill lines are disappearing and will be replaced by a solid line! 

![zick-zack_slic3r_gf](https://cloud.githubusercontent.com/assets/11699283/16243092/f118b422-37f5-11e6-98e0-cdc75b0f719f.png)

OK - this solved my problem but I still don't understand the logic that the gap will now be filled with infill. To me it would be more logical if there will be a gap as that is what I expect from switching gap-fill off! Maybe someone can think about this logic and change in future version - I close the issue!

**Comment by lordofhyphens** [comment]
What your screenshot looked like to me was exactly how it was supposed to.
That your printer wasn't able to produce that isn't Slic3r's fault.

I would make sure your printer is not overextruding just in case.
