### ISSUE TITLE
Bad bridging direction in git master

### ISSUE THREAD

**Issue by thaytan** [alexrj/Slic3r#3388]
git master - commit #cb7296 (1.2.9-266-g259eb99)
on Fedora 24

I'm slicing a piece, and slic3r is picking the longest bridging direction. In 1.2.9, it bridged orthogonally to that, picking the shortest direction. Actually, in 1.2.9 the bridging direction depends somewhat on part orientation on the bed - rotating the part produces incorrect bridging. In git master, it's incorrect in any orientation I tried.

The full model is quite big (22MB zipped), but I can upload if wanted. I made a cut down version around the problem area, and it behaves slightly different in that the bridging direction is now also wrong in 1.2.9 in any orientation, which is interesting.

**Comment by thaytan** [comment]
github is refusing to upload any of my files to this bug - I'll try again later.

**Comment by lordofhyphens** [comment]
:(
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/
Might be case-sensitive on the extension.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by thaytan** [comment]
![bridging-top-trimmed-git-master](https://cloud.githubusercontent.com/assets/74973/16514936/4a6b4760-3fb2-11e6-8f14-c8ee9b7e2777.jpg)
![bridging-top-full-1 2 9](https://cloud.githubusercontent.com/assets/74973/16514956/66c68672-3fb2-11e6-8bb4-90f561fd5ad4.jpg)

There's the images. It's still refusing to let me attach my zip file with config and STL, so find it here: http://noraisin.net/down/top-trimmed.zip

**Comment by thaytan** [comment]
I implemented a new method of choosing bridging angles. It gives some surprising results - small variations in the 'optimal angle' depend on nozzle diameter / extrusion width, but otherwise seems fairly stable, and chooses good directions. Part orientation can sometimes affect the result slightly, but only small changes in angle that are within the 'noise' based on slic3r coordinates resolution.

**Comment by Lenbok** [comment]
How does your new method do on the case that nophead discussed in  http://hydraraptor.blogspot.co.nz/2016/01/a-bridge-too-far.html

**Comment by thaytan** [comment]
It does the same as unmodified git - aligns the bridging "optimally" perpendicularly across the gap, but I notice that if I add more perimeters, then both git and my direction metric produce the same output, bridging at 45 degrees with nothing underneath. 
![screenshot from 2016-07-31 19-10-33](https://cloud.githubusercontent.com/assets/74973/17275648/7b7b2b10-5752-11e6-92a8-8a1b2ab65113.png)

It's not surprising that both git master and my direction metric have the same problem though  - I didn't change anything about logic that's supposed to reject invalid candidate directions.

**Comment by thaytan** [comment]
Here it is with only 1 perimeter:
![screenshot from 2016-07-31 19-14-40](https://cloud.githubusercontent.com/assets/74973/17275671/0fb5e568-5753-11e6-9471-2f1bcf1fbf4b.png)

**Comment by alexrj** [comment]
This was fixed in 1.3.0-dev. Get it at http://dl.slic3r.org/dev/
Thank you for the report! Screenshot follows:

![schermata 2017-05-16 alle 23 35 09](https://cloud.githubusercontent.com/assets/594957/26129415/669aa320-3a90-11e7-984a-9bb991b69d48.png)

**Comment by thaytan** [comment]
Great! Confirming - the new bridging calculation works much better.
