### ISSUE TITLE
Bridge issues

### ISSUE THREAD

**Issue by JuTakata** [alexrj/Slic3r#3393]
### Version

1.2.9
### Operating system type + version

Windows 7
### Behavior

Hi,

I am not sure if this is due to my configuration or if this is a bug but I when I try to slice the ozzebane_test calibration I get gaps on my print beetween top solid infill and "towers perimeters".

This problem appear when I use 0% infill as you can see on the attached screenshots there is no infill under tower perimeters and the 45° bridge/top solid infill. 
This bridge should not be perpendicular to the part instead of 45°? It seems like if there was no bridge but only solid infill.

First layer that should be bridge :
![bridge](https://cloud.githubusercontent.com/assets/20264907/16544898/b7e169cc-4116-11e6-9b40-2df626a44962.PNG)
First tower perimeters :
![perimeters](https://cloud.githubusercontent.com/assets/20264907/16544897/b7e083cc-4116-11e6-9bc6-a88797b555b4.PNG)

With 5% infill the bridge is also printed at 45° but there is a top solid infill under tower perimeters and then there is no problems :

![bridge_5 infill](https://cloud.githubusercontent.com/assets/20264907/16544923/be099d1e-4117-11e6-8c9c-4557163d6549.PNG)
![perimeters_5 infill](https://cloud.githubusercontent.com/assets/20264907/16544924/be09efa8-4117-11e6-920a-d70210ebf0da.PNG)

Thank you for helping me to understand if this is a configuration issue or a bug.
#### STL/Config (.ZIP) where problem occurs

[Slic3r issues.zip](https://github.com/alexrj/Slic3r/files/344976/Slic3r.issues.zip)

PS : Sorry for my not perfect English, if something is not clear please feel free to ask for details

**Comment by lordofhyphens** [comment]
No infill, no bridging infill, so far as I can tell.

**Comment by alexrj** [comment]
@JuTakata, you need infill for that. There are no anchors for a bridge. That object can't be printed at 0%.
