### ISSUE TITLE
Perl Post-processing scripts not working (Windows 8.1 / Perl Strawberry)

### ISSUE THREAD

**Issue by makertum** [alexrj/Slic3r#3414]
### Version

tested from 1.2.9 stable down to 1.2.4b
### Operating system type + version

Windows 8.1
### Behavior
- G-code export gets stuck at "running post-processing scripts"
- No post-processed file is not written
- Also no original g-code file is written
- Shell scripts (`#!bin/sh`) don't cause Slic3r to get stuck though
- Perl scripts can be executed manually, although not via Slic3r
  - to clarify that: `perl filament-weight.pl somegcodefile.gcode` works just fine
  - while Slic3r -- supposedly doing the same thing -- doesn't
- How to reproduce
  - Have Windows 8.1
  - install Perl Strawberry 5.24.0.1
    - install from archive to C:\Strawberry
    - run relocate script
    - set user path vars via script (`;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin`)
    - set system path vars manually (`;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin`)
  - enter absolute path to any of the example .pl scripts from the repository in Slic3r, no quotes
    ![bildschirmfoto 2016-07-12 um 13 17 42](https://cloud.githubusercontent.com/assets/5277180/16765216/16263616-4833-11e6-9ccd-a1e4c841fadb.png)
  - add `$^I = '.bak';` before the `while(<>)` loop or not, doesn't matter
- Expect it to work, just like on OSX or Linux, with the post-processed G-code file being written
- But doesn't: Slic3r is stuck at "running post-processing scripts" in the status bar, no file is written at all
- Slic3r does not crash, it just doesn't finish the post-processing
- It does not even write the original gcode file, which could also be the actual problem here
- However, if no post-processing script is specified, a gcode file is written
- The following image shows where Slic3r get's stuck, it just stays like this:

![bildschirmfoto 2016-07-12 um 13 16 21](https://cloud.githubusercontent.com/assets/5277180/16765217/162725a8-4833-11e6-841b-4bf51d878938.png)
#### STL/Config (.ZIP) where problem occurs
- Default settings

**Comment by alexrj** [comment]
@makertum, this should be fixed as of 1.3.0-dev. Get a fresh build at http://dl.slic3r.org/dev/ and feel free to reopen if you find the issue again.
