### ISSUE TITLE
Bridges generated in two sections.

### ISSUE THREAD

**Issue by ioquatix** [alexrj/Slic3r#3418]
### Version
1.2.9

### Operating system type + version
Arch Linux latest.

### Behavior
Slicing bridges over enclosed area results in multiple areas which fail to connect.

See the attached .STL file and generated gcode.

**Comment by ioquatix** [comment]
Previous layer:

![screenshot from 2016-07-13 17-34-05](https://cloud.githubusercontent.com/assets/30030/16792796/1b03298a-4920-11e6-98a0-68b21c6135a9.png)

Layer on top, it's not bridging correctly from outside to inside.

![screenshot from 2016-07-13 17-32-59](https://cloud.githubusercontent.com/assets/30030/16792804/27ea5bb4-4920-11e6-85aa-7fb3fdb17cf3.png)

**Comment by ioquatix** [comment]
Here are the STL, Gcode and Slic3r configuration.

[Issue 3418.tar.gz](https://github.com/alexrj/Slic3r/files/360767/Issue.3418.tar.gz)

**Comment by lordofhyphens** [comment]
Is this  also present in 1.3.0-dev?

**Comment by ioquatix** [comment]
@lordofhyphens I will see if I can test.. but to answer your question right now.. not sure.

**Comment by lordofhyphens** [comment]
The gcode file you provided wasn't sliced with the same profile you included in the export bundle, btw. I don't know yet if that matters ^^;

**Comment by lordofhyphens** [comment]
Also, what layers were in your screenshot?

Here's Z=5.15 sliced with your profile on 1.3.0-dev. It looks alright to my eyes. 
![z 5 15](https://cloud.githubusercontent.com/assets/31754/16792945/cb760dc0-4892-11e6-98c3-182eea8d3cd3.png)

**Comment by ioquatix** [comment]
@lordofhyphens that's weird, I sliced it and exported the config at the same time.. odd. Your screenshot looks good.. better than what I'm generating.. Just compiling 1.3.0 now

**Comment by lordofhyphens** [comment]
The start gcode was different from my slice of it.

**Comment by ioquatix** [comment]
I found that the issue did not show up in 1.3.0-dev so this has already been fixed. Thanks for your help and patience, and trying out the issue on your end.
