### ISSUE TITLE
perimeter width displayed in the prefix of gcode is wrong

### ISSUE THREAD

**Issue by ekaggrat** [alexrj/Slic3r#3420]
### Version
1.2.9 and 1.1.7

### Operating system type + version
windows 7 ulitmate

### Behavior
when you slice using slic3r and set the perimeter extrusion width to a percentage from 110% to 150% the 
perimeter width that slic3r displays in the prefix of the gcode file is wrong and is in the range of 0.26 - 0.35 

the printer nozzle size is 0.4 mm . So a perimeter of 110% should be 0.44 . 
bug

**Comment by Mikk36** [comment]
![](https://dl.dropboxusercontent.com/u/54281287/slicerPercentage.PNG)
