### ISSUE TITLE
Feature Request: Prompt to export config bundle

### ISSUE THREAD

**Issue by MatthewGSharkey** [alexrj/Slic3r#3425]
### Version
_Version of Slic3r used goes here_
1.2.9

### Operating system type + version
Windows 10

### Behavior
* _Had to reformat the computer, lost all of my Slic3r settings. Settings are presumably kept in the appdata folder._
* _Reformat your computer without any regard to your data._
* _Expected Results_:
Sadness and frustration. Also, all of your settings will be gone.
* _Actual Results_:
All of your settings will be gone

_Is this a new feature request?_: 
Yes

Please include a simple script to remind users (and provide a button) to export their config bundles on a weekly basis or every 10 GCode exports (whichever comes first.)

I believe many users (myself included) actively back up their document folder or their desktop items, however the appdata folder is rarely ever considered. Regular backups to the users documents would be a proactive method to save some heartache.

bonus points if you write a script that emails the config bundle to the user's preferred email address!

**Comment by lordofhyphens** [comment]
Symlink the profile folder to somewhere you backup regularly. On windows 7+ you should be backing up the entire user profile directory. 

Moreover such a prompt makes no sense on Linux or OSX, because those are in a much more sensible location on those platforms: ~/.Slic3r
