### ISSUE TITLE
Volume calculation for model is -1.

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#3431]
### Version
1.3.0-dev 848374602d777f0795a6345c1b337a0d09c0eb4a

### Operating system type + version
Linux Debian Jessie x64

### Behavior
Slic3r is reporting STL volumes as -1.00. See screenshot. 
![neg_volume](https://cloud.githubusercontent.com/assets/31754/16906050/edf7b574-4c75-11e6-9b00-d84b547a0a85.png)

#### STL/Config (.ZIP) where problem occurs
[test.zip](https://github.com/alexrj/Slic3r/files/368332/test.zip)

**Comment by bubnikv** [comment]
This is interesting. At least the Prusa3D Windows build gives a positive number.

**Comment by lordofhyphens** [comment]
Yeah, I suspect it was something recent; I'll check on my build on bintray
and see if that's got the same bug in it.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by alexrj** [comment]
Fixed, thank you.
