### ISSUE TITLE
Discuss: Test with STL/AMF models? 

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#3435]
The recently merged-in PR #3432 uses an an additional file that the test loads to try to cover the regression. It was necessary here because the load syntax needed to be exercised. 

Going forward with tests, how much of this is a considered a "good idea" for adding further tests in the future, especially for printing artifacts? Would it be better to convert the STL ASCII format to the array that Slic3r uses for some of its internals, or should we load STL/AMF files (cut down to the absolute minimum that exposes the bug)?
- Pros
  - Catches the exact failure case
  - Separate from the code base itself.
  - Less likelihood of transcription errors.
- Cons
  - Licensing issues with the 3d model
  - Size of 3d model

**Comment by alexrj** [comment]
Well, I don't care much as long as it's clean ;-)))
