### ISSUE TITLE
Different Infill Percentage before "Top Layer" start   *FEATURE REQUEST*

### ISSUE THREAD

**Issue by LeChuck71** [alexrj/Slic3r#3445]
Hi there,

I just got some problems with my top layers if the infill percentage is very low e.g. 5% and the top layers are quite big e.g. 40mm x 50mm box

It would be great if we could switch the infill percentage to a higher value before the top layers start printing like

Solid top layers: 3
Number of layers before top layer: 5
Infill Percentage before top layer: 50%

In this example the infill would switch to 50% beginning with the 8th last layer and to top layer with the last 3.

I know other slicers that can setup "processes" but they only handle it at a absolute "layer number" if you got multiple "end heights" this is no solution to the problem.

I don't know if slicer can already handle such a feature

Cheers
Axel

**Comment by lordofhyphens** [comment]
See #3333 and modifier meshes.
