### ISSUE TITLE
Hangs forever on ‘Processing triangulated mesh’

### ISSUE THREAD

**Issue by DrLex0** [alexrj/Slic3r#3447]
### Version
1.2.9

### Operating system type + version
Mac OS X 10.11.6

### Behavior
* I try to slice the attached STL file, which is a modification of a tiny subpart of [Thingiverse 1149469](http://www.thingiverse.com/thing:1149469/).
* If background processing is enabled, it never ends, and spins up my laptop's fans.
* When I export the G-code, it stays stuck forever on “Processing triangulated mesh…” and again makes my fans go full throttle.
* If I then quit Slic3r, it crashes consistently. A crash report is included in the ZIP below.
I don't know if it will eventually finish if I wait long enough, but I have sliced way larger and way more complex models in 15 seconds, and this one is still stuck after 15 minutes.

This model is manifold and I have run it through the default repair of Netfabb Free, which hasn't changed anything about it as far as I could see.
I have sliced the entire model this is a subpart of, and it printed “fine” aside from tiny details getting messed up (which is why I want to tweak my settings with this tiny part before I make another attempt). If there is anything about this model that makes it unslicable, I would expect an error message instead of endlessly spinning fans.

(As a sidenote, the unofficial 1.30.0 version does not hang on this. However, it sets the first layer height to a different value than the one I asked, which I reckon has cost me half a day of watching ABS get curled up around the nozzle. I hate this whole object already but my mission is to get it printed by Friday to give it as a birthday present.)

#### STL/Config (.ZIP) where problem occurs
[STL-config-crashreport.zip](https://github.com/alexrj/Slic3r/files/394625/STL-config-crashreport.zip)

**Comment by lordofhyphens** [comment]
Can't reproduce with 1.3.0 and the provided STL and config.ini on Linux.
