### ISSUE TITLE
Feature Request: Max print speed for filament settings

### ISSUE THREAD

**Issue by MGBob** [alexrj/Slic3r#3451]
It would be nice to have a max speed in filament settings that limits the print speed based on filament type. I'm trying rubber filament and I had no luck in high speed, but in low speed it is fine. Now I'm trying to add small rubber parts to solid objects, so I need fast printing for PLA parts and slow print for rubber parts.

**Comment by lordofhyphens** [comment]
I think this can be handled with additional custom gcode tied to filament profiles (M220 adjusts the print speed as a %).

**Comment by alexrj** [comment]
We now have a *max_volumetric_speed* option, so I'm closing this.
