### ISSUE TITLE
Bed temperature is not set correctly

### ISSUE THREAD

**Issue by lavato** [alexrj/Slic3r#3453]
### Version

1.2.9
### Operating system type + version

Win7
### Behavior

In multi extruder environment when e.g. user has ABS on T0 and PLA on T1, when user prints only with PLA (T1), printer bed temperature is set incorrectly to T0 bed temperature.

However hot end temperature is set correctly.

**Comment by lordofhyphens** [comment]
Could use a test config.

**Comment by lordofhyphens** [comment]
Same as #3664 and that one is better documented. Closing.
