### ISSUE TITLE
Over-extrusion when odd number of vertical shells required

### ISSUE THREAD

**Issue by centripetal3** [alexrj/Slic3r#3459]
### Version
Slic3r 1.2.9

### Operating system type + version
Ubuntu Linux 14.04 LTS

### Behavior
* When producing a vertical wall with an odd number of shells, a single line of infill is produced which is larger than the volume it's intended to fill. The extra extruded plastic builds up and eventually collides with the nozzle, causing the print to fail. When a vertical wall has an even number of shells, the extrusion does not use any infill and the part prints flawlessly.

I'm not sure if I'm doing something wrong, or if this is possibly related to https://github.com/alexrj/Slic3r/issues/3448

As a general comment, Slic3r is _amazing_ and does a fantastic job. I've made dozens of successful prints so far, and this is the only problem spot. Keep up the good work!

#### STL/Config (.ZIP) where problem occurs
[testcase.zip](https://github.com/alexrj/Slic3r/files/417450/testcase.zip)

![screenshot_1](https://cloud.githubusercontent.com/assets/21029640/17654136/a66346f2-626d-11e6-8481-5ef5057cdbd8.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/21029640/17654138/a6686498-626d-11e6-813f-57b2dd19e896.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/21029640/17654137/a663929c-626d-11e6-848e-56b58482c3f9.png)

![testcase_overview](https://cloud.githubusercontent.com/assets/21029640/17654195/635132ec-626e-11e6-9fc1-af9ca917538c.jpg)

**Close-up of successful print:**
![testcase_good](https://cloud.githubusercontent.com/assets/21029640/17654193/634c2720-626e-11e6-8052-94230ff39ce3.jpg)

**Close-up of failed print:**
![testcase_bad](https://cloud.githubusercontent.com/assets/21029640/17654194/634dbf04-626e-11e6-8191-3e459f0609ef.jpg)

**Comment by lordofhyphens** [comment]
That single line is gap fill, and it's known to have overextrusion problems in 1.2.9. 
Suggest either using 1.3.0-dev from source or disabling gap fill (set speed of gap fill to 0).

**Comment by centripetal3** [comment]
Worked like a charm. Thank you!
