### ISSUE TITLE
Translation file PrintConfig.cpp, encoding

### ISSUE THREAD

**Issue by AndylgTom** [alexrj/Slic3r#3464]
### Version
compile the repository 1.30....

### Operating system type + version
Windows10 x64_

### Behavior
Hi, help please.
Translate program to russian language. In the translation file PrintConfig.cpp faced with the problem of incorrect display of the translated text in the program. See screenshot ![sssllll](https://cloud.githubusercontent.com/assets/20997012/17785538/71bac722-65ab-11e6-97b1-d01e7e3328ed.png)

That's a line 206 in file PrintConfig.cpp. Ie all the lines with "def->category =" appear in the gibberish. At that translated line "def->label =", def->tooltip = " displays the program normally.
How to fix this?
Thx.

**Comment by lordofhyphens** [comment]
Check the encoding in the source files, otherwise your guess is as good as mine.

**Comment by AndylgTom** [comment]
How to understand you have to offer to convert Print Config.cpp UTF-8 to Unicode?
I tried - gives an error. And the problem with THIS file! (On the other files, such as Object.pm, Print.pm, converting from UTF-8 format to Unicode format helped. But that file PrintConfig.cpp it doesn't work - compile error.)
![error unicode compile notepad cmd](https://cloud.githubusercontent.com/assets/20997012/17800672/5a28e576-660f-11e6-8565-13e355d9a8c4.png)
![utf-8 gibberish](https://cloud.githubusercontent.com/assets/20997012/17800673/5a2bd3a8-660f-11e6-9abb-110bc729eb05.png)

**Comment by lordofhyphens** [comment]
Error message tells you, in C++ terms, what it thinks is wrong.

I am not going to offer to convert anything for you.

**Comment by lordofhyphens** [comment]
Whatever program you used to process the text put a bunch of spaces and
null characters into the source code.

Clean it up and you will probably get somewhere.

**Comment by AndylgTom** [comment]
So why in some russian text files in utf-8 format is displayed in the program interface is normal, and in the other case (Object.pm, Print.pm, PrintConfig.cpp) displaying gibberish? And in PrintConfig.cpp this applies only lines "def-> category". ???

Try to enter сyrillic text into the line 206 in file PrintConfig.cpp... And compile. I am sure at 100% it will be the same.

**Comment by bubnikv** [comment]
Maybe not all the Slic3r code or the underlying Perl::Wx or the WxWidgets
library supports Unicode correctly?

**Comment by AndylgTom** [comment]
> Maybe not all the Slic3r code or the underlying Perl::Wx or the WxWidgets
> library supports Unicode correctly?
I don't know

Apparently in this place source encoding UTF-8 displayed as Windows-1252. Why and how to fix this? 
![2cyr](https://cloud.githubusercontent.com/assets/20997012/17801972/8784d57c-6617-11e6-9a98-aa7fa9152ca8.png)

**Comment by AndylgTom** [comment]
Can delete the topic, the problem was Config.xsp и XS.c . Someone were missed encoding for categories.

**Comment by lordofhyphens** [comment]
This isn't a forum, it is a bug tracker. Best I can do is lock the thread.
