### ISSUE TITLE
-Dev versions from windows CI server won't load GL

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#3469]
What it says on the tin :) 
elvisior did some checking with sysinternals and saw that it was missing libglut-0_.dll, will do some further investigation on my own.

The version used on the ci server is 32-bit strawberry perl 5.22.

I'll have a PR up once it's fully tracked down.

**Comment by elvisior** [comment]
Confirmed working using the libglut-0_.dll from a 32 bit strawberry perl install. 
Will grab the bintray version in an hour and test it (if I don't get distracted by the football)...

**Comment by elvisior** [comment]
Tested slic3r-add-libglut-dll--566bbbd and it worked a charm.
Thanks

**Comment by lordofhyphens** [comment]
Excellent. Thanks.
