### ISSUE TITLE
Issue/Feature request: Auto split before generating GCode

### ISSUE THREAD

**Issue by Iffoffo** [alexrj/Slic3r#3480]
### Version

1.2.9
### Operating system type + version

Win 7 64bit
### Issue
- I use Repetier 1.6.2 and I'd like to do "Sequential Printing" but when Repetier sends objects to Slic3r, Slic3r see them as only one STL (only one object) so it can not complete individual objects
### New Feature
- I'd like to have a checkbox "Auto-split before generating GCode = Y/N". In this way I think that we could solve this issue

Many thanks

**Comment by lordofhyphens** [comment]
I will check the CLI interface to see if it supports multiple input files.
I think split on load through the CLI is probably generally useful though
(if it was just for RepetierHost it probably wouldn't get in, we are
generally disinclined to make changes solely to support closed source
programs).

**Comment by alexrj** [comment]
Repetier-Host should export an AMF file instead of a STL. AMF supports multiple objects. Also, slicing will be faster when you put multiple copies of an object on plate.

**Comment by bubnikv** [comment]
Repetier indeed generates AMF. Only AMF import is many orders of magnitude
slower than STL import. I am working on C++ port of the AMF import.
