### ISSUE TITLE
Set bed size /0 

### ISSUE THREAD

**Issue by Taragorm** [alexrj/Slic3r#3521]
### Version

1.2.9
### Operating system type + version

Linux  OpenSuse Tumbleweed x64
### Behavior
- _Describe the problem_
  When in the "set bed size" dialog, cursoring to the first character of X and hitting delete causes
  an immediate crash with a divide by zero exception. I.e. when 200 -> 00 in the edit box.
- _Steps needed to reproduce the problem_
  See above
  - _If this is a command-line slicing issue, include the options used_
    N/A
- _Expected Results_
  It shouldn't crash.
- _Actual Results_
  It does.
  - _Screenshots from ___Slic3r___ preview are preferred_

_Is this a new feature request?_
No
#### STL/Config (.ZIP) where problem occurs

N/A

**Comment by bubnikv** [comment]
I hope this has been fixed by me.You may try the Prusa3D build
https://github.com/prusa3d/Slic3r/releases

or the builds of the official Slic3r made by @LoH
https://bintray.com/lordofhyphens/Slic3r/Slic3r_Branches

Vojtech

**Comment by alexrj** [comment]
Yes, AFAIK this was fixed in 1.3.0-dev.
