### ISSUE TITLE
Don't start bridge from the middle of the gap

### ISSUE THREAD

**Issue by Yenya** [alexrj/Slic3r#3526]
### Version

slic3r-1.2.9-8.fc24.x86_64
### Operating system type + version

Fedora 24
### Behavior
- When priting a bridge (e.g. "bridge torture test" object from thingiverse) with "Seam position" set to "Random", slic3r often starts printing the bridge from the middle of the gap which is to be bridged. The first trace is therefore not attached to anything, and real print starts from the next trace.

Expected results: even with "Seam position = Random", the layer should start (randomly) from a point that is not part of a bridge.

[bridge.zip](https://github.com/alexrj/Slic3r/files/511049/bridge.zip)

**Comment by DrLex0** [comment]
Also just noticed this on the bridge test [model](http://www.thingiverse.com/thing:12925), here's what it looks like in gcode viewer:
![gcodeview](https://cloud.githubusercontent.com/assets/16401844/20648980/0d3557fa-b4b5-11e6-9e38-06d7b76014e3.png)

The result:
![bridge](https://cloud.githubusercontent.com/assets/16401844/20648954/78f1641c-b4b4-11e6-8163-e5cd1ccb8ed6.jpg)

Still present in the prusa3d 1.31.5 build as well.

**Comment by bubnikv** [comment]
I have fixed that in the Prusa3D fork. The fix avoids placement of the seam on a bridging perimeter, even in the random seam mode. This means it will avoid bridging overhangs as well. I think this is a reasonable implementation, because a seam on an overhang perimeter is bad as well.

**Comment by alexrj** [comment]
Fixed in master as well, thank you.
