### ISSUE TITLE
Empty layer generated

### ISSUE THREAD

**Issue by benv666** [alexrj/Slic3r#3530]
### Version
1.30.0.25-prusa3d-release_candidate_1_3-win64

### Operating system type + version
Windows 8.1 64 bit

### Behavior
A big gap is somehow generated halfway the object, as can be seen in screenshots here:
http://i.imgur.com/UBrAOTk.png
http://i.imgur.com/Bn7wPPG.png

Reproduce: with attached STL file and config, problem occurs between Z=4.70 and Z=5.35 (which is currently filled with support structure, which shouldn't happen).

Expected: no gap / support fill, just my object at those layers with possibly -some- support, not only support material.

#### STL/Config (.ZIP) where problem occurs
[filament guide v1.zip](https://github.com/alexrj/Slic3r/files/518313/filament.guide.v1.zip)
[slic3r-config.zip](https://github.com/alexrj/Slic3r/files/518322/slic3r-config.zip)

**Comment by lordofhyphens** [comment]
You need to confirm this is happening with Slic3r git master (not the
prusa3d fork).

**Comment by benv666** [comment]
Sure, if you have a precompiled git-master win64 build for me?

**Comment by lordofhyphens** [comment]
Win32: https://bintray.com/lordofhyphens/Slic3r/slic3r_dev/1.3.0-master-183#files

Basically, if this can't be confirmed to occur with our git master, it should be brought up in whatever support channels prusa3d operates.

**Comment by benv666** [comment]
Just tried your win32 binary, same problem:
http://i.imgur.com/UmihoEN.png
http://i.imgur.com/W4zMJEX.png

**Comment by lordofhyphens** [comment]
Your model is broken.
![screenshot - 10092016 - 09 30 18 am](https://cloud.githubusercontent.com/assets/31754/19221198/13b92cc8-8e04-11e6-84c8-56e4696784c7.png)

This is the result with a non-broken model. 
![screenshot - 10092016 - 09 38 52 am](https://cloud.githubusercontent.com/assets/31754/19221205/33d2d3b0-8e04-11e6-8f1b-3cd255590f82.png)
[fixed-manifold.zip](https://github.com/alexrj/Slic3r/files/518356/fixed-manifold.zip)

Closing.
