### ISSUE TITLE
Setting "Top Solid Infill" to any any percentage value produces holes in top layer

### ISSUE THREAD

**Issue by Pointedstick** [alexrj/Slic3r#3534]
### Version
1.2.9

### Operating system type + version
Mac OS 10.12 Sierra

### Behavior
When I set any percentage value for Extrusion Width -> Top Solid Infill, the top layer is printed with insufficient flow, resulting in holes.

* _Steps needed to reproduce the problem_
  * Find Extrusion Width -> Top Solid Infill and change the default value (0) to a percentage number (e.g. 98%)

* _Expected Results_: extrusion width and spacing on top solid layers are reduced to improve surface finish, but flow rate is adjusted to compensate

* _Actual Results_: extrusion width and spacing on top solid layers are indeed reduced, and surface finish improves on *most* of the top layer, but insufficient flow rate (or something like that) causes gaps in other parts of the top layer. I've tried this with various values ranging from 80% to 99%; the same thing happens every time.

Layer preview in Slic3r:
![preview](https://cloud.githubusercontent.com/assets/1097249/19328644/dc23fb86-9091-11e6-9efc-24f66c0da5c5.png)

Finished prints:
![cubes](https://cloud.githubusercontent.com/assets/1097249/19328650/e00aa0ce-9091-11e6-80f9-312468a473d2.JPG)

The cube on the left has the default value for Extrusion Width -> Top Solid Infill (0); the one on the right has it set to 98%.

#### STL/Config (.ZIP) where problem occurs
https://www.dropbox.com/s/t0fqb1eg39x5cr7/beveled%20cube.stl
https://www.dropbox.com/s/ekyr4vhs02jjre7/Slic3r_config_bundle.ini

**Comment by lordofhyphens** [comment]
Just an FYI: the % is relative to the layer height, not any other widths.
So values  < 100% are only for if you know what you are doing.

**Comment by lordofhyphens** [comment]
Could you post a screenshot of the 3d preview?

**Comment by Pointedstick** [comment]
3D preview of the object:
![cube](https://cloud.githubusercontent.com/assets/1097249/19329295/2d31faf2-9095-11e6-8270-407790918ade.png)


3D preview of top layer:
![top layer](https://cloud.githubusercontent.com/assets/1097249/19329305/38a60450-9095-11e6-8eea-403f86f999a9.png)

**Comment by lordofhyphens** [comment]
You uploaded a config bundle instead of a plain config, but from what I can see you are trying to to print lines at widths of 0.196mm or 0.098mm, with a nozzle width of 0.4mm.

From the toolpath it's indeed giving you the trace widths you're asking for. I am not surprised that your printer  fails to produce traces less than half of the width of your nozzle.

Does it fail at 450% (with the 0.1mm layer height profile) or 225% (0.2mm layer height). If not, this is a case of your printer not being up to the task of what you asked of it.

**Comment by lordofhyphens** [comment]
Please reopen if you are able to replicate the effect with the widths as mentioned above, and provide a regular exported config File->Export Config (Ctrl+E).

**Comment by Pointedstick** [comment]
All right, looks like I need a smaller nozzle.

**Comment by lordofhyphens** [comment]
Smaller nozzle restricts your speed (higher pressures) and limits the max layer height as well, just FYI.

**Comment by Pointedstick** [comment]
Yeah, I know.
