### ISSUE TITLE
If I change the souce code ,how can I  rebuild it and run it again?

### ISSUE THREAD

**Issue by szxyxukai** [alexrj/Slic3r#3537]
### Version
I'm running slic3r from git/source code by command line. The code is still up-to-date.

### Operating system type
I use it on the windows system.

### Behavior
I WANT to rewrite part of the souce code instead of original code. However I don't know if I change it , CAN I  rebuild it again and use the command line to slice a model? Or I NEED to do something else?
THANK YOU FOR YOUR ANSWERS!

**Comment by lordofhyphens** [comment]
If it is C++, yes: rerun Build.pl

 Perl, no: just restart Slic3r.
