### ISSUE TITLE
Sailfish & MakeWare set temperature unwanted behavior

### ISSUE THREAD

**Issue by uclaros** [alexrj/Slic3r#3546]
### Version

Noticed on 1.2.9 but I can see it has not been addressed neither on stable nor on master branch
### Operating system type + version

Windows7 64 and Debian 8 64x, but the bug is OS independent.
### Behavior

When having Sailfish or MakerWare G-code flavor selected, slic3r's gcode does not wait for the extruders to reach the desired temperature. Furthermore, when using dual extruders and having set a "temperature delta" for ooze prevention, extruders temp is set to (original_temp - delta_temp) (instead of original_temp).

The problem is that Sailfish and MakerWare firmware don't use M109 to set temperature and wait, instead they use M104 to set the temp followed by M6 to wait for it to be reached. This is only partially handled by Slic3r when a "set temp but not wait" is requested (M104 is issued correctly).
When a "set temp and wait" is requested, the "set_temperature" method returns prematurely, effectively ignoring all sailfish requests to set the temperature and wait.

To reproduce slice anything with 2 extruders and select ooze prevention with a delta temp set.

**Comment by lordofhyphens** [comment]
Thanks for the catch. Dangit, Makerbot! :)
