### ISSUE TITLE
Feature Request: Implement Varislice 

### ISSUE THREAD

**Issue by mrjohnc** [alexrj/Slic3r#3559]
Implement Varislice as described at http://hackaday.com/2016/11/03/variable-thickness-slicing-for-3d-printers/

Also combine this feature with a calculation minimising the number of infill layers, similar to to 'Infill every n layers' option but keeps a large infill layer height whilst the perimeter layers heights change.

**Comment by Patola** [comment]
@platsch is working on it in #1386

**Comment by lordofhyphens** [comment]
@platsch was working on it before it was cool.

Pretty sure the second part is NP hard.

**Comment by platsch** [comment]
@lordofhyphens maybe this is a misunderstanding, but what makes you think dynamic infill would be computationally hard? Actually, I think the current implementation already works more or less this way. You can just set `infill_every_n_layers` to a high number (e.g. 10) and the algorithm will combine as many variable perimeter layers as possible to a single infill layer.
Works pretty well in my experiments.

**Comment by lordofhyphens** [comment]
I am probably thinking of a different problem definition, but I thought
that the request was to determine the maximum number of layers to combine.

**Comment by lordofhyphens** [comment]
Platsch's work in #1386 does this better, and setting combine infill and setting it to a high number maximixes infill.

**Comment by mrjohnc** [comment]
Thanks @lordofhyphens
