### ISSUE TITLE
Enable "detect bridging perimeters" when the supports get enabled.

### ISSUE THREAD

**Issue by bubnikv** [alexrj/Slic3r#3571]
Supports require the bottom surfaces to be printed with a bridging flow. That requires the "detect bridging perimeters" feature to be enabled. Following patch proposes this action to the user:

https://github.com/prusa3d/Slic3r/commit/1070f0c0af2ba4c2bba2e47984dcc0e6438d5309

**Comment by lordofhyphens** [comment]
I'm agreed on this behavior, good catch ensuring that the user can override. 

PR is up.

**Comment by alexrj** [comment]
Thank you!  PR merged.
