### ISSUE TITLE
Optimization work from Prusa3d fork

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#3581]
@bubnikv has put quite a bit of effort into optimizations and utility/library code in libslic3r. This work gets used often in feature implementations on that fork.

We should investigate and integrate those changes into Slic3r as both an enhancement to libslic3r and making later features able to be pushed upstream.

**Comment by alexrj** [comment]
Yeah, we've been doing this. I'm closing this particular issue as it's not strictly needed :)
