### ISSUE TITLE
Lots of errors compiling with standard instructions

### ISSUE THREAD

**Issue by Bobobalink** [alexrj/Slic3r#3594]
### Version
alexrj/Slic3r master branch
1.2.9-483-gcba3b19

### Operating system type + version
Windows 10 64 bit

### Behavior
I had some weird issues with installing cpanminus with strawberry perl, so I'm using citrus perl.
 I had to install a newer version of citrusperl (15.6 instead of 15.4), but I managed to get strawberryperl to work properly exactly once, and it had the same result.

Everything works up until the `perl Build.Pl` step. It fails while trying to compile `src\libslic3r\utils.cpp`
It spews several dozen errors, but many of them are the same error repeated many times. All of them are as follows:
```C:\dev\boost_1_59_0/boost/bind/storage.hpp:44:40: error: macro "PerlSock_accept" requires 3 arguments, but only 1 given```
```c:\mingw\mingw64\bin\../lib/gcc/x86_64-w64-mingw32/4.6.3/include/c++/bits/locale_facets_nonio.h:1768:65: error: macro "PerlLIO_open" passed 3 arguments, but takes just 2```
```C:\dev\boost_1_59_0/boost/thread/future.hpp:1884:46: error: macro "PerlProc_wait" passed 2 arguments, but takes just 1```
```C:\dev\boost_1_59_0/boost/thread/win32/thread_primitives.hpp:415:25: error: expected ')' before '*' token ```
```C:\dev\boost_1_59_0/boost/exception/detail/exception_ptr.hpp:149:40: error: expected '}' before end of line```

It looks like the errors are actually with boost, not with slic3r, but building boost does not throw any errors.

**Comment by lordofhyphens** [comment]
Yeah, I literally just fixed this fifteen minutes ago. Perl.h defines a ton of macros and those collide with functions that boost has in its headers (inline functions, etc). 

There are known issues with 5.16 and slic3r. I don't remember what they are.
