### ISSUE TITLE
GUI Crash in Ubuntu 14.04

### ISSUE THREAD

**Issue by jabdoa2** [alexrj/Slic3r#3596]
### Version
_Version of Slic3r used goes here_
master

_For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_
1.2.9-485-g3f3f696

### Operating system type + version
_What OS are you using, and state any version #s_
Ubuntu 14.04 x64

### Behavior
* _Describe the problem_
Sli3r crashes on start:

```
./slic3r
Undefined subroutine &Wx::ToolTip::SetAutoPop called at lib/Slic3r/GUI/MainFrame.pm line 44.
```

Regression caused by commit: https://github.com/alexrj/Slic3r/commit/07009b601f75e6166d75ae6dd292c9863356e99e

GUI starts fine when commenting out that line.

**Comment by alexrj** [comment]
Thank you, that function appears to not be available on GTK. Fixed.
