### ISSUE TITLE
Spurious retractions

### ISSUE THREAD

**Issue by jabdoa2** [alexrj/Slic3r#3597]
### Version
_Version of Slic3r used goes here_
master

_For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_
1.2.9-485-g3f3f696

### Operating system type + version
_What OS are you using, and state any version #s_
Ubuntu 14.04 x64

### Behavior
* _Describe the problem_
Printer retracts a lot during print. Retraction is 1.5mm which works but sometimes when printing infill after diameters it retracts 3cm or more which breaks the print.
* _Steps needed to reproduce the problem_
Slice skull jaw of http://www.thingiverse.com/make:270358
* _Expected Results_
No spurious retraction. 
* _Actual Results_
Retracts unexpectedly.

GCODE output and config.ini (culled from gcode output).
[3597.zip](https://github.com/alexrj/Slic3r/files/622408/3597.zip)

**Comment by lordofhyphens** [comment]
In the future, please use File->Export Config to get a config.ini file and zip that and any attachments and attach that. 

Dumping gcode in plain text like that is painful to deal with.

**Comment by lordofhyphens** [comment]
It would probably help a lot if you turned on firmware retraction to highlight the retract/restore commands (or turned on verbose gcode which should show them). 

Slic3r is going to retract at the end of every loop when it has to cross perimeters (as noted in your gcode). 

I've attached a slice from a build of 3700950 on windows. 
[config-debug.zip](https://github.com/alexrj/Slic3r/files/622450/config-debug.zip)

**Comment by jabdoa2** [comment]
Ok will do next time. Noteworthy in the paste was  Filament used: -5861.5mm. In the snippet it would retract 35mm which removed all Filament from the extruder. Same model works with same settings in stable.

**Comment by Tinchus2009** [comment]
Im observing a what I think is the same behaviour: I have atacched a stl and my configs (slic3r version is the last version I got from git pull command). My retraction setting are 0.5 mm. but like soemthign around Z + 30 mm the extruder starts makeing HUGE retractions, like 3 cms or more I would say, that completly ruins the print since after this retraction, the filament is only pulled in 0.5 mm,,,
[pruebas_impresion.zip](https://github.com/alexrj/Slic3r/files/636857/pruebas_impresion.zip)

**Comment by lordofhyphens** [comment]
@Tinchus2009 turn off pressure advance.

**Comment by Tinchus2009** [comment]
I dont use that feature, in the printer settings you mean? there, pressure advance is set to 0

**Comment by Tinchus2009** [comment]
I have repeated the print: same object, same config, only difference was that I change position of the object. It happened again, but this time I decided to let the print continue. The issue arised somewhere between Z = 40 and 47 mm. A huge retraction hapened there, after that the print conued with no issues so far (still printing now). I generated the verbose gcode file (atached)
[Assem1_-_Part8Assem1-1.zip](https://github.com/alexrj/Slic3r/files/637080/Assem1_-_Part8Assem1-1.zip)

**Comment by jabdoa2** [comment]
Same issue for me. It starts fine and after a few layers it retracts large amounts of filament. Same model with same settings works in stable. Also the total filament used is negative in dev but not in stable.

**Comment by lordofhyphens** [comment]
Gap fill may be the culprit then. Turn on verbose gcode output and it will
tell you in the gcode when it is retract.

**Comment by Tinchus2009** [comment]
I dont use autospeed nor pressure advance

**Comment by lordofhyphens** [comment]
As I said, try disabling gap fill and turn on verbose gcode to see what the
long negative moves look like in the printing process. They probably aren't
actually retract moves.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
@alexrj any idea offhand why there would be negative E values in the extrusion? Verbose gcode is tagging them as perimeters. It's definitely not a retract though, as there's X/Y moves along with it.

**Comment by lordofhyphens** [comment]
Looks like a regression of some kind since 1.2.9 at least. Only have all the commits of course to check.

**Comment by lordofhyphens** [comment]
Still in the middle of the bisect. 893fc2343f0aa3855078f20561d2f7a977610791 exhibits the problem.

**Comment by lordofhyphens** [comment]
Accordng to git bisect, the problem commit is 24afffc421ebd8a9297528bdfa038ba33490e3c2 

Tomorrow I'll write up a regression test with a minimum case of the trex jaw (odds are there's negative flow in some of these areas for some reason). 

@bubnikv Unless you've done a ton more work since this commit this'll be in the Prusa build as well.

**Comment by lordofhyphens** [comment]
The observed behavior is perimeters are being drawn with negative feedrate, unknown at present why.

**Comment by bubnikv** [comment]
> Accordng to git bisect, the problem commit is 24afffc
<https://github.com/alexrj/Slic3r/commit/24afffc421ebd8a9297528bdfa038ba33490e3c2>

> Tomorrow I'll write up a regression test with a minimum case of the trex
jaw (odds are there's negative flow in some of these areas for some reason).

> @bubnikv <https://github.com/bubnikv> Unless you've done a ton more work
since this commit this'll be in the Prusa build as well.


I am not quite sure whether the bisect is a right tool here as the file has
been touched later on to fix some issues.

https://github.com/prusa3d/Slic3r/blame/master/xs/src/libslic3r/ExtrusionEntity.cpp

@Tinchus2009

Would you please test the latest prusa3d build for this issue? Thanks

https://github.com/prusa3d/Slic3r/releases/tag/version_1.31.6

**Comment by lordofhyphens** [comment]
@bubnikv I ran the bisect with an initial good and bad of 1.2.9 and HEAD,
skipping commits that failed to build and verifying the output after every
successful pass. I am fairly confident that the regression was introduced
there (binary search), but I intend to build a regression test anyway for
future safety.

Obviously if you changed the file after that commit then it may not be
reflected in your fork.

**Comment by lordofhyphens** [comment]
@bubnikv Looks like you found the issue in the prusa3d fork and fixed it already, the original commit used the ExtrusionPath constructor that only supplied the role and used default args for everything else.

You later changed it to call the constructor to give the two new paths the same flow amount and width/height. This differs from the original (prior to that commit) in that @alexrj used what looks like the implicit copy constructor (via =). 

Here's a slice of the trex object that shows the problem, currently working on a regression test using it.
[3597-failure.zip](https://github.com/alexrj/Slic3r/files/640944/3597-failure.zip)

**Comment by Tinchus2009** [comment]
Sorry to be kate. I have tested the prusa version you told me, useing the same stl, it looks like the problem is not present. Either way, I can see you solve it here too, great!
