### ISSUE TITLE
Can't locate object method "new" via package "LWP::UserAgent" (perhaps you forgot to load "LWP::UserAgent"?) at /usr/share/perl5/vendor_perl/Slic3r/GUI/Plater.pm line 1330.

### ISSUE THREAD

**Issue by ioquatix** [alexrj/Slic3r#3605]
### Version
1.3.0-dev

### Operating system type + version
Arch Linux

### Behavior
- Any model, send to printer.

slic3r.pl crashes with the following output:
Can't locate object method "new" via package "LWP::UserAgent" (perhaps you forgot to load "LWP::UserAgent"?) at /usr/share/perl5/vendor_perl/Slic3r/GUI/Plater.pm line 1330.

**Comment by lordofhyphens** [comment]
Is this a recent checkout?

**Comment by ioquatix** [comment]
yes like a few days ago

**Comment by lordofhyphens** [comment]
Yeah, apparently that got added w/o adding it as a ref and it works on some systems and not others (go figure). 
I'm testing a fix real quick (just add 'use LWP::UserAgent' to the top of the file with the other use statements to that file).

**Comment by lordofhyphens** [comment]
Should be fixed now.
