### ISSUE TITLE
"FLIP" is the wrong word.

### ISSUE THREAD

**Issue by cameronbergh** [alexrj/Slic3r#3607]
### Version
129

mac, linux, windows

This is some excellent programming, 
Seriously, world changing stuff that you are doing. great job.

My only issue is a very small one.
When i right click on an object there is this option to "flip"
an object along a specified axis, however, this does not flip the object.
instead it reflects the object.

# let me demonstrate:

<img width="524" alt="screen shot 2016-12-06 at 10 45 27 am" src="https://cloud.githubusercontent.com/assets/15796764/20949319/919faa58-bbcd-11e6-9d6b-892116325db8.png">

### below: an unmodified object which i am hastily trying to get printed.

<img width="747" alt="screen shot 2016-12-06 at 10 57 28 am" src="https://cloud.githubusercontent.com/assets/15796764/20949324/957c1f9e-bbcd-11e6-8596-88ae01710ac0.png">

### notice that the threads now turn in the opposite direction, making this printed part useless.

<img width="876" alt="screen shot 2016-12-06 at 10 57 49 am" src="https://cloud.githubusercontent.com/assets/15796764/20949328/97db08b8-bbcd-11e6-95fb-5c2e9da4c394.png">

###here is a picture of a girl doing a flip:

![aid7189-728px-do-a-triple-front-flip-step-2](https://cloud.githubusercontent.com/assets/15796764/20949331/9f867020-bbcd-11e6-8e6f-af5e4c00fc4a.jpg)
http://www.wikihow.com/Do-a-Triple-Front-Flip

### here is what the "flip" function in slic3r is actually doing:
this image is from the wikipedia page for reflection!
https://en.wikipedia.org/wiki/Reflection_(mathematics)
![simx2 transl_ok svg](https://cloud.githubusercontent.com/assets/15796764/20949363/badfee32-bbcd-11e6-80ac-2eb3a05b2beb.png)

one could argue that if i was a smart man, I would have used the rotate function to accomplish what I had intended, but i was in a hurry and didn't notice the subtle difference.

slic3r is still the best software for this task
thanks for all your hard work!

-Cameron

https://sciencelens.files.wordpress.com/2012/06/coin_flip_s.jpg

**Comment by lordofhyphens** [comment]
This was already fixed in -dev a year and a half ago. #3060

**Comment by cameronbergh** [comment]
LOL my bad thanks

**Comment by lordofhyphens** [comment]
And you'd put a lot of work into it too.
