### ISSUE TITLE
Rotating large objects hangs Slic3r

### ISSUE THREAD

**Issue by jkoljo** [alexrj/Slic3r#3621]
### Version
Slic3r 1.2.9 release

### Operating system type + version
Windows 7

### Behavior
When rotating a large object, Slic3r sometimes takes a long time, sometimes even hangs. I often print large stuff so I regularly run into this with about 400x400 xy prints. Then if I first resize object to for example 1% of it's size, then rotate and resize back to large, I can work around the issue.

Steps:
Take STL, resize it to about half a meter size in every direction, try rotating it. -> Slic3r either takes a long time to do it or hangs.

#### STL/Config (.ZIP) where problem occurs
File attached. It can be rotated in current size, but scale it to larger, and it will fail.

[Intake_Manifold.zip](https://github.com/alexrj/Slic3r/files/659089/Intake_Manifold.zip)

PS: Slic3r rotates into wrong direction, it does not follow the positive direction of rotation in right hand coordinate system when using positive rotation amounts. And vice versa. It is only a small nuance, should I create a new issue about it?

**Comment by alexrj** [comment]
Thank you for the report. I just tested on 1.3.0-dev (with background processing turned off) and it does not hang. Rotation is very fast.
