### ISSUE TITLE
TEST dependency fails with the latest pull update

### ISSUE THREAD

**Issue by Tinchus2009** [alexrj/Slic3r#3623]
### Version
Latest pull

_Use `About->About Slic3r` for release versions_

_For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_

### Operating system type + version
win10 64

### Behavior
I just did a git pull, it seems to compile ok, except for a dependency, TEST-SIMPLE wich fails to install. Still, the build finishes and then issuing a perl buil.pl --gui finishes the job.
IS this test-simple important. 

Ataches logs

How can I install (force install) the test-simple throug cpan manually? 
[build.zip](https://github.com/alexrj/Slic3r/files/659440/build.zip)

**Comment by lordofhyphens** [comment]
Probably not important :)

**Comment by Tinchus2009** [comment]
I "somehow" solved it: I just issued a cpan testsimple command and the test module installed with no problems this time, after that the build of slicer completed perfectly
