### ISSUE TITLE
Feature request: Setting temperatures for multiple extruders separately

### ISSUE THREAD

**Issue by JorgenLindell** [alexrj/Slic3r#3626]
When printing with different materials it would be valuable to be able to specify the extrusion temperature per extruder, but as far as I can understand, there is no such possibility in the UI currently. There is only a single common  setting in "Filament Settings".  

The temperature setting should really be per extruder, since technically, the temperature normally is generated in the extruder. Kind of the same as with nozzle width, which is part of the extruder settings.

If temperature should belong to the filament, then it should be possible to define multiple filaments, and then elsewhere connect the filament to a specific extruder, which then would take on the filaments temperature setting.

The use case for this could for example be that you are using one material for supports in one extruder that would print best at another temp than the object material in the other.

I understand that this probably can be done by specifying G-code, but for less technical users, that is not really a usable alternative.

**Comment by lordofhyphens** [comment]
Except that the necessary temperature is generally dependent on the
filament.

**Comment by Patola** [comment]
Disclaimer: I am not a slic3r developer, just a rather annoying user which follows and comments on a lot of issues.

I do not understand what feature you @JorgenLindell are requesting. I have some setups with dual extruders on slic3r and they work wonderfully. I just made a test and confirmed it works as intended. I have a graber i3 dual, two extruders, first one having "ABS filament 1.75mm" (240°C extruder, 120°C heatbed), second one having "PLA filament 1.75mm" (220°C extruder, 60°C heatbed). Then I add the sample "traffic cone for dual extrusion" and I have this initial gcode:

```
M190 S120 ; set bed temperature and wait for it to be reached
M104 S240 T0 ; set temperature
M104 S220 T1 ; set temperature
G28 ; home all axes
G1 Z5 F100 ; lift nozzle
M117 MakerLinux S.A.

M109 S240 T0 ; set temperature and wait for it to be reached
M109 S220 T1 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
T0 ; change extruder
G92 E0 ; reset extrusion distance
G1 E-4.00000 F1800.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.400 F6000.000 ; move to next layer (0)
G1 X93.043 Y93.043 F6000.000 ; move to first perimeter point
G1 E4.00000 F1800.00000 ; unretract
M204 S1000 ; adjust acceleration
G1 F720
G1 X94.273 Y91.929 E4.11747 ; perimeter
```

And then it goes one changing T0 and T1. The heatbed is assumed to be the one for the filament in the first extruder, which I think is a sensible behaviour.

The only thing I miss here is some standby temperature for the filaments. It is not unusual, specially with PLA, that after a few minutes heating in the hotend at full extrusion temperature the filament gets stuck.

**Comment by JorgenLindell** [comment]
Yes, as I said, this can be done inserting custom G-code in the generated result,

For me (who is a skilled programmer, but with no experience in this particular area), and other even less technical users, it would be a good feature to have this temperature setup in the user interface, with proper captions, input fields and help texts.

**Comment by Patola** [comment]
@JorgenLindell But I did not understand _what_ you want. If the temperature is dependent upon the filament, isn't the best place for it indeed the filament settings? You want a "default" temperature on the extruder, is that it? How would it be used if the temperature from filament would always override it? I am confused.

And you said "it can be done inserting custom G-code", what could be done? Are you talking about my "standby temperature" request or your request? I use tool change g-code to indeed change the extruder temperature to a "standby temperature".

**Comment by JorgenLindell** [comment]
I think my original posting was quite clear on the intent, a possibility to, in the User interface, be able to set different temperatures on different extruders, mostly useful when extruding different materials.

The rest of it was two possible design proposals on how that could be done. Which of those, or some third variant I haven't thought of, is basically up to the developers.  I don't fel I have insight enough on how people view the metaphors used in the UI to have a specific opinion on where it would fit best, I just think it is a setting that would be useful for people not fluent in G-code. Especially since the application has great support for multiple extruders in other ways in the UI, it seems strange that this is missing.

**Comment by JorgenLindell** [comment]
@lordofhyphens: Yes,from an UI standpoint it would probably be most logical to implement it on the Filament settings tab, possibly by making it possible to have multiple filaments, but then you also need be able to assign filaments to specific extruders. That could of course be an attribute on the filament.

**Comment by lordofhyphens** [comment]
As far as I am aware you can already assign filament  to extruders.

**Comment by Patola** [comment]
Yes, @lordofhyphens, and that's what I did in my example. That's why I am confused by @JorgenLindell 's request. Are you asking for a feature of the quite new interactive USB interface of slic3r? My G-Code sample had one temperature (240°C) on the first extruder, another one (220°C) on the second one, did you notice it, Jorgen?

I am attaching a screenshot of what I did for completeness. 
![slic3r-dois-filamentos](https://cloud.githubusercontent.com/assets/2991620/21296470/a9888ed4-c553-11e6-8066-e389fe8abf25.png)

**Comment by JorgenLindell** [comment]
Well, of course you can, by assigning things to an extruder, but, since there can only be one filament defined, conceptually you don't assign filaments, as there is only one filament setting, but you can have multiple extruders defined. 

What I am proposing here is that you don't assign extruders to things, but filaments. Then you assign the different filaments to different extruders.

That would make it possible to have a temperature setting on each filament. And I think it might be a more logical workflow.

**Comment by lordofhyphens** [comment]
There is a separate filament setting right there for each extruder. I am
confused.

**Comment by JorgenLindell** [comment]
Well, not really.

(I am now looking at 1.2.9, and checking if it looks the same in 1.3.0-dev)

You have the "Printer settings" tab, where there is an entry for each extruder, but there you can't select filaments, just some other settings. Temp is not among them

Then there is the "Filament settings" tab, where you have one Filament setting only, and for this filament you can set temperature. But there is only one.

Then in "Print settings" tab, you can select which extruder to be used for different things. And you can select extruder per object.

But there is no place to set different temperatures on different extruders.

Most logical would be to have the possibility to define more than one filament in "Filament settings", including temp. 

But I would be happy with the possibility to set temp per extruder in "Printer settings" as an alternative.

**Comment by Patola** [comment]
You can select different filament for different extruders on the 'plater'
tab. Did you see my screenshot?

**Comment by JorgenLindell** [comment]
@Patola : Yes, I also mentioned that "You can select extruder per object". It still does not let me set different temperatures.

**Comment by Patola** [comment]
No. It does let you select extruder per object if you use the individual
object settings. That's not what I am talking about. Look at the right
side. There are four pull-down menus, one for printer, one for print
settings and _two_ for the extruders. I selected ABS for the first extruder
(hence, 240C) and PLA for the second one (hence, 220C). So you have it,
each extruder has a different temperature. I have been repeating this over
and over.

**Comment by JorgenLindell** [comment]
OK, 
I think I get your point there. There need to be one setting file per filament. I hadn't understood that feature fully, my bad.

But how does that work if all my objects for example is ABS, and I want to print supports with PHA that print in a lower temp? There is no simple way that can be set in the UI, is there?

**Comment by JorgenLindell** [comment]
OK, now I finally understood that the dropdowns on the plater tab actually is to set filament per extruder.
That should solve my issue, I suppose.

Then my issue with this is that it is not at all obvious from the UI that this is the case. The text for these dropdowns should probably have been Extruder 1, Extruder 2 etc, instead of Filament, in the case where there ar more than one extruder defined.

In that case, I would have understood from start... :)

**Comment by Patola** [comment]
It is possible, you just load all stls then go to print settings ->
multiple extruders -> support material/raft/skirt extruder and set it to
"2".
On Dec 18, 2016 19:51, "JorgenLindell" <notifications@github.com> wrote:

OK,
I think I get your point there. There need to be one setting file per
filament. I hadn't understood that feature fully, my bad.

But how does that work if all my objects for example is ABS, and I want to
print supports with PHA that print in a lower temp? There is no simple way
that can be set in the UI, is there?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/alexrj/Slic3r/issues/3626#issuecomment-267853055>, or mute
the thread

**Comment by JorgenLindell** [comment]
By the way, thanks for educating a beginner user.

**Comment by Patola** [comment]
You're welcome. :)

**Comment by lordofhyphens** [comment]
I will look into at least extending the drop down tooltip to indicate that
they are in order.
