### ISSUE TITLE
bridges start over the void if seam is "random

### ISSUE THREAD

**Issue by djdelorie** [alexrj/Slic3r#3629]
### Version
1.2.9-579-g12165c7

### Operating system type + version
Fedora 24 x86-64

### Behavior
If seams are set to "random" bridges can start in the middle of the bridge.

See enclosed bridge-bug.stl and config.ini

Attached zip file has config.ini, scad, stl, and gcode, as well as a screenshot from gcode analyzer (gcode.ws)

The screenshot shows the bridging layer, with start/stop points between the supports instead of at them.

[bridge-bug.zip](https://github.com/alexrj/Slic3r/files/662758/bridge-bug.zip)

**Comment by lordofhyphens** [comment]
![image](https://cloud.githubusercontent.com/assets/31754/24343699/6eaf2b38-128d-11e7-9af1-feb0085b31c0.png) 
![image](https://cloud.githubusercontent.com/assets/31754/24343730/9e9f328e-128d-11e7-8811-9c6718534d5b.png)

Looks fixed to me.
