### ISSUE TITLE
[1.3.0-dev] Wrong object placement in ported _slice_region()

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#3632]
### Version
32fdd4d

### Operating system type + version
Arch Linux

### Behavior
Both _3D/2D_ views in plater shows the correct position of objects in the bed plate, but _Preview/Layers_ tabs doesn't.

![captura de pantalla_2016-12-21_10-36-14](https://cloud.githubusercontent.com/assets/288246/21384666/ca196db6-c76b-11e6-929c-df2763eda6c1.png)
![captura de pantalla_2016-12-21_10-36-29](https://cloud.githubusercontent.com/assets/288246/21384667/ca19a9e8-c76b-11e6-8834-331b44362046.png)
![captura de pantalla_2016-12-21_10-37-35](https://cloud.githubusercontent.com/assets/288246/21384668/ca1a9862-c76b-11e6-812c-09a26dc001dc.png)
![captura de pantalla_2016-12-21_10-44-13](https://cloud.githubusercontent.com/assets/288246/21384669/ca1ae60a-c76b-11e6-85c7-8231b4db6e90.png)

**Comment by alexrj** [comment]
Sorry.  Shoud be fixed now.

**Comment by xoan** [comment]
Please, don't say _sorry_ ;)

**Comment by alexrj** [comment]
:-))))
