### ISSUE TITLE
[1.3.0-dev] Object disappears from 2D view when reload from disk

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#3634]
### Version
Current master: 475f9d4

### Operating system type + version
Arch Linux

### Behavior
When click on «Reload from Disk», object in 2D view disappears. You can view how the object shifts to somewhere if you are in the 2D view.

If object is selected from the list view or from the 3D view, and it is rotated or any other transformation, then appears again.

**Comment by alexrj** [comment]
Oh, thank you. Fixed.
