### ISSUE TITLE
First layer travel speed

### ISSUE THREAD

**Issue by claell** [alexrj/Slic3r#3638]
There does not seem to be an option to set a special travel speed for the first layer.
Currently I have set a travel speed of 150mm/s and I fear that it is dragging the filament from the bottom at this speed like described in https://ultimaker.com/en/community/8316-suggestion-bottom-layer-travel-speed

I am pretty new to 3d printing and have adhesion problems unrelated to the travel speed, so I am not sure, whether this is really needed.

**Comment by alexrj** [comment]
Travel speed should just be the fastest your machine can do. There's not advantage in slower travel speed.

**Comment by claell** [comment]
So you say the problem with dragged away filament is not there or caused by a bad machine setup?

**Comment by lordofhyphens** [comment]
Usually, yes.

**Comment by claell** [comment]
Alright. So then I will close this.

**Comment by alexrj** [comment]
Dragged away filament means bad adhesion. Even if you somehow managed to prevent it from being dragged away, you'd have other issues related to bad adhesion. So raise your temperatures, clean build plate etc.
