### ISSUE TITLE
Errors when slicing 3D Benchy

### ISSUE THREAD

**Issue by brrmatteo** [alexrj/Slic3r#3641]
### Version
_1.2.9 x64 win_

### Operating system type + version
Windows 7 Ultimate 64bit 

Hello, when i try to slice 3DBenchy (.stl attached), in "Preview" i got a huge error (.jpg attached) of slicing and the result is a print with this error.

### Error screenshot:
![slicing error](https://cloud.githubusercontent.com/assets/5727045/21555660/62301bae-ce1a-11e6-8ed1-b9fb7ca49277.JPG)

### How model should be:
![correct 3d model](https://cloud.githubusercontent.com/assets/5727045/21555664/6d14a260-ce1a-11e6-97a8-c0196f086dcb.JPG)

### Config file:
[config.zip](https://github.com/alexrj/Slic3r/files/677923/config.zip)

### .stl file
[3DBenchy_-_Multi-part_-_Complete_17_shells_-_3DBenchy.com.zip](https://github.com/alexrj/Slic3r/files/677918/3DBenchy_-_Multi-part_-_Complete_17_shells_-_3DBenchy.com.zip)

**Comment by lordofhyphens** [comment]
Yeah that model has 522557 "repaired" errors for manifoldness. Ergo, trust
nothing about it to work. At all.

The basic 3DBenchy.stl works fine on 1.3.0-dev.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
If you see issues with the model and it's being reported as manifold, post and I'll reopen.
