### ISSUE TITLE
Consider moving retraction settings to Filament Settings

### ISSUE THREAD

**Issue by jammi** [alexrj/Slic3r#3643]
Usability-wise, I'd like the retraction length setting to be a part of the filament profile, since different filaments require different retraction length due to stringing.

**Comment by Patola** [comment]
I agree with you opinion. It won't help if you use firmware retraction though.

**Comment by VBen** [comment]
perhaps a custom gcode per filament can be used to setup the firmware retraction

**Comment by bubnikv** [comment]
Maybe a general way to override printer settings by filament settings would
be useful. At the prusa3d fork I have added a limit for a per filament
maximum volumetric extrusion rate, useful for multi material printing. I
can imagine a user interface similar to the object settings to add new
attributes to a filament.

**Comment by lordofhyphens** [comment]
I've been thinking about override hierarchies myself (currently the idea for me is print -> filament -> printer for something that is shared), either for custom gcode or certain configurations that can logically be in different places.

Reusing the override interface makes some sense, but would require more refactoring to get them to save properly with the hierarchy.

**Comment by alexrj** [comment]
It is now possible to override Retraction settings from Filament profiles :) Enjoy!

![schermata 2017-05-16 alle 23 27 03](https://cloud.githubusercontent.com/assets/594957/26129121/43ebd34a-3a8f-11e7-89ee-b8e5dc02c568.png)

**Comment by hoegge** [comment]
Any chance getting this implemented in Slic3r PE too?

**Comment by lordofhyphens** [comment]
@hoegge ask in slic3r PE issue tracker.
