### ISSUE TITLE
infill-where-needed crashes Slic3r

### ISSUE THREAD

**Issue by g3gg0** [alexrj/Slic3r#3648]
### Version
origin/master 16df4df8f87cb035528f4447a1a21ac79eb2e1af

### Operating system type + version
Windows 10 x64, 
perl 5, version 24, subversion 0 (v5.24.0) built for MSWin32-x86-multi-thread-64int

### Behavior
* load attached config
* add model from http://www.thingiverse.com/download:1156927 to buildplate
* slicer crashes with:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

#### STL/Config (.ZIP) where problem occurs
[3648.zip](https://github.com/alexrj/Slic3r/files/681304/3648.zip)

**Comment by lordofhyphens** [comment]
You need to put the ini file in a zip archive to upload it.

**Comment by lordofhyphens** [comment]
Turn off background processing for starters, see if that avoids the crash. I can't reproduce on Linux :/

**Comment by lordofhyphens** [comment]
I can't reproduce on my development Win32 system, same Perl version. I suspect it's one of the libraries on your system.

**Comment by lordofhyphens** [comment]
![image](https://cloud.githubusercontent.com/assets/31754/21594947/36f372ca-d0ee-11e6-8d2c-075fd1260d95.png)

**Comment by g3gg0** [comment]
thanks for testing. how can i do e.g. a backtrace to find out whats causing the trouble?

about the .zip: already packed a zip with .stl and .ini but that failed to upload.

**Comment by lordofhyphens** [comment]
Well nevermind, I just did manage to reproduce :D

**Comment by g3gg0** [comment]
glad to hear :D

**Comment by lordofhyphens** [comment]
It's in the infill generation, specifically "infill only where needed". Turn that off as a workaround.

**Comment by g3gg0** [comment]
thanks!

**Comment by g3gg0** [comment]
argh, misclicked. "close and comment" is not cancel...

**Comment by lordofhyphens** [comment]
I'm not seeing the bad_alloc exception on my runs (could be because I'm running through powershell). Infill was recently rewritten by @bubnikv and then revised by @alexrj.

**Comment by g3gg0** [comment]
can confirm that it depends how you start slic3r.pl
when starting from cmd.exe, it shows the error.

**Comment by lordofhyphens** [comment]
I just ran it via command line, so it's not the GUI crashing. I wonder if it's a stack thing or if it's just a win32 thing (not 64bit). I edited your post to put an upload of the files.

**Comment by bubnikv** [comment]
A "bad alloc" exception means you most likely ran out of the process
virtual space. A 32bit process on Windows can access only the lower 2GB of
a virtual address space, which is shared by all threads of a process and
every thread gets some stack space reserved. The virtual memory runs out
very quickly if too many threads get instantiated. Just use the process
explorer from sysinternals (now owned by Microsoft) to count the allocated
threads and to inspect their memory allocations, namely the reserved stack.
Often the application itself could allocate just around 1.2GB for itself
because of all the thread stacks reserved.

One can toggle one bit in the perl.exe header to tell the operating system
that the application is "large space aware", which then lets the process
use 3GB of virtual memory instead of just 2GB. This makes often a huge
difference. But one is better off to run a 64bit application on a 64bit
system with enough of physical RAM.

By the way, the 3D print path preview in Slic3r is a memory hog, it
requires around 3-4x more memory than just the slicing and G-code
generation. Instead of generating a list of triangles and quads, one shall
generate triangle and quad strips to reduce memory footprint.

**Comment by lordofhyphens** [comment]
@bubnikv I was able to reproduce the problem on Linux x64, error message
there was a corrupted/double free.

`*** Error in `perl': double free or corruption (fasttop):
0x00007fc854a33e00 ***`

I kept an eye on the process memory usage using task manager and it only
reached around ~160MB before crashing.

It also doesn't crash if "Only infill where needed" is unchecked.

backtrace:
````
#0  0x00007fc884012067 in __GI_raise (sig=sig@entry=6) at
../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fc884013448 in __GI_abort () at abort.c:89
#2  0x00007fc8840501b4 in __libc_message (do_abort=do_abort@entry=1,
    fmt=fmt@entry=0x7fc884145530 "*** Error in `%s': %s: 0x%s ***\n") at
../sysdeps/posix/libc_fatal.c:175
#3  0x00007fc88405598e in malloc_printerr (action=1,
    str=0x7fc884145718 "double free or corruption (fasttop)",
ptr=<optimized out>) at malloc.c:4996
#4  0x00007fc884056696 in _int_free (av=<optimized out>, p=<optimized out>,
have_lock=0) at malloc.c:3840
#5  0x00007fc882a883e6 in deallocate (this=<optimized out>, __p=<optimized
out>)
    at /usr/include/c++/4.9/ext/new_allocator.h:110
#6  deallocate (__a=..., __n=<optimized out>, __p=<optimized out>)
    at /usr/include/c++/4.9/ext/alloc_traits.h:185
#7  _M_deallocate (this=<optimized out>, __n=<optimized out>,
__p=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_vector.h:178
#8  ~_Vector_base (this=0x7fc854a32e38, __in_chrg=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_vector.h:160
#9  ~vector (this=0x7fc854a32e38, __in_chrg=<optimized out>) at
/usr/include/c++/4.9/bits/stl_vector.h:425
#10 ~IntersectionPoint (this=0x7fc854a32e08, __in_chrg=<optimized out>)
    at src/libslic3r/Fill/FillRectilinear.hpp:26
#11 ~pair (this=0x7fc854a32e00, __in_chrg=<optimized out>) at
/usr/include/c++/4.9/bits/stl_pair.h:96
#12 destroy (this=<optimized out>, __p=0x7fc854a32e00) at
/usr/include/c++/4.9/ext/new_allocator.h:133
#13 _M_destroy_node (this=0x7fc854a26e88, __p=0x7fc854a32de0) at
/usr/include/c++/4.9/bits/stl_tree.h:409
#14 std::_Rb_tree<long, std::pair<long const,
Slic3r::FillRectilinear::IntersectionPoint>, std::_Select1st<std::pair<long
const, Slic3r::FillRectilinear::IntersectionPoint> >, std::less<long>,
std::allocator<std::pair<long const,
Slic3r::FillRectilinear::IntersectionPoint> > >::_M_erase_aux (
    this=this@entry=0x7fc854a26e88, __position=..., __position@entry=...)
    at /usr/include/c++/4.9/bits/stl_tree.h:1867
#15 0x00007fc882a86f4a in erase (__position=..., this=0x7fc854a26e88)
    at /usr/include/c++/4.9/bits/stl_tree.h:874
#16 erase (__position=..., this=0x7fc854a26e88) at
/usr/include/c++/4.9/bits/stl_map.h:746
#17 Slic3r::FillRectilinear::_fill_single_direction
(this=this@entry=0x7fc854a240f0,
expolygon=...,
    direction=..., x_shift=x_shift@entry=0, out=out@entry=0x7fc85effcb00)
    at src/libslic3r/Fill/FillRectilinear.cpp:337
#18 0x00007fc882a87368 in Slic3r::FillRectilinear::_fill_surface_single
(this=this@entry=0x7fc854a240f0,
    thickness_layers=<optimized out>, direction=..., expolygon=...,
out=out@entry=0x7fc85effcb00)
    at src/libslic3r/Fill/FillRectilinear.cpp:398
#19 0x00007fc882a44826 in Slic3r::Fill::fill_surface (this=0x7fc854a240f0,
surface=...)
    at src/libslic3r/Fill/Fill.cpp:68
#20 0x00007fc882a7a953 in Slic3r::LayerRegion::make_fill
(this=0x7fc830196680)
    at src/libslic3r/LayerRegionFill.cpp:238
#21 0x00007fc8829d6484 in Slic3r::Layer::make_fills (this=0x7fc828001dc0)
at src/libslic3r/Layer.cpp:241
#22 0x00007fc882abf149 in operator() (a0=0x7fc828001dc0,
this=0x7fc85effced0)
    at /usr/include/boost/function/function_template.hpp:767
#23 Slic3r::_parallelize_do<Slic3r::Layer*>(std::queue<Slic3r::Layer*,
std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*,
boost::mutex*, boost::function<void (Slic3r::Layer*)>)
(queue=0x7fc85e7fba50,
    queue_mutex=0x7fc85e7fb6e0, func=...) at src/libslic3r/libslic3r.h:85
#24 0x00007fc882abf069 in operator()<void (*)(std::queue<Slic3r::Layer*>*,
boost::mutex*, boost::function<void(Slic3r::Layer*)>), boost::_bi::list0> (
    f=@0x7fc8309ba788: 0x7fc882abf0d0
<Slic3r::_parallelize_do<Slic3r::Layer*>(std::queue<Slic3r::Layer*,
std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*,
boost::mutex*, boost::function<void (Slic3r::Layer*)>)>, a=<synthetic
pointer>, this=0x7fc8309ba790) at /usr/include/boost/bind/bind.hpp:392
#25 operator() (this=0x7fc8309ba788) at
/usr/include/boost/bind/bind_template.hpp:20
#26 boost::detail::thread_data<boost::_bi::bind_t<void, void
(*)(std::queue<Slic3r::Layer*, std::deque<Slic3r::Layer*,
std::allocator<Slic3r::Layer*> > >*, boost::mutex*, boost::function<void
(Slic3r::Layer*)>),
boost::_bi::list3<boost::_bi::value<std::queue<Slic3r::Layer*,
std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*>,
boost::_bi::value<boost::mutex*>, boost::_bi::value<boost::function<void
(Slic3r::Layer*)> > > > >::run() (this=0x7fc8309ba5d0) at
/usr/include/boost/thread/detail/thread.hpp:117
#27 0x00007fc88207daea in ?? () from
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
#28 0x00007fc8843900a4 in start_thread (arg=0x7fc85effd700) at
pthread_create.c:309
#29 0x00007fc8840c587d in clone () at
../sysdeps/unix/sysv/linux/x86_64/clone.S:111
````

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
@bubnikv I was able to reproduce the problem on Linux x64, error message
there was a corrupted/double free.

`*** Error in 'perl': double free or corruption (fasttop):
0x00007fc854a33e00 ***`

I kept an eye on the process memory usage using task manager and it only
reached around ~160MB before crashing.

It also doesn't crash if "Only infill where needed" is unchecked.

backtrace:
````
#0  0x00007fc884012067 in __GI_raise (sig=sig@entry=6) at
../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fc884013448 in __GI_abort () at abort.c:89
#2  0x00007fc8840501b4 in __libc_message (do_abort=do_abort@entry=1,
    fmt=fmt@entry=0x7fc884145530 "*** Error in `%s': %s: 0x%s ***\n") at
../sysdeps/posix/libc_fatal.c:175
#3  0x00007fc88405598e in malloc_printerr (action=1,
    str=0x7fc884145718 "double free or corruption (fasttop)",
ptr=<optimized out>) at malloc.c:4996
#4  0x00007fc884056696 in _int_free (av=<optimized out>, p=<optimized out>,
have_lock=0) at malloc.c:3840
#5  0x00007fc882a883e6 in deallocate (this=<optimized out>, __p=<optimized
out>)
    at /usr/include/c++/4.9/ext/new_allocator.h:110
#6  deallocate (__a=..., __n=<optimized out>, __p=<optimized out>)
    at /usr/include/c++/4.9/ext/alloc_traits.h:185
#7  _M_deallocate (this=<optimized out>, __n=<optimized out>,
__p=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_vector.h:178
#8  ~_Vector_base (this=0x7fc854a32e38, __in_chrg=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_vector.h:160
#9  ~vector (this=0x7fc854a32e38, __in_chrg=<optimized out>) at
/usr/include/c++/4.9/bits/stl_vector.h:425
#10 ~IntersectionPoint (this=0x7fc854a32e08, __in_chrg=<optimized out>)
    at src/libslic3r/Fill/FillRectilinear.hpp:26
#11 ~pair (this=0x7fc854a32e00, __in_chrg=<optimized out>) at
/usr/include/c++/4.9/bits/stl_pair.h:96
#12 destroy (this=<optimized out>, __p=0x7fc854a32e00) at
/usr/include/c++/4.9/ext/new_allocator.h:133
#13 _M_destroy_node (this=0x7fc854a26e88, __p=0x7fc854a32de0) at
/usr/include/c++/4.9/bits/stl_tree.h:409
#14 std::_Rb_tree<long, std::pair<long const,
Slic3r::FillRectilinear::IntersectionPoint>, std::_Select1st<std::pair<long
const, Slic3r::FillRectilinear::IntersectionPoint> >, std::less<long>,
std::allocator<std::pair<long const,
Slic3r::FillRectilinear::IntersectionPoint> > >::_M_erase_aux (
    this=this@entry=0x7fc854a26e88, __position=..., __position@entry=...)
    at /usr/include/c++/4.9/bits/stl_tree.h:1867
#15 0x00007fc882a86f4a in erase (__position=..., this=0x7fc854a26e88)
    at /usr/include/c++/4.9/bits/stl_tree.h:874
#16 erase (__position=..., this=0x7fc854a26e88) at
/usr/include/c++/4.9/bits/stl_map.h:746
#17 Slic3r::FillRectilinear::_fill_single_direction
(this=this@entry=0x7fc854a240f0,
expolygon=...,
    direction=..., x_shift=x_shift@entry=0, out=out@entry=0x7fc85effcb00)
    at src/libslic3r/Fill/FillRectilinear.cpp:337
#18 0x00007fc882a87368 in Slic3r::FillRectilinear::_fill_surface_single
(this=this@entry=0x7fc854a240f0,
    thickness_layers=<optimized out>, direction=..., expolygon=...,
out=out@entry=0x7fc85effcb00)
    at src/libslic3r/Fill/FillRectilinear.cpp:398
#19 0x00007fc882a44826 in Slic3r::Fill::fill_surface (this=0x7fc854a240f0,
surface=...)
    at src/libslic3r/Fill/Fill.cpp:68
#20 0x00007fc882a7a953 in Slic3r::LayerRegion::make_fill
(this=0x7fc830196680)
    at src/libslic3r/LayerRegionFill.cpp:238
#21 0x00007fc8829d6484 in Slic3r::Layer::make_fills (this=0x7fc828001dc0)
at src/libslic3r/Layer.cpp:241
#22 0x00007fc882abf149 in operator() (a0=0x7fc828001dc0,
this=0x7fc85effced0)
    at /usr/include/boost/function/function_template.hpp:767
#23 Slic3r::_parallelize_do<Slic3r::Layer*>(std::queue<Slic3r::Layer*,
std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*,
boost::mutex*, boost::function<void (Slic3r::Layer*)>)
(queue=0x7fc85e7fba50,
    queue_mutex=0x7fc85e7fb6e0, func=...) at src/libslic3r/libslic3r.h:85
#24 0x00007fc882abf069 in operator()<void (*)(std::queue<Slic3r::Layer*>*,
boost::mutex*, boost::function<void(Slic3r::Layer*)>), boost::_bi::list0> (
    f=@0x7fc8309ba788: 0x7fc882abf0d0
<Slic3r::_parallelize_do<Slic3r::Layer*>(std::queue<Slic3r::Layer*,
std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*,
boost::mutex*, boost::function<void (Slic3r::Layer*)>)>, a=<synthetic
pointer>, this=0x7fc8309ba790) at /usr/include/boost/bind/bind.hpp:392
#25 operator() (this=0x7fc8309ba788) at
/usr/include/boost/bind/bind_template.hpp:20
#26 boost::detail::thread_data<boost::_bi::bind_t<void, void
(*)(std::queue<Slic3r::Layer*, std::deque<Slic3r::Layer*,
std::allocator<Slic3r::Layer*> > >*, boost::mutex*, boost::function<void
(Slic3r::Layer*)>),
boost::_bi::list3<boost::_bi::value<std::queue<Slic3r::Layer*,
std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*>,
boost::_bi::value<boost::mutex*>, boost::_bi::value<boost::function<void
(Slic3r::Layer*)> > > > >::run() (this=0x7fc8309ba5d0) at
/usr/include/boost/thread/detail/thread.hpp:117
#27 0x00007fc88207daea in ?? () from
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
#28 0x00007fc8843900a4 in start_thread (arg=0x7fc85effd700) at
pthread_create.c:309
#29 0x00007fc8840c587d in clone () at
../sysdeps/unix/sysv/linux/x86_64/clone.S:111
````

**Comment by Tinchus2009** [comment]
I have been trying to see any pattern i the crashes. As I reported earlier, haveing the option checked sometimes crashes slic3r sometimes it doesn't. And I discovered this: the crash happens always when the infill is being calculated. BUT, it seems that the crash is not really produced by this option but something related to, MAY BE, calculations where no infill is made???? Because the real option that produces a crash, 100% of the times is when I set infill to 0%.
Setting infill to 0% produces a crash 100% of the times.

**Comment by lordofhyphens** [comment]
@Tinchus2009 so does 100% infill.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by Salandora** [comment]
this problem also occurs with combine infill every x layers with x > 1.
And also depends on the extrusion width, had a model that slices well with everything set to 0.53 and crashes with 0.5, while nozzle diameter is 0.6.

I'm sorry I can't provide the stl file.
I hope this information helps in locating the bug.

**Comment by g3gg0** [comment]
it crashe with no other model for me with these settings.

only the provided one crashed till today.

**Comment by g3gg0** [comment]
did you do a run with valgrind yet?

**Comment by lordofhyphens** [comment]
You are welcome to give it a shot ;), I haven't tried to run valgrind on a
static library  (libslic3r).

**Comment by g3gg0** [comment]
<- windows only :(

**Comment by Patola** [comment]
I see that there has been a lot of activity on this bug report, but I reported the same issue on Linux 11 days prior to this one. Should this one be marked as duplicate, or my own bug report, issue #3637 be marked as such?

**Comment by lordofhyphens** [comment]
They are both linked, up to you at this point if you want to close yours or
not.

My personal preference is to use the one that either has more info in it or
is older.

**Comment by Tinchus2009** [comment]
I just builted the latest dev version: 1.2.9-618-g1f920dc

I have tested this problem with different models, setting infill to 0% and to 100% is no longer causeing problems. But when activating "only infill where is nedded" I got some crashes, even with the same model. Teh same model with the same infill % sometimes crashed when activateing the option sometimes it didnt, no change at all between the test regarding the configuration. The only different thing I can look as "suspicious" is that the times it crashed, I was previously changeing parameters and slicein to test. After some succesfull slices I went back and activated the option and that times it crashed, so from my poor codeing habilities, could it the problem be that there is some variable not being cleared up that is causeing the problem?

**Comment by lordofhyphens** [comment]
Could be related, did you try with a full restart of Slic3r between tests
to check that possibility  (that it might be something incorrectly set
during a restarted slice that wouldn't be in a clean system)?

**Comment by Tinchus2009** [comment]
yes. tht is exactly wht im observeing. when it crashes, if i restart
slic3r, with no change un config at all, same object, the slice is
perfectly done

**Comment by alexrj** [comment]
Fixed, thank you for the report.
