### ISSUE TITLE
First layer height used above support layers

### ISSUE THREAD

**Issue by dwillmore** [alexrj/Slic3r#3649]
### Version
1.3.0-dev 1.2.9-507-g3a3b24e
### Operating system type + version
Fedora 24 current
### Behavior
In printing a knight from [http://www.thingiverse.com/thing:585218], I had my first layer height set to 0.3mm and my layer height to 0.1mm.  The head of the horse overhangs and needed support.  So, I enabled that.  To make sure it was good, I zoomed in on the area and noticed something odd.  It appears that the first layer of the model above the support was printed at the first layer height.  I would have expected it to be at the normal layer height as first layer height is only intended to improve bed adhesion.
![screenshot_2017-01-02_13-38-09](https://cloud.githubusercontent.com/assets/10374140/21594646/fe64224c-d0f2-11e6-92c1-3b8b23977042.png)
[config.zip](https://github.com/alexrj/Slic3r/files/681273/config.zip)

I believe this is a bug.

#### STL/Config (.ZIP) where problem occurs
See the link to thingiverse above.

**Comment by lordofhyphens** [comment]
That's bridging flow actually, so far as I can tell.
first layer 0.1
![fl 0 1](https://cloud.githubusercontent.com/assets/31754/21594794/404fac6e-d0ec-11e6-95d9-5945886cfcd6.png)

first layer 1.2
![fl 1 2](https://cloud.githubusercontent.com/assets/31754/21594793/404e9932-d0ec-11e6-8aad-15c4b290e1ce.png)

2x bridge flow
![bridge2](https://cloud.githubusercontent.com/assets/31754/21594791/404e2f7e-d0ec-11e6-8ddd-b565f1e0aa87.png)

50% bridge flow
![bridge0 5](https://cloud.githubusercontent.com/assets/31754/21594792/404e5a62-d0ec-11e6-89cd-424f43e182a8.png)

**Comment by lordofhyphens** [comment]
Those layers are being printed with bridging flow, which is generally what you expect since there's a gap there, not the first layer.

If you can think of a reason we shouldn't be using bridging flow for this I'll reopen ;)
