### ISSUE TITLE
[Bug] Slic3r crashing when setting bed size

### ISSUE THREAD

**Issue by forReason** [alexrj/Slic3r#3681]
### Version
lordofhyphens / Slic3r / Slic3r_Branches / 1.3.0-slice_statistics-337

precompiled version

### Operating system type + version
Windows 10

### Behavior
Slicer will crash when setting a different bedsize. I think it is a null error with live preview.

steps to reproduce the problem:
1. Open slicer
2. Go to printer settings
3. Bed size
4. Delete the first number of the preset 200 in orter to type another number like for example 300 -> there will stand 00 - Slicer crashes

The Crash will not ocurr when writing 3200 and then delete the second number

![slic3r bedsize bug](https://cloud.githubusercontent.com/assets/12736950/22244177/d1a47b64-e22a-11e6-867b-9104f83326b1.gif)

**Comment by lordofhyphens** [comment]
Good catch. The actual bug is that the input validation code doesn't properly type munge if you give it "00" or "0000" or similar.

**Comment by forReason** [comment]
Please close the issue when Solved. for some reasons I cant run Slic3r from the branch.

Also this may be a bad question but is there any outlook on when Slic3r 1.3 will get released? Because its now 2 year since the last release and I love the new features like instant re-slicing and the preview and so on.

**Comment by lordofhyphens** [comment]
It will be closed when the fix is merged.

**Comment by lordofhyphens** [comment]
@forReason I did test it before I committed. 

https://bintray.com/lordofhyphens/Slic3r/Slic3r_Branches/1.3.0-fix_3681_zero_bed_shape-338 is the branch with the fix. The slice_statistics branch is a placeholder until that gets merged and so will not see this fix.
