### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by artbody** [alexrj/Slic3r#3687]
### Behaviour
since today each layer is the same hight. Printing a fine structured  surface  needs a lot of time

### this is a new feature request

this idea will speeding up print time 2 or 3 times
if we print with layer hight i.e. 0,06 mm  this needs a lot of time but gives a nice surface
so my idea was to print the wall zone with 0,06 mm 3 Layers in hight and i.e. 3 lines width and then print one Layer with 0,18mm
ooo  ------------------------- ooo
ooo  ||||||||||||||||||||||||| ooo
ooo  ------------------------- ooo
o = 0,06mm
| =  0,18mm

> wallsubdivide by 2x2 3x3 up to  6x6 

i'm building a printer (based on Prusa i3) with 90cm x 90cm x 40cm printing area.
so in this dimension such a feature will increase printing speed dramatically

**Comment by forReason** [comment]
please update your title like
`[Feature Request] - Layerhights`

**Comment by forReason** [comment]
I guess can be closed

You have to activate `Mode: Expert` Under `File/Preferences`
![combined infill](https://cloud.githubusercontent.com/assets/12736950/22333951/e538df8a-e3d8-11e6-8559-ac023fdfd32e.PNG)

**Comment by lordofhyphens** [comment]
See both combined infill setting and the adaptive slicing pull request by @platsch.

Closing.
