### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by baxerus** [alexrj/Slic3r#3694]
Add this:
"Researchers design one of the strongest, lightest materials known
Porous, 3-D forms of graphene developed at MIT can be 10 times as strong as steel but much lighter."
https://news.mit.edu/2017/3-d-graphene-strongest-lightest-materials-0106
http://advances.sciencemag.org/content/3/1/e1601536
as 3D infill pattern.

**Comment by xoan** [comment]
Duplicated: #3666

**Comment by baxerus** [comment]
Sorry. Too late
