### ISSUE TITLE
Slic3r version MacOS pixelation in iMac 5K

### ISSUE THREAD

**Issue by litris** [alexrj/Slic3r#3695]
### Version
1.2.9

### Operating system type + version
macOS Sierra 10.12.3
iMac 27" 5K Late 2015 m395

### Behavior
In an imac 5K Slic3r you see a very low resolution it seems an erroneous scaling you see pixelated text without resolution.

Attached is a screenshot in window mode if wider is pixela more.

Any solution?

Thank you.
<img width="762" alt="captura de pantalla 2017-01-31 a las 11 18 54" src="https://cloud.githubusercontent.com/assets/2809283/22461027/f6a5af82-e7a7-11e6-90a5-da4839002b34.png">
<img width="604" alt="captura de pantalla 2017-01-31 a las 11 27 32" src="https://cloud.githubusercontent.com/assets/2809283/22461131/548dc94a-e7a8-11e6-9a12-aec4641fc438.png">

**Comment by bubnikv** [comment]
See https://github.com/prusa3d/Slic3r/issues/97 for resolution.

**Comment by litris** [comment]
It does not work for me :-(

I pasted the same text as you show and the text is pixelated in an imac 27 "5k late 2015.

**Comment by alexrj** [comment]
This should be fixed as of now. Could you get a fresh automated build at http://dl.slic3r.org/dev/mac/ and confirm it works?  (Just the text, we still have the 16x16 icons)

**Comment by lordofhyphens** [comment]
@litris can you check one of our automated builds to see if this works for you?

**Comment by lordofhyphens** [comment]
We can probably use my hacked wxperl and try 3.1.0 on OSX.

**Comment by litris** [comment]
Sorry for not answering sooner.
Yes! Works perfectly text and menus flout icons remain pixelated.

Thank you.
