### ISSUE TITLE
[Improvement] Filaments manager section

### ISSUE THREAD

**Issue by noisemaker00** [alexrj/Slic3r#3711]
I will be very usefull to have a section to handle different types of filaments (similar to Cura).
To each filament user can set basic info (eg the producer name, color, material, etc) and other info used by the slicer:
- filament diameter
- extrusion multiplier
- temperature hotend/bed

Then user can select current filament from a dropdown list.

This is partially already implemented yet, it will be great to improve that with a simpler view to keep things organized better than now.

**Comment by xoan** [comment]
```File → Preferences → Mode: Expert```

Restart Slic3r and change to ```Filament Settings```.
