### ISSUE TITLE
incompatibility with 3DLabPrint 

### ISSUE THREAD

**Issue by AndKe** [alexrj/Slic3r#3716]
### Version
1.2.9 stable

### Operating system type + version
Ubuntu 16.10

### Behavior
Virually all models build-guide on this site: https://3dlabprint.com
clearly warns agains using Slic3r
like in this PDF,  https://3dlabprint.com/wp-content/uploads/2016/11/Userguide_Me_109_H_F_.pdf

```
universal STL files designed for use with desktop FMD 3d printers and slicer software as
Simplify3D (recommend) CURA or MatterControl (this STLs are not compatible with Slic3r).
```

Is that still the case ? - why is my favorite Slicer the only one to be specifically mentioned as incompatible with those STL's ?

**Comment by lordofhyphens** [comment]
#3523
#3560 

The STLS are not actually valid/solid modelling. Cura resolves the broken model in a different way.
