### ISSUE TITLE
My Slic3r crash when I try to open it

### ISSUE THREAD

**Issue by paulorfmmb** [alexrj/Slic3r#3727]
### Version
Latest stable version merge pull request #3713 

### Operating system type + version
Using Win 10
### Behavior
When I try to open it using the command
perl slic3r.pl
the program opens and crashes immediately.
using when building I get no errors.

**Comment by alexrj** [comment]
Can you try the master branch?
The stable branch is a bit abandoned, and master is much more stable :-)

**Comment by Tinchus2009** [comment]
Im running win 10 64b, I just builted the latest dev version: 1.2.9-677-gf4d73f1

It is working nice

**Comment by alexrj** [comment]
@paulorfmmb, can you confirm the master branch works? Thank you

**Comment by alexrj** [comment]
No answer from @paulorfmmb

**Comment by paulorfmmb** [comment]
Sorry for not responding!!! I was able to make it run using perl 5.18 - 32bits
However I updated my slic3r to use perl 5.24 and now I'm having the same issue. The program closes after I try to open it.

**Comment by lordofhyphens** [comment]
@paulorfmmb Everything has changed. 

Can you check the automatic build first? http://dl.slic3r.org/dev

Then check the wiki again and do a full setup again of perl and boost (as I said, much has changed).

Start slic3r from the command line. It will show you errors that way.

**Comment by lordofhyphens** [comment]
@paulorfmmb FYI #3815

**Comment by paulorfmmb** [comment]
I reinstalled everything and did everything from the beginning like in the wiki. Got same results.

**Comment by lordofhyphens** [comment]
Do the downloads from dl.slic3r.org/dev work?

**Comment by lordofhyphens** [comment]
Try to move your Slic3r directory to somewhere with no spaces in the path
or special characters. Ensure you have updated to the most recent version
with git pull.

Perl should be installed to C:\Strawberry. It also needs to be slic3r-perl.

I would also check command line slicing  (pass a path to the invocation).

**Comment by paulorfmmb** [comment]
slic3r-perl is a directory?

**Comment by lordofhyphens** [comment]
https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-Windows#slic3r-perl
