### ISSUE TITLE
No solid infill when gap width is close to perimeter total width

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#3732]
### Version
1.2.9-637-g62675a2b

### Operating system type + version
Arch Linux 4.4.52-1-lts

### Behavior
In a model with an horizontal gap in the border which width is close to the perimeter total width (perimeter width * num internal perimeters + external perimeter width), there is no solid infill in the previous layers.

The test case has a 1 mm horizontal gap. Print has 2 perimeters and default extrusion width is set to 0.55 mm, so perimeters are 1.10 mm.

Part of sparse infil can be seen in the screenshot.

![captura de pantalla_2017-03-02_08-19-22](https://cloud.githubusercontent.com/assets/288246/23496939/1c40865a-ff21-11e6-9d57-d55736439b50.png)

Here is also the model in which I detect this issue. Gap is ~1 mm (0.999879 mm measured in FreeCAD, but OpenSCAD file is also provided by the author)

* Lego City train track compatible Curved by mtudury: http://www.thingiverse.com/thing:2104338

![captura de pantalla_2017-03-02_08-41-53](https://cloud.githubusercontent.com/assets/288246/23497775/0c831224-ff25-11e6-8fe3-d99616f5e7b3.png)

![captura de pantalla_2017-03-02_08-43-45](https://cloud.githubusercontent.com/assets/288246/23497789/13de3ee0-ff25-11e6-8b8c-7fbefb1bfbf7.png)

Also attached a picture of the print, even it is very subjective.

![img_20170302_085041](https://cloud.githubusercontent.com/assets/288246/23497983/d438f77a-ff25-11e6-9c48-cc7554dbf8a4.jpg)

#### STL/Config (.ZIP) where problem occurs
* [test.stl.zip](https://github.com/alexrj/Slic3r/files/812995/test.stl.zip)
* Config: https://gist.github.com/xoan/ea2768b728b91e4624cdbf575030b3bd

**Comment by lordofhyphens** [comment]
My suspicion here is floating point rounding.

**Comment by alexrj** [comment]
This is more a rendering issue than an actual issue. Did you try to print it?
There's no actual horizontal gap. You can see the layer below because of the sharp way we render the extrusions, which leaves an unrealistic diagonal gap:

![schermata 2017-03-08 alle 13 56 57](https://cloud.githubusercontent.com/assets/594957/23704875/3b532274-0407-11e7-9f57-040913a373f5.png)

When *infill_overlap* is greater than zero (the default is 50%) infill extrusions go slightly beyond the upper layer, so they might become visible in an actual print:

![schermata 2017-03-08 alle 14 00 21](https://cloud.githubusercontent.com/assets/594957/23704942/9a8fbb94-0407-11e7-8915-4d05ac5bae66.png)

Being this an actual or a visualization issue, I agree we should fix it by making solid infill.

**Comment by alexrj** [comment]
To clarify, the actual extrusions look like rectangles ending with semicircumferences, so they are flat on top. We render them with a diamond section for performance reasons, so they have no flat top and these diagonal gaps are visible.

**Comment by xoan** [comment]
Yes, I printed the railtrack you can see in the last attached picture. It has the same dimensions that the test case, and you can see the «dashed» horizontal surface due the rectilinear infill, because the perimeter path is deposited in a non solid (and non continuous) surface.

I know that in an ideal scenario, infill should never been seen from outside, but the real thing is that it is complicated to achieve.

To be safe, a solution could be to have a minimun perimeter overlapping (maybe half of the perimeter extrusion width), and if this overlapping is lower, fire the solid infill routine.

**Comment by alexrj** [comment]
Ah yes, I had even seen the picture yesterday, sorry. I commented without re-reading the post. The diagnosis still applies, as what's visible is caused by the infill overlap.

**Comment by xoan** [comment]
PS. I think I'm using the term «overlap» in a way that is not the correct.

But even ```infill_overlap``` is set to 0%, the effect is still visible due the fact that the perimeter is deposited in a sparse infill, are you agree? :)

**Comment by alexrj** [comment]
Generating solid infill isn't enough, actually, as it's still visible:

![schermata 2017-03-08 alle 14 26 42](https://cloud.githubusercontent.com/assets/594957/23706161/5b4cb2f6-040d-11e7-8de2-12077bd08fb7.png)

So I improved the logic for extra perimeters detection, which was actually supposed to cover these cases. Now a third loop will be added which looks much nicer:

![schermata 2017-03-08 alle 14 38 40](https://cloud.githubusercontent.com/assets/594957/23706236/9e2ae818-040d-11e7-9eb5-e8149f0cbd57.png)

(Note that extra perimeter detection is turned off in the config file you supplied; I recommend to turn it on.)

**Comment by xoan** [comment]
Solid infill is still visible, but the effect is not like if there is not this solid infill.

I think that both solutions can be living together: the default by fixing the issue like in your first capture, but leaving the chance to enable ```extra_perimeters``` if someone need more quality.

BTW, thanks :)

**Comment by alexrj** [comment]
Both solutions needs extra computation. So I prefer to only add the extra perimeters one instead of two...

**Comment by xoan** [comment]
Agreed!

**Comment by xoan** [comment]
Sorry, another test case in which the extra perimeters is not triggered.

![captura de pantalla_2017-04-06_13-33-50](https://cloud.githubusercontent.com/assets/288246/24752354/c7ba0124-1acd-11e7-9683-47ac79d41b6b.png)

[02-battery-bracket-ng.stl.zip](https://github.com/alexrj/Slic3r/files/902387/02-battery-bracket-ng.stl.zip)
