### ISSUE TITLE
Buttons Grey out incorrectly

### ISSUE THREAD

**Issue by thompsbp** [alexrj/Slic3r#3740]
### Version
_Version of Slic3r used goes here_
1.3.0-Dev

_For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_

Unable to do this.

### Operating system type + version
_What OS are you using, and state any version #s_
Windows 7 SP 1

### Behavior
* _Describe the problem_
Buttons grey out incorrectly.
Buttons are still useable and Export STL/GCODE buttons un grey out after use. Positioning buttons remain greyed out after use.

* _Steps needed to reproduce the problem_
Buttons are always greyed out after loading a new STL.

* _Expected Results_
Buttons will only be greyed out when not useable.

* _Actual Results_
Some Buttons are greyed out all the time. Others ungrey after use.

* _Screenshots from __*Slic3r*__ preview are preferred_
http://imgur.com/JRv2EeT

_Is this a new feature request?_
No

**Comment by bubnikv** [comment]
I think this has something to do with the Windows styles, Windows
compatibility settings and the manifest of the application. My impression
is, it is a general wxwidgets issue. I can surely reproduce the issue on my
windows 7 computer. Slic3r behaves similarly on Windows 10, if the exe
wrapper misses a manifest, therefore the compatibility section is missing.

**Comment by lordofhyphens** [comment]
Hm, the only button that I can reproduce the issue with on my (non-development) Win7 system with a recent build is the Arrange button.

**Comment by alexrj** [comment]
I can't reproduce the issue, but the first fix I'd try would be to call `selection_changed()` (the method responsible for enabling/disabling buttons) within a `CallAfter()` callback. wxWidgets often has issues when changing GUI things within events triggered by wxWidgets itself. I'm not sure this applies to the C++ library as well or is specific to wxPerl.

**Comment by gege2b** [comment]
my two cents.

I got the same issue on Windows 10 today (I used 1.2.9 until now)

But even if the buttons are greyed out, they can still be used (and if I remember, using one of them activate all the greyed buttons), at least on my PC

**Comment by bubnikv** [comment]
On Windows 10 it works, if the application has a correct manifest. If you try to run the slic3r through the perl.exe from strawberry, it will be ok. If you do that through the slic3r.exe provided by @lordofhyphens , it may be wrong as it may not contain the necessary manifest. If you run the Slic3r Prusa Edition, it should be fine.

**Comment by lordofhyphens** [comment]
Lower: run by wrapper script. upper: run script through perl5.18.4.exe (same dlls)
![image](https://cloud.githubusercontent.com/assets/31754/24049858/2e9370de-0afb-11e7-8b92-46ee0503ff0e.png)
Yeah, it's something with how the wrapper exe works (I note that it's as what's provided in the prusa3d fork).

**Comment by bubnikv** [comment]
You may use the resource hacker to analyze and replace the manifest.
http://www.angusj.com/resourcehacker/

**Comment by lordofhyphens** [comment]
I'll have to examine what is going on (#thankswindows) and bake whatever changes that need to be made into the build process.

**Comment by bubnikv** [comment]
This solves the behavior on Windows 10, not in Windows 7 IMO.

**Comment by lordofhyphens** [comment]
![image](https://cloud.githubusercontent.com/assets/31754/24074638/b6e89e70-0bda-11e7-9601-e89a4f68dfdf.png)
That's from a Windows 7 system, which is the expected look.
