### ISSUE TITLE
How to arrange multi color STL models

### ISSUE THREAD

**Issue by Massa0815** [alexrj/Slic3r#3753]
### Version
1.2.9

Dual Extrusion

### Operating system type + version
Windows 7

### Behavior
In older Versions there was a Menu item for combining STL FIles to an AMF File. In the actual Version 1.2.9 there is only the posibility to export the actual plate to .amf . But how can i combine two stl without coordinate offset. If i import two stls from a dual colored model, they are not at the correct position. How can i shift them exactly together, Especially in Z direction?

**Comment by alexrj** [comment]
* Add the first part to the plater
* Double click it
* Click on "Load part..." and choose the second part

Voila, you just made a multi-part object. Make sure the two STL files share the same coordinate origin, and they will be automatically aligned.

**Comment by Massa0815** [comment]
Very nice. It works... You saved my Day ;) 
I dint find it in your documentation

**Comment by stuartpb** [comment]
I just tried this, and the parts are still getting added misaligned (Slic3r keeps introducing transforms I can't get rid of).

**Comment by lordofhyphens** [comment]
@Stuartpb are you sure both models have the same reference 0 point?

Turn off auto arrange x/y and add both to the plater manually. If they are misaligned then it's the files.
