### ISSUE TITLE
"No top_infill_pattern in ConfigOptionsGroup config at lib/Slic3r/GUI/OptionsGroup.pm line 369."

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#3761]
Hi all

Using the c93314c windows build available on @lordofhyphens 's bintray (https://bintray.com/lordofhyphens/Slic3r/slic3r_dev/1.3.0-dev-c93314c ), I face this error when launching Slic3r

Seems related to commit 4b4a0c8a5cc7c607fee7680e7c5819d9a697c317 

### Version
c93314c 

### Operating system type + version
Windows 10 x64

### Behavior
mentionned error is shown in console windows, then quit.

config doesn't matter (fresh install)

**Comment by lordofhyphens** [comment]
99% sure this is a build system problem, not a SW issue.

**Comment by lordofhyphens** [comment]
Which I am working on.

**Comment by born2b** [comment]
Hello.
Me, too.

Slic3r-master.2017.03.12.487.e655359 or older
I start it safely.

Slic3r-master.2017.03.12.489.6e42702 or newer
I get an error.

I am sorry that my English composition is not good.

**Comment by lordofhyphens** [comment]
As I said, I know. There is a general build problem on Windows currently.

**Comment by lordofhyphens** [comment]
Locking to avoid a plethora of me too posts.

**Comment by lordofhyphens** [comment]
This is a Windows build issue. I am working in fixing it. Basically Strawberry Perl 5.18 ships a compiler that is too old.

**Comment by lordofhyphens** [comment]
Build server is fixed with a workaround, I will be employing a more permanent fix when I have time.
