### ISSUE TITLE
Slic3R crash in a directory

### ISSUE THREAD

**Issue by Pydo44** [alexrj/Slic3r#3763]
### Version
last one 1,2,9

### Operating system type + version
Mac OS X 10.11.5

### Behavior
I put Slic3r in the application directory and in Sub directory Modelisation

then i launch Slic3r and it crash

if i put only in the application directory it s work

**Comment by lordofhyphens** [comment]
Try the current builds (look at readme.MD for link)

**Comment by alexrj** [comment]
@Pydo44, can you confirm the current 1.3.0-dev builds fix the issue?

**Comment by Pydo44** [comment]
Soory ... but i can found the readme.MD
where i can find it ?

**Comment by lordofhyphens** [comment]
@Pydo44 No, I will not directly link to the newest version at the time of this writing.

1. Click the link that is clearly shown at the top of [Readme.MD](https://github.com/alexrj/Slic3r/blob/master/README.md). 
1. From there, you will see a list of versions, in order from newest to oldest. Click the top one.
1. Click "Files". 
1. Pick the file corresponding to the OSX installer (OSX installers are dmg files).

**Comment by Pydo44** [comment]
hi
the same problem appear
where i can put the failure report

**Comment by Pydo44** [comment]
@lordofhyphens i send you a mail with the report

**Comment by lordofhyphens** [comment]
You can upload .txt files using the github Web interface. Do not directly
email me (or really anyone else) without being requested to ahead of time.

**Comment by lordofhyphens** [comment]
![screenshot_2017-03-17-08-33-37-1](https://cloud.githubusercontent.com/assets/31754/24045298/90533656-0aec-11e7-96fc-3486f2eb9af2.jpg)

**Comment by Pydo44** [comment]
Sure but i don't want put on public web site my private informations

**Comment by lordofhyphens** [comment]
@Pydo44 I also don't have a Mac. Strip out what looks "private", zip it up and post.

**Comment by Pydo44** [comment]
i don't know what is private ....... so .......

**Comment by lordofhyphens** [comment]
https://www.quora.com/Applications-on-my-Mac-crash-often-of-which-a-report-is-sent-to-Apple-Why-do-I-never-hear-back-or-see-updates-of-the-app-to-prevent-such-crashes 
10th entry from https://www.google.com/?q=what+is+private+information+in+an+osx+crash+report

**Comment by alexrj** [comment]
@Pydo44, I was able to reproduce the issue. It's caused by the non-ASCII characters in the directory name (the é in Modélisation).  As a workaround, move it to some other place. I'm working on a fix.

**Comment by alexrj** [comment]
By the way, there's nothing private in a crash dump.

**Comment by alexrj** [comment]
@Pydo44, this should be fixed now.
Can you please download the most recent built at http://dl.slic3r.org/dev/mac/ and confirm it works now?

**Comment by lordofhyphens** [comment]
@Pydo44 Please check to make sure that it is working for you so we can close this issue.

**Comment by lordofhyphens** [comment]
@alexrj was there anything related to #2955 in it?

**Comment by alexrj** [comment]
Yes @lordofhyphens, it was caused by the "Modélisation" directory in application path.

@Pydo44, can you please download the most recent built at http://dl.slic3r.org/dev/mac/ and confirm it works now? Thank you in advance!

**Comment by lordofhyphens** [comment]
````
<keyno> i tried it in /User/me/täst 
<keyno> crashed
````

**Comment by lordofhyphens** [comment]
````
<jammi> LoH|Lenneth: I tested with slic3r in various directories, even one named "täst" now and no issues whatsoever
<LoH|Lenneth> jammi: OSX? New build?
<LoH|Lenneth> Weird
<jammi> LoH|Lenneth: yes macos sierra
````
So now I'm confused.

**Comment by lordofhyphens** [comment]
Also can't reproduce on Windows 10 x64. 

keyno from IRC indicates that after a reboot it is not reproducible, so probably fixed on OSX Sierra. 
jammi concurs.
