### ISSUE TITLE
[1.3.0-dev] Controller interface crashes when trying to connect @ 250000 baud rate on Linux

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#3766]
### Version
c20d44c3887c39eaa6850470ba6571d7c92ab336

### Operating system type + version
Debian Linux 8.6 (Jessie) 
Linux rufus 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

### Behavior
Hard crash with a floating point exception when either a test or connection is attempted at 250000 baud to a printer.

**Comment by alexrj** [comment]
Fixed.
