### ISSUE TITLE
Slic3r fails to start if directory has space in it

### ISSUE THREAD

**Issue by vallon** [alexrj/Slic3r#3777]
### Version
1.30-dev-52a94e8
https://bintray.com/lordofhyphens/Slic3r/slic3r_dev/1.3.0-dev-52a94e8

### Operating system type + version
OS X El Capitan 10.11.6

### Behavior
* Problem: Slic3r does not start
* Reproduce: Double-click on Sli3r app
* Expected: Launches
* Actual: Does not

I was going to complain that the dev version doesn't run, but I had unpacked it into a directory with a space.  After moving the Slic3r.app into a directory without a space, it launched.

1.2.9 (release) doesn't have this problem.

Opening from the command line:

```
$ open "/.../a b/Slic3r.app"
LSOpenURLsWithRole() failed with error -10810 for the file /.../a b/Slic3r.app
```

system.log:

```
Mar 19 18:11:16 toucan com.apple.xpc.launchd[1] (org.slic3r.Slic3r.337952[66579]): Service exited with abnormal code: 127
```

**Comment by alexrj** [comment]
Thank you for reporting this. We just fixed it and you can get a fresh build.
