### ISSUE TITLE
Dos window full of warnings

### ISSUE THREAD

**Issue by cerdeira** [alexrj/Slic3r#3780]
Version

1.3.0-dev slic3r-master.2017.03.20.570.9dbe2ee

Operating system

Windows 10

Behavior

When loading a config file, File/Load Config...  dos window gets full of warnings "Unknown Option..." blocks that repeat several times.

![image](https://cloud.githubusercontent.com/assets/5592642/24115238/9a2dffde-0d9a-11e7-85e4-28ce96a082a3.png)

**Comment by lordofhyphens** [comment]
All those warnings mean is that your print/filament/printer configs that aren't known to the version of Slic3r that you are using (either because the option was removed/replaced or you were using a fork that defined those that upstream doesn't).

**Comment by alexrj** [comment]
Yeah. None of those options are present in the original Slic3r.
