### ISSUE TITLE
3D view confused about Z axis placement of objects after loading from AMF

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#3785]
### Version
1.3.0-dev 61c8359995e785a638d2f39390c2998a889b4a93

### Operating system type + version
Ubuntu 16.04

### Behavior
I added two objects to the plater, and for one of these objects I added a modifier and some part settings to apply to the modifier. Next I saved the plate as an AMF, to store the various settings.

After restarting slic3r, I loaded the AMF, and first I noticed that the objects are not dropped on the Z=0 plane, but they are dropped halfway down beneath. It didn't look like this before I restarted slic3r. Fortunately, prints seem to work fine anyway, printing from Z=0, so it's a cosmetic issue. Here's a screenshot:

![after-loading-amf](https://cloud.githubusercontent.com/assets/684832/24148885/f43f120a-0e40-11e7-9fc4-aedb20489e01.png)

Next, I wanted to replace the main part that had a modifier with a new version. I clicked on the object, chose Settings, added the new part, and then deleted the old part. My aim with this was to test whether I can replace parts of a complex plate, without having to go through all the setup from scratch again. Now the new part is dropped on Z=0, while the other part is still dropped halfway beneath. Again it seems to be cosmetic only, the preview and layers views show both starting from Z=0, so it's just an issue with the 3D view. Here's another screenshot:

![after-replacing-part](https://cloud.githubusercontent.com/assets/684832/24148954/3059f304-0e41-11e7-8430-91748082db53.png)

Fortunately, the workflow of setting up a complex build plate with modifiers, saving to AMF, and then later loading the AMF and modifying objects seems to work fine!

**Comment by lordofhyphens** [comment]
As a FYI I pushed a change a couple days ago that lets you export a single
object with its modifier meshes as an AMF.

**Comment by kefir-** [comment]
@lordofhyphens that's interesting, and certainly useful if I can also add a single object like that to a plate. But this time just replacing the main part with a new stl was the workflow I was looking for. And it worked fine, except for the confusing Z offsets. :)

**Comment by alexrj** [comment]
Should be fixed now. Thank you!
