### ISSUE TITLE
Clicking "Cancel" in Copies dialog removes object

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#3787]
### Version
current master: 4c14c65

### Operating system
Arch Linux 4.9.16-1-lts x86_64

###  Behavior
* When using the `Object → Set number of copies...` dialog, clicking `Cancel` removes the object from the plater.

### Steps to reproduce it
1. Add an object to the plater
2. Select the object
3. Open `Object → Set number of copies...` dialog
4. Click `Cancel`

Expected behavior should left the object (and the current copies of it) unmodified.

**Comment by alexrj** [comment]
Thank you! I fixed this.
