### ISSUE TITLE
Slic3r creates multiple versions of objects when loading AMF

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#3788]
### Version
1.3.0-dev 4c14c656f5c9adf712dfbcea0dc1b7c044131c37

### Operating system type + version
Ubuntu 16.04

### Behavior
I was going to do some testing of reloading of AMF files, but I've stumbled into another issue. I start slic3r, and then added some objects to the plate. Then I save this as an AMF, and quit slic3r. When I restart slic3r and load this AMF, I get a question:

    This file contains several objects positioned at multiple heights. Instead of
    considering them as multiple objects, should I consider this file as a single
    object having multiple parts?

If I click yes, it appears that the objects show up several times. The objects don't seem to appear several times in the AMF. If I click no, it looks right but there's some height confusion, but I don't know if there are any other drawbacks to answering no.

Here's what the plate originally looked like after adding two STLs to Slic3r:

![screenshot from 2017-03-21 23-56-40](https://cloud.githubusercontent.com/assets/684832/24174817/1184b160-0e93-11e7-8ef7-c9f3d13e74bb.png)

Here's what it looks like after loading the AMF and answering "Yes":

![amf-yes](https://cloud.githubusercontent.com/assets/684832/24174868/65b0aa78-0e93-11e7-9816-008ee87aa89d.png)

And for completeness, here's what it looks like after loading the AMF and answering "No":

![amf-no](https://cloud.githubusercontent.com/assets/684832/24174871/724d14d8-0e93-11e7-94b6-53e873a3d52c.png)

#### STL/Config (.ZIP) where problem occurs
Here are my objects, in case they have some features that affect the behaviour:
[load-amf-issue.zip](https://github.com/alexrj/Slic3r/files/859887/load-amf-issue.zip)

**Comment by alexrj** [comment]
Fixed!
