### ISSUE TITLE
Scaling is applied inconsistently over copies

### ISSUE THREAD

**Issue by NateTG** [alexrj/Slic3r#3798]
### Version
Version 1.3.0-dev

1.2.9-790-gaa02dfe2

### Operating system type + version
Linux version 3.16.0-4-686-pae (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07)

### Behavior
* Multiple stls, copy, scale, and rotate interact in some way that causes inconsistent scaling.  I haven't gotten a minimal case,  it seems to happen when I have copies of 2 different STLs on the plate, 2 of one and 3 of the other and then do rotating, scaling, and copying in some random order.

* I expect all copies of an obeject to have the same scaling.
* Sometimes they don't:

![screenshot](https://cloud.githubusercontent.com/assets/4387521/24280639/57b92ddc-100f-11e7-9fb0-db7480037bae.png)

Zip file contains one good 'build plate' stl, and one that displays the issue.

[config.zip](https://github.com/alexrj/Slic3r/files/866882/config.zip)

**Comment by alexrj** [comment]
I am not able to reproduce this.

**Comment by NateTG** [comment]
OK:
Go to 2D plating view
Add Object A.
Hit "more" twice.
Rearrange to remove overlap
Scale by 200%
Add Object B
Scale by 200%
Hit more once.
There should be a random arrangement of object A and object B on the plate now.
Select object A
Right click -> rotate -> around X axis -> 180
Switch to the 3D view.  You should see something odd.

**Comment by Tinchus2009** [comment]
I culd reproduce this following your steps. At the end , when you switch to the 3d platter, the object A is OK, but its 2 copies have been scaled like 400% and the original A only to teh expected 200%. In the 3d platter if you scale object A once more, its 2 copies will be adjusted to the correct size again.

**Comment by NateTG** [comment]
It looks like
scale (not 100%) -> rotate (180) -> scale 
will pop up a menu with 100%.  That's probably related.

**Comment by alexrj** [comment]
Thank you for the instructions! I was able to reproduce this and fix it.
