### ISSUE TITLE
Slic3r not opening when executing stl file

### ISSUE THREAD

**Issue by diegoolavarria** [alexrj/Slic3r#3803]
### Version
Prusa Version

### Operating system type + version
Windows 8.1

### Behavior
When I asociated .stl files into executing Slic3r, is expected to open Slicer with the .stl file already loaded, but it creates a .gcode output file without opening the software. Is it a common problem?

**Comment by xoan** [comment]
This issue tracker is for upstream Slic3r version. You must report it in the Prusa's fork: https://github.com/prusa3d

**Comment by lordofhyphens** [comment]
Closing. If you can reproduce with current build from http://dl.slic3r.org/dev I will reopen.

This is, however, probably normal behavior. If we don't do that then programs like repetierhost will break (and all of the command line interface).

**Comment by lordofhyphens** [comment]
The prusa3d fork uses 2 shell execs, one with a command line window and one without. While we could adjust shell.cpp to build two copies one that forces --gui and one that doesn't (slic3r-gui.exe and slic3r.exe), I'm sure someone else would get confused. 

Reclosing until @diegoolavarria provides a test case with upstream slic3r.

**Comment by diegoolavarria** [comment]
Ok I created an executable of the source code provided here, and tested by executing the .stl file into the slic3r.exe. It opened a command prompt window (which it happens when you execute a .exe created with perl), showing the process of creating a .gcode file.

![cmd](https://cloud.githubusercontent.com/assets/15364801/24358704/61dab58a-12d8-11e7-8704-3b8ca045454a.jpg)

The final result is a .gcode file with the presets.

**Comment by alexrj** [comment]
How did you create the executable?

**Comment by diegoolavarria** [comment]
pp -x -o slic3r.exe slic3r.pl

**Comment by alexrj** [comment]
Then it's normal.
See the contents of the package/win directory for how to properly package Slic3r. Otherwise just get a fresh prebuilt one at http://dl.slic3r.org/dev

**Comment by diegoolavarria** [comment]
Yes, I've tried with different versions and releases, so I also figured out it's a normal setting. Although, I'm trying to configure the code so when I double click a .stl file, it opens Slic3r showing the model instead of automatically create a .gcode file.

**Comment by lordofhyphens** [comment]
@diegoolavarria I have a

**Comment by diegoolavarria** [comment]
@lordofhyphens slic3r.exe by itself always opens the GUI. The problem is when executing a .stl file asociated with slic3r.exe

**Comment by xoan** [comment]
Don't know if it has something to do, but in GNU/Linux, `--gui` option should be passed to `slic3r.pl` when a `file.stl` is provided in order to launch it instead of process it in the command line.

```zsh
% slic3r file.stl       # this process file.stl in the command line
% slic3r --gui file.stl # this opens slic3r and load file.stl
```

**Comment by lordofhyphens** [comment]
I know, I haven't fixed that yet

**Comment by lordofhyphens** [comment]
*sigh*

I will fix it. Please wait for me to say it is fixed before continuing on.
Hopefully that will be tonight.
