### ISSUE TITLE
Add a Notes Tab to the Printer Setting

### ISSUE THREAD

**Issue by ProfDrYoMan** [alexrj/Slic3r#3806]
Hello,

It would be great to add notes to a printer setting.

**Comment by lordofhyphens** [comment]
There's the start/end gcode field. Start lines with ; and you are good to
go.

**Comment by ProfDrYoMan** [comment]
That's right. It's a "workaround". All other tabs got a "notes" section.

**Comment by singh1114** [comment]
@ProfDrYoMan Why do we need notes for the printer settings?

**Comment by ProfDrYoMan** [comment]
I have different setups vor min/max layer limits which I use for some projects.
Also two different g-code setup (one leaves the headbed on).
Yes, it is possible to "code" the differences into the profile name, but it get's to much for me.

**Comment by lordofhyphens** [comment]
Fyi you can mark (as of today) print and filament profiles as compatible
with printer profiles.

**Comment by lordofhyphens** [comment]
Not a replacement, but related.

**Comment by lordofhyphens** [comment]
@ProfDrYoMan What's the intended use for this field? Do you just want it as reference for yourself in the GUI?

Should it get written to output Gcode as comments?

**Comment by ProfDrYoMan** [comment]
My intend is to store information on what is special about this printer setup.
Same as for the notes field in the filament or print setup.

**Comment by lordofhyphens** [comment]
Done.

**Comment by ProfDrYoMan** [comment]
👍 Thanks.
