### ISSUE TITLE
Unable to upload to OctoPrint

### ISSUE THREAD

**Issue by jammi** [alexrj/Slic3r#3811]
### Version
slic3r-1.3.0-dev-426e79c

slic3r-1.3.0-dev-c347487

### Operating system type + version
macOS Sierra 10.12.3

### Behavior
* OctoPrint "Send to printer" support no longer works
* Clicking on the Send to printer button and accepting the dialog, I get this error message: http://i.imgur.com/A7nYAyj.png
  * On subsequent tries (until restarting Slic3r) I get this: http://i.imgur.com/kilbzY8.png
* Nothing found on octoprint's log, so I'd guess Slic3r doesn't even try accessing it.
* Octoprint is at its newest release version (updated within a few days).

This issue is new to me. I used Prusa's builds for a while and the last stable official Slic3r before that. Neither had this issue.

[config.zip](https://github.com/alexrj/Slic3r/files/872308/config.zip)

**Comment by alexrj** [comment]
Thank you for this report, it might be related to our new build procedure not packaging all the required modules for HTTP.

**Comment by alexrj** [comment]
I fixed this. Thank you!

**Comment by Astroman** [comment]
I just tried the latest development build (slic3r-1.3.0-dev-b78ccc6-.dmg) and have exactly the same problem. Should this be fixed in the dev build?

**Comment by jeffbearer** [comment]
I too am seeing this in the slic3r-1.3.0-dev-075adca dmg

**Comment by jammi** [comment]
This issue still (or again) persists.

**Comment by rmpel** [comment]
I'm having similar issues in slic3r-1.3.1-dev-8adf792-osx
No error messages, but no uploads either. Release 1.3.0 works perfectly, so I know it's not my OctoPrints.
