### ISSUE TITLE
Command line "--load" option is ignored

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#3816]
### Version
current master

### Operating system
Arch Linux 4.9.16-1-lts x86_64

### Behavior
When `slic3r` is used from the command line, `--load <file>` is ignored.

### Steps to reproduce the issue
1. Open Slic3r and export your configuration from `File → Export Config...`
2. `$ slic3r --load /path/to/config.ini --output test-cli.gcode test.stl`

You can compare the `.gcode` generated from command line with the one generated by the `File → Quick Slice...`

Attachment: [cli-load-option-ignored.tar.gz](https://github.com/alexrj/Slic3r/files/875377/cli-load-option-ignored.tar.gz)

**Comment by alexrj** [comment]
Ouch. Fixed...
