### ISSUE TITLE
USB/Serial connection configuration is always visible

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#3819]
### Version
current master

### Operating system type + version
Arch Linux

### Behavior
When `Disable USB/Serial connection` is checked in `File → Preferences`, configuration is still visible in `Printer Settings` dialog.

This was implemented in d8be976

**Comment by lordofhyphens** [comment]
Looks like the value from $Settings isn't being passed to the build subroutine in preset editor. I apparently can't perl enough atm to correctly pass it in.

`build` in PresetEditor expects to get the settings as a name/value hash, but the call around line 110 doesn't pass any arguments (assuming that there isn't extra magic that is supposed to be happening here). The values are set via Settings in GUI.pm.
