### ISSUE TITLE
Repetier-Dev-Firmware supports firmware retraction.

### ISSUE THREAD

**Issue by ProfDrYoMan** [alexrj/Slic3r#3821]
As requested by @lordofhyphens:
https://github.com/prusa3d/Slic3r/issues/186

Repetier Firmware (development version) now supports G11/G10 for firmware retraction.
Thus, the guard disallowing it for certain firmwares can be removed in the case of gcfRepetier in libslic3r.

**Comment by lordofhyphens** [comment]
Repetier Firmware has not produced a release with this feature yet.

**Comment by lordofhyphens** [comment]
They accept G10/G11 for this, I don't have a problem with this going in.
https://forum.repetier.com/discussion/1908/feature-retraction-autoretract-enabled
