### ISSUE TITLE
Slic3r is not deterministic

### ISSUE THREAD

**Issue by msrd0** [alexrj/Slic3r#3827]
### Version
1.3.0-dev (1.2.9-871-g8f789da9)

### Operating system type + version
ArchLinux

### Behavior
I wanted to print a [3DBenchy](http://www.thingiverse.com/thing:763622) with Slic3r. I was experimenting with the amount of infill when I noticed that something strange happened. This is the version I'd prefer which I get with 20% infill after changing the layer height from 0.2 to 0.15:

![screenshot_20170331_145711](https://cloud.githubusercontent.com/assets/7853372/24551466/dced0d48-1622-11e7-88e5-a54a5721ab8e.png)

After changing the infill from 20% to 15% I get a completely different result for the solid part:

![screenshot_20170331_145734](https://cloud.githubusercontent.com/assets/7853372/24551499/fd82273c-1622-11e7-9354-3024948aa24e.png)

When changing back to 20% infill this doesn't get reverted:

![screenshot_20170331_145746](https://cloud.githubusercontent.com/assets/7853372/24551520/114e9c82-1623-11e7-9950-256282707b26.png)

The only way to "restore" the best version is to change layer height to 0.2 and back again. I can reproduce this every time.

By the way to get a Preview at all I need to modify one of the parameters, after loading the STL the Preview and Layers view is empty.

#### STL/Config (.ZIP) where problem occurs
[slic3r-config.zip](https://github.com/alexrj/Slic3r/files/885715/slic3r-config.zip)

**Comment by lordofhyphens** [comment]
Is your Perl built with threads?

I generally can't reproduce the layers/preview part of the problem on my Debian system; switching to Preview or Layers is sufficient to start the slicing process (I have background processing turned off).

**Comment by msrd0** [comment]
@lordofhyphens I'm using the perl version of my operating system (ArchLinux). The corresponding [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/perl#n164) file uses the `-Dusethreads` compile flag. `perl --version` says

    This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-thread-multi

**Comment by Lenbok** [comment]
I am seeing something like this too. In my case I am setting the exterior brim width, and the number I set in the entry box isn't "sticking" until I change it's value again. I had "Background Processing" unticked in my preferences. Ticking that and restarting makes things seem to work fine (the preview panel gets updates in place with the correct value).

**Comment by lordofhyphens** [comment]
More likely something isn't registering as a state change to Slic3r (which would force a state change) and/or one of the methods around Fill() isn't idempotent (which is not the same as not being deterministic).

**Comment by msrd0** [comment]
Determinism means that with given prerequisites I can determine the events that will happen in the future. The screenshots I've attached showed that with the same settings (=prerequisites) I get different results, so the event that will happen in the future (after slicing) is different. To me this means that something is not deterministic in that case.

**Comment by lordofhyphens** [comment]
In this case, your initial state for the slicing process is not what you
think it is ;-). If it was nondetetermistic you would see different output
from the same settings with a clean state.

It's still a bug that you are seeing that behavior, of course.

**Comment by alexrj** [comment]
Thank you for reporting this. I applied a fix, and will work more on it after 1.3.0 is released.

**Comment by msrd0** [comment]
The main problem that slic3r was producing different results with the same settings is gone now. Thanks for fixing this.

After loading an STL file the preview and layers view is still empty. Should I open another issue for this?

**Comment by lordofhyphens** [comment]
Always. Separate issues for separate things. Check to make sure it isn't
described by someone else first.

**Comment by lordofhyphens** [comment]
@msrd0  #3839
