### ISSUE TITLE
Enforce Supports not functioning

### ISSUE THREAD

**Issue by jaggzh** [alexrj/Slic3r#3836]
Fresh build on April 2, 2017: 1.2.9-901-g90623c4
OS: Debian Stable

Description:
"Support material -> Enforce support for the first N layers" doesn't seem to do anything.
I have Supports disabled, then any number entered in the Enforce option.

If I'm understanding correctly, this would allow me to have supports generated for N layers, and the rest of my object (above that) be support-less.

**Comment by lordofhyphens** [comment]
Test case:
[3836.zip](https://github.com/alexrj/Slic3r/files/923953/3836.zip)

**Comment by jaggzh** [comment]
Disable "Don't support bridges", or use a model without vertical sides below the Enforce layer count and it should work.

My .zip is not uploading for some reason (Something went really wrong, and we can't process that file. Try again.)
