### ISSUE TITLE
Excessive supports generated, I think.

### ISSUE THREAD

**Issue by jaggzh** [alexrj/Slic3r#3842]
Built on April 2, 2017: 1.2.9-901-g90623c4
OS: Debian Stable

Description:
The attached object (image also attached) seems to get supports generated excessively.  The supports run up the sides where no support is needed (45 degree limit on supports).  The model seems intact, although it does have small faces and some sharp edges/corners.

At least it would be nice to know what qualities of the object result in this behavior.  Thanks a lot.

Ideally: Only what seem to be true overhangs would be supported (near the very bottom, and perhaps up to the circle hole... but not the sides and such).

[foo1](https://cloud.githubusercontent.com/assets/20318973/24604815/3b3bea3c-181b-11e7-9099-b56236373496.jpg)
[test-switch-slot.zip](https://github.com/alexrj/Slic3r/files/889658/test-switch-slot.zip)

**Comment by lordofhyphens** [comment]
Change support threshold to 150% or 200% (tweak that value until you get what you are interested in)

Closing.

**Comment by jaggzh** [comment]
Even at 0 threshold it engulfs the object.  (Front-most object in set here)
![foo1](https://cloud.githubusercontent.com/assets/20318973/24617688/8414672e-1849-11e7-9103-13001e45ffeb.jpg)

**Comment by jaggzh** [comment]
Even at 1 it builds supports all over the object's surface.

**Comment by lordofhyphens** [comment]
@jaggzh Please zip and add the config you were using.

**Comment by lordofhyphens** [comment]
![image](https://cloud.githubusercontent.com/assets/31754/24755967/b65df484-1aa1-11e7-8217-d6c3bd553c8a.png)



Here's a picture of one of my results and the model rotated 90 in Y
![image](https://cloud.githubusercontent.com/assets/31754/24756064/10cdf57c-1aa2-11e7-8a6a-bbf15d6f102e.png)
[0.05config.zip](https://github.com/alexrj/Slic3r/files/902664/0.05config.zip)

It would help as well if you included the object in the orientation you are seeing this issue in. 

Config from #3860, object rotated 90 deg in Y.
![image](https://cloud.githubusercontent.com/assets/31754/24756117/4522d87e-1aa2-11e7-8681-954b18dacaf2.png)

Same config, changed to 60 degrees.
![image](https://cloud.githubusercontent.com/assets/31754/24756264/bb9676f0-1aa2-11e7-9e54-8e7f6bd1f640.png)

**Comment by Arakon** [comment]
I agree with this issue. Comparing my usual "filament test print object" between 1.3.0 and 1.2.9, 1.3.0 generates way, way more support material than 1.2.9. Keep in mind that with the lower amount of support material, the object printed perfectly fine, i.e. there were no badly supported areas.
![2017-04-09 09_34_20-slic3r](https://cloud.githubusercontent.com/assets/12016360/24835673/f2f10cac-1d07-11e7-9486-76d5ee4a804f.png)
![2017-04-09 09_34_40-slic3r](https://cloud.githubusercontent.com/assets/12016360/24835674/f2f18542-1d07-11e7-9424-9f7fbb550e8e.png)

**Comment by lordofhyphens** [comment]
Please post your configuration, this is related to that (and of course
update to newest, I am now enforcing the new configuration option
semantics.

**Comment by jaggzh** [comment]
[supp0rts.zip](https://github.com/alexrj/Slic3r/files/911613/supp0rts.zip)

**Comment by jaggzh** [comment]
![8002-unlimited-11-mo-charge](https://cloud.githubusercontent.com/assets/20318973/24884927/b38ad5c6-1e00-11e7-8abc-dd333275d242.jpg)

![8002-unlimited-11-mo-charge](https://cloud.githubusercontent.com/assets/20318973/24885022/19a8cf52-1e01-11e7-81be-fb602c44a097.jpg)

These are the orientations.

**Comment by lordofhyphens** [comment]
I think I found the bug, I needed an extra pair of () around an if statement in SupportMaterial.pm.
![image](https://cloud.githubusercontent.com/assets/31754/24887525/ee62e67c-1e21-11e7-81cd-0601df5db07e.png)
