### ISSUE TITLE
Background processing is active all the time and it reacts "too quickly"

### ISSUE THREAD

**Issue by Tinchus2009** [alexrj/Slic3r#3843]
### Version

1.2.9-901-g90623c4

### Operating system type + version
Win 10 64b

### Behavior
Background processing is disabled in my preferen ces. Despite of that, when I change values in the printing setting, as soon as I close tthe windows it starts the slicing in the background
Im thinking that may be this is the intended behaviour? because the processing only starts when closeing the window.

* _Steps needed to reproduce the problem_
Load a model, open the printing settings wndow, change for example vertical shells value (no processing when you changed the value), close the printing settings window, the processing starts here. But with on problem, it looks like it reacts too quicly. 
Example: load any model, configure slic3r in the Overrrides section to show the support generation options so you can quickly change the support geenration option without haveing to open the printing settings window. In the supports threshold, write "200%, as soon as you wrote the numer "2" you will see the background slicing starts and ends. When you finish writing the hole "200% you think that the 3d preview shows a correct simulation. Well, it is not, what you will see is a simulation of an verhang value of "2". If you go again to the overhang threshold erase the "%", wait till background provessing finishises the slice, and write the "%" again, now you will see the proper simulation. 
I think there should be a button "slice now" so we cn manually triger the slicing and so to be sure what is being sliced

**Comment by lordofhyphens** [comment]
#3839

**Comment by alexrj** [comment]
Fixed, thank you!
