### ISSUE TITLE
This does not slice as expected, is it me or slic3r?

### ISSUE THREAD

**Issue by ruggb** [alexrj/Slic3r#3844]
### Version
1.2.9 stable -- or 1.3.0 dev

### Operating system type + version
windows 10 1607

### Behavior
this model has one wall = 1mm and the opposite wall = 2mm. If I slice it with infill the walls are 1 or 2 (as set) perimeters wide and the whole model is infilled. If sliced without infill the walls are 1 or 2 (as set) perimeters wide with no infill. Is it possible to slice this and get 1 and 2 mm walls (with infill where necessary) and a hollow core? Does the model need to be different or Slic3r settings different? Or is this not possible with Slic3r? I tried it in 1.3.0 also, same result

0.2mm layers, 1 or 2 perimeters 15% infill

[one wall.zip](https://github.com/alexrj/Slic3r/files/889957/one.wall.zip)

_Is this a new feature request?_NO

**Comment by lordofhyphens** [comment]
http://dl.slic3r.org/dev

**Comment by xoan** [comment]
Are you sure you attached the correct model? If the answer is _yes_, sorry, I can't understand what do you are trying to do... :\

![captura de pantalla_2017-04-03_15-30-21](https://cloud.githubusercontent.com/assets/288246/24611465/783e4792-1882-11e7-86a4-47104b067369.png)

**Comment by ruggb** [comment]
Yes, the model has one wall that is 1mm thick and the opposite is 2mm. It is drawn with one box inside the other and positioned slightly offset to achieve the above. The bottom & top are 2mm thick.
When I slice it, Slic3r gives me the frame with the set # of perimeters and the rest of it is infill instead of being hollow and just infilling the walls. I haven't tried putting a hole in it, which might make Slic3r realize the inside is hollow or it might think it is not manifold.

**Comment by lordofhyphens** [comment]
Please add a few screenshots showing the issue.

**Comment by ruggb** [comment]
this is an xray view. The right wall is 2mm, the left is 1mm, the bottom is 2mm,
the slice (1 perimeter, 15% infill) does not implement the internal hollow. It is all infilled.
the other slice is with 0 infill and again there is no internal structure.
If I put a hole into the hollow it will slice as expected.
This is done with 1.3.0 - I didn't try the hole on 1.2.9, but the others do the same thing with 1.2.9
![onewall xray](https://cloud.githubusercontent.com/assets/12383390/24620400/93768018-186b-11e7-9e73-2a3a97ec1552.PNG)
![onewall slice](https://cloud.githubusercontent.com/assets/12383390/24620409/9baef288-186b-11e7-8c18-b0e9b35cbec5.PNG)
![onewall slice 0 infill](https://cloud.githubusercontent.com/assets/12383390/24620426/ac2c9ee4-186b-11e7-86da-c82b2c095bbd.PNG)
![onewall w-hole 15 infill](https://cloud.githubusercontent.com/assets/12383390/24620437/b18a84dc-186b-11e7-8121-29cdec9b16d4.PNG)
![onewall w-hole 0 infill](https://cloud.githubusercontent.com/assets/12383390/24620439/b4d3a574-186b-11e7-92d5-93e309f14b9a.PNG)

**Comment by lordofhyphens** [comment]
So the original 3d model has no internal voids?

**Comment by xoan** [comment]
I think your model has the internal faces inverted, so it is computed as a whole solid shell.

**Comment by ruggb** [comment]
we are getting into semantic confusion.
The orig internal structure is closed with 2mm between it and the external structure except for one wall which is 1mm. Obviously, if I want it to be hollow I must open it to the outside air with at least one hole.
At this point, the question is, why do I need to put air into it to get Slic3r to make it hollow as in the 5th & 6th pic? Is that the way it has to be, or is Slic3r missing something?

**Comment by xoan** [comment]
I guess it is because I said in my previous comment: the faces in the internal shell are inverted when there is no connetion between internal and external shells of the object.

Probably, your CAD software (SketchUp?) solve this issue when you make a hole connecting the shells. So, the problem is with your CAD software. Try by searching how can you reverse the normals for the inner shell without doing a hole.

**Comment by ruggb** [comment]
Well now, that is just amazing. When I put a hole into the model Sketchup automatically reversed those faces. Since it is virtually impossible to see that, I never thought of it. Of course, I probably never would have even if I could see it since I have no clue how Slic3r does things. It is all magic to me.
I reversed all the faces in the original and it works.
thank you for that education.

**Comment by ruggb** [comment]
thx again

**Comment by lordofhyphens** [comment]
Sketchup is pretty bad when it comes to producing useful models/STLs. I strongly suggest avoid using it.

**Comment by ruggb** [comment]
Everybody says that, but I have mostly figured it out and it is relatively easy for me. There are a few quirks as with any program. But I keep looking at other things to see how much of a learning curve there would be.
So far, I am happy with Sketchup.
