### ISSUE TITLE
Overhang threshold reporting error when a value is set

### ISSUE THREAD

**Issue by Tinchus2009** [alexrj/Slic3r#3848]
### Version
1.2.9-909-g5c2ab11

### Operating system type + version
win10 64b

### Behavior
New default overhang threshold value is to 120%. if you load a model, and activate supports to be generated, inmediatlly you get an error windows saying:
"Argument 120% isn't numeric in numeric eq (==) at F:/slic3r......../Config.pm line 274"

If you change that value to any other value containing %, you get the same error again.

**Comment by lordofhyphens** [comment]
Serves me right for trying to hotfix.

**Comment by lordofhyphens** [comment]
Fixed  via f725b519e848694ea9ced856846161192b291d84. Sorry about that.
