### ISSUE TITLE
Latest git builds forgets which settings were last used

### ISSUE THREAD

**Issue by djdelorie** [alexrj/Slic3r#3852]
### Version
1.2.9-920-g139aeb8

### Operating system type + version
Fedora 24 64-bit

### Behavior
While testing this new git build, when I first brought up slic3r, it defaulted to the first print/filament/printer config based on alphabetical order, instead of loading the last-used configs of each type.

**Comment by alexrj** [comment]
The transition between the previous plater behavior and the new code caused the existing preferences to be ignored, but that's just for the first launch.
