### ISSUE TITLE
[bintray] Cannot download latest (any OS) build

### ISSUE THREAD

**Issue by foreachthing** [alexrj/Slic3r#3854]
FYI: It is _Forbidden!_ to download this (or any other build): https://bintray.com/version/files/lordofhyphens/Slic3r/slic3r_dev/1.3.0-dev-557f1e2
Tried on Firefox (PC) and Opera (Mobile) - same message: _Forbidden!_

**Comment by alexrj** [comment]
Link changed, go to http://slic3r.org/download
