### ISSUE TITLE
`center_selected_object_on_bed` moves object to origin

### ISSUE THREAD

**Issue by foreachthing** [alexrj/Slic3r#3855]
### Version
slic3r-master.2017.04.05.885.66c7eb7

### Operating system type + version
Win 7 Pro

### Behavior
* `center_selected_object_on_bed` (_Center object around bed center_) actually moves object to origin instead of to _center_ of bed. Center and origin may not be the same.

#### STL/Config (.ZIP) where problem occurs
any file, any config.

**Comment by alexrj** [comment]
Whoops, thank you.
