### ISSUE TITLE
Support Pattern Angle not respected

### ISSUE THREAD

**Issue by foreachthing** [alexrj/Slic3r#3861]
### Version
slic3r-master.2017.04.05.885.66c7eb7

### Operating system type + version
Windows 7 Pro

### Behavior
* Added support material - Pattern: Rectilinear; spacing: 2.5 mm
* Angle at 0 degrees, all good
![support_pattern_angle_01](https://cloud.githubusercontent.com/assets/10420187/24741298/9bf5ec42-1aa5-11e7-9863-5cf336f269f6.png)

* Angle at 90 degrees ... so I thought!
![support_pattern_angle_02](https://cloud.githubusercontent.com/assets/10420187/24741326/bdb63b2a-1aa5-11e7-8c67-78ffb4b0c8dc.png)

In the second screenshot the infill pattern is definitely not at 90°.

The pattern jumps around, when using the angles 29 to 31 ...

* 29 degrees:
![support_pattern_angle_29deg_03](https://cloud.githubusercontent.com/assets/10420187/24741779/c34cbe2c-1aa7-11e7-8106-4d2030514459.png)
* 30 degress:
![support_pattern_angle_30deg_04](https://cloud.githubusercontent.com/assets/10420187/24741784/c7e00cfa-1aa7-11e7-9412-02b28bfa8b3b.png)
* 31 degrees:
![support_pattern_angle_31deg_05](https://cloud.githubusercontent.com/assets/10420187/24741785/c81c1b14-1aa7-11e7-88a4-8fa97a6e7d7f.png)

After that, I stopped messing around and used 30 degrees - close enough, Come to think of it, I'll rotate the part!

**Comment by alexrj** [comment]
Thank you for the report.

Also, interesting seeing how many options you exposed in the right panel.

**Comment by alexrj** [comment]
Thank you for the report.

Also, interesting seeing how many options you exposed in the right panel.

**Comment by foreachthing** [comment]
> how many options you exposed in the right panel. 

Just the ones I change from print to print :)
The layout gets slow, though!

**Comment by lordofhyphens** [comment]
Fill takes its angle in radians, SupportMaterial was providing it in degrees. Fixed it by applying deg2rad in all invocations of set_angle() in SupportMaterial.pm  
![image](https://cloud.githubusercontent.com/assets/31754/25066326/691ba06a-21e8-11e7-9a18-81a9ee18669e.png)

![image](https://cloud.githubusercontent.com/assets/31754/25066327/6f3ec0ee-21e8-11e7-971f-232bc70312b3.png)
