### ISSUE TITLE
The

### ISSUE THREAD

**Issue by powertide** [alexrj/Slic3r#3866]
I'm using ubuntu 13.10 64bit was a fresh install.

followed the instructions on https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux
Didn't work I thought it was a perl problem so I then installed perlbrew perl-5.16.0

After installing perlberw lots of things failed after trying sudo perl Build.PL --gui

Then I Tried perl Build.PL everything tested ok except 'The XS/C++ code failed to compile'
Then I tried with the following --force command and got this:

**Comment by lordofhyphens** [comment]
FYI perl 5.16 is known to have problems.

Also, that distro is really old and you *must* have at least gcc 4.9 to build Slic3r.

You should not need to use perlbrew though on Ubuntu.
