### ISSUE TITLE
 XS/C++ compile issue(GUI.cpp bugs)

### ISSUE THREAD

**Issue by powertide** [alexrj/Slic3r#3867]
I followed exactly the instructions on https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-Windows.

I'm using Windows7 64bit.
Strawberryperl 5.24.0 64-bit
boost 1_63_0

It went well till when I did "perl Build.PL", and it looked like this

![image](https://cloud.githubusercontent.com/assets/25276795/24783718/936f5514-1b80-11e7-8fac-a69c4a985ec1.png)

There seems to be some problems in the file "GUI.cpp". 
Really looking forward to your help.

**Comment by lordofhyphens** [comment]
Are you using the appropriate version of Strawberry Perl?

There have been changes, see wiki.

**Comment by lordofhyphens** [comment]
So here's the build log from the last build on the server:
https://ci.appveyor.com/project/lordofhyphens/slic3r/build/1.3.0-master-926

That build (and the numerous ones before it) pass, so I'm not particularly persuaded that there is a problem in GUI.cpp (https://github.com/alexrj/Slic3r/blob/master/xs/src/slic3r/GUI/GUI.cpp). It's been unchanged for over a year.

SetThreadExecutionState is a Windows API function, so it should be in Windows.h
https://msdn.microsoft.com/en-us/library/windows/desktop/aa373208(v=vs.85).aspx

https://github.com/alexrj/Slic3r/blob/master/appveyor.yml is what our build server does on every build. You can examine the individual files it calls (the .ps1 scripts in package/win) and alter paths to suit your local system.

**Comment by lordofhyphens** [comment]
Related:
http://stackoverflow.com/questions/25276092/c-win-api-function-not-declared-in-this-scope

We use mingw-w64's compiler in our setup, are you sure that you don't have another MinGW install in your path before C:\Strawberry\c\bin?

**Comment by powertide** [comment]
@lordofhyphens Thanks a lot for your help. I did have several other MinGW installed in my computer before, and after I had them deleted, the problem I proposed didn't occur again. But another one came up.
![image](https://cloud.githubusercontent.com/assets/25276795/24844928/a8857a3e-1de0-11e7-9a0f-00e6a42329f8.png)
Already tried setting the BOOST_DIR variable to "C:\dev\boost_1_63_0", didn't help. The output stayed the same.
I am sure that I successfully installed boost in C:\dev\boost_1_63_0 before and compiled it(used command bootstrap and b2 as instructed in the Wiki page). 
And I sure looked it up in the issues, but couldn't find a valid answer .

**Comment by lordofhyphens** [comment]
That's not the right version of gcc (sjlj exceptions WILL hang slic3r during the test phase). If you were using the correct mingw as referenced by the wiki for x86_64 (on 64-bit you MUST use Slic3r Perl), the gcc version would be 6.3.0.

The "can't find boost" failure is not necessarily because there is no Boost in that directory, it's that the Boost found can't be used. You need to have Boost installed for every compiler you build with. 

Here's a copy of boost built with the appropriate compiler (gcc 6.3.0), which is what our build server uses. 
https://bintray.com/lordofhyphens/Slic3r/download_file?file_path=boost_1_63_0-x64-gcc-6.3.0-seh.7z

**Comment by powertide** [comment]
![image](https://cloud.githubusercontent.com/assets/25276795/24847660/ee23da68-1df4-11e7-8919-c3298c7d4ff8.png)
As you can see ,the gcc 4.9.2(silj) seems to be just the gcc in strawberryperl directory. The strawberryperl version I installed was 5.24.0 x64. Could it be the problem? But it was exactly the version the wiki page recommended. Hell I'm confused...

**Comment by lordofhyphens** [comment]
https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-Windows#slic3r-perl

The wiki changed about a week or so ago. I know because I was the one to change it.

If you reread the preceding section you will see that note to not use the 64 bit version from strawberryperl.com.

If there is another section of that page that told you to use 64 bit strawberry perl 5.24 tell me and I will fix it (the previous recommended 64 bit version was 5.18 and that version won't work anymore ).

**Comment by powertide** [comment]
OK. I thought that the "32-bit only" meant for the computer used. So I should install 32-bit strawberryperl even though my computer is 64-bit, right?  I'll give it a go. Thanks~

**Comment by lordofhyphens** [comment]
That is almost the *opposite* of what I said. Download and install [Slic3r Perl](https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-Windows#slic3r-perl), which is what the wiki says to do if you are using Windows 64bit.

You may need to overwrite C:\Strawberry with [this archive](https://bintray.com/lordofhyphens/Slic3r/download_file?file_path=Strawberry-6.3.0-seg-archive.7z)

**Comment by powertide** [comment]
First of all, thank you for your patience. @lordofhyphens 
But I installed the custom strawberryperl , recompiled boost and did as you/wiki said, and the problem is still there.
![Uploading image.png…]()

The gcc version shown now has changed to 6.3.0. That is some progress I guess.

**Comment by powertide** [comment]
I really appreciate your help @lordofhyphens, and I have completed the "Perl Build.PL" as below following your advice.
![image](https://cloud.githubusercontent.com/assets/25276795/24988976/df5b8172-203b-11e7-89f9-592ed2706ecf.png)
But where can I find the output of this build( executable file)? 
I can't find it in Slic3r directory , nor in Strawberry.
Could you show me please?

**Comment by lordofhyphens** [comment]
See package/win directory if you want to build something that looks like an exe.

If you just want to start Slic3r, run the Perl program with slic3r.Pl as an argument.

**Comment by lordofhyphens** [comment]
Reference the deployment part of appveyor.yml for hints

**Comment by powertide** [comment]
![image](https://cloud.githubusercontent.com/assets/25276795/24990097/e4e7fe88-2043-11e7-9d9d-228b453575d4.png)
No exe file was found in package/win directory.
And what did you mean  by "the deployment part of appveyor.yml"? 
Could you be more specific, please?
Plus, good to see that the slic3r program was successfully started by running"slic3r.PL".

**Comment by powertide** [comment]
![image](https://cloud.githubusercontent.com/assets/25276795/24991337/943681cc-204c-11e7-9564-dff00fcdaaec.png)
Found only one "appveyor.yml" file on my computer, and it looks like this.
The deployment part seems to not exist. What am I missing here?

**Comment by powertide** [comment]
I've done some search and found several issues regarding： #1777  #2316
I tried using PP (pp -o slic3r.exe slic3r.pl)  and did get a slic3r.exe, but it didn't run as I thought. A black window just flashed a sec and disappeared, nothing else happened.
![image](https://cloud.githubusercontent.com/assets/25276795/24998152/bc871b4a-206b-11e7-8a98-6d8f34804fc1.png)
@lordofhyphens @alexrj I know you guys are very busy, but really hope you can show me how to package slic3r into an executable file. It's very important to me.

**Comment by alexrj** [comment]
@powertide, the packaging script is package/win/package_win32.ps1

Please note we have automated fresh builds at http://slic3r.org/download so you don't need to package yourself.

**Comment by lordofhyphens** [comment]
You need to compile the exe (which is just a thin wrapper to invoke the
Perl interpreter on Slic3r.pl). Unless you really really want an exec file
it isn't strictly necessary.

I mentioned appveyor.yml because that contains the instructions our build
server uses to produce what goes to dl.slic3r.org/dev/win.

The script name should be compile_wrapper.ps1 and you will need to run it
with the argument "524"

**Comment by lordofhyphens** [comment]
If you want an archive to copy to another PC, package_win32.ps1 will do
that.

**Comment by lordofhyphens** [comment]
````
deploy_script:
- ps:  "& package/win/appveyor_deploy.ps1"
````

Read that script and see what it calls.

**Comment by powertide** [comment]
@lordofhyphens  @alexrj  Yes, I do need to get an exec file so that it can be used on other computers without perl environment.
I tried running compile_wrapper.ps1 and it turned out like this:
![image](https://cloud.githubusercontent.com/assets/25276795/25032243/0b08ef84-2105-11e7-8fea-041dbbfa88a6.png)
From what I can tell, the errors displayed seem to be grammar mistakes. But since the compile_wrapper has been used so many times, I believe there are some pieces I'm missing here.  Anyways I will let you decide. The file looks like this:
![image](https://cloud.githubusercontent.com/assets/25276795/25032267/3d67f362-2105-11e7-9675-1b388bcc2dfb.png)

**Comment by lordofhyphens** [comment]
Open up powershell as a prompt and run from there. Cd to the directory (it
is better than cmd.exe imho).

Then run
& compile_wrapper.ps1 524

Or read the file and use the commands one by one, accounting for any
variables.

**Comment by powertide** [comment]
1.  I did as  @lordofhyphens   said but the result stayed the same.
![image](https://cloud.githubusercontent.com/assets/25276795/25076400/28c23120-2353-11e7-8b5c-ea343ebaa899.png)
From what I can tell, the error says that it lacks the terminator “ ' ”.
I'm a newbie on this, please take a minute to look into this for me.

2. Then I used **the commands one by one**, and the result was weird.
![image](https://cloud.githubusercontent.com/assets/25276795/25076154/e43c4c54-2350-11e7-9076-11e8142c1f80.png)
Nothing happened. No mistake , and certainly no files generated after this.

**Comment by lordofhyphens** [comment]
Remove the | Write-Host parts from commands.

**Comment by lordofhyphens** [comment]
Is your default locale non-US (like shift-JIS)?

**Comment by powertide** [comment]
@lordofhyphens Yes, I'm in China.

**Comment by lordofhyphens** [comment]
Read my earlier message  (I edited it).

**Comment by lordofhyphens** [comment]
As an aside,.would you be willing/able to contribute to a Chinese translation of Slic3r? Mechanically making it work is very easy.

**Comment by powertide** [comment]
Yes, I can do translation, and I'm glad to help contribute to slic3r community~I will be so honored!

**Comment by powertide** [comment]
Well, I erased the "| Write-Host" parts, but it didn't make any difference.
I don't think the alternative you @lordofhyphens suggested about downloading packages directly would work for me.  
Because I want to open the setting for " **infill phase**", which means increasing a certain value of infill angle by each layer. For example, if the infill angle for layer 1 is 90°, and the infill phase is 45°. Then for layer 2 the infill angle would be 90+45=135°. And layer 3 would be 135+45=180°. ...
As far as I know, the infill phase in slic3r for now seems to be fixed and cannot be changed. 
(Maybe it should be put forward in an feature request, since I don't find any related request.)
So yes, I want to alter this, generate my own ".exe" files and copy to another PC to use them.

**Comment by lordofhyphens** [comment]
Slic3r.exe does not have any functional part of Slic3r in it (this is
different than 1.2.9). It is basically a simplified form of perl.exe that
calls slic3r.pl.

So yes, you can drop it and all dll files in the root directory of a
packaged Slic3r dir into another source dir and it will work (assuming you
have built libslic3r accordingly via Build.pl).

If you installed slic3r-perl as the wiki indicated, g++ will be in your
PATH.

You can move shell.cpp into the same directory and compile it directly if
you want to keep trying to build the wrapper exe.

There isn't much else I can do to help without having access to your
computer to figure out what is different on your system.

**Comment by lordofhyphens** [comment]
The old packing script just copied perl.exe and perl524.dll from
C:\strawberry to the slic3r directory  (it did a few other things with PAR,
glhf with that if you are having problems getting the compile wrapper
script to run).

You can cheat though by copying your entire slic3r source directory  (where
you built slic3r) into an extracted copy from the build server (overwriting
everything). It is a dirty hack, but it would give you a working,
self-contained archive.

FYI there are known issues with paths that contain non-latin characters on
Windows. I am still trying to find a working solution for that.

**Comment by powertide** [comment]
Thank you for your always patient explaination and kind help.
Here is what I found when I tried the "dirty hack" method you mentioned.(Desperate time, desperate measures~ can't blame me :-) ):

![image](https://cloud.githubusercontent.com/assets/25276795/25079203/e448f2da-236c-11e7-8ef6-cd0d7b297536.png)
This is a package I downloaded and extracted. The "duobianxing.stl" file was manually added into the directory. As you can see, the directory path has none no-latin character.
![image](https://cloud.githubusercontent.com/assets/25276795/25079362/6239fefe-236e-11e7-8c8b-bfc64a0bfcf0.png)
And when I entered command "slic3r-console duobianxing.stl", errors came out. It has something to do with the locale codeset. I looked into the "locale.pm" file:
![image](https://cloud.githubusercontent.com/assets/25276795/25079514/c3a88eac-236f-11e7-8338-16891a2d0bcc.png)
But meanwhile, it's perfectly OK to run "perl slic3r.pl", the program started in secs.
So, how should I modify the "locale.pm" file to make the exe work?

**Comment by lordofhyphens** [comment]
Okay, that is some kind of bug. I suspect the file encoding of the source
needs to be fixed. It is probably why you can't run the scripts either.

Very weird, I will look into it today.

**Comment by powertide** [comment]
Have you got any clues on how to fix this bug? @lordofhyphens

**Comment by lordofhyphens** [comment]
yeah, save the encoding as something that isn't cp932 (which is what I think it used to be because of my editor config somehow). 

Resave the files as utf8 and it should *probably* work.
I also just checked in updated versions of the affected files.

**Comment by powertide** [comment]
I saved the file "Locale.pm" as utf-8 and tried running the command again. But it turned out the same.
Do I need to change other files too? @lordofhyphens

**Comment by lordofhyphens** [comment]
@powertide just update, the problem isn't in locale.pm it was in in the compiled exe. 

Get a new windows build.

**Comment by powertide** [comment]
OK I'll try it.

**Comment by powertide** [comment]
Downloaded the latest windows build.
![image](https://cloud.githubusercontent.com/assets/25276795/25172485/cf083f80-2523-11e7-88c4-54cdd5e753c0.png)
It didn't work. All the same again...

**Comment by powertide** [comment]
The latest window builds don't work on my computer(win7/X64). 
I think this might be high priority.　@lordofhyphens 　How can I help?

**Comment by powertide** [comment]
Any progress on this problem here @lordofhyphens ?
Hope you have not forgotten about it :-)

**Comment by lordofhyphens** [comment]
I have a day job, it is really busy right now. I am also basically out of ideas.

**Comment by powertide** [comment]
@lordofhyphens Just so you know,  the slic3r exe from the latest window builds does work fine now on my PC. I am not sure since from which version it has been working fine though. 
Still,  good news to know! :-)

**Comment by lordofhyphens** [comment]
Well, so long as it's working now. I don't have any real way of debugging this any further. If it stops working for you then open a new ticket.

**Comment by powertide** [comment]
Sure~ Thank you for your always hard work!

**Comment by DaveAM** [comment]
I had the same problem and know nothing about powershell, but noticed in the powershell editor that the formatting changed for the initial '. So the following worked for me (note I'm using Win7). I simply put a space after all the -L and -I and before the "C:\strawberry..." (e.g. -I 'C:\strawberry\perl\lib\CORE\').

**Comment by powertide** [comment]
@DaveAM  WOW I did as you said and it has amazingly worked!
Thank you so much. Though I still don't get it. What led you to edit the ps1 file like that?
