### ISSUE TITLE
Default config

### ISSUE THREAD

**Issue by soosalameh** [alexrj/Slic3r#3869]
Where are the default temperatures saved in the code?

**Comment by lordofhyphens** [comment]
Default config is in PrintConfig.cpp.

You shouldn't ever need to change it, due to the logic of profiles.

**Comment by lordofhyphens** [comment]
Specifically:
https://github.com/alexrj/Slic3r/blob/master/xs/src/libslic3r/PrintConfig.cpp#L56
https://github.com/alexrj/Slic3r/blob/master/xs/src/libslic3r/PrintConfig.cpp#L1458

I reiterate, you will *never* need to change these. Just save a profile. Slic3r will remember the last profile you used for GUI and you can pass in --load on the command line.
