### ISSUE TITLE
[Feature Request] Scale Modifiers

### ISSUE THREAD

**Issue by foreachthing** [alexrj/Slic3r#3875]
### Version
Any

### Operating system type + version
Windows 7 Pro

#### Current Behavior
* Add cylinder (box, slab, stl, ...) modifier
  * make some changes to the model and reload it
  * notice, modifier is suddenly too small or too big
    * or the modifier was chosen just a bit too small
  * need to **delete** modifier and **redo all modifications** (first you need to take notes or make a screenshot of current settings)

#### NEW Behavior
* Add cylinder (box, slab, stl, ...) modifier
  * make some changes to the model and reload it
  * notice, modifier is suddenly too small or too big
  * scale modifier a bit in X and some more in Z - done.

_Is this a new feature request?_
Yes.

**Comment by lordofhyphens** [comment]
Is a right-click menu similar to how it works on the Plater (right-click on the modifier in the menu in this case) sufficient?

**Comment by alexrj** [comment]
It's a good start :-)

**Comment by lordofhyphens** [comment]
Did some looking over the code, and I think we'd be well-served by factoring out the scaling subroutines in Plater.pm so we can call them from ObjectSettingsDialog.pm.

**Comment by foreachthing** [comment]
I thought it could be like the `$optgroup_movers` except scale it in X, Y or Z.
Maybe limit the scale factor to be less than 5 times platter size ;)

**Comment by alexrj** [comment]
@lordofhyphens, there's little to factor out because Plater transforms whole ModelObjects, while ObjectPartsPanel would transform single ModelVolumes, so different API calls. I'd just write new code, not much is needed.

**Comment by lordofhyphens** [comment]
@foreachthing there you go.

**Comment by lordofhyphens** [comment]
@foreachthing http://dl.slic3r.org/dev/win/branches/slic3r-resize-mesh.2017.04.14.938.e202f5b.zip If you want to work with it a bit.

**Comment by foreachthing** [comment]
@lordofhyphens
Thank you! I was like: "nah-damn, I can't build that branch!" and then you upload that - thanks!! :-)
So far it seams to work pretty good!!

But for some reason, I got some (Chinese?!) characters on the buttons.
![slic3r_scale-modfier-001](https://cloud.githubusercontent.com/assets/10420187/25063141/e6c64dd2-21dc-11e7-84a4-34f0c88929de.PNG)

**Comment by lordofhyphens** [comment]
I will see what is going on, I think it is related to file encoding

**Comment by lordofhyphens** [comment]
Should be fixed now.
