### ISSUE TITLE
Background processing is not triggered if config and model are loaded from CLI

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#3887]
1857bf63910a7ade053390157fbd1bb9533629a0

OS: Debian Linux

Using `--gui --load config.ini file.stl` with background processing enabled does not trigger background processing.

**Comment by gege2b** [comment]
could it be related to #3862 ?

**Comment by alexrj** [comment]
Ha, good catch. Fixed.  And yes, @gege2b, #3862 might be related to this...
