### ISSUE TITLE
Resize part under settings doesn't affect print

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#3900]
### Version
1.3.0-dev f24fc2c6757a819ceaf5344bb6ecd5479b0eacb1

### Operating system type + version
Ubuntu Linux

### Behavior
1. Add a part to the print bed.
2. Right-click part, choose Settings...
3. Right-click part again in the pop-up window, choose "Scale to size -> Along Z-axis"
4. Type in a value and click ok, and see that the preview in this pop-up has changed
5. Click OK to close pop-up, and now the main part is unchanged

I would expect the main part to be changed as well. If I do the same directly, without opening the Settings window first, it works as expected.

Screenshot shows difference in the two windows, here the Settings window was reopened after clicking OK, and Slic3r remembers the size of the part there.

![screenshot from 2017-04-22 18-16-24](https://cloud.githubusercontent.com/assets/684832/25306149/e0f51108-2787-11e7-9d98-2007e3afcdb5.png)

_Is this a new feature request?_
NO

#### STL/Config (.ZIP) where problem occurs
Not required

**Comment by lordofhyphens** [comment]
Move the part or click arrange, see if it updates

**Comment by kefir-** [comment]
If I click "Arrange" the part immediately updates.

**Comment by NateTG** [comment]
Could this be a dup of this issue: https://github.com/alexrj/Slic3r/issues/3798

**Comment by alexrj** [comment]
Fixed. Thank you!
