### ISSUE TITLE
Too long menu for quick access override settings.

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#3905]
### Version
1.3.0-dev f24fc2c6757a819ceaf5344bb6ecd5479b0eacb1

### Operating system type + version
Ubuntu 16.04

### Behavior
When overriding settings for the current print with the quick access settings, I click the small green "plus" to access the menu. The menu that pops up is so long, and I have to push the pointer up and down to scroll while search for and accessing the settings that I want. It's not many clicks, but there's a lot of pointer manipulation and accurate aiming involved. Repetitive tasks take a long time, and this design doesn't lend itself well to keyboard shortcuts.

![screenshot from 2017-04-23 16-58-18](https://cloud.githubusercontent.com/assets/684832/25314967/a9fac6cc-284d-11e7-98c4-9a373a38981a.png)

I'm not a GUI guy, so I can't claim to know what is a better design. But I think using menus and submenus would be an improvement, so that the first menu is just 8 entries:

(+)
-> Advanced
-> Extruders
-> Extrusion Width
etc..

And to access the settings under Extruders, you'd have to click the plus, and then click/hover over Extruders, and then find these settings.

Also, the little green plus is small and arguably requires accurate aiming to click on. It's also less accessible when it disappears below the fold and I need to scroll down to find it. In this screenshot, I need to scroll down to find it.

![screenshot from 2017-04-23 16-55-51](https://cloud.githubusercontent.com/assets/684832/25314986/e08be130-284d-11e7-89e2-2833fa69c3b9.png)

**Comment by alexrj** [comment]
@kefir-, I find much faster to click on the cog icon next to the profile menu and change settings from there...

**Comment by kefir-** [comment]
I agree, but doesn't that defeat the purpose of overriding one of the base settings for the current print vs actually changing the settings? I thought that was the idea of the settings configured next to the preview.

**Comment by lordofhyphens** [comment]
The profile would still be dirty, do nothing would be permanent.

**Comment by alexrj** [comment]
Okay, we now have nice submenus:

![schermata 2017-04-29 alle 22 13 28](https://cloud.githubusercontent.com/assets/594957/25558534/2f7e32e0-2d29-11e7-8643-0b4cc993c452.png)
