### ISSUE TITLE
OctoPrint integration broken in latest version

### ISSUE THREAD

**Issue by th0mpy** [alexrj/Slic3r#3906]
### Version
slic3r-1.3.0-dev-f24fc2c

### Operating system type + version
OSX 10.12.4

### Behavior
The problem comes up with an attempt to send code to OctoPrint. I've confirmed both the IP and API key. I've attempted to use both an IP and host name, the same behavior occurs. The error I receive says:
_Error while connecting to the OctoPrint server: 500 LWP::Protocol::request() needs to be overridden in subclasses_

<img width="420" alt="error" src="https://cloud.githubusercontent.com/assets/27927695/25316879/e30ebc44-2833-11e7-8b68-be2f218916ba.png">

#### STL/Config (.ZIP) where problem occurs
[config and stl.zip](https://github.com/alexrj/Slic3r/files/949976/config.and.stl.zip)

**Comment by alexrj** [comment]
Okay, this is a packaging issue. Some module is not being included.

**Comment by alexrj** [comment]
Fixed. I only tested the new OSX package, but I applied the same fix to the other platforms too. Thank you for reporting the issue!
