### ISSUE TITLE
Hello this is related to Replicator Dual... My dual print model is shifting by 1mm... I am using MakerWare

### ISSUE THREAD

**Issue by ShrikantPai123456** [alexrj/Slic3r#3907]
Hi all!!!

My dual print is shifting by 1mm.. Also Belt is tight. ...

Pls tell what to do. ...Pls see the image...
![img_20170420_152247](https://cloud.githubusercontent.com/assets/27852210/25382422/30469f2a-29d5-11e7-9122-da6097114d93.jpg)

**Comment by lordofhyphens** [comment]
So this has nothing to do with Slic3r then?
