### ISSUE TITLE
Slicer unnecessarily inverts faces of model

### ISSUE THREAD

**Issue by kwasmich** [alexrj/Slic3r#3909]
### Version
1.2.9.99 and 1.3.0-dev

### Operating system type + version
OS X El Capitan 10.11.6

### Behavior
* Parts of a particular model are not converted into slices.
* Get the Thingiverse model for a [Canon EF Lens adapter](http://www.thingiverse.com/thing:909176)
  * Import "picam_ef_adapter_v2.1.stl" into Slic3r
  * You will notice oddities in the upper parts of the model. Looks like front face culling.
* The other model "picam_ef_adapter.stl" for a different camera does not show this issue and can be sliced correctly
* The upper part of the model "_v2.1" is missing completely.
  * ![3d](https://cloud.githubusercontent.com/assets/6500650/25450222/77b5e5f2-2abe-11e7-9772-cfb7969ca616.png)
  * ![preview](https://cloud.githubusercontent.com/assets/6500650/25450223/77ebc280-2abe-11e7-9496-6fb370f547a9.png)

I tried Blender, MeshLab, OpenFlipper, OpenSCAD and FreeCAD to somehow "fix" the model without success. Each of those show the model correctly. I tried to either export into STL directly or by using an intermediate format like OFF and convert into STL afterwards. None worked.

The information about the Manifold shows that 56 Facets have been flipped. In my eyes it looks like they have been unnecessarily flipped, thus causing the issue. So I suspect the model loading or issue detection in Slic3r is faulty
  * ![manifold](https://cloud.githubusercontent.com/assets/6500650/25450224/77ec900c-2abe-11e7-8a6b-04070772444e.png)

Cura is able to slice it correctly.

#### STL/Config (.ZIP) where problem occurs
[Archiv.zip](https://github.com/alexrj/Slic3r/files/959447/Archiv.zip)

**Comment by lordofhyphens** [comment]
It's using the repair facilities of admesh.

Netfabb's online service tool https://service.netfabb.com/service.php repairs the model just fine. 

![image](https://cloud.githubusercontent.com/assets/31754/25451403/ae06aef2-2a87-11e7-9a96-710bceeb7b27.png)
