### ISSUE TITLE
Slic3r does not finish gcode file

### ISSUE THREAD

**Issue by Louis-Cypher** [alexrj/Slic3r#3922]
### Version
1.3.0 dev

### Operating system type + version
Windows 7 64bit

### Behavior
* Export of gcode stops. Slic3r says export finished (see screenshot) but in Windows explorer there is only a gcode.tmp file visible

* Slice file and try to export gcode

#### STL/Config (.ZIP) where problem occurs
_Upload a zipped copy of an STL and your config (`File -> Export Config`)_

![slicrwindow](https://cloud.githubusercontent.com/assets/10894095/25615765/5bd94296-2f39-11e7-9a21-5c0113351c17.png)

I sadly cannot upload ANY zip file.  Hence only, the config called config.txt
[config.txt](https://github.com/alexrj/Slic3r/files/970248/config.txt)
. The stl is the one from thingiverse ( http://www.thingiverse.com/thing:730263 ). Please scale it to 91%

Best,

Markus

**Comment by Louis-Cypher** [comment]
The most current build (today) even doesn't read the stl file.

**Comment by foreachthing** [comment]
You cannot have öäü in your path or filename!
I just had the same issue today! :-)

**Comment by Louis-Cypher** [comment]
But I was able to open that file with the build from a couple of weeks ago yesterday (and still am). Isn't this a bug?

**Comment by foreachthing** [comment]
@Louis-Cypher that's what I thought, too! I'm glad you brought it up.
It's no major bug and easy to work around but pretty annoying for us with öäü on our keyboards.

**Comment by Louis-Cypher** [comment]
The problem doesn't occur in the current build as soon as I remove the "ä" from the path.

**Comment by alexrj** [comment]
That bug is #2955

**Comment by Louis-Cypher** [comment]
I don't think so:

Shouldn't loaded config be saved automatically ? #2995

Zitat von Alessandro Ranellucci <notifications@github.com>:

> That bug is #2955
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/alexrj/Slic3r/issues/3922#issuecomment-298633106


-- 
Markus Grebenstein
Adolf-Sturm-Straße 12
82211 Herrsching
