### ISSUE TITLE
Slic3r doesn't open files in paths with "ä"

### ISSUE THREAD

**Issue by Louis-Cypher** [alexrj/Slic3r#3923]
### Version
_Version of Slic3r used goes here_

1.3.0 dev buildbot 2.5.2017
### Operating system type + version
_Win 7 64it_

### Behavior
* Slic3r doesn't open files in paths with "ä". It complains about not being able to read the STL (which is not true; it can be opened in a different path)
* _Steps needed to reproduce the problem_
  * generate a path having an Ä
   * Try to open a stlfile in path
![unbenannt](https://cloud.githubusercontent.com/assets/10894095/25619430/1e1684a2-2f4b-11e7-85db-fb80dba6af92.png)

_
#### STL/Config (.ZIP) where problem occurs
Not related to any config

**Comment by lordofhyphens** [comment]
#3763

Dupe (same underlying problem, exacerbated by how Windows does things).

**Comment by lordofhyphens** [comment]
@Louis-Cypher Recommend following #2955

**Comment by alexrj** [comment]
This was fixed now. It can be tested with the latest dev build available at http://dl.slic3r.org/dev/win
