### ISSUE TITLE
Bridge issue

### ISSUE THREAD

**Issue by dobrzann** [alexrj/Slic3r#3924]
### Version
1.3.0

### Operating system type + version
Win10 x64

### Behavior
Is this a bridge problem or it should be as it is.
Any ideas?

Is it possible to print this model without full support?

![picture](https://cloud.githubusercontent.com/assets/25279164/25620260/2148d384-2f4e-11e7-8d64-d01d37a81c63.jpg)

Just open project and generate preview

_Is this a new feature request?_
No

#### STL/Config (.ZIP) where problem occurs
[project and config.zip](https://github.com/alexrj/Slic3r/files/970643/project.and.config.zip)

**Comment by lordofhyphens** [comment]
This is probably related to #3929 which is also probably related to #3195. Moved to that thread and closing this one.
