### ISSUE TITLE
Feature Request: Rotation through GUI, Auto select object info, Layer number on "Layers" view

### ISSUE THREAD

**Issue by chansheunglong** [alexrj/Slic3r#3927]
I have been using Cura and Slic3r for a long time, and something I notice is that while using Slic3r I sometimes rotate the object in the wrong direction, as taken from Cura, I think a visual rotation or being able to rotate the object like Cura will be a time saver and also make it more user-friendly

Another small feature I think will be good is to auto-select the object in the info section so user can instantly see the material cost and size

Also, I have observed while using the layer/preview, there's only "Current Layer Height" but no "Current Layer Number", I think it will also be a small feature that may help someone

**Comment by lordofhyphens** [comment]
One request per issue, please.

Closing as the third item has been discussed already:
https://github.com/alexrj/Slic3r/issues/3783

Feel free to make different issues for each separate thing you are asking for. I will still close them if they are duplicates of existing issues.
