### ISSUE TITLE
Add "perlbrew install-cpanm" to Doc: "Running Slic3r from git on OS X"

### ISSUE THREAD

**Issue by MartinMajewski** [alexrj/Slic3r#3931]
I've performed a clean install of my Mac lately and followed the instructions here to install perlbrew to get the latest Slic3r compiled.

However, installing a clean perlbrew does not automatically install cpanm which is needed.
Installing cpanm as suggested by the Perl error message is misleading because it is the standard way for the system-wide installation.

To get perlbrew and the user space cpanm running the following command is necessary:

`perlbrew install-cpanm`

Please update the instructions.

Best wishes,
Martin

**Comment by lordofhyphens** [comment]
It's a wiki. Knock yourself out.
