### ISSUE TITLE
group of layer parts omitted from gcode

### ISSUE THREAD

**Issue by jluscher** [alexrj/Slic3r#3935]
### Version
1.2.9

### Operating system type + version
Ubuntu 17.04

### Behavior
Layers are partially missing when sliced - beetween a pair of holes but not another(?!).

Preview:
![image](https://cloud.githubusercontent.com/assets/3855331/25752441/e92312a8-317d-11e7-927e-fc7d1dd2e1b6.png)

Close up of preview:
![image](https://cloud.githubusercontent.com/assets/3855331/25752172/1552d6d4-317d-11e7-969b-ba53069aaef8.png)

The imported .stl file looks good:
![image](https://cloud.githubusercontent.com/assets/3855331/25752257/56afaf8a-317d-11e7-9ed9-dae1ccb00cfe.png)

Testing in Cura (for comparison) showed no problem - the preview shows the missing portion is present there:
![image](https://cloud.githubusercontent.com/assets/3855331/25752502/25fcee38-317e-11e7-913d-902977240366.png)

Printed parts from slic3r:
![image](https://cloud.githubusercontent.com/assets/3855331/25753049/c66a8488-317f-11e7-8546-019b8f23ae83.png)

#### STL/Config (.ZIP) where problem occurs
[slic3r_config-and-stl.zip](https://github.com/alexrj/Slic3r/files/979582/slic3r_config-and-stl.zip)

**Comment by xoan** [comment]
Your model has some errors inside the top drill and it is non-manifold.

![screen](https://cloud.githubusercontent.com/assets/288246/25753404/9ae616ba-31bb-11e7-8ea5-703c9605709f.png)

**Comment by alexrj** [comment]
You might also want to try with 1.3.0-dev

**Comment by lordofhyphens** [comment]
Recent build hard-crashes instead on load. 

Ran the model through netfabb online repair, and all is well.
[lamp-bracket_v25_fixed.zip](https://github.com/alexrj/Slic3r/files/994746/lamp-bracket_v25_fixed.zip)
