### ISSUE TITLE
Incorrect description or bug in Print Settings -> Speed -> Infill -> Gaps ?

### ISSUE THREAD

**Issue by Lenbok** [alexrj/Slic3r#3936]
### Version

Git master at version_1.30.0-748-g1d97698

### Operating system type + version
Ubuntu 16.04

### Behavior

The Print Settings -> Speed -> Infill -> Gaps has a description that indicates the value may either be mm or percentage. However if you try to enter a percentage, the value that gets saved is mm (i.e. if you save, then leave and return to the profile, there is no %). In the following screenshot I had saved gaps with "50%":

![image](https://cloud.githubusercontent.com/assets/282098/25769283/3dfb589e-3269-11e7-84ec-6021cb4878b2.png)

So this is either an error in the description (and percentage values are not supported), or a bug in the implementation that doesn't permit saving/loading as percentage values.

**Comment by alexrj** [comment]
Oops, thank you. Fixed now.
