### ISSUE TITLE
Large number of travel GCODES

### ISSUE THREAD

**Issue by wabbitguy** [alexrj/Slic3r#3940]
### Version
slic3r-1.3.0-dev-1d97698.dmg

### Operating system type + version
Mac OS Sierra 10.12.4
Kossel - Marlin 1.1.0 Release

Slicing fidget spinner: 1.2.9 with similar settings generates 7.4MB file.
With 1.3.0 DEV above, 10.4 MEG. Same layer height and fill on both.

Where the huge difference is some of the travel moves. In the 1.2.9 version, the same travel points look like 3 or 4 lines of GCODE. With the 1.3.0 DEV version there well, a lot of very short ones. Which eventually end up at the same place.

The long green line is comprised of a LOT of small moves. The speed suddenly drops way down to process these.

![slic3r_travel_move](https://cloud.githubusercontent.com/assets/8953419/25786508/5c1b155c-334b-11e7-89b8-48794580f13b.png)

The 1.3.0 GCODE (slow travel is on the second layer)
[fidget_spinner_130.gcode.zip](https://github.com/alexrj/Slic3r/files/982070/fidget_spinner_130.gcode.zip)
[fidget_spinner_129.gcode.zip](https://github.com/alexrj/Slic3r/files/982071/fidget_spinner_129.gcode.zip)
[config_stl.zip](https://github.com/alexrj/Slic3r/files/982074/config_stl.zip)

Any idea why the travel has so many points at times, but not always?
----
Doing some slicing tests today and I found the culprit.

Enabled - "Avoid Crossing Perimeters" results in the deluge of travel points.
Disabled - "Avoid Crossing Perimeters" and the travels are back to what 1.2.9 would do (like 3 or 4 lines of GCODE).

Methinks there's some significant logic changes in the "Avoid Crossing Perimeters" in the 1.3.0. Gcode file size with "Avoid Crossing Perimeters" is also very close to what the older 1.2.9 version would generate.

**Comment by alexrj** [comment]
Thank you for reporting this. I fixed it.
