### ISSUE TITLE
Object "Settings" window loses position and size

### ISSUE THREAD

**Issue by cerdeira** [alexrj/Slic3r#3943]
Version

Slic3r Dev commit 8c77f47

Operating system type + version

Win10 64 home

Behavior

When working with several parts you want to use a lot parts Settings window to diferentiate parts slicing properties.
This window opens on the midle of the main program window and is relatively small, usualy you need to move it to a side or so, and need to resize (enlarge) it.

When you close it and reopen it loses the previous position and size, coming back to predefined position and size. 

It would be nice if it could keep actual properties

_Is this a new feature request?_

No

**Comment by alexrj** [comment]
Right! Done.
