### ISSUE TITLE
Large chunk missing from layers compared to 3D view

### ISSUE THREAD

**Issue by larsrc** [alexrj/Slic3r#3946]
### Version
1.3.0-dev Mac build from 2017-05-10

Config: 
[slic3r-config.ini.zip](https://github.com/alexrj/Slic3r/files/994345/slic3r-config.ini.zip)

### Operating system type + version
Mac OS 10.12.4

### Behavior
* _Describe the problem_
Model that looks nice in the 3D view has big sections missing in the sliced view.

* _Steps needed to reproduce the problem_
Load the Battery_dispenser_extension.stl from http://www.thingiverse.com/thing:399744/#files 
Slice it.

* _Expected Results_

The layers in the sliced view correspond to how it looks in the 3D view

* _Actual Results_
3D View: ![extension-3d](https://cloud.githubusercontent.com/assets/1194334/25970330/83b79450-3698-11e7-98a4-d108763adf46.png)

Sliced preview: ![extension-sliced](https://cloud.githubusercontent.com/assets/1194334/25970329/83b37de8-3698-11e7-8dcb-605846519f8e.png)

#### STL/Config (.ZIP) where problem occurs

[Battery_dispenser_extension.stl.zip](https://github.com/alexrj/Slic3r/files/994334/Battery_dispenser_extension.stl.zip)

**Comment by xoan** [comment]
The model has non-manifold errors:

![captura de pantalla_2017-05-11_23-42-44](https://cloud.githubusercontent.com/assets/288246/25973285/ba180e8e-36a3-11e7-82e3-3f0b7f8782de.png)

**Comment by lordofhyphens** [comment]
Confirmed on Windows that model is garbage. When you see "auto repaired", trust nothing. 
![image](https://cloud.githubusercontent.com/assets/31754/25973420/9eaa6546-3669-11e7-8242-89ec1b7bdd28.png)

**Comment by lordofhyphens** [comment]
http://service.netfabb.com

**Comment by larsrc** [comment]
So the "auto repaired" message should actually read "attempted repaired" - there's no guaranteed that it's repaired.
