### ISSUE TITLE
*_preset placeholders not replacing with name. 

### ISSUE THREAD

**Issue by bah2830** [alexrj/Slic3r#3960]
### Version
1.3.0

### Operating system type + version
Mac OSX 10.12.4

### Behavior
When using [filament_preset] or [print_preset] in my custom g code or file output I get an unexpected output.

Custom start g-code
```
; Filament - [filament_preset]
; Print - [print_preset]
```

Output in G-code
```
; Filament - ARRAY(0x7ff6c6170948)
; Print - ARRAY(0x7ff6a813cb40)
```

### Expected Behavior
The preset name

**Comment by lordofhyphens** [comment]
Was fixed.
