### ISSUE TITLE
Temperature for "Other Layers" applied to first layer when Ooze Prevention is enabled.

### ISSUE THREAD

**Issue by thuSkywalker** [alexrj/Slic3r#3964]
### Version
slic3r-master.2017.05.17.1053.5f6214b.64bit

### Operating system type + version
Windows 10 64bit

### Behavior
Use a printer with 2 extruders, G-code flavor is Sailfish(Makerbot)
Both extruders set to 230C for the first layer and 210C for other layers.
Enable Ooze prevention and delta T is -5C.
Arrange a model using both extruders.
Generated G-code after Start G-code:

```
M104 S225 T0 ; set temperature
M6 T0 ; wait for temperature to be reached
M104 S225 T1 ; set temperature
M6 T1 ; wait for temperature to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M108 T0 ; change extruder
M104 S210 T0 ; set temperature (**expected S230 here**)
M6 T0 ; wait for temperature to be reached
M73 P0 ; update progress
G1 Z0.400 F7800.000 ; move to next layer (0)
G1 X67.226 Y30.409 F7800.000 ; move to first skirt point
G1 F1800
G1 X67.210 Y32.240 E0.15660 ; skirt
G1 X67.123 Y33.793 E0.28953 ; skirt
G1 X67.030 Y34.812 E0.37701 ; skirt
...
```

#### STL/Config (.ZIP) where problem occurs
[config.zip](https://github.com/alexrj/Slic3r/files/1010495/config.zip)

**Comment by alexrj** [comment]
Good catch! I fixed this, and added a regression test to the test suite.
