### ISSUE TITLE
Recent (currently latest) git fails to build. 

### ISSUE THREAD

**Issue by rewolff** [alexrj/Slic3r#3969]
### Version
c4fe123b321be59cc5ed7c7d382bfefde64a19fd

### Operating system type + version
Ubuntu 16.04.2 AMD64. 

### Behavior
Fails to build with: 
```
In file included from src/libslic3r/Layer.hpp:5:0,
                 from src/libslic3r/Model.hpp:7,
                 from src/libslic3r/IO.hpp:5,
                 from src/libslic3r/IO.cpp:1:
src/libslic3r/Flow.hpp:14:6: error: use of enum ‘FlowRole’ without previous declaration

```
as the first error. While version b7544e3c6f32eace65b7bd736cfb6d5f1d664b16 does build. 

P.S. I'm using the hints-and-tips at https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux to compile this. I've never compiled slic3r before. The "download development version"  didn't run, while I have been using 1.2.9 for a while now. Compilation has finished The result seems to work.

**Comment by alexrj** [comment]
Thank you for that, it was a typo left from some documentation work. Fixed now.

**Comment by lordofhyphens** [comment]
Yeah, sorry about that, I was already half asleep when I saw the build
failures.

Thanks to @alexrj for sorting it out.
