### ISSUE TITLE
Unreadable text while printing via USB - white on white

### ISSUE THREAD

**Issue by 7eggert** [alexrj/Slic3r#3977]
### Version
1.3.0 dev 6b68b71-linux-x64 (binary download)

### Behavior
The picture says it all

![dsc00655](https://cloud.githubusercontent.com/assets/924567/26320036/a8013884-3f21-11e7-9f91-6ea3361bbbe6.JPG)

**Comment by lordofhyphens** [comment]
Looks like a strange interaction with your theme.

**Comment by 7eggert** [comment]
Yes, strangely it's not just enough to set one color (foreground/background) to have the other magically match :-)

**Comment by lordofhyphens** [comment]
I didn't realize that @alexrj set any colors at all there.

**Comment by alexrj** [comment]
I should have fixed this, but can't test. @7eggert, do provide feedback!

**Comment by 7eggert** [comment]
7eggert@be10:~/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64$ ./Slic3r --gui
Xlib:  extension "RANDR" missing on display ":0".
Can't locate loadable object for module Wx::AUI in @INC (@INC contains: /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/local-lib/lib/perl5/5.24.0/x86_64-linux-thread-multi /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/local-lib/lib/perl5/5.24.0 /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/local-lib/lib/perl5/x86_64-linux-thread-multi /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/local-lib/lib/perl5 /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/lib ./local-lib/lib/perl5/x86_64-linux-thread-multi ./local-lib/lib/perl5 /home/7eggert/.lib/perl /home/travis/perl5/perlbrew/perls/slic3r-perl/lib/site_perl/5.24.0/x86_64-linux-thread-multi /home/travis/perl5/perlbrew/perls/slic3r-perl/lib/site_perl/5.24.0 /home/travis/perl5/perlbrew/perls/slic3r-perl/lib/5.24.0/x86_64-linux-thread-multi /home/travis/perl5/perlbrew/perls/slic3r-perl/lib/5.24.0 .) at /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/local-lib/lib/perl5/x86_64-linux-thread-multi/Wx/Mini.pm line 78.
Compilation failed in require at /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/local-lib/lib/perl5/Slic3r/GUI/MainFrame.pm line 13.
BEGIN failed--compilation aborted at /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/local-lib/lib/perl5/Slic3r/GUI/MainFrame.pm line 13.
Compilation failed in require at /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/local-lib/lib/perl5/Slic3r/GUI.pm line 33.
BEGIN failed--compilation aborted at /home/7eggert/.lib/slic3r-1.3.0-dev-c22d20b-linux-x64/local-lib/lib/perl5/Slic3r/GUI.pm line 33.
Compilation failed in require at (eval 84) line 1.

**Comment by lordofhyphens** [comment]
@7eggert That should be fixed now (was a packaging bug) as of 6a7057b1ebf09710fa6452013d20b8ea082d01e3. 

Please test!

**Comment by lordofhyphens** [comment]
I just tested it on XFCE-dusk theme which has dark background and white text.

![image](https://cloud.githubusercontent.com/assets/31754/26757903/39745e44-4892-11e7-98dc-4355f27ada73.png)

**Comment by 7eggert** [comment]
Confirmed
