### ISSUE TITLE
Slic3R does not start

### ISSUE THREAD

**Issue by cerdeira** [alexrj/Slic3r#3980]
Version
Dev last commit 3469800

 Operating system type + version
Win 10 64 home

 Behavior
Slic3r does not start, missing dlls.

Is this a new feature request?
no.

**Comment by lordofhyphens** [comment]
There was a desire to "simplify" the root dir of Slic3r, and unfortunately the approach we were using wasn't tested correctly (it worked on our dev systems for the wrong reasons). I've reverted the associated commits.
