### ISSUE TITLE
Height of the skirt can t be modified

### ISSUE THREAD

**Issue by Pydo44** [alexrj/Slic3r#3981]
### Version
1.3.0-dev mac 10.11.5
i have a double extruder

### Behavior
I had put a skirt height at 2000 . like that i was certain to have a skirt for all the print
but it was completely usefull for a pure pla print.
so i change the config to 10 and the skirt stay for all the print.....

i join a gcode generate by slic3r with
 the height set at 10
loop  set at 1
distance set at 1
minimum set at 1

[Accr sup bobine Pydo.txt](https://github.com/alexrj/Slic3r/files/1034221/Accr.sup.bobine.Pydo.txt)

**Comment by Pydo44** [comment]
Hi today for a big shape i had an error message
![capture d ecran 2017-05-30 a 23 46 55](https://cloud.githubusercontent.com/assets/26421644/26606570/bbc6ff26-4592-11e7-93d5-df76a57be502.jpg)

**Comment by Pydo44** [comment]
Ok i can do again the issue
with 1 object on the plater, i choose in the setting for this object the default extruder.
the skirt is at full height
now i choose in the setting of the object the extruder 1 ( all object and support are in the same material) but the skirt can be change in the preview

in the parameter i choose all for extruder 1 and only support/skirt/raft for extruder 2

and at the print the skirt is printed with the extruder 1.....

thanks all

**Comment by Pydo44** [comment]
Eureka ..... I found the problem with the skirt height ....

when you check the ooze prevention option the skirt height is put at the maximum B<

**Comment by alexrj** [comment]
Next time please follow the instructions. We need STL file and config, and proper steps to reproduce the issue. You didn't mention ooze prevention.

**Comment by Pydo44** [comment]
sur i didn't mention it , i didn't know is was checked and ididn't konw how to reproduced the problem

so i warning you for the bug and try to give you the maximum information and you are shooting me..... pfffff
next time if you want a better tester give some money and we spend much time to do the research and correct the software

**Comment by lordofhyphens** [comment]
@Pydo44 The issue description is useless to us without the information asked for in the text you deleted to write it.

Configuration, a model that shows the problem with configuration, and whatever else you did to make it show up. Without that information, we have nowhere to start and as such can do nothing.

Ooze prevention uses the skirt to purge unused extruders.

**Comment by lordofhyphens** [comment]
@Pydo44 neither @alexrj nor I generally get paid for fixing issues like this-we do this in our spare time when we aren't at our real jobs.
