### ISSUE TITLE
Feature Request: Change speed between some layers

### ISSUE THREAD

**Issue by bynobrand** [alexrj/Slic3r#3983]
### Version
_Version of Slic3r used goes here_

_Use `About->About Slic3r` for release versions._

_Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. *Only* use normal Slic3r version IDs._

_For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_

### Operating system type + version
_What OS are you using, and state any version #s_

### Behavior
* _Describe the problem_
Some layers need low speed for better quality

* _Steps needed to reproduce the problem_
  * _If this is a command-line slicing issue, include the options used_
* _Expected Results_
* _Actual Results_
  * _Screenshots from __*Slic3r*__ preview are preferred_

_Is this a new feature request?_
Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 http://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### STL/Config (.ZIP) where problem occurs
_Upload a zipped copy of an STL and your config (`File -> Export Config`)_

**Comment by lordofhyphens** [comment]
So you're missing a few important pieces of information (see http://nickohrn.com/2013/09/write-great-feature-request-bug-report/ for hints) for anyone to consider this report/request. I am going to close this for now, please revise and I will reopen.

Also, consider modifier meshes (http://slic3r.org/blog/modifier-meshes), you can now define and place such meshes in Slic3r itself. 

I've updated the Manual accordingly, it should show up when @alexrj next pushes the update to the live server. 

https://github.com/alexrj/Slic3r-Manual/blob/master/src/advanced/modifier-mesh.md
