### ISSUE TITLE
Win automated dev builds is broken

### ISSUE THREAD

**Issue by cerdeira** [alexrj/Slic3r#3995]
Win automated dev builds is empty after 6a7057b.

**Comment by lordofhyphens** [comment]
Slic3r-master.2017.05.30.1137.c2bdbaf.64bit.zip and 	
Slic3r-master.2017.05.30.1137.c2bdbaf.32bit.zip/ are actually directories, not real archives. I've removed them.

**Comment by lordofhyphens** [comment]
Side note: I accidentally deleted the newest build, rebuilding now,.
