### ISSUE TITLE
3D rendering issues on Fedora 26

### ISSUE THREAD

**Issue by hroncok** [alexrj/Slic3r#4002]
### Version
1.2.9

### Operating system type + version
Linux, Fedora 26 64bit (didn't happen on Fedora 25)

### Behavior
The 3D preview misses the plate and have some extra lines.
![slic3r1](https://cloud.githubusercontent.com/assets/2401856/26725325/4cccd8d0-479e-11e7-9c45-dc0e3578bcec.png)

It only happens with the Fedora package. ten binaries form slic3r.org do not exhibit the issue:
![slic3r2](https://cloud.githubusercontent.com/assets/2401856/26725351/6c885190-479e-11e7-9cd1-bb0384309423.png)

I was thinking maybe it is a dependency problem, but Prusa's Slic3r (Fedora package as well) does not exhibit the problem either.
![slic3r3](https://cloud.githubusercontent.com/assets/2401856/26725372/8c47ad6e-479e-11e7-9c10-eefe079c61f5.png)

I know you might say "the binaries provided work" and close this, but could you please help me investigate what's causing this? Does it look like something you've already seen? Thanks for help.

(Happens with any STL, any config.)

My GL related packages and their versions:

 * perl-OpenGL-0.7000 (was 0.6704 on Fedora 25)
 * perl-Wx-GLCanvas-0.09 (didn't change)

**Comment by lordofhyphens** [comment]
Try installing the Perl local-lib package and installing a copy from
source. It won't hurt your existing system.

See if the behavior exists on that build.

In either case you should contact the Fedora package maintainer.

**Comment by lordofhyphens** [comment]
There were some changes to how the 3d rendering was set up to deal with
opengl changes. The prusa3d branch and -dev have these changes, 1.2.9 would
not.

**Comment by bubnikv** [comment]
@hroncok is the Fedora maintainer :-)

**Comment by lordofhyphens** [comment]
This was a crash issue when it showed up for us #3575 and #3540 by the way, so you're probably ahead of the game ;)

**Comment by hroncok** [comment]
#3575 fixes it, thanks. 
![slic3r4](https://cloud.githubusercontent.com/assets/2401856/26730119/37c3b154-47b0-11e7-8201-3bdb24de6c9d.png)
