### ISSUE TITLE
Slic3r need this feature

### ISSUE THREAD

**Issue by Shahriar57** [alexrj/Slic3r#4011]
Hello , 
im using slic3r for long time , it is just one important thing left for Slic3r .
is it possible out put g-code be same as simplify3d slicer . 
```
; inner perimeter
G1 X208.380 Y141.620 F3000
; outer perimeter
G1 X209.820 Y140.180 F3000
; solid layer
G1 X207.596 Y142.322 F3000
```
as you can to see g-code above ,simplify3d added comment to first line of each section . it make so easy to edit g-code , 
like 
```
; solid layer
M106 S150
G1 X207.596 Y142.322 F3000
M106 S0

```
the point is you can set fan speed for each section , so you can to get nice and smooth surface even with ABS . 
i worked with some g-code viewer to get result same as simplify g-code out put to modify slic3r g-code but it will take long time .
it should be nice to add this feature to slic3r 

Regards ,

**Comment by lordofhyphens** [comment]
General reminder: "Slicer X does this" is not a reason to add something to Slic3r. 

Turn on verbose gcode output in the Advanced print settings menu.

Also see #3132 #2865 #2079
