### ISSUE TITLE
Inner diameter with auto extrusion width

### ISSUE THREAD

**Issue by bonm014** [alexrj/Slic3r#4013]
### Version
1.3.0-dev
Windows 10

I always have too small inner diameters and started to figure out why this is happening.
I reduced the speed, thightend the printer for movement, lowered the temp and/or increased the temp.
Made modification to the STL (openscad modal with 60 vertices to complete a circle, but all without succes.
I noticed the diameter of the inner diameter is always a nozzle size to small. I tested it with different sizes of nozzles (0.2, 0.4 and 0.6)

Then I started to look at the generated GCODE and noticed something strange.
By default I used the default extrusion width slic3r determines (auto/default)
With my 0.6 nozzle it says:
; external perimeters extrusion width = 0.60mm (6.75mm^3/s)
; perimeters extrusion width = 1.01mm (16.96mm^3/s)
; infill extrusion width = 1.01mm (16.96mm^3/s)
; solid infill extrusion width = 1.01mm (14.14mm^3/s)
; top infill extrusion width = 1.01mm (14.14mm^3/s)

I sliced a cylinder with a inner diameter of 3mm
I opened the GCODE within excel and exported only 1 circle of the inner path of de diameter.
The distance of the nozzle from the center is 1.8mm, but with a 1.01mm extrusion this would be too small, right? (I would expect half inner diameter + half extrusion diameter)
Too check it any further I set the extrusion to a fixed width of 0.6 (same as the nozzle). After regenerating the GCODE and analysing it again the GCODE remains the same.... distance of 1.8mm of the center. (3.6 diameter)
But then I changed the fixed extrusion to 0.8mm and my GCODE changed to 1.9mm offset off the center.
So it seems it does check the extrusion diameter, but only when it set to a fixed width.

Could this be the case?
[cylinder 6-3.zip](https://github.com/alexrj/Slic3r/files/1050637/cylinder.6-3.zip)
![extrusion position](https://cloud.githubusercontent.com/assets/7635241/26764707/6930b94a-496c-11e7-8073-93fe91977db2.png)
[gcode.zip](https://github.com/alexrj/Slic3r/files/1050640/gcode.zip)

**Comment by lordofhyphens** [comment]
![image](https://cloud.githubusercontent.com/assets/31754/26765318/386ba1d0-493f-11e7-9094-73abaac13d2a.png)

My diff and screencap indicates no. There is no difference in exported gcode values for any perimeters for using fixed and auto width.

[4013.zip](https://github.com/alexrj/Slic3r/files/1050720/4013.zip)
