### ISSUE TITLE
feature request: generic alternative to octoprint print server

### ISSUE THREAD

**Issue by rob-miller** [alexrj/Slic3r#4022]
### Operating system OS X El Capitan 10.11.6 (old iMac)
I used to use OctoPrint/OctoPi, but now I have a DuetWifi.  I wish I could still use the 'send to printer' button.  Duet supports a different POST method to upload files (see [DuetWebControl ReadMe](https://github.com/chrishamm/DuetWebControl/blob/master/README.md) and/or [forum posting](https://www.duet3d.com/forum/thread.php?pid=9032#p9032)) and apparently ftp although not certain ftp works across all versions.  In any event it is likely I could come up with a command line to implement the transfer.  As there will be other print servers to support with 'send to printer' a more generic option is desirable.

I think this could be implemented by adding a text box for the transfer command next to the OctoPrint API key box, and if this box is filled then use it in preference to the inbuilt OctoPrint transfer command.  More features like the 'overwrite existing file' and 'start print' would be great too, possibly tied to symbols in the command line, but that is outside the core functionality (a button to execute an external command with the output G-code).

Yes I could implement this as others have done by having a script watching the 'export G-code' output directory, but that still leaves me with extra dialogues for file name and overwriting existing files, and depending on implementation I would need to change more things when I actually want to look at the G-code before printing.

Apologies if I have missed some existing way to implement this.

**Comment by lordofhyphens** [comment]
Going to consider this closed for now with the duet commit; I don't see a need to architect some master "use this on your firmware to enable print from Slic3r" at this time; we can refactor later as needed.
