### ISSUE TITLE
OpenGL.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)

### ISSUE THREAD

**Issue by Fahim-Ferdous** [alexrj/Slic3r#4025]
So I tried to install and run my installation but whenever I call $ slic3r --gui, I get this message:
OpenGL.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)
I tried reinstalling all the packages but nothing happens... This problem started when I tried to update the package using yaourt -Syu --aur
before that, it was running just fine.

Version: 1.2.9
OS: Arch Linux

**Comment by lordofhyphens** [comment]
If this is the AUR or the normal package, contact its maintainer. Odds are your version of system perl changed at some point (hence the mismatch). We can't support the Arch package (it's not our work) here.

In the meantime, give the download at http://dl.slic3r.org/dev/linux a try.

**Comment by Fahim-Ferdous** [comment]
Thanks @lordofhyphens  :)

**Comment by NateTG** [comment]
I ran into something similar recently that affected slic3r and Build.PL.    It would be nice if there was some kind of 'make clean' equivalent

**Comment by lordofhyphens** [comment]
@NateTG delete local-lib dir.
