### ISSUE TITLE
Feature Request: sequential printing + spiral vase

### ISSUE THREAD

**Issue by JesusFreke** [alexrj/Slic3r#4043]
### Version
v1.34.1-prusa36-linux64

### Operating system type + version
Ubuntu 14.04.5

### Behavior
1. Plate multiple objects 
2. Turn on "Spiral vase" option
3. Turn on "Complete individual objects" option
3. "Slice Now"
4. Get error saying "The Spiral Vase option can only be used when printing a single object."

It makes sense not to allow multiple objects when not using sequential printing, of course. But there shouldn't be any reason you can't spiral print one complete object and then spiral print the next complete object.

**Comment by lordofhyphens** [comment]
Reminder: we're not prusa3d, so please write issues against dl.slic3r.org builds.

You're in luck this time as I am fairly certain that this behavior is the same ;)

**Comment by JesusFreke** [comment]
Sorry about that! I just assumed this wasn't prusa-specific behavior and didn't even consider whether I should verify it on the "pure" slic3r build. I should have known better :)

**Comment by lordofhyphens** [comment]
Huh, this should be already a thing. 

PrintConfig.cpp:679

**Comment by JesusFreke** [comment]
https://github.com/alexrj/Slic3r/blob/master/xs/src/libslic3r/PrintConfig.cpp#L679 ? Hmm. doesn't look related to spiral/sequential slicing, but I'm not familiar with the codebase..

**Comment by lordofhyphens** [comment]
That line is the check to do spiral vase + multiple complete objects. It's incorrectly implemented. Fixed now.

**Comment by lordofhyphens** [comment]
Wait about 20 minutes or so and the AppImage and build will be ready at http://dl.slic3r.org/dev/linux (aa20fb6 will be present in the name)

**Comment by lordofhyphens** [comment]
https://travis-ci.org/alexrj/Slic3r/builds/245967010 if you want to watch it go ;)

**Comment by JesusFreke** [comment]
Oh, you meant Print.cpp:679 :)

Anywhoo, Thanks! I'll give it a shot tonight.

**Comment by lordofhyphens** [comment]
http://dl.slic3r.org/dev/linux/Slic3r-1.3.0-dev-837be65-x86_64.AppImage
http://dl.slic3r.org/dev/linux/slic3r-1.3.0-dev-837be65-linux-x64.tar.bz2

**Comment by JesusFreke** [comment]
This is now working nicely with the fix. Thanks! :)
