### ISSUE TITLE
Feature request: Make printing supports cheaper, save expensive dissolvable filament

### ISSUE THREAD

**Issue by Mike13815** [alexrj/Slic3r#4044]
Feature request:

Adding a feature to print supports using both the main extruder and the support extruder, filling bulk with the cheap main material. 

Description: 
PVA is expensive but dissolves well. It would be efficient to print support material 99% in the cheap main material (PLA, ABS, etc) and only use the dissolvable filament on the points that connect the supports to the main print object. These are the only points that need to be dissolved anyway for most supports.

Benefits: Cheaper prints, less wasted support material. Less wasted material overall as most plastics can be recycled but PVA typically is not. 

Drawbacks: The slicer would have to detect where support touches the main print to change material, could take slightly longer to slice and to print that specific area.

Anecdotal note: PVA is $35/kg while PLA can be had $12/kg. I find myself taking risky support configurations specifically to avoid wasting material.

Thank you!

**Comment by VanessaE** [comment]
That feature already exists.  Print Settings -> Multiple Extruders -> "Support material/raft interface"

See also https://github.com/alexrj/Slic3r/issues/3316
