### ISSUE TITLE
Multiple Extrusers with different diameters/extrusion multiplier

### ISSUE THREAD

**Issue by tps42** [alexrj/Slic3r#4057]
### Version
          ALL
          example: 1.3.0-dev

### Operating system type + version
           windows

### Behavior
            Using different extruders with different filament diameter results in "random" results.
Example: 
extruder 0: diameter 3mm, extrusion multiplier 1.1
extruder 1: diameter 1.75mm, extrusion multiplier 1.2

Insert to "Printer Settings"/"Custom G-Code":
; filamentDiameter=[filament_diameter]
; filamentDiameter0=[filament_diameter_0]
; filamentDiameter1=[filament_diameter_1]
; filamentDiameter2=[filament_diameter_2] 
; filamentDiameter3=[filament_diameter_3]
; extrusionMultiplier=[extrusion_multiplier]
; extrusionMultiplier0=[extrusion_multiplier_0]
; extrusionMultiplier1=[extrusion_multiplier_1]
; extrusionMultiplier2=[extrusion_multiplier_2]
; extrusionMultiplier3=[extrusion_multiplier_3]

Slice ONE object 2 times (no special settings in "multiple extruder" - only one extruder shall be used for print: 
1. select first extruder for object in Positioning 
2. select second extruder for object in Positioning

Results are ... errrrr ... unexpected:
1. 
; filamentDiameter=3
; filamentDiameter0=3
; filamentDiameter1=7
; filamentDiameter2=1.75 
; filamentDiameter3=7
; extrusionMultiplier=1.1
; extrusionMultiplier0=1.1
; extrusionMultiplier1=1.2
; extrusionMultiplier2=1.1
; extrusionMultiplier3=1.1

i got multipliers korrekt but diameters wrong! "7"???? what the hell?

2. 
dont remember but it was not better than the first slice.

_Is this a new feature request?_
                no feature request

**Comment by lordofhyphens** [comment]
Please include an exported configuration (CTRL+E) file.

**Comment by tps42** [comment]
While exporting slic3r configuration i was able to investigate further:
This is not a slic3r bug. The problem emerges in combination with repetierhost (v2.01) only!

So please mark this one as invalid - sorry for that!

cu. tps42

**Comment by lordofhyphens** [comment]
As a reminder you can control your printer directly from Slic3r now. No need for RepHost ;)

**Comment by tps42** [comment]
My printer is driven by repetierserver (network).Slic3r has only restricted support for network control (manual control of movement, temperatures, etc.) so using slic3r only is no option for me.
Thanx anyway!
Cu.tim

-------- Ursprüngliche Nachricht --------
Von: Joseph Lenox <notifications@github.com> 
Datum: 16.07.2017  18:39  (GMT+01:00) 
An: alexrj/Slic3r <Slic3r@noreply.github.com> 
Cc: tps42 <tim@aptico.de>, State change <state_change@noreply.github.com> 
Betreff: Re: [alexrj/Slic3r] Multiple Extrusers with different diameters/extrusion multiplier (#4057)
