### ISSUE TITLE
With "External perimeters first"  turned on, only print perimeters first for non-overhanging perimeters

### ISSUE THREAD

**Issue by Pointedstick** [alexrj/Slic3r#4063]
### Version
1.29

### Operating system type + version
Kubuntu 17.04

### Behavior
With "External perimeters first" turned on, overhangs get this behavior too, resulting in ugliness. External perimeters should only be printed first if they do not overhang the previous layer.

**Comment by VanessaE** [comment]
That's covered in this issue:  https://github.com/alexrj/Slic3r/issues/3950

**Comment by Pointedstick** [comment]
Thanks!
