### ISSUE TITLE
Question: How to check if model will fit in build volume?

### ISSUE THREAD

**Issue by mmiscool** [alexrj/Slic3r#4069]
Hello. 

I have been using slic3r from the command line successfully in a project. It has been working well. 

I want to inquire as to how to check if a part will fit on the build plate. Is there a method to do this?

**Comment by xoan** [comment]
You can use `--info` option to get `size_x`, `size_y` and `size_z`.

**Comment by mmiscool** [comment]
Thanks. That worked perfectly.
