### ISSUE TITLE
Installing local::lib fail

### ISSUE THREAD

**Issue by sauvik3** [alexrj/Slic3r#4091]
### Version
1.3.0 dev

### Operating system
Windows 7 Professional SP1

### Build Configuration
1. Boost 1.63.0
2. Citrus perl 5.24.1 x64
3. Slic3r Dependencies 5.24.0 win seh gcc6.3.0 x64

### Build Error
Installing local::lib fails. In the build log, the PATH_CHECK test fails because of ordering
of resultant variables. I was able to continue build however with --force option.

#### STL/Config (.ZIP) where problem occurs
[1503305954.5452.zip](https://github.com/alexrj/Slic3r/files/1238401/1503305954.5452.zip)

**Comment by lordofhyphens** [comment]
Don't use CitrusPerl.
