### ISSUE TITLE
Feature Request: Automatic Variable Layer Height Calculator / Adaptive Slicing

### ISSUE THREAD

**Issue by NateTG** [alexrj/Slic3r#4095]
Currently the variable layer height interface calls on the user to manually set the layer heights for the object, but there's a relatively simple way to calculate them if we know how much we want the filament extrusions to overlap.

If we have a max step over s, and a facet whose unit normal has non-zero z-component N_z, then a layer height of no more than s * sqrt(N_z^-2 - 1) will ensure that the step over is less than or equal to s.

Facets with N_z equal to zero will always have zero step-over because they are vertical so they can use some maximum layer height.

We know where the top and bottom of each facet is, so we can calculate an interval and a maximum layer height for each facet, and then merge those intervals to generate a layer height profile for the entire print.

**Comment by Tinchus2009** [comment]
Sorry, is there now a variable layer height setting?

**Comment by NateTG** [comment]
> Sorry, is there now a variable layer height setting?

There's a manual one that's been around for a while.

http://manual.slic3r.org/expert-mode/variable-layer-height

**Comment by lordofhyphens** [comment]
https://github.com/alexrj/Slic3r/pull/1386 Anything to do with this?

**Comment by lordofhyphens** [comment]
Also, the GcodeTimeEstimator class is currently being called by the Host/Controller for its estimates.

**Comment by NateTG** [comment]
> #1386 Anything to do with this?

Definitely.  I'm not sure why I didn't find it while searching.  This could reasonably be considered a dup.

The referenced thesis is not linked to anymore.

I'm not sure what "GcodeTimeEstimator" has to do with this.

**Comment by lordofhyphens** [comment]
Just me derping. #close

**Comment by lordofhyphens** [comment]
@NateTG Also, adaptive slicing is now merged.
