### ISSUE TITLE
Desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [alexrj/Slic3r#4109]
Desktop file does not pass desktop-file-validate. The `Version=` line in the desktop file is _not_ meant for the Slic3r version, but for the version of the XDG desktop format spec.

`Slic3r.desktop: error: value "1.3.0-dev" for key "Version" in group "Desktop Entry" is not a known version`.

__Solution:__ Delete the `Version=` line in the desktop file and then run the desktop file through `desktop-file-validate` to see if it reports any errors.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/271179474#L585

**Comment by lordofhyphens** [comment]
No other errors reported from `desktop-file-validate`.
