### ISSUE TITLE
Double clicking the AppImage or launching it from the menu does nothing

### ISSUE THREAD

**Issue by probonopd** [alexrj/Slic3r#4111]
### Version

Slic3r-1.3.0-dev-66074f5-x86_64.AppImage

### Operating system type + version

Ubuntu 14.04

### Behavior
* Double clicking the AppImage or launching it from the menu results in nothing

There are three ways around it
1. Make Slic3r show the GUI by default, unless a switch like `--no-gui` is used, __or__
2. Edit https://github.com/alexrj/Slic3r/blob/66074f53989d312e8447c4de504d0602fd16ff42/package/linux/appimage.sh#L57 to include --gui, __or__
3. Add `Console=true` to the desktop file (resulting in a terminal window to open rather than the GUI)

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/271212954#L598

**Comment by probonopd** [comment]
Why would you do both? I'd say only add `--gui` and that should be it.

**Comment by lordofhyphens** [comment]
Because the default is to fire up the gui if everything works and you don't have CLI arguments. If something is broken re: gui then it defaults to the CLI interface.

Can you pass --gui to invoking the AppImage (from a terminal) and see what gets spit out?

**Comment by probonopd** [comment]
If I launch the AppImage with `--gui`, then it works.

**Comment by lordofhyphens** [comment]
Interesting. Then adding it to appimage.sh should be fine then.

**Comment by probonopd** [comment]
Indeed. :+1:

**Comment by lordofhyphens** [comment]
I've added it; which required adding a new UI flag (in case you want to run the AppImage in CLI mode): `--no-gui`

**Comment by lordofhyphens** [comment]
Closed via d6469b28.

**Comment by probonopd** [comment]
Thank you. Can you trigger a build on https://dl.slic3r.org/dev/linux/ please?

**Comment by lordofhyphens** [comment]
It's triggered on pushing commits, so it's done already.

**Comment by lordofhyphens** [comment]
https://travis-ci.org/alexrj/Slic3r/builds if you need to check the Linux build state in the future.

**Comment by probonopd** [comment]
What would be awesome would be a link to the latest stable and the latest continuous build that would redirect to the respective file... that would help for the AppImageHub central directory of available AppImages, and other app collections.

**Comment by lordofhyphens** [comment]
@alexrj would need to sort  that out, as the webserver is under his  control. You should open a new issue for that.

There won't be an AppImage of 1.2.9 ever though.

**Comment by probonopd** [comment]
https://dl.slic3r.org/dev/linux/Slic3r-1.3.0-dev-c84bc71-x86_64.AppImage still does not launch the GUI... 

https://travis-ci.org/AppImage/appimage.github.io/builds/271433211#L596

**Comment by probonopd** [comment]
Now it doesn't show the GUI anymore even when the AppImage is invoked with `--gui` on the command line. At least this worked before.

**Comment by lordofhyphens** [comment]
Oh boy, wonder what I broke there. :/

**Comment by lordofhyphens** [comment]
Should be fixed as of next build
