### ISSUE TITLE
Permalink to the latest stable and the latest continuous builds

### ISSUE THREAD

**Issue by probonopd** [alexrj/Slic3r#4112]
What would be awesome would be a link to the latest stable and the latest continuous build that would redirect to the respective file... that would help for the AppImageHub central directory of available AppImages, and other app collections.

**Comment by lordofhyphens** [comment]
I can get the continuous build in a relatively straightforward manner (adding the symlink during sftp).

**Comment by lordofhyphens** [comment]
Should work now for Linux and OSX dev builds. I'm not sure it's particularly useful for the Windows folks

**Comment by lordofhyphens** [comment]
Added to Linux builds as of 2d9580edb4c0e0ea157879ddf1d781460d1bbfa8

OSX is currently done through the Jenkins server, so no commit for that.

**Comment by lordofhyphens** [comment]
https://dl.slic3r.org/dev/linux/Slic3r-master-latest.AppImage is the symlink to the latest AppImage
