### ISSUE TITLE
Feature request: Move models around in Z in plater.

### ISSUE THREAD

**Issue by wjflier** [alexrj/Slic3r#4118]
It would be great to be able to move the model in the z direction, especially for two extruder systems.
Unless I'm missing something.

**Comment by lordofhyphens** [comment]
Can you describe why you need it more clearly?

**Comment by wjflier** [comment]
example would be placing an object on the top of another item and print in two colors, such as a butterfly on a box, or one item i redesigned was an extruder block with and existing bowden fitting. 
<img width="960" alt="test1" src="https://user-images.githubusercontent.com/8867508/30040328-cea68ce6-91ab-11e7-8d86-0f339b4d5a49.png">  here I placed the block on top of the fitting to make one stl.  This was done in Craftware.  I prefer Slic3r and think this could be a great addition.

**Comment by lordofhyphens** [comment]
How about in the Object Settings panel, with the same mechanics as moving modifier meshes?

![image](https://user-images.githubusercontent.com/31754/30043507-5c572f94-91bd-11e7-9fd8-b0119a4a98fc.png)

**Comment by lordofhyphens** [comment]
https://ci.appveyor.com/project/lordofhyphens/slic3r/build/1.3.0-move-object-mesh-1367 

See the pull request when the build completes, this should show up in a build in https://dl.slic3r.org/dev/win/branches

**Comment by wjflier** [comment]
That works, I thought it was there somewhere.  Appreciate the help.

**Comment by lordofhyphens** [comment]
It was while I was first implementing moving modifier meshes.

Everyone at the time thought that there wasn't a use for being able to move
the parts too.

**Comment by wjflier** [comment]
I combine stls a lot.  And I prefer Slic3r.  It's nice to have the ability in Slic3r to mod parts.
Thanks
