### ISSUE TITLE
Make a custom adjust

### ISSUE THREAD

**Issue by paulorfmmb** [alexrj/Slic3r#4125]
Hi,

I'm doing some modifications to the code for a special case that I'm using, and I want to make the layer height none dependent from the nozzle diameter. But I'm not having success doing it, can someone help me?

Thanks.

**Comment by lordofhyphens** [comment]
In general, I highly recommend getting used to `grep` or a tool like it. All of the configuration options will show up by their names in the configuration file, so it's the quickest way to find out what is used where.

In your specific case, it's probably wrapped up in max_allowed_layer_height() in xs/src/libslic3r/Print.cpp.

You can probably cheat a bit by setting more than one extruder and setting the diameter of that extruder to be something big.

These files have a reference to layer_height:
````
GCode/SpiralVase.cpp
GCodeWriter.cpp
IO/AMF.cpp
Layer.hpp
LayerRegionFill.cpp
Model.cpp
Model.hpp
PerimeterGenerator.cpp
PerimeterGenerator.hpp
PrintConfig.cpp
PrintConfig.hpp
Print.cpp
Print.hpp
PrintObject.cpp
PrintRegion.cpp
SLAPrint.cpp
````
and nozzle_diameter:
````
Flow.cpp
Flow.hpp
GCode.cpp
LayerRegionFill.cpp
PerimeterGenerator.cpp
PrintConfig.cpp
PrintConfig.hpp
Print.cpp
PrintObject.cpp
PrintRegion.cpp
````
