### ISSUE TITLE
Unreasonable maximum baud rate limit

### ISSUE THREAD

**Issue by paulfertser** [alexrj/Slic3r#4131]
Hello,
With today's 1.2.9-1140-g1a2df5e4 I'm seeing the serial controller baud rate to be limited to 300000.
I have set my printer to use 500000 to be able to upload files to a uSD card faster, and it seems to work properly (with 1M I'm getting plenty of checksum errors). That's with an old atmega + ch341 usb-uart bridge, and modern microcontrollers with integrated USB peripheral can obviously go much higher.
Please consider removing the limitation.
TIA

**Comment by lordofhyphens** [comment]
Done.
