### ISSUE TITLE
Volumetric 

### ISSUE THREAD

**Issue by jtmoderate876** [alexrj/Slic3r#4133]
### Version
1.37.1-prusa3d-win32
_Version of Slic3r used goes here_

_Use `About->About Slic3r` for release versions._

_Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. *Only* use normal Slic3r version IDs._

_For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_

### Operating system type + version
windows 10 - 32bit
### Behavior
Max volumetric slope positive and Max volumetric slope negetive ignore stops, gaps and retractions.
These two features have the potential to really improve bowden "slop" by easing into stops and starts but they ignore stops and starts and seem to only calculate volumetric flow based upon 

Behavior: extrusion in prints does not slow down before gaps or non-print moves

Expected Behavior: it would be of great value if Max volumetric slope was enforced for gaps, non-print moves and retractions.

**Comment by lordofhyphens** [comment]
>Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. Only use normal Slic3r version IDs.

Will reopen if you test on mainline Slic3r and provide everything else that is commonly asked for (model seeing problems on, config, etc).
