### ISSUE TITLE
Double extension on output files when cutting stl on CLI

### ISSUE THREAD

**Issue by Alberto-Vivar** [alexrj/Slic3r#4136]
### Version
1.2.9

### Operating system type + version
macOS Sierra 10.12.6

### Behavior
Whenever I try to cut an stl file on the CLI version, I call the program as usual:
\> slic3r_alias --cut 10 selected_file.stl
So it should appear two files, named the same as the input file but with _lower and _upper appending to its name. The convention is, there should be only a point into a filename only to mark an extension. So, the files you expect to be generated should be named "selected_file_upper.stl" and "selected_file_lower.stl", but instead "selected_file.stl_upper.stl" and "selected_file.stl_lower.stl" will show.

I'm not familiar with C++ for sure, but reading some code i find on [this file](https://github.com/alexrj/Slic3r/blob/5cd9ecbe5701b1357b97b7c965d53dde6da91a40/src/slic3r.cpp) at the lines 144-145
```
// Remove the previous extension and add .3mf extention.
outfile = outfile.substr(0, outfile.find_first_of('.')) + ".3mf";
```
This is on the case of exporting a 3mf file.
So, in the case we cut an stl file and save the upper and lower sections, the code isn't removing the extension on the file before adding the "_upper" and "_lower". Couldn't it be changed from this:

Lines 168 and 172:
```
IO::STL::write(m, upper.input_file + "_upper.stl");
//...
IO::STL::write(m, lower.input_file + "_lower.stl");
```

To something like this?
```
std::string outfile = upper.input_file;
outfile_base = outfile.substr(0, outfile.find_first_of('.'));
IO::STL::write(m, outfile_base + "_upper.stl");
//...
IO::STL::write(m, outfile_base + "_lower.stl");
```

**Comment by lordofhyphens** [comment]
There you go. It'll drop the output file in a directory where the source file is as well.
