### ISSUE TITLE
This machine config breaks Slic3r

### ISSUE THREAD

**Issue by Kolodner** [alexrj/Slic3r#4137]
### Version
I've tried both 1.2.9 and the most current 1.3.0-dev build, and a current Prusa version so far.

### Operating system type + version
_Windows 10 v1703_
_Sager NP9170 laptop with a GTX 680M with current drivers_

### Behavior
* _On attempting to load the following machine definition, Slic3r crashes in all the versions I've tried. This used to work at a previous point in time, so I'm not sure what has broken along the way:_
[https://www.dropbox.com/s/b38bbwlumxtovs5/Slic3r_config_DVT4_20150812.ini?dl=0](https://www.dropbox.com/s/b38bbwlumxtovs5/Slic3r_config_DVT4_20150812.ini?dl=0)
* _Steps to reproduce:_
1) Start a clean version of Slic3r
2) Try to load this config file. 
* _Expected Results_
It would load the machine parameters.
* _Actual Results_
It Crashes
  * _Screenshots from __*Slic3r*__ preview are preferred_

#### STL/Config (.ZIP) where problem occurs
_Upload a zipped copy of an STL and your config (`File -> Export Config`)_
I've included a link to the file in my Dropbox above, didn't bother zipping because it's so small.

**Comment by lordofhyphens** [comment]
Can you just zip the config and drop it into the web interface for github?

**Comment by lordofhyphens** [comment]
That's a STL bed shape, isn't it?

I can't reproduce with https://dl.slic3r.org/dev/win/Slic3r-master.2017.09.24.1383.5514c84.64bit.zip

**Comment by Kolodner** [comment]
I believe that's in there, yes. It's got a rectangular build area over a circular base plate, so the front two corners overhang the plate, and have to be trimmed in (which the manufacturer did for the config)

Since you can't reproduce on your end, what can I send you as far as crash-dumps and stacks that would be helpful (and how would I do it, not a developer here).

**Comment by Kolodner** [comment]
[Slic3r_config_DVT4_20150812.zip](https://github.com/alexrj/Slic3r/files/1330892/Slic3r_config_DVT4_20150812.zip)

**Comment by lordofhyphens** [comment]
Did you confirm with the linked version of the build? That's right off of the release.

**Comment by Kolodner** [comment]
Yep, still crashes on trying to load that config:

![slicerfail](https://user-images.githubusercontent.com/14181384/30839311-2862508c-a23f-11e7-9cb7-624bb295282f.PNG)

**Comment by lordofhyphens** [comment]
Can you delete the Bed shape line and see if it still crashes?

**Comment by lordofhyphens** [comment]
I can't get it to crash on my Linux system either.

If you open up a command line window and run slic3r-console.exe it should spit out an error message when it crashes.

**Comment by lordofhyphens** [comment]
Just also checked on my Windows 10 system with an nVidia 740M graphics card, no crash either :(

**Comment by lordofhyphens** [comment]
That screenshot screams "OpenGL issue".

**Comment by Kolodner** [comment]
hmmm. I'll try running the console & deleting the bed shape. Also, I double-checked my drivers and oh look, Microsoft had decided they wanted to install a different display adapter driver for my GTX680:
![fuckyoumicrosoft](https://user-images.githubusercontent.com/14181384/30859772-fdece44e-a292-11e7-9bd1-cd6a140eb3c8.PNG)
So, I'm trying to update to the latest Geforce driver first.

**Comment by Kolodner** [comment]
That appears to have been it. When my video card drivers were updated, this _*appears*_ to be resolved, in that it  didn't crash on config import.

Thanks for pointing me to OpenGL as likely culprit, which prompted a drivers update. Not sure why it was rolled back to May's version as I'm pretty sure I'd updated more recently than that. (also not sure why it was working previously then suddenly not, if the driver had been the same this whole time and I've definitely been slicing things in June/July).
