### ISSUE TITLE
GUI preset list width too small - can't see whole name

### ISSUE THREAD

**Issue by sonntam** [alexrj/Slic3r#4142]
### Version
1.2.9 Windows Release build

### Operating system type + version
Windows 10 x64

### Behavior
In the Slic3r print settings GUI the preset list is too narrow to display the whole name of the presets. A dynamic width based on the longest list entry would be better.

![slic3r_bugreport](https://user-images.githubusercontent.com/6692408/31054052-67bda76c-a6aa-11e7-91a6-b625ad899390.png)

**Comment by Samir55** [comment]
Duplicates #3151

**Comment by lordofhyphens** [comment]
@sonntam Try 1.3.0-dev. 

Closing because dupe.
