### ISSUE TITLE
dl.slic3r.org down?

### ISSUE THREAD

**Issue by darrelhunt** [alexrj/Slic3r#4171]
Have been trying to download Slic3r since last night.  Tried multiple connections and devices and site is not responding.  Wasn't sure who to notify.  Would like to download a nightly build of the 1.3.0 dev for Mac.

**Comment by lordofhyphens** [comment]
Noticed that myself. @alexrj runs the server.

**Comment by lordofhyphens** [comment]
Back up

**Comment by Rauchbier87** [comment]
it seems to be down again. I get the message that the website wouldn't connect.
