### ISSUE TITLE
No infill under slopes

### ISSUE THREAD

**Issue by jaroslavas** [alexrj/Slic3r#4175]
### Version
1.3.0-dev
(downloaded binary from automated fresh builds some time ago)

### Operating system type + version
MacOS X 10.12.6

### Behavior
* There is no infill under slopes. If top part of model is not horizontal, there is no infill under these slopes.
* Just slice included object
* There should be infill everywhere, not only under horizontal faces.
* No infill:
![slic3r-1](https://user-images.githubusercontent.com/1903354/32147440-fa71a350-bcef-11e7-97ee-feae74fc2a1b.png)
![slic3r-2](https://user-images.githubusercontent.com/1903354/32147442-0137647c-bcf0-11e7-97f0-b748e75dd1dc.png)
![about slic3r](https://user-images.githubusercontent.com/1903354/32147445-0e7359ca-bcf0-11e7-9e24-2588226d5485.png)

#### STL/Config (.ZIP) where problem occurs
[slic3r-report.zip](https://github.com/alexrj/Slic3r/files/1425426/slic3r-report.zip)

**Comment by lordofhyphens** [comment]
Uncheck "Only infill where needed."
