### ISSUE TITLE
8.2 small holes too big

### ISSUE THREAD

**Issue by boshy** [alexrj/Slic3r#418]
I have had to go back to using 7.2B because 8.2 is no longer accurate.
The small hole sizes are now to big EG this model http://www.thingiverse.com/thing:9094
when I slice it with 7.2B the hole sizes are perfect but when I use 8.2 the hex hole is way too big.
Would it be possible to make 8.2 accurate like 7.2B??
I have a well calibrated machine and prints to within .05 mm.
I love all the new features in 8.2 
I make well fitting parts and need the accuracy.
If you  could make me a version that had the small hole part  like 7.2B with all the new features of 8.2 and email it to me I would be forever grateful ?
I have a Mac running Lion.

**Comment by alexrj** [comment]
Automatic hole compensation was removed a long time ago and now we have an option for manual size compensation
