### ISSUE TITLE
Website is unreachable

### ISSUE THREAD

**Issue by DrLex0** [alexrj/Slic3r#4187]
It shows:

> Warning: require_once(DB.php): failed to open stream: No such file or directory in /srv/data/web/vhosts/slic3r.org/htdocs/index.php on line 7
> 
> Fatal error: require_once(): Failed opening required 'DB.php' (include_path='.:/usr/share/php:/srv/data/web/includes') in /srv/data/web/vhosts/slic3r.org/htdocs/index.php on line 7

**Comment by lordofhyphens** [comment]
Yep, I know. Already notified @alexrj (who owns the server).

https://dl.slic3r.org still works, as does https://dl.slic3r.org/dev

**Comment by mamoit** [comment]
This seems to be resolved.
