### ISSUE TITLE
FAIL ! Installing ./xs failed. -->  Falling back to Archive::Tar 2.26

### ISSUE THREAD

**Issue by larajustine** [alexrj/Slic3r#4194]
Hi, I'm using perl v5.20.3 built for MSWin32-x64-multi-thread and when I run `perl build.pl` appears an error, about _Falling back to Archive::Tar 2.26_

### build.log
cpanm (App::cpanminus) 1.7043 on perl 5.020003 built for MSWin32-x64-multi-thread
Work directory is C:\Users\laraj/.cpanm/work/1511308607.13144
You have make C:\Strawberry\c\bin\dmake.exe
You have LWP 6.15
Falling back to Archive::Tar 2.26
--> Working on ./xs
Entering C:/Slic3r/xs
Checking if you have Module::Build 0.38 ... Yes (0.4216)
Checking if you have ExtUtils::Install 1.46 ... Yes (2.06)
Configuring C:/Slic3r/xs
Running Build.PL
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::XSpp 0.18 ... Yes (0.18)
Checking if you have Module::Build 0.3601 ... Yes (0.4216)
Checking if you have Test::More 0 ... Yes (1.302113)
Checking if you have ExtUtils::Typemaps::Basic 1.05 ... Yes (1.05)
Checking if you have ExtUtils::Typemaps 1.00 ... Yes (3.35)
Checking if you have ExtUtils::Typemaps::Default 1.05 ... Yes (1.05)
Checking if you have ExtUtils::ParseXS 3.35 ... Yes (3.35)
Building and testing Slic3r-XS-0.01
-> FAIL Installing ./xs failed. See C:\Users\laraj\.cpanm\work\1511308607.13144\build.log for details. Retry with --force to force install it.

---------------------------------------------------------------------

I'm using boost_1_59_0 'cause boosts more recently didn't work out.
Slic3r is current clone from git, master branch
OS is Microsoft Windows 10

#### More over, I think I didn't set the variable so that Build.pl can find the boost libs
I used `set BOOST_DIR=C:\dev\boost_1_59_0\stage\lib` but then I got _Invalid BOOST_DIR: no such directory_

**Comment by lordofhyphens** [comment]
Use Slic3r-Perl, like the wiki says to.
