### ISSUE TITLE
Slic3r pe constantly freezing on Intel HD graphics

### ISSUE THREAD

**Issue by Patrik-svobodik** [alexrj/Slic3r#4222]
### Version
1.37.2-prusa3d-win64_

### Operating system type + version
w10 x64

### Behavior
*Constantly freezing when trying to view an stl (sometimes even without stl)
* occurs after start

**Comment by bubnikv** [comment]
This is an evergreen, caused by wrong OpenGL driver installed by the Windows updater. The Redmond guys should talk to the guys at Santa Clara more often.

https://github.com/prusa3d/Slic3r/issues/268
https://github.com/prusa3d/Slic3r/issues/233

**Comment by lordofhyphens** [comment]
Slic3r PE, not Slic3r. I'll reopen if you reproduce from http://dl.slic3r.org/dev/win and it's caused by anything other than what @bubnikv already pointed out (using wrong OpenGL driver).
