### ISSUE TITLE
Retraction settings missing

### ISSUE THREAD

**Issue by vovcacik** [alexrj/Slic3r#4226]
### Version
1.3.0-dev
Slic3r-master.2017.08.14.1313.a54ca92.64bit

### Operating system type + version
Windows 10 Pro 64 bit

### Behavior
According to the [manual][] there should be *Retraction* section on *Printer* tab. I went through the options and there is nothing about retraction.

[manual]: http://manual.slic3r.org/expert-mode/fighting-ooze

**Comment by lordofhyphens** [comment]
It is in the Extruder section.

**Comment by vovcacik** [comment]
@lordofhyphens 
![image](https://user-images.githubusercontent.com/691873/34073722-57a4baa0-e2a0-11e7-933c-11b953654a5f.png)

**Comment by lordofhyphens** [comment]
That's "Print", not "Printer".

**Comment by vovcacik** [comment]
Thanks a lot! This was painful though. You may want to add note about the *Extruder* section to the [manual][]; e.g. *Printer settings* tab > *Extruder 1* page > *Retraction* settings.

[manual]: http://manual.slic3r.org/expert-mode/fighting-ooze

**Comment by lordofhyphens** [comment]
Manual is in github too (https://github.com/alexrj/Slic3r-Manual) and is in
Markdown format. Make a pull request and it can get fixed faster.
