### ISSUE TITLE
Part of symmetric model is missing

### ISSUE THREAD

**Issue by vovcacik** [alexrj/Slic3r#4236]
### Version

1.3.0-dev
Slic3r-master.2017.08.14.1313.a54ca92.64bit

### Operating system type + version
Windows 10 Pro 64 bit

### Behavior

- part of symmetric model is incorrectly rendered
- missing part is in red
![image](https://user-images.githubusercontent.com/691873/34083503-104ac2d0-e372-11e7-8ed3-e8cf16f5ee9e.png)
- it is also completely missing in the solution
![image](https://user-images.githubusercontent.com/691873/34083530-7070cd08-e372-11e7-986f-11eca3b6a1f1.png)
- it works correctly in OpenSCAD and Windows STL viewer
- I can reproduce this problem for higher towers too

#### STL/Config (.ZIP) where problem occurs

[rail.zip](https://github.com/alexrj/Slic3r/files/1566024/rail.zip)

**Comment by lordofhyphens** [comment]
Run the model through netfabb service and confirm that Slic3r isn't trying
to repair it.

**Comment by lordofhyphens** [comment]
![image](https://user-images.githubusercontent.com/31754/34091418-1e3b0628-e383-11e7-94d5-155af10aa18e.png)
Netfabb indicates that the surface is not closed, and a pass through the online service fixes it.

3d model preview of the bad file:
![image](https://user-images.githubusercontent.com/31754/34091501-9aa06618-e383-11e7-839e-905720b58db4.png)

Fixed model:
![image](https://user-images.githubusercontent.com/31754/34091510-ad3e9448-e383-11e7-8091-61ef36552801.png)

![image](https://user-images.githubusercontent.com/31754/34091519-bb57aede-e383-11e7-989f-fbda49b8f02d.png)
