### ISSUE TITLE
Feature Request: GUI option to disable geometry compensation

### ISSUE THREAD

**Issue by Area5142** [alexrj/Slic3r#426]
Just designed a stepper pulley with a shaft hole and a mounting slot.
Simple test CAD picture: https://dl.dropbox.com/u/6681664/github/Slic3r_Hole_Correction_Failure.jpg

Slicing the item gives the shaft two hole diameters one at the lower layers and one at the top layers (shaft designed with constant diameter).
Repetier-Host view: https://dl.dropbox.com/u/6681664/github/Slic3r_Hole_Correction_Failure_2.jpg
Ini file: https://dl.dropbox.com/u/6681664/github/Slic3r_Hole_Correction_Failure.ini
(Can be difficult to see but the diameter changes from one layer to another)

I think this has to do with hole or other geometry compensation and not an error in the program.

I would like an option to prevent the automatic geometry compensation (preferable in the GUI). This way I know I have to compensate for precise geometry taking into account material shrinkage (PLA/ABS) and the surrounding geometry.
I often have the problem with older models - they printed fine then, but now there is a new (and unknown) compensation algorithm and the model must be changed to print correctly... extra work...

Mold makers has a similar problem. They begin with a perfect model and has to make mold model taking shrinkage and post machining into account. I would like the same option.
As a bonus I could have the compensation values documented in the "mold" CAD drawing and make it easier changing to  printing material with other properties.

Just to make a great program better :)

**Comment by alexrj** [comment]
Hole compensation was removed a long time ago, and we now have an option for size compensation
