### ISSUE TITLE
Add-ing any STL b0rks mouse scroll

### ISSUE THREAD

**Issue by mozgy** [alexrj/Slic3r#4274]
### Version
Slic3r-master.2018.01.21.1590.dc9d7ed.32bit
(several previous versions too)

### Operating system type + version
Win7 Pro

### Behavior
- open Slic3r GUI
- mouse scroll works
- drag any STL into '3D' window
- mouse scroll is b0rken

Clicking 'Preview' then back to '3D' fixes it, although next model 'Add' and mouse scroll went south again ..

**Comment by dartrax** [comment]
We're already discussing this in #4217. May be you can confirm the observations there regarding the use of Chrome ;-)
