### ISSUE TITLE
Question : automated build set up

### ISSUE THREAD

**Issue by rockandsalt** [alexrj/Slic3r#4275]
Hi,
I would like to know how do you get fresh builds for all platform. I made some modification to the slic3r code and I would like to send a dmg file to a friend so that he can try it. But I don't own a mac. And I would rather not go through the trouble of setting up a virtual machine with macos. 

thanks

**Comment by lordofhyphens** [comment]
We have an OSX build server (donated by MacStadium), and a windows build server (Appveyor). Linux builds are prepared on TravisCI. Currently you do need an OSX system to do the build (we aren't using a cross-compiler yet). 

Submit a PR if you think it'd be generally useful.
