### ISSUE TITLE
[feature/improvement] Add documentation on multimaterial printing through tool changes to the Slic3r manual

### ISSUE THREAD

**Issue by mrjohnc** [alexrj/Slic3r#4280]
Please add documentation on multimaterial printing through tool changes to the Slic3r manual, as detailed here http://reprap.org/wiki/Mulitcolour_printing_with_one_hotend

Thanks

**Comment by lordofhyphens** [comment]
The Manual accepts pull requests too.

Http://github.com/alexrj/Slic3r-Manual

**Comment by mrjohnc** [comment]
Ah, cool, didn't realise, will have a look, see if I can work out how to do it

**Comment by lordofhyphens** [comment]
It is all in Markdown, which is really easy to write and has tons of online references.

Closing because this is the wrong repo ;)
