### ISSUE TITLE
Slic3r Solarized - Background Color of Layers-Tab missing?

### ISSUE THREAD

**Issue by foreachthing** [alexrj/Slic3r#4296]
### Version
1.3 beta

### Issue
I'm working on "solarizing" (http://ethanschoonover.com/solarized) Slic3r and can't find where I need to adjust the background color of the Layers tab. Any hint is appreciated.
Everything else was pretty "easy" - if you know/knew Perl! Still work in progress: https://github.com/foreachthing/Slic3r/tree/Solarized

### Screenshots
Preview Tab:
![image](https://user-images.githubusercontent.com/10420187/36122954-7b55a54e-104b-11e8-8e99-9bb16e305c5b.png)

Layers Tab:
The only thing I'm missing, is the background color. Everything else I got (not visible here).
![image](https://user-images.githubusercontent.com/10420187/36123023-b252162c-104b-11e8-976b-b960d7224bf6.png)

**Comment by lordofhyphens** [comment]
Take a look at 3DScene.pm. If you want to port the C++ 3DScene from the Prusa fork then I'd happily accept it.

**Comment by lordofhyphens** [comment]
I'd also accept a PR for solarizing if you can make it an optional change in the preferences.

**Comment by foreachthing** [comment]
Yes, in 3DScene, I was able to change the background for **3D** and **Preview**. Then in 2d.pm I could change the **2D** background. But the **Layers** ... !?
Ok... I need to take a look at the Prusa fork first. And yes, it's optional already ;-)

**Comment by foreachthing** [comment]
I don't know .... I can't find it. I got the slider backcolor on **Layers** changed, though. 
It's like, it's not there for the grasp.
Does anybody see where I can change the background color of **Layers**?

**Comment by lordofhyphens** [comment]
The Layers tab is drawn in 3D mode from my investigations. 

You are interested in the `glClearColor` call in `sub Render` in 2DToolpaths.pm.

For `glClearColor(0.3, 0.4, 0.1, 0);`
![image](https://user-images.githubusercontent.com/31754/36635776-9a64602c-1980-11e8-95d3-78f7acfbfe6b.png)

**Comment by lordofhyphens** [comment]
http://prideout.net/archive/colors.php for your reference.

**Comment by lordofhyphens** [comment]
You will also need to apply the same color to the individual line drawings.
