### ISSUE TITLE
Fix external perimeter width to nozzle diameter to avoid auto width messing things up

### ISSUE THREAD

**Issue by Tinchus2009** [alexrj/Slic3r#4298]
### Version
1.2.9-1276-g05461b8

### Operating system type + version
win10
### Behavior
 There has been a change: 

commit 86c36006845392d9e842fbe76482975e01089818
Author: Joseph Lenox <lenox.joseph@gmail.com>
Date:   Fri Jan 5 20:48:42 2018 -0600

    Fix external perimeter width to nozzle diameter to avoid auto width messing things up

Well, problem with this fix is that, there are many reason why you wuld want the external extrussion bigger thanjust noozle width. Somerimes you want to have just a single line wall... and to make it strnger if you have a 0.4 noozle, you set up the extrusion to be 0.68 for example. With this fix, we lost that ability

**Comment by lordofhyphens** [comment]
That is literally for just auto-width; manual should do whatever you tell
it (even if what you tell it is stupid).
