### ISSUE TITLE
Latest automated builds are incomplete

### ISSUE THREAD

**Issue by foreachthing** [alexrj/Slic3r#4306]
### Version
https://dl.slic3r.org/dev/win/
i.e.: Slic3r-master.2018.02.18.1602.5f28ee4.32bit.zip.filepart

### Operating system type
Windows

### Behavior
* Latest automated builds are incomplete
* if downloaded, extraction is followed by a disc error.

![image](https://user-images.githubusercontent.com/10420187/36377244-bd3793c0-1576-11e8-8e42-a1904a1ea5af.png)

**Comment by lordofhyphens** [comment]
Probably out of room. I will go clean things up in the branch dir.

**Comment by lordofhyphens** [comment]
Did it sort itself out?

**Comment by foreachthing** [comment]
I guess! There's a build from 2018-02-20...

**Comment by foreachthing** [comment]
Nope! The issue still persists:
![image](https://user-images.githubusercontent.com/10420187/36587871-a3ea918e-1886-11e8-94bc-9d74bccf0c88.png)

**Comment by lordofhyphens** [comment]
Should be fine now.

**Comment by lordofhyphens** [comment]
I've also kicked off a set of builds to make sure the last commit is available for download.

**Comment by lordofhyphens** [comment]
Yep, builds are good to go now.
