### ISSUE TITLE
Placeholder question / feature request

### ISSUE THREAD

**Issue by Richie76** [alexrj/Slic3r#4312]
### Version
doesn´t matter

### Operating system type + version
doesn´t matter

### Behavior
Can I do simple math inside the [ ] with the placeholders ?
i.e. something like this here:
M140 S[first_layer_bed_temperature - 5] ; set bed temp -5
M190 S[first_layer_bed_temperature - 5] ; wait for bed temp -5

M104 S[first_layer_temperature] ; set extruder temp
M140 S[first_layer_bed_temperature] ; set bed temp
M109 S[first_layer_temperature] ; wait for extruder temp
M140 S[first_layer_bed_temperature] ; wait for bed temp

I don´t want the nozzle to sit there for like 10-15 Minutes until the big heatbed on my custom machine has heated up. With this simple calculation I could wait for a certain bed temp - and then heat the nozzle and the bed to their final temps.

_Is this a new feature request?_
maybe ?

Best rgds, Richard

**Comment by lordofhyphens** [comment]
https://github.com/alexrj/Slic3r-Manual/blob/master/src/advanced/conditional-gcode.md
