### ISSUE TITLE
Feature request: brim layer height

### ISSUE THREAD

**Issue by bigrip** [alexrj/Slic3r#4320]
hi
I often have the problem when I print small things on a long support the pla curl up and then the nozzle crash into the print and the support break from the brim and become loose,if we can make the brim stronger it would help.

**Comment by lordofhyphens** [comment]
Duplicates #641

**Comment by lordofhyphens** [comment]
Furthermore brim is printed at the first layer height (nominally thick already). Printing it thicker than the perimeter will cause the nozzle to drag through the brim, making your problem worse.

**Comment by ecob81** [comment]
I use this feature all the time in S3D and recently started using Slic3r but couldn't believe this is missing. Would really love to see it added.
