### ISSUE TITLE
Missing Perimeter and/or Layers

### ISSUE THREAD

**Issue by DanyboyInSwitzerland** [alexrj/Slic3r#4348]
### Version
Version 1.39.1-prusa3d-win64

### Operating system type + version
Win10 Pro, Version 1709, build 16299.309

### Behavior
*When loading a statue (downloaded from thingiverse), in the 3d-view it seems ok. After slicing, there is the perimeter missing in two spots, and on one spot, there's not even infill printed. On that non-printed spot, the gcode seems to act as if he was printing two individual objects, sitting on top of each other.
The phenomenon only appears on the main-body, the "extremities" and supports appear not affected.
From the preview, it really appears that layers are missing, as the curvutare extends over the gap.
Repairing the stl-file did not change the behaviour.
When checking the file in Fusion360, I cannot see any problem with the stl itself as the gaps do not appear there.
I tried with using different types and amounts of infill, as well as layer-heights and number of perimeters, but no help... :(
If this is an error from my side - PLEASE let me know, I am eager to learn!
* Just load the stl and slice.
* Obviously, those gaps should not exist.
* In the gap where nothing gets printed, the same layout gets printed as if it would lay support on the print-bed.

screenshot from the 3d-view:
![harley_quinn_1_model](https://user-images.githubusercontent.com/37697139/37828242-be574510-2e9a-11e8-90fb-dcf33eb2933c.jpg)
screenshot from the preview-view:
![harley_quinn_1_preview](https://user-images.githubusercontent.com/37697139/37828243-be8d25ea-2e9a-11e8-9b22-34fb53d398f2.jpg)

_Is this a new feature request?_
I did not find anything similar looking through six pages of reports/requests.

#### STL/Config (.ZIP) where problem occurs
config used for slicing:
[HarleyQuinn_Config.zip](https://github.com/alexrj/Slic3r/files/1841454/HarleyQuinn_Config.zip)
stl used to slice:
[HarleyQuinn_stl.zip](https://github.com/alexrj/Slic3r/files/1841462/HarleyQuinn_stl.zip)

**Comment by FidelCapo** [comment]
@DanyboyInSwitzerland Thanks for the report. If you are using Prusa Edition Slic3r, please write reports to our issues: https://github.com/prusa3d/Slic3r/issues
I tested your model and there are a lot of errors. In the current master branch (version 1.40.0), the model slice correctly. As a temporary workaround I attach a repaired model.
Models can be repaired, for example, by Netfabb or Meshmixer services.

[aa-repaired.stl.zip](https://github.com/alexrj/Slic3r/files/1841946/aa-repaired.stl.zip)

**Comment by DanyboyInSwitzerland** [comment]
Hello Hurka,

 

Thank you very much for the quick reply!

 

Ok, so the problem was a combination of an older version of slicer due to customization by prusa, as well as a model with lots of errors that needed more that autorepair could handle.

So next time for a similar situation, I will use the more sophisticated services if autorepair cannot provide a satisfying result.

 

THANK YOU VERY MUCH FOR THE HELP!

 

Sincerely,

Daniel

 

Gesendet: Freitag, 23. März 2018 um 15:47 Uhr
Von: HurkaF <notifications@github.com>
An: alexrj/Slic3r <Slic3r@noreply.github.com>
Cc: DanyboyInSwitzerland <dnovet@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [alexrj/Slic3r] Missing Perimeter and/or Layers (#4348)


@DanyboyInSwitzerland Thanks for the report. If you are using Prusa Edition Slic3r, please write reports to our issues: https://github.com/prusa3d/Slic3r/issues
I tested your model and there are a lot of errors. In the current master branch (version 1.40.0), the model slice correctly. As a temporary workaround I attach a repaired model.
Models can be repaired, for example, by Netfabb or Meshmixer services.

aa-repaired.stl.zip

**Comment by FidelCapo** [comment]
@DanyboyInSwitzerland The problem isn't in Prusa Edition, but in this version (1.39.1) we have modified the auto repair and unfortunately did not work the way we expected. I'm currently testing a lot of auto-repairing on the variously damaged models, and it looks very good in version 1.40.0.

Lots of happy prints
Filip

**Comment by DanyboyInSwitzerland** [comment]
Cool! Looking forward to the next update then...! :)
...and please keep up the good work!I am very impressed with slicer, this was the first time I had a real problem - and my printer is almost working non-stop since I received it two months ago... ;)
Cheers,Daniel
-------- Ursprüngliche Nachricht --------Von: HurkaF <notifications@github.com> Datum: 23.03.18  18:50  (GMT+01:00) An: alexrj/Slic3r <Slic3r@noreply.github.com> Cc: DanyboyInSwitzerland <dnovet@gmx.net>, Mention <mention@noreply.github.com> Betreff: Re: [alexrj/Slic3r] Missing Perimeter and/or Layers (#4348) 
@DanyboyInSwitzerland The problem isn't in Prusa Edition, but in this version (1.39.1) we have modified the auto repair and unfortunately did not work the way we expected. I'm currently testing a lot of auto-repairing on the variously damaged models, and it looks very good in version 1.40.0.
Lots of happy prints

Filip

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alexrj/Slic3r","title":"alexrj/Slic3r","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alexrj/Slic3r"}},"updates":{"snippets":[{"icon":"PERSON","message":"@FidelCapo in #4348: @DanyboyInSwitzerland The problem isn't in Prusa Edition, but in this version (1.39.1) we have modified the auto repair and unfortunately did not work the way we expected. I'm currently testing a lot of auto-repairing on the variously damaged models, and it looks very good in version 1.40.0.\r\n\r\nLots of happy prints\r\nFilip"}],"action":{"name":"View Issue","url":"https://github.com/alexrj/Slic3r/issues/4348#issuecomment-375748649"}}}
