### ISSUE TITLE
Incorrect colors for infill and outline in layers tab

### ISSUE THREAD

**Issue by xoan** [alexrj/Slic3r#4352]
### Version
Current master: 1.2.9-1291-gce6b7c8f

### Operating system type + version
Arch Linux

### Behavior
I guess since merge #4322 for color scheme, some colors changed in «Default» scheme and seems to be wrong.

Infill is now black, and outline is red, like perimeters.

![captura de pantalla_2018-03-31_12-44-48](https://user-images.githubusercontent.com/288246/38162465-1a070f2e-34e2-11e8-81da-d87f0fc2a05f.png)
*After last commit*

![captura de pantalla_2018-03-31_20-59-56](https://user-images.githubusercontent.com/288246/38166586-7dc8abc8-3526-11e8-90f3-74cab7eefef9.png)
*Before last commit*

It seems that I have 3 perimeters configured, but actually, I have 2. The outer line is the outline of the layer part.

**Comment by foreachthing** [comment]
I`ll have a look. I don`t think I changed any of the default colors... but something happened, I guess?!

**Comment by xoan** [comment]
I've updated the prior message to attach the screenshot of the layers tab before the last commit.

**Comment by xoan** [comment]
Also in 2D tab, when there are more than one copy of the object, the selected one have no different color.

![captura de pantalla_2018-03-31_21-58-11](https://user-images.githubusercontent.com/288246/38167026-a277062e-352e-11e8-8c0a-4795fcc35650.png)
*After last commit*

![captura de pantalla_2018-03-31_21-57-00](https://user-images.githubusercontent.com/288246/38167029-acb13e52-352e-11e8-8dcc-b08514f0f6a9.png)
*Before last commit*

**Comment by Samir55** [comment]
@foreachthing 
For the 2D tab. The instance_brush (the selected instance of the selected object) color shouldn't be the same color of the selected_brush. 
```Perl
 -    $self->{instance_brush}     = Wx::Brush->new(Wx::Colour->new(255,128,128), wxSOLID);
 -    $self->{selected_brush}     = Wx::Brush->new(Wx::Colour->new(255,166,128), wxSOLID);
 +    $self->{instance_brush}     = Wx::Brush->new(Wx::Colour->new(@BED_SELECTED), wxSOLID);
 +    $self->{selected_brush}     = Wx::Brush->new(Wx::Colour->new(@BED_SELECTED), wxSOLID);
```

**Comment by lordofhyphens** [comment]
Fix has been merged, closing.
