### ISSUE TITLE
perimeter every other layer?

### ISSUE THREAD

**Issue by JelleB** [alexrj/Slic3r#460]
not sure if I should put feature requests here as well. It would be nice if slic3r could add a perimeter every other (or every 3, 4 etc) layer. With infill alone the form of the print is not very defined. A perimeter every other layer would still keep the print very porous, but would give more stability and shape definition. 

Any hinst how/where to hack this myself would also be welcome.

**Comment by lordofhyphens** [comment]
Going to close this. If you want to remove layers you could do it with a script to read the gcode (turn on verbose output) that removes perimeter moves. The layers are delineated by Z moves for the most part (you'd want to use firmware retract so that z lift doesn't break your script).
