### ISSUE TITLE
Slic3r erroneously uses M104 to set temperature and wait; should be  M109

### ISSUE THREAD

**Issue by Pointedstick** [alexrj/Slic3r#49]
Slic3r inserts an M104 command as the first line of every gcode file it  generates:

M104 S185 ; wait for temperature to be reached

[ beginning of my start.gcode]

G1 E30 F300     ;Prime extruder 30mm
G28 ; home all axes

[ end of my start.gcode ]

G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
G1 Z-0.825 F18000.000 ; move to next layer
G1 X58.938 Y56.873 ; move to first skirt point
G1 F1080.000 E1.00000 ; compensate retraction
G1 X59.118 Y56.723 F3000.000 E1.00279 ; skirt
G1 X60.108 Y55.923 E1.01795 ; skirt
G1 X60.238 Y55.813 E1.01998 ; skirt

However, M104 does _not_ wait for the temperature to be reached. M109 does that. M104 sets the temperature and them immediately executes the next command. Thus, the hardcoded M104 command should be an M109.

**Comment by mickkn** [comment]
Is there a way to cheange this for the default G-Code export?

**Comment by lordofhyphens** [comment]
@mickkn Yeah, add "M109 [first_layer_temperature]" to your start gcode for your printer settings. Something you should be doing anyway.
