### ISSUE TITLE
Feature Req: GUI Hole compensation ratio

### ISSUE THREAD

**Issue by Aggresive** [alexrj/Slic3r#494]
What with the amount of issues people have with hole sizes - (I know it's never going to be perfect.) and that i've just tried printing a polygon modeled at 6.8mm (M4 nut) and it's printed at 6.2mm, and an 8.4mm circle that it has printed at 7.6mm - would it be possible to add a GUI option to adjust the amount of compensation?

BTW - the model was sliced with the latest commit 0.8.5-dev with 0.6mm wall thickness

**Comment by lordofhyphens** [comment]
XY Compensation is now a thing. This can probably be closed.

**Comment by bubnikv** [comment]
The XY compensation compensates not only holes, but the outer perimeters as well.
