### ISSUE TITLE
Shortest, but not best path

### ISSUE THREAD

**Issue by blddk** [alexrj/Slic3r#512]
I was trying to print a tube squeezer, when I noticed it do some moves that was not that great, even when they might be the shortest.

http://www.youtube.com/watch?v=1YRLSeFctzc

it keeps retacting, moving to the opposite side of the slot, extrudes a bit, retracts, moves to the opposite side, and so on.

**Comment by lordofhyphens** [comment]
@blddk I'm going to close this, you never responded to any requests for more info. If you notice this and it still breaks in a current version of Slic3r, please reopen and add the information requested in the contributing guidelines. Thanks.
