### ISSUE TITLE
Slic3r will not open after a fresh install on M1 MacBook Pro 

### ISSUE THREAD

**Issue by DrGravlin** [alexrj/Slic3r#5173]
**Describe the bug**
After a fresh install on my M1 MacBook Pro, it kept on failing to open. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 14.0

**Comment by AleyRobotics** [comment]
looks like it the same bug https://github.com/slic3r/Slic3r/issues/5172

**Comment by Chromeking** [comment]
any update on this?

**Comment by mayaway** [comment]
any update on this?
