### ISSUE TITLE
leading zero for input fields

### ISSUE THREAD

**Issue by jgeerds-zz** [alexrj/Slic3r#518]
some input fields will have some error cheack when saving the profile when I enter a value without a leading zero. i.e. the first layer hight. the layer height accepts inputs such as ".2" without throwing an error. some values are written then without the leading zero to the INI file, while some are converted to a leading zero.

It would be great to make the behavior of all input fields the same, allowing input without a leading zero, but instantly converting it into the proper format.

**Comment by lordofhyphens** [comment]
Well, it does it now.
