### ISSUE TITLE
slic3r crash with complicated stl's

### ISSUE THREAD

**Issue by pet110** [alexrj/Slic3r#532]
Hi,

I'm running the latest version of Slic3r using perl 5.14.2. on Windows 7 64bit. If i try to slice the things below slic3r crashes.

http://www.thingiverse.com/thing:26567

http://www.thingiverse.com/thing:22734

My config:

acceleration = 0
bed_size = 200,200
bed_temperature = 65
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 70
brim_width = 4
complete_objects = 0
cooling = 0
disable_fan_first_layers = 1
duplicate = 1
duplicate_distance = 6
duplicate_grid = 1,1
end_gcode = G1 X12.0 F4000       ; home (almost) x - stops extruder crashing into frame if at very top of Z height\nG1 Y170 F4000        ; move the print to the front.\nM104 S0                   ; make sure the extuder is turned off.\nM140 S0                   ; make sure the bed is turned off.\nM84                          ; shut down motors.
external_perimeter_speed = 60
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
fan_always_on = 0
fan_below_layer_time = 60
filament_diameter = 2.9
fill_angle = 45
fill_density = 0.5
fill_pattern = rectilinear
first_layer_bed_temperature = 82
first_layer_extrusion_width = 0
first_layer_height = 100%
first_layer_speed = 30%
first_layer_temperature = 177
g0 = 0
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
infill_acceleration = 50
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_speed = 110
layer_gcode = 
layer_height = 0.2
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 10
notes = 
nozzle_diameter = 0.37
output_filename_format = [input_filename_base].gcode
perimeter_acceleration = 25
perimeter_speed = 50
perimeters = 2
perimeters_extruder = 1
perimeters_extrusion_width = 0
post_process = 
print_center = 100,100
randomize_start = 1
retract_before_travel = 2
retract_length = 0.8
retract_lift = 0.6
retract_restart_extra = 0
retract_speed = 30
rotate = 0
scale = 1
skirt_distance = 8
skirt_height = 1
skirts = 1
slowdown_below_layer_time = 15
small_perimeter_speed = 30
solid_fill_pattern = rectilinear
solid_infill_speed = 90
solid_layers = 2
start_gcode = G28                 ; home all axes\nG92 E0  ;reset extruder\nG1 E3 F1200 ;Prime extruder 3mm\nG1 E2 F1200 ;retract extruder 1mm\nG92 E0  ;reset extruder
support_material = 0
support_material_angle = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_pattern = rectilinear
support_material_spacing = 2.5
support_material_threshold = 45
temperature = 177
threads = 2
top_solid_infill_speed = 50
travel_speed = 200
use_relative_e_distances = 0
z_offset = 0.2

**Comment by lordofhyphens** [comment]
@pet110 both of those models are no longer available on Thingiverse, if this is still a problem for you, please open a new issue with a zip of the file that broke it and your slicing config.
