### ISSUE TITLE
Feature Request: Implement regions/partitions

### ISSUE THREAD

**Issue by klaszlo** [alexrj/Slic3r#577]
Hi,

The basic idea is having custom gcode injected to file based on conditions. 
It is more like gcode scripting, netfabb calls this "regions", as you can define 
part of the model using conditions (like perimeters of bottom 10 layers, etc, etc).

All things could be a condition to enter into such a region, like:
if layer < 10 then "do this" 
if layer == 8 then "do this"
if layer % 2 == 0 and layertime < 10*sec and perimeter == 0 then "do this"

Im not asking a complete scripting language, Im more asking for some variables I can use 
when I define my conditions.

A current real world example:
http://www.flickr.com/photos/48806889@N05/7688919220/in/photostream

As you can see abs delaminates because the too excess fan speed. 
However to have straight walls at the bottom 5mm of the object, I need high fan speed to 
get rid of the excess heat conducted by the heated bed. Above that the fan speed should 
be reduced to minimise the warping on the object. Also the plastic is cold enough to have 
less and less fan speed.

So the fan speed would be like this:
1. Disable fan altogether for bottom layer for maximum adhesion. (M106 S0)
2. Adjust the fan to the max speed I want to print (M106 S150)
3. if layers is above 50, then reduce the fan speed (M106 S100)
4. if layers is above 100, then reduce more.

Also I could define some fancy things (like top of a pyramid), adjust the fan speed 
if layer time is below 40sec:
while layertime < 40: M106 S200
(so a temporary switch).

Although the above usecase is for fan, this regions can be defined for almost anything, and 
enables experimenting much more easier.

Like I could define 3 different printing quality (fast, normal, high quality), I could apply each 
printing quality different things(high quality: 0.2 mm layer height, infill 0.4mm layer height, outer primeter 0.1mm layer height, printing speed 20mm/s(outer perimeter), 40mm/s (other perimeters), 70mm/s infill. medium: ...)

And apply those printing speed based on conditions.

**Comment by lordofhyphens** [comment]
This has been implemented with Mesh Modifiers, if I am correct. Closing :) Reopen if there is something else about this request that hasn't been implemented yet that you want to see.
