### ISSUE TITLE
Add CFBundleIdentifier in Mac builds

### ISSUE THREAD

**Issue by alexrj** [alexrj/Slic3r#612]
15:46 kthx: Sound: 15 hours 9 min ago <brix> tell Sound It would be nice if you could include 'CFBundleIdentifier' => 'org.slic3r.Slic3r' or similar in Info.plist in future builds
15:46 kthx: Sound: 15 hours 8 min ago <brix> tell Sound that will make it possible to launch/activate Slic3r from apps, that expect a bundleID

**Comment by lordofhyphens** [comment]
@alexrj did this ever get done?

**Comment by bubnikv** [comment]
I believe this field is currently empty in Alex's builds. It is also empty in Prusa3d builds.
What is exactly the purpose of this field and what value shall be picked?

**Comment by alexrj** [comment]
Done.
