### ISSUE TITLE
Slic3R crashes on OS X 10.5

### ISSUE THREAD

**Issue by tenaciousRas** [alexrj/Slic3r#634]
When trying to run Slic3R on OS X 10.5.x from the pre-compiled 0.9.1 DMG it crashes with the following error:

dyld: unknown required load command 0x80000022

This recommendation from Intel might help:
http://software.intel.com/en-us/articles/running-an-intel-compiled-binary-on-older-mac-os-x-system-gives-dyld-unknown-required-load-command-0x80000022/#comment-65685

It's likely this issue also affects 10.4.  Using the PERL install might be a workaround, but haven't confirmed.

**Comment by alexrj** [comment]
I'm closing this. I don't know if current binaries work on 10.5, but even if they don't I have no plans to support that OS. 10.6 is the minimum required OS X version at the moment.
