### ISSUE TITLE
Bridge Layers and multiple perimeters cause problems with arcs

### ISSUE THREAD

**Issue by ahmetcemturan** [alexrj/Slic3r#638]
When printing a bridge layer that has a hole in it then having multiple perimeters is causing the printer to extrude in mid air.
Thats normal...  
Unfortunately this makes the task to use custom made supports very difficult..  
See: https://www.youtube.com/watch?v=VMH43dyyAy0  about 9:00
I was trying to test Nopheads support theory... 

SF makes only a single perimeter on Bridge layers and makes 100% fill then..  It is obviously overkill..
So best of both worlds:  Straight lines:  multiple perimeters,  Arcs: single perimeters...

**Comment by lordofhyphens** [comment]
Support generation has gotten a lot better over the last 4 years or so. Could you check to see if it is still a problem?
