### ISSUE TITLE
Feature request;  GUI presentation of verbose report on processed plate.

### ISSUE THREAD

**Issue by danielpublic** [alexrj/Slic3r#647]
As feature request [644#](https://github.com/alexrj/Slic3r/issues/644#) was well received; a related GUI feature request.

It would be really nice if the calculated cost, length and weight of the filament required and maybe estimated print-time for the 'plate' one has processed, would maybe(?) appear beneath the object placement window.

Thanks again for sharing your awesomeness with the rest of mankind!

**Comment by lordofhyphens** [comment]
@danielpublic https://bintray.com/lordofhyphens/Slic3r/Slic3r_Branches/1.3.0-slice_statistics-339#files How's that work for you?
