### ISSUE TITLE
Extra length on restart does not work correctly for negative values.

### ISSUE THREAD

**Issue by capitaenz** [alexrj/Slic3r#654]
If negative values ​​are entered, for example -0.20, then the objects are not correctly sliced.

**Comment by geryxyz** [comment]
Hi all, I am still able to reproduce the error with Repetier Host 2.1.6 and Slic3r 1.3.0. Config bundle and screenshot attached. 
![image](https://user-images.githubusercontent.com/2602591/114214620-cf61bb00-9964-11eb-825a-7a8f8c359c08.png)
[Slic3r_config_bundle.zip](https://github.com/slic3r/Slic3r/files/6287352/Slic3r_config_bundle.zip)
