### ISSUE TITLE
Feature Request: option for having less contact between object and brim

### ISSUE THREAD

**Issue by zdar** [alexrj/Slic3r#731]
It would be nice to have "horizontal" support for small parts on base layer.

Small things trend to not stick enough to hot plate and the extruder movement tears them away (cohesion in filament is bigger then they adhesion). 

Therefore anchoring them by horizontal  bridges (="support") to bigger parts would solve a lot of troubles.

**Comment by alexrj** [comment]
I'm closing this, it was done in #2230
