### ISSUE TITLE
No support generated on walls which are one extrusion width thick

### ISSUE THREAD

**Issue by mmihalko** [alexrj/Slic3r#771]
I`m trying to print propellers, but facing problem as described in title.
![no_support_example](http://dl.dropbox.com/u/60714578/problem_support.png)
Sorry for bad angle, I havent found better one. Please see enclosed gcode for better view.

config, stl and gcode:
http://dl.dropbox.com/u/60714578/support_report.zip

Maybe custom support width offset will help? Is it hard to implement? In situation above, wider support will also should improve sticking to bed.

**Comment by lordofhyphens** [comment]
Fixed, closing.
