### ISSUE TITLE
Lift Z relative to layer height

### ISSUE THREAD

**Issue by AxTheB** [alexrj/Slic3r#774]
It will be great if we can set Lift Z to xx% and have the lift based on actual layer height.
Lifts then will be automatically optimal at all times - even for configurations like --layer-height=0.1 --first-layer-height=0.4 --infill-every-layers=3

**Comment by lordofhyphens** [comment]
Looking at this again, seems like we'd need a new vector version of ConfigOptionFloatOrPercent, liftZ is stored as vector (because different extruder configs). 

Is this still desirable as an option (I know I use firmware retract myself).

**Comment by alexrj** [comment]
Hm, noone else ever requested this feature... also I wonder why I thought it's a good idea. Why would the amount of Z lift change according to layer height?

**Comment by lordofhyphens** [comment]
The one use case  can think of is if you have prints near the maximum Z
 your system supports. You don't want to lift in those situations (as it'd
hit the max).

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
That's already in the codebase though.

The other thing I can think about is maybe there was an assumption that if you did combined infill you'd somehow get into a situation where you'd knock into perimeters? The algorithm for drawing perimeters and infill though means that isn't going to happen, unless you're using combined infill and doing the infill first and you had a really small (~1 perimeter layer height) z lift.

**Comment by alexrj** [comment]
Combined infill is printed like: perimeter --> perimeter --> infill --> perimeter --> perimeter --> infill, so the nozzle is always free in the XY plane. No collisions can ever happen...

**Comment by AxTheB** [comment]
Well I actually fuzzily remember why I opened this issue, and I think it can be safely closed as "fixed by fixing the printer"

**Comment by lordofhyphens** [comment]
:)
