### ISSUE TITLE
internationalization strategy

### ISSUE THREAD

**Issue by Cdriko** [alexrj/Slic3r#789]
Hello, I began a translation of the interface in french here :
 https://github.com/Cdriko/Slic3r
But I think is not a good strategy to translate the soft because interface sentences are in several files
(config.pm, tab.pm etc...)
Did you already imagine a strategy about that ?
or we have to imagine a i18n system ?

**Comment by miharix** [comment]
Anything new about multi language support? (implement .qt files?)
& I can translate it to Slovenian.

**Comment by MartinMeise** [comment]
I think translation would be a big plus for this software as 3D printers are getting below 200$.
I can help with german.

**Comment by gege2b** [comment]
+1
I would help for french translation too

**Comment by Patola** [comment]
This is linked to #1378 and there is even a very old (2013) tentative PR#1214 - and I agree with using gettext instead of XML. Should we close one of these issues as duplicate?

**Comment by lordofhyphens** [comment]
@Patola going to close this one as duplicate, leaving the main thread in #1378.

For other people looking here, branch https://github.com/alexrj/Slic3r/tree/i18n is current place to submit PRs against to add translations for libslic3r strings. As more of the UI is ported to C++, more msgids will get added.

So this will be something of an ongoing effort as new options are made ^^;
