### ISSUE TITLE
Extrusion Axis field is gone in 0.9.5

### ISSUE THREAD

**Issue by sgraber** [alexrj/Slic3r#794]
The Extrusion Axis field is gone in 0.9.5.  From the release notes, it was apparently added in 0.5.4 but for the life of me I cannot find it in 0.9.5.

https://github.com/alexrj/Slic3r/wiki/Online-Help#wiki-printer_section_label

I have to globally replace all extruder gcode references from E's to A's after slicing in order to run Slic3r code on my Cupcake.

**Comment by alexrj** [comment]
Makerbot/makerware G-code flavor was updated in the meanwhile.
