### ISSUE TITLE
Feature Request: Save Plate

### ISSUE THREAD

**Issue by avalero** [alexrj/Slic3r#797]
It would be nice to be able so save a plate configuration: like a printing project. 

I do it currently creating a new STL with all the parts, but it is not exactly the same and it will not be printed the same.

**Comment by Cocacolalover** [comment]
Hi alexrj,

Exporting as AMF works fine but slic3r won't save parameters like object scale.
I think that would be usefull since I send the amf files to people not aware of object scales that could lead to mistakes (I don't know if there are other "not saved" parameters)

Kind regards

**Comment by lordofhyphens** [comment]
Does it work when exporting as stl?

**Comment by Cocacolalover** [comment]
Nops. STL only saves geometric info (triangles)

**Comment by lordofhyphens** [comment]
Could you add a new github issue regarding this? I'd rather open a new, focused issue than reopen an ancient one :)
