### ISSUE TITLE
z axis speed

### ISSUE THREAD

**Issue by smartroad** [alexrj/Slic3r#81]
Is there a setting to control the speed at which the z axis moves at as currently it moves too quick for my huxley

**Comment by totalitarian** [comment]
What if I don't want my zhop speed to be anywhere near as fast as my Z travel speed?

**Comment by lordofhyphens** [comment]
Turn on firmware retraction then. You should be able to specify the Z hop speed separately then. 

That or use a short post-process script to replace the speed.
