### ISSUE TITLE
Feature request: Expand the filament options

### ISSUE THREAD

**Issue by bryanboettcher** [alexrj/Slic3r#814]
I use a large variety of filaments, and each has different settings that it likes for all manner of factors, like temperature and cooling (both implemented in the Filament tab), and other things like retraction and speeds.  These other factors require me to maintain a permutation of settings for my machines as well (like 'm2 pretty - red pla', 'm2 pretty - green pla', in addition to the 'red pla' and 'green pla' filaments being set).  This is because the physical properties of each filament require more changes in the machine than the tabs currently configured will allow.

Would it be possible to not only keep the existing options where they are, and add additional "offset"-type values to the filament tab?  Example, if Retraction speed is set to 40mm/sec on the Machine tab, and Retraction is set to -5mm/sec on the Filament tab, the end result would be a retract speed of 35mm/sec.

Options that I believe should be included:
* Retraction distance
* Retraction speed
* Perimeter speed
* Infill speed
* Bridge speed
* Bridge flow rate

**Comment by lordofhyphens** [comment]
Going to close this, I agree that it's way too easy to over-complicate things.
