### ISSUE TITLE
Auto-angle rectilinear support by using bridge-orientation

### ISSUE THREAD

**Issue by simonkuehling** [alexrj/Slic3r#830]
Since slic3r already calculates the best bridge-infill-angle, maybe rectilinear support for bridges could also be auto-angled like this?
At the moment i am sometimes unable to choose an appropriate angle for support when an object has many bridges in every possible orientation.

(I think i have read this idea somewhere, but i could not find an issue for that so i open a new one)

**Comment by lordofhyphens** [comment]
Bridges, if they were printed right, should be able to be unsupported.

I believe that any support generated for them is a bug, evidenced by the "don't support bridges" option. 

If the bridge detection code worked then I could see a reason  to try to reduce the amount of support (basically bisecting the bridge with support pillars until some maximum length threshold is met).

**Comment by lordofhyphens** [comment]
I'm going to close this and suggest that further discussion moves to #1925 as there is an option to turn on/off bridge support and I think the original question was answered.
