### ISSUE TITLE
Memory overflow crash/system freeze

### ISSUE THREAD

**Issue by epengr** [alexrj/Slic3r#840]
Using both 0.9.5 and 0.9.7 x64, trying to slice any of these stp files:

http://www.thingiverse.com/thing:18214  (minute wheel.stp is a good example)

results in sli3r filling all free physical memory (~4GB in my case), and the system freezing while "Processing triangulated mesh".

Trying the same slice with the 0.9.7 x86 version doesn't freeze the system, but produces this error:

MS VC++ Runtime Library:
"This application has requested the Runtime to terminate it in a unusual way."

Slic3r does give an error on loading the stp that it's non-manifold with hole near edge 0.00-1.00, but it does so with most files, even directly exported from SolidWorks.  Repairing it with NetFab doesn't eliminate that error.   Importing into SolidWorks, healing it and exporting it results in the same error but with a "hole" at  1.00-2.00.

Slic3r will successfully process many files despite the about error.

Skeinforge will slice these files without error.

Slic3r 0.7.1 that's integrated into Pronterface seems to handle these files okay.  (Still reports non-manifold.)

Windows 7 Ultimate SP1
AMD Athlon 64 x2 6000+
6GB memory

=======================config.ini======================

# generated by Slic3r 0.9.6-dev on Fri Nov 30 22:36:06 2012
acceleration = 0
bed_size = 175,170
bed_temperature = 0
bottom_solid_layers = 2
bridge_fan_speed = 100
bridge_flow_ratio = 1
bridge_speed = 60
brim_width = 0
complete_objects = 0
cooling = 0
disable_fan_first_layers = 1
duplicate = 1
duplicate_distance = 6
duplicate_grid = 1,1
end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors
external_perimeter_speed = 100%
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extruder_offset = 0x0
extrusion_axis = E
extrusion_multiplier = 1
extrusion_width = 0
fan_always_on = 0
fan_below_layer_time = 60
filament_diameter = 2.9
fill_angle = 45
fill_density = 0.25
fill_pattern = rectilinear
first_layer_bed_temperature = 0
first_layer_extrusion_width = 200%
first_layer_height = 0.35
first_layer_speed = 50%
first_layer_temperature = 185
g0 = 0
gcode_arcs = 0
gcode_comments = 0
gcode_flavor = reprap
infill_acceleration = 50
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0
infill_speed = 60
layer_gcode = 
layer_height = 0.25
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 10
min_skirt_length = 0
notes = 
nozzle_diameter = 0.35
only_retract_when_crossing_perimeters = 1
output_filename_format = [input_filename_base].gcode
perimeter_acceleration = 25
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 45
perimeters = 2
post_process = 
print_center = 87.5,85
randomize_start = 1
retract_before_travel = 5
retract_length = 1
retract_length_toolchange = 3
retract_lift = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 30
rotate = 0
scale = 1
skirt_distance = 6
skirt_height = 1
skirts = 1
slowdown_below_layer_time = 15
small_perimeter_speed = 45
solid_fill_pattern = rectilinear
solid_infill_below_area = 70
solid_infill_every_layers = 0
solid_infill_speed = 60
start_gcode = G28 ; home all axes
support_material = 0
support_material_angle = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_pattern = rectilinear
support_material_spacing = 2.5
support_material_threshold = 45
temperature = 185
threads = 2
top_solid_infill_speed = 60
top_solid_layers = 2
travel_speed = 60
use_relative_e_distances = 0
z_offset = 0

**Comment by lordofhyphens** [comment]
Closing, as it was the model's fault (when model is garbage, all bets are off).
