### ISSUE TITLE
Support for older glibc linux?

### ISSUE THREAD

**Issue by ericu** [alexrj/Slic3r#861]
On the current Debian stable distro [squeeze], you can't run the prebuilt binaries.  They're linked against glibc 2.14, which is just a bit newer than Debian's glibc.  If you're not actually using any brand-new features, you can link against an older glibc, and then your package should run on both older and newer systems.

I should mention that I've worked around this for myself, by building from source, but it took a little hackery due to some perl issues.  It would be really nice to be able just to download and run, and Debian Squeeze is hardly ancient or obscure.

"bin/slic3r: /lib/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/Slic3r/bin/../dll/libperl.so)"

**Comment by lordofhyphens** [comment]
Squeeze is pretty ancient at this point, so is Wheezy.

I have a Debian package for Jessie and the sources are available to build your own debian package (which is how I recommend installing Slic3r on a debian system to avoid cpan hell). 

Going to close.
