### ISSUE TITLE
At low infill rates, progressively increase infill solidity before top layers

### ISSUE THREAD

**Issue by Pointedstick** [alexrj/Slic3r#87]
Using a very low infill rate like 5 or 10% is great for non-structural parts because it allows you to print quickly, but the top layer often comes out poorly unless you set the number of solid layers very high; usually about 3 or 4. This ends up being rather wasteful. How about this instead… at low infill levels (say, 20% and below), Slic3r can progressively begin to increase the infill solidity a few layers before the top solid layers so they can be well supported.  This will let you reduce the number of solid layers to 2 or even 1 and still get a nice top surface finish. It could do like a 30% solid layer and then a 60% solid layer, and then the final top layer would come out perfect!

**Comment by lordofhyphens** [comment]
I'm going to close this, as it is generally served by #240. If you end up having a PR to address this yourself and make it an option this can be reopened. Also, it's 2 years old.
