### ISSUE TITLE
Narrow gap filling ability causes problems in narrow bridges

### ISSUE THREAD

**Issue by ttsalo** [alexrj/Slic3r#887]
In 0.9.7, with track width of 0.6, layer height 0.3, 3 perimeters (can provide full config if needed to reproduce), the narrow bridges such as used in the Ultimate Calibration Test are not generated correcly (saw also the same issue in a different design, so it's not related to just this object). 

The attached image shows the first layer of the first bridge (in the middle). Instead of straight bridge tracks, the zigzag infill is used even for the first bridge layer. As a result, most of the infill fails to attach to the bridge's single perimeter tracks and droops down.

For wider bridges, the correct bridge infill seems to be generated.

The STL is from this thing: http://www.thingiverse.com/thing:9804

![UltiCalibTest](https://f.cloud.github.com/assets/1005351/36113/bd59af2e-52cf-11e2-96bd-20a36dfd58f3.png)

**Comment by lordofhyphens** [comment]
Should be fixed in 1.3.0-dev.
