### ISSUE TITLE
Feature Request: Bundle a Calibration Feature into Slic3r

### ISSUE THREAD

**Issue by IdolCrasher** [alexrj/Slic3r#893]
Good Day All,

I am sure you all have your own process for calibrating Slic3r's settings.  I certainly have my own process down to an art/science.  I have a number of models (STLs) on hand that I use to dial in settings for single-wall width, retraction, and maybe someday after support structure is working nicely, I will keep STLs on hand to dial in support structure as well.

I recommend that a process for dialing in your Slic3r settings be built into Slic3r itself.  

Implementing the feature could start simply; a text file with explanations and some STLs; but that could grow into a full GUI driven wizard that makes recommendations based on results of your prints.

I think this would get new folks very interested in Slic3r and would make the Slic3r community grow.

This would fit nicely the current theme that "Slic3r is Nicer" (easier and friendlier) than other slicing programs.

Thanks for your thoughts,

Best Regards,

Adam

**Comment by lordofhyphens** [comment]
This will probably will never actually happen (at least from an effort by @alexrj or other developers here). You are welcome to start a series of instructions and models to start this yourselves though :) 

If it gets done, open up a new issue and we'll figure out how to link it properly to slic3r.
