### ISSUE TITLE
Feature Request: N solid infill layers every X layers

### ISSUE THREAD

**Issue by llluis** [alexrj/Slic3r#899]
This would be used along with the "Solid infill every" parameter.
It would be nice to specify how many layers to be solid instead of only one.

Every time I am printing big objects with low infill, only one solid layer is not enough. The layer is too sparse and not filled. If it was at least 2 layers, the infill would be effective.

Thanks in advance.
Best regards.

**Comment by lordofhyphens** [comment]
I've created a script for to generate a modifier mesh via OpenSCAD, which should let you do what you want.
