### ISSUE TITLE
Update bridging algorithm to start on areas of more support rather than less if possible.

### ISSUE THREAD

**Issue by dublo7** [alexrj/Slic3r#906]
I tried printing a hypercube using Slic3r on a model I have printed well before.  The bridging didn't work out so well compared to other slicing programs I've used.  

Get STL file from here: http://www.thingiverse.com/thing:9728

The problem was the inner cube bridge started in the center where there was only the smallest of support available because it was being bridged from the tips of the diagonal supports.  This caused the first line of the lower inner cube to be a bunch of spaghetti plastic.

If possible please tweak the algoritm to make sure it starts somewhere there is enough support underneath.  I know this is easier said than done, but something to try to figure out if possible.  

If the gcode would have gone outside in, then the print would have turned out OK on the bottom.  Seems to be working OK otherwise.

**Comment by lordofhyphens** [comment]
Could you check to see if this is still a problem on 1.2.9 or 1.3.0-dev? Going to close for now, reopen if you see issues.
