### ISSUE TITLE
Multiple Extruder: Dont heat up extruders that are not used 

### ISSUE THREAD

**Issue by pi-ratte** [alexrj/Slic3r#931]
In my setup i have 2 extruders.
If i set in  Print/settings/Multiple extruders. All types to the same extruder, Slicer should not heat up + Skirt the other extruders.
At the moment it heats up both extruders and does a skirt on both.

Howto reproduce: Just slice anything with a 2 extruder setup and check the gcode, you will see   : M109 S186 T0 ; wait for temperature to be reached
M109 S186 T1 ; wait for temperature to be reached

OS: win7 running from source.
Slicer version:   0.9.9-dev  (65ef3b35d9350a3a9843c1a40800f491c7ea9941)

**Comment by alexrj** [comment]
This was done in the mean time! :)
