### ISSUE TITLE
Brim should follow small perimeter speed adjustment where necessary

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#943]
A brim on a small piece does not follow the small perimeter logic. Both small perimeter and first layer speed (and flow?) adjustments should be applied to the brim (and skirt, I guess) as well.

**Comment by lordofhyphens** [comment]
@kefir- if this is still a problem for you, please reopen and provide a repeatable test case (config/stl). I haven't seen this as a problem for me in my prints, so...
