### ISSUE TITLE
New infill and Gap-Fill Method.

### ISSUE THREAD

**Issue by pi-ratte** [alexrj/Slic3r#949]
I have a new idea for a new kind of infill and gapfill. Please let me know what you think of it.
Its based on the idea that its possible to influence the extrusion width.
If we give for example infill a min/default/max value 
For a 0.5 nozzle for example:

Layer Height = 0.3
Min =
	Width Over Height 2.0
	Line Width =0.6

Default
	Width Over Height 2.2
	Line Width =0.66

Max = 
	Width Over Height 2.90
	Line Width =0.87
	(calculations done with = http://calculator.josefprusa.cz/) Thanks ! :]

Infil: 
Now if we can influence the line width a simple infill would be to start with the smallest possible and each adjacent line would be a bit bigger causing a kind of wave effect. See Pic.
![wave v1](https://f.cloud.github.com/assets/3269311/95515/06407c7a-6673-11e2-974d-d2bc5c837b71.jpg)
(v1. .6 .65 .70 .75 .80 .85 .87 .6 .65 .70 .75 .80 .85 .87  .6 .65 .70 .75 .80 .85 .87)

![wave v2](https://f.cloud.github.com/assets/3269311/95517/17d079fe-6673-11e2-9539-6b2da883bb31.jpg)
(v2. .6 .65 .70 .75 .80 .85 .87  .87 .85 .80 .75 .70  .65 .6 .6 .65 .70 .75 .80 .85 .87  .87 .85 .80 .75 .70  .65 .6 )

That would be a simple version. Another one would be to make a thick/thin/thick/thin..... line and the adjacent infill would then be alternating the thickness. See pic.
![alternate](https://f.cloud.github.com/assets/3269311/95521/33a28c6c-6673-11e2-87c3-523040fd473b.jpg)
Alternating every 5mm between 0.6 and 0.87

Gap fill.
At the moment when slicer fills gaps it makes the printer do its little zigzag dance. And sometimes leves holes in concentric object(rectlinear) or makes to 2 perimeter shells that dont connect (concentric),im planning to do a bug report on concentric objects. So the idea is that instead of doing the zigzag dance, move down the center and increase the extrusion width (or reduce it if we need to add an extra line). If the additional width alone is not enuf then the adjacent perimeters/infill can also be increased or reduced(to add an extra line) so that all walls and infill touch.

It could also be used to fill into tight corners. By reducing the extrusion width when coming into the corner. And at the end drop a little bit extra and dive the extruder out over the corner.so that the filament is pushed down and into the hole. 

Im not doing pics for these at the moment (if you want them request it.).

Well let me know what you think. Since I dont know how the coding in slicer works. I have no idea how much work this would be. I thinks its a cool idea that would reduce the zigzag gap fills, speeding up print time.  And it would make a new kind of infill that has a lot of potential for variations (If one could drops scripts in or have parameters to tweek to choose the pattern).

**Comment by lordofhyphens** [comment]
Gap fill has been implemented and works pretty well now in 1.3.0-dev. It has also been "some time". Closing :)
