### ISSUE TITLE
E-Value Steps Per MM Changes With Extrusion Speeds, Can Be Adjusted For With Formula

### ISSUE THREAD

**Issue by Macgyverzboss** [alexrj/Slic3r#955]
Although my printer technically can print fast the inertia from the moving mass is enough to create jerk resulting in rounded rectangles. I've overcome this by printing slow for the perimeters and fast for the infill. As I started doing this I noticed that my parts were not dimensionally accurate where parts that fit inside other parts where too big. I calibrated my printer for the slow perimeter speed and the parts printed perfect. My infill though seemed to be too little than what it should have been. I then noticed that my E value for the Extruder Motor Steps changed based on the extruder motor's speed. I did a thorough calibration test recording at different intervals of extruder speed what the E value would have to be to extrude the correct length. I measured 149 mm of raw filament and marked with a fine tip permanent marker. Using Repetier Host to control my 3d printer I set the extrusion speed to 10mm/s and the extrude length to 149. Same as what I marked on the raw filament. I then hit extrude and waited for it to finish and marked where the filament stopped. I then compared where it should have stopped to where it stopped with a caliper. I then calculated how much it extruded, (Difference in Length) + (Fixed Length) = (Actual Length). (-4.5) + (149) = (144.5). I then calculated what the E value steps needed to be to extrude the proper amount. (Fixed Steps) x (Actual Length) / (Fixed Length) = (Actual Steps). (712) x (144.5) / (149) = (690.49....). Repeating this for each speed of 10mm/s, 30mm/s, 50mm/s, 70mm/s, 90mm/s. I then plotted the extrusion speed to the actual steps for that speed on a graphing calculator. The scatter plot indicates a linear function. I solved the function and the formula is Y = .75x + 681. I know that this specific equation will not be the same for other printers. It is unique to the hardware setup for my printer. For other printers the same process I did would have to be done to calculate the unique formula for their extruder system. I use a geared extruder with 3mm filament. In theory the 681 represents the steps per millimeter without any force from the extruder. As the speed increases more force is pushing back on the motor resulting in the motor having to turn more to retain the same movement.That is where the .75x accounts for the extra steps to compensate the extra force. 
![A Graph and Chart](https://f.cloud.github.com/assets/3026684/99497/7620b69a-6772-11e2-8d26-b7c29762ab2e.png)
![A Scatterplot](https://f.cloud.github.com/assets/3026684/99494/36aad09a-6772-11e2-8112-c7bde6f4cf54.png)

The solution would be a script that uses the formula unique to each printer's hardware to change the firmwares E value as the slicer changes from perimeters to infill and the other types of speed changes. For perimeters I have it set for 40mm/s and infill at 70mm/s. The script would then have to change the E value to 711 when it prints the perimeters and change the E value to 733.5 when it prints the infill. It could be an optional feature that requires input to be enabled. The input could be in the form of ax+b, what is A and B? or it could be to input the speed and relative E value for multiple speeds and the program calculate the linear regression from those values. I know there must be a way to do this for cura controls the E value when it slices. Without this feature prints that have large differences in speed from perimeter, small perimeter, infil, bridges, gap fill will not extrude the correct plastic for each setting.
 Example: Perimeters 40mm/s, Gap fill 20mm/s, infill 70mm/s. 
- If i set the E value relative to the 40mm/s The gap fill will be wider than it is suppose to and the infill will be smaller than it is suppose to resulting in a weaker part, but accurate dimensionally. Nut and bolt parts would work. 
- If i set the E value relative to the 70mm/s infill the gap fill and perimeter infill will be wider than it is suppose to resulting in a strong part but inaccurate dimensionally. Nut and bolt parts would not work.

**Comment by kyrreaa** [comment]
I just like to mention in this thread that there indeed are effects that make the extruder e-steps change with pressure.

For one, the depth at wich the hobbed bolt engages the filament may change due to the geometry and angle of the pressure. In my extruder (modified Wades design with much more guide to filament) I have noticed that it indeed bites deeper when pressure goes up and this in turn reduces the apparent radius and so e-steps go up.

Secondly, harder and softer filaments will get a different depth of grip again causing same change as above.

I do not think filament deformation from pressure is part of it though as there is no pressure on the filament not already engaged by a tooth. Only once a tooth has a firm grip will force be applied and filament pushed forwards by that grip.

**Comment by lordofhyphens** [comment]
In any case, I don't think this is something that should be fixed in the slicer -- should probably be approximated to be "close enough" in esteps and if you want it to be exact add some measurement mechanism. I'm going to close this and add a label so we can find it later.

**Comment by orcinus** [comment]
Sweet mother of necro...

**Comment by lordofhyphens** [comment]
@orcinus That's what happens when I actively am looking for stuff to close and clean up the issue tracker. :) Glad someone is reading.

**Comment by orcinus** [comment]
Anyway, while i'm here...

> any case, I don't think this is something that should be fixed in the slicer -- should probably be approximated to be "close enough" in esteps and if you want it to be exact add some measurement mechanism. I'm going to close this and add a label so we can find it later.

That's not quite the solution for the original issue - which was dimensional inaccuracy of *some* features in a print, dependent on the relative speed (extrusion rate) within the same print. I think the originally proposed solution was to scale extrusion rate with speed (linear scaling of Esteps with speed, based on some fudge factor).

”Static” fudging of Esteps won't help with that.

**Comment by orcinus** [comment]
(Although ideally, this is something the firmware should be doing.)
