### ISSUE TITLE
Loading an AMF file results in a crash with the latest build

### ISSUE THREAD

**Issue by funbart** [alexrj/Slic3r#972]
Hi,
when trying to load an AMF file into eae1e7adc2162e13c61a4136a6c7ede6bdc34102 it results in a direct crash. Same with a new generated AMF file.
Loading the same AMF file into 0.9.8 has no problem and generates ok.
I'm on windows 7 x64.
config, amf ans stls posted on:
http://forums.reprap.org/read.php?263,181270.
Bart

**Comment by Darker** [comment]
You could've shared how did you install those dependencies because I have the same problem.
