### ISSUE TITLE
do_install on Xubuntu throws Error

### ISSUE THREAD

**Issue by garyhodgson** [alexrj/Slic3r#988]
When I run bin/do_install on Xubuntu (12.04) I get the following Error:

    Fatal Error: Installer Error : The installer cannot find the application binaries to extract. at /home/garyhodgson/Desktop/Slic3r/lib/std/cavaexecscript/cpwxinstaller.pl line 1572

I notice that Slic3r/lib/std/cavaexecscript does not exist.  

Running bin/slic3r works fine.

**Comment by lordofhyphens** [comment]
1) Probably not a problem anymore.
2) Making a ubuntu package is a better solution (feel free to use my fork/branch as a base, or get a copy from prusa3d.com).
