### ISSUE TITLE
Request for Comments: rename "Infill every n layers" to "Combine infill" and remove numeric input

### ISSUE THREAD

**Issue by alexrj** [alexrj/Slic3r#992]
As of c9b506fa02bf037126e8e47e69b476c554ad2b70 the *Infill every 'n' layers* option uses a new simplified and more robust algorithm.

Many users miss the purpose and behavior of this feature, thinking that it would simply skip infill on some layers. Also, the numeric input might be scary or tricky to setup because it requires some layer height math which might be unclear for some people.

My proposal is to turn the option into a simple checkbox (on/off). When enabled it should try to combine infill across the highest number of layers allowed by the configured nozzle diameter (basically it will infill every `floor(nozzle_diameter/layer_height)` layers). I don't see any advantage for having this configurable, as everybody will just set it to the maximum allowed number.

The new name could be *Combine infill*.  Another option could be *Microlayering* which was used by Adrian Bowyer, but I'm afraid the word describes the other way around and could be confusing. Do you have any ideas?

I think this option could be even enabled by default in the future.

**Comment by lordofhyphens** [comment]
I'd rather leave it the way it is. Is this still something people want to talk about? If not, I'd like to close this issue.

**Comment by lordofhyphens** [comment]
Closing this as it's been ~2years. If someone wants to reopen it, by all means do.
