### ISSUE TITLE
pb with brim

### ISSUE THREAD

**Issue by jfpion** [alexrj/Slic3r#996]
when you ask for a brim (in my case 6mm) if your stl has a circular thin wall 8 mm diameter you got strange brim resulting with a blob : 
![brim pb](https://f.cloud.github.com/assets/1093595/152235/b7e4e61c-75bb-11e2-9c6e-4488241d8a2c.JPG)

in my stl i have 2 concentric thin walls acting as support for a cylindrical form uspide.

the outside wall got the brim ok but the inside got the brim inside the circular thin wall (i don't really care i could have been the other side) but the brim is quite strange 

thank you for advice

**Comment by lordofhyphens** [comment]
Looks fixed to me.
